Repository elastic/beats, pull requests merged in 2019-11, with the labels that each got.

#14366 ca cannot be used as a shorthand
  x-pack/agent/pkg/agent/cmd/enroll.go
Labels: fleet

#14325 GA the script processor
  CHANGELOG.next.asciidoc
  libbeat/docs/processors-using.asciidoc
Labels: docs, libbeat, review

#14367 revisiting sample configuration and bringin it up to date
  x-pack/agent/_meta/common.p2.yml
  x-pack/agent/agent.yml
Labels: fleet

#14326 GA the Winlogbeat Sysmon module
  CHANGELOG.next.asciidoc
  winlogbeat/docs/modules/sysmon.asciidoc
  x-pack/winlogbeat/module/sysmon/_meta/docs.asciidoc
Labels: Team:SIEM, docs, review

#14313 [Monitoring] Use op_type = create with ES version >= 7.5.0
  libbeat/monitoring/report/elasticsearch/client.go
Labels: Stack monitoring, in progress, libbeat, v7.5.1, v7.6.0, v8.0.0

#14205 Fingerprint processor
  CHANGELOG.next.asciidoc
  libbeat/docs/processors-using.asciidoc
  libbeat/processors/fingerprint/config.go
  libbeat/processors/fingerprint/encode.go
  libbeat/processors/fingerprint/errors.go
  libbeat/processors/fingerprint/fingerprint.go
  libbeat/processors/fingerprint/fingerprint_test.go
  libbeat/processors/fingerprint/hash.go
Labels: :Processors, enhancement, libbeat, review, v7.6.0, v8.0.0

#14324 Libbeat: Add support for API keys in Elasticsearch outputs
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  auditbeat/auditbeat.yml
  filebeat/filebeat.reference.yml
  filebeat/filebeat.yml
  heartbeat/heartbeat.reference.yml
  heartbeat/heartbeat.yml
  journalbeat/journalbeat.reference.yml
  journalbeat/journalbeat.yml
  libbeat/_meta/config.reference.yml.tmpl
  libbeat/_meta/config.yml.tmpl
  libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
  libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
  libbeat/docs/monitoring/shared-monitor-config.asciidoc
  libbeat/docs/security/api-keys.asciidoc
  libbeat/docs/security/securing-beats.asciidoc
  libbeat/monitoring/report/elasticsearch/config.go
  libbeat/monitoring/report/elasticsearch/elasticsearch.go
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/elasticsearch/config.go
  libbeat/outputs/elasticsearch/elasticsearch.go
  metricbeat/metricbeat.reference.yml
  metricbeat/metricbeat.yml
  packetbeat/packetbeat.reference.yml
  packetbeat/packetbeat.yml
  winlogbeat/winlogbeat.reference.yml
  winlogbeat/winlogbeat.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/auditbeat/auditbeat.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/filebeat.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/functionbeat/functionbeat.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/metricbeat.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.yml
Labels: libbeat, review

#14307 Docs: Fix monitoring privileges
  libbeat/docs/security/users.asciidoc
Labels: docs, review

#14373 [7.5] Flaky test `test_beat.test_xpack`: try increasing timeout (#14250)
  metricbeat/tests/system/test_beat.py
Labels: backport

#14377 [7.5][DOCS] Backport: Use shared versions (#14080)
  auditbeat/docs/getting-started.asciidoc
  auditbeat/docs/index.asciidoc
  auditbeat/docs/running-on-kubernetes.asciidoc
  dev-tools/promote_docs
  docs/devguide/index.asciidoc
  filebeat/docs/index.asciidoc
  filebeat/docs/running-on-kubernetes.asciidoc
  heartbeat/docs/index.asciidoc
  journalbeat/docs/getting-started.asciidoc
  journalbeat/docs/index.asciidoc
  libbeat/docs/command-reference.asciidoc
  libbeat/docs/index.asciidoc
  libbeat/docs/outputs/output-logstash.asciidoc
  libbeat/docs/repositories.asciidoc
  libbeat/docs/shared-beats-attributes.asciidoc
  libbeat/docs/shared-brew-install.asciidoc
  libbeat/docs/shared-docker.asciidoc
  libbeat/docs/shared-template-load.asciidoc
  libbeat/docs/upgrading.asciidoc
  libbeat/docs/version.asciidoc
  metricbeat/docs/gettingstarted.asciidoc
  metricbeat/docs/index.asciidoc
  metricbeat/docs/running-on-kubernetes.asciidoc
  packetbeat/docs/gettingstarted.asciidoc
  packetbeat/docs/index.asciidoc
  packetbeat/docs/packetbeat-options.asciidoc
  winlogbeat/docs/index.asciidoc
  x-pack/functionbeat/docs/index.asciidoc
Labels: backport, docs, v7.5.0

#14383 Add missing testing.Init calls
  x-pack/heartbeat/main_test.go
  x-pack/journalbeat/main_test.go
  x-pack/packetbeat/main_test.go
  x-pack/winlogbeat/main_test.go
Labels: review

#14380 [7.4][DOCS] Backport: Change structure of section about security settings for monitoring (#…
  libbeat/docs/security/users.asciidoc
Labels: backport, docs, v7.4.0

#14381 [7.5][DOCS] Backport: Change structure of section about security settings for monitoring (#…
  libbeat/docs/security/users.asciidoc
Labels: backport, docs, v7.5.0

#13981 Add state field for connection metricset from RabbitMQ module (#13697) #WIP
  metricbeat/docs/fields.asciidoc
  metricbeat/module/rabbitmq/connection/_meta/data.json
  metricbeat/module/rabbitmq/connection/_meta/fields.yml
  metricbeat/module/rabbitmq/connection/_meta/testdata/docs.json-expected.json
  metricbeat/module/rabbitmq/connection/data.go
  metricbeat/module/rabbitmq/fields.go
Labels: :integrations, Metricbeat, [zube]: In Review, enhancement, module

#14268 Cherry-pick #14259 to 7.4: Fix cleanup when autodiscover pods are terminated
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
Labels: :integrations, [zube]: Done, backport, review

#14391 [Metricbeat] Fix cloudwatch metricset copying address in for loop
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Labels: :integrations, Metricbeat, bug, v7.5.0, v7.6.0

#14333 [libbeat] Fix documentation of output.kafka.key
  libbeat/docs/outputs/output-kafka.asciidoc
Labels: docs, libbeat, needs_backport

#14393 Cherry-pick #14391 to 7.x: [Metricbeat] Fix cloudwatch metricset copying address in for loop
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Labels: backport, review

#14392 Cherry-pick #14391 to 7.5: [Metricbeat] Fix cloudwatch metricset copying address in for loop
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Labels: backport, review

#14397 Add missing header to table in CEF processor docs
  libbeat/docs/processors-using.asciidoc
Labels: docs, review

#14135 [Metricbeat] VSphere module dashboards
  CHANGELOG.next.asciidoc
  metricbeat/docs/images/metricbeat_vsphere_dashboard.png
  metricbeat/docs/images/metricbeat_vsphere_vm_dashboard.png
  metricbeat/docs/modules/vsphere.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/module/vsphere/_meta/docs.asciidoc
  metricbeat/module/vsphere/_meta/kibana/7/dashboard/metricbeat-vsphere-host.json
  metricbeat/module/vsphere/_meta/kibana/7/dashboard/metricbeat-vsphere-vm.json
  metricbeat/module/vsphere/module.yml
Labels: :Dashboards, :integrations, Metricbeat, [zube]: In Review, review

#14359 [Filebeat] Race condition fix in S3 input plugin
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/s3/input.go
Labels: :integrations, Filebeat, bug, needs_backport

#14401 Cherry-pick #14359 to 7.x: [Filebeat] Race condition fix in S3 input plugin
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/s3/input.go
Labels: backport, review

#14402 Cherry-pick #14359 to 7.5: [Filebeat] Race condition fix in S3 input plugin
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/s3/input.go
Labels: backport, review

#14372 [7.5] [Monitoring] Use op_type = create with ES version >= 7.5.0 (#14313)
  libbeat/monitoring/report/elasticsearch/client.go
Labels: backport

#14374 Remove beta flag for some filebeat modules
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/cisco.asciidoc
  filebeat/docs/modules/panw.asciidoc
  x-pack/filebeat/module/cisco/README.md
  x-pack/filebeat/module/cisco/_meta/docs.asciidoc
  x-pack/filebeat/module/coredns/README.md
  x-pack/filebeat/module/envoyproxy/README.md
  x-pack/filebeat/module/iptables/README.md
  x-pack/filebeat/module/panw/README.md
  x-pack/filebeat/module/panw/_meta/docs.asciidoc
  x-pack/filebeat/module/suricata/README.md
  x-pack/filebeat/module/zeek/README-developer.md
  x-pack/filebeat/module/zeek/README.md
Labels: Filebeat, module, review

#14010 [Filebeat] Select output index based on the source input
  CHANGELOG.next.asciidoc
  filebeat/beater/filebeat.go
  filebeat/channel/connector.go
  filebeat/channel/connector_test.go
  filebeat/channel/factory.go
  filebeat/docs/inputs/input-common-options.asciidoc
  filebeat/input/input.go
  filebeat/kafka.yml
  libbeat/common/fmtstr/formattimestamp.go
  libbeat/common/fmtstr/formattimestamp_test.go
  libbeat/idxmgmt/ilm/ilm.go
  libbeat/idxmgmt/std.go
Labels: Filebeat, needs_backport

#14271 Convert ticks to milliseconds for diskio metricset
  CHANGELOG.next.asciidoc
  metricbeat/module/system/diskio/diskstat_windows_helper.go
Labels: :integrations, Metricbeat, [zube]: In Review

#14405 Skip flaky test: test_beat.Test.test_xpack
  metricbeat/tests/system/test_logstash.py
Labels: flaky-test, needs_backport, review, v7.5.1, v7.6.0, v8.0.0

#14403 Agent: updated transpile rules for metricbeat
  x-pack/agent/magefile.go
  x-pack/agent/pkg/agent/program/supported.go
  x-pack/agent/pkg/agent/program/testdata/single_config-metricbeat.yml
  x-pack/agent/pkg/agent/program/testdata/single_config.yml
  x-pack/agent/spec/metricbeat.yml
Labels: fleet

#14418 Cherry-pick #13905 to 7.4: [Libbeat]Kubernetes: fix statefulset watcher typo
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/watcher.go
Labels: backport, review

#14427 Replace certs with a 20 year expiry
  heartbeat/monitors/active/http/testdata/client_cert.pem
  heartbeat/monitors/active/http/testdata/client_key.pem
  heartbeat/monitors/active/http/testdata/openssl_command.txt
Labels: :Testing, Heartbeat, needs_backport

#14378 Convert license struct to MapStr
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/cluster_stats/data_xpack.go
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/test_elasticsearch.py
Labels: Stack monitoring, bug, review, v6.8.5, v7.5.1, v7.6.0, v8.0.0

#14429 [7.x] Replace certs with a 20 year expiry (#14427)
  heartbeat/monitors/active/http/testdata/client_cert.pem
  heartbeat/monitors/active/http/testdata/client_key.pem
  heartbeat/monitors/active/http/testdata/openssl_command.txt
Labels: backport

#14430 [7.5] Replace certs with a 20 year expiry (#14427)
  heartbeat/monitors/active/http/testdata/client_cert.pem
  heartbeat/monitors/active/http/testdata/client_key.pem
  heartbeat/monitors/active/http/testdata/openssl_command.txt
Labels: backport

#14369 Move light modules to OSS
  CHANGELOG-developer.next.asciidoc
  metricbeat/beater/metricbeat.go
  metricbeat/cmd/root.go
  metricbeat/mb/lightmodules.go
  metricbeat/mb/lightmodules_test.go
  metricbeat/mb/testdata/lightmodules/broken/module.yml
  metricbeat/mb/testdata/lightmodules/empty/.placeholder
  metricbeat/mb/testdata/lightmodules/service/metricset/manifest.yml
  metricbeat/mb/testdata/lightmodules/service/module.yml
  metricbeat/mb/testdata/lightmodules/service/nondefault/manifest.yml
  x-pack/metricbeat/beater/metricbeat.go
  x-pack/metricbeat/cmd/root.go
  x-pack/metricbeat/module/aws/ebs/ebs_test.go
  x-pack/metricbeat/module/aws/elb/elb_test.go
  x-pack/metricbeat/module/cockroachdb/status/status_integration_test.go
  x-pack/metricbeat/module/cockroachdb/status/status_test.go
  x-pack/metricbeat/scripts/msetlists/main.go
Labels: :integrations, Metricbeat, [zube]: In Review, review, x-pack

#14347 [Metricbeat] Add more TCP states for socket_summary
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/fields.go
  metricbeat/module/system/socket_summary/_meta/fields.yml
  metricbeat/module/system/socket_summary/socket_summary.go
  metricbeat/module/system/socket_summary/socket_summary_test.go
Labels: :integrations, [zube]: In Review, enhancement

#14469 Cherry-pick #14329 to 7.4: [Metricbeat]Kubernetes: add nil check for kubernetes parent object check
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/metadata.go
  libbeat/common/kubernetes/metadata_test.go
Labels: :integrations, [zube]: In Review, backport, review

#14431 Cherry-pick #14329 to 7.5: [Metricbeat]Kubernetes: add nil check for kubernetes parent object check
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/metadata.go
  libbeat/common/kubernetes/metadata_test.go
Labels: :integrations, [zube]: In Review, backport, review

#14394 Ensure that init containers are no longer tailed after they stop
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
  libbeat/autodiscover/providers/kubernetes/kubernetes_test.go
Labels: :integrations, [zube]: In Review, bug, containers, needs_backport

#14477 Cherry-pick #14394 to 7.x: Ensure that init containers are no longer tailed after they stop
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
  libbeat/autodiscover/providers/kubernetes/kubernetes_test.go
Labels: :integrations, [zube]: In Review, backport, review

#14476 Cherry-pick #14394 to 7.5: Ensure that init containers are no longer tailed after they stop
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
  libbeat/autodiscover/providers/kubernetes/kubernetes_test.go
Labels: :integrations, [zube]: In Review, backport, review

#14424 Remove add_docker_metadata from Functionbeat configuration
  dev-tools/mage/config.go
  libbeat/_meta/config.yml.tmpl
  x-pack/functionbeat/functionbeat.yml
  x-pack/functionbeat/scripts/mage/config.go
Labels: Functionbeat, needs_backport, review

#14475 Cherry-pick #14369 to 7.x: Move light modules to OSS
  CHANGELOG-developer.next.asciidoc
  metricbeat/beater/metricbeat.go
  metricbeat/cmd/root.go
  metricbeat/mb/lightmodules.go
  metricbeat/mb/lightmodules_test.go
  metricbeat/mb/testdata/lightmodules/broken/module.yml
  metricbeat/mb/testdata/lightmodules/empty/.placeholder
  metricbeat/mb/testdata/lightmodules/service/metricset/manifest.yml
  metricbeat/mb/testdata/lightmodules/service/module.yml
  metricbeat/mb/testdata/lightmodules/service/nondefault/manifest.yml
  x-pack/metricbeat/beater/metricbeat.go
  x-pack/metricbeat/cmd/root.go
  x-pack/metricbeat/module/aws/ebs/ebs_test.go
  x-pack/metricbeat/module/aws/elb/elb_test.go
  x-pack/metricbeat/module/cockroachdb/status/status_integration_test.go
  x-pack/metricbeat/module/cockroachdb/status/status_test.go
  x-pack/metricbeat/scripts/msetlists/main.go
Labels: backport, review

#14425 [7.x] Skip flaky test (#14405)
  metricbeat/tests/system/test_logstash.py
Labels: backport

#14384 Update Go to 1.13.4
  .go-version
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: review

#14471 [Filebeat] Decode hex values in auditd log messages
  CHANGELOG.next.asciidoc
  filebeat/module/auditd/log/ingest/pipeline.json
  filebeat/module/auditd/log/ingest/pipeline.yml
  filebeat/module/auditd/log/manifest.yml
  filebeat/module/auditd/log/test/test.log
  filebeat/module/auditd/log/test/test.log-expected.json
Labels: Filebeat, Team:SIEM, needs_backport, review

#14488 [DOCS] Add temporary file needed by doc build
  libbeat/processors/actions/docs/placeholder.asciidoc
Labels: docs, review

#14473 [7.5] Convert license struct to MapStr (#14378)
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/cluster_stats/data_xpack.go
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/test_elasticsearch.py
Labels: backport

#14472 [7.x] Convert license struct to MapStr (#14378)
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/cluster_stats/data_xpack.go
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/test_elasticsearch.py
Labels: backport

#14426 [7.5] Skip flaky test (#14405)
  metricbeat/tests/system/test_logstash.py
Labels: backport

#14482 Remove kbn-version header from requests to Kibana.
  libbeat/kibana/client.go
Labels: bug

#14494 [7.5] Remove kbn-version header from requests to Kibana. (#14482)
  libbeat/kibana/client.go
Labels: backport

#14269 Move changelog entry to correct section
  CHANGELOG.next.asciidoc
Labels: review

#14483 Add light modules of oss as source in docs collector
  metricbeat/scripts/msetlists/cmd/main.go
Labels: :integrations, Metricbeat, [zube]: In Review, needs_backport, review, v7.6.0, x-pack

#14375 [docker plugin] Refactor pipeline reader for data safety
  NOTICE.txt
  x-pack/dockerlogbeat/handlers.go
  x-pack/dockerlogbeat/magefile.go
  x-pack/dockerlogbeat/main.go
  x-pack/dockerlogbeat/pipelinemanager/clientLogReader.go
  x-pack/dockerlogbeat/pipelinemanager/libbeattools.go
  x-pack/dockerlogbeat/pipelinemanager/pipelineManager.go
  x-pack/dockerlogbeat/pipereader/reader.go
  x-pack/dockerlogbeat/vendor/github.com/gogo/protobuf/io/full.go
  x-pack/dockerlogbeat/vendor/github.com/gogo/protobuf/io/io.go
  x-pack/dockerlogbeat/vendor/github.com/gogo/protobuf/io/uint32.go
  x-pack/dockerlogbeat/vendor/github.com/gogo/protobuf/io/varint.go
  x-pack/dockerlogbeat/vendor/github.com/tonistiigi/fifo/LICENSE
  x-pack/dockerlogbeat/vendor/github.com/tonistiigi/fifo/Makefile
  x-pack/dockerlogbeat/vendor/github.com/tonistiigi/fifo/errors.go
  x-pack/dockerlogbeat/vendor/github.com/tonistiigi/fifo/fifo.go
  x-pack/dockerlogbeat/vendor/github.com/tonistiigi/fifo/handle_linux.go
  x-pack/dockerlogbeat/vendor/github.com/tonistiigi/fifo/handle_nolinux.go
  x-pack/dockerlogbeat/vendor/github.com/tonistiigi/fifo/mkfifo_nosolaris.go
  x-pack/dockerlogbeat/vendor/github.com/tonistiigi/fifo/mkfifo_solaris.go
  x-pack/dockerlogbeat/vendor/github.com/tonistiigi/fifo/raw.go
  x-pack/dockerlogbeat/vendor/github.com/tonistiigi/fifo/readme.md
  x-pack/dockerlogbeat/vendor/vendor.json
Labels: :integrations, [zube]: In Review

#14502 Cherry-pick #14483 to 7.x: Add light modules of oss as source in docs collector
  metricbeat/scripts/msetlists/cmd/main.go
Labels: backport, review

#14487 [6.8] Replace certs with a 20 year expiry (#14427)
  heartbeat/monitors/active/http/testdata/client_cert.pem
  heartbeat/monitors/active/http/testdata/client_key.pem
  heartbeat/monitors/active/http/testdata/openssl_command.txt
Labels: backport

#14252 [Uptime] Add docs for autodiscover hints
  heartbeat/docs/autodiscover-hints.asciidoc
  heartbeat/docs/configuring-howto.asciidoc
Labels: :uptime, Heartbeat, docs, v7.5.0

#14499 Fix: nginx module can't handle multiline entries
  CHANGELOG.next.asciidoc
  filebeat/module/nginx/error/config/nginx-error.yml
  filebeat/module/nginx/error/ingest/pipeline.json
  filebeat/module/nginx/error/test/error.log
  filebeat/module/nginx/error/test/error.log-expected.json
Labels: :integrations, Filebeat, needs_backport, review, v7.6.0

#14504 Cherry-pick #14471 to 7.x: [Filebeat] Decode hex values in auditd log messages
  CHANGELOG.next.asciidoc
  filebeat/module/auditd/log/ingest/pipeline.json
  filebeat/module/auditd/log/ingest/pipeline.yml
  filebeat/module/auditd/log/manifest.yml
  filebeat/module/auditd/log/test/test.log
  filebeat/module/auditd/log/test/test.log-expected.json
Labels: Filebeat, Team:SIEM, backport, review

#13917 Add asciidoctor flag to mage docs script
  dev-tools/mage/docs.go
Labels: docs, review

#14512 [7.x] Fix: nginx module can't handle multiline entries (#14499)
  CHANGELOG.next.asciidoc
  filebeat/module/nginx/error/config/nginx-error.yml
  filebeat/module/nginx/error/ingest/pipeline.json
  filebeat/module/nginx/error/test/error.log
  filebeat/module/nginx/error/test/error.log-expected.json
Labels: backport

#14514 Close changelog for 6.8.5
  CHANGELOG-developer.asciidoc
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, release, review, v6.8.5

#14515 Update testing env 6.8.5
  testing/environments/latest.yml
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: :Testing, release, review, v6.8.5

#14507 [libbeat] clarify behavior of pipeline.Load in godoc
  libbeat/publisher/pipeline/module.go
Labels: :integrations, docs, libbeat

#14522 [DOCS] Add missing line to fix list formatting in relnotes
  libbeat/docs/release.asciidoc
Labels: Team:Beats, docs, review

#14356 Log monitoring bulk failures
  CHANGELOG.next.asciidoc
  libbeat/monitoring/report/elasticsearch/client.go
  libbeat/outputs/elasticsearch/bulkapi.go
  libbeat/outputs/elasticsearch/bulkapi_mock_test.go
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/elasticsearch/json_read.go
Labels: Stack monitoring, bug, libbeat, v7.5.1, v7.6.0, v8.0.0

#14231 Close chan of Closer first before calling callback
  CHANGELOG.next.asciidoc
  filebeat/inputsource/tcp/closeref.go
  filebeat/inputsource/tcp/handler.go
Labels: review

#14498 Replace generate_imports python script with mage imports
  dev-tools/cmd/module_include_list/module_include_list.go
  dev-tools/mage/fields.go
  filebeat/magefile.go
  generator/common/beatgen/beatgen.go
  generator/common/beatgen/setup/setup.go
  generator/metricbeat/{beat}/magefile.go
  heartbeat/Makefile
  heartbeat/magefile.go
  heartbeat/monitors/defaults/default.go
  metricbeat/Makefile
  metricbeat/include/list_common.go
  metricbeat/include/list_docker.go
  metricbeat/magefile.go
  metricbeat/scripts/generate_imports_helper.py
  metricbeat/scripts/mage/fields.go
  packetbeat/magefile.go
  script/generate_imports.py
  x-pack/filebeat/magefile.go
Labels: :integrations, [zube]: In Review, refactoring, review

#14470 Add attack_pattern_kql field to MISP threat indicators
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/misp/fields.go
  x-pack/filebeat/module/misp/threat/_meta/fields.yml
  x-pack/filebeat/module/misp/threat/config/pipeline.js
  x-pack/filebeat/module/misp/threat/test/misp-test.json.log
  x-pack/filebeat/module/misp/threat/test/misp-test.json.log-expected.json
Labels: Filebeat, Team:SIEM, module, review

#14416 Update Envoy Proxy versions and add new metrics to envyproxy metricbeat module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/envoyproxy.asciidoc
  metricbeat/module/envoyproxy/_meta/Dockerfile
  metricbeat/module/envoyproxy/_meta/docs.asciidoc
  metricbeat/module/envoyproxy/_meta/envoy.json
  metricbeat/module/envoyproxy/_meta/envoy.yaml
  metricbeat/module/envoyproxy/_meta/test/serverstats
  metricbeat/module/envoyproxy/fields.go
  metricbeat/module/envoyproxy/server/_meta/data.json
  metricbeat/module/envoyproxy/server/_meta/fields.yml
  metricbeat/module/envoyproxy/server/data.go
  metricbeat/module/envoyproxy/server/server_test.go
  metricbeat/tests/system/test_envoyproxy.py
Labels: :integrations, [zube]: In Review, enhancement, needs_backport, review, v7.6.0

#14530 Finalize changelog for 7.5.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
Labels: docs, needs_edit, release, review, v7.5.0

#14525 [Metricbeat] Check length of the slice instead of comparing with nil in cloudwatch
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
Labels: :integrations, Metricbeat, [zube]: In Review, bug, needs_backport

#14534 Cherry-pick #14416 to 7.x: Update Envoy Proxy versions and add new metrics to envyproxy metricbeat module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/envoyproxy.asciidoc
  metricbeat/module/envoyproxy/_meta/Dockerfile
  metricbeat/module/envoyproxy/_meta/docs.asciidoc
  metricbeat/module/envoyproxy/_meta/envoy.json
  metricbeat/module/envoyproxy/_meta/envoy.yaml
  metricbeat/module/envoyproxy/_meta/test/serverstats
  metricbeat/module/envoyproxy/fields.go
  metricbeat/module/envoyproxy/server/_meta/data.json
  metricbeat/module/envoyproxy/server/_meta/fields.yml
  metricbeat/module/envoyproxy/server/data.go
  metricbeat/module/envoyproxy/server/server_test.go
  metricbeat/tests/system/test_envoyproxy.py
Labels: backport, review

#14533 Add CommunityProject variable to beats generator's magefile.go
  generator/beat/{beat}/magefile.go
Labels: :Generator, review

#13831 fix typo
  libbeat/docs/processors-using.asciidoc
Labels: docs, needs_backport, review, v7.6.0

#14474 [6.8] Convert license struct to MapStr (#14378)
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/cluster_stats/data_xpack.go
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/test_elasticsearch.py
Labels: backport

#14116 [7.5][DOCS] Fixes link to role mapping (#13927)
  libbeat/docs/security/basic-auth.asciidoc
Labels: backport

#14538 Cherry-pick #14525 to 7.5: [Metricbeat] Check length of the slice instead of comparing with nil in cloudwatch
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
Labels: backport, review

#14410 [DOCS] Create separate topics for processor docs
  libbeat/docs/processors-list.asciidoc
  libbeat/docs/processors-using.asciidoc
  libbeat/docs/shared-beats-attributes.asciidoc
  libbeat/processors/actions/docs/add_fields.asciidoc
  libbeat/processors/actions/docs/add_labels.asciidoc
  libbeat/processors/actions/docs/add_tags.asciidoc
  libbeat/processors/actions/docs/decode_base64_field.asciidoc
  libbeat/processors/actions/docs/decode_json_fields.asciidoc
  libbeat/processors/actions/docs/decompress_gzip_field.asciidoc
  libbeat/processors/actions/docs/drop_event.asciidoc
  libbeat/processors/actions/docs/drop_fields.asciidoc
  libbeat/processors/actions/docs/include_fields.asciidoc
  libbeat/processors/actions/docs/rename.asciidoc
  libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc
  libbeat/processors/add_docker_metadata/docs/add_docker_metadata.asciidoc
  libbeat/processors/add_host_metadata/docs/add_host_metadata.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  libbeat/processors/add_locale/docs/add_locale.asciidoc
  libbeat/processors/add_observer_metadata/docs/add_observer_metadata.asciidoc
  libbeat/processors/add_process_metadata/docs/add_process_metadata.asciidoc
  libbeat/processors/communityid/docs/communityid.asciidoc
  libbeat/processors/convert/docs/convert.asciidoc
  libbeat/processors/decode_csv_fields/docs/decode_csv_fields.asciidoc
  libbeat/processors/dissect/docs/dissect.asciidoc
  libbeat/processors/dns/docs/dns.asciidoc
  libbeat/processors/extract_array/docs/extract_array.asciidoc
  libbeat/processors/fingerprint/docs/fingerprint.asciidoc
  libbeat/processors/registered_domain/docs/registered_domain.asciidoc
  libbeat/processors/script/docs/script.asciidoc
  libbeat/processors/timestamp/docs/timestamp.asciidoc
  x-pack/filebeat/processors/decode_cef/docs/decode_cef.asciidoc
Labels: Team:Beats, [zube]: In Review, docs, needs_backport, review

#14312 [Metricbeat] Release ebs as GA
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws/ebs.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/aws/ebs/_meta/fields.yml
  x-pack/metricbeat/module/aws/fields.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, needs_backport, review

#14543 bump es heap sizes for integration tests
  metricbeat/module/jolokia/_meta/Dockerfile
  metricbeat/module/jolokia/_meta/jolokia-1.5.0.sum
  testing/environments/latest.yml
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: :Testing, needs_backport, review

#14544 Cherry-pick #13831 to 7.x: fix typo
  libbeat/docs/processors-using.asciidoc
Labels: backport, review

#14545 Cherry-pick #13831 to 7.5: fix typo
  libbeat/docs/processors-using.asciidoc
Labels: backport, review

#14561 fix breaking changes list for 7.5
  CHANGELOG.asciidoc
Labels: Team:Beats, [zube]: In Review, review

#14398 [DOCS] Add placeholder files for 7.5 BCs and highlights
  libbeat/docs/index.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.0.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.1.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.2.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.3.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.4.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.5.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
  libbeat/docs/release-notes/breaking/field-name-changes.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.0.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.1.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.2.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.3.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.4.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.5.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-8.0.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights.asciidoc
Labels: Team:Beats, [zube]: In Review, docs, needs_backport, review

#14570 [7.x][DOCS] Backport: Add temporary files to support doc build changes
  libbeat/processors/actions/docs/placeholder.asciidoc
  x-pack/filebeat/processors/decode_cef/docs/placeholder.asciidoc
Labels: backport, docs

#14571 [7.5][DOCS] Backport: Add temporary files to support doc build changes
  libbeat/processors/actions/docs/placeholder.asciidoc
  x-pack/filebeat/processors/decode_cef/docs/placeholder.asciidoc
Labels: backport, docs, v7.5.0

#14539 Cherry-pick #14525 to 7.x: [Metricbeat] Check length of the slice instead of comparing with nil in cloudwatch
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
Labels: backport, review

#14478 Pass GENERATE env var to `mage pythonIntegTest`
  filebeat/magefile.go
  x-pack/filebeat/magefile.go
Labels: :Testing, Team:Integrations, [zube]: In Review

#14547 Fixing node name to use `DATA` grok pattern
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/slowlog/ingest/pipeline-plaintext.json
  filebeat/module/elasticsearch/slowlog/test/test.log
  filebeat/module/elasticsearch/slowlog/test/test.log-expected.json
Labels: Filebeat, bug, module, review, v7.5.1, v7.6.0, v8.0.0

#14559 Cherry-pick #14312 to 7.x: [Metricbeat] Release ebs as GA
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws/ebs.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/aws/ebs/_meta/fields.yml
  x-pack/metricbeat/module/aws/fields.go
Labels: backport, review

#14523 [Docker logging driver] Shuffle around docker deps due to import path checking
  NOTICE.txt
  x-pack/dockerlogbeat/handlers.go
  x-pack/dockerlogbeat/pipelinemanager/clientLogReader.go
  x-pack/dockerlogbeat/pipereader/reader.go
  x-pack/dockerlogbeat/vendor/github.com/docker/docker/daemon/logger/adapter.go
  x-pack/dockerlogbeat/vendor/github.com/docker/docker/daemon/logger/copier.go
  x-pack/dockerlogbeat/vendor/github.com/docker/docker/daemon/logger/factory.go
  x-pack/dockerlogbeat/vendor/github.com/docker/docker/daemon/logger/logger.go
  x-pack/dockerlogbeat/vendor/github.com/docker/docker/daemon/logger/loginfo.go
  x-pack/dockerlogbeat/vendor/github.com/docker/docker/daemon/logger/metrics.go
  x-pack/dockerlogbeat/vendor/github.com/docker/docker/daemon/logger/plugin.go
  x-pack/dockerlogbeat/vendor/github.com/docker/docker/daemon/logger/plugin_unix.go
  x-pack/dockerlogbeat/vendor/github.com/docker/docker/daemon/logger/plugin_unsupported.go
  x-pack/dockerlogbeat/vendor/github.com/docker/docker/daemon/logger/proxy.go
  x-pack/dockerlogbeat/vendor/github.com/docker/docker/daemon/logger/ring.go
  x-pack/dockerlogbeat/vendor/github.com/docker/engine/LICENSE
  x-pack/dockerlogbeat/vendor/github.com/docker/engine/NOTICE
  x-pack/dockerlogbeat/vendor/github.com/docker/engine/api/types/plugins/logdriver/entry.pb.go
  x-pack/dockerlogbeat/vendor/github.com/docker/engine/api/types/plugins/logdriver/entry.proto
  x-pack/dockerlogbeat/vendor/github.com/docker/engine/api/types/plugins/logdriver/gen.go
  x-pack/dockerlogbeat/vendor/github.com/docker/engine/api/types/plugins/logdriver/io.go
  x-pack/dockerlogbeat/vendor/vendor.json
Labels: Team:Integrations, [zube]: In Review

#14555 docs: add azure module known issue
  CHANGELOG.asciidoc
Labels: docs, needs_backport, v7.5.0

#14518 [docker log driver] Move pipeline check + creation to single atomic operation
  x-pack/dockerlogbeat/pipelinemanager/pipelineManager.go
Labels: Team:Integrations, [zube]: In Review

#14572 [7.5][DOCS] Add placeholder files for 7.5 BCs and highlights (#14398)
  libbeat/docs/index.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.0.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.1.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.2.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.3.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.4.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.5.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
  libbeat/docs/release-notes/breaking/field-name-changes.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.0.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.1.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.2.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.3.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.4.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.5.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-8.0.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights.asciidoc
Labels: backport, docs, v7.5.0

#14573 [7.x][DOCS] Backport: Add placeholder files for 7.5 BCs and highlights (#14398)
  libbeat/docs/index.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.0.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.1.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.2.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.3.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.4.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.5.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
  libbeat/docs/release-notes/breaking/field-name-changes.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.0.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.1.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.2.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.3.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.4.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.5.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights-8.0.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights.asciidoc
Labels: backport, docs, v7.6.0

#14574 [7.x][DOCS] Create separate topics for processor docs (#14410)
  libbeat/docs/processors-list.asciidoc
  libbeat/docs/processors-using.asciidoc
  libbeat/docs/shared-beats-attributes.asciidoc
  libbeat/processors/actions/docs/add_fields.asciidoc
  libbeat/processors/actions/docs/add_labels.asciidoc
  libbeat/processors/actions/docs/add_tags.asciidoc
  libbeat/processors/actions/docs/decode_base64_field.asciidoc
  libbeat/processors/actions/docs/decode_json_fields.asciidoc
  libbeat/processors/actions/docs/decompress_gzip_field.asciidoc
  libbeat/processors/actions/docs/drop_event.asciidoc
  libbeat/processors/actions/docs/drop_fields.asciidoc
  libbeat/processors/actions/docs/include_fields.asciidoc
  libbeat/processors/actions/docs/rename.asciidoc
  libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc
  libbeat/processors/add_docker_metadata/docs/add_docker_metadata.asciidoc
  libbeat/processors/add_host_metadata/docs/add_host_metadata.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  libbeat/processors/add_locale/docs/add_locale.asciidoc
  libbeat/processors/add_observer_metadata/docs/add_observer_metadata.asciidoc
  libbeat/processors/add_process_metadata/docs/add_process_metadata.asciidoc
  libbeat/processors/communityid/docs/communityid.asciidoc
  libbeat/processors/convert/docs/convert.asciidoc
  libbeat/processors/decode_csv_fields/docs/decode_csv_fields.asciidoc
  libbeat/processors/dissect/docs/dissect.asciidoc
  libbeat/processors/dns/docs/dns.asciidoc
  libbeat/processors/extract_array/docs/extract_array.asciidoc
  libbeat/processors/fingerprint/docs/fingerprint.asciidoc
  libbeat/processors/registered_domain/docs/registered_domain.asciidoc
  libbeat/processors/script/docs/script.asciidoc
  libbeat/processors/timestamp/docs/timestamp.asciidoc
  x-pack/filebeat/processors/decode_cef/docs/decode_cef.asciidoc
Labels: backport, docs, v7.6.0

#14576 [7.5][DOCS] Backport: Create separate topics for processor docs (#14410)
  libbeat/docs/processors-list.asciidoc
  libbeat/docs/processors-using.asciidoc
  libbeat/docs/shared-beats-attributes.asciidoc
  libbeat/processors/actions/docs/add_fields.asciidoc
  libbeat/processors/actions/docs/add_labels.asciidoc
  libbeat/processors/actions/docs/add_tags.asciidoc
  libbeat/processors/actions/docs/decode_base64_field.asciidoc
  libbeat/processors/actions/docs/decode_json_fields.asciidoc
  libbeat/processors/actions/docs/decompress_gzip_field.asciidoc
  libbeat/processors/actions/docs/drop_event.asciidoc
  libbeat/processors/actions/docs/drop_fields.asciidoc
  libbeat/processors/actions/docs/include_fields.asciidoc
  libbeat/processors/actions/docs/rename.asciidoc
  libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc
  libbeat/processors/add_docker_metadata/docs/add_docker_metadata.asciidoc
  libbeat/processors/add_host_metadata/docs/add_host_metadata.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  libbeat/processors/add_locale/docs/add_locale.asciidoc
  libbeat/processors/add_observer_metadata/docs/add_observer_metadata.asciidoc
  libbeat/processors/add_process_metadata/docs/add_process_metadata.asciidoc
  libbeat/processors/communityid/docs/communityid.asciidoc
  libbeat/processors/convert/docs/convert.asciidoc
  libbeat/processors/decode_csv_fields/docs/decode_csv_fields.asciidoc
  libbeat/processors/dissect/docs/dissect.asciidoc
  libbeat/processors/dns/docs/dns.asciidoc
  libbeat/processors/extract_array/docs/extract_array.asciidoc
  libbeat/processors/registered_domain/docs/registered_domain.asciidoc
  libbeat/processors/script/docs/script.asciidoc
  libbeat/processors/timestamp/docs/timestamp.asciidoc
  x-pack/filebeat/processors/decode_cef/docs/decode_cef.asciidoc
Labels: backport, docs, v7.5.0

#14408 [DOCS] Fix description of rename processor
  libbeat/processors/actions/docs/rename.asciidoc
Labels: Team:Beats, [zube]: In Review, docs, needs_backport, review

#14104 [DOCS] Deprecate central management
  filebeat/docs/configuring-howto.asciidoc
  filebeat/docs/getting-started.asciidoc
  libbeat/docs/shared-central-management.asciidoc
  libbeat/docs/shared-cm-tip.asciidoc
  metricbeat/docs/configuring-howto.asciidoc
  metricbeat/docs/gettingstarted.asciidoc
Labels: Team:Beats, [zube]: In Review, docs, needs_backport, review, v7.5.0

#14400 [DOCS] State minimum Go version
  docs/devguide/newbeat.asciidoc
Labels: Team:Beats, [zube]: In Review, docs, needs_backport, review

#14575 Add missing colon
  libbeat/docs/processors-using.asciidoc
Labels: Team:Beats, docs

#14591 Check license expiry date zero value
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/ccr/ccr.go
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/test_elasticsearch.py
Labels: Metricbeat, Stack monitoring, needs_backport, review, v7.5.0, v7.6.0, v8.0.0

#14603 [7.x] Check license expiry date zero value (#14591)
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/ccr/ccr.go
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/test_elasticsearch.py
Labels: backport

#14604 [7.5] Check license expiry date zero value (#14591)
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/ccr/ccr.go
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/test_elasticsearch.py
Labels: backport

#14529 Cherry-pick #14498 to 7.x: Replace generate_imports python script with mage imports
  dev-tools/cmd/module_include_list/module_include_list.go
  dev-tools/mage/fields.go
  filebeat/magefile.go
  generator/common/beatgen/beatgen.go
  generator/common/beatgen/setup/setup.go
  generator/metricbeat/{beat}/magefile.go
  heartbeat/Makefile
  heartbeat/magefile.go
  heartbeat/monitors/defaults/default.go
  metricbeat/Makefile
  metricbeat/include/list_common.go
  metricbeat/include/list_docker.go
  metricbeat/magefile.go
  metricbeat/scripts/generate_imports_helper.py
  metricbeat/scripts/mage/fields.go
  packetbeat/magefile.go
  script/generate_imports.py
  x-pack/filebeat/magefile.go
Labels: Team:Integrations, [zube]: In Review, backport, review

#14519 [Filebeat] Fix parsing of Cisco ASA/FTD message 302021
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/test/hostnames.log
  x-pack/filebeat/module/cisco/asa/test/hostnames.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: Filebeat, Team:SIEM, bug, needs_backport

#14404 Added support for intel.log zeek module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/zeek/_meta/config.yml
  x-pack/filebeat/module/zeek/fields.go
  x-pack/filebeat/module/zeek/intel/_meta/fields.yml
  x-pack/filebeat/module/zeek/intel/config/intel.yml
  x-pack/filebeat/module/zeek/intel/ingest/pipeline.yml
  x-pack/filebeat/module/zeek/intel/manifest.yml
  x-pack/filebeat/module/zeek/intel/test/intel-json.log
  x-pack/filebeat/module/zeek/intel/test/intel-json.log-expected.json
  x-pack/filebeat/modules.d/zeek.yml.disabled
Labels: Filebeat, Team:SIEM, ecs, review

#14594 [7.5][DOCS] Backport: Deprecate central management
  filebeat/docs/configuring-howto.asciidoc
  filebeat/docs/getting-started.asciidoc
  libbeat/docs/shared-central-management.asciidoc
  libbeat/docs/shared-cm-tip.asciidoc
  metricbeat/docs/configuring-howto.asciidoc
  metricbeat/docs/gettingstarted.asciidoc
Labels: backport, docs, v7.5.0

#14598 [7.5][DOCS] Backport: State minimum Go version (#14400)
  docs/devguide/newbeat.asciidoc
Labels: backport, docs, v7.5.0

#14600 [7.5][DOCS] Backport: Fix description of rename processor
  libbeat/processors/actions/docs/rename.asciidoc
Labels: backport, docs, v7.5.0

#14609 Add compose option to advertise hosts for specific ports
  libbeat/tests/compose/project.go
  libbeat/tests/compose/wrapper.go
  libbeat/tests/system/beat/compose.py
  metricbeat/module/kafka/consumergroup/consumergroup_integration_test.go
  metricbeat/module/kafka/partition/partition_integration_test.go
  metricbeat/tests/system/test_kafka.py
Labels: :Testing, Metricbeat, Team:Integrations, [zube]: In Review, module, needs_backport, review

#14520 Read build args for metricbeat system tests from file
  CHANGELOG-developer.next.asciidoc
  libbeat/tests/system/requirements.txt
  metricbeat/docker-compose.yml
  metricbeat/module/apache/_meta/supported-versions.yml
  metricbeat/module/apache/test_apache.py
  metricbeat/module/mysql/_meta/supported-versions.yml
  metricbeat/module/mysql/docker-compose.yml
  metricbeat/module/mysql/test_mysql.py
  metricbeat/tests/system/metricbeat.py
Labels: :Testing, Metricbeat, [zube]: In Review, module, review

#7213 Issue #7187/fix vsphere metricbeat host
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/magefile.go
  metricbeat/module/vsphere/fields.go
  metricbeat/module/vsphere/virtualmachine/_meta/data.json
  metricbeat/module/vsphere/virtualmachine/_meta/fields.yml
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
  metricbeat/module/vsphere/virtualmachine/virtualmachine_test.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, module, review

#14582 [7.x] Fixing node name to use `DATA` grok pattern (#14547)
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/slowlog/ingest/pipeline-plaintext.json
  filebeat/module/elasticsearch/slowlog/test/test.log
  filebeat/module/elasticsearch/slowlog/test/test.log-expected.json
Labels: backport

#14588 [Heartbeat] Record TLS Metadata for expired/invalid certs
  CHANGELOG.next.asciidoc
  heartbeat/monitors/active/dialchain/tls.go
  heartbeat/monitors/active/dialchain/tls_test.go
Labels: :uptime, Heartbeat, bug, v7.5.1

#14611 Cherry-pick #14519 to 7.5: [Filebeat] Fix parsing of Cisco ASA/FTD message 302021
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/test/hostnames.log
  x-pack/filebeat/module/cisco/asa/test/hostnames.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: backport, review

#14610 Cherry-pick #14519 to 7.x: [Filebeat] Fix parsing of Cisco ASA/FTD message 302021
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/test/hostnames.log
  x-pack/filebeat/module/cisco/asa/test/hostnames.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: backport, review

#14553 New fileset for googlecloud firewall logs
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/googlecloud.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/googlecloud/_meta/config.yml
  x-pack/filebeat/module/googlecloud/_meta/docs.asciidoc
  x-pack/filebeat/module/googlecloud/_meta/fields.yml
  x-pack/filebeat/module/googlecloud/fields.go
  x-pack/filebeat/module/googlecloud/firewall/_meta/fields.yml
  x-pack/filebeat/module/googlecloud/firewall/config/input.yml
  x-pack/filebeat/module/googlecloud/firewall/config/pipeline.js
  x-pack/filebeat/module/googlecloud/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/googlecloud/firewall/manifest.yml
  x-pack/filebeat/module/googlecloud/firewall/test/rare.log
  x-pack/filebeat/module/googlecloud/firewall/test/rare.log-expected.json
  x-pack/filebeat/module/googlecloud/firewall/test/test.log
  x-pack/filebeat/module/googlecloud/firewall/test/test.log-expected.json
  x-pack/filebeat/module/googlecloud/vpcflow/_meta/fields.yml
  x-pack/filebeat/module/googlecloud/vpcflow/config/pipeline.js
  x-pack/filebeat/module/googlecloud/vpcflow/test/vpc-flow-log-entries.json.log-expected.json
  x-pack/filebeat/modules.d/googlecloud.yml.disabled
Labels: Filebeat, Team:SIEM, enhancement, module, review

#14309 Reword error message when we fail to add a CA to the certpool
  CHANGELOG.next.asciidoc
  libbeat/common/transport/tlscommon/tls.go
Labels: review

#14602 Add document for Filebeat input httpjson
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
Labels: review

#14493 [7.x] Remove kbn-version header from requests to Kibana. (#14482)
  libbeat/kibana/client.go
Labels: Team:APM, [zube]: In Review, backport

#14557 [Winlogbeat] Add support for eventID 4688 & 4689
  CHANGELOG.next.asciidoc
  winlogbeat/docs/modules/security.asciidoc
  x-pack/winlogbeat/module/security/_meta/docs.asciidoc
  x-pack/winlogbeat/module/security/config/winlogbeat-security.js
  x-pack/winlogbeat/module/security/test/testdata/security-windows2019_4688_Process_Created.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2019_4688_Process_Created.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2019_4689_Process_Exited.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2019_4689_Process_Exited.evtx.golden.json
Labels: Team:SIEM, Winlogbeat, needs_backport, review

#14619 [DOCS] Make processor conditionals opt-out rather than opt-in
  auditbeat/docs/index.asciidoc
  filebeat/docs/index.asciidoc
  heartbeat/docs/index.asciidoc
  journalbeat/docs/index.asciidoc
  libbeat/docs/processors-list.asciidoc
  libbeat/processors/decode_csv_fields/docs/decode_csv_fields.asciidoc
  libbeat/processors/script/docs/script.asciidoc
  libbeat/processors/timestamp/docs/timestamp.asciidoc
  metricbeat/docs/index.asciidoc
  packetbeat/docs/index.asciidoc
  winlogbeat/docs/index.asciidoc
  x-pack/filebeat/processors/decode_cef/docs/decode_cef.asciidoc
  x-pack/functionbeat/docs/index.asciidoc
Labels: Team:Beats, [zube]: In Review, docs, needs_backport, review

#14595 [7.x][DOCS] Backport: Deprecate central management
  filebeat/docs/configuring-howto.asciidoc
  filebeat/docs/getting-started.asciidoc
  libbeat/docs/shared-central-management.asciidoc
  libbeat/docs/shared-cm-tip.asciidoc
  metricbeat/docs/configuring-howto.asciidoc
  metricbeat/docs/gettingstarted.asciidoc
Labels: backport, docs, v7.6.0

#14597 [7.x][DOCS] Backport: State minimum Go version (#14400)
  docs/devguide/newbeat.asciidoc
Labels: backport, docs, v7.6.0

#14601 [7.x][DOCS] Backport: Fix description of rename processor
  libbeat/processors/actions/docs/rename.asciidoc
Labels: backport, docs, v7.6.0

#14338 Allow users to set just monitoring.cluster_uuid
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
  libbeat/monitoring/monitoring.go
  libbeat/tests/system/config/mockbeat.yml.j2
  libbeat/tests/system/test_monitoring.py
Labels: Stack monitoring, bug, libbeat, review, v7.5.1, v7.6.0, v8.0.0

#14592 Fix license ID field name
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/elasticsearch.go
Labels: Stack monitoring, bug, needs_backport, review, v7.5.1, v7.6.0, v8.0.0

#14583 [7.5] Fixing node name to use `DATA` grok pattern (#14547)
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/slowlog/ingest/pipeline-plaintext.json
  filebeat/module/elasticsearch/slowlog/test/test.log
  filebeat/module/elasticsearch/slowlog/test/test.log-expected.json
Labels: backport

#14608 googlecloud/vpcflow fileset: Populate additional log fields
  filebeat/docs/modules/googlecloud.asciidoc
  x-pack/filebeat/module/googlecloud/_meta/docs.asciidoc
  x-pack/filebeat/module/googlecloud/vpcflow/config/input.yml
  x-pack/filebeat/module/googlecloud/vpcflow/config/pipeline.js
  x-pack/filebeat/module/googlecloud/vpcflow/manifest.yml
  x-pack/filebeat/module/googlecloud/vpcflow/test/vpc-flow-log-entries.json.log-expected.json
Labels: Team:SIEM, enhancement, review

#14421 Improve hash performance on Prometheus collector
  NOTICE.txt
  auditbeat/helper/hasher/hasher.go
  auditbeat/module/file_integrity/event.go
  metricbeat/helper/http.go
  metricbeat/helper/prometheus/hash.go
  metricbeat/helper/prometheus/hash_benchmark_test.go
  metricbeat/helper/prometheus/prometheus.go
  metricbeat/module/prometheus/collector/data.go
  vendor/github.com/OneOfOne/xxhash/LICENSE
  vendor/github.com/OneOfOne/xxhash/README.md
  vendor/github.com/OneOfOne/xxhash/go.mod
  vendor/github.com/OneOfOne/xxhash/xxhash.go
  vendor/github.com/OneOfOne/xxhash/xxhash_go17.go
  vendor/github.com/OneOfOne/xxhash/xxhash_safe.go
  vendor/github.com/OneOfOne/xxhash/xxhash_unsafe.go
  vendor/github.com/cespare/xxhash/LICENSE.txt
  vendor/github.com/cespare/xxhash/README.md
  vendor/github.com/cespare/xxhash/go.mod
  vendor/github.com/cespare/xxhash/go.sum
  vendor/github.com/cespare/xxhash/xxhash.go
  vendor/github.com/cespare/xxhash/xxhash_amd64.go
  vendor/github.com/cespare/xxhash/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/xxhash_other.go
  vendor/github.com/cespare/xxhash/xxhash_safe.go
  vendor/github.com/cespare/xxhash/xxhash_unsafe.go
  vendor/vendor.json
  x-pack/auditbeat/cache/cache_test.go
  x-pack/auditbeat/module/system/host/host.go
  x-pack/auditbeat/module/system/package/package.go
  x-pack/auditbeat/module/system/process/process.go
  x-pack/auditbeat/module/system/user/user.go
  x-pack/filebeat/input/netflow/convert.go
Labels: Team:Integrations, [zube]: In Review, enhancement, needs_backport, review

#14616 Cherry-pick #7213 to 7.x: Issue #7187/fix vsphere metricbeat host
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/magefile.go
  metricbeat/module/vsphere/fields.go
  metricbeat/module/vsphere/virtualmachine/_meta/data.json
  metricbeat/module/vsphere/virtualmachine/_meta/fields.yml
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
  metricbeat/module/vsphere/virtualmachine/virtualmachine_test.go
Labels: backport, review

#14580 [Metricbeat] Create ActiveMQ module
  CHANGELOG.next.asciidoc
  libbeat/tests/system/requirements.txt
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/activemq.asciidoc
  metricbeat/docs/modules/activemq/broker.asciidoc
  metricbeat/docs/modules/activemq/queue.asciidoc
  metricbeat/docs/modules/activemq/topic.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/tests/system/config/metricbeat.yml.j2
  x-pack/metricbeat/docker-compose.yml
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/activemq/_meta/Dockerfile
  x-pack/metricbeat/module/activemq/_meta/config.yml
  x-pack/metricbeat/module/activemq/_meta/docs.asciidoc
  x-pack/metricbeat/module/activemq/_meta/fields.yml
  x-pack/metricbeat/module/activemq/broker/_meta/data.json
  x-pack/metricbeat/module/activemq/broker/_meta/docs.asciidoc
  x-pack/metricbeat/module/activemq/broker/_meta/fields.yml
  x-pack/metricbeat/module/activemq/broker/manifest.yml
  x-pack/metricbeat/module/activemq/fields.go
  x-pack/metricbeat/module/activemq/module.yml
  x-pack/metricbeat/module/activemq/queue/_meta/data.json
  x-pack/metricbeat/module/activemq/queue/_meta/docs.asciidoc
  x-pack/metricbeat/module/activemq/queue/_meta/fields.yml
  x-pack/metricbeat/module/activemq/queue/manifest.yml
  x-pack/metricbeat/module/activemq/topic/_meta/data.json
  x-pack/metricbeat/module/activemq/topic/_meta/docs.asciidoc
  x-pack/metricbeat/module/activemq/topic/_meta/fields.yml
  x-pack/metricbeat/module/activemq/topic/manifest.yml
  x-pack/metricbeat/modules.d/activemq.yml.disabled
  x-pack/metricbeat/tests/system/test_activemq.py
Labels: Team:Integrations, [zube]: In Progress, enhancement, module, needs_backport, review

#14556 remove -i from go build
  libbeat/scripts/Makefile
Labels: Team:Beats

#14516 Bump docs version for 6.8.5
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, review, v6.8.5

#14587 Add target to build images from supported-versions.yml file
  dev-tools/mage/target/compose/compose.go
  metricbeat/magefile.go
  x-pack/metricbeat/magefile.go
Labels: :Testing, Metricbeat

#14615 [Docker log driver] cleanup output
  x-pack/dockerlogbeat/handlers.go
  x-pack/dockerlogbeat/pipelinemanager/clientLogReader.go
  x-pack/dockerlogbeat/pipelinemanager/pipelineManager.go
Labels: Team:Integrations

#14634 [7.x] Fix license ID field name (#14592)
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/elasticsearch.go
Labels: backport

#14636 Use complete versions in deprecation warnings
  libbeat/common/cfgtype/byte_size.go
  libbeat/monitoring/monitoring.go
  metricbeat/module/system/core/config.go
  metricbeat/module/system/cpu/config.go
  metricbeat/module/system/process/config.go
  x-pack/functionbeat/provider/aws/aws/config.go
Labels: Team:Beats, [zube]: In Review, cleanup, review, v7.6.0, v8.0.0

#14330 [Metricbeat] Add Kafka JMX metricsets
  CHANGELOG.next.asciidoc
  metricbeat/docker-compose.yml
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/kafka.asciidoc
  metricbeat/docs/modules/kafka/broker.asciidoc
  metricbeat/docs/modules/kafka/consumer.asciidoc
  metricbeat/docs/modules/kafka/producer.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kafka/_meta/Dockerfile
  metricbeat/module/kafka/_meta/config.reference.yml
  metricbeat/module/kafka/_meta/config.yml
  metricbeat/module/kafka/_meta/docs.asciidoc
  metricbeat/module/kafka/_meta/healthcheck.sh
  metricbeat/module/kafka/_meta/jaas-kafka-client-consumer.conf
  metricbeat/module/kafka/_meta/jaas-kafka-client-producer.conf
  metricbeat/module/kafka/_meta/run.sh
  metricbeat/module/kafka/_meta/sasl-consumer.properties
  metricbeat/module/kafka/_meta/sasl-producer.properties
  metricbeat/module/kafka/broker/_meta/data.json
  metricbeat/module/kafka/broker/_meta/docs.asciidoc
  metricbeat/module/kafka/broker/_meta/fields.yml
  metricbeat/module/kafka/broker/manifest.yml
  metricbeat/module/kafka/consumer/_meta/data.json
  metricbeat/module/kafka/consumer/_meta/docs.asciidoc
  metricbeat/module/kafka/consumer/_meta/fields.yml
  metricbeat/module/kafka/consumer/manifest.yml
  metricbeat/module/kafka/consumergroup/consumergroup_integration_test.go
  metricbeat/module/kafka/fields.go
  metricbeat/module/kafka/module.yml
  metricbeat/module/kafka/partition/partition_integration_test.go
  metricbeat/module/kafka/producer/_meta/data.json
  metricbeat/module/kafka/producer/_meta/docs.asciidoc
  metricbeat/module/kafka/producer/_meta/fields.yml
  metricbeat/module/kafka/producer/manifest.yml
  metricbeat/modules.d/kafka.yml.disabled
  x-pack/filebeat/modules.d/googlecloud.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Metricbeat, Team:Integrations, [zube]: In Progress, in progress, module, needs_backport, qa, v7.6.0

#14633 [7.5] Allow users to set just monitoring.cluster_uuid (#14338)
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
  libbeat/monitoring/monitoring.go
  libbeat/tests/system/config/mockbeat.yml.j2
  libbeat/tests/system/test_monitoring.py
Labels: backport

#14517 Bump version to 6.8.6
  libbeat/version/version.go
Labels: in progress, release, review, v6.8.6

#14635 [7.5] Fix license ID field name (#14592)
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/elasticsearch.go
Labels: backport

#14652 [7.x] Use complete versions in deprecation warnings (#14636)
  libbeat/common/cfgtype/byte_size.go
  libbeat/monitoring/monitoring.go
  metricbeat/module/system/core/config.go
  metricbeat/module/system/cpu/config.go
  metricbeat/module/system/process/config.go
  x-pack/functionbeat/provider/aws/aws/config.go
Labels: backport

#14613 Cherry-pick #14609 to 7.x: Add compose option to advertise hosts for specific ports
  libbeat/tests/compose/project.go
  libbeat/tests/compose/wrapper.go
  libbeat/tests/system/beat/compose.py
  metricbeat/module/kafka/consumergroup/consumergroup_integration_test.go
  metricbeat/module/kafka/partition/partition_integration_test.go
  metricbeat/tests/system/test_kafka.py
Labels: backport, review

#14625 [Winlogbeat] Set host.name to computername
  CHANGELOG.next.asciidoc
  winlogbeat/eventlog/eventlog.go
  x-pack/winlogbeat/module/security/test/testdata/security-windows2012r2-logon.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016-4672.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016-logoff.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4720_Account_Created.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4722_Account_Enabled.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4723_Password_Change.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4724_Password_Reset.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4725_Account_Disabled.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4726_Account_Deleted.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4738_Account_Changed.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4740_Account_Locked_Out.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4767_Account_Unlocked.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4781_Account_Renamed.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2019_4688_Process_Created.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2019_4689_Process_Exited.evtx.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-10.2-dns.evtx.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-9.01.evtx.golden.json
Labels: Team:SIEM, Winlogbeat, needs_backport, review

#14664 Cherry-pick #14010 to 7.5: [Filebeat] Select output index based on the source input
  CHANGELOG.next.asciidoc
  filebeat/beater/filebeat.go
  filebeat/channel/connector.go
  filebeat/channel/connector_test.go
  filebeat/channel/factory.go
  filebeat/docs/inputs/input-common-options.asciidoc
  filebeat/input/input.go
  libbeat/common/fmtstr/formattimestamp.go
  libbeat/common/fmtstr/formattimestamp_test.go
  libbeat/idxmgmt/ilm/ilm.go
  libbeat/idxmgmt/std.go
Labels: backport, review
