Repository elastic/beats, pull requests merged in 2019-12, with the labels that each got.

#14407 Libbeat: Do not overwrite agent.*, ecs.version, and host.name
  CHANGELOG.next.asciidoc
  filebeat/channel/connector_test.go
  libbeat/common/mapstr.go
  libbeat/processors/actions/add_fields.go
  libbeat/processors/actions/add_labels.go
  libbeat/publisher/processing/default.go
  libbeat/publisher/processing/default_test.go
Labels: libbeat, review

#14869 Change from Enrollment token to use Elasticsearch API key
  x-pack/agent/pkg/agent/application/application.go
  x-pack/agent/pkg/agent/application/config_storage.go
  x-pack/agent/pkg/agent/application/enroll_cmd.go
  x-pack/agent/pkg/agent/application/enroll_cmd_test.go
  x-pack/agent/pkg/fleetapi/enroll_cmd.go
  x-pack/agent/pkg/fleetapi/enroll_cmd_test.go
Labels: Project:fleet, [zube]: In Review, review

#14867 Change the Authentication mechanism for fleet.
  x-pack/agent/pkg/fleetapi/client.go
  x-pack/agent/pkg/fleetapi/client_test.go
  x-pack/agent/pkg/fleetapi/round_trippers.go
Labels: Project:fleet, [zube]: In Review, review

#14833 Cherry-pick #14702 to 7.5: Fix rds metricset from reporting the same value for different instances
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/rds/_meta/fields.yml
  x-pack/metricbeat/module/aws/rds/data.go
  x-pack/metricbeat/module/aws/rds/rds.go
  x-pack/metricbeat/module/aws/rds/rds_test.go
Labels: backport, review

#14840 [Filebeat] Create ActiveMQ module
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/activemq.asciidoc
  filebeat/docs/modules_list.asciidoc
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/include/list.go
  x-pack/filebeat/module/activemq/_meta/config.yml
  x-pack/filebeat/module/activemq/_meta/docs.asciidoc
  x-pack/filebeat/module/activemq/_meta/fields.yml
  x-pack/filebeat/module/activemq/audit/_meta/fields.yml
  x-pack/filebeat/module/activemq/audit/config/audit.yml
  x-pack/filebeat/module/activemq/audit/ingest/pipeline.yml
  x-pack/filebeat/module/activemq/audit/manifest.yml
  x-pack/filebeat/module/activemq/audit/test/audit.log
  x-pack/filebeat/module/activemq/audit/test/audit.log-expected.json
  x-pack/filebeat/module/activemq/fields.go
  x-pack/filebeat/module/activemq/log/_meta/fields.yml
  x-pack/filebeat/module/activemq/log/config/log.yml
  x-pack/filebeat/module/activemq/log/ingest/pipeline.yml
  x-pack/filebeat/module/activemq/log/manifest.yml
  x-pack/filebeat/module/activemq/log/test/activemq.log
  x-pack/filebeat/module/activemq/log/test/activemq.log-expected.json
  x-pack/filebeat/module/activemq/module.yml
  x-pack/filebeat/modules.d/activemq.yml.disabled
  x-pack/metricbeat/module/activemq/_meta/Dockerfile
Labels: Team:Integrations, [zube]: In Review, in progress, module, needs_backport, review

#14881 Update docs for 7.5.0
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, review, v7.5.0

#14715 Google-pubsub: ACK msgs when acknowledged by publisher
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-google-pubsub.asciidoc
  x-pack/filebeat/input/googlepubsub/input.go
  x-pack/filebeat/input/googlepubsub/pubsub_test.go
Labels: Filebeat, Team:SIEM, enhancement, review

#14240 Bump version to 7.5.1
  libbeat/version/version.go
Labels: in progress, release, review, v7.5.1

#14805 [Heartbeat] Document the user agent sent by heartbeat
  heartbeat/docs/heartbeat-options.asciidoc
Labels: :uptime, Heartbeat, docs

#14748 Use dashes instead of spaces in UA
  CHANGELOG.next.asciidoc
  libbeat/common/useragent/useragent.go
  libbeat/common/useragent/useragent_test.go
Labels: :uptime, Filebeat, Heartbeat, bug, v8.0.0

#14883 [Heartbeat] Document the user agent sent by heartbeat (#14805)
  heartbeat/docs/heartbeat-options.asciidoc
Labels: :uptime, Heartbeat, backport, docs, v7.6.0

#14885 Cherry-pick #14796 to 7.x: Create extra set of UBI based images
  dev-tools/mage/dockerbuilder.go
  dev-tools/packaging/packages.yml
Labels: backport, review

#14884 Cherry-pick #14384 to 7.x: Update Go to 1.13.4
  .go-version
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: backport, review

#14888 [DOCS] Adds security fixes to release notes
  CHANGELOG.asciidoc
Labels: docs, v7.5.0

#14749 [Heartbeat] Use dashes for heartbeat HTTP user agent.
  CHANGELOG.next.asciidoc
  heartbeat/monitors/active/http/task.go
  heartbeat/monitors/active/http/task_test.go
  libbeat/common/useragent/useragent.go
  libbeat/common/useragent/useragent_test.go
  x-pack/filebeat/input/googlepubsub/input.go
  x-pack/filebeat/input/httpjson/input.go
Labels: :uptime, Heartbeat, bug, v7.6.0

#14891 [Heartbeat] Add changelog/docs for new scheduler
  CHANGELOG.next.asciidoc
  heartbeat/docs/heartbeat-options.asciidoc
Labels: :uptime, Heartbeat, bug, docs, enhancement, needs_edit

#14868 [DOCS] Fixes security link
  libbeat/docs/security/securing-beats.asciidoc
Labels: docs, v6.3.3, v6.4.4, v6.5.5, v6.6.3, v6.7.3, v6.8.6

#14812 [7.x][DOCS] Backport: Remove asciidoctor flag because it's the default now (#14774)
  script/build_docs.sh
Labels: Team:Beats, backport, docs, v7.6.0

#14813 [7.5][DOCS] Backport: Remove asciidoctor flag because it's the default now (#14774)
  script/build_docs.sh
Labels: Team:Beats, backport, docs, v7.5.0

#14423 Add missing docs for copy_fields and truncate_fields
  libbeat/docs/processors-list.asciidoc
  libbeat/processors/actions/docs/copy_fields.asciidoc
  libbeat/processors/actions/docs/truncate_fields.asciidoc
Labels: Team:Beats, docs, in progress, libbeat, needs_backport, needs_edit

#14797 Additional check on flag ignore_non_existent_counters if the PdhExpandWildCardPathW returns no errors
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/perfmon.go
  metricbeat/module/windows/perfmon/reader.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, needs_backport

#14880 [Filebeat] Create Kibana dashboards for the ActiveMQ module
  CHANGELOG.next.asciidoc
  filebeat/docs/images/filebeat-activemq-application-events.png
  filebeat/docs/images/filebeat-activemq-audit-events.png
  filebeat/docs/modules/activemq.asciidoc
  x-pack/filebeat/module/activemq/_meta/docs.asciidoc
  x-pack/filebeat/module/activemq/_meta/kibana/7/dashboard/Filebeat-activemq-application-events.json
  x-pack/filebeat/module/activemq/_meta/kibana/7/dashboard/Filebeat-activemq-audit-events.json
  x-pack/filebeat/module/activemq/module.yml
Labels: Team:Integrations, [zube]: In Review, module, needs_backport, review

#14903 Make independent python virtualenvs in docker
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/scripts/Makefile
  libbeat/tests/system/requirements.txt
  metricbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: refactoring, review

#14889 Rerun test_modules.py with 7.6.0 Snapshots
  filebeat/module/nginx/access/test/test-with-host.log-expected.json
Labels: Team:Integrations, review

#14909 Add missing CHANGELOG entry
  CHANGELOG.next.asciidoc
Labels: Team:Integrations, review

#14908 Cherry-pick #14840 to 7.x: [Filebeat] Create ActiveMQ module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/activemq.asciidoc
  filebeat/docs/modules_list.asciidoc
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/include/list.go
  x-pack/filebeat/module/activemq/_meta/config.yml
  x-pack/filebeat/module/activemq/_meta/docs.asciidoc
  x-pack/filebeat/module/activemq/_meta/fields.yml
  x-pack/filebeat/module/activemq/audit/_meta/fields.yml
  x-pack/filebeat/module/activemq/audit/config/audit.yml
  x-pack/filebeat/module/activemq/audit/ingest/pipeline.yml
  x-pack/filebeat/module/activemq/audit/manifest.yml
  x-pack/filebeat/module/activemq/audit/test/audit.log
  x-pack/filebeat/module/activemq/audit/test/audit.log-expected.json
  x-pack/filebeat/module/activemq/fields.go
  x-pack/filebeat/module/activemq/log/_meta/fields.yml
  x-pack/filebeat/module/activemq/log/config/log.yml
  x-pack/filebeat/module/activemq/log/ingest/pipeline.yml
  x-pack/filebeat/module/activemq/log/manifest.yml
  x-pack/filebeat/module/activemq/log/test/activemq.log
  x-pack/filebeat/module/activemq/log/test/activemq.log-expected.json
  x-pack/filebeat/module/activemq/module.yml
  x-pack/filebeat/modules.d/activemq.yml.disabled
  x-pack/metricbeat/module/activemq/_meta/Dockerfile
Labels: backport, review

#14910 Cherry-pick #14880 to 7.x: [Filebeat] Create Kibana dashboards for the ActiveMQ module
  CHANGELOG.next.asciidoc
  filebeat/docs/images/filebeat-activemq-application-events.png
  filebeat/docs/images/filebeat-activemq-audit-events.png
  filebeat/docs/modules/activemq.asciidoc
  x-pack/filebeat/module/activemq/_meta/docs.asciidoc
  x-pack/filebeat/module/activemq/_meta/kibana/7/dashboard/Filebeat-activemq-application-events.json
  x-pack/filebeat/module/activemq/_meta/kibana/7/dashboard/Filebeat-activemq-audit-events.json
  x-pack/filebeat/module/activemq/module.yml
Labels: backport, review

#14830 Agent add support for multiples outputs
  x-pack/agent/pkg/agent/application/emitter.go
  x-pack/agent/pkg/agent/program/program.go
  x-pack/agent/pkg/agent/program/program_test.go
  x-pack/agent/pkg/agent/program/spec_test.go
  x-pack/agent/pkg/agent/program/supported.go
  x-pack/agent/pkg/agent/program/testdata/audit_config.yml
  x-pack/agent/pkg/agent/program/testdata/enabled_false.yml
  x-pack/agent/pkg/agent/program/testdata/enabled_output_false.yml
  x-pack/agent/pkg/agent/program/testdata/enabled_output_true.yml
  x-pack/agent/pkg/agent/program/testdata/enabled_true.yml
  x-pack/agent/pkg/agent/program/testdata/journal_config.yml
  x-pack/agent/pkg/agent/program/testdata/monitor_config-heartbeat.yml
  x-pack/agent/pkg/agent/program/testdata/monitor_config.yml
  x-pack/agent/pkg/agent/program/testdata/multiple_output_true.yml
  x-pack/agent/pkg/agent/program/testdata/single_config.yml
  x-pack/agent/pkg/agent/transpiler/ast.go
  x-pack/agent/pkg/agent/transpiler/rules.go
  x-pack/agent/spec/auditbeat.yml
  x-pack/agent/spec/filebeat.yml
  x-pack/agent/spec/heartbeat.yml
  x-pack/agent/spec/journalbeat.yml
  x-pack/agent/spec/metricbeat.yml
Labels: Project:fleet, [zube]: In Review, review

#14826 Cherry-pick #14755 to 7.x: use event.timezone if defined in haproxy ingest pipeline
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/haproxy.asciidoc
  filebeat/module/haproxy/_meta/docs.asciidoc
  filebeat/module/haproxy/log/config/file.yml
  filebeat/module/haproxy/log/config/syslog.yml
  filebeat/module/haproxy/log/ingest/pipeline.json
  filebeat/module/haproxy/log/test/default.log-expected.json
  filebeat/module/haproxy/log/test/haproxy.log-expected.json
  filebeat/module/haproxy/log/test/httplog-no-headers.log-expected.json
  filebeat/module/haproxy/log/test/tcplog.log-expected.json
Labels: backport, review

#14912 Pass PYTHON_EXE when integration tests are executed from mage
  dev-tools/mage/integtest.go
Labels: review

#14892 Add Beats 7.5 highlights
  libbeat/docs/release-notes/highlights/highlights-7.5.0.asciidoc
Labels: Team:Beats, docs, needs_backport, review

#14738 Refactor kubernetes autodiscover to enable different resource based discovery
  CHANGELOG.next.asciidoc
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/filebeat/filebeat-configmap.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  libbeat/autodiscover/providers/kubernetes/config.go
  libbeat/autodiscover/providers/kubernetes/config_test.go
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
  libbeat/autodiscover/providers/kubernetes/node.go
  libbeat/autodiscover/providers/kubernetes/node_test.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/autodiscover/providers/kubernetes/service.go
  libbeat/autodiscover/providers/kubernetes/service_test.go
  libbeat/common/kubernetes/types.go
  libbeat/common/kubernetes/watcher.go
  libbeat/docs/shared-autodiscover.asciidoc
Labels: Team:Integrations, [zube]: In Review, autodiscovery, enhancement, test-plan, v7.6.0

#14916 Cherry-pick #14797 to 7.5:Additional check on flag ignore_non_existent_counters if the PdhExpandWildCardPathW returns no errors
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/perfmon.go
  metricbeat/module/windows/perfmon/reader.go
Labels: Team:Integrations, [zube]: In Review, backport, v7.5.1

#14918 Cherry-pick #14797 to 7.x:Additional check on flag ignore_non_existent_counters if the PdhExpandWildCardPathW returns no errors
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/perfmon.go
  metricbeat/module/windows/perfmon/reader.go
Labels: Team:Integrations, [zube]: In Review, backport, v7.6.0

#14924 Cherry-pick #14738 to 7.x: Refactor kubernetes autodiscover to enable different resource based discovery
  CHANGELOG.next.asciidoc
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/filebeat/filebeat-configmap.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  libbeat/autodiscover/providers/kubernetes/config.go
  libbeat/autodiscover/providers/kubernetes/config_test.go
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
  libbeat/autodiscover/providers/kubernetes/node.go
  libbeat/autodiscover/providers/kubernetes/node_test.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/autodiscover/providers/kubernetes/service.go
  libbeat/autodiscover/providers/kubernetes/service_test.go
  libbeat/common/kubernetes/types.go
  libbeat/common/kubernetes/watcher.go
  libbeat/docs/shared-autodiscover.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport, review

#14932 [Fleet] Tokenbucket fix
  x-pack/agent/pkg/tokenbucket/token_bucket_test.go
Labels: Project:fleet, agent

#14828 [Docker Log driver] Expand testing, add mocking tooling
  x-pack/dockerlogbeat/pipelinemanager/clientLogReader.go
  x-pack/dockerlogbeat/pipelinemanager/clientLogReader_test.go
  x-pack/dockerlogbeat/pipelinemanager/pipelineManager.go
  x-pack/dockerlogbeat/pipelinemock/pipelines.go
  x-pack/dockerlogbeat/pipelinemock/reader.go
  x-pack/dockerlogbeat/pipereader/reader_test.go
Labels: Team:Integrations, [zube]: In Review

#14913 [Docker Log Driver] Add common targets to mage
  x-pack/dockerlogbeat/magefile.go
Labels: Team:Integrations, [zube]: In Review

#14712 Cherry-pick #14628 to 7.x: Expose all netflow input options through netflow module
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-common-udp-options.asciidoc
  filebeat/docs/modules/netflow.asciidoc
  filebeat/fileset/fileset.go
  x-pack/filebeat/module/netflow/_meta/docs.asciidoc
  x-pack/filebeat/module/netflow/log/config/netflow.yml
  x-pack/filebeat/module/netflow/log/manifest.yml
  x-pack/filebeat/module/zeek/dhcp/manifest.yml
Labels: backport, review

#14911 [metricbeat] correct fields doc for diskio avg_size
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/diskio/_meta/fields.yml
  metricbeat/module/system/fields.go
Labels: Team:Integrations, [zube]: In Review, needs_backport, v7.5.1, v7.6.0

#14940 Cherry-pick #14928 to 7.x: Add missing UBI images for heartbeat, journalbeat, packetbeat
  dev-tools/packaging/packages.yml
Labels: backport, review

#14871 Add required API calls to retrieve configuration from Fleet.
  x-pack/agent/pkg/fleetapi/action.go
  x-pack/agent/pkg/fleetapi/checkin_cmd.go
  x-pack/agent/pkg/fleetapi/checkin_cmd_test.go
  x-pack/agent/pkg/fleetapi/client_test.go
  x-pack/agent/pkg/fleetapi/custom_type.go
  x-pack/agent/pkg/fleetapi/custom_type_test.go
  x-pack/agent/pkg/fleetapi/helper_test.go
  x-pack/agent/pkg/fleetapi/reply.go
  x-pack/agent/pkg/fleetapi/round_trippers.go
  x-pack/agent/pkg/reporter/fleet/reporter.go
  x-pack/agent/pkg/reporter/fleet/reporter_test.go
Labels: Project:fleet, [zube]: In Review, review

#14920 [7.5][DOCS] Backport: Add Beats 7.5 highlights
  libbeat/docs/release-notes/highlights/highlights-7.5.0.asciidoc
Labels: backport, docs, v7.5.0

#14921 [7x][DOCS] Backport: Add Beats 7.5 highlights
  libbeat/docs/release-notes/highlights/highlights-7.5.0.asciidoc
Labels: backport, docs, v7.6.0

#14941 Cherry-pick #14936 to 7.x: Add missing files override for docker ubi images
  dev-tools/packaging/packages.yml
Labels: backport, review

#14863 Make use of consumer_lag in dashboard
  CHANGELOG.next.asciidoc
  metricbeat/docs/images/metricbeat_kafka_dashboard.png
  metricbeat/docs/modules/kafka.asciidoc
  metricbeat/module/kafka/_meta/docs.asciidoc
  metricbeat/module/kafka/_meta/kibana/7/dashboard/Metricbeat-kafka-overview.json
Labels: :Dashboards, Metricbeat, Team:Integrations, [zube]: In Review, review, test-plan, v7.6.0

#14879 Cherry-pick #14407 to 7.x: Libbeat: Do not overwrite agent.*, ecs.version, and host.name
  CHANGELOG.next.asciidoc
  libbeat/common/mapstr.go
  libbeat/processors/actions/add_fields.go
  libbeat/processors/actions/add_labels.go
  libbeat/publisher/processing/default.go
  libbeat/publisher/processing/default_test.go
Labels: backport, libbeat, review

#14707 Cherry-pick #14368 to 7.x: Fix docker client in tests so it performs API version negotiation.
  libbeat/common/docker/client_test.go
  libbeat/tests/compose/wrapper.go
  libbeat/tests/docker/docker.go
  metricbeat/module/docker/event/event_integration_test.go
Labels: backport, review

#14948 Cherry-pick #14863 to 7.x: Make use of consumer_lag in dashboard
  CHANGELOG.next.asciidoc
  metricbeat/docs/images/metricbeat_kafka_dashboard.png
  metricbeat/docs/modules/kafka.asciidoc
  metricbeat/module/kafka/_meta/docs.asciidoc
  metricbeat/module/kafka/_meta/kibana/7/dashboard/Metricbeat-kafka-overview.json
Labels: Team:Integrations, [zube]: In Review, backport, review

#14945 Fakewebapi simulare a Fleet API endpoint for testing the checkin
  x-pack/agent/dev-tools/cmd/fakewebapi/README.md
  x-pack/agent/dev-tools/cmd/fakewebapi/action_example.json
  x-pack/agent/dev-tools/cmd/fakewebapi/checkin.json
  x-pack/agent/dev-tools/cmd/fakewebapi/fetch.sh
  x-pack/agent/dev-tools/cmd/fakewebapi/main.go
  x-pack/agent/dev-tools/cmd/fakewebapi/push.sh
Labels: Project:fleet, review

#14942 [Metricbeat] Add pagination to ListMetrics AWS API call
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/utils.go
Labels: Metricbeat, Team:Integrations, bug, needs_backport, review

#14939 Cherry-pick of #14911 [metricbeat] correct fields doc for diskio avg_size
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/diskio/_meta/fields.yml
  metricbeat/module/system/fields.go
Labels: Team:Integrations, backport, bug

#14943 Cherry-pick of #14911 [metricbeat] correct fields doc for diskio avg_size
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/diskio/_meta/fields.yml
  metricbeat/module/system/fields.go
Labels: Team:Integrations, backport, bug

#14956 Cherry-pick #14942 to 7.5: [Metricbeat] Add pagination to ListMetrics AWS API call
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/utils.go
Labels: backport, review

#14955 Cherry-pick #14942 to 7.x: [Metricbeat] Add pagination to ListMetrics AWS API call
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/utils.go
Labels: backport, review

#14930 * Fixes #14906 - Kafka output dropping messages due to size, but doesn’t increment the “failed” counter.
  libbeat/outputs/kafka/client.go
Labels: libbeat

#14946 [Metricbeat] [AWS] Create a metricset for SNS
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  metricbeat/docs/modules/aws/sns.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/module.yml
  x-pack/metricbeat/module/aws/sns/_meta/data.json
  x-pack/metricbeat/module/aws/sns/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/sns/_meta/fields.yml
  x-pack/metricbeat/module/aws/sns/manifest.yml
  x-pack/metricbeat/module/aws/sns/sns_integration_test.go
  x-pack/metricbeat/module/aws/sns/sns_test.go
Labels: Team:Integrations, [zube]: In Review, needs_backport, review, skip-test-plan

#14801 [Metricbeat] Add billing metricset for aws module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/images/metricbeat-aws-billing-overview.png
  metricbeat/docs/modules/aws.asciidoc
  metricbeat/docs/modules/aws/billing.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-billing-overview.json
  x-pack/metricbeat/module/aws/billing/_meta/data.json
  x-pack/metricbeat/module/aws/billing/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/billing/_meta/fields.yml
  x-pack/metricbeat/module/aws/billing/billing_integration_test.go
  x-pack/metricbeat/module/aws/billing/billing_test.go
  x-pack/metricbeat/module/aws/billing/manifest.yml
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/module.yml
Labels: Metricbeat, Team:Integrations, [zube]: In Review, needs_backport, review, test-plan

#14960 [6.8] Fix license ID field name (#14592)
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/elasticsearch.go
Labels: backport

#14980 Cherry-pick #14946 to 7.x: [Metricbeat] [AWS] Create a metricset for SNS
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  metricbeat/docs/modules/aws/sns.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/module.yml
  x-pack/metricbeat/module/aws/sns/_meta/data.json
  x-pack/metricbeat/module/aws/sns/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/sns/_meta/fields.yml
  x-pack/metricbeat/module/aws/sns/manifest.yml
  x-pack/metricbeat/module/aws/sns/sns_integration_test.go
  x-pack/metricbeat/module/aws/sns/sns_test.go
Labels: backport, review

#14988 Cherry-pick #14987 to 7.x: Fix: typo 'a values'
  libbeat/docs/outputs/output-logstash.asciidoc
Labels: backport, review

#14568 Adding publisher event cache
  CHANGELOG.next.asciidoc
  filebeat/input/kafka/kafka_integration_test.go
  libbeat/outputs/kafka/client.go
  libbeat/outputs/kafka/kafka.go
  libbeat/outputs/kafka/kafka_integration_test.go
  libbeat/outputs/kafka/partition.go
  libbeat/publisher/event.go
  testing/environments/docker/kafka/run.sh
Labels: :Outputs, Team:Beats, [zube]: In Review, bug, libbeat, review, v7.5.1, v7.6.0, v8.0.0

#14958 Update Go to 1.13.5
  .go-version
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: Team:Beats, review

#14991 Cherry-pick #14958 to 7.x: Update Go to 1.13.5
  .go-version
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: Team:Beats, backport, review

#14925 [Metricbeat] Add usage metricset into aws module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/images/metricbeat-aws-usage-overview.png
  metricbeat/docs/modules/aws.asciidoc
  metricbeat/docs/modules/aws/usage.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-usage-overview.json
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/module.yml
  x-pack/metricbeat/module/aws/usage/_meta/data.json
  x-pack/metricbeat/module/aws/usage/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/usage/_meta/fields.yml
  x-pack/metricbeat/module/aws/usage/manifest.yml
  x-pack/metricbeat/module/aws/usage/usage_integration_test.go
  x-pack/metricbeat/module/aws/usage/usage_test.go
Labels: Metricbeat, Team:Integrations, needs_backport, review, test-plan

#14986 Cherry-pick #14801 to 7.x: [Metricbeat] Add billing metricset for aws module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/images/metricbeat-aws-billing-overview.png
  metricbeat/docs/modules/aws.asciidoc
  metricbeat/docs/modules/aws/billing.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-billing-overview.json
  x-pack/metricbeat/module/aws/billing/_meta/data.json
  x-pack/metricbeat/module/aws/billing/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/billing/_meta/fields.yml
  x-pack/metricbeat/module/aws/billing/billing_integration_test.go
  x-pack/metricbeat/module/aws/billing/billing_test.go
  x-pack/metricbeat/module/aws/billing/manifest.yml
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/module.yml
Labels: backport, review

#14996 [DOCS] Remove incorrect information about monitoring data routing
  libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
  libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Labels: docs, needs_backport, review

#14998 [DOCS] Comment out unwanted links
  libbeat/docs/monitoring/monitoring-beats.asciidoc
  libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Labels: docs, needs_backport

#14999 [7.5][DOCS] Backport: Remove incorrect information about monitoring data routing
  libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
  libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Labels: backport, docs, v7.5.0

#15000 [7.x][DOCS] Backport: Remove incorrect information about monitoring data routing
  libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
  libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Labels: backport, docs, v7.6.0

#15001 [7.x][DOCS] Backport: Comment out unwanted links (#14998)
  libbeat/docs/monitoring/monitoring-beats.asciidoc
  libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Labels: backport, docs, v7.6.0

#15002 [7.5][DOCS] Backport: Comment out unwanted links (#14998)
  libbeat/docs/monitoring/monitoring-beats.asciidoc
  libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Labels: backport, docs, v7.5.0

#14901 Migrate Functionbeat to Python3
  x-pack/functionbeat/tests/system/test_base.py
Labels: Functionbeat

#14929 Remove leftover encode from cherrypick_pr
  dev-tools/cherrypick_pr
Labels: review

#14800 Metricbeat perfmon - fix issues with retrieving counter paths/adding counters to query when OS language is not ENG
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/pdh_integration_windows_test.go
  metricbeat/module/windows/perfmon/pdh_query_windows.go
  metricbeat/module/windows/perfmon/pdh_query_windows_test.go
  metricbeat/module/windows/perfmon/pdh_windows.go
  metricbeat/module/windows/perfmon/pdh_windows_test.go
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/zpdh_windows.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, needs_backport

#14981 Fix default value in rollover_alias docs
  libbeat/docs/shared-ilm.asciidoc
Labels: Team:Beats, docs, needs_backport, review

#15006 Cherry-pick #14800 to 7.5:Metricbeat perfmon - fix issues with retrieving counter paths/adding counters to query when OS language is not ENG
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/pdh_integration_windows_test.go
  metricbeat/module/windows/perfmon/pdh_query_windows.go
  metricbeat/module/windows/perfmon/pdh_query_windows_test.go
  metricbeat/module/windows/perfmon/pdh_windows.go
  metricbeat/module/windows/perfmon/pdh_windows_test.go
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/zpdh_windows.go
Labels: Team:Integrations, backport, v7.5.1

#15005 Cherry-pick #14800 to 7.x:Metricbeat perfmon - fix issues with retrieving counter paths/adding counters to query when OS language is not ENG
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/pdh_integration_windows_test.go
  metricbeat/module/windows/perfmon/pdh_query_windows.go
  metricbeat/module/windows/perfmon/pdh_query_windows_test.go
  metricbeat/module/windows/perfmon/pdh_windows.go
  metricbeat/module/windows/perfmon/pdh_windows_test.go
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/zpdh_windows.go
Labels: Team:Integrations, backport, v7.6.0

#14992 [7.x] Adding publisher event cache (#14568)
  CHANGELOG.next.asciidoc
  filebeat/input/kafka/kafka_integration_test.go
  libbeat/outputs/kafka/client.go
  libbeat/outputs/kafka/kafka.go
  libbeat/outputs/kafka/kafka_integration_test.go
  libbeat/outputs/kafka/partition.go
  libbeat/publisher/event.go
  testing/environments/docker/kafka/run.sh
Labels: backport

#14993 [7.5] Adding publisher event cache (#14568)
  CHANGELOG.next.asciidoc
  filebeat/input/kafka/kafka_integration_test.go
  libbeat/outputs/kafka/client.go
  libbeat/outputs/kafka/kafka.go
  libbeat/outputs/kafka/kafka_integration_test.go
  libbeat/outputs/kafka/partition.go
  libbeat/publisher/event.go
  testing/environments/docker/kafka/run.sh
Labels: backport

#14947 [Elastic Log Plugin] Turn on Jenkins and Travis CI tests
  .travis.yml
  Jenkinsfile
  x-pack/dockerlogbeat/Makefile
  x-pack/dockerlogbeat/magefile.go
Labels: Team:Integrations

#14938 Cherry-pick #13484 to 7.5: Add o365beat to community beats list.
  libbeat/docs/communitybeats.asciidoc
Labels: backport, review

#15014 [Elastic logging plugin] Fix some old naming issues
  x-pack/dockerlogbeat/magefile.go
  x-pack/dockerlogbeat/readme.md
Labels: Team:Integrations, [zube]: In Review

#14767 Fix SSLconfig in input.yml for Filebeat httpjson input in the MISP module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/misp/threat/config/input.yml
  x-pack/filebeat/module/misp/threat/manifest.yml
Labels: Filebeat, bug, review

#14794 [metricbeat]kubernetes kube-state-metrics service
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/docs/modules/kubernetes/state_service.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/helper/prometheus/metric.go
  metricbeat/helper/prometheus/prometheus.go
  metricbeat/helper/prometheus/prometheus_test.go
  metricbeat/include/list_docker.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/_meta/config.yml
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_service/README.md
  metricbeat/module/kubernetes/state_service/_meta/data.json
  metricbeat/module/kubernetes/state_service/_meta/docs.asciidoc
  metricbeat/module/kubernetes/state_service/_meta/fields.yml
  metricbeat/module/kubernetes/state_service/_meta/test/ksm-unit-1.8
  metricbeat/module/kubernetes/state_service/_meta/test/ksm-unit-1.8.expected
  metricbeat/module/kubernetes/state_service/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_service/_meta/testdata/kube-state-metrics.1.7.plain
  metricbeat/module/kubernetes/state_service/_meta/testdata/kube-state-metrics.1.7.plain-expected.json
  metricbeat/module/kubernetes/state_service/state_service.go
  metricbeat/module/kubernetes/state_service/state_service_test.go
  metricbeat/module/kubernetes/state_service/svc-out.txt
  metricbeat/modules.d/kubernetes.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Metricbeat, Team:Integrations, [zube]: In Review, containers, review

#15009 Cherry-pick #14981 to 7.5: Fix default value in rollover_alias…
  libbeat/docs/shared-ilm.asciidoc
Labels: Team:Beats, backport, docs, review

#15018 Add the Tokenizer field
  libbeat/processors/dissect/docs/dissect.asciidoc
Labels: [zube]: In Review, docs, needs_backport, review

#14962 Assert Trial in the licenser integration test
  x-pack/libbeat/licenser/elastic_fetcher_integration_test.go
Labels: Team:Beats, [zube]: In Review, review

#15025 Cherry-pick #15018 to 7.x: Add the Tokenizer field
  libbeat/processors/dissect/docs/dissect.asciidoc
Labels: Team:Beats, [zube]: In Review, backport, review

#15017 [libbeat] Create a LoadWithSettings pipeline constructor that exposes WaitTime settingss
  libbeat/publisher/pipeline/module.go
Labels: Team:Integrations, libbeat

#15023 [Filebeat] Add example to CoreDNS filebeat module docs
  filebeat/docs/modules/coredns.asciidoc
  x-pack/filebeat/module/coredns/_meta/docs.asciidoc
Labels: Team:Integrations, [zube]: In Review, docs

#14950 Fix proxy_url option in Elasticsearch output
  CHANGELOG.next.asciidoc
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/outputs/elasticsearch/elasticsearch.go
Labels: Team:Beats, [zube]: In Review, needs_backport, review, v7.5.1, v7.6.0

#15032 [Elastic logging driver] Trim slashes from container names and fix beat name
  x-pack/dockerlogbeat/pipelinemanager/clientLogReader.go
  x-pack/dockerlogbeat/pipelinemanager/clientLogReader_test.go
  x-pack/dockerlogbeat/pipelinemanager/libbeattools.go
Labels: Team:Integrations

#15020 [DOCS] Added older release notice.
  auditbeat/docs/page_header.html
  docs/devguide/page_header.html
  filebeat/docs/page_header.html
  heartbeat/docs/page_header.html
  journalbeat/docs/page_header.html
  libbeat/docs/page_header.html
  metricbeat/docs/page_header.html
  packetbeat/docs/page_header.html
  winlogbeat/docs/page_header.html
  x-pack/functionbeat/docs/page_header.html
Labels: docs, v6.8.6

#14524 Add ID processor
  CHANGELOG.next.asciidoc
  libbeat/docs/processors-list.asciidoc
  libbeat/processors/add_id/add_id.go
  libbeat/processors/add_id/add_id_test.go
  libbeat/processors/add_id/config.go
  libbeat/processors/add_id/docs/add_id.asciidoc
  libbeat/processors/add_id/errors.go
  libbeat/processors/add_id/generator/errors.go
  libbeat/processors/add_id/generator/es_generator.go
  libbeat/processors/add_id/generator/es_generator_test.go
  libbeat/processors/add_id/generator/generator.go
  libbeat/processors/add_id/generator/generator_test.go
  libbeat/processors/add_id/generator/mac.go
  libbeat/processors/add_id/generator/mac_test.go
Labels: :Processors, Team:Beats, [zube]: In Review, libbeat, review, v7.6.0, v8.0.0

#15034 Cherry-pick #15023 to 7.x: [Filebeat] Add example to CoreDNS filebeat module docs
  filebeat/docs/modules/coredns.asciidoc
  x-pack/filebeat/module/coredns/_meta/docs.asciidoc
Labels: backport, review

#14235 Modifying test fields for the filebeat azure filesets
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/azure/_meta/fields.yml
  x-pack/filebeat/module/azure/activitylogs/_meta/fields.yml
  x-pack/filebeat/module/azure/activitylogs/config/file.yml
  x-pack/filebeat/module/azure/activitylogs/config/kafka.yml
  x-pack/filebeat/module/azure/activitylogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/activitylogs/manifest.yml
  x-pack/filebeat/module/azure/activitylogs/test/activity_log.json
  x-pack/filebeat/module/azure/activitylogs/test/activity_log_expected.json
  x-pack/filebeat/module/azure/activitylogs/test/activitylogs.log
  x-pack/filebeat/module/azure/activitylogs/test/activitylogs.log-expected.json
  x-pack/filebeat/module/azure/auditlogs/_meta/fields.yml
  x-pack/filebeat/module/azure/auditlogs/config/file.yml
  x-pack/filebeat/module/azure/auditlogs/config/kafka.yml
  x-pack/filebeat/module/azure/auditlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/auditlogs/manifest.yml
  x-pack/filebeat/module/azure/auditlogs/test/audit_log.json
  x-pack/filebeat/module/azure/auditlogs/test/audit_log_expected.json
  x-pack/filebeat/module/azure/auditlogs/test/auditlogs.log
  x-pack/filebeat/module/azure/auditlogs/test/auditlogs.log-expected.json
  x-pack/filebeat/module/azure/fields.go
  x-pack/filebeat/module/azure/signinlogs/_meta/fields.yml
  x-pack/filebeat/module/azure/signinlogs/config/file.yml
  x-pack/filebeat/module/azure/signinlogs/config/kafka.yml
  x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/signinlogs/manifest.yml
  x-pack/filebeat/module/azure/signinlogs/test/signin_log.json
  x-pack/filebeat/module/azure/signinlogs/test/signin_log_expected.json
  x-pack/filebeat/module/azure/signinlogs/test/signinlogs.log
  x-pack/filebeat/module/azure/signinlogs/test/signinlogs.log-expected.json
Labels: Filebeat, Team:Integrations, [zube]: In Progress, needs_backport

#14977 [Metricbeat] Create dashboard for AWS SNS metricset
  metricbeat/docs/images/metricbeat-aws-sns-overview.png
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-sns-overview.json
  x-pack/metricbeat/module/aws/sns/_meta/docs.asciidoc
Labels: Team:Integrations, [zube]: In Review, needs_backport, review

#15036 Cherry-pick #14950 to 7.x: Fix proxy_url option in Elasticsearch output
  CHANGELOG.next.asciidoc
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/outputs/elasticsearch/elasticsearch.go
Labels: backport, review

#15044 Cherry-pick #14977 to 7.x: [Metricbeat] Create dashboard for AWS SNS metricset
  metricbeat/docs/images/metricbeat-aws-sns-overview.png
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-sns-overview.json
  x-pack/metricbeat/module/aws/sns/_meta/docs.asciidoc
Labels: backport, review

#14679 Cherry-pick #14637 to 7.x: Fix typo in metricbeat hints documentation
  metricbeat/docs/autodiscover-hints.asciidoc
Labels: backport, review

#15045 Update CHANGELOG to PR#14977
  CHANGELOG.next.asciidoc
Labels: Team:Integrations, review

#13257 [Metricbeat] [WIP] Add SQL module (#13106)
  CHANGELOG.next.asciidoc
  NOTICE.txt
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/sql.asciidoc
  metricbeat/docs/modules/sql/query.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/sql/_meta/config.yml
  x-pack/metricbeat/module/sql/_meta/docs.asciidoc
  x-pack/metricbeat/module/sql/_meta/fields.yml
  x-pack/metricbeat/module/sql/doc.go
  x-pack/metricbeat/module/sql/fields.go
  x-pack/metricbeat/module/sql/query/_meta/data.json
  x-pack/metricbeat/module/sql/query/_meta/docs.asciidoc
  x-pack/metricbeat/module/sql/query/_meta/fields.yml
  x-pack/metricbeat/module/sql/query/query.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/LICENSE
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/README.md
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/bind.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/doc.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/go.mod
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/go.sum
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/named.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/named_context.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/reflectx/README.md
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/reflectx/reflect.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/sqlx.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/sqlx_context.go
  x-pack/metricbeat/module/sql/vendor/vendor.json
  x-pack/metricbeat/modules.d/sql.yml.disabled
Labels: Metricbeat, Team:Integrations, [zube]: In Progress, enhancement, in progress, module, needs_backport, v7.6.0

#15050 Cherry-pick #15045 to 7.x: Update CHANGELOG to PR#14977
  CHANGELOG.next.asciidoc
Labels: backport, review

#15041 [7.x] Add ID processor (#14524)
  CHANGELOG.next.asciidoc
  libbeat/docs/processors-list.asciidoc
  libbeat/processors/add_id/add_id.go
  libbeat/processors/add_id/add_id_test.go
  libbeat/processors/add_id/config.go
  libbeat/processors/add_id/docs/add_id.asciidoc
  libbeat/processors/add_id/errors.go
  libbeat/processors/add_id/generator/errors.go
  libbeat/processors/add_id/generator/es_generator.go
  libbeat/processors/add_id/generator/es_generator_test.go
  libbeat/processors/add_id/generator/generator.go
  libbeat/processors/add_id/generator/generator_test.go
  libbeat/processors/add_id/generator/mac.go
  libbeat/processors/add_id/generator/mac_test.go
Labels: backport

#15042 Cherry-pick #14235 to 7.x:Modifying test fields for the filebeat azure filesets
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/azure/_meta/fields.yml
  x-pack/filebeat/module/azure/activitylogs/_meta/fields.yml
  x-pack/filebeat/module/azure/activitylogs/config/file.yml
  x-pack/filebeat/module/azure/activitylogs/config/kafka.yml
  x-pack/filebeat/module/azure/activitylogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/activitylogs/manifest.yml
  x-pack/filebeat/module/azure/activitylogs/test/activity_log.json
  x-pack/filebeat/module/azure/activitylogs/test/activity_log_expected.json
  x-pack/filebeat/module/azure/activitylogs/test/activitylogs.log
  x-pack/filebeat/module/azure/activitylogs/test/activitylogs.log-expected.json
  x-pack/filebeat/module/azure/auditlogs/_meta/fields.yml
  x-pack/filebeat/module/azure/auditlogs/config/file.yml
  x-pack/filebeat/module/azure/auditlogs/config/kafka.yml
  x-pack/filebeat/module/azure/auditlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/auditlogs/manifest.yml
  x-pack/filebeat/module/azure/auditlogs/test/audit_log.json
  x-pack/filebeat/module/azure/auditlogs/test/audit_log_expected.json
  x-pack/filebeat/module/azure/auditlogs/test/auditlogs.log
  x-pack/filebeat/module/azure/auditlogs/test/auditlogs.log-expected.json
  x-pack/filebeat/module/azure/fields.go
  x-pack/filebeat/module/azure/signinlogs/_meta/fields.yml
  x-pack/filebeat/module/azure/signinlogs/config/file.yml
  x-pack/filebeat/module/azure/signinlogs/config/kafka.yml
  x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/signinlogs/manifest.yml
  x-pack/filebeat/module/azure/signinlogs/test/signin_log.json
  x-pack/filebeat/module/azure/signinlogs/test/signin_log_expected.json
  x-pack/filebeat/module/azure/signinlogs/test/signinlogs.log
  x-pack/filebeat/module/azure/signinlogs/test/signinlogs.log-expected.json
Labels: Team:Integrations, backport, v7.6.0

#15038 [Elastic Logging Plugin] Use LoadWithSettings and clean up pipeline code
  x-pack/dockerlogbeat/pipelinemanager/libbeattools.go
  x-pack/dockerlogbeat/pipelinemanager/pipelineManager.go
Labels: Team:Integrations

#14835 [Agent] Grpc support for agent to beat communication
  filebeat/beater/filebeat.go
  filebeat/filebeat.spec
  libbeat/cmd/instance/beat.go
  libbeat/management/management.go
  x-pack/agent/pkg/agent/configrequest/step.go
  x-pack/agent/pkg/agent/operation/operator_handlers.go
  x-pack/filebeat/filebeat.spec
  x-pack/libbeat/cmd/inject.go
  x-pack/libbeat/management/config.go
  x-pack/libbeat/management/error.go
  x-pack/libbeat/management/error_test.go
  x-pack/libbeat/management/fleet/config.go
  x-pack/libbeat/management/fleet/config_server.go
  x-pack/libbeat/management/fleet/manager.go
  x-pack/libbeat/management/fleet/manager_test.go
  x-pack/libbeat/management/fleet/plugin.go
  x-pack/libbeat/management/manager.go
  x-pack/libbeat/management/manager_test.go
  x-pack/libbeat/management/plugin.go
  x-pack/metricbeat/metricbeat.spec
Labels: Project:fleet, [zube]: In Review, agent, review

#15037 Cherry-pick #14950 to 7.5: Fix proxy_url option in Elasticsearch output
  CHANGELOG.next.asciidoc
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/outputs/elasticsearch/elasticsearch.go
Labels: backport, review

#15043 Cherry-pick #14235 to 7.5:Modifying test fields for the filebeat azure filesets
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/azure/_meta/fields.yml
  x-pack/filebeat/module/azure/activitylogs/_meta/fields.yml
  x-pack/filebeat/module/azure/activitylogs/config/file.yml
  x-pack/filebeat/module/azure/activitylogs/config/kafka.yml
  x-pack/filebeat/module/azure/activitylogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/activitylogs/manifest.yml
  x-pack/filebeat/module/azure/activitylogs/test/activity_log.json
  x-pack/filebeat/module/azure/activitylogs/test/activity_log_expected.json
  x-pack/filebeat/module/azure/activitylogs/test/activitylogs.log
  x-pack/filebeat/module/azure/activitylogs/test/activitylogs.log-expected.json
  x-pack/filebeat/module/azure/auditlogs/_meta/fields.yml
  x-pack/filebeat/module/azure/auditlogs/config/file.yml
  x-pack/filebeat/module/azure/auditlogs/config/kafka.yml
  x-pack/filebeat/module/azure/auditlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/auditlogs/manifest.yml
  x-pack/filebeat/module/azure/auditlogs/test/audit_log.json
  x-pack/filebeat/module/azure/auditlogs/test/audit_log_expected.json
  x-pack/filebeat/module/azure/auditlogs/test/auditlogs.log
  x-pack/filebeat/module/azure/auditlogs/test/auditlogs.log-expected.json
  x-pack/filebeat/module/azure/fields.go
  x-pack/filebeat/module/azure/signinlogs/_meta/fields.yml
  x-pack/filebeat/module/azure/signinlogs/config/file.yml
  x-pack/filebeat/module/azure/signinlogs/config/kafka.yml
  x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/signinlogs/manifest.yml
  x-pack/filebeat/module/azure/signinlogs/test/signin_log.json
  x-pack/filebeat/module/azure/signinlogs/test/signin_log_expected.json
  x-pack/filebeat/module/azure/signinlogs/test/signinlogs.log
  x-pack/filebeat/module/azure/signinlogs/test/signinlogs.log-expected.json
Labels: Team:Integrations, backport, v7.5.1

#15011 [Metricbeat] Fix: mixed modules fail loading standard and light metricsets
  metricbeat/mb/lightmodules.go
  metricbeat/mb/lightmodules_test.go
  metricbeat/mb/registry.go
  metricbeat/mb/testdata/lightmodules/mixed/light/manifest.yml
  metricbeat/mb/testdata/lightmodules/mixed/module.yml
  metricbeat/mb/testdata/lightmodules/mixed/standard/.placeholder
  metricbeat/mb/testdata/lightmodules/mixedbroken/light/manifest.yml
  metricbeat/mb/testdata/lightmodules/mixedbroken/module.yml
  metricbeat/mb/testdata/lightmodules/mixedbroken/unregistered/.placeholder
Labels: Team:Integrations, [zube]: In Review

#15016 Rename TEST-empty.xml to .out
  dev-tools/jenkins_ci.ps1
  dev-tools/jenkins_ci.sh
Labels: Team:Integrations, [zube]: In Review, v7.6.0

#15061 Cherry-pick #15011 to 7.x: Registered metricsets fail to load if listed as light modules
  metricbeat/mb/lightmodules.go
  metricbeat/mb/lightmodules_test.go
  metricbeat/mb/registry.go
  metricbeat/mb/testdata/lightmodules/mixed/light/manifest.yml
  metricbeat/mb/testdata/lightmodules/mixed/module.yml
  metricbeat/mb/testdata/lightmodules/mixed/standard/.placeholder
  metricbeat/mb/testdata/lightmodules/mixedbroken/light/manifest.yml
  metricbeat/mb/testdata/lightmodules/mixedbroken/module.yml
  metricbeat/mb/testdata/lightmodules/mixedbroken/unregistered/.placeholder
Labels: backport, review

#15068 [Metricbeat] [ActiveMQ] Flaky test: wait for all messages to be enqueued
  x-pack/metricbeat/module/activemq/test_activemq.py
Labels: Metricbeat, Team:Integrations, flaky-test, review

#15074 Add missing CHANGELOG entry
  CHANGELOG.next.asciidoc
Labels: Metricbeat, Team:Integrations, review

#15076 Cherry-pick #15074 to 7.x: Add missing CHANGELOG entry
  CHANGELOG.next.asciidoc
Labels: backport, review

#15073 Cherry-pick #15068 to 7.x: [Metricbeat] [ActiveMQ] Flaky test: wait for all messages to be enqueued
  x-pack/metricbeat/tests/system/test_activemq.py
Labels: backport, review

#15069 Docker image build isolation
  dev-tools/mage/dockerbuilder.go
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgtypes.go
  dev-tools/packaging/package_test.go
Labels: :Packaging, Team:Beats, bug, review

#15070 [metricbeat] Fallback to different CPU calculation if we have no online_cpu count
  CHANGELOG.next.asciidoc
  metricbeat/module/docker/cpu/helper.go
Labels: bug, needs_backport, v7.5.1

#15058 [libbeat] move Docker helpers to libbeat, add some godocs
  libbeat/common/docker/helpers.go
  metricbeat/module/docker/config.go
  metricbeat/module/docker/container/data.go
  metricbeat/module/docker/docker.go
  metricbeat/module/docker/helper.go
  metricbeat/module/docker/helper_test.go
  metricbeat/module/docker/image/data.go
Labels: Team:Integrations, libbeat

#15051 Cherry-pick #13257 to 7.x: [Metricbeat] [WIP] Add SQL module (#13106)
  CHANGELOG.next.asciidoc
  NOTICE.txt
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/sql.asciidoc
  metricbeat/docs/modules/sql/query.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/sql/_meta/config.yml
  x-pack/metricbeat/module/sql/_meta/docs.asciidoc
  x-pack/metricbeat/module/sql/_meta/fields.yml
  x-pack/metricbeat/module/sql/doc.go
  x-pack/metricbeat/module/sql/fields.go
  x-pack/metricbeat/module/sql/query/_meta/data.json
  x-pack/metricbeat/module/sql/query/_meta/docs.asciidoc
  x-pack/metricbeat/module/sql/query/_meta/fields.yml
  x-pack/metricbeat/module/sql/query/query.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/LICENSE
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/README.md
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/bind.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/doc.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/go.mod
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/go.sum
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/named.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/named_context.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/reflectx/README.md
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/reflectx/reflect.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/sqlx.go
  x-pack/metricbeat/module/sql/vendor/github.com/jmoiron/sqlx/sqlx_context.go
  x-pack/metricbeat/module/sql/vendor/vendor.json
  x-pack/metricbeat/modules.d/sql.yml.disabled
Labels: backport, review

#15079 Cherry-pick #15069 to 7.x: Docker image build isolation
  dev-tools/mage/dockerbuilder.go
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgtypes.go
  dev-tools/packaging/package_test.go
Labels: Team:Beats, backport, bug, review, v7.6.0

#15008 Cherry-pick #14981 to 7.x: Fix default value in rollover_alias…
  libbeat/docs/shared-ilm.asciidoc
Labels: Team:Beats, backport, docs, review

#15082 Cherry-pick #15070 to 7.5: fallback to different CPU calculation if we have no online_cpu count
  CHANGELOG.next.asciidoc
  metricbeat/module/docker/cpu/helper.go
Labels: backport, bug, v7.5.1

#12973 [libbeat] Enable TLS 1.3
  filebeat/tests/system/test_tcp_tls.py
  libbeat/common/transport/tlscommon/tls_test.go
  libbeat/common/transport/tlscommon/types.go
  libbeat/docs/shared-ssl-config.asciidoc
Labels: Team:Beats, [zube]: In Review, libbeat

#15071 Journalbeat: add index option to input
  filebeat/channel/connector.go
  journalbeat/beater/journalbeat.go
  journalbeat/docs/config-options.asciidoc
  journalbeat/input/config.go
  journalbeat/input/input.go
  journalbeat/input/input_test.go
  libbeat/processors/add_formatted_index/add_formatted_index.go
  libbeat/processors/processor.go
Labels: Journalbeat, Team:Beats, enhancement, libbeat, needs_backport, review, v7.6.0, v8.0.0

#14839 [Metricbeat] Add STAN (NATS streaming) module
  CHANGELOG.next.asciidoc
  dev-tools/mage/gotest.go
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/stan.asciidoc
  metricbeat/docs/modules/stan/channels.asciidoc
  metricbeat/docs/modules/stan/stats.asciidoc
  metricbeat/docs/modules/stan/subscriptions.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/stan/_meta/Dockerfile
  x-pack/metricbeat/module/stan/_meta/config.reference.yml
  x-pack/metricbeat/module/stan/_meta/config.yml
  x-pack/metricbeat/module/stan/_meta/docs.asciidoc
  x-pack/metricbeat/module/stan/_meta/fields.yml
  x-pack/metricbeat/module/stan/_meta/run.sh
  x-pack/metricbeat/module/stan/channels/_meta/data.json
  x-pack/metricbeat/module/stan/channels/_meta/docs.asciidoc
  x-pack/metricbeat/module/stan/channels/_meta/fields.yml
  x-pack/metricbeat/module/stan/channels/_meta/test/channels.json
  x-pack/metricbeat/module/stan/channels/channels.go
  x-pack/metricbeat/module/stan/channels/channels_integration_test.go
  x-pack/metricbeat/module/stan/channels/channels_test.go
  x-pack/metricbeat/module/stan/channels/data.go
  x-pack/metricbeat/module/stan/doc.go
  x-pack/metricbeat/module/stan/docker-compose.yml
  x-pack/metricbeat/module/stan/fields.go
  x-pack/metricbeat/module/stan/module.yml
  x-pack/metricbeat/module/stan/stats/_meta/data.json
  x-pack/metricbeat/module/stan/stats/_meta/docs.asciidoc
  x-pack/metricbeat/module/stan/stats/_meta/fields.yml
  x-pack/metricbeat/module/stan/stats/_meta/test/serversz.json
  x-pack/metricbeat/module/stan/stats/data.go
  x-pack/metricbeat/module/stan/stats/docs.asciidoc
  x-pack/metricbeat/module/stan/stats/stats.go
  x-pack/metricbeat/module/stan/stats/stats_integration_test.go
  x-pack/metricbeat/module/stan/stats/stats_test.go
  x-pack/metricbeat/module/stan/subscriptions/_meta/data.json
  x-pack/metricbeat/module/stan/subscriptions/_meta/docs.asciidoc
  x-pack/metricbeat/module/stan/subscriptions/_meta/fields.yml
  x-pack/metricbeat/module/stan/subscriptions/_meta/test/subscriptions.json
  x-pack/metricbeat/module/stan/subscriptions/data.go
  x-pack/metricbeat/module/stan/subscriptions/subscriptions.go
  x-pack/metricbeat/module/stan/subscriptions/subscriptions_integration_test.go
  x-pack/metricbeat/module/stan/subscriptions/subscriptions_test.go
  x-pack/metricbeat/module/stan/test_stan.py
  x-pack/metricbeat/modules.d/stan.yml.disabled
Labels: Metricbeat, Team:Integrations, [zube]: In Review, module, review, test-plan, v7.6.0

#15049 Enable all metricsets for AWS module
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: Team:Integrations, [zube]: In Review, needs_backport, review

#15093 Cherry-pick #15049 to 7.x: Enable all metricsets for AWS module
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: backport, review

#14724 [DOCS] Refactor output docs
  libbeat/docs/outputconfig.asciidoc
  libbeat/docs/outputs-list.asciidoc
  libbeat/docs/shared-beats-attributes.asciidoc
  libbeat/outputs/codec/docs/codec.asciidoc
  libbeat/outputs/codec/docs/placeholder.asciidoc
  libbeat/outputs/console/docs/console.asciidoc
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
  libbeat/outputs/fileout/docs/fileout.asciidoc
  libbeat/outputs/kafka/docs/kafka.asciidoc
  libbeat/outputs/logstash/docs/logstash.asciidoc
  libbeat/outputs/redis/docs/redis.asciidoc
  winlogbeat/docs/getting-started.asciidoc
  x-pack/functionbeat/docs/configuring-howto.asciidoc
Labels: Team:Beats, backport, docs, libbeat, technical debt

#13594 [DOCS] config example for AD domain credential for MSSQL module
  metricbeat/docs/modules/mssql.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/mssql/_meta/config.yml
  x-pack/metricbeat/module/mssql/_meta/docs.asciidoc
  x-pack/metricbeat/modules.d/mssql.yml.disabled
Labels: Metricbeat, Team:Integrations, [zube]: In Review, docs, enhancement, module, needs_backport

#15095 Cherry-pick #12973 to 7.x: [libbeat] Enable TLS 1.3
  CHANGELOG.next.asciidoc
  filebeat/tests/system/test_tcp_tls.py
  libbeat/common/transport/tlscommon/tls_test.go
  libbeat/common/transport/tlscommon/types.go
  libbeat/docs/shared-ssl-config.asciidoc
Labels: backport, libbeat, review

#15094 Cherry-pick #14010 to 7.x: [Filebeat] Select output index based on the source input
  CHANGELOG.next.asciidoc
  filebeat/beater/filebeat.go
  filebeat/channel/connector.go
  filebeat/channel/connector_test.go
  filebeat/channel/factory.go
  filebeat/docs/inputs/input-common-options.asciidoc
  filebeat/input/input.go
  filebeat/kafka.yml
  libbeat/common/fmtstr/formattimestamp.go
  libbeat/common/fmtstr/formattimestamp_test.go
  libbeat/idxmgmt/ilm/ilm.go
  libbeat/idxmgmt/std.go
Labels: Filebeat, backport, review

#15030 Migrate Filebeat integration tests to Python3
  filebeat/tests/system/test_autodiscover.py
  filebeat/tests/system/test_crawler.py
  filebeat/tests/system/test_harvester.py
  filebeat/tests/system/test_input.py
  filebeat/tests/system/test_keystore.py
  filebeat/tests/system/test_modules.py
  filebeat/tests/system/test_multiline.py
  filebeat/tests/system/test_registrar.py
  filebeat/tests/system/test_shutdown.py
  filebeat/tests/system/test_stdin.py
  filebeat/tests/system/test_syslog.py
  filebeat/tests/system/test_tcp.py
  filebeat/tests/system/test_tcp_tls.py
  filebeat/tests/system/test_udp.py
  libbeat/tests/system/beat/beat.py
Labels: review

#15108 [7.x][DOCS] Backport: Add temporary file needed by conf.yaml to refactor output docs (#14700)
  libbeat/outputs/codec/docs/placeholder.asciidoc
Labels: backport, docs, v7.6.0

#15109 [7.5][DOCS] Backport: Add temporary file needed by conf.yaml to refactor output docs
  libbeat/outputs/codec/docs/placeholder.asciidoc
Labels: backport, docs, v7.5.0

#14995 Cherry-pick #14925 to 7.x: [Metricbeat] Add usage metricset into aws module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/images/metricbeat-aws-usage-overview.png
  metricbeat/docs/modules/aws.asciidoc
  metricbeat/docs/modules/aws/usage.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-usage-overview.json
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/module.yml
  x-pack/metricbeat/module/aws/usage/_meta/data.json
  x-pack/metricbeat/module/aws/usage/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/usage/_meta/fields.yml
  x-pack/metricbeat/module/aws/usage/manifest.yml
  x-pack/metricbeat/module/aws/usage/usage_integration_test.go
  x-pack/metricbeat/module/aws/usage/usage_test.go
Labels: backport, review

#14971 Allow namespace: "*" for cloudwatch metricset
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, needs_backport, review, test-plan

#15092 Cherry-pick #14839 to 7.x: [Metricbeat] Add STAN (NATS streaming) module
  CHANGELOG.next.asciidoc
  dev-tools/mage/gotest.go
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/stan.asciidoc
  metricbeat/docs/modules/stan/channels.asciidoc
  metricbeat/docs/modules/stan/stats.asciidoc
  metricbeat/docs/modules/stan/subscriptions.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/stan/_meta/Dockerfile
  x-pack/metricbeat/module/stan/_meta/config.reference.yml
  x-pack/metricbeat/module/stan/_meta/config.yml
  x-pack/metricbeat/module/stan/_meta/docs.asciidoc
  x-pack/metricbeat/module/stan/_meta/fields.yml
  x-pack/metricbeat/module/stan/_meta/run.sh
  x-pack/metricbeat/module/stan/channels/_meta/data.json
  x-pack/metricbeat/module/stan/channels/_meta/docs.asciidoc
  x-pack/metricbeat/module/stan/channels/_meta/fields.yml
  x-pack/metricbeat/module/stan/channels/_meta/test/channels.json
  x-pack/metricbeat/module/stan/channels/channels.go
  x-pack/metricbeat/module/stan/channels/channels_integration_test.go
  x-pack/metricbeat/module/stan/channels/channels_test.go
  x-pack/metricbeat/module/stan/channels/data.go
  x-pack/metricbeat/module/stan/doc.go
  x-pack/metricbeat/module/stan/docker-compose.yml
  x-pack/metricbeat/module/stan/fields.go
  x-pack/metricbeat/module/stan/module.yml
  x-pack/metricbeat/module/stan/stats/_meta/data.json
  x-pack/metricbeat/module/stan/stats/_meta/docs.asciidoc
  x-pack/metricbeat/module/stan/stats/_meta/fields.yml
  x-pack/metricbeat/module/stan/stats/_meta/test/serversz.json
  x-pack/metricbeat/module/stan/stats/data.go
  x-pack/metricbeat/module/stan/stats/docs.asciidoc
  x-pack/metricbeat/module/stan/stats/stats.go
  x-pack/metricbeat/module/stan/stats/stats_integration_test.go
  x-pack/metricbeat/module/stan/stats/stats_test.go
  x-pack/metricbeat/module/stan/subscriptions/_meta/data.json
  x-pack/metricbeat/module/stan/subscriptions/_meta/docs.asciidoc
  x-pack/metricbeat/module/stan/subscriptions/_meta/fields.yml
  x-pack/metricbeat/module/stan/subscriptions/_meta/test/subscriptions.json
  x-pack/metricbeat/module/stan/subscriptions/data.go
  x-pack/metricbeat/module/stan/subscriptions/subscriptions.go
  x-pack/metricbeat/module/stan/subscriptions/subscriptions_integration_test.go
  x-pack/metricbeat/module/stan/subscriptions/subscriptions_test.go
  x-pack/metricbeat/module/stan/test_stan.py
  x-pack/metricbeat/modules.d/stan.yml.disabled
Labels: Team:Integrations, [zube]: In Review, backport, review

#15055 Update Kubernetes Autodiscover docs with the new resources
  libbeat/docs/shared-autodiscover.asciidoc
Labels: Team:Integrations, [zube]: In Review, autodiscovery, docs, review, v7.6.0

#15116 Cherry-pick #15055 to 7.x: Update Kubernetes Autodiscover docs with the new resources
  libbeat/docs/shared-autodiscover.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport, review

#15117 [filebeat] Fix: missing beta label for ActiveMQ
  filebeat/docs/modules/activemq.asciidoc
  x-pack/filebeat/module/activemq/_meta/docs.asciidoc
  x-pack/filebeat/module/activemq/_meta/fields.yml
  x-pack/filebeat/module/activemq/fields.go
Labels: Filebeat, Team:Integrations, [zube]: In Review, review

#15099 [Elastic Logging Plugin] Use docker helper functions to format output
  x-pack/dockerlogbeat/pipelinemanager/clientLogReader.go
Labels: Team:Integrations, [zube]: In Review

#14990 make additional credentials available for tests
  libbeat/scripts/Makefile
Labels: Team:Beats, Team:apm

#15120 Cherry-pick #15117 to 7.x: [filebeat] Fix: missing beta label for ActiveMQ
  filebeat/docs/modules/activemq.asciidoc
  x-pack/filebeat/module/activemq/_meta/docs.asciidoc
  x-pack/filebeat/module/activemq/_meta/fields.yml
  x-pack/filebeat/module/activemq/fields.go
Labels: backport, review

#15098 [libbeat] Belatedly add changelog for #12973
  CHANGELOG.next.asciidoc
Labels: libbeat

#15089 Store access token missing
  agent/kibana/config.go
  x-pack/agent/_meta/agent.fleet.yml
  x-pack/agent/dev-tools/cmd/buildfleetcfg/buildfleetcfg.go
  x-pack/agent/magefile.go
  x-pack/agent/pkg/agent/application/application.go
  x-pack/agent/pkg/agent/application/config.go
  x-pack/agent/pkg/agent/application/config_storage.go
  x-pack/agent/pkg/agent/application/configuration_embed.go
  x-pack/agent/pkg/agent/application/enroll_cmd.go
  x-pack/agent/pkg/agent/application/enroll_cmd_test.go
  x-pack/agent/pkg/agent/application/local_mode.go
  x-pack/agent/pkg/agent/application/managed_mode.go
  x-pack/agent/pkg/agent/cmd/enroll.go
  x-pack/agent/pkg/agent/storage/storage.go
  x-pack/agent/pkg/agent/storage/storage_test.go
  x-pack/agent/pkg/config/config.go
  x-pack/agent/pkg/core/plugin/app/configure.go
  x-pack/agent/pkg/crypto/io.go
  x-pack/agent/pkg/crypto/io_test.go
  x-pack/agent/pkg/fleetapi/client.go
  x-pack/agent/pkg/fleetapi/helper_test.go
  x-pack/agent/pkg/reporter/fleet/config.go
  x-pack/agent/pkg/reporter/log/config.go
  x-pack/agent/pkg/reporter/log/format.go
Labels: Project:fleet, [zube]: In Review, agent, review

#15100 [metricbeat] [auditbeat] Add formatted index option to metricbeat / auditbeat modules
  CHANGELOG.next.asciidoc
  metricbeat/beater/metricbeat.go
  metricbeat/docs/metricbeat-options.asciidoc
  metricbeat/mb/module/connector.go
  metricbeat/mb/module/connector_test.go
  metricbeat/mb/module/example_test.go
  metricbeat/mb/module/factory.go
Labels: Auditbeat, Metricbeat, needs_backport

#15127 cherry-pick of #15017: create a LoadWithSettings constructor that exposes WaitTime settings
  libbeat/publisher/pipeline/module.go
Labels: backport

#14778 [Heartbeat] Add monitor.timespan field
  CHANGELOG.next.asciidoc
  heartbeat/_meta/fields.common.yml
  heartbeat/docs/fields.asciidoc
  heartbeat/hbtest/hbtestutil.go
  heartbeat/hbtestllext/isdefs.go
  heartbeat/hbtestllext/validators.go
  heartbeat/include/fields.go
  heartbeat/monitors/active/http/http_test.go
  heartbeat/monitors/active/tcp/tcp_test.go
  heartbeat/monitors/mocks_test.go
  heartbeat/monitors/monitor.go
  heartbeat/monitors/pluginconf.go
  heartbeat/monitors/wrappers/monitors.go
  heartbeat/monitors/wrappers/monitors_test.go
  heartbeat/scheduler/schedule/schedule.go
  libbeat/mapping/field.go
  libbeat/tests/system/beat/beat.py
Labels: :uptime, Heartbeat, enhancement, in progress
