Repository elastic/beats, pull requests merged in 2020-04, with the labels that each got.

#17368 [Agent] fixed mage package for agent
  dev-tools/mage/dmgbuilder.go
Labels: Team:Ingest Management, bug, needs_backport

#17366 Cherry-pick #17196 to 7.x: Recommend `remote_write` instead of federate API
  metricbeat/module/prometheus/collector/_meta/docs.asciidoc
Labels: backport, review

#17367 Cherry-pick #17196 to 7.7: Recommend `remote_write` instead of federate API
  metricbeat/module/prometheus/collector/_meta/docs.asciidoc
Labels: backport, review

#17241 [Agent] Enable post install hooks
  x-pack/agent/CHANGELOG.asciidoc
  x-pack/agent/pkg/agent/program/spec.go
  x-pack/agent/pkg/agent/program/spec_test.go
  x-pack/agent/pkg/agent/program/supported.go
  x-pack/agent/pkg/agent/transpiler/rules.go
  x-pack/agent/pkg/agent/transpiler/steps.go
  x-pack/agent/pkg/agent/transpiler/steps_test.go
  x-pack/agent/pkg/artifact/install/hooks/hooks_installer.go
  x-pack/agent/pkg/artifact/install/installer.go
  x-pack/agent/spec/metricbeat.yml
Labels: Project:fleet, Team:Ingest Management, agent, enhancement

#17365 Small correction to googlecloud/firewall docs
  filebeat/docs/modules/googlecloud.asciidoc
  x-pack/filebeat/module/googlecloud/_meta/docs.asciidoc
Labels: Team:SIEM, docs

#17311 Cherry-pick #17209 to 7.x: Add source field in k8s events
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/event/_meta/fields.yml
  metricbeat/module/kubernetes/event/event.go
  metricbeat/module/kubernetes/event/event_test.go
  metricbeat/module/kubernetes/fields.go
Labels: Team:Platforms, backport, review

#17156 [BUG] Fix "regular expression has redundant nested repeat operator" in MySQL slowlog module.
  CHANGELOG.next.asciidoc
  filebeat/module/mysql/slowlog/ingest/pipeline.json
Labels: Team:Services, [zube]: In Review, review

#17345 [Metricbeat]Combine metrics with no dimension into one event
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Labels: Team:Platforms, bug, needs_backport

#17388 Fix command which installs mage
  dev-tools/make/mage.mk
Labels: Team:Services, [zube]: In Review, needs_backport

#17374 Fix mbean parsing for mbeans with multiple quoted properties
  CHANGELOG.next.asciidoc
  metricbeat/module/jolokia/jmx/config.go
  metricbeat/module/jolokia/jmx/config_test.go
Labels: Team:Integrations, [zube]: In Review, bug, needs_backport, review, v7.6.3, v7.7.0, v7.8.0

#17147 Add support for MODULE in mage goIntegTest for metricbeat
  CHANGELOG-developer.next.asciidoc
  dev-tools/mage/gotest.go
  dev-tools/mage/integtest.go
  metricbeat/magefile.go
  x-pack/metricbeat/magefile.go
Labels: :Testing, Metricbeat, Team:Integrations, [zube]: In Review, module, review

#17354 Cherry-pick #17139 to 7.x: Add reference documentation about indexers and matchers
  filebeat/docs/index.asciidoc
  filebeat/docs/kubernetes-default-indexers-matchers.asciidoc
  libbeat/docs/processors-list.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc
  metricbeat/docs/index.asciidoc
  metricbeat/docs/kubernetes-default-indexers-matchers.asciidoc
Labels: [zube]: In Review, backport, review

#17355 Cherry-pick #17139 to 7.7: Add reference documentation about indexers and matchers
  filebeat/docs/index.asciidoc
  filebeat/docs/kubernetes-default-indexers-matchers.asciidoc
  libbeat/docs/processors-list.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc
  metricbeat/docs/index.asciidoc
  metricbeat/docs/kubernetes-default-indexers-matchers.asciidoc
Labels: [zube]: In Review, backport, review

#17356 Cherry-pick #17139 to 7.6: Add reference documentation about indexers and matchers
  filebeat/docs/index.asciidoc
  filebeat/docs/kubernetes-default-indexers-matchers.asciidoc
  libbeat/docs/processors-list.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc
  metricbeat/docs/index.asciidoc
  metricbeat/docs/kubernetes-default-indexers-matchers.asciidoc
Labels: [zube]: In Review, backport, review

#17371 [Filebeat] Improve ECS categorization field mappings for mongodb module
  CHANGELOG.next.asciidoc
  filebeat/module/mongodb/log/ingest/pipeline.json
  filebeat/module/mongodb/log/ingest/pipeline.yml
  filebeat/module/mongodb/log/manifest.yml
  filebeat/module/mongodb/log/test/mongodb-debian-3.2.11.log
  filebeat/module/mongodb/log/test/mongodb-debian-3.2.11.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, needs_backport

#17376 [Filebeat] Improve ECS categorization field mappings for mssql module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/mssql/log/ingest/pipeline.json
  x-pack/filebeat/module/mssql/log/ingest/pipeline.yml
  x-pack/filebeat/module/mssql/log/manifest.yml
  x-pack/filebeat/module/mssql/log/test/test.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, needs_backport

#17394 Cherry-pick #17156 to 7.x: [BUG] Fix "regular expression has redundant nested repeat operator" in MySQL slowlog module.
  CHANGELOG.next.asciidoc
  filebeat/module/mysql/slowlog/ingest/pipeline.json
Labels: [zube]: In Review, backport, review

#17395 Cherry-pick #17156 to 7.7: [BUG] Fix "regular expression has redundant nested repeat operator" in MySQL slowlog module.
  CHANGELOG.next.asciidoc
  filebeat/module/mysql/slowlog/ingest/pipeline.json
Labels: [zube]: In Review, backport, review

#17406 Add pattern to handle logs from newer ES versions
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/audit/ingest/pipeline-json.yml
  filebeat/module/elasticsearch/audit/test/test-audit-761.log
  filebeat/module/elasticsearch/audit/test/test-audit-761.log-expected.json
Labels: Filebeat, Stack monitoring, Team:Services, [zube]: In Review, bug, module, v7.6.3, v7.7.0, v7.8.0, v8.0.0

#17339 [7.6] Allow a wider range of characters for logstash.log.pipeline_id (#17243)
  CHANGELOG.next.asciidoc
  filebeat/module/logstash/log/ingest/pipeline-plain.json
  filebeat/module/logstash/log/test/logstash-plain-7.4.log
  filebeat/module/logstash/log/test/logstash-plain-7.4.log-expected.json
Labels: Team:Integrations, [zube]: In Review, backport

#17403 Cherry-pick #17345 to 7.7: [Metricbeat]Combine metrics with no dimension into one event
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Labels: Team:Platforms, backport, review

#17398 Cherry-pick #17345 to 7.x: [Metricbeat]Combine metrics with no dimension into one event
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Labels: Team:Platforms, [zube]: In Review, backport, review

#17383 Remove dataType field of query metricset
  metricbeat/module/prometheus/query/_meta/data.json
  metricbeat/module/prometheus/query/data.go
Labels: Team:Platforms, bug, needs_backport, v7.7.0, v7.8.0

#17386 Cherry-pick #17365 to 7.7: Small correction to googlecloud/firewall docs
  filebeat/docs/modules/googlecloud.asciidoc
  x-pack/filebeat/module/googlecloud/_meta/docs.asciidoc
Labels: [zube]: In Review, backport, review

#17399 [Agent] Fix merge of config
  x-pack/agent/CHANGELOG.asciidoc
  x-pack/agent/pkg/agent/program/supported.go
  x-pack/agent/pkg/agent/program/testdata/single_config-filebeat.yml
  x-pack/agent/pkg/agent/program/testdata/single_config-metricbeat.yml
  x-pack/agent/pkg/agent/program/testdata/single_config.yml
  x-pack/agent/pkg/agent/transpiler/rules.go
  x-pack/agent/pkg/agent/transpiler/rules_test.go
  x-pack/agent/spec/filebeat.yml
  x-pack/agent/spec/metricbeat.yml
Labels: Project:fleet, agent, bug

#17385 Cherry-pick #17365 to 7.x: Small correction to googlecloud/firewall docs
  filebeat/docs/modules/googlecloud.asciidoc
  x-pack/filebeat/module/googlecloud/_meta/docs.asciidoc
Labels: [zube]: In Review, backport, review

#17413 Cherry-pick #17393 to 7.7: Add metricbeat as dependency for auditbeat to Pipeline check
  Jenkinsfile
Labels: backport, review

#16365 Refactor keystore interface into 3 different interfaces
  libbeat/cmd/keystore.go
  libbeat/keystore/file_keystore.go
  libbeat/keystore/file_keystore_test.go
  libbeat/keystore/keystore.go
  x-pack/libbeat/management/enroll.go
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, autodiscovery, enhancement, libbeat, needs_backport, v7.8.0

#17334 Add test for documented fields check for metricsets without a http input
  CHANGELOG.next.asciidoc
  metricbeat/mb/testing/testdata.go
  metricbeat/mb/testing/testdata_test.go
  x-pack/metricbeat/module/azure/compute_vm/compute_vm_integration_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/compute_vm_scaleset_integration_test.go
  x-pack/metricbeat/module/azure/container_instance/container_instance_integration_test.go
  x-pack/metricbeat/module/azure/container_registry/container_registry_integration_test.go
  x-pack/metricbeat/module/azure/container_service/container_service_integration_test.go
  x-pack/metricbeat/module/azure/database_account/database_account_integration_test.go
  x-pack/metricbeat/module/azure/monitor/monitor_integration_test.go
  x-pack/metricbeat/module/azure/storage/storage_integration_test.go
  x-pack/metricbeat/module/azure/test/integration.go
Labels: Team:Integrations, [zube]: In Review, needs_backport

#17427 Cherry-pick #17383 to 7.x: Remove dataType field of query metricset
  metricbeat/module/prometheus/query/_meta/data.json
  metricbeat/module/prometheus/query/data.go
Labels: Team:Platforms, backport, review

#17426 Cherry-pick #17383 to 7.7: Remove dataType field of query metricset
  metricbeat/module/prometheus/query/_meta/data.json
  metricbeat/module/prometheus/query/data.go
Labels: Team:Platforms, backport, review

#17416 Cherry-pick #17371 to 7.x: [Filebeat] Improve ECS categorization field mappings for mongodb module
  CHANGELOG.next.asciidoc
  filebeat/module/mongodb/log/ingest/pipeline.json
  filebeat/module/mongodb/log/ingest/pipeline.yml
  filebeat/module/mongodb/log/manifest.yml
  filebeat/module/mongodb/log/test/mongodb-debian-3.2.11.log
  filebeat/module/mongodb/log/test/mongodb-debian-3.2.11.log-expected.json
Labels: Team:SIEM, backport, review

#17417 Cherry-pick #17376 to 7.x: [Filebeat] Improve ECS categorization field mappings for mssql module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/mssql/log/ingest/pipeline.json
  x-pack/filebeat/module/mssql/log/ingest/pipeline.yml
  x-pack/filebeat/module/mssql/log/manifest.yml
  x-pack/filebeat/module/mssql/log/test/test.log-expected.json
Labels: Team:SIEM, backport, review

#17435 Cherry-pick #16365 to 7.x: Refactor keystore interface into 3 different interfaces
  libbeat/cmd/keystore.go
  libbeat/keystore/file_keystore.go
  libbeat/keystore/file_keystore_test.go
  libbeat/keystore/keystore.go
  x-pack/libbeat/management/enroll.go
Labels: Team:Integrations, backport, review

#17428 Fix redundant operator in activemq ingest pipeline
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/activemq/log/ingest/pipeline.yml
Labels: Filebeat, bug, needs_backport, review

#17400 [Metricbeat] Further revise check for bad data in docker/memory
  CHANGELOG.next.asciidoc
  metricbeat/module/docker/memory/helper.go
  metricbeat/module/docker/memory/memory.go
  metricbeat/module/docker/memory/memory_test.go
Labels: Metricbeat, Team:Integrations, bug, needs_backport

#17434 Typo in Heartbeat docs
  heartbeat/docs/getting-started.asciidoc
Labels: docs, review

#17448 Postpone selection of the logger output
  libbeat/logp/config.go
  libbeat/logp/core.go
Labels: Team:Services, bug, libbeat, v7.7.0

#17446 Cherry-pick #17400 to 7.x: [Metricbeat] Further revise check for bad data in docker/memory
  CHANGELOG.next.asciidoc
  metricbeat/module/docker/memory/helper.go
  metricbeat/module/docker/memory/memory.go
  metricbeat/module/docker/memory/memory_test.go
Labels: [zube]: Inbox, backport, bug, review

#17452 [Heartbeat][Docs] Fix typo (#17434)
  heartbeat/docs/getting-started.asciidoc
Labels: :uptime, Heartbeat, docs

#17453 [Heartbeat][Docs] Fix typo (#17434)
  heartbeat/docs/getting-started.asciidoc
Labels: :uptime, Heartbeat, docs

#17373 Cherry-pick #17161 to 7.7: Add dashboard for pubsub metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/images/metricbeat-googlecloud-pubsub-overview.png
  x-pack/metricbeat/module/googlecloud/_meta/kibana/7/dashboard/Metricbeat-googlecloud-pubsub-overview.json
Labels: Team:Platforms, [zube]: In Review, backport, review

#17372 Cherry-pick #17161 to 7.x: Add dashboard for pubsub metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/images/metricbeat-googlecloud-pubsub-overview.png
  x-pack/metricbeat/module/googlecloud/_meta/kibana/7/dashboard/Metricbeat-googlecloud-pubsub-overview.json
Labels: Team:Platforms, [zube]: In Review, backport, review

#17418 [Metricbeat AWS] check if cpuOptions is nil in DescribeInstances output
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/ec2/ec2.go
Labels: Metricbeat, Team:Platforms, bug, needs_backport

#17360 Add regex based cid extractor to add_process_metadata
  CHANGELOG.next.asciidoc
  libbeat/processors/add_process_metadata/add_process_metadata.go
  libbeat/processors/add_process_metadata/add_process_metadata_test.go
  libbeat/processors/add_process_metadata/config.go
  libbeat/processors/add_process_metadata/docs/add_process_metadata.asciidoc
  libbeat/processors/add_process_metadata/gosigar_cid_provider.go
Labels: Team:Platforms, enhancement, needs_backport, review

#17436 Cherry-pick #17388 to 7.x: Fix command which installs mage
  dev-tools/make/mage.mk
Labels: Team:Services, [zube]: In Review, backport

#17466 chore: hide mage install output
  dev-tools/make/mage.mk
Labels: automation, bug, ci

#17437 Cherry-pick #17388 to 7.7: Fix command which installs mage
  dev-tools/make/mage.mk
Labels: Team:Services, [zube]: In Review, backport

#17463 Cherry-pick #17441 to 7.x: Filebeat: Fix fields indentation
  x-pack/filebeat/module/coredns/_meta/fields.yml
  x-pack/filebeat/module/coredns/fields.go
  x-pack/filebeat/module/envoyproxy/_meta/fields.yml
  x-pack/filebeat/module/envoyproxy/fields.go
Labels: backport, review

#17459 Cherry-pick #17418 to 7.7: [Metricbeat AWS] check if cpuOptions is nil in DescribeInstances output
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/ec2/ec2.go
Labels: Team:Platforms, backport, review

#17458 Cherry-pick #17418 to 7.x: [Metricbeat AWS] check if cpuOptions is nil in DescribeInstances output
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/ec2/ec2.go
Labels: Team:Platforms, backport, review

#17445 Add Elastic Agent in the Jenkinsfile
  Jenkinsfile
  x-pack/elastic-agent/pkg/agent/transpiler/steps_test.go
Labels: Team:Ingest Management, [zube]: In Review, bug, needs_backport, review

#17470 Enable GSSAPI authentication when Kerberos is configured
  filebeat/input/kafka/config.go
  libbeat/outputs/kafka/config.go
Labels: Team:Services, [zube]: In Review, needs_backport

#17454 Cherry-pick #17448 to 7.x: Postpone selection of the logger output
  libbeat/logp/config.go
  libbeat/logp/core.go
Labels: Team:Services, backport, ci

#17455 Cherry-pick #17448 to 7.7: Postpone selection of the logger output
  libbeat/logp/config.go
  libbeat/logp/core.go
Labels: Team:Services, bug, libbeat, v7.7.0

#17423 [7.6] Add pattern to handle logs from newer ES versions (#17406)
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/audit/ingest/pipeline-json.json
  filebeat/module/elasticsearch/audit/test/test-audit-761.log
  filebeat/module/elasticsearch/audit/test/test-audit-761.log-expected.json
Labels: Team:Integrations, [zube]: In Review, backport

#17422 [7.7] Add pattern to handle logs from newer ES versions (#17406)
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/audit/ingest/pipeline-json.yml
  filebeat/module/elasticsearch/audit/test/test-audit-761.log
  filebeat/module/elasticsearch/audit/test/test-audit-761.log-expected.json
Labels: Team:Integrations, [zube]: In Review, backport

#17421 [7.x] Add pattern to handle logs from newer ES versions (#17406)
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/audit/ingest/pipeline-json.yml
  filebeat/module/elasticsearch/audit/test/test-audit-761.log
  filebeat/module/elasticsearch/audit/test/test-audit-761.log-expected.json
Labels: Team:Integrations, [zube]: In Review, backport

#17420 Always extract monitoring.cluster_uuid setting from Beat config
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
  libbeat/tests/system/test_monitoring.py
Labels: Team:Services, [zube]: In Review, bug, needs_backport, v7.6.3, v7.7.0, v7.8.0, v8.0.0

#17298 Cherry-pick #17275 to 7.x: Add documentation for deploying filebeat and metricbeat in Cloud Foundry.
  CHANGELOG.next.asciidoc
  deploy/cloudfoundry/README.md
  deploy/cloudfoundry/filebeat/filebeat.yml
  deploy/cloudfoundry/filebeat/manifest.yml
  deploy/cloudfoundry/metricbeat/manifest.yml
  deploy/cloudfoundry/metricbeat/metricbeat.yml
  filebeat/docs/getting-started.asciidoc
  filebeat/docs/running-on-cloudfoundry.asciidoc
  filebeat/docs/setting-up-running.asciidoc
  metricbeat/docs/gettingstarted.asciidoc
  metricbeat/docs/running-on-cloudfoundry.asciidoc
  metricbeat/docs/setting-up-running.asciidoc
Labels: Team:Platforms, [zube]: In Review, backport, review

#17471 Cherry-pick #17470 to 7.x: Enable GSSAPI authentication when Kerberos is configured
  filebeat/input/kafka/config.go
  libbeat/outputs/kafka/config.go
Labels: Team:Services, [zube]: In Review, backport

#17472 Cherry-pick #17470 to 7.7: Enable GSSAPI authentication when Kerberos is configured
  filebeat/input/kafka/config.go
  libbeat/outputs/kafka/config.go
Labels: Team:Services, [zube]: In Review, backport

#17284 Cherry-pick #17253 to 7.7: Ignore trailing spaces in CEF messages
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cef/log/test/cef.log
  x-pack/filebeat/module/cef/log/test/cef.log-expected.json
  x-pack/filebeat/processors/decode_cef/cef/cef.go
  x-pack/filebeat/processors/decode_cef/cef/cef.rl
  x-pack/filebeat/processors/decode_cef/cef/cef_test.go
  x-pack/filebeat/processors/decode_cef/cef/parser.go
Labels: Team:SIEM, [zube]: In Review, backport, review

#17283 Cherry-pick #17253 to 7.x: Ignore trailing spaces in CEF messages
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cef/log/test/cef.log
  x-pack/filebeat/module/cef/log/test/cef.log-expected.json
  x-pack/filebeat/processors/decode_cef/cef/cef.go
  x-pack/filebeat/processors/decode_cef/cef/cef.rl
  x-pack/filebeat/processors/decode_cef/cef/cef_test.go
  x-pack/filebeat/processors/decode_cef/cef/parser.go
Labels: Team:SIEM, [zube]: In Review, backport, review

#17424 [Metricbeat] Fix cloudwatch metricset missing tags collection
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/sqs/sqs.go
Labels: Metricbeat, Team:Platforms, bug, needs_backport

#17473 Jenkinsfile: Fix auditbeat check and add comments
  Jenkinsfile
Labels: Team:Services, bug, ci, enhancement, review

#17456 [Filebeat] Add access_key_id, secret_access_key and session_token into aws module config
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/aws/_meta/config.yml
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/cloudtrail/config/s3.yml
  x-pack/filebeat/module/aws/cloudtrail/manifest.yml
  x-pack/filebeat/module/aws/cloudwatch/config/s3.yml
  x-pack/filebeat/module/aws/cloudwatch/manifest.yml
  x-pack/filebeat/module/aws/ec2/config/s3.yml
  x-pack/filebeat/module/aws/ec2/manifest.yml
  x-pack/filebeat/module/aws/elb/config/s3.yml
  x-pack/filebeat/module/aws/elb/manifest.yml
  x-pack/filebeat/module/aws/s3access/config/s3.yml
  x-pack/filebeat/module/aws/s3access/manifest.yml
  x-pack/filebeat/module/aws/vpcflow/config/input.yml
  x-pack/filebeat/module/aws/vpcflow/manifest.yml
  x-pack/filebeat/modules.d/aws.yml.disabled
Labels: Filebeat, Team:Platforms, [zube]: In Review, needs_backport, review

#17477 Cherry-pick #17424 to 7.x: [Metricbeat] Fix cloudwatch metricset missing tags collection
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/sqs/sqs.go
Labels: Team:Platforms, backport, review

#17478 Cherry-pick #17424 to 7.7: [Metricbeat] Fix cloudwatch metricset missing tags collection
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/sqs/sqs.go
Labels: Team:Platforms, backport, review

#17476 [7.6] Always extract monitoring.cluster_uuid setting from Beat config (#17420)
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
  libbeat/tests/system/test_monitoring.py
Labels: Team:Services, [zube]: In Review, backport

#17475 [7.7] Always extract monitoring.cluster_uuid setting from Beat config (#17420)
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
  libbeat/tests/system/test_monitoring.py
Labels: Team:Services, [zube]: In Review, backport

#17474 [7.x] Always extract monitoring.cluster_uuid setting from Beat config (#17420)
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
  libbeat/tests/system/test_monitoring.py
Labels: Team:Services, [zube]: In Review, backport

#17425 Remove migrationVersion map 7.7.0 reference from Kibana dashboard file to avoid backward compat…
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/okta/_meta/kibana/7/dashboard/749203a0-67b1-11ea-a76f-bf44814e437d.json
Labels: Filebeat, Team:SIEM, module, needs_backport, review

#16982 Cherry-pick #16889 to 7.6: [Filebeat] Cisco FTD issues parsing Security Event messages
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/ftd/test/firepower-management.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/intrusion.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/security-malware-site.log
  x-pack/filebeat/module/cisco/ftd/test/security-malware-site.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: Team:SIEM, [zube]: In Review, backport, review

#17483 Cherry-pick #17456 to 7.x: [Filebeat] Add access_key_id, secret_access_key and session_token into aws module config
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/aws/_meta/config.yml
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/cloudtrail/config/s3.yml
  x-pack/filebeat/module/aws/cloudtrail/manifest.yml
  x-pack/filebeat/module/aws/cloudwatch/config/s3.yml
  x-pack/filebeat/module/aws/cloudwatch/manifest.yml
  x-pack/filebeat/module/aws/ec2/config/s3.yml
  x-pack/filebeat/module/aws/ec2/manifest.yml
  x-pack/filebeat/module/aws/elb/config/s3.yml
  x-pack/filebeat/module/aws/elb/manifest.yml
  x-pack/filebeat/module/aws/s3access/config/s3.yml
  x-pack/filebeat/module/aws/s3access/manifest.yml
  x-pack/filebeat/module/aws/vpcflow/config/input.yml
  x-pack/filebeat/module/aws/vpcflow/manifest.yml
  x-pack/filebeat/modules.d/aws.yml.disabled
Labels: Team:Platforms, backport, review

#17443 Log to stderr in auditbeat reference doc for kubernetes
  CHANGELOG.next.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Labels: Auditbeat, Team:Platforms, [zube]: In Review, needs_backport, review, v7.7.0

#17488 Log updates on autodiscovered pods at the debug level
  libbeat/autodiscover/providers/kubernetes/pod.go
Labels: Team:Platforms, [zube]: In Review, bug, needs_backport, review, v7.7.0

#17501 Cherry-pick #17443 to 7.x: Log to stderr in auditbeat reference doc for kubernetes
  CHANGELOG.next.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Labels: backport, review

#17502 Cherry-pick #17443 to 7.7: Log to stderr in auditbeat reference doc for kubernetes
  CHANGELOG.next.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Labels: backport, review

#17503 Cherry-pick #17488 to 7.x: Log updates on autodiscovered pods at the debug level
  libbeat/autodiscover/providers/kubernetes/pod.go
Labels: backport, review

#17504 Cherry-pick #17488 to 7.7: Log updates on autodiscovered pods at the debug level
  libbeat/autodiscover/providers/kubernetes/pod.go
Labels: backport, review

#17429 Add data directories to kubernetes manifests
  CHANGELOG.next.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset.yaml
Labels: Auditbeat, Metricbeat, Team:Platforms, Team:SIEM, [zube]: In Review, containers, needs_backport, review, v7.6.3, v7.7.0

#17439 Cherry-pick #17334 to 7.x: Add test for documented fields check for metricsets without a http input
  CHANGELOG.next.asciidoc
  metricbeat/mb/testing/testdata.go
  metricbeat/mb/testing/testdata_test.go
  x-pack/metricbeat/module/azure/compute_vm/compute_vm_integration_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/compute_vm_scaleset_integration_test.go
  x-pack/metricbeat/module/azure/container_instance/container_instance_integration_test.go
  x-pack/metricbeat/module/azure/container_registry/container_registry_integration_test.go
  x-pack/metricbeat/module/azure/container_service/container_service_integration_test.go
  x-pack/metricbeat/module/azure/database_account/database_account_integration_test.go
  x-pack/metricbeat/module/azure/monitor/monitor_integration_test.go
  x-pack/metricbeat/module/azure/storage/storage_integration_test.go
  x-pack/metricbeat/module/azure/test/integration.go
Labels: Team:Integrations, [zube]: In Review, backport

#17438 Cherry-pick #17334 to 7.7: Add test for documented fields check for metricsets without a http input
  CHANGELOG.next.asciidoc
  metricbeat/mb/testing/testdata.go
  metricbeat/mb/testing/testdata_test.go
  x-pack/metricbeat/module/azure/compute_vm/compute_vm_integration_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/compute_vm_scaleset_integration_test.go
  x-pack/metricbeat/module/azure/container_instance/container_instance_integration_test.go
  x-pack/metricbeat/module/azure/container_registry/container_registry_integration_test.go
  x-pack/metricbeat/module/azure/container_service/container_service_integration_test.go
  x-pack/metricbeat/module/azure/database_account/database_account_integration_test.go
  x-pack/metricbeat/module/azure/monitor/monitor_integration_test.go
  x-pack/metricbeat/module/azure/storage/storage_integration_test.go
  x-pack/metricbeat/module/azure/test/integration.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, backport

#17440 Cherry-pick #17428 to 7.x: Fix redundant operator in activemq ingest pipeline
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/activemq/log/ingest/pipeline.yml
Labels: Team:SIEM, [zube]: In Review, backport, review

#17442 Cherry-pick #17428 to 7.7: Fix redundant operator in activemq ingest pipeline
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/activemq/log/ingest/pipeline.yml
Labels: Team:SIEM, [zube]: In Review, backport, review

#12774 feat: enable make help for the top level makefile
  Makefile
Labels: [zube]: In Review, automation, needs_backport

#17500 [Auditbeat] Memory leak and syscall fix
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/socket/_meta/docs.asciidoc
  x-pack/auditbeat/module/system/socket/arch_386.go
  x-pack/auditbeat/module/system/socket/config.go
  x-pack/auditbeat/module/system/socket/socket_linux.go
  x-pack/auditbeat/module/system/socket/state.go
  x-pack/auditbeat/module/system/socket/state_test.go
Labels: Auditbeat, Team:SIEM, bug, needs_backport, review

#17379 Add dashboards for Google Cloud Audit and AWS CloudTrail
  CHANGELOG.next.asciidoc
  filebeat/docs/images/filebeat-aws-cloudtrail.png
  filebeat/docs/images/filebeat-googlecloud-audit.png
  filebeat/docs/modules/aws.asciidoc
  filebeat/docs/modules/googlecloud.asciidoc
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/_meta/kibana/7/dashboard/filebeat-aws-cloudtrail.json
  x-pack/filebeat/module/googlecloud/_meta/docs.asciidoc
  x-pack/filebeat/module/googlecloud/_meta/kibana/7/dashboard/filebeat-googlecloud-audit.json
Labels: :Dashboards, Filebeat, Team:SIEM, enhancement, needs_backport, review

#17489 Cherry-pick #17415 to 7.7: [metricbeat] fix system/service filtering issues
  CHANGELOG.next.asciidoc
  metricbeat/module/system/service/service.go
  metricbeat/module/system/service/service_test.go
Labels: [zube]: Inbox, backport, bug, review

#17513 Cherry-pick #17500 to 7.x: [Auditbeat] Memory leak and syscall fix
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/socket/_meta/docs.asciidoc
  x-pack/auditbeat/module/system/socket/arch_386.go
  x-pack/auditbeat/module/system/socket/config.go
  x-pack/auditbeat/module/system/socket/socket_linux.go
  x-pack/auditbeat/module/system/socket/state.go
  x-pack/auditbeat/module/system/socket/state_test.go
Labels: Auditbeat, Team:SIEM, backport, review

#17487 Cherry-pick #17415 to 7.x: [metricbeat] fix system/service filtering issues
  CHANGELOG.next.asciidoc
  metricbeat/module/system/service/service.go
  metricbeat/module/system/service/service_test.go
Labels: [zube]: Inbox, backport, bug, review

#17491 [Filebeat] Improve ECS categorization field mappings for mysql module
  CHANGELOG.next.asciidoc
  filebeat/module/mysql/error/ingest/pipeline.json
  filebeat/module/mysql/error/ingest/pipeline.yml
  filebeat/module/mysql/error/manifest.yml
  filebeat/module/mysql/error/test/error.log-expected.json
  filebeat/module/mysql/error/test/mariadb-10.4.8.log-expected.json
  filebeat/module/mysql/error/test/mysql-darwin-brew-5.7.10.log-expected.json
  filebeat/module/mysql/error/test/mysql-ubuntu-5.5.53.log-expected.json
  filebeat/module/mysql/error/test/mysql-ubuntu-8.0.15.log-expected.json
  filebeat/module/mysql/slowlog/ingest/pipeline.json
  filebeat/module/mysql/slowlog/test/mariadb-10.1.21.log-expected.json
  filebeat/module/mysql/slowlog/test/mariadb-10.2.12.log-expected.json
  filebeat/module/mysql/slowlog/test/mariadb-10.3.13.log-expected.json
  filebeat/module/mysql/slowlog/test/mariadb-explain.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-5.7.22.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-darwin-brew-5.7.10.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-debian-5.7.17.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-debian-5.7.19.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-ubuntu-5.5.53.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-ubuntu-8.0.15.log-expected.json
  filebeat/module/mysql/slowlog/test/percona-ubuntu-5.7.19-innodb.log-expected.json
  filebeat/module/mysql/slowlog/test/percona-ubuntu-5.7.19.log-expected.json
  filebeat/module/mysql/slowlog/test/percona-ubuntu-8.0.15.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, needs_backport

#17508 Cherry-pick #17429 to 7.x: Add data directories to kubernetes manifests
  CHANGELOG.next.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset.yaml
Labels: backport, review

#17509 Cherry-pick #17429 to 7.7: Add data directories to kubernetes manifests
  CHANGELOG.next.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset.yaml
Labels: backport, review

#17430 Add autodiscover example for Auditbeat
  auditbeat/docs/running-on-kubernetes.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-configmap.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Labels: Auditbeat, Team:Platforms, Team:SIEM, [zube]: In Review, containers, needs_backport, review, v7.6.3, v7.7.0, v7.8.0

#17507 Fix kafka TestConfigAcceptValid test when when GSS-API mechanism is used
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config.reference.yml.tmpl
  libbeat/outputs/kafka/config_test.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Services, [zube]: In Review

#17409 Cherry-pick #17147 to 7.x: Add support for MODULE in mage goIntegTest for metricbeat
  CHANGELOG-developer.next.asciidoc
  dev-tools/mage/gotest.go
  dev-tools/mage/integtest.go
  metricbeat/magefile.go
  x-pack/metricbeat/magefile.go
Labels: [zube]: Inbox, backport, review

#17387 Add .ci to the list of directories that trigger all travis builds
  .ci/scripts/travis_has_changes.sh
  Jenkinsfile
Labels: :Testing, Team:Integrations, [zube]: In Review, ci, needs_backport, review, v7.7.0, v7.8.0

#17522 Cherry-pick #17491 to 7.x: [Filebeat] Improve ECS categorization field mappings for mysql module
  CHANGELOG.next.asciidoc
  filebeat/module/mysql/error/ingest/pipeline.json
  filebeat/module/mysql/error/ingest/pipeline.yml
  filebeat/module/mysql/error/manifest.yml
  filebeat/module/mysql/error/test/error.log-expected.json
  filebeat/module/mysql/error/test/mariadb-10.4.8.log-expected.json
  filebeat/module/mysql/error/test/mysql-darwin-brew-5.7.10.log-expected.json
  filebeat/module/mysql/error/test/mysql-ubuntu-5.5.53.log-expected.json
  filebeat/module/mysql/error/test/mysql-ubuntu-8.0.15.log-expected.json
  filebeat/module/mysql/slowlog/ingest/pipeline.json
  filebeat/module/mysql/slowlog/test/mariadb-10.1.21.log-expected.json
  filebeat/module/mysql/slowlog/test/mariadb-10.2.12.log-expected.json
  filebeat/module/mysql/slowlog/test/mariadb-10.3.13.log-expected.json
  filebeat/module/mysql/slowlog/test/mariadb-explain.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-5.7.22.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-darwin-brew-5.7.10.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-debian-5.7.17.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-debian-5.7.19.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-ubuntu-5.5.53.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-ubuntu-8.0.15.log-expected.json
  filebeat/module/mysql/slowlog/test/percona-ubuntu-5.7.19-innodb.log-expected.json
  filebeat/module/mysql/slowlog/test/percona-ubuntu-5.7.19.log-expected.json
  filebeat/module/mysql/slowlog/test/percona-ubuntu-8.0.15.log-expected.json
Labels: Team:SIEM, backport, review

#17486 Remove build parameters.
  CHANGELOG.next.asciidoc
  x-pack/libbeat/processors/add_cloudfoundry_metadata/add_cloudfoundry_metadata.go
  x-pack/libbeat/processors/add_cloudfoundry_metadata/add_cloudfoundry_metadata_test.go
Labels: Team:Platforms, [zube]: In Review, bug, x-pack

#17296 Update testing env 7.7.0
  testing/environments/latest.yml
Labels: :Testing, [zube]: In Review, release, review, v7.7.0

#17431 Add auditd example with Auditbeat in kubernetes manifests
  CHANGELOG.next.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-configmap.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Labels: Auditbeat, Team:Platforms, Team:SIEM, [zube]: In Review, needs_backport, review, test-plan, v7.7.0, v7.8.0

#17484 Cherry-pick #17456 to 7.7: [Filebeat] Add access_key_id, secret_access_key and session_token into aws module config
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/aws/_meta/config.yml
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/cloudtrail/config/s3.yml
  x-pack/filebeat/module/aws/cloudtrail/manifest.yml
  x-pack/filebeat/module/aws/cloudwatch/config/s3.yml
  x-pack/filebeat/module/aws/cloudwatch/manifest.yml
  x-pack/filebeat/module/aws/ec2/config/s3.yml
  x-pack/filebeat/module/aws/ec2/manifest.yml
  x-pack/filebeat/module/aws/elb/config/s3.yml
  x-pack/filebeat/module/aws/elb/manifest.yml
  x-pack/filebeat/module/aws/s3access/config/s3.yml
  x-pack/filebeat/module/aws/s3access/manifest.yml
  x-pack/filebeat/module/aws/vpcflow/config/input.yml
  x-pack/filebeat/module/aws/vpcflow/manifest.yml
  x-pack/filebeat/modules.d/aws.yml.disabled
Labels: Team:Platforms, [zube]: Inbox, backport, review

#17461 [Agent] Handle abs paths on windows correctly
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/transpiler/steps.go
  x-pack/elastic-agent/pkg/agent/transpiler/steps_test.go
Labels: Project:fleet, Team:Ingest Management, agent, bug, needs_backport

#17540 Cherry-pick #17486 to 7.x: Remove build parameters.
  CHANGELOG.next.asciidoc
  x-pack/libbeat/processors/add_cloudfoundry_metadata/add_cloudfoundry_metadata.go
  x-pack/libbeat/processors/add_cloudfoundry_metadata/add_cloudfoundry_metadata_test.go
Labels: Team:Platforms, backport, review

#17541 Cherry-pick #17486 to 7.7: Remove build parameters.
  CHANGELOG.next.asciidoc
  x-pack/libbeat/processors/add_cloudfoundry_metadata/add_cloudfoundry_metadata.go
  x-pack/libbeat/processors/add_cloudfoundry_metadata/add_cloudfoundry_metadata_test.go
Labels: Team:Platforms, backport, review

#17542 [Metricbeat] Fix s3 dashboard to use aws.s3.bucket.name field name
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-s3-overview.json
Labels: Team:Platforms, bug, needs_backport, review

#17548 Revert "[Filebeat] Get AWS credentials again when token expired"
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/s3/input.go
Labels: Filebeat, Team:Platforms

#17532 Cherry-pick #12774 to 7.x: enable make help for the top level makefile
  Makefile
Labels: backport, review

#17535 Cherry-pick #17507 to 7.x: Fix kafka TestConfigAcceptValid test when when GSS-API mechanism is used
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config.reference.yml.tmpl
  libbeat/outputs/kafka/config_test.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Services, [zube]: In Review, backport

#17536 Cherry-pick #17507 to 7.7: Fix kafka TestConfigAcceptValid test when when GSS-API mechanism is used
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config.reference.yml.tmpl
  libbeat/outputs/kafka/config_test.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Services, [zube]: In Review, backport

#17560 Cherry-pick #17512 to 7.x: Fix Unix socket path in memcached
  CHANGELOG.next.asciidoc
  metricbeat/module/memcached/stats/stats.go
  metricbeat/module/memcached/stats/stats_test.go
Labels: backport, review

#17545 Cherry-pick #17431 to 7.x: Add auditd example with Auditbeat in kubernetes manifests
  CHANGELOG.next.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-configmap.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Labels: backport, review

#17546 Cherry-pick #17431 to 7.7: Add auditd example with Auditbeat in kubernetes manifests
  CHANGELOG.next.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-configmap.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Labels: backport, review

#17561 Cherry-pick #17512 to 7.7: Fix Unix socket path in memcached
  CHANGELOG.next.asciidoc
  metricbeat/module/memcached/stats/stats.go
  metricbeat/module/memcached/stats/stats_test.go
Labels: backport, review

#17469 Replace HOSTNAME with NODE_NAME when accessing Kubelet API
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/docs/running-on-kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Platforms, [zube]: In Review, needs_backport, review, v7.7.0, v7.8.0

#17562 Fix istio mapping
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/istio/fields.go
  x-pack/metricbeat/module/istio/mixer/_meta/data.json
  x-pack/metricbeat/module/istio/mixer/_meta/fields.yml
  x-pack/metricbeat/module/istio/mixer/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/istio/mixer/mixer.go
  x-pack/metricbeat/module/istio/pilot/_meta/fields.yml
  x-pack/metricbeat/module/istio/pilot/_meta/testdata/docs.plain
  x-pack/metricbeat/module/istio/pilot/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/istio/pilot/pilot.go
Labels: Team:Platforms, [zube]: In Review, bug, needs_backport, review, v7.7.0, v7.8.0

#17565 Cherry-pick #17469 to 7.7: Replace HOSTNAME with NODE_NAME when accessing Kubelet API
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/docs/running-on-kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Platforms, backport, review

#17564 Cherry-pick #17469 to 7.x: Replace HOSTNAME with NODE_NAME when accessing Kubelet API
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/docs/running-on-kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Platforms, backport, review

#17568 Cherry-pick #17562 to 7.x: Fix istio mapping
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/istio/fields.go
  x-pack/metricbeat/module/istio/mixer/_meta/data.json
  x-pack/metricbeat/module/istio/mixer/_meta/fields.yml
  x-pack/metricbeat/module/istio/mixer/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/istio/mixer/mixer.go
  x-pack/metricbeat/module/istio/pilot/_meta/fields.yml
  x-pack/metricbeat/module/istio/pilot/_meta/testdata/docs.plain
  x-pack/metricbeat/module/istio/pilot/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/istio/pilot/pilot.go
Labels: Team:Platforms, backport, review

#17567 Cherry-pick #17562 to 7.7: Fix istio mapping
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/istio/fields.go
  x-pack/metricbeat/module/istio/mixer/_meta/data.json
  x-pack/metricbeat/module/istio/mixer/_meta/fields.yml
  x-pack/metricbeat/module/istio/mixer/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/istio/mixer/mixer.go
  x-pack/metricbeat/module/istio/pilot/_meta/fields.yml
  x-pack/metricbeat/module/istio/pilot/_meta/testdata/docs.plain
  x-pack/metricbeat/module/istio/pilot/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/istio/pilot/pilot.go
Labels: Team:Platforms, [zube]: In Review, backport, review

#17555 Fix vsphere VM dashboard show VM host aggregation works
  CHANGELOG.next.asciidoc
  metricbeat/module/vsphere/_meta/kibana/7/dashboard/metricbeat-vsphere-vm.json
Labels: Team:Platforms, [zube]: Inbox, bug, needs_backport, v7.6.3, v7.7.0, v7.8.0

#17412 Cherry-pick #17393 to 7.x: Add metricbeat as dependency for auditbeat to Pipeline check
  Jenkinsfile
Labels: [zube]: Inbox, backport, review

#17575 Cherry-pick #17555 to 7.x: Fix vsphere VM dashboard show VM host aggregation works
  CHANGELOG.next.asciidoc
  metricbeat/module/vsphere/_meta/kibana/7/dashboard/metricbeat-vsphere-vm.json
Labels: Team:Platforms, backport, review

#17543 feat: add Docker images to the workes cache
  .ci/packer_cache.sh
Labels: [zube]: In Review, automation, ci, enhancement

#17514 Cherry-pick #17500 to 7.7: [Auditbeat] Memory leak and syscall fix
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/socket/_meta/docs.asciidoc
  x-pack/auditbeat/module/system/socket/arch_386.go
  x-pack/auditbeat/module/system/socket/config.go
  x-pack/auditbeat/module/system/socket/socket_linux.go
  x-pack/auditbeat/module/system/socket/state.go
  x-pack/auditbeat/module/system/socket/state_test.go
Labels: Auditbeat, Team:SIEM, backport, review

#17574 Cherry-pick #16927 to 7.x: Fix issue when building Agent snapshot and enable building the agent.
  Makefile
  dev-tools/mage/crossbuild.go
  dev-tools/mage/dmgbuilder.go
  dev-tools/mage/dockerbuilder.go
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.agent.tmpl
  dev-tools/packaging/templates/docker/docker-entrypoint.agent.tmpl
  x-pack/agent/CHANGELOG.asciidoc
  x-pack/agent/_meta/agent.docker.yml
  x-pack/agent/_meta/agent.fleet.yml
  x-pack/agent/_meta/agent.yml
  x-pack/agent/_meta/common.p2.yml
  x-pack/agent/_meta/common.reference.p2.yml
  x-pack/agent/agent.docker.yml
  x-pack/agent/agent.reference.yml
  x-pack/agent/agent.yml
  x-pack/agent/magefile.go
  x-pack/agent/pkg/agent/application/configuration_embed.go
  x-pack/agent/pkg/agent/operation/operator.go
  x-pack/agent/pkg/agent/operation/operator_handlers.go
  x-pack/agent/pkg/artifact/download/fs/downloader.go
  x-pack/agent/pkg/artifact/download/fs/verifier.go
  x-pack/agent/pkg/artifact/install/installer.go
  x-pack/agent/pkg/artifact/install/tar/tar_installer.go
  x-pack/agent/pkg/artifact/install/zip/zip_installer.go
  x-pack/agent/pkg/basecmd/version/cmd.go
  x-pack/agent/pkg/release/version.go
Labels: Team:Ingest Management, [zube]: In Review, backport, review

#17557 Cherry-pick #17542 to 7.7: [Metricbeat] Fix s3 dashboard to use aws.s3.bucket.name field name
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-s3-overview.json
Labels: Team:Platforms, backport, review

#17482 Cherry-pick #17473 to 7.7: Jenkinsfile: Fix auditbeat check and add comments
  Jenkinsfile
Labels: Team:Services, [zube]: Inbox, backport, ci, review

#17573 Fix jenkins match patterns
  Jenkinsfile
Labels: Team:Services, bug, ci, review

#17566 Ceph: describe exposed ports
  metricbeat/docs/modules/ceph.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/ceph/_meta/config.reference.yml
  metricbeat/module/ceph/_meta/docs.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Metricbeat, Team:Services, [zube]: In Review, docs, module, needs_backport, review, v7.7.0, v7.8.0

#17576 Cherry-pick #17555 to 7.7: Fix vsphere VM dashboard show VM host aggregation works
  CHANGELOG.next.asciidoc
  metricbeat/module/vsphere/_meta/kibana/7/dashboard/metricbeat-vsphere-vm.json
Labels: Team:Platforms, backport, review

#17510 Add ingress_controller docs
  filebeat/docs/modules/nginx.asciidoc
  filebeat/module/nginx/_meta/docs.asciidoc
Labels: Team:Platforms, [zube]: In Review, docs, needs_backport, review, v7.7.0, v7.8.0

#17577 Cherry-pick #16931 to 7.x: Fleet gateway had a deadlocking test
  x-pack/agent/pkg/agent/application/fleet_gateway_test.go
Labels: Team:Ingest Management, [zube]: In Review, backport, review

#17578 Cherry-pick #17336 to 7.x: Display the stability status of the Elastic Agent
  x-pack/agent/CHANGELOG.asciidoc
  x-pack/agent/pkg/agent/application/application.go
  x-pack/agent/pkg/agent/cmd/enroll.go
  x-pack/agent/pkg/agent/warn/warn.go
Labels: Team:Ingest Management, backport, review

#17505 New processor: urldecode
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  filebeat/tests/system/test_processors.py
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config.reference.yml.tmpl
  libbeat/cmd/instance/imports_common.go
  libbeat/docs/processors-list.asciidoc
  libbeat/processors/urldecode/docs/urldecode.asciidoc
  libbeat/processors/urldecode/urldecode.go
  libbeat/processors/urldecode/urldecode_test.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Services, [zube]: In Review

#17582 Cherry-pick #16922 to 7.x: [Agent] Fixed test to pass on windows
  x-pack/agent/pkg/agent/operation/common_test.go
  x-pack/agent/pkg/agent/operation/monitoring_test.go
  x-pack/agent/pkg/agent/operation/operator_test.go
  x-pack/agent/pkg/core/plugin/app/monitoring/beats/beats_monitor.go
  x-pack/agent/pkg/core/plugin/app/monitoring/beats/drop_test.go
Labels: Team:Ingest Management, [zube]: In Review, backport, review

#17583 Cherry-pick #17112 to 7.x: [Agent] Support for config constraints
  go.mod
  x-pack/agent/CHANGELOG.asciidoc
  x-pack/agent/pkg/agent/application/emitter.go
  x-pack/agent/pkg/agent/application/filters/constraints_filter.go
  x-pack/agent/pkg/agent/application/filters/constraints_filter_test.go
  x-pack/agent/pkg/agent/application/info/agent_id.go
  x-pack/agent/pkg/agent/application/local_mode.go
  x-pack/agent/pkg/agent/application/managed_mode.go
  x-pack/agent/pkg/agent/program/program_test.go
  x-pack/agent/pkg/agent/program/testdata/constraints_config-filebeat.yml
  x-pack/agent/pkg/agent/program/testdata/constraints_config.yml
  x-pack/agent/pkg/agent/transpiler/ast.go
  x-pack/agent/pkg/boolexp/boolexp_test.go
Labels: Team:Ingest Management, [zube]: In Review, backport, review

#17586 Cherry-pick #16994 to 7.x: [Agent] Fix ACK to fleet
  x-pack/agent/pkg/agent/application/action_store.go
  x-pack/agent/pkg/agent/application/fleet_acker.go
  x-pack/agent/pkg/fleetapi/ack_cmd.go
Labels: Team:Ingest Management, [zube]: In Review, backport, review

#17497 Fix initialization of Logstash service URL
  CHANGELOG.next.asciidoc
  metricbeat/module/logstash/_meta/Dockerfile
  metricbeat/module/logstash/_meta/pipeline/logstash.conf
  metricbeat/module/logstash/docker-compose.yml
  metricbeat/module/logstash/logstash_integration_test.go
  metricbeat/module/logstash/node_stats/node_stats.go
  metricbeat/module/logstash/node_stats/node_stats_test.go
  testing/environments/local.yml
Labels: Metricbeat, Stack monitoring, Team:Services, [zube]: In Review, bug, module, needs_backport, v7.6.3, v7.7.1, v7.8.0, v8.0.0

#17556 Cherry-pick #17542 to 7.x: [Metricbeat] Fix s3 dashboard to use aws.s3.bucket.name field name
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-s3-overview.json
Labels: Team:Platforms, backport, review

#17533 Cherry-pick #17387 to 7.x: Add .ci to the list of directories that trigger all travis builds
  Jenkinsfile
Labels: [zube]: In Review

#17534 Cherry-pick #17387 to 7.7: Add .ci to the list of directories that trigger all travis builds
  Jenkinsfile
Labels: backport, review

#17530 Cherry-pick #17430 to 7.x: Add autodiscover example for Auditbeat
  auditbeat/docs/running-on-kubernetes.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-configmap.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Labels: backport, review

#17531 Cherry-pick #17430 to 7.7: Add autodiscover example for Auditbeat
  auditbeat/docs/running-on-kubernetes.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-configmap.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
Labels: backport, review

#17588 Cherry-pick #17241 to 7.x: [Agent] Enable post install hooks
  x-pack/agent/CHANGELOG.asciidoc
  x-pack/agent/pkg/agent/program/spec.go
  x-pack/agent/pkg/agent/program/spec_test.go
  x-pack/agent/pkg/agent/program/supported.go
  x-pack/agent/pkg/agent/transpiler/rules.go
  x-pack/agent/pkg/agent/transpiler/steps.go
  x-pack/agent/pkg/agent/transpiler/steps_test.go
  x-pack/agent/pkg/artifact/install/hooks/hooks_installer.go
  x-pack/agent/pkg/artifact/install/installer.go
  x-pack/agent/spec/metricbeat.yml
Labels: Team:Ingest Management, [zube]: In Review, backport, review

#17450 [docs] Documentation updates from APM (#15835)
  libbeat/docs/command-reference.asciidoc
  libbeat/docs/security/api-keys.asciidoc
  libbeat/docs/shared-securing-beat.asciidoc
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: backport, docs

#17405 Cherry-pick #17374 to 7.x: Fix mbean parsing for mbeans with multiple quoted properties
  CHANGELOG.next.asciidoc
  metricbeat/module/jolokia/jmx/config.go
  metricbeat/module/jolokia/jmx/config_test.go
Labels: [zube]: Inbox, backport, review

#17407 Cherry-pick #17374 to 7.7: Fix mbean parsing for mbeans with multiple quoted properties
  CHANGELOG.next.asciidoc
  metricbeat/module/jolokia/jmx/config.go
  metricbeat/module/jolokia/jmx/config_test.go
Labels: [zube]: Inbox, backport, review
