Repository elastic/beats, pull requests merged in 2020-01, with the labels that each got.

#15288 Remove journalbeat dashboard
  CHANGELOG.next.asciidoc
  NOTICE.txt
  journalbeat/_meta/kibana/7/dashboard/Journalbeat-overview.json
Labels: Team:Beats, [zube]: In Review, needs_backport

#15237 [Agent] refactor reporter
  x-pack/agent/pkg/agent/application/fleet_gateway.go
  x-pack/agent/pkg/agent/application/fleet_gateway_test.go
  x-pack/agent/pkg/agent/application/managed_mode.go
  x-pack/agent/pkg/reporter/fleet/reporter.go
  x-pack/agent/pkg/reporter/fleet/reporter_test.go
Labels: Project:fleet, [zube]: In Review, agent, review

#15291 Cherry-pick #15288 to 7.5: Remove journalbeat dashboard
  CHANGELOG.next.asciidoc
  NOTICE.txt
  journalbeat/_meta/kibana/7/dashboard/Journalbeat-overview.json
Labels: backport, review

#15290 Cherry-pick #15288 to 7.x: Remove journalbeat dashboard
  CHANGELOG.next.asciidoc
  NOTICE.txt
  journalbeat/_meta/kibana/7/dashboard/Journalbeat-overview.json
Labels: Team:Beats, [zube]: In Progress, backport, review

#15293 Update elastic/go-sysinfo to v1.2.0
  NOTICE.txt
  vendor/github.com/elastic/go-sysinfo/CHANGELOG.md
  vendor/github.com/elastic/go-sysinfo/NOTICE.txt
  vendor/github.com/elastic/go-sysinfo/README.md
  vendor/github.com/elastic/go-sysinfo/go.mod
  vendor/github.com/elastic/go-sysinfo/go.sum
  vendor/vendor.json
Labels: Team:Beats, [zube]: In Review, needs_backport

#15282 [Agent] Fix flaky tests concerning the TokenBucket
  x-pack/agent/pkg/tokenbucket/token_bucket.go
  x-pack/agent/pkg/tokenbucket/token_bucket_test.go
Labels: Project:fleet, [zube]: In Review, agent, review

#15286 [6.8] Adding CHANGELOG entry (#15280)
  CHANGELOG.next.asciidoc
Labels: backport

#15285 [7.5] Adding CHANGELOG entry (#15280)
  CHANGELOG.next.asciidoc
Labels: backport

#15284 [7.x] Adding CHANGELOG entry (#15280)
  CHANGELOG.next.asciidoc
Labels: backport

#15294 [Agent] Onboard custom errors package - part 2
  NOTICE.txt
  x-pack/agent/pkg/agent/errors/types.go
  x-pack/agent/pkg/agent/operation/monitoring.go
  x-pack/agent/pkg/agent/operation/operation_config.go
  x-pack/agent/pkg/agent/operation/operation_fetch.go
  x-pack/agent/pkg/agent/operation/operation_install.go
  x-pack/agent/pkg/agent/operation/operation_remove.go
  x-pack/agent/pkg/agent/operation/operation_start.go
  x-pack/agent/pkg/agent/operation/operation_stop.go
  x-pack/agent/pkg/agent/operation/operation_verify.go
  x-pack/agent/pkg/agent/operation/operator.go
  x-pack/agent/pkg/agent/operation/operator_handlers.go
  x-pack/agent/pkg/agent/program/program.go
  x-pack/agent/pkg/agent/program/spec.go
  x-pack/agent/pkg/core/plugin/app/process_cred.go
  x-pack/agent/pkg/core/plugin/process/process.go
  x-pack/agent/pkg/filewatcher/watcher.go
  x-pack/agent/pkg/fleetapi/action.go
  x-pack/agent/pkg/fleetapi/checkin_cmd.go
  x-pack/agent/pkg/fleetapi/client.go
  x-pack/agent/pkg/fleetapi/enroll_cmd.go
  x-pack/agent/pkg/packer/packer.go
  x-pack/agent/pkg/reporter/reporter.go
Labels: Project:fleet, [zube]: In Review, agent, review

#15257 Cherry-pick #15248 to 7.x: [Filebeat] Add beta label for aws filesets
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/_meta/fields.yml
  x-pack/filebeat/module/aws/elb/_meta/fields.yml
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/module/aws/s3access/_meta/fields.yml
  x-pack/filebeat/module/aws/vpcflow/_meta/fields.yml
Labels: backport, review

#15222 [Heartbeat] Add docs for rootless pings (#15194)
  heartbeat/docs/heartbeat-options.asciidoc
Labels: :uptime, Heartbeat, backport, docs, v7.5.2

#15221 [Heartbeat] Add docs for rootless pings (#15194)
  heartbeat/docs/heartbeat-options.asciidoc
Labels: :uptime, Heartbeat, backport, docs, v7.6.0

#15307 Revert ubi packaging
  dev-tools/packaging/packages.yml
Labels: Team:Beats, [zube]: In Progress

#15153 Cherry-pick #14299 to 7.x: Add Group Management Events - Add NewUAC Description for User Management Events
  x-pack/winlogbeat/module/security/config/winlogbeat-security.js
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4720_Account_Created.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4727.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4727.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4728.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4728.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4729.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4729.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4730.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4730.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4731.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4731.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4732.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4732.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4733.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4733.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4734.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4734.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4735.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4735.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4737.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4737.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4738_Account_Changed.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4754.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4754.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4755.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4755.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4756.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4756.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4757.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4757.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4758.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4758.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4764.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4764.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4798.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4798.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4799.evtx
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4799.evtx.golden.json
Labels: backport, review

#15224 [metricbeat]Docker: add size flag to docker.container
  CHANGELOG.next.asciidoc
  metricbeat/module/docker/container/_meta/data.json
  metricbeat/module/docker/container/container.go
Labels: Metricbeat, Team:Integrations, bug, containers, needs_backport, review

#15315 Cherry-pick #14859 to 7.x: [metricbeat]kubernetes: add kube-state-metrics persistentvolumes
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/helper/prometheus/prometheus.go
  metricbeat/include/list_docker.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/_meta/config.yml
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_persistentvolume/README.md
  metricbeat/module/kubernetes/state_persistentvolume/_meta/fields.yml
  metricbeat/module/kubernetes/state_persistentvolume/_meta/test/ksm-unit-1.8
  metricbeat/module/kubernetes/state_persistentvolume/_meta/test/ksm-unit-1.8.expected
  metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume.go
  metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume_test.go
  metricbeat/module/kubernetes/state_persistentvolumeclaim/README.md
  metricbeat/modules.d/kubernetes.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: backport, review

#15316 Cherry-pick #15190 to 7.x: [metricbeat]kubernetes: ksm service labels
  metricbeat/module/kubernetes/state_service/_meta/data.json
  metricbeat/module/kubernetes/state_service/_meta/test/ksm-unit-1.8.expected
  metricbeat/module/kubernetes/state_service/_meta/testdata/kube-state-metrics.1.7.plain-expected.json
  metricbeat/module/kubernetes/state_service/_meta/testdata/kube-state-metrics.1.8.plain
  metricbeat/module/kubernetes/state_service/_meta/testdata/kube-state-metrics.1.8.plain-expected.json
  metricbeat/module/kubernetes/state_service/state_service.go
Labels: backport, review

#15318 Cherry-pick #15224 to 7.5: [metricbeat]Docker: add size flag to docker.container
  CHANGELOG.next.asciidoc
  metricbeat/module/docker/container/_meta/data.json
  metricbeat/module/docker/container/container.go
Labels: backport, review, v7.5.2

#15310 [Filebeat] Remove timestamp from iptables filebeat module
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/module/cisco/asa/test/asa.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/filtered.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/hostnames.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/not-ip.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ios/test/cisco-ios-syslog.log-expected.json
  x-pack/filebeat/module/iptables/log/test/geo.log-expected.json
  x-pack/filebeat/module/iptables/log/test/icmp.log-expected.json
  x-pack/filebeat/module/iptables/log/test/iptables.log-expected.json
  x-pack/filebeat/module/iptables/log/test/ipv6.log-expected.json
  x-pack/filebeat/module/iptables/log/test/ubiquiti.log-expected.json
Labels: Filebeat, Team:Integrations, needs_backport, review

#15317 Cherry-pick #15224 to 7.x: [metricbeat]Docker: add size flag to docker.container
  CHANGELOG.next.asciidoc
  metricbeat/module/docker/container/_meta/data.json
  metricbeat/module/docker/container/container.go
Labels: backport, review

#15311 Cherry-pick #15197 to 7.x: [Winlogbeat] ignore message field in security unit tests
  x-pack/winlogbeat/module/security/test/security_windows_test.go
  x-pack/winlogbeat/module/security/test/testdata/security-windows2012r2-logon.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016-4672.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016-logoff.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4720_Account_Created.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4722_Account_Enabled.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4723_Password_Change.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4724_Password_Reset.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4725_Account_Disabled.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4726_Account_Deleted.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4727.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4728.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4729.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4730.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4731.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4732.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4733.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4734.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4735.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4737.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4738_Account_Changed.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4740_Account_Locked_Out.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4754.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4755.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4756.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4757.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4758.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4764.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4767_Account_Unlocked.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4781_Account_Renamed.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4798.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2016_4799.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2019_4688_Process_Created.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2019_4689_Process_Exited.evtx.golden.json
Labels: backport, review

#15308 Cherry-pick #15307 to 7.x: Revert ubi packaging
  dev-tools/packaging/packages.yml
Labels: backport, review

#15306 Move HTTP calls to Logstash from New() to Fetch()
  CHANGELOG.next.asciidoc
  metricbeat/module/logstash/logstash.go
  metricbeat/module/logstash/node/node.go
  metricbeat/module/logstash/node_stats/node_stats.go
Labels: Metricbeat, Stack monitoring, Team:Beats, bug, module, needs_backport, v7.5.2, v7.6.0, v8.0.0

#15321 Cherry-pick #15310 to 7.5: [Filebeat] Remove timestamp from iptables filebeat module
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/module/cisco/asa/test/asa.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/filtered.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/hostnames.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/not-ip.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ios/test/cisco-ios-syslog.log-expected.json
  x-pack/filebeat/module/iptables/log/test/geo.log-expected.json
  x-pack/filebeat/module/iptables/log/test/icmp.log-expected.json
  x-pack/filebeat/module/iptables/log/test/iptables.log-expected.json
  x-pack/filebeat/module/iptables/log/test/ipv6.log-expected.json
  x-pack/filebeat/module/iptables/log/test/ubiquiti.log-expected.json
Labels: backport, review

#15320 Cherry-pick #15310 to 7.x: [Filebeat] Remove timestamp from iptables filebeat module
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/module/cisco/asa/test/asa.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/filtered.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/hostnames.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/not-ip.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ios/test/cisco-ios-syslog.log-expected.json
  x-pack/filebeat/module/iptables/log/test/geo.log-expected.json
  x-pack/filebeat/module/iptables/log/test/icmp.log-expected.json
  x-pack/filebeat/module/iptables/log/test/iptables.log-expected.json
  x-pack/filebeat/module/iptables/log/test/ipv6.log-expected.json
  x-pack/filebeat/module/iptables/log/test/ubiquiti.log-expected.json
Labels: backport, review

#15300 [Metricbeat] Update field docs for free memory
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/fields.go
  metricbeat/module/system/memory/_meta/fields.yml
Labels: bug, docs, v7.6.0

#15261 [Filebeat] Update MISP module config file
  filebeat/docs/modules/misp.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/misp/_meta/config.yml
  x-pack/filebeat/module/misp/_meta/docs.asciidoc
  x-pack/filebeat/modules.d/misp.yml.disabled
Labels: Filebeat, Team:Integrations, needs_backport, review, skip-test-plan

#15329 Update go-sysinfo to v1.2.1
  NOTICE.txt
  vendor/github.com/elastic/go-sysinfo/CHANGELOG.md
  vendor/github.com/elastic/go-sysinfo/NOTICE.txt
  vendor/github.com/elastic/go-sysinfo/providers/linux/container.go
  vendor/github.com/elastic/go-sysinfo/providers/linux/host_linux.go
  vendor/github.com/elastic/go-sysinfo/providers/linux/machineid.go
  vendor/github.com/elastic/go-sysinfo/providers/linux/os.go
  vendor/github.com/elastic/go-sysinfo/providers/linux/procnet.go
  vendor/github.com/elastic/go-sysinfo/providers/windows/helpers_windows.go
  vendor/github.com/elastic/go-sysinfo/providers/windows/process_windows.go
  vendor/github.com/elastic/go-sysinfo/types/host.go
  vendor/vendor.json
Labels: :integrations, needs_backport, v7.6.0

#15289 Document metricsets that require specific permissions
  metricbeat/docs/modules/system.asciidoc
  metricbeat/module/system/_meta/docs.asciidoc
Labels: Team:Integrations, [zube]: In Review, needs_backport

#15323 [7.5] Move HTTP calls to Logstash from New() to Fetch() (#15306)
  CHANGELOG.next.asciidoc
  metricbeat/module/logstash/logstash.go
  metricbeat/module/logstash/node/node.go
  metricbeat/module/logstash/node_stats/node_stats.go
Labels: backport

#15200 Add audit fileset to googlecloud module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/googlecloud/_meta/config.yml
  x-pack/filebeat/module/googlecloud/audit/_meta/fields.yml
  x-pack/filebeat/module/googlecloud/audit/config/input.yml
  x-pack/filebeat/module/googlecloud/audit/config/pipeline.js
  x-pack/filebeat/module/googlecloud/audit/ingest/pipeline.yml
  x-pack/filebeat/module/googlecloud/audit/manifest.yml
  x-pack/filebeat/module/googlecloud/audit/test/audit-log-entries.json.log
  x-pack/filebeat/module/googlecloud/audit/test/audit-log-entries.json.log-expected.json
  x-pack/filebeat/module/googlecloud/fields.go
  x-pack/filebeat/modules.d/googlecloud.yml.disabled
Labels: Filebeat, Team:SIEM, module, review

#15322 [7.x] Move HTTP calls to Logstash from New() to Fetch() (#15306)
  CHANGELOG.next.asciidoc
  metricbeat/module/logstash/logstash.go
  metricbeat/module/logstash/node/node.go
  metricbeat/module/logstash/node_stats/node_stats.go
Labels: backport

#15325 Scheduler now add some jitter when waiting on Tick.
  x-pack/agent/pkg/agent/application/fleet_gateway.go
  x-pack/agent/pkg/agent/application/managed_mode.go
  x-pack/agent/pkg/scheduler/scheduler.go
  x-pack/agent/pkg/scheduler/scheduler_test.go
Labels: Project:fleet, [zube]: In Review, agent

#15327 Enroll delay
  x-pack/agent/pkg/agent/cmd/enroll.go
Labels: Project:fleet, [zube]: In Review, agent, review

#15331 cherry-pick of #15329 to 7.x: Update go-sysinfo to v1.2.1
  NOTICE.txt
  vendor/github.com/elastic/go-sysinfo/CHANGELOG.md
  vendor/github.com/elastic/go-sysinfo/NOTICE.txt
  vendor/github.com/elastic/go-sysinfo/providers/linux/container.go
  vendor/github.com/elastic/go-sysinfo/providers/linux/host_linux.go
  vendor/github.com/elastic/go-sysinfo/providers/linux/machineid.go
  vendor/github.com/elastic/go-sysinfo/providers/linux/os.go
  vendor/github.com/elastic/go-sysinfo/providers/linux/procnet.go
  vendor/github.com/elastic/go-sysinfo/providers/windows/helpers_windows.go
  vendor/github.com/elastic/go-sysinfo/providers/windows/process_windows.go
  vendor/github.com/elastic/go-sysinfo/types/host.go
  vendor/vendor.json
Labels: :integrations, Team:Integrations, backport

#15335 Cherry-pick #15289 to 7.x: Document metricsets that require specific permissions
  metricbeat/docs/modules/system.asciidoc
  metricbeat/module/system/_meta/docs.asciidoc
Labels: backport, review

#15326 Cherry pick of #15300 to 7.x: Update field docs for free memory
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/fields.go
  metricbeat/module/system/memory/_meta/fields.yml
Labels: backport

#15314 [Auditbeat] Removed GUID from dashboard definition
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/_meta/kibana/7/dashboard/auditbeat-system-host-dashboard.json
Labels: Auditbeat, Team:SIEM, review

#15334 [Metricbeat] Comment out optional configurations in default aws config.yml
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: Metricbeat, Team:Integrations, needs_backport, review, skip-test-plan

#14899 Cherry-pick #14423 to 7.x: Add missing docs for copy_fields and truncate_fields
  libbeat/docs/processors-list.asciidoc
  libbeat/processors/actions/docs/copy_fields.asciidoc
  libbeat/processors/actions/docs/truncate_fields.asciidoc
Labels: backport, review

#15340 [Agent] Onboard to custom errors type - step 3
  x-pack/agent/pkg/agent/application/action_dispatch.go
  x-pack/agent/pkg/agent/application/application.go
  x-pack/agent/pkg/agent/application/config.go
  x-pack/agent/pkg/agent/application/emitter.go
  x-pack/agent/pkg/agent/application/enroll_cmd.go
  x-pack/agent/pkg/agent/application/handler_action_policy_change.go
  x-pack/agent/pkg/agent/application/info/agent_id.go
  x-pack/agent/pkg/agent/application/local_mode.go
  x-pack/agent/pkg/agent/application/managed_mode.go
  x-pack/agent/pkg/agent/application/once.go
  x-pack/agent/pkg/agent/application/periodic.go
  x-pack/agent/pkg/agent/application/stream.go
  x-pack/agent/pkg/agent/cmd/enroll.go
  x-pack/agent/pkg/agent/cmd/run.go
  x-pack/agent/pkg/agent/storage/storage.go
  x-pack/agent/pkg/agent/transpiler/rules.go
  x-pack/agent/pkg/core/plugin/server/server.go
  x-pack/agent/pkg/core/remoteconfig/grpc/factory.go
  x-pack/agent/pkg/dir/discover.go
Labels: Project:fleet, agent, review

#15254 Make cloud.id work for monitoring Elasticsearch reporter
  CHANGELOG.next.asciidoc
  libbeat/cloudid/cloudid.go
  libbeat/cloudid/cloudid_test.go
  libbeat/cmd/instance/beat.go
  libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
  libbeat/monitoring/cloudid.go
  libbeat/monitoring/cloudid_test.go
Labels: Stack monitoring, Team:Beats, [zube]: In Review, enhancement, libbeat, needs_backport, v7.6.0, v8.0.0

#15137 [DOCS] Indicate that Journalbeat dashboard is broken
  journalbeat/docs/getting-started.asciidoc
Labels: Team:Beats, docs, needs_backport, review

#15239 [7.x] Allow console output to make local debugging easier (#15143)
  x-pack/functionbeat/function/beater/functionbeat.go
Labels: backport

#14904 Netflow input: Improve session reset detection and allow disabling
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/netflow.asciidoc
  x-pack/filebeat/docs/inputs/input-netflow.asciidoc
  x-pack/filebeat/input/netflow/config.go
  x-pack/filebeat/input/netflow/decoder/v9/session.go
  x-pack/filebeat/input/netflow/decoder/v9/session_test.go
  x-pack/filebeat/input/netflow/decoder/v9/v9.go
  x-pack/filebeat/input/netflow/input.go
  x-pack/filebeat/module/netflow/_meta/docs.asciidoc
  x-pack/filebeat/module/netflow/log/config/netflow.yml
  x-pack/filebeat/module/netflow/log/manifest.yml
Labels: Filebeat, bug, needs_backport, review

#14865 Update autodiscover docs to add missing settings
  libbeat/docs/shared-autodiscover.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
Labels: Team:Integrations, [zube]: In Review, docs, libbeat, needs_backport, review

#15309 Retries on error when communicating with Fleet
  agent/kibana/client.go
  x-pack/agent/pkg/agent/application/enroll_cmd.go
  x-pack/agent/pkg/agent/application/fleet_gateway.go
  x-pack/agent/pkg/agent/application/fleet_gateway_test.go
Labels: Project:fleet, [zube]: In Review, agent, review

#15299 StateResolver consider errors when updating current state
  x-pack/agent/pkg/agent/operation/operator.go
  x-pack/agent/pkg/agent/stateresolver/stateresolver.go
  x-pack/agent/pkg/agent/stateresolver/stateresolver_test.go
Labels: Project:fleet, agent, review

#15332 Cherry-pick #15261 to 7.x: [Filebeat] Update MISP module config file
  filebeat/docs/modules/misp.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/misp/_meta/config.yml
  x-pack/filebeat/module/misp/_meta/docs.asciidoc
  x-pack/filebeat/modules.d/misp.yml.disabled
Labels: backport, review

#15333 Cherry-pick #15261 to 7.5: [Filebeat] Update MISP module config file
  filebeat/docs/modules/misp.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/misp/_meta/config.yml
  x-pack/filebeat/module/misp/_meta/docs.asciidoc
  x-pack/filebeat/modules.d/misp.yml.disabled
Labels: backport, review

#15350 Cherry-pick #14904 to 7.x: Netflow input: Improve session reset detection and allow disabling
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/netflow.asciidoc
  x-pack/filebeat/docs/inputs/input-netflow.asciidoc
  x-pack/filebeat/input/netflow/config.go
  x-pack/filebeat/input/netflow/decoder/v9/session.go
  x-pack/filebeat/input/netflow/decoder/v9/session_test.go
  x-pack/filebeat/input/netflow/decoder/v9/v9.go
  x-pack/filebeat/input/netflow/input.go
  x-pack/filebeat/module/netflow/_meta/docs.asciidoc
  x-pack/filebeat/module/netflow/log/config/netflow.yml
  x-pack/filebeat/module/netflow/log/manifest.yml
Labels: Team:SIEM, backport, review

#15346 [Elastic Logging Plugin] Fix tarball file name in dockerlogbeat build
  x-pack/dockerlogbeat/magefile.go
Labels: :integrations, Team:Integrations, [zube]: In Review

#15343 [7.x] Make cloud.id work for monitoring Elasticsearch reporter (#15254)
  CHANGELOG.next.asciidoc
  libbeat/cloudid/cloudid.go
  libbeat/cloudid/cloudid_test.go
  libbeat/cmd/instance/beat.go
  libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
  libbeat/monitoring/cloudid.go
  libbeat/monitoring/cloudid_test.go
Labels: backport

#15360 Cherry-pick of #15346: [Elastic Logging Plugin] Fix tarball file name in dockerlogbeat build
  x-pack/dockerlogbeat/magefile.go
Labels: backport, v7.6.0

#15252 [Filebeat] Check content type when reading s3 files
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/s3/input.go
Labels: Filebeat, Team:Integrations, bug, needs_backport, review, test-plan

#15358 Update CHANGELOG for 7.x
  CHANGELOG-developer.asciidoc
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Beats, [zube]: In Review

#15208 Use travis_wait to extend no output timeout
  .travis.yml
Labels: Team:Integrations, [zube]: In Review

#15362 Cherry-pick #15200 to 7.x: Add audit fileset to googlecloud module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/googlecloud/_meta/config.yml
  x-pack/filebeat/module/googlecloud/audit/_meta/fields.yml
  x-pack/filebeat/module/googlecloud/audit/config/input.yml
  x-pack/filebeat/module/googlecloud/audit/config/pipeline.js
  x-pack/filebeat/module/googlecloud/audit/ingest/pipeline.yml
  x-pack/filebeat/module/googlecloud/audit/manifest.yml
  x-pack/filebeat/module/googlecloud/audit/test/audit-log-entries.json.log
  x-pack/filebeat/module/googlecloud/audit/test/audit-log-entries.json.log-expected.json
  x-pack/filebeat/module/googlecloud/fields.go
  x-pack/filebeat/modules.d/googlecloud.yml.disabled
Labels: backport, review

#15361 [DOCS] Remove docs/outputs folder
  libbeat/docs/output-cloud.asciidoc
  libbeat/docs/outputs-list.asciidoc
  x-pack/functionbeat/docs/configuring-howto.asciidoc
Labels: docs, needs_backport, review, technical debt

#15172 [7.5][DOCS] Backport: Switch doc build to use direct_html flag (#15159)
  script/build_docs.sh
Labels: backport, docs, v7.5.0

#15173 [7.x][DOCS] Backport: Switch doc build to use direct_html flag (#15159)
  script/build_docs.sh
Labels: backport, docs, v7.6.0

#15336 Fix/filebeat docker events 15096
  CHANGELOG.next.asciidoc
  libbeat/common/docker/watcher.go
Labels: Team:Integrations, [zube]: Ready, bug, needs_backport, v7.5.0, v7.5.1, v7.6.0

#15140 Fix mage package on generated beats
  .travis.yml
  Jenkinsfile
  generator/beat/{beat}/magefile.go
  generator/common/Makefile
  generator/metricbeat/{beat}/magefile.go
Labels: :Generator, needs_backport, review, v7.5.1, v7.6.0

#15385 Move IBM MQ Filebeat module to GA
  filebeat/docs/modules/ibmmq.asciidoc
  x-pack/filebeat/module/ibmmq/_meta/docs.asciidoc
  x-pack/filebeat/module/ibmmq/_meta/fields.yml
  x-pack/filebeat/module/ibmmq/fields.go
Labels: Filebeat, Team:Integrations, [zube]: In Review, needs_backport, review, v7.6.0

#15373 [Elastic Log Driver] Remove the clean step from build for now
  x-pack/dockerlogbeat/magefile.go
Labels: bug, needs_backport, v7.6.0

#15379 Cherry-pick #15336 to 7.5: Fix/filebeat docker events 15096
  CHANGELOG.next.asciidoc
  libbeat/common/docker/watcher.go
Labels: backport, review

#15378 Cherry-pick #15336 to 7.x: Fix/filebeat docker events 15096
  CHANGELOG.next.asciidoc
  libbeat/common/docker/watcher.go
Labels: backport, review

#15389 Cherry-pick #15385 to 7.x: Move IBM MQ Filebeat module to GA
  filebeat/docs/modules/ibmmq.asciidoc
  x-pack/filebeat/module/ibmmq/_meta/docs.asciidoc
  x-pack/filebeat/module/ibmmq/_meta/fields.yml
  x-pack/filebeat/module/ibmmq/fields.go
Labels: backport, review

#15298 Cherry-pick #14342 to 7.x: [Filebeat] Add dashboards to CEF module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/cef/_meta/kibana/7/dashboard/filebeat-cef-endpoint-os-activity.json
  x-pack/filebeat/module/cef/_meta/kibana/7/dashboard/filebeat-cef-endpoint-overview.json
  x-pack/filebeat/module/cef/_meta/kibana/7/dashboard/filebeat-cef-microsoft-dns.json
  x-pack/filebeat/module/cef/_meta/kibana/7/dashboard/filebeat-cef-network-overview.json
  x-pack/filebeat/module/cef/_meta/kibana/7/dashboard/filebeat-cef-network-suspicious-activity.json
  x-pack/filebeat/module/cef/log/test/cef.log-expected.json
  x-pack/filebeat/processors/decode_cef/_meta/fields.yml
  x-pack/filebeat/processors/decode_cef/cef/cef.go
  x-pack/filebeat/processors/decode_cef/cef/cef_test.go
  x-pack/filebeat/processors/decode_cef/cef/keys.go
  x-pack/filebeat/processors/decode_cef/cef/types.go
  x-pack/filebeat/processors/decode_cef/decode_cef.go
  x-pack/filebeat/processors/decode_cef/decode_cef_test.go
  x-pack/filebeat/processors/decode_cef/fields.go
  x-pack/filebeat/processors/decode_cef/keys.ecs.go
  x-pack/filebeat/processors/decode_cef/testdata/samples.log.golden.json
Labels: Team:SIEM, backport, review

#15387 Cherry-pick #15373 to 7.x: [Elastic Log Driver] Remove the clean step from build for now
  x-pack/dockerlogbeat/magefile.go
Labels: backport, review

#15367 Cherry-pick #15252 to 7.x: [Filebeat] Check content type when reading s3 files
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/s3/input.go
Labels: backport, review

#15363 Cherry-pick #15334 to 7.x: [Metricbeat] Comment out optional configurations in default aws config.yml
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: backport, review

#15364 Cherry-pick #15334 to 7.5: [Metricbeat] Comment out optional configurations in default aws config.yml
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: backport, review

#15369 Cherry-pick #15252 to 7.5: [Filebeat] Check content type when reading s3 files
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/s3/input.go
Labels: backport, review

#15384 [Agent] Combine spec with translation rules together with app info spec
  x-pack/agent/pkg/agent/operation/monitoring.go
  x-pack/agent/pkg/agent/operation/operation.go
  x-pack/agent/pkg/agent/operation/operation_install.go
  x-pack/agent/pkg/agent/operation/operator.go
  x-pack/agent/pkg/agent/operation/operator_handlers.go
  x-pack/agent/pkg/agent/operation/operator_test.go
  x-pack/agent/pkg/agent/operation/tests/scripts/configurable-1.0-darwin-x86/README.md
  x-pack/agent/pkg/agent/operation/tests/scripts/configurable-1.0-darwin-x86/configurable.spec
  x-pack/agent/pkg/agent/operation/tests/scripts/configurablebyfile-1.0-darwin-x86/README.md
  x-pack/agent/pkg/agent/operation/tests/scripts/configurablebyfile-1.0-darwin-x86/configurablebyfile.spec
  x-pack/agent/pkg/agent/operation/tests/scripts/long-1.0-darwin-x86/README.md
  x-pack/agent/pkg/agent/operation/tests/scripts/long-1.0-darwin-x86/long.spec
  x-pack/agent/pkg/agent/operation/tests/scripts/short-1.0-darwin-x86/README.md
  x-pack/agent/pkg/agent/operation/tests/scripts/short-1.0-darwin-x86/short.spec
  x-pack/agent/pkg/agent/program/spec.go
  x-pack/agent/pkg/agent/program/spec_test.go
  x-pack/agent/pkg/agent/program/supported.go
  x-pack/agent/pkg/core/plugin/app/app.go
  x-pack/agent/pkg/core/plugin/app/configure.go
  x-pack/agent/pkg/core/plugin/app/descriptor.go
  x-pack/agent/pkg/core/plugin/app/spec.go
  x-pack/agent/pkg/core/plugin/app/start.go
  x-pack/agent/spec/filebeat.yml
  x-pack/agent/spec/metricbeat.yml
  x-pack/filebeat/filebeat.spec
  x-pack/metricbeat/metricbeat.spec
Labels: Project:fleet, agent, review

#15371 [DOCS] Adds description for missing kafka_home parameter
  filebeat/docs/modules/kafka.asciidoc
  filebeat/module/kafka/_meta/docs.asciidoc
Labels: docs, needs_backport, review

#15312 Providing the Why for the elevated privileges.
  filebeat/docs/running-on-kubernetes.asciidoc
Labels: docs

#15365 Cherry-pick #15359 to 7.x: [Elastic Logging Plugin] add dockerlogbeat to make release (#15359)
  Makefile
Labels: backport

#15353 Configuration option for HTTP request header redaction.
  CHANGELOG.next.asciidoc
  packetbeat/_meta/beat.reference.yml
  packetbeat/docs/packetbeat-options.asciidoc
  packetbeat/packetbeat.reference.yml
  packetbeat/protos/http/config.go
  packetbeat/protos/http/http.go
  packetbeat/protos/http/http_test.go
Labels: Packetbeat, Team:SIEM, enhancement, review

#15345 [7.5][DOCS] Backport: Add note about broken dashboards (#15137)
  journalbeat/docs/getting-started.asciidoc
Labels: backport, docs, v7.5.0

#15376 [7.5][DOCS] Backport: Remove outputs folder under docs (#15361)
  libbeat/docs/output-cloud.asciidoc
  libbeat/docs/outputs-list.asciidoc
  x-pack/functionbeat/docs/configuring-howto.asciidoc
Labels: backport, docs, libbeat, v7.5.0

#15377 [7.x][DOCS] Backport: Remove outputs folder under docs (#15361)
  libbeat/docs/output-cloud.asciidoc
  libbeat/docs/outputs-list.asciidoc
  x-pack/functionbeat/docs/configuring-howto.asciidoc
Labels: backport, docs, libbeat, v7.6.0

#15395 [7.5][DOCS] Backport: Adds description for missing kafka_home parameter (#15371)
  filebeat/docs/modules/kafka.asciidoc
  filebeat/module/kafka/_meta/docs.asciidoc
Labels: Filebeat, backport, docs, v7.5.0

#15400 Revert "[Elastic Logging Plugin] add dockerlogbeat to make release (#15359)"
  Makefile
Labels: needs_backport, v7.6.0

#15344 [7.x][DOCS] Backport: Add note about broken dashboards (#15137)
  journalbeat/docs/getting-started.asciidoc
Labels: backport, docs, v7.6.0

#15396 [7.x][DOCS] Backport: Adds description for missing kafka_home parameter
  filebeat/docs/modules/kafka.asciidoc
  filebeat/module/kafka/_meta/docs.asciidoc
Labels: Filebeat, backport, docs, v7.6.0

#15401 Backport #15400 to 7.x: Revert "[Elastic Logging Plugin] add dockerlogbeat to make release (#15359)
  Makefile
Labels: backport

#15372 Cherry-pick #15208 to 7.x: Use travis_wait to extend no output timeout
  .travis.yml
Labels: backport, review

#15352 [Agent] ACK action events on a handler level
  x-pack/agent/pkg/agent/application/action_dispatch.go
  x-pack/agent/pkg/agent/application/action_dispatch_test.go
  x-pack/agent/pkg/agent/application/fleet_acker.go
  x-pack/agent/pkg/agent/application/fleet_acker_test.go
  x-pack/agent/pkg/agent/application/fleet_gateway.go
  x-pack/agent/pkg/agent/application/fleet_gateway_test.go
  x-pack/agent/pkg/agent/application/handler_action_policy_change.go
  x-pack/agent/pkg/agent/application/handler_action_policy_change_test.go
  x-pack/agent/pkg/agent/application/handler_default.go
  x-pack/agent/pkg/agent/application/handler_unknown.go
  x-pack/agent/pkg/agent/application/managed_mode.go
Labels: Project:fleet, agent, review

#13395 Add more metrics to Filebeat harvesters
  CHANGELOG.next.asciidoc
  filebeat/input/log/harvester.go
  libbeat/monitoring/metrics.go
Labels: Filebeat, Team:Beats, [zube]: In Review, review

#15393 Fix the tick than wait strategy for the PeriodicJitter
  x-pack/agent/pkg/scheduler/scheduler.go
  x-pack/agent/pkg/scheduler/scheduler_test.go
Labels: Project:fleet, [zube]: In Review, agent, review

#15406 [Agent] Increase frequency of the Agent polling
  x-pack/agent/pkg/agent/application/managed_mode.go
Labels: Project:fleet, [zube]: In Review, agent, review

#15411 Cherry-pick #13395 to 7.x: Add more metrics to Filebeat harvesters
  CHANGELOG.next.asciidoc
  filebeat/input/log/harvester.go
  libbeat/monitoring/metrics.go
Labels: Team:Beats, [zube]: In Progress, backport, review

#15356 Add cost warning messages to azure get metric values calls
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/monitor_service.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review

#15349 Add username/password in Metricbeat autodiscover hints
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/builder/helper_test.go
  metricbeat/autodiscover/builder/hints/metrics.go
  metricbeat/docs/autodiscover-hints.asciidoc
Labels: Team:Integrations, [zube]: In Review, autodiscovery, enhancement, review

#15245 [Metricbeat] Update cloudwatch metricset mappings
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/aws/_meta/fields.yml
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-billing-overview.json
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-ebs-overview.json
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-elb-overview.json
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-overview.json
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-sns-overview.json
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-usage-overview.json
  x-pack/metricbeat/module/aws/billing/_meta/data.json
  x-pack/metricbeat/module/aws/cloudwatch/_meta/data.json
  x-pack/metricbeat/module/aws/cloudwatch/_meta/fields.yml
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/ebs/_meta/data.json
  x-pack/metricbeat/module/aws/elb/_meta/data.json
  x-pack/metricbeat/module/aws/elb/_meta/data_alb.json
  x-pack/metricbeat/module/aws/elb/_meta/data_nlb.json
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/mtest/integration.go
  x-pack/metricbeat/module/aws/sns/_meta/data.json
  x-pack/metricbeat/module/aws/usage/_meta/data.json
Labels: Metricbeat, Team:Integrations, breaking change, needs_backport, review, test-plan

#15417 Cherry-pick #15349 to 7.x: Add username/password in Metricbeat autodiscover hints
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/builder/helper_test.go
  metricbeat/autodiscover/builder/hints/metrics.go
  metricbeat/docs/autodiscover-hints.asciidoc
Labels: backport, review

#15419 [Filebeat] Add missing googlecloud.yml.disabled file
  x-pack/filebeat/modules.d/googlecloud.yml.disabled
Labels: Filebeat, bug, needs_backport, review, skip-test-plan

#15238 [OSX] Set MACOSX_DEPLOYMENT_TARGET to remove linking warning
  .travis.yml
Labels: Team:Integrations, [zube]: In Review, flaky-test, needs_backport, skip-test-plan, v7.6.0

#15233 Fix: expect more output lines / Test the addition of a dynamic config
  heartbeat/tests/system/test_reload.py
Labels: Team:Integrations, [zube]: In Review, flaky-test, needs_backport, v7.6.0

#15381 Cherry-pick #15140 to 7.x: Fix mage package on generated beats
  .travis.yml
  generator/beat/{beat}/magefile.go
  generator/common/Makefile
  generator/metricbeat/{beat}/magefile.go
Labels: backport, review

#15427 Cherry-pick #15238 to 7.x: [OSX] Set MACOSX_DEPLOYMENT_TARGET to remove linking warning
  .travis.yml
Labels: backport, review

#15428 Cherry-pick #15233 to 7.x: Fix: expect more output lines / Test the addition of a dynamic config
  heartbeat/tests/system/test_reload.py
Labels: backport, review

#15292 [Metricbeat] Use single data flag
  CHANGELOG-developer.next.asciidoc
  metricbeat/helper/prometheus/ptest/ptest.go
  metricbeat/magefile.go
  metricbeat/mb/testing/data/README.md
  metricbeat/mb/testing/data_generator.go
  metricbeat/mb/testing/flags/flags.go
  metricbeat/mb/testing/testdata.go
Labels: Team:Integrations, [zube]: In Review, needs_backport

#15432 Cherry-pick #15292 to 7.x: [Metricbeat] Use single data flag
  CHANGELOG-developer.next.asciidoc
  metricbeat/helper/prometheus/ptest/ptest.go
  metricbeat/magefile.go
  metricbeat/mb/testing/data/README.md
  metricbeat/mb/testing/data_generator.go
  metricbeat/mb/testing/flags/flags.go
  metricbeat/mb/testing/testdata.go
Labels: backport, review

#15368 Fix test output with ipv6 addresses
  CHANGELOG.next.asciidoc
  libbeat/outputs/elasticsearch/client.go
Labels: bug, needs_backport, v7.6.0

#15446 Cherry-pick #15368 to 7.x: Fix test output with ipv6 addresses
  CHANGELOG.next.asciidoc
  libbeat/outputs/elasticsearch/client.go
Labels: backport, review

#14876 Add monitoring information about functions to Functionbeat
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/function/beater/functionbeat.go
  x-pack/functionbeat/function/core/coordinator.go
  x-pack/functionbeat/function/core/coordinator_test.go
  x-pack/functionbeat/function/provider/provider.go
  x-pack/functionbeat/function/provider/provider_test.go
  x-pack/functionbeat/function/provider/registry_test.go
  x-pack/functionbeat/function/telemetry/telemetry.go
  x-pack/functionbeat/provider/aws/aws/api_gateway_proxy.go
  x-pack/functionbeat/provider/aws/aws/cloudwatch_kinesis.go
  x-pack/functionbeat/provider/aws/aws/cloudwatch_logs.go
  x-pack/functionbeat/provider/aws/aws/kinesis.go
  x-pack/functionbeat/provider/aws/aws/sqs.go
  x-pack/functionbeat/provider/local/local/local.go
Labels: Functionbeat, Team:Beats, [zube]: In Review, needs_backport

#15415 Cherry-pick #15356 to 7.x: Add cost warning messages to azure get metric values calls
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/monitor_service.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, v7.6.0

#15410 [Agent] Fixed casing in spec and binary path resolution
  x-pack/agent/pkg/agent/program/supported.go
  x-pack/agent/pkg/core/plugin/app/descriptor.go
  x-pack/agent/spec/filebeat.yml
Labels: Project:fleet, agent, review

#15305 Fix ocasional panic in UTF16ToStringArray when processing unicode strings
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/pdh_query_windows.go
  metricbeat/module/windows/perfmon/pdh_query_windows_test.go
Labels: Team:Integrations, [zube]: In Review, needs_backport, v7.5.2, v7.6.0

#15366 Adding comment clarifying expectation of redis input's Run() method.
  filebeat/input/redis/input.go
Labels: Team:Beats, needs_backport, review, v7.6.0, v8.0.0

#15390 Keep only Filebeat and Metricbeat enabled
  x-pack/agent/pkg/agent/program/program_test.go
  x-pack/agent/pkg/agent/program/supported.go
  x-pack/agent/spec/auditbeat.yml.disabled
  x-pack/agent/spec/heartbeat.yml.disabled
  x-pack/agent/spec/journalbeat.yml.disabled
Labels: Project:fleet, [zube]: In Review, agent, review

#15418 New hashing algorithm for fingerprint processor
  CHANGELOG.next.asciidoc
  NOTICE.txt
  libbeat/processors/fingerprint/docs/fingerprint.asciidoc
  libbeat/processors/fingerprint/fingerprint_test.go
  libbeat/processors/fingerprint/hash.go
  vendor/github.com/OneOfOne/xxhash/LICENSE
  vendor/github.com/OneOfOne/xxhash/README.md
  vendor/github.com/OneOfOne/xxhash/go.mod
  vendor/github.com/OneOfOne/xxhash/xxhash.go
  vendor/github.com/OneOfOne/xxhash/xxhash_go17.go
  vendor/github.com/OneOfOne/xxhash/xxhash_safe.go
  vendor/github.com/OneOfOne/xxhash/xxhash_unsafe.go
  vendor/vendor.json
Labels: Team:Beats, [zube]: In Review, needs_backport, review, v7.6.0, v8.0.0

#15431 Move s3access fileset from beta to ga
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/module/aws/s3access/_meta/fields.yml
Labels: Filebeat, Team:Integrations, review, skip-test-plan

#15461 Cherry-pick #14876 to 7.x: Add monitoring information about functions to Functionbeat
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/function/beater/functionbeat.go
  x-pack/functionbeat/function/core/coordinator.go
  x-pack/functionbeat/function/core/coordinator_test.go
  x-pack/functionbeat/function/provider/provider.go
  x-pack/functionbeat/function/provider/provider_test.go
  x-pack/functionbeat/function/provider/registry_test.go
  x-pack/functionbeat/function/telemetry/telemetry.go
  x-pack/functionbeat/provider/aws/aws/api_gateway_proxy.go
  x-pack/functionbeat/provider/aws/aws/cloudwatch_kinesis.go
  x-pack/functionbeat/provider/aws/aws/cloudwatch_logs.go
  x-pack/functionbeat/provider/aws/aws/kinesis.go
  x-pack/functionbeat/provider/aws/aws/sqs.go
  x-pack/functionbeat/provider/local/local/local.go
Labels: Team:Beats, [zube]: In Review, backport

#15451 cherrypick_pr new flags: remote, zube-team
  dev-tools/cherrypick_pr
Labels: Team:Beats, [zube]: In Review

#15394 Use source blocks in asciidocs instead of backquotes
  filebeat/docs/inputs/input-kafka.asciidoc
  filebeat/docs/modules/azure.asciidoc
  metricbeat/docs/modules/system.asciidoc
  metricbeat/module/system/_meta/docs.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/monitor/_meta/docs.asciidoc
Labels: Team:Integrations, docs, needs_backport, review, v7.5.2, v7.6.0

#13773 x-pack: fix dropped errors
  CHANGELOG-developer.next.asciidoc
  x-pack/metricbeat/module/azure/compute_vm/compute_vm_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/compute_vm_scaleset_test.go
  x-pack/metricbeat/module/azure/monitor/monitor_test.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, module, review

#15421 Cherry-pick #15245 to 7.x: [Metricbeat] Update cloudwatch metricset mappings
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/aws/_meta/fields.yml
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-billing-overview.json
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-ebs-overview.json
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-elb-overview.json
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-overview.json
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-sns-overview.json
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-usage-overview.json
  x-pack/metricbeat/module/aws/billing/_meta/data.json
  x-pack/metricbeat/module/aws/cloudwatch/_meta/data.json
  x-pack/metricbeat/module/aws/cloudwatch/_meta/fields.yml
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/ebs/_meta/data.json
  x-pack/metricbeat/module/aws/elb/_meta/data.json
  x-pack/metricbeat/module/aws/elb/_meta/data_alb.json
  x-pack/metricbeat/module/aws/elb/_meta/data_nlb.json
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/mtest/integration.go
  x-pack/metricbeat/module/aws/sns/_meta/data.json
  x-pack/metricbeat/module/aws/usage/_meta/data.json
Labels: backport, review

#15351 Cherry-pick #14904 to 7.5: Netflow input: Improve session reset detection and allow disabling
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/netflow.asciidoc
  x-pack/filebeat/docs/inputs/input-netflow.asciidoc
  x-pack/filebeat/input/netflow/config.go
  x-pack/filebeat/input/netflow/decoder/v9/session.go
  x-pack/filebeat/input/netflow/decoder/v9/session_test.go
  x-pack/filebeat/input/netflow/decoder/v9/v9.go
  x-pack/filebeat/input/netflow/input.go
  x-pack/filebeat/module/netflow/_meta/docs.asciidoc
  x-pack/filebeat/module/netflow/log/config/netflow.yml
  x-pack/filebeat/module/netflow/log/manifest.yml
Labels: Team:SIEM, backport, review

#15370 [Filebeat] Add basic json support into s3 input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/s3/config.go
  x-pack/filebeat/input/s3/input.go
Labels: Filebeat, Team:Integrations, needs_backport, review, test-plan

#15466 Cherry-pick #14666 to 7.5: Restrict permissible regex for instance name in perfmon
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/pdh_query_windows.go
  metricbeat/module/windows/perfmon/pdh_query_windows_test.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, backport, v7.5.2

#15464 Cherry-pick #14666 to 7.x: Restrict permissible regex for instance name in perfmon
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/pdh_query_windows.go
  metricbeat/module/windows/perfmon/pdh_query_windows_test.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, backport, v7.6.0

#15476 Cherry-pick #15394 to 7.x: Use source blocks in asciidocs instead of backquotes
  filebeat/docs/inputs/input-kafka.asciidoc
  filebeat/docs/modules/azure.asciidoc
  metricbeat/docs/modules/system.asciidoc
  metricbeat/module/system/_meta/docs.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/monitor/_meta/docs.asciidoc
Labels: backport, review

#15473 Cherry-pick #15431 to 7.x: Move s3access fileset from beta to ga
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/module/aws/s3access/_meta/fields.yml
Labels: backport, review

#15429 Cherry-pick #15419 to 7.x: [Filebeat] Add missing googlecloud.yml.disabled file
  x-pack/filebeat/modules.d/googlecloud.yml.disabled
Labels: backport, review

#15174 [6.8][DOCS] Backport: Switch doc build to use direct_html flag (#15159)
  NOTICE.txt
  script/build_docs.sh
Labels: backport, docs, v6.8.0

#15426 [Filebeat] Move elb fileset from beta to ga
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/aws/elb/_meta/fields.yml
  x-pack/filebeat/module/aws/fields.go
Labels: Filebeat, needs_backport, review, skip-test-plan

#14844 Update to ECS 1.4.0
  CHANGELOG.next.asciidoc
  NOTICE.txt
  auditbeat/docs/fields.asciidoc
  auditbeat/include/fields.go
  filebeat/docs/fields.asciidoc
  filebeat/include/fields.go
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  journalbeat/docs/fields.asciidoc
  journalbeat/include/fields.go
  libbeat/_meta/fields.ecs.yml
  metricbeat/_meta/fields.common.yml
  metricbeat/docs/fields.asciidoc
  metricbeat/include/fields/fields.go
  packetbeat/docs/fields.asciidoc
  packetbeat/include/fields.go
  vendor/github.com/elastic/ecs/code/go/ecs/dns.go
  vendor/github.com/elastic/ecs/code/go/ecs/event.go
  vendor/github.com/elastic/ecs/code/go/ecs/file.go
  vendor/github.com/elastic/ecs/code/go/ecs/host.go
  vendor/github.com/elastic/ecs/code/go/ecs/package.go
  vendor/github.com/elastic/ecs/code/go/ecs/process.go
  vendor/github.com/elastic/ecs/code/go/ecs/registry.go
  vendor/github.com/elastic/ecs/code/go/ecs/related.go
  vendor/github.com/elastic/ecs/code/go/ecs/rule.go
  vendor/github.com/elastic/ecs/code/go/ecs/threat.go
  vendor/github.com/elastic/ecs/code/go/ecs/tls.go
  vendor/github.com/elastic/ecs/code/go/ecs/user_agent.go
  vendor/github.com/elastic/ecs/code/go/ecs/version.go
  vendor/github.com/elastic/ecs/code/go/ecs/vulnerability.go
  vendor/vendor.json
  winlogbeat/docs/fields.asciidoc
  winlogbeat/include/fields.go
  x-pack/functionbeat/docs/fields.asciidoc
  x-pack/functionbeat/include/fields.go
Labels: ecs, in progress

#15178 Change metricbeat image tags to use integrations-ci
  metricbeat/docker-compose.yml
  metricbeat/module/aerospike/docker-compose.yml
  metricbeat/module/apache/docker-compose.yml
  metricbeat/module/ceph/docker-compose.yml
  metricbeat/module/consul/docker-compose.yml
  metricbeat/module/couchbase/docker-compose.yml
  metricbeat/module/couchdb/docker-compose.yml
  metricbeat/module/dropwizard/docker-compose.yml
  metricbeat/module/envoyproxy/docker-compose.yml
  metricbeat/module/etcd/docker-compose.yml
  metricbeat/module/golang/docker-compose.yml
  metricbeat/module/haproxy/docker-compose.yml
  metricbeat/module/http/docker-compose.yml
  metricbeat/module/jolokia/docker-compose.yml
  metricbeat/module/kafka/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  metricbeat/module/memcached/docker-compose.yml
  metricbeat/module/mongodb/docker-compose.yml
  metricbeat/module/munin/docker-compose.yml
  metricbeat/module/mysql/docker-compose.yml
  metricbeat/module/nats/docker-compose.yml
  metricbeat/module/nginx/docker-compose.yml
  metricbeat/module/php_fpm/docker-compose.yml
  metricbeat/module/postgresql/docker-compose.yml
  metricbeat/module/prometheus/docker-compose.yml
  metricbeat/module/rabbitmq/docker-compose.yml
  metricbeat/module/redis/docker-compose.yml
  metricbeat/module/traefik/docker-compose.yml
  metricbeat/module/uwsgi/docker-compose.yml
  metricbeat/module/zookeeper/docker-compose.yml
  x-pack/metricbeat/docker-compose.yml
  x-pack/metricbeat/module/activemq/docker-compose.yml
  x-pack/metricbeat/module/cockroachdb/docker-compose.yml
  x-pack/metricbeat/module/coredns/docker-compose.yml
  x-pack/metricbeat/module/mssql/docker-compose.yml
  x-pack/metricbeat/module/stan/docker-compose.yml
Labels: Team:Integrations, [zube]: In Review, needs_backport, review, v7.6.0

#15383 Cherry-pick #15140 to 7.5: Fix mage package on generated beats
  .travis.yml
  generator/beat/{beat}/magefile.go
  generator/common/Makefile
  generator/metricbeat/{beat}/magefile.go
Labels: backport, review

#15479 Update Go to 1.13.6
  .go-version
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: Team:Beats, [zube]: In Review

#15482 Cherry-pick #15305 to 7.5: Fix ocasional panic in UTF16ToStringArray when processing unicode strings
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/pdh_query_windows.go
  metricbeat/module/windows/perfmon/pdh_query_windows_test.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, backport, v7.5.2

#15489 Cherry-pick #15178 to 7.x: Change metricbeat image tags to use integrations-ci
  metricbeat/docker-compose.yml
  metricbeat/module/aerospike/docker-compose.yml
  metricbeat/module/apache/docker-compose.yml
  metricbeat/module/ceph/docker-compose.yml
  metricbeat/module/consul/docker-compose.yml
  metricbeat/module/couchbase/docker-compose.yml
  metricbeat/module/couchdb/docker-compose.yml
  metricbeat/module/dropwizard/docker-compose.yml
  metricbeat/module/envoyproxy/docker-compose.yml
  metricbeat/module/etcd/docker-compose.yml
  metricbeat/module/golang/docker-compose.yml
  metricbeat/module/haproxy/docker-compose.yml
  metricbeat/module/http/docker-compose.yml
  metricbeat/module/jolokia/docker-compose.yml
  metricbeat/module/kafka/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  metricbeat/module/memcached/docker-compose.yml
  metricbeat/module/mongodb/docker-compose.yml
  metricbeat/module/munin/docker-compose.yml
  metricbeat/module/mysql/docker-compose.yml
  metricbeat/module/nats/docker-compose.yml
  metricbeat/module/nginx/docker-compose.yml
  metricbeat/module/php_fpm/docker-compose.yml
  metricbeat/module/postgresql/docker-compose.yml
  metricbeat/module/prometheus/docker-compose.yml
  metricbeat/module/rabbitmq/docker-compose.yml
  metricbeat/module/redis/docker-compose.yml
  metricbeat/module/traefik/docker-compose.yml
  metricbeat/module/uwsgi/docker-compose.yml
  metricbeat/module/zookeeper/docker-compose.yml
  x-pack/metricbeat/docker-compose.yml
  x-pack/metricbeat/module/activemq/docker-compose.yml
  x-pack/metricbeat/module/cockroachdb/docker-compose.yml
  x-pack/metricbeat/module/coredns/docker-compose.yml
  x-pack/metricbeat/module/mssql/docker-compose.yml
  x-pack/metricbeat/module/stan/docker-compose.yml
Labels: backport, review

#15453 Include log.source.address for unparseable syslog messages
  CHANGELOG.next.asciidoc
  filebeat/input/syslog/input.go
  filebeat/input/syslog/input_test.go
  filebeat/tests/system/test_syslog.py
Labels: Filebeat, Team:Beats, [zube]: In Review, enhancement, needs_backport, review, test-plan, v7.6.0

#15460 Cherry-pick #15305 to 7.x: Fix ocasional panic in UTF16ToStringArray when processing unicode strings
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/pdh_query_windows.go
  metricbeat/module/windows/perfmon/pdh_query_windows_test.go
Labels: Metricbeat, Team:Integrations, [zube]: In Review, backport, v7.6.0

#15408 [Agent] Ignore not supported applications on operator level
  x-pack/agent/dev-tools/cmd/buildspec/buildspec.go
  x-pack/agent/pkg/agent/operation/operator.go
  x-pack/agent/pkg/agent/operation/operator_test.go
  x-pack/agent/pkg/agent/program/supported.go
Labels: Project:fleet, agent, review

#15480 Integrate the azure-eventhub input with the filebeat azure module
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/azure/_meta/config.yml
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
  x-pack/filebeat/module/azure/activitylogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/activitylogs/config/kafka.yml
  x-pack/filebeat/module/azure/activitylogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/activitylogs/manifest.yml
  x-pack/filebeat/module/azure/auditlogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/auditlogs/config/kafka.yml
  x-pack/filebeat/module/azure/auditlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/auditlogs/manifest.yml
  x-pack/filebeat/module/azure/signinlogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/signinlogs/config/kafka.yml
  x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/signinlogs/manifest.yml
  x-pack/filebeat/modules.d/azure.yml.disabled
Labels: Metricbeat, Team:Integrations, [zube]: In Review, needs_backport

#15491 Cherry-pick #15479 to 7.x: Update Go to 1.13.6
  .go-version
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: backport, review

#15496 [Agent] Send hostname when enrolling
  x-pack/agent/pkg/agent/application/enroll_cmd.go
Labels: Project:fleet, agent

#15498 Cherry-pick #15480 to 7.x: Integrate the azure-eventhub input with the filebeat azure module
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/azure/_meta/config.yml
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
  x-pack/filebeat/module/azure/activitylogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/activitylogs/config/kafka.yml
  x-pack/filebeat/module/azure/activitylogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/activitylogs/manifest.yml
  x-pack/filebeat/module/azure/auditlogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/auditlogs/config/kafka.yml
  x-pack/filebeat/module/azure/auditlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/auditlogs/manifest.yml
  x-pack/filebeat/module/azure/signinlogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/signinlogs/config/kafka.yml
  x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/signinlogs/manifest.yml
  x-pack/filebeat/modules.d/azure.yml.disabled
Labels: Filebeat, Team:Integrations, [zube]: Inbox, backport, v7.6.0

#15485 [Metricbeat] Move elb metricset to ga
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/aws/elb.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/aws/elb/_meta/fields.yml
  x-pack/metricbeat/module/aws/fields.go
Labels: Metricbeat, Team:Integrations, review, skip-test-plan

#15413 [Agent] Batch ACKs together
  x-pack/agent/pkg/agent/application/action_dispatch.go
  x-pack/agent/pkg/agent/application/fleet_acker.go
  x-pack/agent/pkg/agent/application/fleet_acker_test.go
  x-pack/agent/pkg/agent/application/fleet_gateway.go
  x-pack/agent/pkg/agent/application/handler_action_policy_change_test.go
  x-pack/agent/pkg/agent/application/lazy_acker.go
  x-pack/agent/pkg/agent/application/lazy_acker_test.go
  x-pack/agent/pkg/agent/application/managed_mode.go
Labels: Project:fleet, agent, review

#15398 [Agent] Remove workaround outpout url returned by Fleet
  x-pack/agent/pkg/agent/program/supported.go
  x-pack/agent/spec/auditbeat.yml.disabled
  x-pack/agent/spec/filebeat.yml
  x-pack/agent/spec/heartbeat.yml.disabled
  x-pack/agent/spec/journalbeat.yml.disabled
  x-pack/agent/spec/metricbeat.yml
Labels: Project:fleet, agent

#15472 [Agent] Fleet auth round tripper nil ptr
  x-pack/agent/pkg/fleetapi/client_test.go
  x-pack/agent/pkg/fleetapi/round_trippers.go
Labels: Project:fleet, [zube]: In Review, agent, review

#15481 Scheduler close ordering
  x-pack/agent/pkg/agent/application/fleet_gateway.go
Labels: Project:fleet, [zube]: In Review, agent, review

#15477 Cherry-pick #15370 to 7.x: [Filebeat] Add basic json support into s3 input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/s3/config.go
  x-pack/filebeat/input/s3/input.go
Labels: backport, review

#15499 [Agent] Send meta with every checkin request
  x-pack/agent/pkg/agent/application/enroll_cmd.go
  x-pack/agent/pkg/agent/application/fleet_gateway.go
  x-pack/agent/pkg/agent/application/local_meta.go
  x-pack/agent/pkg/fleetapi/checkin_cmd.go
  x-pack/agent/pkg/fleetapi/checkin_cmd_test.go
Labels: Project:fleet, agent
