Repository elastic/beats, pull requests merged in 2020-07, with the labels that each got.

#19490 ci: disable upstream trigger on PRs for the packaging job
  .ci/packaging.groovy
Labels: Team:Automation, bug, ci

#19536 ci: enable packaging job
  .ci/jobs/packaging.yml
Labels: Team:Automation, ci

#19483 [Filebeat][httpjson] Add date_cursor to httpjson input
  CHANGELOG.next.asciidoc
  go.mod
  x-pack/filebeat/input/httpjson/config.go
  x-pack/filebeat/input/httpjson/config_test.go
  x-pack/filebeat/input/httpjson/httpjson_test.go
  x-pack/filebeat/input/httpjson/input.go
Labels: Filebeat, Team:SIEM, enhancement, review, v7.9.0

#19542 Cherry-pick #19535 to 7.x: Use Go install for getting goimports
  dev-tools/mage/fmt.go
Labels: backport, needs_team

#19463 Add support for Thread ID in Filebeat Kafka module
  CHANGELOG.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/kafka.asciidoc
  filebeat/module/kafka/_meta/docs.asciidoc
  filebeat/module/kafka/fields.go
  filebeat/module/kafka/log/_meta/fields.yml
  filebeat/module/kafka/log/ingest/pipeline.yml
  filebeat/module/kafka/log/test/state-change-2.2.2.log
  filebeat/module/kafka/log/test/state-change-2.2.2.log-expected.json
Labels: Team:Services, [zube]: In Review, needs_backport

#19518 Implement storage handling for cursor inputs
  filebeat/input/v2/input-cursor/publish.go
  filebeat/input/v2/input-cursor/store.go
  filebeat/input/v2/input-cursor/store_test.go
Labels: Filebeat, Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, needs_backport, review, v7.9.0

#19548 Cherry-pick #19463 to 7.x: Add support for Thread ID in Filebeat Kafka module
  CHANGELOG.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/kafka.asciidoc
  filebeat/module/kafka/_meta/docs.asciidoc
  filebeat/module/kafka/fields.go
  filebeat/module/kafka/log/_meta/fields.yml
  filebeat/module/kafka/log/ingest/pipeline.yml
  filebeat/module/kafka/log/test/state-change-2.2.2.log
  filebeat/module/kafka/log/test/state-change-2.2.2.log-expected.json
Labels: Team:Services, [zube]: In Review, backport

#19549 Cherry-pick #19463 to 7.8: Add support for Thread ID in Filebeat Kafka module
  CHANGELOG.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/kafka.asciidoc
  filebeat/module/kafka/_meta/docs.asciidoc
  filebeat/module/kafka/fields.go
  filebeat/module/kafka/log/_meta/fields.yml
  filebeat/module/kafka/log/ingest/pipeline.yml
  filebeat/module/kafka/log/test/state-change-2.2.2.log
  filebeat/module/kafka/log/test/state-change-2.2.2.log-expected.json
Labels: Team:Services, [zube]: In Review, backport

#19357 Change link in readme for new snapshots URL
  README.md
Labels: Team:Automation, [zube]: In Review, review

#19529 Add unit tests for cursor API
  filebeat/input/v2/input-cursor/cursor_test.go
Labels: Filebeat, Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, needs_backport, review, v7.9.0

#19556 change #19423 changelog from bug to add
  CHANGELOG.next.asciidoc
Labels: Team:Platforms, review

#19557 Remove outdated references to vendor folder
  Makefile
  dev-tools/mage/dashboard.go
Labels: Team:Automation, Team:Services, [zube]: In Review, needs_backport

#19519 Cherry-pick #19423 to 7.x: [MetricBeat] add param `aws_partition` to support aws-cn, aws-us-gov regions
  CHANGELOG.next.asciidoc
  go.mod
  x-pack/libbeat/common/aws/credentials.go
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
  x-pack/metricbeat/module/aws/aws.go
Labels: Team:Platforms, [zube]: In Review, backport

#19558 Update Jenkinsfile to check go.mod instead of vendor/
  Jenkinsfile
Labels: Team:Automation, Team:Integrations, bug

#19559 ci: trigger packages builds only manually or with a comment
  .ci/packaging.groovy
Labels: Team:Automation, ci, enhancement

#19546 Cherry-pick #19490 #19559 to 7.x: ci: disable upstream trigger on PRs for the packaging job
  .ci/packaging.groovy
Labels: Team:Automation, ci

#19545 Cherry-pick #19490 #19559 to 7.7: ci: disable upstream trigger on PRs for the packaging job
  .ci/packaging.groovy
Labels: Team:Automation, ci

#19543 Cherry-pick #19490 #19559 to 7.9: ci: disable upstream trigger on PRs for the packaging job
  .ci/packaging.groovy
Labels: Team:Automation, ci

#19544 Cherry-pick #19490 #19559 to 7.8: ci: disable upstream trigger on PRs for the packaging job
  .ci/packaging.groovy
Labels: Team:Automation, ci

#19565 Cherry-pick #19558 to 7.9: Update Jenkinsfile to check go.mod instead of vendor/
  Jenkinsfile
Labels: Team:Automation, Team:Integrations, [zube]: In Review, backport

#19563 Cherry-pick #19527 to 7.8: Update Beats to the current Sarama fork
  NOTICE.txt
  go.mod
  go.sum
  vendor/github.com/Shopify/sarama/README.md
  vendor/github.com/Shopify/sarama/async_producer.go
  vendor/github.com/Shopify/sarama/broker.go
  vendor/modules.txt
Labels: Team:Integrations, [zube]: In Review, backport

#19025 Add awscloudwatch filebeat input
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/docs/inputs/input-awscloudwatch.asciidoc
  x-pack/filebeat/include/list.go
  x-pack/filebeat/input/awscloudwatch/_meta/fields.yml
  x-pack/filebeat/input/awscloudwatch/config.go
  x-pack/filebeat/input/awscloudwatch/fields.go
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/filebeat/input/awscloudwatch/input_test.go
Labels: Team:Platforms, [zube]: In Review, enhancement, needs_backport, review, test-plan

#19530 Add publisher implementation for stateful inputs
  filebeat/input/v2/input-cursor/publish.go
  filebeat/input/v2/input-cursor/publish_test.go
Labels: Filebeat, Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, needs_backport, review, v7.9.0

#19568 [Filebeat] Add default_fields: false to fields.yml in aws module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/aws/elb/_meta/fields.yml
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/module/aws/s3access/_meta/fields.yml
  x-pack/filebeat/module/aws/vpcflow/_meta/fields.yml
Labels: Team:Platforms, [zube]: In Review, needs_backport, review

#19433 [MetricBeat] set tags correctly if the dimension value is ARN
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
Labels: Team:Platforms, [zube]: In Review, needs_backport, review

#19358 Cherry-pick #19244 to 7.x: Agent longpoll
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go
  x-pack/elastic-agent/pkg/kibana/client.go
Labels: Ingest Management:beta1, Team:Ingest Management, backport, enhancement, review

#19237 Cherry-pick #17964 to 7.x: [Filebeat] Fix Cisco ASA 3020** and 106023 messages
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/test/asa-fix.log
  x-pack/filebeat/module/cisco/asa/test/asa-fix.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/asa-fix.log
  x-pack/filebeat/module/cisco/ftd/test/asa-fix.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: Team:SIEM, Team:Services, [zube]: In Review, backport

#19441 Cherry-pick #19430 to 7.x: updated cisco module to use new nullcheck in set processors
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: Team:SIEM, [zube]: In Review, backport

#19442 Cherry-pick #19429 to 7.x: updated iptables module to use new nullcheck in set processors
  x-pack/filebeat/module/iptables/log/ingest/pipeline.yml
Labels: Team:SIEM, [zube]: In Review, backport

#19444 Cherry-pick #19421 to 7.x: updated fortinet module to use new nullcheck in set processors
  x-pack/filebeat/module/fortinet/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/fortinet/firewall/ingest/traffic.yml
Labels: Team:SIEM, [zube]: In Review, backport

#19445 Cherry-pick #19420 to 7.x: updated suricata module to use new nullcheck in set processors
  x-pack/filebeat/module/suricata/eve/ingest/pipeline.yml
Labels: Team:SIEM, [zube]: In Review, backport

#19446 Cherry-pick #19419 to 7.x: updated activemq module to use new nullcheck in set processors
  x-pack/filebeat/module/activemq/audit/ingest/pipeline.yml
Labels: Team:SIEM, [zube]: In Review, backport

#19449 Cherry-pick #19412 to 7.x: updated auditd module to use new nullcheck in set processors
  filebeat/module/auditd/log/ingest/pipeline.yml
Labels: Team:SIEM, [zube]: Inbox, backport

#19447 Cherry-pick #19418 to 7.x: updated checkpoint module to use new nullcheck in set processors
  x-pack/filebeat/module/checkpoint/firewall/ingest/pipeline.yml
Labels: Team:SIEM, [zube]: In Review, backport

#19443 Cherry-pick #19425 to 7.x: updated panw module to use new nullcheck in set processors
  x-pack/filebeat/module/panw/panos/ingest/pipeline.yml
Labels: Team:SIEM, [zube]: In Review, backport

#19588 ci: some jjbb improvements
  .ci/jobs/apm-beats-update.yml
  .ci/jobs/beats.yml
  .ci/jobs/build-it-docker-images.yml
  .ci/jobs/defaults.yml
  .ci/jobs/packaging.yml
Labels: Team:Automation, ci, enhancement

#19589 ci: enable upstream triggering on the packaging job
  .ci/packaging.groovy
Labels: Team:Automation, ci, enhancement

#19590 ci: apm-server-update trigered only on upstream, comments, and manual triggered
  .ci/apm-beats-update.groovy
Labels: Team:Automation, ci, enhancement

#19561 Add description to HAProxy fields in Metricbeat
  metricbeat/docs/fields.asciidoc
  metricbeat/module/haproxy/fields.go
  metricbeat/module/haproxy/info/_meta/fields.yml
Labels: Team:Integrations, [zube]: In Review

#19592 Cherry-pick #19589 to 7.9: ci: enable upstream triggering on the packaging job
  .ci/packaging.groovy
Labels: Team:Automation, backport

#19593 Cherry-pick #19589 to 7.8: ci: enable upstream triggering on the packaging job
  .ci/packaging.groovy
Labels: Team:Automation, backport

#19594 Cherry-pick #19589 to 7.7: ci: enable upstream triggering on the packaging job
  .ci/packaging.groovy
Labels: Team:Automation, backport

#19595 Cherry-pick #19589 to 7.x: ci: enable upstream triggering on the packaging job
  .ci/packaging.groovy
Labels: Team:Automation, backport

#19596 Cherry-pick #19590 to 7.9: ci: apm-server-update trigered only on upstream, comments, and manual triggered
  .ci/apm-beats-update.groovy
Labels: Team:Automation, backport

#19555 Cherry-pick #18873 to 7.x: Allow the Docker image to be run with a random user id (#12905)
  CHANGELOG.next.asciidoc
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/auditbeat/auditbeat-daemonset.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/filebeat/filebeat-daemonset.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset.yaml
  deploy/kubernetes/metricbeat/metricbeat-deployment.yaml
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Platforms, [zube]: In Review, backport

#19533 Implement memlog store operations
  libbeat/statestore/backend/memlog/memlog.go
  libbeat/statestore/backend/memlog/memlog_test.go
  libbeat/statestore/backend/memlog/store.go
  libbeat/statestore/backend/memlog/testdata/1/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/commit_wrong_id/1.json
  libbeat/statestore/backend/memlog/testdata/1/commit_wrong_id/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/commit_wrong_id/expected.json
  libbeat/statestore/backend/memlog/testdata/1/commit_wrong_id/log.json
  libbeat/statestore/backend/memlog/testdata/1/commit_wrong_id/meta.json
  libbeat/statestore/backend/memlog/testdata/1/data_and_log/1.json
  libbeat/statestore/backend/memlog/testdata/1/data_and_log/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/data_and_log/expected.json
  libbeat/statestore/backend/memlog/testdata/1/data_and_log/log.json
  libbeat/statestore/backend/memlog/testdata/1/data_and_log/meta.json
  libbeat/statestore/backend/memlog/testdata/1/datafile_only/1.json
  libbeat/statestore/backend/memlog/testdata/1/datafile_only/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/datafile_only/expected.json
  libbeat/statestore/backend/memlog/testdata/1/datafile_only/meta.json
  libbeat/statestore/backend/memlog/testdata/1/incomplete_op/1.json
  libbeat/statestore/backend/memlog/testdata/1/incomplete_op/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/incomplete_op/expected.json
  libbeat/statestore/backend/memlog/testdata/1/incomplete_op/log.json
  libbeat/statestore/backend/memlog/testdata/1/incomplete_op/meta.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_incomplete/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/logfile_incomplete/expected.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_incomplete/log.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_incomplete/meta.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_only/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/logfile_only/expected.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_only/log.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_only/meta.json
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/1.json
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/2.json
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/3.json
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/expected.json
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/meta.json
  libbeat/statestore/backend/memlog/testdata/1/old_entries_in_log/5.json
  libbeat/statestore/backend/memlog/testdata/1/old_entries_in_log/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/old_entries_in_log/expected.json
  libbeat/statestore/backend/memlog/testdata/1/old_entries_in_log/log.json
  libbeat/statestore/backend/memlog/testdata/1/old_entries_in_log/meta.json
  libbeat/statestore/backend/memlog/util.go
Labels: Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, libbeat, needs_backport, review, v7.9.0

#19582 Cherry-pick #19433 to 7.x: [MetricBeat] set tags correctly if the dimension value is ARN
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#19345 Accept prefix as metric_types for stackdriver metricset in GCP
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/googlecloud/stackdriver/_meta/docs.asciidoc
  x-pack/metricbeat/module/googlecloud/stackdriver/metrics_requester.go
  x-pack/metricbeat/module/googlecloud/stackdriver/metricset.go
Labels: Team:Platforms, [zube]: In Review, enhancement, needs_backport, review, test-plan

#19583 Cherry-pick #19433 to 7.8: [MetricBeat] set tags correctly if the dimension value is ARN
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#19586 [Ingest Manager] Make Agent beta and Constraints experimental
  x-pack/elastic-agent/docs/elastic-agent_configuration_example.yml
  x-pack/elastic-agent/pkg/agent/application/filters/constraints_filter.go
  x-pack/elastic-agent/pkg/agent/warn/warn.go
Labels: Ingest Management:beta1, Team:Ingest Management, needs_backport, review

#19570 Cherry-pick #19025 to 7.x: Add awscloudwatch filebeat input
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/docs/inputs/input-awscloudwatch.asciidoc
  x-pack/filebeat/include/list.go
  x-pack/filebeat/input/awscloudwatch/_meta/fields.yml
  x-pack/filebeat/input/awscloudwatch/config.go
  x-pack/filebeat/input/awscloudwatch/fields.go
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/filebeat/input/awscloudwatch/input_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#19494 Fix tls mapping in suricata module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/suricata/eve/_meta/fields.yml
  x-pack/filebeat/module/suricata/eve/config/eve.yml
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
  x-pack/filebeat/module/suricata/fields.go
Labels: Filebeat, Team:SIEM, bug, needs_backport

#19571 Cursor input and manager implementation
  filebeat/input/v2/input-cursor/input.go
  filebeat/input/v2/input-cursor/manager.go
Labels: Filebeat, Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, needs_backport, review, v7.9.0

#19516 Prepare input/file for changes in the registrar
  filebeat/input/file/state.go
  filebeat/input/file/states.go
Labels: Filebeat, Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, needs_backport, review, v7.9.0

#19609 Cherry-pick #19494 to 7.x: Fix tls mapping in suricata module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/suricata/eve/_meta/fields.yml
  x-pack/filebeat/module/suricata/eve/config/eve.yml
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
  x-pack/filebeat/module/suricata/fields.go
Labels: Team:SIEM, [zube]: In Review, backport

#19317 Fix ordering and duplicate configs on autodiscover
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  metricbeat/autodiscover/builder/hints/metrics.go
  metricbeat/autodiscover/builder/hints/metrics_test.go
Labels: Team:Platforms, [zube]: In Review, needs_backport, v7.9.0

#19610 Update Jenkinsfile to not inspect removed vendor
  Jenkinsfile
Labels: Team:Automation, ci, review

#19566 Cherry-pick #19558 to 7.x: Update Jenkinsfile to check go.mod instead of vendor/
  Jenkinsfile
Labels: Team:Automation, Team:Integrations, [zube]: In Review, backport

#19606 Cherry-pick #19345 to 7.x: Accept prefix as metric_types for stackdriver metricset in GCP
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/googlecloud/stackdriver/_meta/docs.asciidoc
  x-pack/metricbeat/module/googlecloud/stackdriver/metrics_requester.go
  x-pack/metricbeat/module/googlecloud/stackdriver/metricset.go
Labels: Team:Platforms, [zube]: In Review, backport

#19572 Cherry-pick #19568 to 7.x: [Filebeat] Add default_fields: false to fields.yml in aws module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/aws/elb/_meta/fields.yml
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/module/aws/s3access/_meta/fields.yml
  x-pack/filebeat/module/aws/vpcflow/_meta/fields.yml
Labels: Team:Platforms, [zube]: In Review, backport

#19573 Input v2 cursor testing
  filebeat/input/v2/input-cursor/manager_test.go
Labels: Filebeat, Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, blocked, needs_backport, review, v7.9.0

#19625 ci: use fixed type of agent
  .ci/build-docker-images.groovy
  .ci/jobs/build-it-docker-images.yml
Labels: Team:Automation, bug, ci

#19621 Cherry-pick to 7.x: Update Jenkinsfile to not inspect removed vendor (#19610)
  Jenkinsfile
Labels: Team:Automation, backport, bug, ci

#19181 Cache error responses for cloudfoundry apps metadata
  CHANGELOG.next.asciidoc
  x-pack/libbeat/common/cloudfoundry/cache.go
  x-pack/libbeat/common/cloudfoundry/cache_integration_test.go
  x-pack/libbeat/common/cloudfoundry/cache_test.go
  x-pack/libbeat/common/cloudfoundry/config.go
  x-pack/libbeat/common/cloudfoundry/hub.go
  x-pack/libbeat/processors/add_cloudfoundry_metadata/add_cloudfoundry_metadata.go
  x-pack/libbeat/processors/add_cloudfoundry_metadata/add_cloudfoundry_metadata_test.go
  x-pack/libbeat/processors/add_cloudfoundry_metadata/docs/add_cloudfoundry_metadata.asciidoc
Labels: Team:Platforms, [zube]: In Review, needs_backport, review, v7.9.0

#19617 [ci] fix env variable name for xpack filebeats
  Jenkinsfile
Labels: Team:Automation, automation, bug

#19434 Use MODULE in metricbeat python system tests
  dev-tools/mage/pytest.go
  docs/devguide/metricset-details.asciidoc
  metricbeat/magefile.go
  x-pack/metricbeat/magefile.go
Labels: :Testing, Team:Integrations, [zube]: In Review, needs_backport, review, v7.9.0

#19647 Fix filebeat unit test
  filebeat/input/v2/input-cursor/manager_test.go
Labels: Filebeat, Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, needs_backport, review, v7.9.0

#19515 Export Run from common listener inputsource
  filebeat/inputsource/common/listener.go
Labels: Filebeat, Team:Services, [zube]: In Review, needs_backport, review, v7.9.0

#19650 Pin version of pip and setuptools in Dockerfiles
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: :Testing, Team:Automation, Team:Integrations, bug

#19619 Init journald input
  dev-tools/mage/pkgdeps.go
  filebeat/Dockerfile
  filebeat/input/journald/config.go
  filebeat/input/journald/conv.go
  filebeat/input/journald/input.go
  filebeat/magefile.go
  journalbeat/magefile.go
Labels: Filebeat, Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, needs_backport, review, v7.9.0

#19584 tlscommon: require cert in ServerConfig.Validate
  CHANGELOG.next.asciidoc
  libbeat/common/transport/tlscommon/server_config.go
  libbeat/common/transport/tlscommon/tls.go
  libbeat/common/transport/tlscommon/tls_test.go
  libbeat/common/transport/tlscommon/types.go
Labels: Team:Services, [zube]: In Review, enhancement, needs_backport

#19608 Cherry-pick #19494 to 7.8: Fix tls mapping in suricata module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/suricata/eve/_meta/fields.yml
  x-pack/filebeat/module/suricata/eve/config/eve.yml
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
  x-pack/filebeat/module/suricata/fields.go
Labels: Team:SIEM, [zube]: In Review, backport

#19607 Cherry-pick #19494 to 7.7: Fix tls mapping in suricata module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/suricata/eve/_meta/fields.yml
  x-pack/filebeat/module/suricata/eve/config/eve.yml
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
  x-pack/filebeat/module/suricata/fields.go
Labels: Team:SIEM, [zube]: In Review, backport

#19640 Cherry-pick #19617 to 7.8: [ci] fix env variable name for xpack filebeats
  Jenkinsfile
Labels: Team:Automation, [zube]: In Review, automation, backport

#19601 Add missing azure metricsets in azure doc
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/azure.asciidoc
  x-pack/metricbeat/module/azure/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/compute_vm/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/compute_vm_scaleset/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_instance/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_registry/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_service/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/database_account/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/storage/_meta/docs.asciidoc
Labels: Team:Integrations, [zube]: In Review

#19651 Cherry-pick #19650 to 7.x: Pin version of pip and setuptools in Dockerfiles
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: Team:Automation, Team:Integrations, [zube]: In Review, backport

#19652 Cherry-pick #19650 to 7.8: Pin version of pip and setuptools in Dockerfiles
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: Team:Automation, Team:Integrations, [zube]: In Review, backport

#19643 Cherry-pick #19434 to 7.x: Use MODULE in metricbeat python system tests
  dev-tools/mage/pytest.go
  docs/devguide/metricset-details.asciidoc
  metricbeat/magefile.go
  x-pack/metricbeat/magefile.go
Labels: Team:Integrations, [zube]: In Review, backport

#19664 Cherry-pick #19601 to 7.8: Add missing azure metricsets in azure doc
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/azure.asciidoc
  x-pack/metricbeat/module/azure/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/compute_vm/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/compute_vm_scaleset/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_instance/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_registry/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_service/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/database_account/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/storage/_meta/docs.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#19539 Fix configuration values in the perfmon metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/windows.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/windows/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Integrations, [zube]: In Review, needs_backport

#19638 Cherry-pick #19181 to 7.x: Cache error responses for cloudfoundry apps metadata
  CHANGELOG.next.asciidoc
  x-pack/libbeat/common/cloudfoundry/cache.go
  x-pack/libbeat/common/cloudfoundry/cache_integration_test.go
  x-pack/libbeat/common/cloudfoundry/cache_test.go
  x-pack/libbeat/common/cloudfoundry/config.go
  x-pack/libbeat/common/cloudfoundry/hub.go
  x-pack/libbeat/processors/add_cloudfoundry_metadata/add_cloudfoundry_metadata.go
  x-pack/libbeat/processors/add_cloudfoundry_metadata/add_cloudfoundry_metadata_test.go
  x-pack/libbeat/processors/add_cloudfoundry_metadata/docs/add_cloudfoundry_metadata.asciidoc
Labels: Team:Platforms, [zube]: In Review, backport

#19614 Cherry-pick #19317 to 7.x: Fix ordering and duplicate configs on autodiscover
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  metricbeat/autodiscover/builder/hints/metrics.go
  metricbeat/autodiscover/builder/hints/metrics_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#19658 fix journalbeat depending on filebeat v2
  journalbeat/pkg/journalread/reader.go
Labels: Journalbeat, Team:Services, [zube]: In Review, needs_backport, review

#19653 Cherry-pick #18738 to 7.8: Improve thread safety of fingerprint processor
  CHANGELOG.next.asciidoc
  libbeat/processors/fingerprint/fingerprint.go
  libbeat/processors/fingerprint/fingerprint_test.go
Labels: Team:Services, [zube]: In Review, backport

#19325 Updated wording to avoid use of racially-charged language
  winlogbeat/docs/winlogbeat-options.asciidoc
Labels: Team:SIEM, Winlogbeat, docs, needs_backport

#19639 Cherry-pick #19617 to 7.x: [ci] fix env variable name for xpack filebeats
  Jenkinsfile
Labels: Team:Automation, [zube]: In Review, automation, backport

#19602 ci: add backport tool configuration
  .backportrc.json
Labels: Team:Automation, ci, enhancement

#19598 Cherry-pick #19590 to 7.7: ci: apm-server-update trigered only on upstream, comments, and manual triggered
  .ci/apm-beats-update.groovy
Labels: Team:Automation, backport

#19599 Cherry-pick #19590 to 7.x: ci: apm-server-update trigered only on upstream, comments, and manual triggered
  .ci/apm-beats-update.groovy
Labels: Team:Automation, backport

#19671 ci: do not delete mage installation
  .ci/packaging.groovy
Labels: Team:Automation, bug, ci

#19604 [Filebeat] [tests] Keep host.name in forwarded events
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/module/cisco/ftd/test/firepower-management.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/security-connection.log-expected.json
  x-pack/filebeat/module/crowdstrike/falcon/test/falcon-audit-events.log-expected.json
  x-pack/filebeat/module/crowdstrike/falcon/test/falcon-events.log-expected.json
  x-pack/filebeat/module/o365/audit/test/01-exchange-admin.log-expected.json
  x-pack/filebeat/module/o365/audit/test/02-exchange-item.log-expected.json
  x-pack/filebeat/module/o365/audit/test/04-sharepoint.log-expected.json
  x-pack/filebeat/module/o365/audit/test/06-sharepointfileop.log-expected.json
  x-pack/filebeat/module/o365/audit/test/08-azuread.log-expected.json
  x-pack/filebeat/module/o365/audit/test/11-dlp-sharepoint.log-expected.json
  x-pack/filebeat/module/o365/audit/test/13-dlp-exchange.log-expected.json
  x-pack/filebeat/module/o365/audit/test/14-sp-sharing-op.log-expected.json
  x-pack/filebeat/module/o365/audit/test/15-azuread-sts-logon.log-expected.json
  x-pack/filebeat/module/o365/audit/test/25-ms-teams.log-expected.json
  x-pack/filebeat/module/o365/audit/test/40-sec-comp-alerts.log-expected.json
Labels: :Testing, Filebeat, Team:SIEM, needs_backport, review

#19673 Cherry-pick to 7.7: ci: do not delete mage installation (#19671)
  .ci/packaging.groovy
Labels: Team:Automation, backport, bug, ci

#19672 Cherry-pick to 7.8: ci: do not delete mage installation (#19671)
  .ci/packaging.groovy
Labels: Team:Automation, backport, bug, ci

#19674 Cherry-pick to 7.x: ci: do not delete mage installation (#19671)
  .ci/packaging.groovy
Labels: Team:Automation, backport, bug, ci

#19667 Close changelog for 6.8.11
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
Labels: Team:Automation

#18703 Get stats for all indices, including hidden indices
  CHANGELOG.next.asciidoc
  metricbeat/docker-compose.yml
  metricbeat/module/elasticsearch/elasticsearch_integration_test.go
  metricbeat/module/elasticsearch/index/data_xpack.go
  metricbeat/module/elasticsearch/index/index.go
  metricbeat/module/logstash/docker-compose.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Stack monitoring, Team:Services, [zube]: In Review, in progress, review

#19632 Composable ACKer
  CHANGELOG-developer.next.asciidoc
  filebeat/beater/acker.go
  filebeat/beater/acker_test.go
  filebeat/beater/filebeat.go
  filebeat/input/kafka/input.go
  filebeat/input/v2/input-cursor/input.go
  filebeat/input/v2/input-cursor/manager_test.go
  journalbeat/beater/journalbeat.go
  journalbeat/input/input.go
  libbeat/beat/pipeline.go
  libbeat/common/acker/acker.go
  libbeat/common/acker/acker_test.go
  libbeat/publisher/pipeline/acker.go
  libbeat/publisher/pipeline/acker_test.go
  libbeat/publisher/pipeline/client.go
  libbeat/publisher/pipeline/client_ack.go
  libbeat/publisher/pipeline/config.go
  libbeat/publisher/pipeline/consumer.go
  libbeat/publisher/pipeline/nilpipeline.go
  libbeat/publisher/pipeline/pipeline.go
  libbeat/publisher/pipeline/pipeline_ack.go
  libbeat/publisher/pipeline/stress/gen.go
  libbeat/publisher/pipetool/pipetool.go
  libbeat/publisher/testing/testing.go
  metricbeat/cmd/test/modules.go
  winlogbeat/beater/eventlogger.go
  winlogbeat/beater/winlogbeat.go
  x-pack/dockerlogbeat/pipelinemanager/clientLogReader.go
  x-pack/filebeat/input/googlepubsub/input.go
  x-pack/filebeat/input/googlepubsub/pubsub_test.go
  x-pack/filebeat/input/o365audit/input.go
  x-pack/filebeat/input/s3/input.go
  x-pack/functionbeat/function/core/sync_client.go
  x-pack/functionbeat/function/core/sync_client_test.go
Labels: Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, needs_backport, release-note:dev_docs, review, v7.9.0

#19567 [Elastic Agent] Properly stop subprocess when receiving SIGTERM
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/agent/application/router.go
  x-pack/elastic-agent/pkg/agent/application/router_test.go
  x-pack/elastic-agent/pkg/agent/application/stream.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring_test.go
  x-pack/elastic-agent/pkg/agent/operation/operation.go
  x-pack/elastic-agent/pkg/agent/operation/operator.go
  x-pack/elastic-agent/pkg/core/plugin/process/app.go
  x-pack/elastic-agent/pkg/core/plugin/service/app.go
  x-pack/elastic-agent/pkg/core/process/cmd_darwin.go
  x-pack/elastic-agent/pkg/core/process/cmd_linux.go
Labels: Team:Ingest Management, bug

#19680 Disable journald input build from filebeat
  filebeat/input/journald/config.go
  filebeat/input/journald/conv.go
  filebeat/input/journald/input.go
  filebeat/magefile.go
Labels: Filebeat, Team:Services, [zube]: In Review, review

#19464 Dissect: Support trimming captured values and other configuration options
  CHANGELOG.next.asciidoc
  libbeat/processors/dissect/config.go
  libbeat/processors/dissect/config_test.go
  libbeat/processors/dissect/dissect.go
  libbeat/processors/dissect/docs/dissect.asciidoc
  libbeat/processors/dissect/processor.go
  libbeat/processors/dissect/processor_test.go
  libbeat/processors/dissect/trim.go
  libbeat/processors/dissect/trim_test.go
Labels: Team:SIEM, enhancement, needs_backport, review

#19267 Cherry-pick #19149 to 7.8: [Filebeat] Fix Cisco ASA dissect pattern for 313008 & 313009
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/test/asa-fix.log
  x-pack/filebeat/module/cisco/asa/test/asa-fix.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: Team:SIEM, backport, review

#19657 Cherry-pick #19516 to 7.x: Prepare input/file for changes in the registrar
  filebeat/input/file/state.go
  filebeat/input/file/states.go
Labels: Team:Services, [zube]: In Review, backport

#19633 Update filebeat registrar to use statestore
  filebeat/beater/filebeat.go
  filebeat/beater/store.go
  filebeat/config/config.go
  filebeat/registrar/migrate.go
  filebeat/registrar/registrar.go
  filebeat/registrar/registrar_test.go
  filebeat/tests/system/filebeat.py
  filebeat/tests/system/test_harvester.py
  filebeat/tests/system/test_registrar.py
  filebeat/tests/system/test_registrar_upgrade.py
  libbeat/common/file/file_other.go
  libbeat/common/file/file_windows.go
  libbeat/statestore/backend/memlog/util_darwin.go
Labels: Filebeat, Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, needs_backport, review, v7.9.0

#19676 Cherry-pick #19557 to 7.x: Remove outdated references to vendor folder
  Makefile
  dev-tools/mage/dashboard.go
Labels: Team:Services, [zube]: In Review, backport

#19562 Use a cache instead of sync.Pool in script processor
  CHANGELOG.next.asciidoc
  libbeat/processors/script/docs/script.asciidoc
  libbeat/processors/script/javascript/config.go
  libbeat/processors/script/javascript/session.go
Labels: Team:SIEM, discuss, enhancement, review

#19398 Add support for named ports in autodiscover (hints & templates)
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/autodiscover/template/config_test.go
  libbeat/common/kubernetes/k8skeystore/kubernetes_keystore.go
  metricbeat/autodiscover/builder/hints/metrics.go
  metricbeat/autodiscover/builder/hints/metrics_test.go
  metricbeat/docs/autodiscover-hints.asciidoc
  metricbeat/docs/autodiscover-kubernetes-config.asciidoc
Labels: Team:Platforms, [zube]: In Review, autodiscovery, enhancement, needs_backport, test-plan, v7.9.0

#19681 ci: remove PRs refspec from the ITs docker images job
  .ci/jobs/build-it-docker-images.yml
Labels: Team:Automation, automation, bug, ci

#19597 Cherry-pick #19590 to 7.8: ci: apm-server-update trigered only on upstream, comments, and manual triggered
  .ci/apm-beats-update.groovy
Labels: Team:Automation, backport

#19666 Cherry-pick #19539 to 7.8: Fix configuration values in the perfmon metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/windows.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/windows/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Integrations, [zube]: In Review, backport

#19505 Create fsnotify watcher only when starting file_integrity module
  CHANGELOG.next.asciidoc
  auditbeat/module/file_integrity/eventreader_fsnotify.go
Labels: Team:SIEM, enhancement

#19328 Add clusterRole note for apiserver
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-deployment-configmap.yaml
  deploy/kubernetes/metricbeat/metricbeat-role.yaml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/module/kubernetes/_meta/docs.asciidoc
Labels: Team:Platforms, [zube]: In Review, docs, enhancement, needs_backport, v7.8, v7.9.0

#19507 [Ingest Manager] Agent unenroll
  go.sum
  x-pack/elastic-agent/pkg/agent/application/action_store.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_unenroll.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/agent/application/router.go
  x-pack/elastic-agent/pkg/agent/application/router_test.go
  x-pack/elastic-agent/pkg/agent/application/stream.go
  x-pack/elastic-agent/pkg/agent/configrequest/config_request.go
  x-pack/elastic-agent/pkg/agent/configrequest/config_request_test.go
  x-pack/elastic-agent/pkg/agent/configrequest/request.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring_test.go
  x-pack/elastic-agent/pkg/agent/operation/operator.go
  x-pack/elastic-agent/pkg/agent/stateresolver/resolve_test.go
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
  x-pack/elastic-agent/pkg/core/monitoring/monitor.go
  x-pack/elastic-agent/pkg/core/monitoring/noop/noop_monitor.go
  x-pack/elastic-agent/pkg/fleetapi/action.go
Labels: Ingest Management:beta1, Team:Ingest Management, enhancement, needs_backport

#19683 Cherry-pick #19567 to 7.x: [Elastic Agent] Properly stop subprocess when receiving SIGTERM
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/agent/application/router.go
  x-pack/elastic-agent/pkg/agent/application/router_test.go
  x-pack/elastic-agent/pkg/agent/application/stream.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring_test.go
  x-pack/elastic-agent/pkg/agent/operation/operation.go
  x-pack/elastic-agent/pkg/agent/operation/operator.go
  x-pack/elastic-agent/pkg/core/plugin/process/app.go
  x-pack/elastic-agent/pkg/core/plugin/service/app.go
  x-pack/elastic-agent/pkg/core/process/cmd_darwin.go
  x-pack/elastic-agent/pkg/core/process/cmd_linux.go
Labels: Team:Ingest Management

#19692 Cherry-pick #19584 to 7.x: tlscommon: require cert in ServerConfig.Validate
  CHANGELOG.next.asciidoc
  libbeat/common/transport/tlscommon/server_config.go
  libbeat/common/transport/tlscommon/tls.go
  libbeat/common/transport/tlscommon/tls_test.go
  libbeat/common/transport/tlscommon/types.go
  libbeat/outputs/tls.go
Labels: Team:Services, [zube]: In Review, backport

#19694 Cherry-pick #19398 to 7.x: Add support for named ports in autodiscover (hints & templates)
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/autodiscover/template/config_test.go
  libbeat/common/kubernetes/k8skeystore/kubernetes_keystore.go
  metricbeat/autodiscover/builder/hints/metrics.go
  metricbeat/autodiscover/builder/hints/metrics_test.go
  metricbeat/docs/autodiscover-hints.asciidoc
  metricbeat/docs/autodiscover-kubernetes-config.asciidoc
Labels: Team:Platforms, [zube]: In Review, backport

#19422 Update monitoring-internal-collection.asciidoc
  libbeat/docs/monitoring/monitoring-internal-collection.asciidoc
Labels: Team:Services, [zube]: In Review, docs, needs_backport, v7.8.2, v7.9.0, v8.0.0

#19695 Cherry-pick #19328 to 7.x: Add clusterRole note for apiserver
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-deployment-configmap.yaml
  deploy/kubernetes/metricbeat/metricbeat-role.yaml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/module/kubernetes/_meta/docs.asciidoc
Labels: Team:Platforms, [zube]: In Review, backport

#19663 Cherry-pick #19601 to 7.x: Add missing azure metricsets in azure doc
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/azure.asciidoc
  x-pack/metricbeat/module/azure/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/compute_vm/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/compute_vm_scaleset/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_instance/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_registry/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_service/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/database_account/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/storage/_meta/docs.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#19654 Cherry-pick #17655 to 7.x: Start to split filebeat/channel up
  filebeat/beater/channels.go
  filebeat/beater/crawler.go
  filebeat/beater/filebeat.go
  filebeat/channel/connector.go
  filebeat/channel/factory.go
  filebeat/channel/outlet.go
  filebeat/channel/runner.go
  filebeat/channel/runner_test.go
  libbeat/autodiscover/autodiscover.go
  libbeat/cfgfile/list.go
  libbeat/cfgfile/reload.go
  libbeat/publisher/pipetool/pipetool.go
Labels: Team:Services, [zube]: In Review, backport

#19329 [Filebeat][GSuite] Initial implementation of SAML and User Accounts filesets
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/gsuite.asciidoc
  filebeat/docs/modules_list.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/include/list.go
  x-pack/filebeat/input/httpjson/config_oauth.go
  x-pack/filebeat/input/httpjson/config_test.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/module/gsuite/_meta/config.yml
  x-pack/filebeat/module/gsuite/_meta/docs.asciidoc
  x-pack/filebeat/module/gsuite/_meta/fields.yml
  x-pack/filebeat/module/gsuite/config/common.js
  x-pack/filebeat/module/gsuite/fields.go
  x-pack/filebeat/module/gsuite/ingest/common.yml
  x-pack/filebeat/module/gsuite/saml/_meta/fields.yml
  x-pack/filebeat/module/gsuite/saml/config/config.yml
  x-pack/filebeat/module/gsuite/saml/config/pipeline.js
  x-pack/filebeat/module/gsuite/saml/manifest.yml
  x-pack/filebeat/module/gsuite/saml/test/gsuite-saml-test.json.log
  x-pack/filebeat/module/gsuite/saml/test/gsuite-saml-test.json.log-expected.json
  x-pack/filebeat/module/gsuite/user_accounts/config/config.yml
  x-pack/filebeat/module/gsuite/user_accounts/config/pipeline.js
  x-pack/filebeat/module/gsuite/user_accounts/manifest.yml
  x-pack/filebeat/module/gsuite/user_accounts/test/gsuite-user_accounts-test.json.log
  x-pack/filebeat/module/gsuite/user_accounts/test/gsuite-user_accounts-test.json.log-expected.json
  x-pack/filebeat/modules.d/gsuite.yml.disabled
Labels: Filebeat, Team:SIEM, enhancement, review, v7.9.0

#19690 Cherry-pick #19177 to 7.x: Introduce statestore internal testing support
  libbeat/statestore/internal/storecompliance/reg.go
  libbeat/statestore/internal/storecompliance/storecompliance.go
  libbeat/statestore/internal/storecompliance/util.go
Labels: Team:Services, [zube]: In Review, backport

#19691 Cherry-pick #19261 to 7.x: Introduce skeleton of memlog store
  libbeat/statestore/backend/memlog/diskstore.go
  libbeat/statestore/backend/memlog/doc.go
  libbeat/statestore/backend/memlog/error.go
  libbeat/statestore/backend/memlog/memlog.go
  libbeat/statestore/backend/memlog/op.go
  libbeat/statestore/backend/memlog/store.go
  libbeat/statestore/backend/memlog/util.go
  libbeat/statestore/backend/memlog/util_darwin.go
  libbeat/statestore/backend/memlog/util_other.go
  libbeat/statestore/backend/memlog/util_windows.go
Labels: Team:Services, [zube]: In Review, backport

#19701 [Elastic Agent] Increase install/uninstall timeouts for Endpoint to 10 minutes.
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/endpoint.yml
Labels: Team:Ingest Management, bug, needs_backport

#19678 [Elastic Agent] Harden permissions and remove encrypted store
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/application/action_store.go
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_id.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/storage/storage.go
  x-pack/elastic-agent/pkg/agent/storage/storage_test.go
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
Labels: Team:Ingest Management

#19660 [MetricBeat] support wildcard `*` dimension value in AWS CloudWatch module
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Labels: Team:Platforms, [zube]: In Review, needs_backport, review

#19689 Cherry-pick #19227 to 7.x: Add statestore test helpers and unit tests
  libbeat/statestore/mock_test.go
  libbeat/statestore/registry_test.go
  libbeat/statestore/store_test.go
  libbeat/statestore/storetest/storetest.go
  libbeat/statestore/storetest/storetest_test.go
Labels: Team:Services, [zube]: In Review, backport

#19708 Cherry-pick #19135 to 7.x: Apply Autodiscovery dynamic fields in autoreloading
  CHANGELOG-developer.next.asciidoc
  filebeat/beater/crawler.go
  filebeat/channel/runner.go
  filebeat/fileset/factory.go
  filebeat/fileset/setup.go
  filebeat/input/input.go
  filebeat/input/kafka/input.go
  filebeat/input/log/input.go
  filebeat/input/mqtt/client_mocked.go
  filebeat/input/mqtt/input.go
  filebeat/input/redis/input.go
  filebeat/input/registry.go
  filebeat/input/runnerfactory.go
  filebeat/input/stdin/input.go
  filebeat/input/syslog/input.go
  filebeat/input/tcp/input.go
  filebeat/input/udp/input.go
  filebeat/input/unix/input.go
  heartbeat/beater/heartbeat.go
  heartbeat/monitors/factory.go
  heartbeat/monitors/monitor.go
  heartbeat/monitors/monitor_test.go
  heartbeat/monitors/task.go
  libbeat/autodiscover/autodiscover_test.go
  libbeat/cfgfile/factories.go
  libbeat/cfgfile/list.go
  libbeat/cfgfile/list_test.go
  libbeat/cfgfile/reload.go
  libbeat/publisher/pipetool/pipetool.go
  libbeat/publisher/testing/connector.go
  metricbeat/beater/metricbeat.go
  metricbeat/mb/module/connector.go
  metricbeat/mb/module/example_test.go
  metricbeat/mb/module/factory.go
  x-pack/filebeat/input/azureeventhub/input.go
  x-pack/filebeat/input/cloudfoundry/input.go
  x-pack/filebeat/input/googlepubsub/input.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/netflow/input.go
  x-pack/filebeat/input/o365audit/input.go
  x-pack/filebeat/input/s3/input.go
Labels: Team:Services, [zube]: In Review, backport

#19696 Cherry-pick #19507 to 7.x: Agent unenroll
  go.sum
  x-pack/elastic-agent/pkg/agent/application/action_store.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_unenroll.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/agent/application/router.go
  x-pack/elastic-agent/pkg/agent/application/router_test.go
  x-pack/elastic-agent/pkg/agent/application/stream.go
  x-pack/elastic-agent/pkg/agent/configrequest/config_request.go
  x-pack/elastic-agent/pkg/agent/configrequest/config_request_test.go
  x-pack/elastic-agent/pkg/agent/configrequest/request.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring_test.go
  x-pack/elastic-agent/pkg/agent/operation/operator.go
  x-pack/elastic-agent/pkg/agent/stateresolver/resolve_test.go
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
  x-pack/elastic-agent/pkg/core/monitoring/monitor.go
  x-pack/elastic-agent/pkg/core/monitoring/noop/noop_monitor.go
  x-pack/elastic-agent/pkg/fleetapi/action.go
Labels: Ingest Management:beta1, Team:Ingest Management, backport, review

#19699 Fix k8s scheduler compatibility issue
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/helper/prometheus/metric.go
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/scheduler/_meta/fields.yml
  metricbeat/module/kubernetes/scheduler/_meta/test/metrics.scheduler.1.14.expected
  metricbeat/module/kubernetes/scheduler/_meta/test/metrics.scheduler.1.17
  metricbeat/module/kubernetes/scheduler/_meta/test/metrics.scheduler.1.17.expected
  metricbeat/module/kubernetes/scheduler/scheduler.go
  metricbeat/module/kubernetes/scheduler/scheduler_test.go
Labels: Team:Platforms, [zube]: In Review, bug, needs_backport, review, v7.9.0

#19637 Cherry-pick #19586 to 7.x: Make Agent beta and Constraints experimental
  x-pack/elastic-agent/docs/elastic-agent_configuration_example.yml
  x-pack/elastic-agent/pkg/agent/application/filters/constraints_filter.go
  x-pack/elastic-agent/pkg/agent/warn/warn.go
Labels: Ingest Management:beta1, Team:Ingest Management, backport, review

#19709 Cherry-pick #19377 to 7.x: Add inputest package
  filebeat/input/v2/internal/inputest/inputest.go
  filebeat/input/v2/internal/inputest/loader.go
Labels: Team:Services, [zube]: In Review, backport

#19710 Cherry-pick #19378 to 7.x: Cursor input skeleton
  filebeat/input/v2/input-cursor/clean.go
  filebeat/input/v2/input-cursor/cursor.go
  filebeat/input/v2/input-cursor/doc.go
  filebeat/input/v2/input-cursor/input.go
  filebeat/input/v2/input-cursor/manager.go
  filebeat/input/v2/input-cursor/publish.go
  filebeat/input/v2/input-cursor/store.go
Labels: Team:Services, [zube]: In Review, backport

#19711 Cherry-pick #19405 to 7.x: Add more helpers to pipeline/testing package
  libbeat/publisher/testing/connector.go
Labels: Team:Services, [zube]: In Review, backport

#19719 Move O365audit input to v2 input API
  x-pack/filebeat/include/list.go
  x-pack/filebeat/input/default-inputs/inputs.go
  x-pack/filebeat/input/o365audit/contentblob.go
  x-pack/filebeat/input/o365audit/contentblob_test.go
  x-pack/filebeat/input/o365audit/dates.go
  x-pack/filebeat/input/o365audit/input.go
  x-pack/filebeat/input/o365audit/listblobs.go
  x-pack/filebeat/input/o365audit/listblobs_test.go
  x-pack/filebeat/input/o365audit/state.go
  x-pack/filebeat/input/o365audit/state_test.go
Labels: Team:Integrations, Team:SIEM, [zube]: In Review, needs_backport, needs_docs, review, test-plan

#19706 Cherry-pick #19701 to 7.x: [Elastic Agent] Increase install/uninstall timeouts for Endpoint to 10 minutes.
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/endpoint.yml
Labels: Team:Ingest Management, [zube]: In Review, backport

#19668 Update testing env 6.8.11
  testing/environments/latest.yml
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: :Testing, Team:Automation, release

#19392 Cherry-pick #19379 to 7.x: [Filebeat] Improve ECS categorization field mappings in traefik module
  CHANGELOG.next.asciidoc
  filebeat/module/traefik/access/ingest/pipeline.json
  filebeat/module/traefik/access/ingest/pipeline.yml
  filebeat/module/traefik/access/manifest.yml
  filebeat/module/traefik/access/test/test.log-expected.json
Labels: Team:SIEM, [zube]: In Review, backport

#19376 [Filebeat] Improve ECS categorization field mappings for azure module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/azure/_meta/kibana/7/dashboard/Filebeat-azure-alerts-overview.json
  x-pack/filebeat/module/azure/_meta/kibana/7/dashboard/Filebeat-azure-overview.json
  x-pack/filebeat/module/azure/_meta/kibana/7/dashboard/Filebeat-azure-user-activity.json
  x-pack/filebeat/module/azure/activitylogs/_meta/fields.yml
  x-pack/filebeat/module/azure/activitylogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/activitylogs/ingest/pipeline.yml
  x-pack/filebeat/module/azure/activitylogs/manifest.yml
  x-pack/filebeat/module/azure/activitylogs/test/activitylogs.log-expected.json
  x-pack/filebeat/module/azure/activitylogs/test/supporttickets_write.log
  x-pack/filebeat/module/azure/activitylogs/test/supporttickets_write.log-expected.json
  x-pack/filebeat/module/azure/auditlogs/_meta/fields.yml
  x-pack/filebeat/module/azure/auditlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/auditlogs/ingest/pipeline.yml
  x-pack/filebeat/module/azure/auditlogs/manifest.yml
  x-pack/filebeat/module/azure/auditlogs/test/auditlogs.log-expected.json
  x-pack/filebeat/module/azure/azure-shared-pipeline.json
  x-pack/filebeat/module/azure/azure-shared-pipeline.yml
  x-pack/filebeat/module/azure/fields.go
  x-pack/filebeat/module/azure/signinlogs/_meta/fields.yml
  x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.json
  x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.yml
  x-pack/filebeat/module/azure/signinlogs/manifest.yml
  x-pack/filebeat/module/azure/signinlogs/test/signinlogs.log-expected.json
Labels: Filebeat, Team:SIEM, enhancement, needs_backport

#19723 Cherry-pick #19699 to 7.x: Fix k8s scheduler compatibility issue
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/helper/prometheus/metric.go
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/scheduler/_meta/fields.yml
  metricbeat/module/kubernetes/scheduler/_meta/test/metrics.scheduler.1.14.expected
  metricbeat/module/kubernetes/scheduler/_meta/test/metrics.scheduler.1.17
  metricbeat/module/kubernetes/scheduler/_meta/test/metrics.scheduler.1.17.expected
  metricbeat/module/kubernetes/scheduler/scheduler.go
  metricbeat/module/kubernetes/scheduler/scheduler_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#19620 align service parameters to documentation (#19616)
  dev-tools/packaging/templates/deb/init.sh.tmpl
  dev-tools/packaging/templates/linux/beatname.sh.tmpl
  dev-tools/packaging/templates/linux/systemd.unit.tmpl
  dev-tools/packaging/templates/rpm/init.sh.tmpl
  dev-tools/packaging/templates/windows/install-service.ps1.tmpl
Labels: Team:Services, [zube]: In Review, bug, review

#18706 Report if index is hidden in index stats
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/elasticsearch_integration_test.go
  metricbeat/module/elasticsearch/index/data_xpack.go
Labels: Stack monitoring, Team:Services, [zube]: In Review

#19622 Init winlog input
  filebeat/input/default-inputs/inputs_windows.go
  filebeat/input/winlog/input.go
  winlogbeat/eventlog/factory.go
Labels: Filebeat, Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, needs_backport, review, v7.9.0

#19728 Cherry-pick #19401 to 7.x: Input v2 compatibility layer
  filebeat/input/v2/compat/compat.go
  filebeat/input/v2/compat/compat_test.go
  filebeat/input/v2/compat/composed.go
  filebeat/input/v2/compat/composed_test.go
Labels: Team:Services, [zube]: In Review, backport

#19729 Cherry-pick #19406 to 7.x: Input v2 stateless manager
  filebeat/input/v2/input-stateless/stateless.go
  filebeat/input/v2/input-stateless/stateless_test.go
Labels: Team:Services, [zube]: In Review, backport

#19720 Cherry-pick #19408, #19533 to 7.x: Implement memlog on-disk handling
  libbeat/statestore/backend/memlog/diskstore.go
  libbeat/statestore/backend/memlog/json.go
  libbeat/statestore/backend/memlog/memlog.go
  libbeat/statestore/backend/memlog/memlog_test.go
  libbeat/statestore/backend/memlog/store.go
  libbeat/statestore/backend/memlog/testdata/1/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/commit_wrong_id/1.json
  libbeat/statestore/backend/memlog/testdata/1/commit_wrong_id/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/commit_wrong_id/expected.json
  libbeat/statestore/backend/memlog/testdata/1/commit_wrong_id/log.json
  libbeat/statestore/backend/memlog/testdata/1/commit_wrong_id/meta.json
  libbeat/statestore/backend/memlog/testdata/1/data_and_log/1.json
  libbeat/statestore/backend/memlog/testdata/1/data_and_log/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/data_and_log/expected.json
  libbeat/statestore/backend/memlog/testdata/1/data_and_log/log.json
  libbeat/statestore/backend/memlog/testdata/1/data_and_log/meta.json
  libbeat/statestore/backend/memlog/testdata/1/datafile_only/1.json
  libbeat/statestore/backend/memlog/testdata/1/datafile_only/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/datafile_only/expected.json
  libbeat/statestore/backend/memlog/testdata/1/datafile_only/meta.json
  libbeat/statestore/backend/memlog/testdata/1/incomplete_op/1.json
  libbeat/statestore/backend/memlog/testdata/1/incomplete_op/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/incomplete_op/expected.json
  libbeat/statestore/backend/memlog/testdata/1/incomplete_op/log.json
  libbeat/statestore/backend/memlog/testdata/1/incomplete_op/meta.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_incomplete/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/logfile_incomplete/expected.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_incomplete/log.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_incomplete/meta.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_only/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/logfile_only/expected.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_only/log.json
  libbeat/statestore/backend/memlog/testdata/1/logfile_only/meta.json
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/1.json
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/2.json
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/3.json
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/expected.json
  libbeat/statestore/backend/memlog/testdata/1/old_datafiles/meta.json
  libbeat/statestore/backend/memlog/testdata/1/old_entries_in_log/5.json
  libbeat/statestore/backend/memlog/testdata/1/old_entries_in_log/Readme.md
  libbeat/statestore/backend/memlog/testdata/1/old_entries_in_log/expected.json
  libbeat/statestore/backend/memlog/testdata/1/old_entries_in_log/log.json
  libbeat/statestore/backend/memlog/testdata/1/old_entries_in_log/meta.json
  libbeat/statestore/backend/memlog/util.go
Labels: Team:Services, [zube]: In Review, backport

#19199 [CI] enable Windows-2016 and support 32 bits build requirements
  .ci/scripts/install-tools.bat
  .ci/windows.groovy
  dev-tools/mage/gotest.go
  x-pack/elastic-agent/magefile.go
Labels: Team:Automation, Team:Ingest Management

#19682 Cherry-pick to 7.x: Get stats for all indices, including hidden indices (#18703)
  CHANGELOG.next.asciidoc
  metricbeat/docker-compose.yml
  metricbeat/module/elasticsearch/elasticsearch_integration_test.go
  metricbeat/module/elasticsearch/index/data_xpack.go
  metricbeat/module/elasticsearch/index/index.go
  metricbeat/module/logstash/docker-compose.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Services, backport

#19744 Bumping up app search image version to 7.6.2
  x-pack/metricbeat/module/appsearch/docker-compose.yml
Labels: Team:Services, [zube]: In Review, needs_backport, v7.8.2, v7.9.0, v8.0.0

#19714 Cherry-pick #19660 to 7.x: [MetricBeat] support wildcard `*` dimension value in AWS CloudWatch module
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#19730 Cherry-pick #19515 to 7.x: Export Run from common listener inputsource
  filebeat/inputsource/common/listener.go
Labels: Team:Services, [zube]: In Review, backport
