Repository elastic/beats, pull requests merged in 2020-10, with the labels that each got.

#21372 [Ingest Manager] Upgrade Action: make source URI optional
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_unpack.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade.go
  x-pack/elastic-agent/pkg/fleetapi/action.go
Labels: Ingest Management:beta2, Team:Ingest Management, enhancement

#21225 Initial spec file for apm-server
  x-pack/elastic-agent/spec/apm-server.yml.disabled
Labels: Agent, Team:Ingest Management, Team:apm

#21427 Add initial skeleton of filestream input
  filebeat/input/filestream/input.go
  filebeat/input/filestream/internal/input-logfile/clean.go
  filebeat/input/filestream/internal/input-logfile/clean_test.go
  filebeat/input/filestream/internal/input-logfile/cursor.go
  filebeat/input/filestream/internal/input-logfile/cursor_test.go
  filebeat/input/filestream/internal/input-logfile/doc.go
  filebeat/input/filestream/internal/input-logfile/fswatch.go
  filebeat/input/filestream/internal/input-logfile/harvester.go
  filebeat/input/filestream/internal/input-logfile/input.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/filestream/internal/input-logfile/prospector.go
  filebeat/input/filestream/internal/input-logfile/publish.go
  filebeat/input/filestream/internal/input-logfile/publish_test.go
  filebeat/input/filestream/internal/input-logfile/store.go
  filebeat/input/filestream/internal/input-logfile/store_test.go
  filebeat/input/filestream/prospector.go
Labels: Team:Services

#21410 [JJBB] Use reference repo for fast checkouts
  .ci/jobs/beats.yml
Labels: Team:Automation, automation, ci

#21394 Cherry-pick #21374 to 7.x: Add UBI 8 image to Beats dependencies report
  dev-tools/dependencies-report
  dev-tools/notice/dependencies.csv.tmpl
Labels: Team:Automation, [zube]: In Review, backport

#21447 Revert "[JJBB] Set shallow cloning to 10"
  .ci/jobs/apm-beats-update.yml
  .ci/jobs/beats-tester.yml
  .ci/jobs/beats-windows-mbp.yml
  .ci/jobs/beats.yml
  .ci/jobs/golang-crossbuild-mbp.yml
  .ci/jobs/packaging.yml
Labels: Team:Automation

#21353 Cherry-pick #21085 to 7.x: Adds a default for failure_cache.min_ttl
  libbeat/processors/dns/config.go
Labels: Team:SIEM, [zube]: In Review, backport

#21443 Cherry-pick to 7.x: [Metricbeat][test] Disable ec2 flaky test (#20959)
  x-pack/metricbeat/module/aws/ec2/ec2_integration_test.go
Labels: Team:Automation, automation, backport, ci

#21233 Edit SQL module docs and fix broken doc structure
  metricbeat/docs/modules/sql.asciidoc
  x-pack/metricbeat/module/sql/_meta/docs.asciidoc
  x-pack/metricbeat/module/sql/query/_meta/docs.asciidoc
Labels: Team:Docs, Team:Integrations, docs, needs_backport, review, v7.9.0, v8.0.0

#21453 Cherry-pick to 7.x: Edit SQL module docs and fix broken doc structure (#21233)
  metricbeat/docs/modules/sql.asciidoc
  x-pack/metricbeat/module/sql/_meta/docs.asciidoc
  x-pack/metricbeat/module/sql/query/_meta/docs.asciidoc
Labels: Team:Docs, backport, docs, v7.10.0

#21452 Cherry-pick to 7.9: Edit SQL module docs and fix broken doc structure (#21233)
  metricbeat/docs/modules/sql.asciidoc
  x-pack/metricbeat/module/sql/_meta/docs.asciidoc
  x-pack/metricbeat/module/sql/query/_meta/docs.asciidoc
Labels: Team:Docs, backport, docs, v7.9.0

#21429 Cherry-pick #21402 to 7.x: [Winlogbeat] Move winlogbeat javascript processor to libbeat
  libbeat/processors/script/javascript/module/include.go
  libbeat/processors/script/javascript/module/windows/doc.go
  libbeat/processors/script/javascript/module/windows/windows.go
  libbeat/processors/script/javascript/module/windows/windows_test.go
  winlogbeat/cmd/root.go
  x-pack/winlogbeat/module/powershell/config/winlogbeat-powershell.js
  x-pack/winlogbeat/module/security/config/winlogbeat-security.js
  x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js
  x-pack/winlogbeat/module/testing_windows.go
Labels: Team:SIEM, [zube]: In Review, backport

#21384 Cherry-pick #20751 to 7.x: [Filebeat][httpjson] Make httpjson use cursor input when using date cursor
  CHANGELOG.next.asciidoc
  filebeat/input/v2/input-cursor/manager.go
  x-pack/filebeat/input/default-inputs/inputs.go
  x-pack/filebeat/input/httpjson/config.go
  x-pack/filebeat/input/httpjson/config_oauth.go
  x-pack/filebeat/input/httpjson/config_oauth_test.go
  x-pack/filebeat/input/httpjson/config_test.go
  x-pack/filebeat/input/httpjson/date_cursor.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/input_cursor.go
  x-pack/filebeat/input/httpjson/input_manager.go
  x-pack/filebeat/input/httpjson/input_stateless.go
  x-pack/filebeat/input/httpjson/input_test.go
  x-pack/filebeat/input/httpjson/pagination.go
  x-pack/filebeat/input/httpjson/pagination_test.go
  x-pack/filebeat/input/httpjson/rate_limiter.go
  x-pack/filebeat/input/httpjson/requester.go
Labels: Team:SIEM, [zube]: In Review, backport

#21354 Cherry-pick #21212 to 7.x: Configurable index template loading
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/setup.template.reference.yml.tmpl
  libbeat/docs/template-config.asciidoc
  libbeat/template/config.go
  libbeat/template/load.go
  libbeat/template/load_integration_test.go
  libbeat/template/template.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Services, [zube]: In Review, backport

#21442 Cherry-pick #21427 to 7.x: Add initial skeleton of filestream input
  filebeat/input/filestream/input.go
  filebeat/input/filestream/internal/input-logfile/clean.go
  filebeat/input/filestream/internal/input-logfile/clean_test.go
  filebeat/input/filestream/internal/input-logfile/cursor.go
  filebeat/input/filestream/internal/input-logfile/cursor_test.go
  filebeat/input/filestream/internal/input-logfile/doc.go
  filebeat/input/filestream/internal/input-logfile/fswatch.go
  filebeat/input/filestream/internal/input-logfile/harvester.go
  filebeat/input/filestream/internal/input-logfile/input.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/filestream/internal/input-logfile/prospector.go
  filebeat/input/filestream/internal/input-logfile/publish.go
  filebeat/input/filestream/internal/input-logfile/publish_test.go
  filebeat/input/filestream/internal/input-logfile/store.go
  filebeat/input/filestream/internal/input-logfile/store_test.go
  filebeat/input/filestream/prospector.go
Labels: Team:Services, [zube]: In Review, backport

#21406 [Ingest Manager] Split index restrictions into type,dataset, namespace parts
  x-pack/elastic-agent/pkg/agent/application/filters/stream_checker.go
  x-pack/elastic-agent/pkg/agent/application/filters/stream_checker_test.go
Labels: Ingest Management:beta2, Team:Ingest Management

#21444 Add implementation of FSWatcher and FSScanner for filestream
  filebeat/input/filestream/fswatch.go
  filebeat/input/filestream/fswatch_test.go
  filebeat/input/filestream/testdata/excluded_file
  filebeat/input/filestream/testdata/included_file
  filebeat/input/filestream/testdata/symlink_to_included_file
Labels: Team:Services, needs_backport

#21462 Remove duplicated sources url in dependencies report
  dev-tools/dependencies-report
Labels: Team:Automation, bug, needs_backport, v7.10.0

#21428 [CI] Send slack message with build status
  Jenkinsfile
Labels: Team:Automation, automation, ci

#21450 Add new log file reader for filestream input
  filebeat/input/filestream/config.go
  filebeat/input/filestream/filestream.go
Labels: Team:Services, needs_backport

#21464 [CI] changeset from #20603 was not added to CI2.0
  Jenkinsfile.yml
Labels: Team:Automation, automation, ci, needs_backport, v7.10.0

#21463 [CI] Change x-pack/auditbeat build events (comments, labels)
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, ci

#21459 Cherry-pick #21406 to 7.x: Split index restrictions into type,dataset, namespace parts
  x-pack/elastic-agent/pkg/agent/application/filters/stream_checker.go
  x-pack/elastic-agent/pkg/agent/application/filters/stream_checker_test.go
Labels: Ingest Management:beta2, Team:Ingest Management, backport

#21482 Fix format of debug messages in tlscommon
  libbeat/common/transport/tlscommon/tls.go
Labels: Team:Integrations, Team:Services, bug, needs_backport, v7.10.0, v7.9.3

#21467 Revert "Revert "[JJBB] Set shallow cloning to 10""
  .ci/jobs/apm-beats-update.yml
  .ci/jobs/beats-tester.yml
  .ci/jobs/beats-windows-mbp.yml
  .ci/jobs/beats.yml
  .ci/jobs/golang-crossbuild-mbp.yml
  .ci/jobs/packaging.yml
Labels: Team:Automation, automation, ci

#21475 Cherry-pick to 7.x: [CI] changeset from #20603 was not added to CI2.0 (#21464)
  Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#21477 Cherry-pick to 7.x: [CI] Change x-pack/auditbeat build events (comments, labels) (#21463)
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#21476 Cherry-pick to 7.9: [CI] Change x-pack/auditbeat build events (comments, labels) (#21463)
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#21469 Cherry-pick to 7.x: [CI] Send slack message with build status (#21428)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#21493 [libbeat] Add configurable exponential backoff for disk queue write errors
  libbeat/publisher/queue/diskqueue/config.go
  libbeat/publisher/queue/diskqueue/deleter_loop.go
  libbeat/publisher/queue/diskqueue/segments.go
  libbeat/publisher/queue/diskqueue/util.go
  libbeat/publisher/queue/diskqueue/writer_loop.go
Labels: Team:Integrations, enhancement, libbeat, needs_backport

#20005 Migrate S3 Input to Filebeat Input V2
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/default-inputs/inputs.go
  x-pack/filebeat/input/s3/collector.go
  x-pack/filebeat/input/s3/collector_test.go
  x-pack/filebeat/input/s3/config.go
  x-pack/filebeat/input/s3/input.go
  x-pack/filebeat/input/s3/s3_integration_test.go
Labels: Team:Platforms, [zube]: In Review, needs_backport, test-plan

#21487 Increase index pattern size check to 10MiB
  libbeat/tests/system/beat/common_tests.py
Labels: :Testing, Team:SIEM, enhancement, needs_backport, review

#19284 Clarify input type configuration options
  filebeat/docs/reload-configuration.asciidoc
Labels: Team:Services, [zube]: In Review, docs

#21491 Cherry-pick #21482 to 7.x: Fix format of debug messages in tlscommon
  libbeat/common/transport/tlscommon/tls.go
Labels: Team:Integrations, Team:Services, [zube]: In Review, backport

#21492 Cherry-pick #21482 to 7.9: Fix format of debug messages in tlscommon
  libbeat/common/transport/tlscommon/tls.go
Labels: Team:Integrations, Team:Services, [zube]: In Review, backport

#21474 [docs] [Kubernetes] Fix leftover deployment example
  metricbeat/docs/running-on-kubernetes.asciidoc
Labels: Team:Platforms, [zube]: In Review, needs_backport, review, v7.10.0

#21473 [Ingest Manager] Prompt only when agent is already enrolled
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
Labels: Ingest Management:beta2, Team:Ingest Management, bug

#21484 Include original error when metricbeat fails to connect with Kafka
  metricbeat/module/kafka/broker.go
Labels: Metricbeat, Team:Services, enhancement, needs_backport, v7.10.0, v7.9.3

#21483 Map `cloud.account.id` to azure sub id
  CHANGELOG.next.asciidoc
  libbeat/processors/add_cloud_metadata/provider_azure_vm.go
  libbeat/processors/add_cloud_metadata/provider_azure_vm_test.go
  x-pack/metricbeat/module/azure/add_metadata.go
  x-pack/metricbeat/module/azure/compute_vm/_meta/data.json
  x-pack/metricbeat/module/azure/compute_vm_scaleset/_meta/data.json
  x-pack/metricbeat/module/azure/data.go
Labels: Team:Platforms, [zube]: In Review, needs_backport

#21472 Do not run symlink tests on Windows
  filebeat/input/filestream/fswatch_test.go
  filebeat/input/filestream/fswatch_test_non_windows.go
  filebeat/input/filestream/testdata/excluded_file
  filebeat/input/filestream/testdata/included_file
  filebeat/input/filestream/testdata/symlink_to_included_file
Labels: Team:Services

#21505 Cherry-pick #21474 to 7.x: [docs] [Kubernetes] Fix leftover deployment example
  metricbeat/docs/running-on-kubernetes.asciidoc
Labels: Team:Platforms, [zube]: In Review, backport

#21486 Ignore unsupported metrics in the azure module
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/compute_vm_scaleset/manifest.yml
  x-pack/metricbeat/module/azure/config.go
  x-pack/metricbeat/module/azure/container_instance/manifest.yml
  x-pack/metricbeat/module/azure/container_service/manifest.yml
  x-pack/metricbeat/module/azure/database_account/manifest.yml
  x-pack/metricbeat/module/azure/monitor/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/monitor/client_helper.go
  x-pack/metricbeat/module/azure/monitor/client_helper_test.go
Labels: Team:Platforms, [zube]: In Review, needs_backport

#21508 Cherry-pick #21484 to 7.x: Include original error when metricbeat fails to connect with Kafka
  metricbeat/module/kafka/broker.go
Labels: Team:Services, [zube]: In Review, backport

#21509 Cherry-pick #21484 to 7.9: Include original error when metricbeat fails to connect with Kafka
  metricbeat/module/kafka/broker.go
Labels: Team:Services, [zube]: In Review, backport

#21468 Cherry-pick #21444 to 7.x: Add implementation of FSWatcher and FSScanner for filestream
  filebeat/input/filestream/fswatch.go
  filebeat/input/filestream/fswatch_test.go
  filebeat/input/filestream/fswatch_test_non_windows.go
Labels: Team:Services, [zube]: In Review, backport

#21490 Skip filestream flaky tests
  filebeat/input/filestream/fswatch_test.go
Labels: Team:Services, flaky-test

#21471 Cherry-pick #21462 to 7.x: Remove duplicated sources url in dependencies report
  dev-tools/dependencies-report
Labels: Team:Automation, [zube]: In Review, backport

#21513 Cherry-pick #21486 to 7.x: Ignore unsupported metrics in the azure module
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/compute_vm_scaleset/manifest.yml
  x-pack/metricbeat/module/azure/config.go
  x-pack/metricbeat/module/azure/container_instance/manifest.yml
  x-pack/metricbeat/module/azure/container_service/manifest.yml
  x-pack/metricbeat/module/azure/database_account/manifest.yml
  x-pack/metricbeat/module/azure/monitor/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/monitor/client_helper.go
  x-pack/metricbeat/module/azure/monitor/client_helper_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#21516 Cherry-pick #21490 to 7.x: Skip filestream flaky tests
  filebeat/input/filestream/fswatch_test.go
Labels: Team:Services, [zube]: In Review, backport

#21500 Cherry-pick #20005 to 7.x: Migrate S3 Input to Filebeat Input V2
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/default-inputs/inputs.go
  x-pack/filebeat/input/s3/collector.go
  x-pack/filebeat/input/s3/collector_test.go
  x-pack/filebeat/input/s3/config.go
  x-pack/filebeat/input/s3/input.go
  x-pack/filebeat/input/s3/s3_integration_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#21470 Cherry-pick #21450 to 7.x: Add new log file reader for filestream input
  filebeat/input/filestream/config.go
  filebeat/input/filestream/filestream.go
Labels: Team:Services, [zube]: In Review, backport

#21511 Cherry-pick #21483 to 7.x: Map `cloud.account.id` to azure sub id
  CHANGELOG.next.asciidoc
  libbeat/processors/add_cloud_metadata/provider_azure_vm.go
  libbeat/processors/add_cloud_metadata/provider_azure_vm_test.go
  x-pack/metricbeat/module/azure/add_metadata.go
  x-pack/metricbeat/module/azure/compute_vm/_meta/data.json
  x-pack/metricbeat/module/azure/compute_vm_scaleset/_meta/data.json
  x-pack/metricbeat/module/azure/data.go
Labels: Team:Platforms, [zube]: In Review, backport

#20875 [Metricbeat] Add latency config option into aws module
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/aws.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/ec2/ec2.go
  x-pack/metricbeat/module/aws/rds/rds.go
  x-pack/metricbeat/module/aws/s3_daily_storage/s3_daily_storage.go
  x-pack/metricbeat/module/aws/s3_request/s3_request.go
  x-pack/metricbeat/module/aws/sqs/sqs.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: Team:Platforms, needs_backport, review

#21479 Implementation of fileProspector
  filebeat/input/filestream/identifier.go
  filebeat/input/filestream/identifier_inode_deviceid.go
  filebeat/input/filestream/identifier_inode_deviceid_windows.go
  filebeat/input/filestream/input.go
  filebeat/input/filestream/prospector.go
Labels: Team:Services

#21497 Cherry-pick #21493 to 7.x: [libbeat] Add configurable exponential backoff for disk queue write errors
  libbeat/publisher/queue/diskqueue/config.go
  libbeat/publisher/queue/diskqueue/deleter_loop.go
  libbeat/publisher/queue/diskqueue/segments.go
  libbeat/publisher/queue/diskqueue/util.go
  libbeat/publisher/queue/diskqueue/writer_loop.go
Labels: Team:Integrations, [zube]: In Review, backport

#21488 [Ingest Manager] Download asc from artifact store specified in spec
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
  x-pack/elastic-agent/pkg/agent/operation/common_test.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
  x-pack/elastic-agent/pkg/agent/operation/operation_verify.go
  x-pack/elastic-agent/pkg/artifact/download/composed/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/fs/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/fs/verifier_test.go
  x-pack/elastic-agent/pkg/artifact/download/http/elastic_test.go
  x-pack/elastic-agent/pkg/artifact/download/http/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/verifier.go
Labels: Ingest Management:beta2, Team:Ingest Management, bug

#21504 [Filebeat][New Fileset] Cisco Umbrella support
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/cisco.asciidoc
  x-pack/filebeat/module/cisco/_meta/docs.asciidoc
  x-pack/filebeat/module/cisco/fields.go
  x-pack/filebeat/module/cisco/umbrella/_meta/fields.yml
  x-pack/filebeat/module/cisco/umbrella/config/input.yml
  x-pack/filebeat/module/cisco/umbrella/ingest/pipeline.yml
  x-pack/filebeat/module/cisco/umbrella/manifest.yml
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-cloudfirewalllogs.log
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-cloudfirewalllogs.log-expected.json
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-dnslogs.log
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-dnslogs.log-expected.json
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-iplogs.log
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-iplogs.log-expected.json
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-proxylogs.log
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-proxylogs.log-expected.json
Labels: Filebeat, Team:SIEM, enhancement, review

#21441 Cherry-pick #21241 to 7.x: Enabled dev builds
  x-pack/elastic-agent/magefile.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
Labels: Ingest Management:beta2, Team:Ingest Management, backport, enhancement

#21460 Cherry-pick #21285 to 7.x: Send snapshot flag together with metadata
  x-pack/elastic-agent/pkg/agent/application/info/agent_metadata.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade.go
  x-pack/elastic-agent/pkg/release/upgrade.go
  x-pack/elastic-agent/pkg/release/version.go
Labels: Ingest Management:beta2, Team:Ingest Management, backport, review

#21440 Cherry-pick #21372 to 7.x: Upgrade Action: make source URI optional
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_unpack.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade.go
  x-pack/elastic-agent/pkg/fleetapi/action.go
Labels: Ingest Management:beta2, Team:Ingest Management, backport, enhancement

#21461 [Ingest Manager] Send updating state
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade.go
  x-pack/elastic-agent/pkg/core/state/state.go
  x-pack/elastic-agent/pkg/reporter/reporter.go
Labels: Ingest Management:beta2, Team:Ingest Management, enhancement, needs_backport

#21523 Cherry-pick #21488 to 7.x: Download asc from artifact store specified in spec
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
  x-pack/elastic-agent/pkg/agent/operation/common_test.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
  x-pack/elastic-agent/pkg/agent/operation/operation_verify.go
  x-pack/elastic-agent/pkg/artifact/download/composed/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/fs/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/fs/verifier_test.go
  x-pack/elastic-agent/pkg/artifact/download/http/elastic_test.go
  x-pack/elastic-agent/pkg/artifact/download/http/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/verifier.go
Labels: Ingest Management:beta2, Team:Ingest Management, bug

#21531 Fix billing.go aws.GetStartTimeEndTime
  x-pack/metricbeat/module/aws/billing/billing.go
Labels: Team:Platforms, review

#21466 [CI] fix 'no matches found within 10000'
  Jenkinsfile
Labels: Team:Automation, automation, ci

#21481 Add filestream input reader
  filebeat/input/filestream/config.go
  filebeat/input/filestream/filestream.go
  filebeat/input/filestream/input.go
Labels: Team:Services, needs_backport

#21529 Cherry-pick #21479 to 7.x: Implementation of fileProspector
  filebeat/input/filestream/identifier.go
  filebeat/input/filestream/identifier_inode_deviceid.go
  filebeat/input/filestream/identifier_inode_deviceid_windows.go
  filebeat/input/filestream/input.go
  filebeat/input/filestream/prospector.go
Labels: Team:Services, [zube]: In Review, backport

#21530 Cherry-pick #21461 to 7.x: Send updating state
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade.go
  x-pack/elastic-agent/pkg/core/state/state.go
  x-pack/elastic-agent/pkg/reporter/reporter.go
Labels: Ingest Management:beta2, Team:Ingest Management, backport, enhancement

#21514 Cherry-pick #21487 to 7.x: Increase index pattern size check to 10MiB
  libbeat/tests/system/beat/common_tests.py
Labels: Team:SIEM, [zube]: In Review, backport, review

#21425 [Elastic Agent] Add upgrade CLI to initiate upgrade of Agent locally
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/application.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_upgrade.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_mark.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade.go
  x-pack/elastic-agent/pkg/agent/cmd/common.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/cmd/upgrade.go
  x-pack/elastic-agent/pkg/agent/control/control_test.go
  x-pack/elastic-agent/pkg/agent/control/server/server.go
  x-pack/elastic-agent/pkg/basecmd/version/cmd_test.go
Labels: Team:Ingest Management

#21502 Cherry-pick to 7.9: Clarify input type configuration options (#19284)
  filebeat/docs/reload-configuration.asciidoc
Labels: Team:Docs, backport, docs, v7.9.0

#21503 Cherry-pick to 7.x: Clarify input type configuration options (#19284)
  filebeat/docs/reload-configuration.asciidoc
Labels: Team:Docs, backport, docs, v7.10.0

#21538 Cherry-pick #21481 to 7.x: Add filestream input reader
  filebeat/input/filestream/config.go
  filebeat/input/filestream/filestream.go
  filebeat/input/filestream/input.go
Labels: Team:Services, [zube]: In Review, backport

#21539 Cherry-pick #21533 to 7.x: Enable filestream input
  filebeat/input/default-inputs/inputs.go
  filebeat/input/filestream/fswatch.go
Labels: Team:Services, [zube]: In Review, backport

#21550 [Filebeat][cisco] Add missing changelog entry for cisco umbrella
  CHANGELOG.next.asciidoc
Labels: Filebeat, Team:SIEM

#21534 Cherry-pick to 7.9: [CI] fix 'no matches found within 10000' (#21466)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#21535 Cherry-pick to 7.x: [CI] fix 'no matches found within 10000' (#21466)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#20017 junipersrx-module initial release
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/juniper.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/juniper/_meta/config.yml
  x-pack/filebeat/module/juniper/_meta/docs.asciidoc
  x-pack/filebeat/module/juniper/fields.go
  x-pack/filebeat/module/juniper/netscreen/test/generated.log-expected.json
  x-pack/filebeat/module/juniper/srx/_meta/fields.yml
  x-pack/filebeat/module/juniper/srx/config/srx.yml
  x-pack/filebeat/module/juniper/srx/ingest/atp.yml
  x-pack/filebeat/module/juniper/srx/ingest/flow.yml
  x-pack/filebeat/module/juniper/srx/ingest/idp.yml
  x-pack/filebeat/module/juniper/srx/ingest/ids.yml
  x-pack/filebeat/module/juniper/srx/ingest/pipeline.yml
  x-pack/filebeat/module/juniper/srx/ingest/secintel.yml
  x-pack/filebeat/module/juniper/srx/ingest/utm.yml
  x-pack/filebeat/module/juniper/srx/manifest.yml
  x-pack/filebeat/module/juniper/srx/test/atp.log
  x-pack/filebeat/module/juniper/srx/test/atp.log-expected.json
  x-pack/filebeat/module/juniper/srx/test/flow.log
  x-pack/filebeat/module/juniper/srx/test/flow.log-expected.json
  x-pack/filebeat/module/juniper/srx/test/idp.log
  x-pack/filebeat/module/juniper/srx/test/idp.log-expected.json
  x-pack/filebeat/module/juniper/srx/test/ids.log
  x-pack/filebeat/module/juniper/srx/test/ids.log-expected.json
  x-pack/filebeat/module/juniper/srx/test/secintel.log
  x-pack/filebeat/module/juniper/srx/test/secintel.log-expected.json
  x-pack/filebeat/module/juniper/srx/test/utm.log
  x-pack/filebeat/module/juniper/srx/test/utm.log-expected.json
  x-pack/filebeat/modules.d/juniper.yml.disabled
Labels: Filebeat, Team:SIEM, enhancement, review

#21383 Cherry-pick #21258 to 7.x: o365input: Restart after fatal error
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/o365audit/input.go
Labels: Team:SIEM, [zube]: In Review, backport, review

#21527 Cherry-pick #21504 to 7.x: [Filebeat][New Fileset] Cisco Umbrella support
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/cisco.asciidoc
  x-pack/filebeat/module/cisco/_meta/docs.asciidoc
  x-pack/filebeat/module/cisco/fields.go
  x-pack/filebeat/module/cisco/umbrella/_meta/fields.yml
  x-pack/filebeat/module/cisco/umbrella/config/input.yml
  x-pack/filebeat/module/cisco/umbrella/ingest/pipeline.yml
  x-pack/filebeat/module/cisco/umbrella/manifest.yml
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-cloudfirewalllogs.log
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-cloudfirewalllogs.log-expected.json
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-dnslogs.log
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-dnslogs.log-expected.json
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-iplogs.log
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-iplogs.log-expected.json
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-proxylogs.log
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-proxylogs.log-expected.json
Labels: Team:SIEM, [zube]: In Review, backport

#20999 [Beats][pytest] Asserting if filebeat logs include errors
  filebeat/tests/system/test_modules.py
Labels: Team:Platforms, Team:Services, enhancement, needs_backport, v7.10.0

#21446 [Filebeat][New Module] Add support for Microsoft MTP / 365 Defender
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/microsoft.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/microsoft/_meta/config.yml
  x-pack/filebeat/module/microsoft/_meta/docs.asciidoc
  x-pack/filebeat/module/microsoft/fields.go
  x-pack/filebeat/module/microsoft/m365_defender/_meta/fields.yml
  x-pack/filebeat/module/microsoft/m365_defender/config/defender.yml
  x-pack/filebeat/module/microsoft/m365_defender/ingest/pipeline.yml
  x-pack/filebeat/module/microsoft/m365_defender/manifest.yml
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log-expected.json
  x-pack/filebeat/modules.d/microsoft.yml.disabled
Labels: Filebeat, Team:SIEM, enhancement, review

#21221 [Packetbeat] New SIP protocol
  CHANGELOG.next.asciidoc
  packetbeat/_meta/config/beat.docker.yml.tmpl
  packetbeat/_meta/config/beat.reference.yml.tmpl
  packetbeat/_meta/config/beat.yml.tmpl
  packetbeat/_meta/sample_outputs/sip.json
  packetbeat/docs/fields.asciidoc
  packetbeat/docs/shared-protocol-list.asciidoc
  packetbeat/include/list.go
  packetbeat/packetbeat.docker.yml
  packetbeat/packetbeat.reference.yml
  packetbeat/packetbeat.yml
  packetbeat/pb/ecs.go
  packetbeat/pb/event.go
  packetbeat/protos/sip/README.md
  packetbeat/protos/sip/_meta/fields.yml
  packetbeat/protos/sip/config.go
  packetbeat/protos/sip/event.go
  packetbeat/protos/sip/fields.go
  packetbeat/protos/sip/parser.go
  packetbeat/protos/sip/plugin.go
  packetbeat/protos/sip/plugin_test.go
  packetbeat/tests/system/config/golden-tests.yml
  packetbeat/tests/system/config/packetbeat.yml.j2
  packetbeat/tests/system/golden/sip-expected.json
  packetbeat/tests/system/golden/sip_authenticated_register-expected.json
  packetbeat/tests/system/pcaps/sip.pcap
  packetbeat/tests/system/pcaps/sip_authenticated_register.pcap
  packetbeat/tests/system/test_0099_golden_files.py
Labels: Packetbeat, Team:SIEM, enhancement, in progress, v7.10.0

#21525 Release cloudfoundry input and processor as GA
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/cloudfoundry/input.go
  x-pack/libbeat/processors/add_cloudfoundry_metadata/docs/add_cloudfoundry_metadata.asciidoc
Labels: Team:Platforms, v7.10.0

#21557 Cherry-pick #21221 to 7.x: [Packetbeat] New SIP protocol
  CHANGELOG.next.asciidoc
  packetbeat/_meta/config/beat.docker.yml.tmpl
  packetbeat/_meta/config/beat.reference.yml.tmpl
  packetbeat/_meta/config/beat.yml.tmpl
  packetbeat/_meta/sample_outputs/sip.json
  packetbeat/docs/fields.asciidoc
  packetbeat/docs/shared-protocol-list.asciidoc
  packetbeat/include/list.go
  packetbeat/packetbeat.docker.yml
  packetbeat/packetbeat.reference.yml
  packetbeat/packetbeat.yml
  packetbeat/pb/ecs.go
  packetbeat/pb/event.go
  packetbeat/protos/sip/README.md
  packetbeat/protos/sip/_meta/fields.yml
  packetbeat/protos/sip/config.go
  packetbeat/protos/sip/event.go
  packetbeat/protos/sip/fields.go
  packetbeat/protos/sip/parser.go
  packetbeat/protos/sip/plugin.go
  packetbeat/protos/sip/plugin_test.go
  packetbeat/tests/system/config/golden-tests.yml
  packetbeat/tests/system/config/packetbeat.yml.j2
  packetbeat/tests/system/golden/sip-expected.json
  packetbeat/tests/system/golden/sip_authenticated_register-expected.json
  packetbeat/tests/system/pcaps/sip.pcap
  packetbeat/tests/system/pcaps/sip_authenticated_register.pcap
  packetbeat/tests/system/test_0099_golden_files.py
Labels: Team:SIEM, [zube]: In Review, backport

#21554 Cherry-pick #20999 to 7.x: [Beats][pytest] Asserting if filebeat logs include errors
  filebeat/tests/system/test_modules.py
Labels: Team:Platforms, Team:Services, [zube]: In Review, backport

#21543 [Elastic Agent] Add elastic agent ID and version to events from filebeat and metricbeat.
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/emitter.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_info.go
  x-pack/elastic-agent/pkg/agent/application/inspect_output_cmd.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/agent/application/monitoring_decorator.go
  x-pack/elastic-agent/pkg/agent/application/monitoring_decorator_test.go
  x-pack/elastic-agent/pkg/agent/program/program.go
  x-pack/elastic-agent/pkg/agent/program/program_test.go
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/pkg/agent/program/testdata/enabled_output_true-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/enabled_true-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-metricbeat.yml
  x-pack/elastic-agent/pkg/agent/transpiler/rules.go
  x-pack/elastic-agent/pkg/agent/transpiler/rules_test.go
  x-pack/elastic-agent/spec/filebeat.yml
  x-pack/elastic-agent/spec/metricbeat.yml
Labels: Team:Ingest Management

#21542 Cherry-pick #21425 to 7.x: [Elastic Agent] Add upgrade CLI to initiate upgrade of Agent locally
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/application.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_upgrade.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_mark.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade.go
  x-pack/elastic-agent/pkg/agent/cmd/common.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/cmd/upgrade.go
  x-pack/elastic-agent/pkg/agent/control/control_test.go
  x-pack/elastic-agent/pkg/agent/control/server/server.go
  x-pack/elastic-agent/pkg/basecmd/version/cmd_test.go
Labels: Team:Ingest Management, [zube]: In Review, backport

#21567 ci: add Heartbeat Packaging for Elastic Synthetics job
  .ci/heartbeat-synthetics.groovy
Labels: Team:Automation, automation, ci

#21100 feat: add a new step to run the e2e tests for certain parts of Beats
  .ci/packaging.groovy
Labels: Team:Automation

#21568 ci: add Heartbeat Packaging for Elastic Synthetics job
  .ci/heartbeat-synthetics.groovy
Labels: Team:Automation, automation, ci

#21569 ci: change to use Ubuntu-18
  .ci/heartbeat-synthetics.groovy
Labels: Team:Automation, bug, ci

#21570 ci: change to use Ubuntu-18
  .ci/heartbeat-synthetics.groovy
Labels: Team:Automation, automation, bug, ci

#21566 Cherry-pick #21543 to 7.x: [Elastic Agent] Add elastic agent ID and version to events from filebeat and metricbeat.
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/emitter.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_info.go
  x-pack/elastic-agent/pkg/agent/application/inspect_output_cmd.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/agent/application/monitoring_decorator.go
  x-pack/elastic-agent/pkg/agent/application/monitoring_decorator_test.go
  x-pack/elastic-agent/pkg/agent/program/program.go
  x-pack/elastic-agent/pkg/agent/program/program_test.go
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/pkg/agent/program/testdata/enabled_output_true-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/enabled_true-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-metricbeat.yml
  x-pack/elastic-agent/pkg/agent/transpiler/rules.go
  x-pack/elastic-agent/pkg/agent/transpiler/rules_test.go
  x-pack/elastic-agent/spec/filebeat.yml
  x-pack/elastic-agent/spec/metricbeat.yml
Labels: Team:Ingest Management, [zube]: In Review, backport

#21571 ci: use apm GCP credentials
  .ci/heartbeat-synthetics.groovy
Labels: Team:Automation, automation, bug, ci

#21556 Bump allow duplicates version check to 7.11
  filebeat/fileset/modules_integration_test.go
  filebeat/fileset/pipelines.go
  filebeat/fileset/pipelines_test.go
Labels: Team:SIEM, needs_backport, review

#21553 Cherry-pick #20017 to 7.x: junipersrx-module initial release
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/juniper.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/juniper/_meta/config.yml
  x-pack/filebeat/module/juniper/_meta/docs.asciidoc
  x-pack/filebeat/module/juniper/fields.go
  x-pack/filebeat/module/juniper/netscreen/test/generated.log-expected.json
  x-pack/filebeat/module/juniper/srx/_meta/fields.yml
  x-pack/filebeat/module/juniper/srx/config/srx.yml
  x-pack/filebeat/module/juniper/srx/ingest/atp.yml
  x-pack/filebeat/module/juniper/srx/ingest/flow.yml
  x-pack/filebeat/module/juniper/srx/ingest/idp.yml
  x-pack/filebeat/module/juniper/srx/ingest/ids.yml
  x-pack/filebeat/module/juniper/srx/ingest/pipeline.yml
  x-pack/filebeat/module/juniper/srx/ingest/secintel.yml
  x-pack/filebeat/module/juniper/srx/ingest/utm.yml
  x-pack/filebeat/module/juniper/srx/manifest.yml
  x-pack/filebeat/module/juniper/srx/test/atp.log
  x-pack/filebeat/module/juniper/srx/test/atp.log-expected.json
  x-pack/filebeat/module/juniper/srx/test/flow.log
  x-pack/filebeat/module/juniper/srx/test/flow.log-expected.json
  x-pack/filebeat/module/juniper/srx/test/idp.log
  x-pack/filebeat/module/juniper/srx/test/idp.log-expected.json
  x-pack/filebeat/module/juniper/srx/test/ids.log
  x-pack/filebeat/module/juniper/srx/test/ids.log-expected.json
  x-pack/filebeat/module/juniper/srx/test/secintel.log
  x-pack/filebeat/module/juniper/srx/test/secintel.log-expected.json
  x-pack/filebeat/module/juniper/srx/test/utm.log
  x-pack/filebeat/module/juniper/srx/test/utm.log-expected.json
  x-pack/filebeat/modules.d/juniper.yml.disabled
Labels: Team:SIEM, [zube]: In Review, backport

#21572 ci: use apm GCP credentials
  .ci/heartbeat-synthetics.groovy
Labels: Team:Automation, automation, bug, ci

#21558 Cherry-pick #21525 to 7.x: Release cloudfoundry input and processor as GA
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/cloudfoundry/input.go
  x-pack/libbeat/processors/add_cloudfoundry_metadata/docs/add_cloudfoundry_metadata.asciidoc
Labels: Team:Platforms, [zube]: In Review, backport

#21540 Add support for additional fields from V2 ALB logs
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/aws/elb/_meta/fields.yml
  x-pack/filebeat/module/aws/elb/ingest/pipeline.yml
  x-pack/filebeat/module/aws/elb/test/application-lb-http.log
  x-pack/filebeat/module/aws/elb/test/application-lb-http.log-expected.json
  x-pack/filebeat/module/aws/elb/test/example-alb-http.log
  x-pack/filebeat/module/aws/elb/test/example-alb-http.log-expected.json
  x-pack/filebeat/module/aws/fields.go
Labels: Team:Platforms, needs_backport, review

#21359 docs: Update generate_fields_docs.py
  auditbeat/docs/fields.asciidoc
  filebeat/docs/fields.asciidoc
  heartbeat/docs/fields.asciidoc
  journalbeat/docs/fields.asciidoc
  libbeat/scripts/generate_fields_docs.py
  metricbeat/docs/fields.asciidoc
  packetbeat/docs/fields.asciidoc
  winlogbeat/docs/fields.asciidoc
  x-pack/functionbeat/docs/fields.asciidoc
Labels: Team:Docs, Team:Services, Team:apm, v7.9.0

#21562 [CI] Setup git config globally
  Jenkinsfile
Labels: Team:Automation, automation, ci

#21574 Cherry-pick #21507 to 7.x: Move Prometheus query & remote_write to GA
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/prometheus/query.asciidoc
  metricbeat/docs/modules/prometheus/remote_write.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/module/prometheus/fields.go
  metricbeat/module/prometheus/query/_meta/fields.yml
  metricbeat/module/prometheus/remote_write/_meta/fields.yml
Labels: Team:Platforms, [zube]: In Review, backport

#21555 Cherry-pick #21446 to 7.x: [Filebeat][New Module] Add support for Microsoft MTP / 365 Defender
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/microsoft.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/microsoft/_meta/config.yml
  x-pack/filebeat/module/microsoft/_meta/docs.asciidoc
  x-pack/filebeat/module/microsoft/fields.go
  x-pack/filebeat/module/microsoft/m365_defender/_meta/fields.yml
  x-pack/filebeat/module/microsoft/m365_defender/config/defender.yml
  x-pack/filebeat/module/microsoft/m365_defender/ingest/pipeline.yml
  x-pack/filebeat/module/microsoft/m365_defender/manifest.yml
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log-expected.json
  x-pack/filebeat/modules.d/microsoft.yml.disabled
Labels: Team:SIEM, [zube]: In Review, backport

#21480 Add kubernetes composable inputs provider
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/include.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/config.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/kubernetes.go
Labels: Team:Ingest Management, Team:Platforms, enhancement

#21573 [Ingest Manager] Improved verify experience
  x-pack/elastic-agent/pkg/agent/application/emitter.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
  x-pack/elastic-agent/pkg/agent/operation/common_test.go
  x-pack/elastic-agent/pkg/agent/operation/operation_verify.go
  x-pack/elastic-agent/pkg/artifact/download/composed/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/fs/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/fs/verifier_test.go
  x-pack/elastic-agent/pkg/artifact/download/http/elastic_test.go
  x-pack/elastic-agent/pkg/artifact/download/http/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/verifier.go
  x-pack/elastic-agent/pkg/core/plugin/process/app.go
  x-pack/elastic-agent/pkg/core/plugin/process/start.go
Labels: Ingest Management:beta2, Team:Ingest Management, bug, enhancement

#21478 [Ingest Manager] Use new form of fleet API paths
  dev-tools/packaging/templates/docker/docker-entrypoint.elastic-agent.tmpl
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd_test.go
  x-pack/elastic-agent/pkg/fleetapi/ack_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/ack_cmd_test.go
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd_test.go
  x-pack/elastic-agent/pkg/fleetapi/enroll_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/enroll_cmd_test.go
Labels: Ingest Management:beta2, Team:Ingest Management, enhancement

#21588 Cherry-pick #21573 to 7.x: Improved verify experience
  x-pack/elastic-agent/pkg/agent/application/emitter.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
  x-pack/elastic-agent/pkg/agent/operation/common_test.go
  x-pack/elastic-agent/pkg/agent/operation/operation_verify.go
  x-pack/elastic-agent/pkg/artifact/download/composed/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/fs/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/fs/verifier_test.go
  x-pack/elastic-agent/pkg/artifact/download/http/elastic_test.go
  x-pack/elastic-agent/pkg/artifact/download/http/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/verifier.go
  x-pack/elastic-agent/pkg/core/plugin/process/app.go
  x-pack/elastic-agent/pkg/core/plugin/process/start.go
Labels: Ingest Management:beta2, Team:Ingest Management, bug, enhancement

#21585 [Filebeat][S3 Input] Add support for FIPS endpoints
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/s3/config.go
  x-pack/filebeat/input/s3/input.go
Labels: Team:Integrations, enhancement, needs_backport, review

#21498 [Metricbeat] Use timestamp from CloudWatch for events
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/aws.go
  x-pack/metricbeat/module/aws/billing/billing.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/ec2/ec2.go
  x-pack/metricbeat/module/aws/rds/rds.go
  x-pack/metricbeat/module/aws/s3_daily_storage/s3_daily_storage.go
  x-pack/metricbeat/module/aws/s3_request/s3_request.go
  x-pack/metricbeat/module/aws/sqs/sqs.go
Labels: Team:Platforms, needs_backport, review

#21586 Cherry-pick #21480 to 7.x: Add kubernetes composable inputs provider
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/include.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/config.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/kubernetes.go
Labels: Team:Ingest Management, Team:Platforms, [zube]: In Review, backport

#21595 Cherry-pick #21498 to 7.x: [Metricbeat] Use timestamp from CloudWatch for events
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/aws.go
  x-pack/metricbeat/module/aws/billing/billing.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/ec2/ec2.go
  x-pack/metricbeat/module/aws/rds/rds.go
  x-pack/metricbeat/module/aws/s3_daily_storage/s3_daily_storage.go
  x-pack/metricbeat/module/aws/s3_request/s3_request.go
  x-pack/metricbeat/module/aws/sqs/sqs.go
Labels: Team:Platforms, [zube]: In Review, backport

#21589 Cherry-pick #21478 to 7.x: Use new form of fleet API paths
  dev-tools/packaging/templates/docker/docker-entrypoint.elastic-agent.tmpl
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd_test.go
  x-pack/elastic-agent/pkg/fleetapi/ack_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/ack_cmd_test.go
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd_test.go
  x-pack/elastic-agent/pkg/fleetapi/enroll_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/enroll_cmd_test.go
Labels: Ingest Management:beta2, Team:Ingest Management, enhancement

#20395 Update timestamp.asciidoc
  libbeat/processors/timestamp/docs/timestamp.asciidoc
Labels: Team:Services, docs

#21584 Cherry-pick to 7.x: [CI] Setup git config globally (#21562)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#21583 Cherry-pick to 7.9: [CI] Setup git config globally (#21562)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#21608 [E2E Tests] fix: set versions ony for PRs
  .ci/packaging.groovy
Labels: Team:Automation

#21622 Fix docs version in 7.10 branch
  filebeat/modules.d/iis.yml.disabled
  libbeat/docs/version.asciidoc
Labels: Team:Automation, bug

#21501 Add `add_observer_metadata` `geo.name` to Quickstart
  heartbeat/docs/getting-started.asciidoc
Labels: Team:Docs, docs

#21559 [CI] Change notification channel
  Jenkinsfile
Labels: Team:Automation, automation

#21624 [Filebeat S3] Change log.file.path to be nested object
  x-pack/filebeat/input/s3/collector.go
Labels: Team:Platforms, needs_backport, review

#21626 [Filebeat] Add fips_enabled into all aws filesets
  x-pack/filebeat/module/aws/cloudtrail/config/s3.yml
  x-pack/filebeat/module/aws/cloudwatch/config/s3.yml
  x-pack/filebeat/module/aws/ec2/config/s3.yml
  x-pack/filebeat/module/aws/elb/config/s3.yml
  x-pack/filebeat/module/aws/s3access/config/s3.yml
  x-pack/filebeat/module/aws/vpcflow/config/input.yml
Labels: Team:Platforms, needs_backport

#21639 Cherry-pick to 7.x: Add `add_observer_metadata` `geo.name` to Quickstart (#21501)
  heartbeat/docs/getting-started.asciidoc
Labels: backport, needs_team

#21638 Cherry-pick to 7.9: Add `add_observer_metadata` `geo.name` to Quickstart (#21501)
  heartbeat/docs/getting-started.asciidoc
Labels: backport, needs_team

#21594 Cherry-pick #21585 to 7.x: [Filebeat][S3 Input] Add support for FIPS endpoints
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/s3/config.go
  x-pack/filebeat/input/s3/input.go
Labels: Team:Integrations, [zube]: In Review, backport

#21590 Add openstack ssl provider in add_cloud_metadata
  CHANGELOG.next.asciidoc
  libbeat/processors/add_cloud_metadata/add_cloud_metadata.go
  libbeat/processors/add_cloud_metadata/config.go
  libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc
  libbeat/processors/add_cloud_metadata/http_fetcher.go
  libbeat/processors/add_cloud_metadata/provider_openstack_nova.go
  libbeat/processors/add_cloud_metadata/provider_openstack_nova_test.go
  libbeat/processors/add_cloud_metadata/providers.go
Labels: Team:Platforms, enhancement, needs_backport, v7.11.0

#21637 Cherry-pick #21626 to 7.x: [Filebeat] Add fips_enabled into all aws filesets
  x-pack/filebeat/module/aws/cloudtrail/config/s3.yml
  x-pack/filebeat/module/aws/cloudwatch/config/s3.yml
  x-pack/filebeat/module/aws/ec2/config/s3.yml
  x-pack/filebeat/module/aws/elb/config/s3.yml
  x-pack/filebeat/module/aws/s3access/config/s3.yml
  x-pack/filebeat/module/aws/vpcflow/config/input.yml
Labels: Team:Platforms, [zube]: In Review, backport

#21636 Cherry-pick #21624 to 7.x: [Filebeat S3] Change log.file.path to be nested object
  x-pack/filebeat/input/s3/collector.go
Labels: Team:Platforms, [zube]: In Review, backport

#21633 Cherry-pick to 7.9: [CI] cherry-pick #20891 (#21314)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#21634 Cherry-pick to 7.x: [CI] cherry-pick #20891 (#21314)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#21632 Cherry-pick to 7.x: [CI] Change notification channel (#21559)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#21629 Bump version to 7.11.0
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
  libbeat/version/version.go
Labels: Team:Automation, Team:Integrations

#21643 [Filebeat][Cyberark] Fix cyberark/corepas pipeline
  x-pack/filebeat/module/cyberark/corepas/ingest/pipeline.yml
  x-pack/filebeat/module/cyberark/corepas/test/generated.log-expected.json
Labels: Team:SIEM, bug

#21641 Cherry-pick #21585 to 7.10: [Filebeat][S3 Input] Add support for FIPS endpoints
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/s3/config.go
  x-pack/filebeat/input/s3/input.go
Labels: Team:Integrations, [zube]: In Review, backport

#21642 Cherry-pick #21626 to 7.10: [Filebeat] Add fips_enabled into all aws filesets
  x-pack/filebeat/module/aws/cloudtrail/config/s3.yml
  x-pack/filebeat/module/aws/cloudwatch/config/s3.yml
  x-pack/filebeat/module/aws/ec2/config/s3.yml
  x-pack/filebeat/module/aws/elb/config/s3.yml
  x-pack/filebeat/module/aws/s3access/config/s3.yml
  x-pack/filebeat/module/aws/vpcflow/config/input.yml
Labels: Team:Platforms, [zube]: In Review, backport

#21650 Cherry-pick to 7.9: [CI] Change notification channel (#21559)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#21649 Cherry-pick to 7.10: [CI] Change notification channel (#21559)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#21654 Cherry-pick #21643 to 7.x: [Filebeat][Cyberark] Fix cyberark/corepas pipeline
  x-pack/filebeat/module/cyberark/corepas/ingest/pipeline.yml
  x-pack/filebeat/module/cyberark/corepas/test/generated.log-expected.json
Labels: Team:SIEM, [zube]: In Review, backport

#21655 Cherry-pick #21643 to 7.10: [Filebeat][Cyberark] Fix cyberark/corepas pipeline
  x-pack/filebeat/module/cyberark/corepas/ingest/pipeline.yml
  x-pack/filebeat/module/cyberark/corepas/test/generated.log-expected.json
Labels: Team:SIEM, [zube]: In Review, backport

#21580 Cherry-pick to 7.x: docs: update generate_fields_docs.py (#21359)
  auditbeat/docs/fields.asciidoc
  filebeat/docs/fields.asciidoc
  heartbeat/docs/fields.asciidoc
  journalbeat/docs/fields.asciidoc
  libbeat/scripts/generate_fields_docs.py
  metricbeat/docs/fields.asciidoc
  packetbeat/docs/fields.asciidoc
  winlogbeat/docs/fields.asciidoc
  x-pack/functionbeat/docs/fields.asciidoc
Labels: Team:Docs, backport

#21599 [Elastic Agent] Reload fleet.kibana.hosts from policy change
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/fleet_acker.go
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_policy_change.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_policy_change_test.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/agent/storage/storage.go
Labels: Team:Ingest Management

#21579 Cherry-pick #21540 to 7.x: Add support for additional fields from V2 ALB logs
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/aws/elb/_meta/fields.yml
  x-pack/filebeat/module/aws/elb/ingest/pipeline.yml
  x-pack/filebeat/module/aws/elb/test/application-lb-http.log
  x-pack/filebeat/module/aws/elb/test/application-lb-http.log-expected.json
  x-pack/filebeat/module/aws/elb/test/example-alb-http.log
  x-pack/filebeat/module/aws/elb/test/example-alb-http.log-expected.json
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/module/zscaler/zia/test/generated.log-expected.json
  x-pack/filebeat/module/zscaler/zia/test/test.log-expected.json
Labels: Team:Platforms, [zube]: In Review, backport

#21670 chore: add versions 7.1x
  .ci/jobs/apm-beats-update.yml
  .ci/jobs/beats.yml
  .ci/jobs/packaging.yml
Labels: Team:Automation, automation, ci

#21625 Fix flaky FSWatch/FSScanner tests
  filebeat/input/filestream/fswatch_test.go
  filebeat/input/filestream/fswatch_test_non_windows.go
Labels: Team:Services, needs_backport, v7.10.0, v7.11.0

#21587 Docker build resiliance with a retry
  dev-tools/mage/integtest_docker.go
Labels: Team:Automation, Team:Integrations, [zube]: In Review, automation

#21675 Cherry-pick to 7.10: [CI] Setup git config globally (#21562)
  Jenkinsfile
Labels: Team:Automation, automation, backport

#21621 [CI: Packaging] fix: push ubi8 images too
  .ci/packaging.groovy
Labels: Team:Automation, [zube]: Inbox

#21635 backport: add 7.10 branch
  .backportrc.json
Labels: Team:Automation, [zube]: Inbox

#21657 Skip publisher flaky tests
  libbeat/publisher/pipeline/controller_test.go
  libbeat/publisher/pipeline/output_test.go
Labels: Team:Services, bug, flaky-test, libbeat

#21677 Cherry-pick #21625 to 7.10: Fix flaky FSWatch/FSScanner tests
  filebeat/input/filestream/fswatch_test.go
  filebeat/input/filestream/fswatch_test_non_windows.go
Labels: Team:Services, [zube]: In Review, backport

#21676 Cherry-pick #21625 to 7.x: Fix flaky FSWatch/FSScanner tests
  filebeat/input/filestream/fswatch_test.go
  filebeat/input/filestream/fswatch_test_non_windows.go
Labels: Team:Services, [zube]: In Review, backport
