Repository elastic/beats, pull requests merged in 2020-09, with the labels that each got.

#20721 docs: Add `processor.event` info to Logstash output
  libbeat/outputs/logstash/docs/logstash.asciidoc
Labels: Team:Docs, docs, v7.9.0

#20857 feat: update test environments for 7.9.1
  testing/environments/latest.yml
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: Team:Automation, [zube]: In Review, automation, release

#20627 Ensure kind cluster has RFC1123 compliant name
  dev-tools/mage/kubernetes/kind.go
  dev-tools/mage/kubernetes/kubernetes.go
Labels: Team:Platforms, bug

#20867 [Filebeat][zeek] Add new x509 fields to zeek
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/zeek/x509/ingest/pipeline.yml
  x-pack/filebeat/module/zeek/x509/test/x509-json.log-expected.json
Labels: Team:SIEM, ecs, enhancement, review, v7.1.0

#20649 Kubernetes state_daemonset metricset for Metricbeat
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/docs/modules/kubernetes/state_daemonset.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_docker.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_daemonset/_meta/data.json
  metricbeat/module/kubernetes/state_daemonset/_meta/docs.asciidoc
  metricbeat/module/kubernetes/state_daemonset/_meta/fields.yml
  metricbeat/module/kubernetes/state_daemonset/_meta/test/ksm.v1.3.0.expected
  metricbeat/module/kubernetes/state_daemonset/_meta/test/ksm.v1.8.0.expected
  metricbeat/module/kubernetes/state_daemonset/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_daemonset/_meta/testdata/docs.plain
  metricbeat/module/kubernetes/state_daemonset/_meta/testdata/docs.plain-expected.json
  metricbeat/module/kubernetes/state_daemonset/state_daemonset.go
  metricbeat/module/kubernetes/state_daemonset/state_daemonset_integration_test.go
  metricbeat/module/kubernetes/state_daemonset/state_daemonset_test.go
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Platforms, enhancement, needs_backport, v7.10.0

#20899 Bump kibana version to 7.9.0 in x-pack/metricbeat
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Platforms, review

#20879 Cherry-pick to 7.9: docs: update cipher suites (#20697)
  libbeat/docs/shared-ssl-config.asciidoc
Labels: Team:Docs, backport

#20880 Cherry-pick to 7.x: docs: update cipher suites (#20697)
  libbeat/docs/shared-ssl-config.asciidoc
Labels: Team:Docs, backport

#20882 Cherry-pick to 7.9: docs: Add `processor.event` info to Logstash output (#20721)
  libbeat/outputs/logstash/docs/logstash.asciidoc
Labels: Team:Docs, backport

#20883 Cherry-pick to 7.x: docs: Add `processor.event` info to Logstash output (#20721)
  libbeat/outputs/logstash/docs/logstash.asciidoc
Labels: Team:Docs, backport

#20884 Adding cborbeat to community beats
  libbeat/docs/communitybeats.asciidoc
Labels: Team:Docs, Team:Services

#20881 docs: Update beats for APM
  libbeat/docs/howto/load-index-templates.asciidoc
  libbeat/docs/shared/configuring-intro.asciidoc
Labels: Team:Docs, v7.9.0

#20874 Document how to set the ES host and Kibana URLs in Ingest Manager
  x-pack/elastic-agent/docs/run-elastic-agent.asciidoc
Labels: Team:Ingest Management, docs, needs_backport, review, v7.10.0, v7.9.0, v8.0.0

#20601 Improve docs of leaderelection configuration
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  deploy/kubernetes/metricbeat/metricbeat-deployment-configmap.yaml
  deploy/kubernetes/metricbeat/metricbeat-deployment.yaml
  metricbeat/docs/running-on-kubernetes.asciidoc
Labels: Team:Platforms, needs_backport, v7.10.0

#20898 Avoid generating incomplete configurations in autodiscover
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/template/config.go
  libbeat/autodiscover/template/config_test.go
Labels: Team:Platforms, needs_backport, review, v7.10.0

#20896 Cherry-pick #20867 to 7.x: [Filebeat][zeek] Add new x509 fields to zeek
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/zeek/x509/ingest/pipeline.yml
  x-pack/filebeat/module/zeek/x509/test/x509-json.log-expected.json
Labels: Team:SIEM, [zube]: In Review, backport

#20917 Include python docs in devguide index
  docs/devguide/index.asciidoc
  docs/devguide/python.asciidoc
Labels: Team:Docs, Team:Integrations, needs_backport, review

#20916 Cherry-pick #20601 to 7.x: Improve docs of leaderelection configuration
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  deploy/kubernetes/metricbeat/metricbeat-deployment-configmap.yaml
  deploy/kubernetes/metricbeat/metricbeat-deployment.yaml
  metricbeat/docs/running-on-kubernetes.asciidoc
Labels: Team:Platforms, [zube]: In Review, backport

#20921 Cherry-pick #20917 to 7.x: Include python docs in devguide index
  docs/devguide/index.asciidoc
  docs/devguide/python.asciidoc
Labels: Team:Docs, Team:Integrations, [zube]: In Review, backport

#20922 Cherry-pick #20917 to 7.9: Include python docs in devguide index
  docs/devguide/index.asciidoc
  docs/devguide/python.asciidoc
Labels: Team:Docs, Team:Integrations, [zube]: In Review, backport

#20903 [packaging] Normalise GCP bucket folder structure
  .ci/packaging.groovy
Labels: :Packaging, Team:Automation, automation

#20449 [Ingest Manager] Remove Success from fleet contract
  x-pack/elastic-agent/dev-tools/cmd/fakewebapi/action_example.json
  x-pack/elastic-agent/dev-tools/cmd/fakewebapi/main.go
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd_test.go
  x-pack/elastic-agent/pkg/agent/application/fleet_acker_test.go
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway_test.go
  x-pack/elastic-agent/pkg/agent/application/lazy_acker_test.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/fleetapi/ack_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/ack_cmd_test.go
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd_test.go
  x-pack/elastic-agent/pkg/fleetapi/enroll_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/enroll_cmd_test.go
Labels: Team:Ingest Management, enhancement, review

#20838 Cherry-pick #20827 to 7.9: [Build] Make mage-linux-amd64 statically compiled.
  CHANGELOG-developer.next.asciidoc
  dev-tools/mage/crossbuild.go
Labels: Team:Platforms, Team:Services, [zube]: In Review, backport

#20915 [Autodiscover] Handle input-not-finished errors in config reload
  CHANGELOG.next.asciidoc
  filebeat/input/log/input.go
  filebeat/input/runnerfactory.go
  libbeat/cfgfile/list.go
  libbeat/common/errors.go
Labels: Team:Platforms, [zube]: In Review, autodiscovery, bug, needs_backport, review, v7.10.0

#20925 Cherry-pick to 7.x: [packaging] Normalise GCP bucket folder structure (#20903)
  .ci/packaging.groovy
Labels: Team:Automation, automation, backport, ci

#20924 Cherry-pick to 7.9: [packaging] Normalise GCP bucket folder structure (#20903)
  .ci/packaging.groovy
Labels: Team:Automation, automation, backport, ci

#20930 [CI] fix regression with variable name
  .ci/packaging.groovy
Labels: Team:Automation, automation

#20932 Cherry-pick to 7.9: [CI] fix regression with variable name (#20930)
  .ci/packaging.groovy
Labels: Team:Automation, automation, backport, ci

#20933 Cherry-pick to 7.x: [CI] fix regression with variable name (#20930)
  .ci/packaging.groovy
Labels: Team:Automation, automation, backport, ci

#20934 fix: update test environment 7.9.1
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Automation, automation, bug, ci

#20940 fix: make update revert some changes
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
Labels: Team:Automation, automation, bug, ci

#20909 Cherry-pick to 7.9: Document how to set the ES host and Kibana URLs in Ingest Manager (#20874)
  x-pack/elastic-agent/docs/run-elastic-agent.asciidoc
Labels: Team:Ingest Management, backport, docs, v7.9.0

#20910 Cherry-pick to 7.x: Document how to set the ES host and Kibana URLs in Ingest Manager (#20874)
  x-pack/elastic-agent/docs/run-elastic-agent.asciidoc
Labels: Team:Ingest Management, backport, docs

#20927 [Filebeat][zeek] Map new x509 fields for ssl module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/zeek/ssl/ingest/pipeline.yml
  x-pack/filebeat/module/zeek/ssl/test/ssl-json.log-expected.json
Labels: Team:SIEM, ecs, enhancement, review

#20952 [Ingest Manager] Align introspect-inspect naming in code
  x-pack/elastic-agent/docs/elastic-agent-command-line.asciidoc
  x-pack/elastic-agent/pkg/agent/application/inspect_config_cmd.go
  x-pack/elastic-agent/pkg/agent/application/inspect_output_cmd.go
  x-pack/elastic-agent/pkg/agent/cmd/common.go
  x-pack/elastic-agent/pkg/agent/cmd/inspect.go
Labels: Team:Ingest Management

#20942 Skip flaky test on unix input
  filebeat/tests/system/test_unix.py
Labels: Team:Integrations, flaky-test, needs_backport

#20900 Cherry-pick #20649 to 7.x: Kubernetes state_daemonset metricset for Metricbeat
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/docs/modules/kubernetes/state_daemonset.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_docker.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_daemonset/_meta/data.json
  metricbeat/module/kubernetes/state_daemonset/_meta/docs.asciidoc
  metricbeat/module/kubernetes/state_daemonset/_meta/fields.yml
  metricbeat/module/kubernetes/state_daemonset/_meta/test/ksm.v1.3.0.expected
  metricbeat/module/kubernetes/state_daemonset/_meta/test/ksm.v1.8.0.expected
  metricbeat/module/kubernetes/state_daemonset/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_daemonset/_meta/testdata/docs.plain
  metricbeat/module/kubernetes/state_daemonset/_meta/testdata/docs.plain-expected.json
  metricbeat/module/kubernetes/state_daemonset/state_daemonset.go
  metricbeat/module/kubernetes/state_daemonset/state_daemonset_integration_test.go
  metricbeat/module/kubernetes/state_daemonset/state_daemonset_test.go
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Platforms, [zube]: In Review, backport

#20919 Cherry-pick #20898 to 7.x: Avoid generating incomplete configurations in autodiscover
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/template/config.go
  libbeat/autodiscover/template/config_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#20955 Cherry-pick #20942 to 7.x: Skip flaky test on unix input
  filebeat/tests/system/test_unix.py
Labels: Team:Integrations, [zube]: In Review, backport

#20948 [Ingest Manager] Print a message confirming shutdown
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/control/server/listener.go
Labels: Team:Ingest Management, enhancement

#20400 [Ingest Manager] New agent structure (symlinks)
  dev-tools/mage/dmgbuilder.go
  dev-tools/mage/pkgtypes.go
  dev-tools/mage/settings.go
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/darwin/scripts/postinstall.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  x-pack/elastic-agent/pkg/agent/application/paths/paths.go
  x-pack/elastic-agent/pkg/agent/application/reexec/manager.go
  x-pack/elastic-agent/pkg/agent/application/reexec/reexec.go
  x-pack/elastic-agent/pkg/agent/application/reexec/reexec_windows.go
  x-pack/elastic-agent/pkg/agent/cmd/checks.go
  x-pack/elastic-agent/pkg/agent/cmd/checks_windows.go
  x-pack/elastic-agent/pkg/agent/cmd/common.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
  x-pack/elastic-agent/pkg/artifact/config.go
  x-pack/elastic-agent/pkg/artifact/download/fs/downloader.go
  x-pack/elastic-agent/pkg/artifact/download/fs/verifier.go
  x-pack/elastic-agent/pkg/core/logger/logger.go
  x-pack/elastic-agent/pkg/core/monitoring/beats/monitoring.go
  x-pack/elastic-agent/pkg/core/plugin/process/start.go
  x-pack/heartbeat/magefile.go
Labels: Team:Ingest Management

#20928 Cherry-pick #20915 to 7.x: [Autodiscover] Handle input-not-finished errors in config reload
  CHANGELOG.next.asciidoc
  filebeat/input/log/input.go
  filebeat/input/runnerfactory.go
  libbeat/cfgfile/list.go
  libbeat/common/errors.go
Labels: Team:Platforms, [zube]: In Review, backport

#20873 docs: update docs versions 7.9.1
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: Team:Automation, automation, docs, in progress, release

#20938 Only request wildcard expansion for hidden indices if supported
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/index/index.go
  metricbeat/module/elasticsearch/index/index_test.go
Labels: Metricbeat, Stack monitoring, Team:Services, [zube]: In Review, bug, module, needs_backport, v7.9.2, v8.0.0

#20839 [Elastic Agent] Add support for variable replacement from providers
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/application.go
  x-pack/elastic-agent/pkg/agent/application/config.go
  x-pack/elastic-agent/pkg/agent/application/config_test.go
  x-pack/elastic-agent/pkg/agent/application/emitter.go
  x-pack/elastic-agent/pkg/agent/application/emitter_test.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_policy_change.go
  x-pack/elastic-agent/pkg/agent/application/inspect_config_cmd.go
  x-pack/elastic-agent/pkg/agent/application/inspect_output_cmd.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
  x-pack/elastic-agent/pkg/agent/cmd/include.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/transpiler/ast.go
  x-pack/elastic-agent/pkg/agent/transpiler/ast_test.go
  x-pack/elastic-agent/pkg/agent/transpiler/vars.go
  x-pack/elastic-agent/pkg/agent/transpiler/vars_test.go
  x-pack/elastic-agent/pkg/composable/controller.go
  x-pack/elastic-agent/pkg/composable/controller_test.go
  x-pack/elastic-agent/pkg/composable/providers/localdynamic/localdynamic.go
  x-pack/elastic-agent/pkg/composable/providers/localdynamic/localdynamic_test.go
  x-pack/elastic-agent/pkg/composable/providers/path/path.go
  x-pack/elastic-agent/pkg/composable/providers/path/path_test.go
  x-pack/elastic-agent/pkg/config/config.go
Labels: Team:Ingest Management

#20959 [Metricbeat][test] Disable ec2 flaky test
  x-pack/metricbeat/module/aws/ec2/ec2_integration_test.go
Labels: Team:Integrations, flaky-test

#20929 Clarify use for shared_credential_file
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Docs, docs

#20935 fix: update test environments
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Automation, automation, bug, ci

#20901 Release Kubernetes state metricsets as GA
  CHANGELOG.next.asciidoc
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  metricbeat/docs/modules/kubernetes/state_daemonset.asciidoc
  metricbeat/docs/modules/kubernetes/state_persistentvolumeclaim.asciidoc
  metricbeat/docs/modules/kubernetes/state_service.asciidoc
  metricbeat/docs/modules/kubernetes/state_storageclass.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_daemonset/_meta/fields.yml
  metricbeat/module/kubernetes/state_persistentvolume/_meta/fields.yml
  metricbeat/module/kubernetes/state_persistentvolumeclaim/_meta/fields.yml
  metricbeat/module/kubernetes/state_service/_meta/fields.yml
  metricbeat/module/kubernetes/state_storageclass/_meta/fields.yml
Labels: Team:Platforms, needs_backport, v7.10.0

#20871 docs: Update docs to 7.9.2
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: Team:Automation, automation, docs, release

#20869 feat: Update version to 7.9.2
  libbeat/version/version.go
Labels: Team:Automation, automation, release

#20966 Cherry-pick #20901 to 7.x: Release Kubernetes state metricsets as GA
  CHANGELOG.next.asciidoc
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  metricbeat/docs/modules/kubernetes/state_daemonset.asciidoc
  metricbeat/docs/modules/kubernetes/state_persistentvolumeclaim.asciidoc
  metricbeat/docs/modules/kubernetes/state_service.asciidoc
  metricbeat/docs/modules/kubernetes/state_storageclass.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_daemonset/_meta/fields.yml
  metricbeat/module/kubernetes/state_persistentvolume/_meta/fields.yml
  metricbeat/module/kubernetes/state_persistentvolumeclaim/_meta/fields.yml
  metricbeat/module/kubernetes/state_service/_meta/fields.yml
  metricbeat/module/kubernetes/state_storageclass/_meta/fields.yml
Labels: Team:Platforms, [zube]: In Review, backport

#20908 [Filebeat] backwards compatibility for set processor
  CHANGELOG.next.asciidoc
  filebeat/fileset/pipelines.go
  filebeat/fileset/pipelines_test.go
Labels: Filebeat, Team:SIEM, bug, needs_backport

#20957 Cherry-pick #20948 to 7.x: Print a message confirming shutdown
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/control/server/listener.go
Labels: Team:Ingest Management, backport, enhancement

#20949 Cherry-pick #20927 to 7.x: [Filebeat][zeek] Map new x509 fields for ssl module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/zeek/ssl/ingest/pipeline.yml
  x-pack/filebeat/module/zeek/ssl/test/ssl-json.log-expected.json
Labels: Team:SIEM, [zube]: In Review, backport

#20958 [Filebeat][zeek] Add mappings for x509 fields in kerberos
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/zeek/kerberos/ingest/pipeline.yml
  x-pack/filebeat/module/zeek/kerberos/test/kerberos-json.log
  x-pack/filebeat/module/zeek/kerberos/test/kerberos-json.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, review

#20870 feat: Update test environments 7.9.2
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: Team:Automation, automation, release

#20920 Cherry-pick #20898 to 7.9: Avoid generating incomplete configurations in autodiscover
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/template/config.go
  libbeat/autodiscover/template/config_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#20968 Skip flaky test for prometheus remote write
  metricbeat/module/prometheus/test_prometheus.py
Labels: Team:Platforms, flaky-test, review

#20979 Cherry-pick #20968 to 7.x: Skip flaky test for prometheus remote write
  metricbeat/module/prometheus/test_prometheus.py
Labels: Team:Platforms, [zube]: In Review, backport

#20987 Change version of unused dependencies in go.mod to support Go 1.13
  go.mod
Labels: Team:Services, [zube]: In Review, needs_backport

#20975 Cherry-pick #20958 to 7.x: [Filebeat][zeek] Add mappings for x509 fields in kerberos
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/zeek/kerberos/ingest/pipeline.yml
  x-pack/filebeat/module/zeek/kerberos/test/kerberos-json.log
  x-pack/filebeat/module/zeek/kerberos/test/kerberos-json.log-expected.json
Labels: Team:SIEM, [zube]: In Review, backport

#20986 [Ingest Manager] Fix DEB\RPM packages
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/linux/elastic-agent.sh.tmpl
  dev-tools/packaging/templates/linux/elastic-agent.unit.tmpl
  x-pack/elastic-agent/pkg/agent/application/paths/paths.go
Labels: Team:Ingest Management, bug

#20926 Use go install to install tools from go modules
  dev-tools/mage/install.go
  libbeat/scripts/Makefile
Labels: :Testing, Team:Automation, Team:Integrations, needs_backport

#20947 Cherry-pick #20449 to 7.x: Remove Success from fleet contract
  x-pack/elastic-agent/dev-tools/cmd/fakewebapi/action_example.json
  x-pack/elastic-agent/dev-tools/cmd/fakewebapi/main.go
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd_test.go
  x-pack/elastic-agent/pkg/agent/application/fleet_acker_test.go
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway_test.go
  x-pack/elastic-agent/pkg/agent/application/lazy_acker_test.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/fleetapi/ack_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/ack_cmd_test.go
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd_test.go
  x-pack/elastic-agent/pkg/fleetapi/enroll_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/enroll_cmd_test.go
Labels: Team:Ingest Management, backport, enhancement, review

#20918 Update fields.yml in azure module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/azure/_meta/fields.yml
  x-pack/metricbeat/module/azure/fields.go
  x-pack/metricbeat/module/azure/monitor/_meta/fields.yml
Labels: Team:Platforms, [zube]: In Review, needs_backport

#20954 Cherry-pick #20952 to 7.x: Align introspect-inspect naming in code
  x-pack/elastic-agent/docs/elastic-agent-command-line.asciidoc
  x-pack/elastic-agent/pkg/agent/application/inspect_config_cmd.go
  x-pack/elastic-agent/pkg/agent/application/inspect_output_cmd.go
  x-pack/elastic-agent/pkg/agent/cmd/common.go
  x-pack/elastic-agent/pkg/agent/cmd/inspect.go
Labels: Team:Ingest Management, backport

#20891 ci: configure retries on tests
  Jenkinsfile
  libbeat/tests/system/requirements.txt
Labels: Team:Automation, [zube]: In Review, automation, ci

#21006 Cherry-pick to 7.x: docs: update changelog 7.9.1 (#20953)
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Automation, automation, backport

#21005 [CI]fix: APM Beats Update job
  .ci/apm-beats-update.groovy
Labels: Team:Automation, [zube]: In Review, automation, bug

#20889 Make compute_vm light metricset and add update cloud instance id
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/azure/compute_vm.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-billing-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-blob-storage-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-container-instance-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-container-registry-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-container-service-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-database-account-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-file-storage-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-queue-storage-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-storage-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-table-storage-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-vm-guestmetrics-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-vm-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-vmss-overview.json
  x-pack/metricbeat/module/azure/add_metadata.go
  x-pack/metricbeat/module/azure/azure.go
  x-pack/metricbeat/module/azure/client.go
  x-pack/metricbeat/module/azure/client_test.go
  x-pack/metricbeat/module/azure/client_utils.go
  x-pack/metricbeat/module/azure/client_utils_test.go
  x-pack/metricbeat/module/azure/compute_vm/_meta/data.json
  x-pack/metricbeat/module/azure/compute_vm/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/compute_vm/client_helper.go
  x-pack/metricbeat/module/azure/compute_vm/client_helper_test.go
  x-pack/metricbeat/module/azure/compute_vm/compute_vm.go
  x-pack/metricbeat/module/azure/compute_vm/compute_vm_integration_test.go
  x-pack/metricbeat/module/azure/compute_vm/compute_vm_test.go
  x-pack/metricbeat/module/azure/compute_vm/manifest.yml
  x-pack/metricbeat/module/azure/compute_vm_scaleset/_meta/data.json
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper_test.go
  x-pack/metricbeat/module/azure/config.go
  x-pack/metricbeat/module/azure/container_instance/_meta/data.json
  x-pack/metricbeat/module/azure/container_registry/_meta/data.json
  x-pack/metricbeat/module/azure/container_service/_meta/data.json
  x-pack/metricbeat/module/azure/data.go
  x-pack/metricbeat/module/azure/data_test.go
  x-pack/metricbeat/module/azure/database_account/_meta/data.json
  x-pack/metricbeat/module/azure/database_account/database_account_integration_test.go
  x-pack/metricbeat/module/azure/mock_service.go
  x-pack/metricbeat/module/azure/module.yml
  x-pack/metricbeat/module/azure/monitor/_meta/data.json
  x-pack/metricbeat/module/azure/monitor/client_helper.go
  x-pack/metricbeat/module/azure/monitor/client_helper_test.go
  x-pack/metricbeat/module/azure/monitor_service.go
  x-pack/metricbeat/module/azure/monitor_service_test.go
  x-pack/metricbeat/module/azure/resources.go
  x-pack/metricbeat/module/azure/storage/client_helper.go
  x-pack/metricbeat/module/azure/storage/client_helper_test.go
Labels: Team:Platforms, [zube]: In Review, needs_backport

#20995 Cherry-pick #20926 to 7.x: Use go install to install tools from go modules
  dev-tools/mage/install.go
  libbeat/scripts/Makefile
Labels: Team:Automation, Team:Integrations, [zube]: In Review, backport

#20603 Fix python deprecation warnings
  Jenkinsfile
  Makefile
  auditbeat/tests/system/test_file_integrity.py
  dev-tools/cmd/dashboards/export_5x_dashboards.py
  filebeat/scripts/docs_collector.py
  filebeat/tests/open-file-handlers/log_stdout.py
  filebeat/tests/system/filebeat.py
  filebeat/tests/system/test_container.py
  filebeat/tests/system/test_modules.py
  filebeat/tests/system/test_multiline.py
  filebeat/tests/system/test_pipeline.py
  filebeat/tests/system/test_registrar.py
  filebeat/tests/system/test_setup.py
  heartbeat/scripts/generate_imports_helper.py
  heartbeat/tests/system/test_base.py
  heartbeat/tests/system/test_telemetry.py
  libbeat/scripts/generate_makefile_doc.py
  libbeat/tests/system/beat/beat.py
  libbeat/tests/system/beat/common_tests.py
  libbeat/tests/system/beat/compose.py
  libbeat/tests/system/requirements.txt
  libbeat/tests/system/test_cmd_setup_index_management.py
  libbeat/tests/system/test_monitoring.py
  metricbeat/module/elasticsearch/test_elasticsearch.py
  metricbeat/module/system/test_system.py
  metricbeat/module/uwsgi/test_uwsgi.py
  metricbeat/tests/system/metricbeat.py
  metricbeat/tests/system/test_cmd.py
  packetbeat/tests/system/test_0012_http_basicauth.py
  pytest.ini
  winlogbeat/tests/system/winlogbeat.py
  x-pack/auditbeat/tests/system/test_system_socket.py
  x-pack/functionbeat/tests/system/test_base.py
  x-pack/libbeat/tests/system/test_management.py
Labels: :Testing, Team:Automation, Team:Integrations, technical debt

#20840 Flaky TestConfigurableService disable test
  x-pack/elastic-agent/pkg/agent/operation/operator_test.go
Labels: Team:Ingest Management, [zube]: In Review, review

#21008 Cherry-pick #20400 to 7.x: Flaky TestConfigurableService disable test (#20840)
  x-pack/elastic-agent/pkg/agent/operation/operator_test.go
Labels: Agent, Team:Ingest Management, backport, review

#21004 [Filebeat][Sophos] Docs YAML example for serial number mapping fixes
  filebeat/docs/modules/sophos.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/sophos/_meta/config.yml
  x-pack/filebeat/module/sophos/_meta/docs.asciidoc
  x-pack/filebeat/modules.d/sophos.yml.disabled
Labels: Filebeat, Team:SIEM, enhancement

#20962 Cherry-pick to 7.9: Only request wildcard expansion for hidden indices if supported (#20938)
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/index/index.go
  metricbeat/module/elasticsearch/index/index_test.go
Labels: Team:Services, backport

#21009 Cherry-pick #21004 to 7.x: [Filebeat][Sophos] Docs YAML example for serial number mapping fixes
  filebeat/docs/modules/sophos.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/sophos/_meta/config.yml
  x-pack/filebeat/module/sophos/_meta/docs.asciidoc
  x-pack/filebeat/modules.d/sophos.yml.disabled
Labels: Team:SIEM, [zube]: In Review, backport

#21003 [Filebeat][zeek] Bump zeek kerberos/ssl/x509 ecs version
  x-pack/filebeat/module/zeek/kerberos/config/kerberos.yml
  x-pack/filebeat/module/zeek/ssl/config/ssl.yml
  x-pack/filebeat/module/zeek/x509/config/x509.yml
Labels: Team:SIEM, ecs, enhancement, review

#20983 [Filebeat][fortinet] Map x509 ecs fields for fortinet fw fileset
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/fortinet/fields.go
  x-pack/filebeat/module/fortinet/firewall/_meta/fields.yml
  x-pack/filebeat/module/fortinet/firewall/config/firewall.yml
  x-pack/filebeat/module/fortinet/firewall/ingest/utm.yml
  x-pack/filebeat/module/fortinet/firewall/test/fortinet.log
  x-pack/filebeat/module/fortinet/firewall/test/fortinet.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, review

#20976 [Filebeat][santa] Map x509 fields in santa module
  CHANGELOG.next.asciidoc
  filebeat/module/santa/log/config/file.yml
  filebeat/module/santa/log/ingest/pipeline.yml
  filebeat/module/santa/log/test/santa.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, review

#20973 [Filebeat][suricata] Map x509 for suricata/eve fileset
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/suricata/eve/config/eve.yml
  x-pack/filebeat/module/suricata/eve/ingest/pipeline.yml
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-small.log
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, review

#20963 Cherry-pick to 7.x: Only request wildcard expansion for hidden indices if supported (#20938)
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/index/index.go
  metricbeat/module/elasticsearch/index/index_test.go
Labels: Team:Services, backport

#21013 Cherry-pick #21003 to 7.x: [Filebeat][zeek] Bump zeek kerberos/ssl/x509 ecs version
  x-pack/filebeat/module/zeek/kerberos/config/kerberos.yml
  x-pack/filebeat/module/zeek/ssl/config/ssl.yml
  x-pack/filebeat/module/zeek/x509/config/x509.yml
Labels: Team:SIEM, [zube]: In Review, backport

#21026 Update api-keys.asciidoc - API key prerequisites
  libbeat/docs/security/api-keys.asciidoc
Labels: Team:Docs, docs, enhancement, needs_backport

#20904 Cherry-pick to 7.9: Adding cborbeat to community beats (#20884)
  libbeat/docs/communitybeats.asciidoc
Labels: Team:Docs, backport

#20905 Cherry-pick to 7.x: Adding cborbeat to community beats (#20884)
  libbeat/docs/communitybeats.asciidoc
Labels: Team:Docs, backport

#20906 Cherry-pick to 7.9: docs: Update beats for APM (#20881)
  libbeat/docs/howto/load-index-templates.asciidoc
  libbeat/docs/shared/configuring-intro.asciidoc
Labels: Team:Docs, backport

#20907 Cherry-pick to 7.x: docs: Update beats for APM (#20881)
  libbeat/docs/howto/load-index-templates.asciidoc
  libbeat/docs/shared/configuring-intro.asciidoc
Labels: Team:Docs, backport

#21014 Cherry-pick #20983 to 7.x: [Filebeat][fortinet] Map x509 ecs fields for fortinet fw fileset
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/fortinet/fields.go
  x-pack/filebeat/module/fortinet/firewall/_meta/fields.yml
  x-pack/filebeat/module/fortinet/firewall/config/firewall.yml
  x-pack/filebeat/module/fortinet/firewall/ingest/utm.yml
  x-pack/filebeat/module/fortinet/firewall/test/fortinet.log
  x-pack/filebeat/module/fortinet/firewall/test/fortinet.log-expected.json
Labels: Team:SIEM, [zube]: In Review, backport

#21022 Sanitize event.host in Metricbeat
  CHANGELOG.next.asciidoc
  metricbeat/mb/module/wrapper.go
  x-pack/metricbeat/module/oracle/performance/_meta/cache_data.json
  x-pack/metricbeat/module/oracle/performance/_meta/cursor_by_username_and_machine_data.json
  x-pack/metricbeat/module/oracle/performance/_meta/data.json
  x-pack/metricbeat/module/oracle/performance/metricset.go
  x-pack/metricbeat/module/oracle/tablespace/_meta/data.json
  x-pack/metricbeat/module/oracle/tablespace/metricset.go
Labels: Team:Integrations, enhancement, needs_backport

#21030 Cherry-pick #21022 to 7.x: Sanitize event.host in Metricbeat
  CHANGELOG.next.asciidoc
  metricbeat/mb/module/wrapper.go
  x-pack/metricbeat/module/oracle/performance/_meta/cache_data.json
  x-pack/metricbeat/module/oracle/performance/_meta/cursor_by_username_and_machine_data.json
  x-pack/metricbeat/module/oracle/performance/_meta/data.json
  x-pack/metricbeat/module/oracle/performance/metricset.go
  x-pack/metricbeat/module/oracle/tablespace/_meta/data.json
  x-pack/metricbeat/module/oracle/tablespace/metricset.go
Labels: Team:Integrations, [zube]: In Review, backport

#20984 Add container ECS fields in kubernetes metadata
  CHANGELOG.next.asciidoc
  go.mod
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/processors/add_kubernetes_metadata/indexers.go
  libbeat/processors/add_kubernetes_metadata/indexers_test.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
Labels: Team:Platforms, bug, needs_backport, v7.10.0, v7.9.2

#21007 Cherry-pick #20603 to 7.x: Fix python deprecation warnings
  Jenkinsfile
  Makefile
  auditbeat/tests/system/test_file_integrity.py
  dev-tools/cmd/dashboards/export_5x_dashboards.py
  filebeat/scripts/docs_collector.py
  filebeat/tests/open-file-handlers/log_stdout.py
  filebeat/tests/system/filebeat.py
  filebeat/tests/system/test_container.py
  filebeat/tests/system/test_modules.py
  filebeat/tests/system/test_multiline.py
  filebeat/tests/system/test_pipeline.py
  filebeat/tests/system/test_registrar.py
  filebeat/tests/system/test_setup.py
  heartbeat/scripts/generate_imports_helper.py
  heartbeat/tests/system/test_base.py
  heartbeat/tests/system/test_telemetry.py
  libbeat/scripts/generate_makefile_doc.py
  libbeat/tests/system/beat/beat.py
  libbeat/tests/system/beat/common_tests.py
  libbeat/tests/system/beat/compose.py
  libbeat/tests/system/requirements.txt
  libbeat/tests/system/test_cmd_setup_index_management.py
  libbeat/tests/system/test_monitoring.py
  metricbeat/module/elasticsearch/test_elasticsearch.py
  metricbeat/module/system/test_system.py
  metricbeat/module/uwsgi/test_uwsgi.py
  metricbeat/tests/system/metricbeat.py
  metricbeat/tests/system/test_cmd.py
  packetbeat/tests/system/test_0012_http_basicauth.py
  pytest.ini
  winlogbeat/tests/system/winlogbeat.py
  x-pack/auditbeat/tests/system/test_system_socket.py
  x-pack/functionbeat/tests/system/test_base.py
  x-pack/libbeat/tests/system/test_management.py
Labels: Team:Automation, Team:Integrations, [zube]: In Review, backport

#21034 Cherry-pick #20984 to 7.9: Add container ECS fields in kubernetes metadata
  CHANGELOG.next.asciidoc
  go.mod
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/processors/add_kubernetes_metadata/indexers.go
  libbeat/processors/add_kubernetes_metadata/indexers_test.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
Labels: Team:Platforms, [zube]: In Review, backport

#21033 Cherry-pick #20984 to 7.x: Add container ECS fields in kubernetes metadata
  CHANGELOG.next.asciidoc
  go.mod
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/processors/add_kubernetes_metadata/indexers.go
  libbeat/processors/add_kubernetes_metadata/indexers_test.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
Labels: Team:Platforms, [zube]: In Review, backport

#20989 Disable Kafka metricsets based on Jolokia
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/kafka/broker.asciidoc
  metricbeat/docs/modules/kafka/consumer.asciidoc
  metricbeat/docs/modules/kafka/producer.asciidoc
  metricbeat/module/kafka/broker/manifest.yml
  metricbeat/module/kafka/consumer/manifest.yml
  metricbeat/module/kafka/producer/manifest.yml
Labels: Team:Services, needs_backport, review, v7.10.0

#21016 Cherry-pick #20976 to 7.x: [Filebeat][santa] Map x509 fields in santa module
  CHANGELOG.next.asciidoc
  filebeat/module/santa/log/config/file.yml
  filebeat/module/santa/log/ingest/pipeline.yml
  filebeat/module/santa/log/test/santa.log-expected.json
Labels: Team:SIEM, [zube]: In Review, backport

#20894 Cherry-pick #20855 to 7.x: [Filebeat][Gsuite] Add note about admin in gsuite docs
  filebeat/docs/modules/gsuite.asciidoc
  x-pack/filebeat/module/gsuite/_meta/docs.asciidoc
Labels: Team:SIEM, [zube]: In Review, backport

#21041 [Elastic Agent] Add changelog entry for EQL based condition
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
Labels: Team:Ingest Management

#21037 [Ingest Manager] Increase kibana client timeout to 5 minutes
  x-pack/elastic-agent/pkg/kibana/config.go
Labels: Ingest Management:beta2, Team:Ingest Management

#21029 Cherry-pick to 7.x: Update api-keys.asciidoc - API key prerequisites (#21026)
  libbeat/docs/security/api-keys.asciidoc
Labels: Team:Docs, backport, docs, v7.10.0

#21028 Cherry-pick to 7.9: Update api-keys.asciidoc - API key prerequisites (#21026)
  libbeat/docs/security/api-keys.asciidoc
Labels: Team:Docs, backport, docs, v7.9.0

#21018 Cherry-pick #20973 to 7.x: [Filebeat][suricata] Map x509 for suricata/eve fileset
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/suricata/eve/config/eve.yml
  x-pack/filebeat/module/suricata/eve/ingest/pipeline.yml
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-small.log
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
Labels: Team:SIEM, [zube]: In Review, backport

#21047 [Elastic Agent] Fix loggers in composable module.
  x-pack/elastic-agent/pkg/agent/application/inspect_output_cmd.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/composable/context.go
  x-pack/elastic-agent/pkg/composable/controller.go
  x-pack/elastic-agent/pkg/composable/controller_test.go
  x-pack/elastic-agent/pkg/composable/dynamic.go
  x-pack/elastic-agent/pkg/composable/providers/agent/agent.go
  x-pack/elastic-agent/pkg/composable/providers/agent/agent_test.go
  x-pack/elastic-agent/pkg/composable/providers/env/env.go
  x-pack/elastic-agent/pkg/composable/providers/env/env_test.go
  x-pack/elastic-agent/pkg/composable/providers/host/host.go
  x-pack/elastic-agent/pkg/composable/providers/host/host_test.go
  x-pack/elastic-agent/pkg/composable/providers/local/local.go
  x-pack/elastic-agent/pkg/composable/providers/local/local_test.go
  x-pack/elastic-agent/pkg/composable/providers/localdynamic/localdynamic.go
  x-pack/elastic-agent/pkg/composable/providers/localdynamic/localdynamic_test.go
  x-pack/elastic-agent/pkg/composable/providers/path/path.go
  x-pack/elastic-agent/pkg/composable/providers/path/path_test.go
Labels: Team:Ingest Management

#21052 Add ingress controller dashboards
  CHANGELOG.next.asciidoc
  filebeat/module/nginx/_meta/kibana/7/dashboard/Filebeat-nginx-ingress-logs.json
  filebeat/module/nginx/_meta/kibana/7/dashboard/Filebeat-nginx-ingress-overview.json
Labels: :Dashboards, Team:Platforms, needs_backport, v7.10.0

#21048 Filebeat: Fix random error on harvester close
  CHANGELOG.next.asciidoc
  filebeat/input/log/harvester.go
Labels: Filebeat, Team:SIEM, Team:Services, bug, needs_backport, review

#21053 Cherry-pick #21047 to 7.x: [Elastic Agent] Fix loggers in composable module.
  x-pack/elastic-agent/pkg/agent/application/inspect_output_cmd.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/composable/context.go
  x-pack/elastic-agent/pkg/composable/controller.go
  x-pack/elastic-agent/pkg/composable/controller_test.go
  x-pack/elastic-agent/pkg/composable/dynamic.go
  x-pack/elastic-agent/pkg/composable/providers/agent/agent.go
  x-pack/elastic-agent/pkg/composable/providers/agent/agent_test.go
  x-pack/elastic-agent/pkg/composable/providers/env/env.go
  x-pack/elastic-agent/pkg/composable/providers/env/env_test.go
  x-pack/elastic-agent/pkg/composable/providers/host/host.go
  x-pack/elastic-agent/pkg/composable/providers/host/host_test.go
  x-pack/elastic-agent/pkg/composable/providers/local/local.go
  x-pack/elastic-agent/pkg/composable/providers/local/local_test.go
  x-pack/elastic-agent/pkg/composable/providers/localdynamic/localdynamic.go
  x-pack/elastic-agent/pkg/composable/providers/localdynamic/localdynamic_test.go
  x-pack/elastic-agent/pkg/composable/providers/path/path.go
  x-pack/elastic-agent/pkg/composable/providers/path/path_test.go
Labels: Team:Ingest Management, [zube]: In Review, backport

#20993 Add support for GMT timezone offset in decode_cef
  CHANGELOG.next.asciidoc
  x-pack/filebeat/processors/decode_cef/cef/types.go
  x-pack/filebeat/processors/decode_cef/cef/types_test.go
Labels: Filebeat, Team:SIEM, enhancement

#21015 Cherry-pick #20889 to 7.x: Make compute_vm light metricset and add update cloud instance id
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/azure/compute_vm.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-billing-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-blob-storage-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-container-instance-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-container-registry-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-container-service-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-database-account-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-file-storage-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-queue-storage-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-storage-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-table-storage-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-vm-guestmetrics-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-vm-overview.json
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-vmss-overview.json
  x-pack/metricbeat/module/azure/add_metadata.go
  x-pack/metricbeat/module/azure/azure.go
  x-pack/metricbeat/module/azure/client.go
  x-pack/metricbeat/module/azure/client_test.go
  x-pack/metricbeat/module/azure/client_utils.go
  x-pack/metricbeat/module/azure/client_utils_test.go
  x-pack/metricbeat/module/azure/compute_vm/_meta/data.json
  x-pack/metricbeat/module/azure/compute_vm/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/compute_vm/client_helper.go
  x-pack/metricbeat/module/azure/compute_vm/client_helper_test.go
  x-pack/metricbeat/module/azure/compute_vm/compute_vm.go
  x-pack/metricbeat/module/azure/compute_vm/compute_vm_integration_test.go
  x-pack/metricbeat/module/azure/compute_vm/compute_vm_test.go
  x-pack/metricbeat/module/azure/compute_vm/manifest.yml
  x-pack/metricbeat/module/azure/compute_vm_scaleset/_meta/data.json
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper_test.go
  x-pack/metricbeat/module/azure/config.go
  x-pack/metricbeat/module/azure/container_instance/_meta/data.json
  x-pack/metricbeat/module/azure/container_registry/_meta/data.json
  x-pack/metricbeat/module/azure/container_service/_meta/data.json
  x-pack/metricbeat/module/azure/data.go
  x-pack/metricbeat/module/azure/data_test.go
  x-pack/metricbeat/module/azure/database_account/_meta/data.json
  x-pack/metricbeat/module/azure/database_account/database_account_integration_test.go
  x-pack/metricbeat/module/azure/mock_service.go
  x-pack/metricbeat/module/azure/module.yml
  x-pack/metricbeat/module/azure/monitor/_meta/data.json
  x-pack/metricbeat/module/azure/monitor/client_helper.go
  x-pack/metricbeat/module/azure/monitor/client_helper_test.go
  x-pack/metricbeat/module/azure/monitor_service.go
  x-pack/metricbeat/module/azure/monitor_service_test.go
  x-pack/metricbeat/module/azure/resources.go
  x-pack/metricbeat/module/azure/storage/client_helper.go
  x-pack/metricbeat/module/azure/storage/client_helper_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#20414 [Filebeat][New Module] Zoom webhook module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/zoom.asciidoc
  filebeat/docs/modules_list.asciidoc
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/include/list.go
  x-pack/filebeat/module/zoom/_meta/config.yml
  x-pack/filebeat/module/zoom/_meta/docs.asciidoc
  x-pack/filebeat/module/zoom/_meta/fields.yml
  x-pack/filebeat/module/zoom/fields.go
  x-pack/filebeat/module/zoom/module.yml
  x-pack/filebeat/module/zoom/webhook/_meta/fields.yml
  x-pack/filebeat/module/zoom/webhook/config/webhook.yml
  x-pack/filebeat/module/zoom/webhook/ingest/account.yml
  x-pack/filebeat/module/zoom/webhook/ingest/chat_channel.yml
  x-pack/filebeat/module/zoom/webhook/ingest/chat_message.yml
  x-pack/filebeat/module/zoom/webhook/ingest/meeting.yml
  x-pack/filebeat/module/zoom/webhook/ingest/phone.yml
  x-pack/filebeat/module/zoom/webhook/ingest/pipeline.yml
  x-pack/filebeat/module/zoom/webhook/ingest/recording.yml
  x-pack/filebeat/module/zoom/webhook/ingest/user.yml
  x-pack/filebeat/module/zoom/webhook/ingest/webinar.yml
  x-pack/filebeat/module/zoom/webhook/ingest/zoomroom.yml
  x-pack/filebeat/module/zoom/webhook/manifest.yml
  x-pack/filebeat/module/zoom/webhook/test/account.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/account.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/chat_channel.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/chat_channel.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/chat_message.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/chat_message.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/meeting.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/meeting.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/phone.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/phone.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/recording.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/recording.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/user.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/user.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/webinar.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/webinar.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/zoomroom.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/zoomroom.ndjson.log-expected.json
  x-pack/filebeat/modules.d/zoom.yml.disabled
Labels: Filebeat, Team:SIEM, enhancement, review

#21072 Do not need Google credentials before using it
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/manager/gcp/cli_manager.go
Labels: Team:Services, needs_backport, review

#21042 [Elastic Agent] Add fleet.host.id for sending to endpoint.
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/fleet_decorator.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/program/testdata/endpoint_basic-endpoint-security.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/endpoint_basic.yml
Labels: Team:Ingest Management

#21075 Cherry-pick #21072 to 7.x: Do not need Google credentials before using it
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/manager/gcp/cli_manager.go
Labels: Team:Services, [zube]: In Review, backport

#21076 Cherry-pick #21072 to 7.9: Do not need Google credentials before using it
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/manager/gcp/cli_manager.go
Labels: Team:Services, [zube]: In Review, backport

#21054 Cherry-pick #21052 to 7.x: Add ingress controller dashboards
  CHANGELOG.next.asciidoc
  filebeat/module/nginx/_meta/kibana/7/dashboard/Filebeat-nginx-ingress-logs.json
  filebeat/module/nginx/_meta/kibana/7/dashboard/Filebeat-nginx-ingress-overview.json
Labels: Team:Platforms, [zube]: In Review, backport

#21070 Add vendoring to Google Cloud Functions again
  CHANGELOG.next.asciidoc
  dev-tools/mage/gotool/go.go
  x-pack/functionbeat/dev-tools/packaging/packages.yml
  x-pack/functionbeat/magefile.go
  x-pack/functionbeat/manager/gcp/template_builder.go
  x-pack/functionbeat/scripts/mage/update.go
Labels: Team:Services, needs_backport, review

#21078 Cherry-pick #21070 to 7.x: Add vendoring to Google Cloud Functions again
  CHANGELOG.next.asciidoc
  dev-tools/mage/gotool/go.go
  x-pack/functionbeat/dev-tools/packaging/packages.yml
  x-pack/functionbeat/magefile.go
  x-pack/functionbeat/manager/gcp/template_builder.go
  x-pack/functionbeat/scripts/mage/update.go
Labels: Team:Services, [zube]: In Review, backport

#21079 Cherry-pick #21070 to 7.9: Add vendoring to Google Cloud Functions again
  CHANGELOG.next.asciidoc
  dev-tools/mage/gotool/go.go
  x-pack/functionbeat/dev-tools/packaging/packages.yml
  x-pack/functionbeat/magefile.go
  x-pack/functionbeat/manager/gcp/template_builder.go
  x-pack/functionbeat/scripts/mage/update.go
Labels: Team:Services, [zube]: In Review, backport

#21060 Cherry-pick #20993 to 7.9: Add support for GMT timezone offset in decode_cef
  CHANGELOG.next.asciidoc
  x-pack/filebeat/processors/decode_cef/cef/types.go
  x-pack/filebeat/processors/decode_cef/cef/types_test.go
Labels: Team:SIEM, [zube]: In Review, backport

#21059 Cherry-pick #20993 to 7.x: Add support for GMT timezone offset in decode_cef
  CHANGELOG.next.asciidoc
  x-pack/filebeat/processors/decode_cef/cef/types.go
  x-pack/filebeat/processors/decode_cef/cef/types_test.go
Labels: Team:SIEM, [zube]: In Review, backport

#21056 Cherry-pick #21048 to 7.9: Filebeat: Fix random error on harvester close
  CHANGELOG.next.asciidoc
  filebeat/input/log/harvester.go
Labels: Team:SIEM, Team:Services, [zube]: In Review, backport

#21055 Cherry-pick #21048 to 7.x: Filebeat: Fix random error on harvester close
  CHANGELOG.next.asciidoc
  filebeat/input/log/harvester.go
Labels: Team:SIEM, Team:Services, [zube]: In Review, backport

#21073 Cherry-pick #20414 to 7.x: [Filebeat][New Module] Zoom webhook module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/zoom.asciidoc
  filebeat/docs/modules_list.asciidoc
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/include/list.go
  x-pack/filebeat/module/zoom/_meta/config.yml
  x-pack/filebeat/module/zoom/_meta/docs.asciidoc
  x-pack/filebeat/module/zoom/_meta/fields.yml
  x-pack/filebeat/module/zoom/fields.go
  x-pack/filebeat/module/zoom/module.yml
  x-pack/filebeat/module/zoom/webhook/_meta/fields.yml
  x-pack/filebeat/module/zoom/webhook/config/webhook.yml
  x-pack/filebeat/module/zoom/webhook/ingest/account.yml
  x-pack/filebeat/module/zoom/webhook/ingest/chat_channel.yml
  x-pack/filebeat/module/zoom/webhook/ingest/chat_message.yml
  x-pack/filebeat/module/zoom/webhook/ingest/meeting.yml
  x-pack/filebeat/module/zoom/webhook/ingest/phone.yml
  x-pack/filebeat/module/zoom/webhook/ingest/pipeline.yml
  x-pack/filebeat/module/zoom/webhook/ingest/recording.yml
  x-pack/filebeat/module/zoom/webhook/ingest/user.yml
  x-pack/filebeat/module/zoom/webhook/ingest/webinar.yml
  x-pack/filebeat/module/zoom/webhook/ingest/zoomroom.yml
  x-pack/filebeat/module/zoom/webhook/manifest.yml
  x-pack/filebeat/module/zoom/webhook/test/account.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/account.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/chat_channel.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/chat_channel.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/chat_message.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/chat_message.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/meeting.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/meeting.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/phone.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/phone.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/recording.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/recording.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/user.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/user.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/webinar.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/webinar.ndjson.log-expected.json
  x-pack/filebeat/module/zoom/webhook/test/zoomroom.ndjson.log
  x-pack/filebeat/module/zoom/webhook/test/zoomroom.ndjson.log-expected.json
  x-pack/filebeat/modules.d/zoom.yml.disabled
Labels: Team:SIEM, [zube]: In Review, backport, review

#21086 [Filebeat] Add support for Cloudtrail digest files
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/input/s3/config.go
  x-pack/filebeat/input/s3/input.go
  x-pack/filebeat/input/s3/input_test.go
  x-pack/filebeat/module/aws/_meta/config.yml
  x-pack/filebeat/module/aws/cloudtrail/_meta/fields.yml
  x-pack/filebeat/module/aws/cloudtrail/config/s3.yml
  x-pack/filebeat/module/aws/cloudtrail/ingest/pipeline.yml
  x-pack/filebeat/module/aws/cloudtrail/manifest.yml
  x-pack/filebeat/module/aws/cloudtrail/test/cloudtrail-digest-json.log
  x-pack/filebeat/module/aws/cloudtrail/test/cloudtrail-digest-json.log-expected.json
  x-pack/filebeat/module/aws/cloudtrail/test/insight-json.log
  x-pack/filebeat/module/aws/cloudtrail/test/insight-json.log-expected.json
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/modules.d/aws.yml.disabled
Labels: Filebeat, Team:SIEM, bug, needs_backport

#21088 Cherry-pick #21086 to 7.x: [Filebeat] Add support for Cloudtrail digest files
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/input/s3/config.go
  x-pack/filebeat/input/s3/input.go
  x-pack/filebeat/input/s3/input_test.go
  x-pack/filebeat/module/aws/_meta/config.yml
  x-pack/filebeat/module/aws/cloudtrail/_meta/fields.yml
  x-pack/filebeat/module/aws/cloudtrail/config/s3.yml
  x-pack/filebeat/module/aws/cloudtrail/ingest/pipeline.yml
  x-pack/filebeat/module/aws/cloudtrail/manifest.yml
  x-pack/filebeat/module/aws/cloudtrail/test/cloudtrail-digest-json.log
  x-pack/filebeat/module/aws/cloudtrail/test/cloudtrail-digest-json.log-expected.json
  x-pack/filebeat/module/aws/cloudtrail/test/insight-json.log
  x-pack/filebeat/module/aws/cloudtrail/test/insight-json.log-expected.json
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/modules.d/aws.yml.disabled
Labels: Team:SIEM, [zube]: In Review, backport

#21089 Cherry-pick #21086 to 7.9: [Filebeat] Add support for Cloudtrail digest files
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/input/s3/config.go
  x-pack/filebeat/input/s3/input.go
  x-pack/filebeat/input/s3/input_test.go
  x-pack/filebeat/module/aws/_meta/config.yml
  x-pack/filebeat/module/aws/cloudtrail/_meta/fields.yml
  x-pack/filebeat/module/aws/cloudtrail/config/s3.yml
  x-pack/filebeat/module/aws/cloudtrail/ingest/pipeline.yml
  x-pack/filebeat/module/aws/cloudtrail/manifest.yml
  x-pack/filebeat/module/aws/cloudtrail/test/cloudtrail-digest-json.log
  x-pack/filebeat/module/aws/cloudtrail/test/cloudtrail-digest-json.log-expected.json
  x-pack/filebeat/module/aws/cloudtrail/test/insight-json.log
  x-pack/filebeat/module/aws/cloudtrail/test/insight-json.log-expected.json
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/modules.d/aws.yml.disabled
Labels: Team:SIEM, [zube]: In Review, backport

#21036 Cherry-pick #20989 to 7.x: Disable Kafka metricsets based on Jolokia
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/kafka/broker.asciidoc
  metricbeat/docs/modules/kafka/consumer.asciidoc
  metricbeat/docs/modules/kafka/producer.asciidoc
  metricbeat/module/kafka/broker/manifest.yml
  metricbeat/module/kafka/consumer/manifest.yml
  metricbeat/module/kafka/producer/manifest.yml
Labels: Team:Services, [zube]: In Review, backport

#21012 Cherry-pick #20918 to 7.x: Update fields.yml in azure module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/azure/_meta/fields.yml
  x-pack/metricbeat/module/azure/fields.go
  x-pack/metricbeat/module/azure/monitor/_meta/fields.yml
Labels: Team:Platforms, [zube]: In Review, backport

#21038 Move the `compute_vm_scalset` to a light metricset and map the cloud metadata
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/azure/compute_vm.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/module/azure/add_metadata.go
  x-pack/metricbeat/module/azure/client.go
  x-pack/metricbeat/module/azure/client_utils.go
  x-pack/metricbeat/module/azure/client_utils_test.go
  x-pack/metricbeat/module/azure/compute_vm/manifest.yml
  x-pack/metricbeat/module/azure/compute_vm_scaleset/_meta/data.json
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/compute_vm_scaleset.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/compute_vm_scaleset_integration_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/compute_vm_scaleset_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/manifest.yml
  x-pack/metricbeat/module/azure/data.go
  x-pack/metricbeat/module/azure/module.yml
  x-pack/metricbeat/module/azure/resources.go
Labels: Team:Integrations, [zube]: In Review, needs_backport

#21083 Cherry-pick #20929 to 7.8: Clarify use for shared_credential_file
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Docs, [zube]: In Review, backport

#21082 Cherry-pick #20929 to 7.9: Clarify use for shared_credential_file
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Docs, [zube]: In Review, backport

#21081 Cherry-pick #20929 to 7.x: Clarify use for shared_credential_file
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Docs, [zube]: In Review, backport

#21077 Cherry-pick #21042 to 7.x: [Elastic Agent] Add fleet.host.id for sending to endpoint.
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/fleet_decorator.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/program/testdata/endpoint_basic-endpoint-security.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/endpoint_basic.yml
Labels: Team:Ingest Management, [zube]: In Review, backport

#20969 Cherry-pick #20908 to 7.x: [Filebeat] backwards compatibility for set processor
  CHANGELOG.next.asciidoc
  filebeat/fileset/pipelines.go
  filebeat/fileset/pipelines_test.go
Labels: Team:SIEM, [zube]: In Review, backport

#21084 Cherry-pick #20908 to 7.9: [Filebeat] backwards compatibility for set processor
  CHANGELOG.next.asciidoc
  filebeat/fileset/pipelines.go
  filebeat/fileset/pipelines_test.go
Labels: Team:SIEM, [zube]: In Review, backport

#21094 Cherry-pick #21038 to 7.x: Move the `compute_vm_scalset` to a light metricset and map the cloud metadata
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/azure/compute_vm.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/module/azure/add_metadata.go
  x-pack/metricbeat/module/azure/client.go
  x-pack/metricbeat/module/azure/client_utils.go
  x-pack/metricbeat/module/azure/client_utils_test.go
  x-pack/metricbeat/module/azure/compute_vm/manifest.yml
  x-pack/metricbeat/module/azure/compute_vm_scaleset/_meta/data.json
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/compute_vm_scaleset.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/compute_vm_scaleset_integration_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/compute_vm_scaleset_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/manifest.yml
  x-pack/metricbeat/module/azure/data.go
  x-pack/metricbeat/module/azure/module.yml
  x-pack/metricbeat/module/azure/resources.go
Labels: Team:Integrations, [zube]: In Review, backport

#20912 [Filebeat] add panos type and sub_type
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/panw/fields.go
  x-pack/filebeat/module/panw/panos/_meta/fields.yml
  x-pack/filebeat/module/panw/panos/config/input.yml
  x-pack/filebeat/module/panw/panos/ingest/pipeline.yml
  x-pack/filebeat/module/panw/panos/test/pan_inc_other.log-expected.json
  x-pack/filebeat/module/panw/panos/test/pan_inc_threat.log-expected.json
  x-pack/filebeat/module/panw/panos/test/pan_inc_traffic.log-expected.json
  x-pack/filebeat/module/panw/panos/test/threat.log-expected.json
  x-pack/filebeat/module/panw/panos/test/traffic.log-expected.json
Labels: Filebeat, Team:SIEM, enhancement, needs_backport

#20799 [docs] typo in the command line
  filebeat/docs/inputs/input-log.asciidoc
Labels: Team:Services, docs, needs_backport

#20802 Update users.asciidoc
  libbeat/docs/security/users.asciidoc
Labels: Team:Docs, needs_backport

#21105 Cherry-pick to 7.9: [docs] typo in the command line (#20799)
  filebeat/docs/inputs/input-log.asciidoc
Labels: Team:Docs, backport, v7.9.0

#21106 Cherry-pick to 7.x: [docs] typo in the command line (#20799)
  filebeat/docs/inputs/input-log.asciidoc
Labels: Team:Docs, backport, docs, v7.10.0

#21061 Fix broken links to external websites
  filebeat/docs/modules/zeek.asciidoc
  libbeat/docs/communitybeats.asciidoc
  libbeat/docs/shared-faq.asciidoc
  packetbeat/docs/packetbeat-options.asciidoc
  x-pack/filebeat/module/zeek/_meta/docs.asciidoc
Labels: Team:Docs, docs, needs_backport, v7.10.0, v7.9.0, v8.0.0

#21102 Cherry-pick #20912 to 7.x: [Filebeat] add panos type and sub_type
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/panw/fields.go
  x-pack/filebeat/module/panw/panos/_meta/fields.yml
  x-pack/filebeat/module/panw/panos/config/input.yml
  x-pack/filebeat/module/panw/panos/ingest/pipeline.yml
  x-pack/filebeat/module/panw/panos/test/pan_inc_other.log-expected.json
  x-pack/filebeat/module/panw/panos/test/pan_inc_threat.log-expected.json
  x-pack/filebeat/module/panw/panos/test/pan_inc_traffic.log-expected.json
  x-pack/filebeat/module/panw/panos/test/threat.log-expected.json
  x-pack/filebeat/module/panw/panos/test/traffic.log-expected.json
Labels: Team:SIEM, [zube]: In Review, backport

#20842 [Elastic Agent] Add docker composable dynamic provider.
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/include.go
  x-pack/elastic-agent/pkg/composable/providers/docker/config.go
  x-pack/elastic-agent/pkg/composable/providers/docker/docker.go
  x-pack/elastic-agent/pkg/composable/providers/docker/docker_test.go
  x-pack/elastic-agent/pkg/config/config.go
Labels: Team:Ingest Management

#21115 Cherry-pick #21037 to 7.x: Increase kibana client timeout to 5 minutes
  x-pack/elastic-agent/pkg/kibana/config.go
Labels: Ingest Management:beta2, Team:Ingest Management, bug

#21118 [Elastic Agent] Fix docker provider builder
  x-pack/elastic-agent/pkg/composable/providers/docker/docker.go
Labels: Team:Ingest Management, [zube]: In Review, review

#21117 Cherry-pick #20842 to 7.x: [Elastic Agent] Add docker composable dynamic provider.
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/include.go
  x-pack/elastic-agent/pkg/composable/providers/docker/config.go
  x-pack/elastic-agent/pkg/composable/providers/docker/docker.go
  x-pack/elastic-agent/pkg/composable/providers/docker/docker_test.go
  x-pack/elastic-agent/pkg/config/config.go
Labels: Team:Ingest Management, [zube]: In Review, backport

#21109 Cherry-pick to 7.9: Fix broken links to external websites (#21061)
  filebeat/docs/modules/zeek.asciidoc
  libbeat/docs/communitybeats.asciidoc
  libbeat/docs/shared-faq.asciidoc
  packetbeat/docs/packetbeat-options.asciidoc
  x-pack/filebeat/module/zeek/_meta/docs.asciidoc
Labels: Team:Docs, backport, docs, v7.9.0

#21107 Cherry-pick to 7.x: Update users.asciidoc (#20802)
  libbeat/docs/security/users.asciidoc
Labels: Team:Docs, backport, docs, v7.10.0
