Repository elastic/beats, pull requests merged in 2020-02, with the labels that each got.

#15841 [7.x][docs] Backport: Add placeholder files for 7.6 release highlights and breaking …
  libbeat/docs/release-notes/breaking/breaking-7.6.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.6.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights.asciidoc
Labels: backport, docs, v7.7.0

#15842 [7.6][docs] Backport: Add placeholder files for 7.6 release highlights and breaking …
  libbeat/docs/release-notes/breaking/breaking-7.6.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.6.0.asciidoc
  libbeat/docs/release-notes/highlights/highlights.asciidoc
Labels: backport, docs, v7.6.1

#15964 [Metricbeat] Update aws module documentation
  metricbeat/docs/images/metricbeat-aws-dynamodb-overview.png
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/dynamodb/_meta/docs.asciidoc
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: Metricbeat, Team:Platforms, needs_backport, review

#15989 Cherry-pick #15930 to 7.x: Kubernetes: node autodiscover, add InternalIP
  libbeat/autodiscover/providers/kubernetes/node.go
Labels: backport, review

#15954 [Agent] Wait for GRPC on start
  x-pack/agent/pkg/agent/operation/tests/scripts/configurable-1.0-darwin-x86/main.go
  x-pack/agent/pkg/core/plugin/app/start.go
  x-pack/agent/pkg/core/remoteconfig/grpc/configclient.go
  x-pack/agent/pkg/core/remoteconfig/grpc/remote_config.pb.go
  x-pack/agent/proto/remote_config.proto
  x-pack/libbeat/management/fleet/config_server.go
Labels: Project:fleet, agent, discuss

#16017 Update mage version in Makefile v1.8.0 to v1.9.0
  dev-tools/make/mage.mk
Labels: Team:Services, [zube]: In Review

#16000 Make field names in Functionbeat ECS compliant
  x-pack/functionbeat/magefile.go
  x-pack/functionbeat/provider/gcp/gcp/transformer.go
Labels: Team:Services, [zube]: In Review, needs_backport

#16011 Cherry-pick #15964 to 7.x: [Metricbeat] Update aws module documentation
  metricbeat/docs/images/metricbeat-aws-dynamodb-overview.png
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/dynamodb/_meta/docs.asciidoc
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: backport, review

#15990 Add citadel metricset for Istio Metricbeat module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/istio.asciidoc
  metricbeat/docs/modules/istio/citadel.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/istio/_meta/config.reference.yml
  x-pack/metricbeat/module/istio/_meta/config.yml
  x-pack/metricbeat/module/istio/_meta/docs.asciidoc
  x-pack/metricbeat/module/istio/citadel/_meta/data.json
  x-pack/metricbeat/module/istio/citadel/_meta/docs.asciidoc
  x-pack/metricbeat/module/istio/citadel/_meta/fields.yml
  x-pack/metricbeat/module/istio/citadel/_meta/testdata/config.yml
  x-pack/metricbeat/module/istio/citadel/_meta/testdata/docs.plain
  x-pack/metricbeat/module/istio/citadel/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/istio/citadel/citadel.go
  x-pack/metricbeat/module/istio/citadel/citadel_test.go
  x-pack/metricbeat/module/istio/fields.go
  x-pack/metricbeat/modules.d/istio.yml.disabled
Labels: Metricbeat, Team:Integrations, Team:Platforms, [zube]: In Review, enhancement, needs_backport, review, v7.7.0

#16001 Reuse connections on sql module
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/sql/query/query.go
Labels: Metricbeat, Team:Services, [zube]: In Review, module, needs_backport, review, v7.7.0

#16007 [Filebeat] Add dashboard for vpc flow log
  CHANGELOG.next.asciidoc
  filebeat/docs/images/filebeat-aws-vpcflow-overview.png
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/_meta/kibana/7/dashboard/Filebeat-aws-vpcflow-overview.json
Labels: Filebeat, Team:Platforms, [zube]: In Review, needs_backport, review

#16023 Cherry-pick #15804 to 7.6: Filebeat: add ELB dashboard
  CHANGELOG.asciidoc
  filebeat/docs/images/filebeat-aws-elb-overview.png
  x-pack/filebeat/module/aws/_meta/kibana/7/dashboard/Filebeat-aws-elb-overview.json
Labels: backport, review

#15936 [Filebeat] Add ECS tls fields to zeek and aws modules
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/aws/elb/ingest/pipeline.yml
  x-pack/filebeat/module/aws/elb/test/example-alb-http.log-expected.json
  x-pack/filebeat/module/aws/elb/test/example-https.log-expected.json
  x-pack/filebeat/module/aws/elb/test/example-nlb-tcp.log-expected.json
  x-pack/filebeat/module/aws/elb/test/example-ssl.log-expected.json
  x-pack/filebeat/module/aws/s3access/ingest/pipeline.yml
  x-pack/filebeat/module/aws/s3access/test/s3_server_access.log-expected.json
  x-pack/filebeat/module/aws/s3access/test/test.log-expected.json
  x-pack/filebeat/module/zeek/rdp/ingest/pipeline.json
  x-pack/filebeat/module/zeek/rdp/test/rdp-json.log-expected.json
  x-pack/filebeat/module/zeek/smtp/ingest/pipeline.json
  x-pack/filebeat/module/zeek/smtp/test/smtp-json.log-expected.json
  x-pack/filebeat/module/zeek/ssl/ingest/pipeline.json
  x-pack/filebeat/module/zeek/ssl/ingest/pipeline.yml
  x-pack/filebeat/module/zeek/ssl/manifest.yml
  x-pack/filebeat/module/zeek/ssl/test/ssl-json.log-expected.json
Labels: Filebeat, Team:SIEM, enhancement, needs_backport

#16018 Cherry-pick #15854 to 7.6: Kubernetes: update replicaset type to apps/v1
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/types.go
Labels: backport, review

#15948 [MetricBeat] Add up metric for health status
  CHANGELOG.next.asciidoc
  metricbeat/module/prometheus/collector/_meta/data.json
  metricbeat/module/prometheus/collector/_meta/testdata/docs.plain-expected.json
  metricbeat/module/prometheus/collector/_meta/testdata/etcd-3.3.10-partial.plain-expected.json
  metricbeat/module/prometheus/collector/_meta/testdata/metrics-with-naninf.plain-expected.json
  metricbeat/module/prometheus/collector/_meta/testdata/prometheus-2.6.0-partial.plain-expected.json
  metricbeat/module/prometheus/collector/collector.go
  x-pack/metricbeat/module/cockroachdb/status/_meta/testdata/cockroachdb-status.v19.1.1.plain-expected.json
  x-pack/metricbeat/module/ibmmq/qmgr/_meta/testdata/ibmmq-status.9.1.4.0-r1-amd64.plain-expected.json
Labels: Team:Platforms, [zube]: Inbox, enhancement, needs_backport, review

#15906 Fix Filebeat Zeek Weird Ingest Pipeline
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/zeek/weird/ingest/pipeline.json
  x-pack/filebeat/module/zeek/weird/test/weird-json.log
  x-pack/filebeat/module/zeek/weird/test/weird-json.log-expected.json
Labels: Filebeat, Team:SIEM, needs_backport, review

#16012 Cherry-pick #15964 to 7.6: [Metricbeat] Update aws module documentation
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: backport, review

#16050 Cherry-pick #15761 to 7.x: [Metricbeat][Istio] Add pilot metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/istio.asciidoc
  metricbeat/docs/modules/istio/pilot.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/istio/_meta/config.reference.yml
  x-pack/metricbeat/module/istio/_meta/config.yml
  x-pack/metricbeat/module/istio/_meta/docs.asciidoc
  x-pack/metricbeat/module/istio/fields.go
  x-pack/metricbeat/module/istio/pilot/_meta/data.json
  x-pack/metricbeat/module/istio/pilot/_meta/docs.asciidoc
  x-pack/metricbeat/module/istio/pilot/_meta/fields.yml
  x-pack/metricbeat/module/istio/pilot/_meta/testdata/config.yml
  x-pack/metricbeat/module/istio/pilot/_meta/testdata/docs.plain
  x-pack/metricbeat/module/istio/pilot/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/istio/pilot/pilot.go
  x-pack/metricbeat/module/istio/pilot/pilot_test.go
  x-pack/metricbeat/modules.d/istio.yml.disabled
Labels: backport, review

#15890 [Auditbeat] Reduce system/socket logging noise
  x-pack/auditbeat/module/system/socket/arch_amd64.go
  x-pack/auditbeat/module/system/socket/guess/deref.go
  x-pack/auditbeat/module/system/socket/guess/syscallargs.go
  x-pack/auditbeat/module/system/socket/socket_linux.go
  x-pack/auditbeat/module/system/socket/state.go
Labels: Auditbeat, Team:SIEM, enhancement, review

#15955 Add Kafka README for manual testing
  metricbeat/module/kafka/README.md
Labels: Team:Integrations, Team:Services, [zube]: In Review, docs, enhancement, review

#16052 Cherry-pick #15990 to 7.x: Add citadel metricset for Istio Metricbeat module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/istio.asciidoc
  metricbeat/docs/modules/istio/citadel.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/istio/_meta/config.reference.yml
  x-pack/metricbeat/module/istio/_meta/config.yml
  x-pack/metricbeat/module/istio/_meta/docs.asciidoc
  x-pack/metricbeat/module/istio/citadel/_meta/data.json
  x-pack/metricbeat/module/istio/citadel/_meta/docs.asciidoc
  x-pack/metricbeat/module/istio/citadel/_meta/fields.yml
  x-pack/metricbeat/module/istio/citadel/_meta/testdata/config.yml
  x-pack/metricbeat/module/istio/citadel/_meta/testdata/docs.plain
  x-pack/metricbeat/module/istio/citadel/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/istio/citadel/citadel.go
  x-pack/metricbeat/module/istio/citadel/citadel_test.go
  x-pack/metricbeat/module/istio/fields.go
  x-pack/metricbeat/modules.d/istio.yml.disabled
Labels: backport, review

#16053 Cherry-pick #15955 to 7.x: Add Kafka README for manual testing
  metricbeat/module/kafka/README.md
Labels: backport, review

#15929 Fix tests for the dissect processor
  libbeat/processors/dissect/dissect_test.go
  libbeat/processors/dissect/testdata/dissect_tests.json
Labels: Team:Beats, [zube]: In Review, needs_backport

#15997 Correctly format the path to read data from npipe.
  metricbeat/mb/parse/url.go
  metricbeat/mb/parse/url_test.go
Labels: Team:Beats, [zube]: In Review, bug, needs_backport, review

#16034 Cherry-pick #16007 to 7.6: [Filebeat] Add dashboard for vpc flow log
  CHANGELOG.next.asciidoc
  filebeat/docs/images/filebeat-aws-vpcflow-overview.png
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/_meta/kibana/7/dashboard/Filebeat-aws-vpcflow-overview.json
Labels: backport, review

#16033 Cherry-pick #16007 to 7.x: [Filebeat] Add dashboard for vpc flow log
  CHANGELOG.next.asciidoc
  filebeat/docs/images/filebeat-aws-vpcflow-overview.png
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/_meta/kibana/7/dashboard/Filebeat-aws-vpcflow-overview.json
Labels: backport, review

#16057 Cherry-pick #15929 to 7.5: Fix tests for the dissect processor
  libbeat/processors/dissect/dissect_test.go
  libbeat/processors/dissect/testdata/dissect_tests.json
Labels: backport, review

#16056 Cherry-pick #15929 to 7.6: Fix tests for the dissect processor
  libbeat/processors/dissect/dissect_test.go
  libbeat/processors/dissect/testdata/dissect_tests.json
Labels: backport, review

#16055 Cherry-pick #15929 to 7.x: Fix tests for the dissect processor
  libbeat/processors/dissect/dissect_test.go
  libbeat/processors/dissect/testdata/dissect_tests.json
Labels: backport, review

#16027 Cherry-pick #16001 to 7.x: Reuse connections on sql module
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/sql/query/query.go
Labels: backport, review

#16035 Cherry-pick #15948 to 7.x: [MetricBeat] Add up metric for health status
  CHANGELOG.next.asciidoc
  metricbeat/module/prometheus/collector/_meta/data.json
  metricbeat/module/prometheus/collector/_meta/testdata/docs.plain-expected.json
  metricbeat/module/prometheus/collector/_meta/testdata/etcd-3.3.10-partial.plain-expected.json
  metricbeat/module/prometheus/collector/_meta/testdata/metrics-with-naninf.plain-expected.json
  metricbeat/module/prometheus/collector/_meta/testdata/prometheus-2.6.0-partial.plain-expected.json
  metricbeat/module/prometheus/collector/collector.go
  x-pack/metricbeat/module/cockroachdb/status/_meta/testdata/cockroachdb-status.v19.1.1.plain-expected.json
  x-pack/metricbeat/module/ibmmq/qmgr/_meta/testdata/ibmmq-status.9.1.4.0-r1-amd64.plain-expected.json
Labels: backport, review

#16036 [Filebeat] Add s3 bucket name filter into vpcflow dashboard
  filebeat/docs/images/filebeat-aws-vpcflow-overview.png
  x-pack/filebeat/module/aws/_meta/kibana/7/dashboard/Filebeat-aws-vpcflow-overview.json
Labels: Filebeat, Team:Platforms, [zube]: In Review, needs_backport, review

#16065 Clean up functionbeat/build/vendor folder before collecting dependencies
  x-pack/functionbeat/scripts/mage/update.go
Labels: Team:Services, [zube]: In Review, enhancement, needs_backport

#16004 [Metricbeat] Add collecting AuroraDB metrics in rds metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/rds/_meta/data.json
  x-pack/metricbeat/module/aws/rds/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/rds/_meta/fields.yml
  x-pack/metricbeat/module/aws/rds/data.go
Labels: Metricbeat, Team:Platforms, [zube]: In Review, needs_backport, review

#16062 Cherry-pick #15997 to 7.6: Correctly format the path to read data from npipe.
  metricbeat/mb/parse/url.go
  metricbeat/mb/parse/url_test.go
Labels: [zube]: In Review, backport, review

#16061 Cherry-pick #15997 to 7.x: Correctly format the path to read data from npipe.
  metricbeat/mb/parse/url.go
  metricbeat/mb/parse/url_test.go
Labels: [zube]: In Review, backport, review

#16021 Cherry-pick #16000 to 7.x: Make field names in Functionbeat ECS compliant
  x-pack/functionbeat/magefile.go
  x-pack/functionbeat/provider/gcp/gcp/transformer.go
Labels: Team:Beats, [zube]: In Review, backport

#16044 Only initialize service URL once
  CHANGELOG.next.asciidoc
  metricbeat/module/logstash/node_stats/node_stats.go
Labels: Metricbeat, Stack monitoring, Team:Integrations, [zube]: In Review, bug, module, needs_backport, test-plan, v7.6.1, v7.7.0, v8.0.0

#16067 Cherry-pick #16036 to 7.6: [Filebeat] Add s3 bucket name filter into vpcflow dashboard
  filebeat/docs/images/filebeat-aws-vpcflow-overview.png
  x-pack/filebeat/module/aws/_meta/kibana/7/dashboard/Filebeat-aws-vpcflow-overview.json
Labels: backport, review

#16066 Cherry-pick #16036 to 7.x: [Filebeat] Add s3 bucket name filter into vpcflow dashboard
  filebeat/docs/images/filebeat-aws-vpcflow-overview.png
  x-pack/filebeat/module/aws/_meta/kibana/7/dashboard/Filebeat-aws-vpcflow-overview.json
Labels: backport, review

#16037 Cherry-pick #15906 to 7.x: Fix Filebeat Zeek Weird Ingest Pipeline
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/zeek/weird/ingest/pipeline.json
  x-pack/filebeat/module/zeek/weird/test/weird-json.log
  x-pack/filebeat/module/zeek/weird/test/weird-json.log-expected.json
Labels: backport, review

#16022 Cherry-pick #16000 to 7.6: Make field names in Functionbeat ECS compliant
  x-pack/functionbeat/magefile.go
  x-pack/functionbeat/provider/gcp/gcp/transformer.go
Labels: backport, review

#16069 Cherry-pick #16065 to 7.x: Clean up functionbeat/build/vendor folder before collecting dependencies
  x-pack/functionbeat/scripts/mage/update.go
Labels: Team:Beats, [zube]: In Review, backport

#16068 Cherry-pick #16065 to 7.6: Clean up functionbeat/build/vendor folder before collecting dependencies
  x-pack/functionbeat/scripts/mage/update.go
Labels: Team:Beats, [zube]: In Review, backport

#16010 [DOCS] Recommend env variables rather than keystore for functionbeat
  libbeat/docs/command-reference.asciidoc
  libbeat/docs/dashboards.asciidoc
  libbeat/docs/https.asciidoc
  libbeat/docs/security/basic-auth.asciidoc
  libbeat/docs/step-configure-credentials.asciidoc
  x-pack/functionbeat/docs/deploying.asciidoc
  x-pack/functionbeat/docs/setting-up-running.asciidoc
Labels: Functionbeat, docs, needs_backport, review

#16015 Cherry-pick #15999 to 7.x: Update github.com/magefile/mage to v1.9.0
  NOTICE.txt
  vendor/github.com/magefile/mage/README.md
  vendor/github.com/magefile/mage/go.mod
  vendor/github.com/magefile/mage/mage/main.go
  vendor/github.com/magefile/mage/mage/template.go
  vendor/github.com/magefile/mage/magefile.go
  vendor/github.com/magefile/mage/mg/deps.go
  vendor/github.com/magefile/mage/mg/runtime.go
  vendor/github.com/magefile/mage/sh/cmd.go
  vendor/github.com/magefile/mage/sh/helpers.go
  vendor/github.com/magefile/mage/target/target.go
  vendor/vendor.json
Labels: Team:Beats, [zube]: In Review, backport

#16070 Cherry-pick #16017 to 7.x: Update mage version v1.8.0 to v1.9.0 in Makefile
  dev-tools/make/mage.mk
Labels: Team:Services, [zube]: In Review, backport

#16003 Reduce global logging in some docker/k8s + AD related packages
  libbeat/autodiscover/autodiscover.go
  libbeat/autodiscover/providers/docker/docker.go
  libbeat/autodiscover/providers/docker/docker_integration_test.go
  libbeat/autodiscover/providers/jolokia/discovery.go
  libbeat/autodiscover/providers/kubernetes/node.go
  libbeat/autodiscover/providers/kubernetes/node_test.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/autodiscover/providers/kubernetes/service_test.go
  libbeat/common/bus/bus.go
  libbeat/common/bus/bus_test.go
  libbeat/common/docker/watcher.go
  libbeat/common/docker/watcher_test.go
  libbeat/common/kubernetes/util.go
  libbeat/processors/add_docker_metadata/add_docker_metadata.go
  libbeat/processors/add_docker_metadata/add_docker_metadata_test.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  metricbeat/module/kubernetes/util/kubernetes.go
  x-pack/libbeat/autodiscover/providers/aws/elb/provider_test.go
Labels: Team:Beats, [zube]: In Review, refactoring, review

#16049 [Metricbeat] Update visualization to show last value
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-billing-overview.json
Labels: Metricbeat, Team:Platforms, [zube]: In Review, bug, needs_backport, review

#15835 [docs] Documentation updates from APM
  libbeat/docs/command-reference.asciidoc
  libbeat/docs/security/api-keys.asciidoc
  libbeat/docs/shared-securing-beat.asciidoc
  libbeat/docs/shared-systemd.asciidoc
  libbeat/docs/template-config.asciidoc
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: docs, v7.6.0

#16071 Cherry-pick #16004 to 7.x: [Metricbeat] Add collecting AuroraDB metrics in rds metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/rds/_meta/data.json
  x-pack/metricbeat/module/aws/rds/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/rds/_meta/fields.yml
  x-pack/metricbeat/module/aws/rds/data.go
Labels: backport, review

#16039 [elastic log driver] Use CrossBuild to build binary
  x-pack/dockerlogbeat/Dockerfile
  x-pack/dockerlogbeat/config.json
  x-pack/dockerlogbeat/magefile.go
Labels: bug, needs_backport, v7.6.0

#16080 [7.x][docs] Backport: Recommend env variables rather than keystore for functionbeat …
  libbeat/docs/command-reference.asciidoc
  libbeat/docs/dashboards.asciidoc
  libbeat/docs/https.asciidoc
  libbeat/docs/security/basic-auth.asciidoc
  libbeat/docs/step-configure-credentials.asciidoc
  x-pack/functionbeat/docs/deploying.asciidoc
  x-pack/functionbeat/docs/setting-up-running.asciidoc
Labels: backport, docs, v7.7.0

#16082 [7.6][docs] Backport: Recommend env variables rather than keystore for functionbeat …
  libbeat/docs/command-reference.asciidoc
  libbeat/docs/dashboards.asciidoc
  libbeat/docs/https.asciidoc
  libbeat/docs/security/basic-auth.asciidoc
  libbeat/docs/step-configure-credentials.asciidoc
  x-pack/functionbeat/docs/deploying.asciidoc
  x-pack/functionbeat/docs/setting-up-running.asciidoc
Labels: backport, docs, v7.6.0

#16074 [7.6] Only initialize service URL once (#16044)
  CHANGELOG.next.asciidoc
  metricbeat/module/logstash/node_stats/node_stats.go
Labels: Team:Integrations, [zube]: In Review, backport

#16073 [7.x] Only initialize service URL once (#16044)
  CHANGELOG.next.asciidoc
  metricbeat/module/logstash/node_stats/node_stats.go
Labels: Team:Integrations, [zube]: In Review, backport

#15994 [7.x] Remove redundant wildcard after %{SPACE} patterns (#15900)
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/deprecation/ingest/pipeline-plaintext.json
  filebeat/module/elasticsearch/gc/ingest/pipeline.json
  filebeat/module/elasticsearch/server/ingest/pipeline-plaintext.json
  filebeat/module/elasticsearch/slowlog/ingest/pipeline-json.json
  filebeat/module/elasticsearch/slowlog/ingest/pipeline-plaintext.json
Labels: Team:Integrations, [zube]: In Review, backport

#15995 [7.6] Remove redundant wildcard after %{SPACE} patterns (#15900)
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/deprecation/ingest/pipeline-plaintext.json
  filebeat/module/elasticsearch/gc/ingest/pipeline.json
  filebeat/module/elasticsearch/server/ingest/pipeline-plaintext.json
  filebeat/module/elasticsearch/slowlog/ingest/pipeline-json.json
  filebeat/module/elasticsearch/slowlog/ingest/pipeline-plaintext.json
Labels: Team:Integrations, [zube]: In Review, backport

#16043 [Filebeat] Add ECS tls fields to zeek and aws modules (#15936)
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/aws/elb/ingest/pipeline.yml
  x-pack/filebeat/module/aws/elb/test/example-alb-http.log-expected.json
  x-pack/filebeat/module/aws/elb/test/example-https.log-expected.json
  x-pack/filebeat/module/aws/elb/test/example-nlb-tcp.log-expected.json
  x-pack/filebeat/module/aws/elb/test/example-ssl.log-expected.json
  x-pack/filebeat/module/aws/s3access/ingest/pipeline.yml
  x-pack/filebeat/module/aws/s3access/test/s3_server_access.log-expected.json
  x-pack/filebeat/module/aws/s3access/test/test.log-expected.json
  x-pack/filebeat/module/zeek/rdp/ingest/pipeline.json
  x-pack/filebeat/module/zeek/rdp/test/rdp-json.log-expected.json
  x-pack/filebeat/module/zeek/smtp/ingest/pipeline.json
  x-pack/filebeat/module/zeek/smtp/test/smtp-json.log-expected.json
  x-pack/filebeat/module/zeek/ssl/ingest/pipeline.json
  x-pack/filebeat/module/zeek/ssl/ingest/pipeline.yml
  x-pack/filebeat/module/zeek/ssl/manifest.yml
  x-pack/filebeat/module/zeek/ssl/test/ssl-json.log-expected.json
Labels: Filebeat, Team:SIEM, backport, review

#16088 [Filebeat] fix mapping error for cloudtrail additonalEventData field
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/aws/cloudtrail/ingest/pipeline.yml
  x-pack/filebeat/module/aws/cloudtrail/test/console-login-json.log-expected.json
Labels: Filebeat, Team:SIEM, needs_backport

#16091 Cherry-pick #16049 to 7.6: [Metricbeat] Update visualization to show last value
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-billing-overview.json
Labels: backport, review

#16093 Cherry-pick #16039 to 7.x: [elastic log driver] Use CrossBuild to build binary
  x-pack/dockerlogbeat/Dockerfile
  x-pack/dockerlogbeat/config.json
  x-pack/dockerlogbeat/magefile.go
Labels: backport, bug, review, v7.6.0

#16096 Cherry-pick #16039 to 7.6: [elastic log driver] Use CrossBuild to build binary
  x-pack/dockerlogbeat/Dockerfile
  x-pack/dockerlogbeat/config.json
  x-pack/dockerlogbeat/magefile.go
Labels: backport, review

#16094 Cherry-pick #15935 to 7.x: [Elastic Log Driver] Fix file check bug, deal with logging
  x-pack/dockerlogbeat/handlers.go
  x-pack/dockerlogbeat/magefile.go
  x-pack/dockerlogbeat/main.go
  x-pack/dockerlogbeat/pipelinemanager/libbeattools.go
  x-pack/dockerlogbeat/pipelinemanager/pipelineManager.go
Labels: backport, bug, review, v7.6.0

#15236 User/Group Management Dashboards
  winlogbeat/_meta/fields.common.yml
  winlogbeat/docs/fields.asciidoc
  winlogbeat/include/fields.go
  winlogbeat/scripts/mage/update.go
  x-pack/winlogbeat/module/security/_meta/kibana/7/dashboard/01c54730-fee6-11e9-8405-516218e3d268.json
  x-pack/winlogbeat/module/security/_meta/kibana/7/dashboard/71f720f0-ff18-11e9-8405-516218e3d268.json
  x-pack/winlogbeat/module/security/_meta/kibana/7/dashboard/8223bed0-b9e9-11e9-b6a2-c9b4015c4baf.json
  x-pack/winlogbeat/module/security/_meta/kibana/7/dashboard/bb858830-f412-11e9-8405-516218e3d268.json
Labels: Team:SIEM, Winlogbeat

#16063 Make use of secure port when accessing Kubelet API
  CHANGELOG.next.asciidoc
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Integrations, Team:Platforms, [zube]: In Progress, containers, enhancement, in progress, needs_backport, v7.7.0

#16083 Cherry-pick #16003 to 7.x: Reduce global logging in some docker/k8s + AD related packages
  libbeat/autodiscover/autodiscover.go
  libbeat/autodiscover/providers/docker/docker.go
  libbeat/autodiscover/providers/docker/docker_integration_test.go
  libbeat/autodiscover/providers/jolokia/discovery.go
  libbeat/autodiscover/providers/kubernetes/node.go
  libbeat/autodiscover/providers/kubernetes/node_test.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/autodiscover/providers/kubernetes/service_test.go
  libbeat/common/bus/bus.go
  libbeat/common/bus/bus_test.go
  libbeat/common/docker/watcher.go
  libbeat/common/docker/watcher_test.go
  libbeat/common/kubernetes/util.go
  libbeat/processors/add_docker_metadata/add_docker_metadata.go
  libbeat/processors/add_docker_metadata/add_docker_metadata_test.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  metricbeat/module/kubernetes/util/kubernetes.go
  x-pack/libbeat/autodiscover/providers/aws/elb/provider_test.go
Labels: Team:Beats, [zube]: In Review, backport, review

#16101 Cherry-pick #16063 to 7.x: Make use of secure port when accessing Kubelet API
  CHANGELOG.next.asciidoc
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: backport, review

#11366 packetbeat: Enable setting promiscuous mode automatically
  CHANGELOG.next.asciidoc
  packetbeat/Dockerfile
  packetbeat/Makefile
  packetbeat/_meta/beat.reference.yml
  packetbeat/config/config.go
  packetbeat/docker-compose.yml
  packetbeat/docs/packetbeat-options.asciidoc
  packetbeat/packetbeat.reference.yml
  packetbeat/sniffer/afpacket_linux.go
  packetbeat/sniffer/afpacket_nonlinux.go
  packetbeat/sniffer/sniffer.go
  packetbeat/tests/system/config/packetbeat.yml.j2
  packetbeat/tests/system/test_0069_af_packet.py
Labels: Packetbeat, Team:Beats, [zube]: In Review, review, test-plan, v7.7.0

#16090 Cherry-pick #16049 to 7.x: [Metricbeat] Update visualization to show last value
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-billing-overview.json
Labels: backport, review

#15795 Metricbeat `logstash` module: accept override cluster UUID from Logstash
  CHANGELOG.next.asciidoc
  metricbeat/module/logstash/logstash.go
  metricbeat/module/logstash/logstash_test.go
  metricbeat/module/logstash/node/data_xpack.go
  metricbeat/module/logstash/node/node.go
  metricbeat/module/logstash/node_stats/data_xpack.go
Labels: Metricbeat, Stack monitoring, Team:Integrations, Team:Services, [zube]: In Review, enhancement, module, needs_backport, review, test-plan, v7.7.0, v8.0.0

#16095 Cherry-pick #15935 to 7.6: [Elastic Log Driver] Fix file check bug, deal with logging
  x-pack/dockerlogbeat/config.json
  x-pack/dockerlogbeat/handlers.go
  x-pack/dockerlogbeat/magefile.go
  x-pack/dockerlogbeat/main.go
  x-pack/dockerlogbeat/pipelinemanager/libbeattools.go
  x-pack/dockerlogbeat/pipelinemanager/pipelineManager.go
Labels: backport, bug, review

#15927 Cherry-pick #15883 to 7.x: Change lookup_field to service.address.
  CHANGELOG.next.asciidoc
  metricbeat/processor/add_kubernetes_metadata/indexers.go
Labels: backport, review

#16075 [Filebeat] Update filebeat aws module doc to show all filesets
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
Labels: Filebeat, Team:Platforms, [zube]: In Review, bug, needs_backport, review

#15910 [Filebeat] Add CustomString mapping to CEF for Forcepoint NGFW
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/cef.asciidoc
  x-pack/filebeat/module/cef/_meta/docs.asciidoc
  x-pack/filebeat/module/cef/_meta/fields.yml
  x-pack/filebeat/module/cef/fields.go
  x-pack/filebeat/module/cef/log/_meta/fields.yml
  x-pack/filebeat/module/cef/log/ingest/fp-pipeline.yml
  x-pack/filebeat/module/cef/log/ingest/pipeline.yml
  x-pack/filebeat/module/cef/log/manifest.yml
  x-pack/filebeat/module/cef/log/test/fp-ngfw-smc.log
  x-pack/filebeat/module/cef/log/test/fp-ngfw-smc.log-expected.json
Labels: Filebeat, Team:SIEM, enhancement, needs_backport

#16097 Cherry-pick #16088 to 7.x: [Filebeat] fix mapping error for cloudtrail additonalEventData field
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/aws/cloudtrail/ingest/pipeline.yml
  x-pack/filebeat/module/aws/cloudtrail/test/console-login-json.log-expected.json
Labels: backport, review

#16104 Cherry-pick #11366 to 7.x: packetbeat: Enable setting promiscuous mode automatically
  CHANGELOG.next.asciidoc
  packetbeat/Dockerfile
  packetbeat/Makefile
  packetbeat/_meta/beat.reference.yml
  packetbeat/config/config.go
  packetbeat/docker-compose.yml
  packetbeat/docs/packetbeat-options.asciidoc
  packetbeat/packetbeat.reference.yml
  packetbeat/sniffer/afpacket_linux.go
  packetbeat/sniffer/afpacket_nonlinux.go
  packetbeat/sniffer/sniffer.go
  packetbeat/tests/system/config/packetbeat.yml.j2
  packetbeat/tests/system/test_0069_af_packet.py
Labels: Packetbeat, Team:Beats, [zube]: In Review, backport, test-plan

#16038 Template generation maintenance + remove number of routing shards from default template
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config.reference.yml.tmpl
  libbeat/template/template.go
  libbeat/template/template_test.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Beats, [zube]: In Review, bug, libbeat, needs_backport, review, v7.7.0

#16042 export default kibana client config
  libbeat/kibana/client.go
  libbeat/kibana/client_config.go
Labels: enhancement

#16112 Cherry-pick #16075 to 7.x: [Filebeat] Update filebeat aws module doc to show all filesets
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
Labels: backport, review

#16113 Cherry-pick #16075 to 7.6: [Filebeat] Update filebeat aws module doc to show all filesets
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
Labels: backport, review

#15963 [7.6] Teach `elasticsearch/audit` fileset to handle timestamps correctly (#15942)
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/audit/config/audit.yml
  filebeat/module/elasticsearch/audit/ingest/pipeline-json.json
  filebeat/module/elasticsearch/audit/test/test-audit-711.log
  filebeat/module/elasticsearch/audit/test/test-audit-711.log-expected.json
  filebeat/module/elasticsearch/audit/test/test-audit.log-expected.json
Labels: Team:Integrations, [zube]: In Review, backport

#15993 Updates Metricbeat stack module tests to use require.*
  metricbeat/module/beat/beat_integration_test.go
  metricbeat/module/beat/state/data_test.go
  metricbeat/module/beat/stats/data_test.go
  metricbeat/module/elasticsearch/ccr/data_test.go
  metricbeat/module/elasticsearch/elasticsearch_integration_test.go
  metricbeat/module/elasticsearch/enrich/data_test.go
  metricbeat/module/elasticsearch/index/data_test.go
  metricbeat/module/elasticsearch/index_summary/data_test.go
  metricbeat/module/elasticsearch/node/data_test.go
  metricbeat/module/elasticsearch/node/node_test.go
  metricbeat/module/elasticsearch/pending_tasks/data_test.go
  metricbeat/module/elasticsearch/shard/data_test.go
  metricbeat/module/elasticsearch/testing.go
  metricbeat/module/kibana/kibana_test.go
  metricbeat/module/kibana/stats/data_test.go
  metricbeat/module/kibana/stats/data_xpack_test.go
  metricbeat/module/kibana/stats/stats_integration_test.go
  metricbeat/module/kibana/stats/stats_test.go
  metricbeat/module/kibana/status/data_test.go
  metricbeat/module/kibana/status/status_integration_test.go
  metricbeat/module/logstash/logstash_integration_test.go
  metricbeat/module/logstash/node/data_test.go
  metricbeat/module/logstash/node_stats/data_test.go
Labels: :Testing, Metricbeat, Stack monitoring, Team:Integrations, [zube]: In Review, cleanup, module, needs_backport, refactoring, v7.7.0, v8.0.0

#15655 [docs] Adding clarifications for client based PKI (replaces #9351)
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: docs, libbeat, needs_backport, review

#16014 [Filebeat] Refactor mqtt input
  filebeat/input/mqtt/client.go
  filebeat/input/mqtt/client_mocked.go
  filebeat/input/mqtt/config.go
  filebeat/input/mqtt/input.go
  filebeat/input/mqtt/input_test.go
  filebeat/input/mqtt/logging.go
Labels: Filebeat, Team:Services, [zube]: In Review

#16107 Add documentation about tool dependencies
  docs/devguide/contributing.asciidoc
Labels: Team:Services, [zube]: In Review, docs

#16109 Cherry-pick #16038 to 7.x: Template generation maintenance + remove number of routing shards from default template
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config.reference.yml.tmpl
  libbeat/template/template.go
  libbeat/template/template_test.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Beats, backport, review

#15836 [Filebeat] move create-[module,fileset,fields] to mage
  CHANGELOG.next.asciidoc
  filebeat/Makefile
  filebeat/magefile.go
  filebeat/scripts/generator/fileset/main.go
  filebeat/scripts/mage/generate/fields.go
  filebeat/scripts/mage/generate/fileset.go
  filebeat/scripts/mage/generate/module.go
  x-pack/filebeat/magefile.go
Labels: Filebeat, Team:SIEM, enhancement, needs_backport

#16081 Elasticsearch index must be lowercase
  CHANGELOG.next.asciidoc
  libbeat/outputs/kafka/client.go
  libbeat/outputs/logstash/config.go
  libbeat/outputs/logstash/enc.go
  libbeat/outputs/logstash/logstash_integration_test.go
  libbeat/outputs/outil/select.go
  libbeat/outputs/outil/select_test.go
  libbeat/outputs/redis/client.go
Labels: :Outputs, Team:Beats, [zube]: In Review, libbeat, needs_backport, review, test-plan, v7.7.0

#16117 [7.x][docs] Backport: Add new topic about data deduplication (#15171)
  filebeat/docs/configuring-howto.asciidoc
  libbeat/docs/shared-deduplication.asciidoc
Labels: backport, docs, v7.7.0

#16122 [7.5][docs] Backport: Adding clarifications for client based PKI (replaces #9351) (#…
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: backport, docs, v7.5.0

#16118 [7.6][docs] Backport: Add new topic about data deduplication (#15171)
  filebeat/docs/configuring-howto.asciidoc
  libbeat/docs/shared-deduplication.asciidoc
Labels: backport, docs, v7.6.0

#16119 [7.6][docs] Backport: Adding clarifications for client based PKI (replaces #9351) (#…
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: backport, docs, v7.6.0

#16120 [7.x][docs] Backport: Adding clarifications for client based PKI (replaces #9351) (#…
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: backport, docs, v7.7.0

#15968 [7.x] Adding integration test for logstash Metricbeat module, xpack code path (#15800)
  metricbeat/mb/testing/modules.go
  metricbeat/module/logstash/logstash_integration_test.go
  metricbeat/module/logstash/testing.go
Labels: Team:Integrations, [zube]: In Review, backport

#16144 Modify changelog for 7.6.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
Labels: docs, release, review, v7.6.0

#16139 Regenerate expected files after changes in date parsing
  filebeat/module/system/auth/test/timestamp.log-expected.json
  filebeat/module/system/syslog/test/tz-offset.log-expected.json
Labels: :Testing, Team:Services, [zube]: In Review, needs_backport, review, v7.7.0, v8.0.0

#16152 MQTT: update docs
  filebeat/docs/filebeat-options.asciidoc
  filebeat/docs/inputs/input-mqtt.asciidoc
  filebeat/input/mqtt/config.go
Labels: Filebeat, Team:Services, [zube]: In Review

#15996 [7.5] Remove redundant wildcard after %{SPACE} patterns (#15900)
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/deprecation/ingest/pipeline-plaintext.json
  filebeat/module/elasticsearch/gc/ingest/pipeline.json
  filebeat/module/elasticsearch/server/ingest/pipeline-plaintext.json
  filebeat/module/elasticsearch/slowlog/ingest/pipeline-json.json
  filebeat/module/elasticsearch/slowlog/ingest/pipeline-plaintext.json
Labels: Team:Integrations, [zube]: In Review, backport

#16123 Fix a connection error in httpjson input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/config.go
  x-pack/filebeat/input/httpjson/httpjson_test.go
  x-pack/filebeat/input/httpjson/input.go
Labels: Filebeat, Team:SIEM, bug, needs_backport

#16156 Include document_id in decode_json_fields allowed fields
  libbeat/processors/actions/decode_json_fields.go
Labels: bug, libbeat, needs_backport

#15570 ci: run test on Windows
  .ci/scripts/install-tools.bat
  Jenkinsfile
  dev-tools/make/mage.mk
Labels: [zube]: In Review, automation, ci

#16128 Improve kubernetes.pod.cpu.usage.limit.pct field description
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/pod/_meta/fields.yml
Labels: [zube]: In Review, containers, docs, enhancement, needs_backport, review, v7.5.0, v7.6.0, v7.7.0

#16186 Cherry-pick #16156 to 7.6: Include document_id in decode_json_fields allowed fields
  libbeat/processors/actions/decode_json_fields.go
Labels: backport, review

#16187 Cherry-pick #16156 to 7.x: Include document_id in decode_json_fields allowed fields
  libbeat/processors/actions/decode_json_fields.go
Labels: backport, review

#16142 Cherry-pick #16081 to 7.x: Elasticsearch index must be lowercase
  CHANGELOG.next.asciidoc
  libbeat/outputs/kafka/client.go
  libbeat/outputs/logstash/config.go
  libbeat/outputs/logstash/enc.go
  libbeat/outputs/logstash/logstash_integration_test.go
  libbeat/outputs/outil/select.go
  libbeat/outputs/outil/select_test.go
  libbeat/outputs/redis/client.go
Labels: Team:Beats, backport, review

#16193 Cherry-pick #16128 to 7.6: Improve kubernetes.pod.cpu.usage.limit.pct field description
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/pod/_meta/fields.yml
Labels: backport, review

#16192 Cherry-pick #16128 to 7.x: Improve kubernetes.pod.cpu.usage.limit.pct field description
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/pod/_meta/fields.yml
Labels: backport, review

#16185 Cherry-pick #16123 to 7.x: Fix a connection error in httpjson input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/config.go
  x-pack/filebeat/input/httpjson/httpjson_test.go
  x-pack/filebeat/input/httpjson/input.go
Labels: Filebeat, Team:SIEM, backport, bug, review

#16140 [Filebeat] move create-[module,fileset,fields] to mage (#15836)
  CHANGELOG.next.asciidoc
  filebeat/Makefile
  filebeat/magefile.go
  filebeat/scripts/generator/fileset/main.go
  filebeat/scripts/mage/generate/fields.go
  filebeat/scripts/mage/generate/fileset.go
  filebeat/scripts/mage/generate/module.go
  x-pack/filebeat/magefile.go
Labels: backport, review

#16121 [Filebeat] Add ECS tls & categorization fields to apache module
  CHANGELOG.next.asciidoc
  filebeat/module/apache/access/ingest/default.json
  filebeat/module/apache/access/ingest/pipeline.yml
  filebeat/module/apache/access/manifest.yml
  filebeat/module/apache/access/test/darwin-2.4.23.log-expected.json
  filebeat/module/apache/access/test/ssl-request.log-expected.json
  filebeat/module/apache/access/test/test-vhost.log-expected.json
  filebeat/module/apache/access/test/test.log-expected.json
  filebeat/module/apache/access/test/ubuntu-2.2.22.log-expected.json
  filebeat/module/apache/error/ingest/pipeline.json
  filebeat/module/apache/error/ingest/pipeline.yml
  filebeat/module/apache/error/manifest.yml
  filebeat/module/apache/error/test/darwin-2.4.23.log-expected.json
  filebeat/module/apache/error/test/test.log-expected.json
  filebeat/module/apache/error/test/ubuntu-2.2.22.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement

#16143 MQTT: add integration test
  filebeat/docker-compose.yml
  filebeat/input/mqtt/input.go
  filebeat/input/mqtt/input_test.go
  filebeat/input/mqtt/mqtt_integration_test.go
  testing/environments/docker/mosquitto/Dockerfile
Labels: Filebeat, Team:Services, [zube]: In Review

#14026 [Metricbeat] Add Overview dashboard to Tomcat module
  CHANGELOG.next.asciidoc
  metricbeat/docs/images/metricbeat-tomcat-overview.png
  metricbeat/docs/modules/tomcat.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/tomcat/_meta/docs.asciidoc
  x-pack/metricbeat/module/tomcat/_meta/kibana/7/dashboard/Metricbeat-Tomcat-overview.json
Labels: :Dashboards, Metricbeat, Team:Integrations, Team:Services, [zube]: In Review, enhancement, needs_backport, review, v7.7.0

#15962 [7.x] Teach `elasticsearch/audit` fileset to handle timestamps correctly (#15942)
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/audit/config/audit.yml
  filebeat/module/elasticsearch/audit/ingest/pipeline-json.json
  filebeat/module/elasticsearch/audit/test/test-audit-711.log
  filebeat/module/elasticsearch/audit/test/test-audit-711.log-expected.json
  filebeat/module/elasticsearch/audit/test/test-audit.log-expected.json
Labels: Team:Integrations, [zube]: In Review, backport

#16132 [Metricbeat] Fix PostgreSQL Dashboard
  metricbeat/module/postgresql/_meta/kibana/7/dashboard/Metricbeat-postgresql-overview.json
Labels: Metricbeat, Team:Integrations, Team:Services, [zube]: In Review, bug

#16207 Fix: imports order
  x-pack/libbeat/autodiscover/providers/aws/ec2/provider_test.go
  x-pack/libbeat/autodiscover/providers/aws/elb/provider_test.go
Labels: Team:Services, libbeat

#16194 Cherry-pick #16128 to 7.5: Improve kubernetes.pod.cpu.usage.limit.pct field description
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/pod/_meta/fields.yml
Labels: backport, review

#16145 [Metricbeat]kube-state-metrics: add storage class support
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/docs/modules/kubernetes/state_storageclass.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_docker.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/_meta/config.yml
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_storageclass/README.md
  metricbeat/module/kubernetes/state_storageclass/_meta/data.json
  metricbeat/module/kubernetes/state_storageclass/_meta/docs.asciidoc
  metricbeat/module/kubernetes/state_storageclass/_meta/fields.yml
  metricbeat/module/kubernetes/state_storageclass/_meta/test/ksm.unit.v1.8.0
  metricbeat/module/kubernetes/state_storageclass/_meta/test/ksm.unit.v1.8.0.expected
  metricbeat/module/kubernetes/state_storageclass/_meta/test/ksm.v1.8.0.expected
  metricbeat/module/kubernetes/state_storageclass/state_storageclass.go
  metricbeat/module/kubernetes/state_storageclass/state_storageclass_test.go
  metricbeat/modules.d/kubernetes.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Metricbeat, Team:Platforms, [zube]: In Progress, containers

#16105 [7.x] Metricbeat `logstash` module: accept override cluster UUID from Logstash (#15795)
  CHANGELOG.next.asciidoc
  metricbeat/module/logstash/logstash.go
  metricbeat/module/logstash/logstash_test.go
  metricbeat/module/logstash/node/data_xpack.go
  metricbeat/module/logstash/node/node.go
  metricbeat/module/logstash/node_stats/data_xpack.go
Labels: Team:Integrations, [zube]: In Review, backport

#16116 [Journalbeat] Improve parsing of syslog.pid in journalbeat to strip the username when present
  CHANGELOG.next.asciidoc
  journalbeat/reader/journal.go
  journalbeat/reader/journal_test.go
Labels: Journalbeat, bug, review

#16200 Cherry-pick #16121 to 7.x: [Filebeat] Add ECS tls & categorization fields to apache module
  CHANGELOG.next.asciidoc
  filebeat/module/apache/access/ingest/default.json
  filebeat/module/apache/access/ingest/pipeline.yml
  filebeat/module/apache/access/manifest.yml
  filebeat/module/apache/access/test/darwin-2.4.23.log-expected.json
  filebeat/module/apache/access/test/ssl-request.log-expected.json
  filebeat/module/apache/access/test/test-vhost.log-expected.json
  filebeat/module/apache/access/test/test.log-expected.json
  filebeat/module/apache/access/test/ubuntu-2.2.22.log-expected.json
  filebeat/module/apache/error/ingest/pipeline.json
  filebeat/module/apache/error/ingest/pipeline.yml
  filebeat/module/apache/error/manifest.yml
  filebeat/module/apache/error/test/darwin-2.4.23.log-expected.json
  filebeat/module/apache/error/test/test.log-expected.json
  filebeat/module/apache/error/test/ubuntu-2.2.22.log-expected.json
Labels: backport, review

#16019 [Agent] Allow CA cert pinning on the Elasticsearch output or any code that user tlscommon.TLSConfig builder.
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config.reference.yml.tmpl
  libbeat/common/transport/tlscommon/ca_pinning.go
  libbeat/common/transport/tlscommon/ca_pinning_test.go
  libbeat/common/transport/tlscommon/config.go
  libbeat/common/transport/tlscommon/tls_config.go
  libbeat/docker-compose.yml
  libbeat/docs/shared-ssl-config.asciidoc
  libbeat/scripts/Makefile
  libbeat/tests/system/beat/beat.py
  libbeat/tests/system/test_ca_pinning.py
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  testing/environments/docker/elasticsearch/pki/ca/ca.crt
  testing/environments/docker/elasticsearch/pki/ca/ca.key
  testing/environments/docker/elasticsearch/pki/elasticsearchssl/elasticsearchssl.crt
  testing/environments/docker/elasticsearch/pki/elasticsearchssl/elasticsearchssl.key
  testing/environments/docker/elasticsearch/pki/generate_pki.sh
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Project:fleet, [zube]: In Review, review, test-plan

#16202 [docs] Add 7.6 breaking changes and release highlights
  libbeat/docs/release-notes/breaking/breaking-7.6.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.6.0.asciidoc
Labels: docs, review, v7.6.0

#16213 Cherry-pick #16116 to 7.x: [Journalbeat] Improve parsing of syslog.pid in journalbeat to strip the username when present
  CHANGELOG.next.asciidoc
  journalbeat/reader/journal.go
  journalbeat/reader/journal_test.go
Labels: backport, review

#16218 [7.6][docs] Backport: Add 7.6 breaking changes and release highlights (#16202)
  libbeat/docs/release-notes/breaking/breaking-7.6.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.6.0.asciidoc
Labels: backport, docs, v7.6.0

#15799 [docs] Add early draft of Elastic Log Driver docs
  x-pack/dockerlogbeat/docs/configuration.asciidoc
  x-pack/dockerlogbeat/docs/index.asciidoc
  x-pack/dockerlogbeat/docs/install.asciidoc
  x-pack/dockerlogbeat/docs/limitations.asciidoc
  x-pack/dockerlogbeat/docs/overview.asciidoc
  x-pack/dockerlogbeat/docs/troubleshooting.asciidoc
  x-pack/dockerlogbeat/docs/usage.asciidoc
Labels: docs, v7.6.0

#16220 [7.x][docs] Backport: Add 7.6 breaking changes and release highlights (#16202)
  libbeat/docs/release-notes/breaking/breaking-7.6.asciidoc
  libbeat/docs/release-notes/highlights/highlights-7.6.0.asciidoc
Labels: backport, docs, v7.7.0

#16221 [7.6][docs] Backport: Add early draft of Elastic Log Driver docs (#15799)
  x-pack/dockerlogbeat/docs/configuration.asciidoc
  x-pack/dockerlogbeat/docs/index.asciidoc
  x-pack/dockerlogbeat/docs/install.asciidoc
  x-pack/dockerlogbeat/docs/limitations.asciidoc
  x-pack/dockerlogbeat/docs/overview.asciidoc
  x-pack/dockerlogbeat/docs/troubleshooting.asciidoc
  x-pack/dockerlogbeat/docs/usage.asciidoc
Labels: backport, docs, v7.6.0

#16222 [7.x][docs] Backport: Add early draft of Elastic Log Driver docs (#15799)
  x-pack/dockerlogbeat/docs/configuration.asciidoc
  x-pack/dockerlogbeat/docs/index.asciidoc
  x-pack/dockerlogbeat/docs/install.asciidoc
  x-pack/dockerlogbeat/docs/limitations.asciidoc
  x-pack/dockerlogbeat/docs/overview.asciidoc
  x-pack/dockerlogbeat/docs/troubleshooting.asciidoc
  x-pack/dockerlogbeat/docs/usage.asciidoc
Labels: backport, docs, v7.7.0

#16124 Index template will only be loaded if the configured output is Elasticsearch or Elastic Cloud
  libbeat/docs/template-config.asciidoc
Labels: docs, needs_backport

#16223 [7.6][docs] Backport: Index template will only be loaded if the configured output is Elasticsearch
  libbeat/docs/template-config.asciidoc
Labels: backport, docs, v7.6.0

#16225 [master][docs] Forward port: Index template will only be loaded if the configured output is Elasti…
  libbeat/docs/template-config.asciidoc
Labels: backport, docs

#16224 [7.x][docs] Backport: Index template will only be loaded if the configured output is Elasticsearch
  libbeat/docs/template-config.asciidoc
Labels: backport, docs, v7.6.0

#16211 Cherry-pick #16145 to 7.x: [Metricbeat]kube-state-metrics: add storage class support
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/docs/modules/kubernetes/state_storageclass.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_docker.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/_meta/config.yml
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_storageclass/README.md
  metricbeat/module/kubernetes/state_storageclass/_meta/data.json
  metricbeat/module/kubernetes/state_storageclass/_meta/docs.asciidoc
  metricbeat/module/kubernetes/state_storageclass/_meta/fields.yml
  metricbeat/module/kubernetes/state_storageclass/_meta/test/ksm.unit.v1.8.0
  metricbeat/module/kubernetes/state_storageclass/_meta/test/ksm.unit.v1.8.0.expected
  metricbeat/module/kubernetes/state_storageclass/_meta/test/ksm.v1.8.0.expected
  metricbeat/module/kubernetes/state_storageclass/state_storageclass.go
  metricbeat/module/kubernetes/state_storageclass/state_storageclass_test.go
  metricbeat/modules.d/kubernetes.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: backport, review

#15600 Bump version to 7.6.1
  libbeat/version/version.go
Labels: in progress, release, review, v7.6.1

#15940 Agent Configuration examples
  x-pack/agent/docs/agent_configuration_example.yml
Labels: Project:fleet, [zube]: In Progress, review

#16229 [docs] Set release state to released
  libbeat/docs/version.asciidoc
Labels: docs, libbeat

#16233 Remove spaces in prometheus commented out option
  metricbeat/docs/modules/prometheus.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/prometheus/_meta/config.yml
  metricbeat/modules.d/prometheus.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Platforms, Team:Services, [zube]: Inbox, docs, needs_backport, review

#16205 Fix: don't miss address scheme
  CHANGELOG.next.asciidoc
  metricbeat/mb/lightmetricset.go
  metricbeat/mb/lightmodules_test.go
  metricbeat/mb/testdata/lightmodules/httpextended/extends/manifest.yml
  metricbeat/mb/testdata/lightmodules/httpextended/module.yml
Labels: Metricbeat, Team:Services, [zube]: In Review, bug

#16241 Cherry-pick #16205 to 7.x: Fix: don't miss address scheme
  CHANGELOG.next.asciidoc
  metricbeat/mb/lightmetricset.go
  metricbeat/mb/lightmodules_test.go
  metricbeat/mb/testdata/lightmodules/httpextended/extends/manifest.yml
  metricbeat/mb/testdata/lightmodules/httpextended/module.yml
Labels: backport, review

#16235 Freeze virtualenv version until issue with CI is resolved
  .travis.yml
Labels: Team:Platforms, [zube]: Inbox, review

#16008 [7.x] Adding integration test for elasticsearch Metricbeat module, xpack code path (#15975)
  metricbeat/module/elasticsearch/elasticsearch_integration_test.go
Labels: Team:Integrations, [zube]: In Review, backport

#16141 Use mage target instead of nosetests on Windows jenkins CI
  dev-tools/jenkins_ci.ps1
  filebeat/tests/open-file-handlers/log_stdout.py
  filebeat/tests/system/test_crawler.py
  filebeat/tests/system/test_load.py
  heartbeat/magefile.go
  journalbeat/magefile.go
  libbeat/magefile.go
  libbeat/tests/system/requirements.txt
  script/kibana-migration.py
  script/renamed_fields.py
  x-pack/libbeat/magefile.go
Labels: :Testing, :Windows

#16249 [docs] Fix install command to match instructions on docker hub
  x-pack/dockerlogbeat/docs/install.asciidoc
Labels: docs, review, v7.6.0

#16246 [docs] Add link to observability release blog
  libbeat/docs/release-notes/highlights/highlights-7.6.0.asciidoc
Labels: docs, libbeat, needs_backport, review

#16251 [7.6][docs] Backport: Fix install command to match instructions on docker hub (#16249)
  x-pack/dockerlogbeat/docs/install.asciidoc
Labels: backport, docs, v7.6.0

#16130 ci(jenkins): enable fix-permissions to be executed without running make too
  Jenkinsfile
  libbeat/scripts/Makefile
  script/fix_permissions.sh
Labels: automation, ci

#16188 Cherry-pick #16123 to 7.6: Fix a connection error in httpjson input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/config.go
  x-pack/filebeat/input/httpjson/httpjson_test.go
  x-pack/filebeat/input/httpjson/input.go
Labels: Filebeat, Team:SIEM, backport, bug, review

#16199 Upgrade go-ucfg to version 0.8.2
  NOTICE.txt
  filebeat/fileset/modules_test.go
  metricbeat/mb/lightmodules_test.go
  metricbeat/mb/mb_test.go
  metricbeat/module/prometheus/collector/_meta/data.json
  vendor/github.com/elastic/go-ucfg/CHANGELOG.md
  vendor/github.com/elastic/go-ucfg/error.go
  vendor/github.com/elastic/go-ucfg/reify.go
  vendor/github.com/elastic/go-ucfg/validator.go
  vendor/vendor.json
Labels: libbeat

#16255 [7.6][docs] Backport: Add link to observability release blog (#16246)
  libbeat/docs/release-notes/highlights/highlights-7.6.0.asciidoc
Labels: backport, docs, v7.6.0
