Repository elastic/beats, pull requests merged in 2020-03, with the labels that each got.

#16654 [Libbeat] Use *logp.Logger in libbeat processors
  libbeat/processors/actions/copy_fields.go
  libbeat/processors/actions/copy_fields_test.go
  libbeat/processors/actions/decode_json_fields.go
  libbeat/processors/actions/decode_json_fields_test.go
  libbeat/processors/actions/rename.go
  libbeat/processors/actions/rename_test.go
  libbeat/processors/actions/truncate_fields.go
  libbeat/processors/actions/truncate_fields_test.go
  libbeat/processors/add_cloud_metadata/add_cloud_metadata.go
  libbeat/processors/add_cloud_metadata/providers.go
  libbeat/processors/add_host_metadata/add_host_metadata.go
  libbeat/processors/add_locale/add_locale_test.go
  libbeat/processors/add_observer_metadata/add_observer_metadata.go
Labels: Team:Beats, [zube]: In Review, needs_backport, refactoring, review

#12867 Add "mechanism" in output.kafka to support SCRAM-SHA-512 and SCRAM-SHA-256
  libbeat/outputs/kafka/config.go
  libbeat/outputs/kafka/scram.go
Labels: :Outputs, Team:Services, [zube]: In Review, libbeat, review

#16327 [Agent] Include agentID in event payload
  x-pack/agent/pkg/agent/application/fleet_acker.go
  x-pack/agent/pkg/agent/application/fleet_gateway_test.go
  x-pack/agent/pkg/fleetapi/ack_cmd.go
  x-pack/agent/pkg/reporter/event.go
  x-pack/agent/pkg/reporter/fleet/reporter.go
  x-pack/agent/pkg/reporter/fleet/reporter_test.go
  x-pack/agent/pkg/reporter/log/reporter.go
  x-pack/agent/pkg/reporter/log/reporter_test.go
Labels: Project:fleet, agent

#16722 Cherry-pick #15503 to 7.x: Move pdh query to shared location in order for new modules/metricsets to reuse
  CHANGELOG.next.asciidoc
  metricbeat/helper/windows/pdh/defs_pdh_windows.go
  metricbeat/helper/windows/pdh/defs_pdh_windows_386.go
  metricbeat/helper/windows/pdh/defs_pdh_windows_amd64.go
  metricbeat/helper/windows/pdh/doc.go
  metricbeat/helper/windows/pdh/mkpdh_defs.go
  metricbeat/helper/windows/pdh/pdh_query_windows.go
  metricbeat/helper/windows/pdh/pdh_query_windows_test.go
  metricbeat/helper/windows/pdh/pdh_windows.go
  metricbeat/helper/windows/pdh/pdh_windows_test.go
  metricbeat/helper/windows/pdh/zpdh_windows.go
  metricbeat/helper/windows/run.go
  metricbeat/module/windows/perfmon/doc.go
  metricbeat/module/windows/perfmon/perfmon.go
  metricbeat/module/windows/perfmon/perfmon_test.go
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/reader_test.go
  metricbeat/module/windows/service/doc.go
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, backport

#16690 Cherry-pick #15059 to 7.x: Add metricbeat iis module
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/iis.asciidoc
  metricbeat/docs/modules/iis/application_pool.asciidoc
  metricbeat/docs/modules/iis/webserver.asciidoc
  metricbeat/docs/modules/iis/website.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/helper/windows/pdh/pdh_query_windows.go
  metricbeat/helper/windows/pdh/pdh_windows.go
  metricbeat/helper/windows/pdh/zpdh_windows.go
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/iis/_meta/config.yml
  metricbeat/module/iis/_meta/docs.asciidoc
  metricbeat/module/iis/_meta/fields.yml
  metricbeat/module/iis/application_pool/_meta/data.json
  metricbeat/module/iis/application_pool/_meta/docs.asciidoc
  metricbeat/module/iis/application_pool/_meta/fields.yml
  metricbeat/module/iis/application_pool/application_pool.go
  metricbeat/module/iis/application_pool/application_pool_test.go
  metricbeat/module/iis/application_pool/doc.go
  metricbeat/module/iis/application_pool/reader.go
  metricbeat/module/iis/application_pool/reader_test.go
  metricbeat/module/iis/doc.go
  metricbeat/module/iis/fields.go
  metricbeat/module/iis/module.yml
  metricbeat/module/iis/webserver/_meta/data.json
  metricbeat/module/iis/webserver/_meta/docs.asciidoc
  metricbeat/module/iis/webserver/_meta/fields.yml
  metricbeat/module/iis/webserver/doc.go
  metricbeat/module/iis/webserver/manifest.yml
  metricbeat/module/iis/webserver/webserver_integration_test.go
  metricbeat/module/iis/webserver/webserver_test.go
  metricbeat/module/iis/website/_meta/data.json
  metricbeat/module/iis/website/_meta/docs.asciidoc
  metricbeat/module/iis/website/_meta/fields.yml
  metricbeat/module/iis/website/doc.go
  metricbeat/module/iis/website/manifest.yml
  metricbeat/module/iis/website/website_integration_test.go
  metricbeat/module/iis/website/website_test.go
  metricbeat/module/windows/perfmon/_meta/docs.asciidoc
  metricbeat/module/windows/perfmon/perfmon.go
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/reader_test.go
  metricbeat/modules.d/iis.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, backport

#16624 Agent required changes for building the agent artifacts
  dev-tools/mage/common.go
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgspecs.go
  dev-tools/mage/pkgtypes.go
  dev-tools/packaging/packages.yml
Labels: Project:fleet, [zube]: In Review, needs_backport, review

#16685 Cherry-pick #16681 to 7.x: Close files earlier when generating fields files
  libbeat/generator/fields/fields.go
Labels: backport, review

#16618 [Filebeat] Improve ECS categorization field mappings in iis module
  CHANGELOG.next.asciidoc
  filebeat/module/iis/access/ingest/default.json
  filebeat/module/iis/access/ingest/pipeline.yml
  filebeat/module/iis/access/manifest.yml
  filebeat/module/iis/access/test/test-iis-7.2.log-expected.json
  filebeat/module/iis/access/test/test-iis-7.5.log-expected.json
  filebeat/module/iis/access/test/test-ipv6zone.log-expected.json
  filebeat/module/iis/access/test/test.log-expected.json
  filebeat/module/iis/error/ingest/default.json
  filebeat/module/iis/error/ingest/pipeline.yml
  filebeat/module/iis/error/manifest.yml
  filebeat/module/iis/error/test/iis_error_url.log-expected.json
  filebeat/module/iis/error/test/ipv6_zone_id.log-expected.json
  filebeat/module/iis/error/test/test.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, needs_backport

#16686 Cherry-pick #16440 to 7.x: [libbeat] Fix / clarify the module reload logic
  CHANGELOG.next.asciidoc
  heartbeat/tests/system/test_reload.py
  libbeat/cfgfile/reload.go
  libbeat/cfgfile/reload_test.go
  libbeat/docs/http-endpoint.asciidoc
  libbeat/tests/system/test_http.py
  metricbeat/module/beat/stats/_meta/test/stats.800.json
  metricbeat/tests/system/test_reload.py
Labels: backport, review

#16671 Add cloudfoundry module to metricbeat
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/cloudfoundry.asciidoc
  metricbeat/docs/modules/cloudfoundry/container.asciidoc
  metricbeat/docs/modules/cloudfoundry/counter.asciidoc
  metricbeat/docs/modules/cloudfoundry/value.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/cloudfoundry/_meta/config.reference.yml
  x-pack/metricbeat/module/cloudfoundry/_meta/config.yml
  x-pack/metricbeat/module/cloudfoundry/_meta/docs.asciidoc
  x-pack/metricbeat/module/cloudfoundry/_meta/fields.yml
  x-pack/metricbeat/module/cloudfoundry/cloudfoundry.go
  x-pack/metricbeat/module/cloudfoundry/container/_meta/data.json
  x-pack/metricbeat/module/cloudfoundry/container/_meta/docs.asciidoc
  x-pack/metricbeat/module/cloudfoundry/container/_meta/fields.yml
  x-pack/metricbeat/module/cloudfoundry/container/container.go
  x-pack/metricbeat/module/cloudfoundry/counter/_meta/data.json
  x-pack/metricbeat/module/cloudfoundry/counter/_meta/docs.asciidoc
  x-pack/metricbeat/module/cloudfoundry/counter/_meta/fields.yml
  x-pack/metricbeat/module/cloudfoundry/counter/counter.go
  x-pack/metricbeat/module/cloudfoundry/doc.go
  x-pack/metricbeat/module/cloudfoundry/fields.go
  x-pack/metricbeat/module/cloudfoundry/module.yml
  x-pack/metricbeat/module/cloudfoundry/value/_meta/data.json
  x-pack/metricbeat/module/cloudfoundry/value/_meta/docs.asciidoc
  x-pack/metricbeat/module/cloudfoundry/value/_meta/fields.yml
  x-pack/metricbeat/module/cloudfoundry/value/value.go
  x-pack/metricbeat/modules.d/cloudfoundry.yml.disabled
Labels: Team:Platforms, [zube]: In Review, enhancement, review

#16645 [Filebeat] Improve ECS categorization field mapping in kafka module
  CHANGELOG.next.asciidoc
  filebeat/module/kafka/log/ingest/pipeline.json
  filebeat/module/kafka/log/ingest/pipeline.yml
  filebeat/module/kafka/log/manifest.yml
  filebeat/module/kafka/log/test/controller-2.0.0.log-expected.json
  filebeat/module/kafka/log/test/controller.log-expected.json
  filebeat/module/kafka/log/test/server-2.0.0.log-expected.json
  filebeat/module/kafka/log/test/server.log-expected.json
  filebeat/module/kafka/log/test/state-change-1.1.0.log-expected.json
  filebeat/module/kafka/log/test/state-change-2.0.0.log-expected.json
  filebeat/module/kafka/log/test/state-change.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, needs_backport

#16743 [7.x][docs] Backport: Add abbreviated titles for a cleaner nav (#16537)
  libbeat/processors/actions/docs/add_fields.asciidoc
  libbeat/processors/actions/docs/add_labels.asciidoc
  libbeat/processors/actions/docs/add_tags.asciidoc
  libbeat/processors/actions/docs/copy_fields.asciidoc
  libbeat/processors/actions/docs/decode_base64_field.asciidoc
  libbeat/processors/actions/docs/decode_json_fields.asciidoc
  libbeat/processors/actions/docs/decompress_gzip_field.asciidoc
  libbeat/processors/actions/docs/drop_event.asciidoc
  libbeat/processors/actions/docs/drop_fields.asciidoc
  libbeat/processors/actions/docs/include_fields.asciidoc
  libbeat/processors/actions/docs/placeholder.asciidoc
  libbeat/processors/actions/docs/rename.asciidoc
  libbeat/processors/actions/docs/truncate_fields.asciidoc
  libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc
  libbeat/processors/add_docker_metadata/docs/add_docker_metadata.asciidoc
  libbeat/processors/add_host_metadata/docs/add_host_metadata.asciidoc
  libbeat/processors/add_id/docs/add_id.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  libbeat/processors/add_locale/docs/add_locale.asciidoc
  libbeat/processors/add_observer_metadata/docs/add_observer_metadata.asciidoc
  libbeat/processors/add_process_metadata/docs/add_process_metadata.asciidoc
  libbeat/processors/communityid/docs/communityid.asciidoc
  libbeat/processors/convert/docs/convert.asciidoc
  libbeat/processors/decode_csv_fields/docs/decode_csv_fields.asciidoc
  libbeat/processors/dissect/docs/dissect.asciidoc
  libbeat/processors/dns/docs/dns.asciidoc
  libbeat/processors/extract_array/docs/extract_array.asciidoc
  libbeat/processors/fingerprint/docs/fingerprint.asciidoc
  libbeat/processors/registered_domain/docs/registered_domain.asciidoc
  libbeat/processors/script/docs/script.asciidoc
  libbeat/processors/timestamp/docs/timestamp.asciidoc
  x-pack/filebeat/processors/decode_cef/docs/decode_cef.asciidoc
  x-pack/filebeat/processors/decode_cef/docs/placeholder.asciidoc
Labels: backport, docs, v7.7.0

#16744 [7.6][docs] Backport: Add abbreviated titles for a cleaner nav (#16537)
  libbeat/processors/actions/docs/add_fields.asciidoc
  libbeat/processors/actions/docs/add_labels.asciidoc
  libbeat/processors/actions/docs/add_tags.asciidoc
  libbeat/processors/actions/docs/copy_fields.asciidoc
  libbeat/processors/actions/docs/decode_base64_field.asciidoc
  libbeat/processors/actions/docs/decode_json_fields.asciidoc
  libbeat/processors/actions/docs/decompress_gzip_field.asciidoc
  libbeat/processors/actions/docs/drop_event.asciidoc
  libbeat/processors/actions/docs/drop_fields.asciidoc
  libbeat/processors/actions/docs/include_fields.asciidoc
  libbeat/processors/actions/docs/placeholder.asciidoc
  libbeat/processors/actions/docs/rename.asciidoc
  libbeat/processors/actions/docs/truncate_fields.asciidoc
  libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc
  libbeat/processors/add_docker_metadata/docs/add_docker_metadata.asciidoc
  libbeat/processors/add_host_metadata/docs/add_host_metadata.asciidoc
  libbeat/processors/add_id/docs/add_id.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  libbeat/processors/add_locale/docs/add_locale.asciidoc
  libbeat/processors/add_observer_metadata/docs/add_observer_metadata.asciidoc
  libbeat/processors/add_process_metadata/docs/add_process_metadata.asciidoc
  libbeat/processors/communityid/docs/communityid.asciidoc
  libbeat/processors/convert/docs/convert.asciidoc
  libbeat/processors/decode_csv_fields/docs/decode_csv_fields.asciidoc
  libbeat/processors/dissect/docs/dissect.asciidoc
  libbeat/processors/dns/docs/dns.asciidoc
  libbeat/processors/extract_array/docs/extract_array.asciidoc
  libbeat/processors/fingerprint/docs/fingerprint.asciidoc
  libbeat/processors/registered_domain/docs/registered_domain.asciidoc
  libbeat/processors/script/docs/script.asciidoc
  libbeat/processors/timestamp/docs/timestamp.asciidoc
  x-pack/filebeat/processors/decode_cef/docs/decode_cef.asciidoc
  x-pack/filebeat/processors/decode_cef/docs/placeholder.asciidoc
Labels: backport, docs, v7.6.0

#16747 [7.6][docs] Forward port: fix pattern for java stacktrace (#13516)
  filebeat/docs/multiline.asciidoc
Labels: backport, docs, v7.6.0

#16746 [7.x][docs] Forward port: fix pattern for java stacktrace (#13516)
  filebeat/docs/multiline.asciidoc
Labels: backport, docs, v7.7.0

#16721 [Redis Enterprise] Fix flaky: wait for metrics to be emitted
  x-pack/metricbeat/module/redisenterprise/_meta/healthcheck.sh
Labels: Metricbeat

#16421 Add container azure metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/azure.asciidoc
  metricbeat/docs/modules/azure/container_instance.asciidoc
  metricbeat/docs/modules/azure/container_registry.asciidoc
  metricbeat/docs/modules/azure/container_service.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/azure/_meta/config.reference.yml
  x-pack/metricbeat/module/azure/_meta/config.yml
  x-pack/metricbeat/module/azure/azure.go
  x-pack/metricbeat/module/azure/client.go
  x-pack/metricbeat/module/azure/client_utils.go
  x-pack/metricbeat/module/azure/client_utils_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper_test.go
  x-pack/metricbeat/module/azure/container_instance/_meta/data.json
  x-pack/metricbeat/module/azure/container_instance/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_instance/_meta/fields.yml
  x-pack/metricbeat/module/azure/container_instance/container_instance_integration_test.go
  x-pack/metricbeat/module/azure/container_instance/container_instance_test.go
  x-pack/metricbeat/module/azure/container_instance/manifest.yml
  x-pack/metricbeat/module/azure/container_registry/_meta/data.json
  x-pack/metricbeat/module/azure/container_registry/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_registry/_meta/fields.yml
  x-pack/metricbeat/module/azure/container_registry/container_registry_integration_test.go
  x-pack/metricbeat/module/azure/container_registry/container_registry_test.go
  x-pack/metricbeat/module/azure/container_registry/manifest.yml
  x-pack/metricbeat/module/azure/container_service/_meta/data.json
  x-pack/metricbeat/module/azure/container_service/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_service/_meta/fields.yml
  x-pack/metricbeat/module/azure/container_service/container_service_integration_test.go
  x-pack/metricbeat/module/azure/container_service/container_service_test.go
  x-pack/metricbeat/module/azure/container_service/manifest.yml
  x-pack/metricbeat/module/azure/data.go
  x-pack/metricbeat/module/azure/data_test.go
  x-pack/metricbeat/module/azure/fields.go
  x-pack/metricbeat/module/azure/module.yml
  x-pack/metricbeat/modules.d/azure.yml.disabled
Labels: Metricbeat, Team:Integrations, Team:Platforms, [zube]: In Review

#16731 [Metricbeat] Add documentation for tags_filter and tags
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/aws/_meta/config.reference.yml
  x-pack/metricbeat/module/aws/cloudwatch/_meta/docs.asciidoc
Labels: Metricbeat, Team:Platforms, [zube]: Inbox, docs, needs_backport, review

#16719 Cherry-pick #16654 to 7.x: [Libbeat] Use *logp.Logger in libbeat processors
  libbeat/processors/actions/copy_fields.go
  libbeat/processors/actions/copy_fields_test.go
  libbeat/processors/actions/decode_json_fields.go
  libbeat/processors/actions/decode_json_fields_test.go
  libbeat/processors/actions/rename.go
  libbeat/processors/actions/rename_test.go
  libbeat/processors/actions/truncate_fields.go
  libbeat/processors/actions/truncate_fields_test.go
  libbeat/processors/add_cloud_metadata/add_cloud_metadata.go
  libbeat/processors/add_cloud_metadata/providers.go
  libbeat/processors/add_host_metadata/add_host_metadata.go
  libbeat/processors/add_locale/add_locale_test.go
  libbeat/processors/add_observer_metadata/add_observer_metadata.go
Labels: backport, review

#16751 Cherry-pick #16482 to 7.x: [Metricbeat] Redis Enterprise: add "node" and "proxy" metricsets
  CHANGELOG.next.asciidoc
  libbeat/tests/compose/compose.go
  libbeat/tests/compose/project.go
  libbeat/tests/compose/wrapper.go
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/redis.asciidoc
  metricbeat/docs/modules/redisenterprise.asciidoc
  metricbeat/docs/modules/redisenterprise/node.asciidoc
  metricbeat/docs/modules/redisenterprise/proxy.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/module/redis/_meta/docs.asciidoc
  metricbeat/module/redis/docker-compose.yml
  metricbeat/module/redis/module.yml
  metricbeat/module/redis/test_redis.py
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/redisenterprise/_meta/Dockerfile
  x-pack/metricbeat/module/redisenterprise/_meta/config.reference.yml
  x-pack/metricbeat/module/redisenterprise/_meta/config.yml
  x-pack/metricbeat/module/redisenterprise/_meta/docs.asciidoc
  x-pack/metricbeat/module/redisenterprise/_meta/fields.yml
  x-pack/metricbeat/module/redisenterprise/_meta/healthcheck.sh
  x-pack/metricbeat/module/redisenterprise/_meta/supported-versions.yml
  x-pack/metricbeat/module/redisenterprise/docker-compose.yml
  x-pack/metricbeat/module/redisenterprise/fields.go
  x-pack/metricbeat/module/redisenterprise/module.yml
  x-pack/metricbeat/module/redisenterprise/node/_meta/data.json
  x-pack/metricbeat/module/redisenterprise/node/_meta/docs.asciidoc
  x-pack/metricbeat/module/redisenterprise/node/_meta/fields.yml
  x-pack/metricbeat/module/redisenterprise/node/_meta/testdata/config.yml
  x-pack/metricbeat/module/redisenterprise/node/_meta/testdata/redis-node.5.4.10-22.plain
  x-pack/metricbeat/module/redisenterprise/node/_meta/testdata/redis-node.5.4.10-22.plain-expected.json
  x-pack/metricbeat/module/redisenterprise/node/manifest.yml
  x-pack/metricbeat/module/redisenterprise/node/node_integration_test.go
  x-pack/metricbeat/module/redisenterprise/node/node_test.go
  x-pack/metricbeat/module/redisenterprise/proxy/_meta/data.json
  x-pack/metricbeat/module/redisenterprise/proxy/_meta/docs.asciidoc
  x-pack/metricbeat/module/redisenterprise/proxy/_meta/fields.yml
  x-pack/metricbeat/module/redisenterprise/proxy/_meta/testdata/config.yml
  x-pack/metricbeat/module/redisenterprise/proxy/_meta/testdata/redis-proxy.5.4.10-22.plain
  x-pack/metricbeat/module/redisenterprise/proxy/_meta/testdata/redis-proxy.5.4.10-22.plain-expected.json
  x-pack/metricbeat/module/redisenterprise/proxy/manifest.yml
  x-pack/metricbeat/module/redisenterprise/proxy/proxy_integration_test.go
  x-pack/metricbeat/module/redisenterprise/proxy/proxy_test.go
  x-pack/metricbeat/module/redisenterprise/test_redisenterprise.py
  x-pack/metricbeat/modules.d/redisenterprise.yml.disabled
Labels: backport, review

#16756 Fix imports for previous PR
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/container_instance/container_instance_integration_test.go
  x-pack/metricbeat/module/azure/container_instance/container_instance_test.go
  x-pack/metricbeat/module/azure/container_registry/container_registry_integration_test.go
  x-pack/metricbeat/module/azure/container_registry/container_registry_test.go
  x-pack/metricbeat/module/azure/container_service/container_service_integration_test.go
  x-pack/metricbeat/module/azure/container_service/container_service_test.go
  x-pack/metricbeat/module/azure/data_test.go
Labels: Team:Integrations, Team:Platforms

#16652 [Filebeat] Improve ECS categorization field mappings in kibana module
  CHANGELOG.next.asciidoc
  filebeat/module/kibana/log/ingest/pipeline.json
  filebeat/module/kibana/log/ingest/pipeline.yml
  filebeat/module/kibana/log/manifest.yml
  filebeat/module/kibana/log/test/log.624.log-expected.json
  filebeat/module/kibana/log/test/log.verbose.624.log-expected.json
  filebeat/module/kibana/log/test/test.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, needs_backport

#16687 Cherry-pick #16440 to 7.6: [libbeat] Fix / clarify the module reload logic
  CHANGELOG.next.asciidoc
  heartbeat/tests/system/test_reload.py
  libbeat/cfgfile/reload.go
  libbeat/cfgfile/reload_test.go
  libbeat/docs/http-endpoint.asciidoc
  libbeat/tests/system/test_http.py
  metricbeat/module/beat/stats/_meta/test/stats.800.json
  metricbeat/tests/system/test_reload.py
Labels: backport, review

#16766 Fix zeek pipelines to include millisecond precision
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/zeek/files/ingest/pipeline.json
  x-pack/filebeat/module/zeek/files/test/files-json.log-expected.json
  x-pack/filebeat/module/zeek/http/ingest/pipeline.json
  x-pack/filebeat/module/zeek/http/test/http-json.log-expected.json
  x-pack/filebeat/module/zeek/notice/ingest/pipeline.json
  x-pack/filebeat/module/zeek/notice/test/notice-json.log-expected.json
Labels: Filebeat, Team:SIEM, bug, needs_backport, review

#16759 Cherry-pick #16731 to 7.x: [Metricbeat] Add documentation for tags_filter and tags
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/aws/_meta/config.reference.yml
  x-pack/metricbeat/module/aws/cloudwatch/_meta/docs.asciidoc
Labels: backport, review

#16755 Cherry-pick #16421 to 7.x: Add container azure metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/azure.asciidoc
  metricbeat/docs/modules/azure/container_instance.asciidoc
  metricbeat/docs/modules/azure/container_registry.asciidoc
  metricbeat/docs/modules/azure/container_service.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/azure/_meta/config.reference.yml
  x-pack/metricbeat/module/azure/_meta/config.yml
  x-pack/metricbeat/module/azure/azure.go
  x-pack/metricbeat/module/azure/client.go
  x-pack/metricbeat/module/azure/client_utils.go
  x-pack/metricbeat/module/azure/client_utils_test.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper.go
  x-pack/metricbeat/module/azure/compute_vm_scaleset/client_helper_test.go
  x-pack/metricbeat/module/azure/container_instance/_meta/data.json
  x-pack/metricbeat/module/azure/container_instance/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_instance/_meta/fields.yml
  x-pack/metricbeat/module/azure/container_instance/container_instance_integration_test.go
  x-pack/metricbeat/module/azure/container_instance/container_instance_test.go
  x-pack/metricbeat/module/azure/container_instance/manifest.yml
  x-pack/metricbeat/module/azure/container_registry/_meta/data.json
  x-pack/metricbeat/module/azure/container_registry/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_registry/_meta/fields.yml
  x-pack/metricbeat/module/azure/container_registry/container_registry_integration_test.go
  x-pack/metricbeat/module/azure/container_registry/container_registry_test.go
  x-pack/metricbeat/module/azure/container_registry/manifest.yml
  x-pack/metricbeat/module/azure/container_service/_meta/data.json
  x-pack/metricbeat/module/azure/container_service/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/container_service/_meta/fields.yml
  x-pack/metricbeat/module/azure/container_service/container_service_integration_test.go
  x-pack/metricbeat/module/azure/container_service/container_service_test.go
  x-pack/metricbeat/module/azure/container_service/manifest.yml
  x-pack/metricbeat/module/azure/data.go
  x-pack/metricbeat/module/azure/data_test.go
  x-pack/metricbeat/module/azure/fields.go
  x-pack/metricbeat/module/azure/module.yml
  x-pack/metricbeat/modules.d/azure.yml.disabled
Labels: Team:Integrations, Team:Platforms, [zube]: In Review

#13808 Fix renaming cloud metadata processor fields
  CHANGELOG.next.asciidoc
  libbeat/processors/add_cloud_metadata/add_cloud_metadata.go
Labels: Team:Platforms, [zube]: In Review, bug, libbeat, needs_backport, review

#16764 [Libbeat] Add v7 into libbeat/logp when importing
  libbeat/processors/actions/copy_fields_test.go
  libbeat/processors/actions/rename_test.go
  libbeat/processors/actions/truncate_fields_test.go
Labels: review

#16689 [7.6] Adding missing metricset to list (#16401)
  metricbeat/docs/modules/elasticsearch.asciidoc
  metricbeat/module/elasticsearch/_meta/docs.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#16769 Cherry-pick #16766 to 7.x: Fix zeek pipelines to include millisecond precision
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/zeek/files/ingest/pipeline.json
  x-pack/filebeat/module/zeek/files/test/files-json.log-expected.json
  x-pack/filebeat/module/zeek/http/ingest/pipeline.json
  x-pack/filebeat/module/zeek/http/test/http-json.log-expected.json
  x-pack/filebeat/module/zeek/notice/ingest/pipeline.json
  x-pack/filebeat/module/zeek/notice/test/notice-json.log-expected.json
Labels: Filebeat, Team:SIEM, backport, review

#16703 [docs] Add username and password to haproxy example
  metricbeat/metricbeat.reference.yml
  metricbeat/module/haproxy/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Integrations, docs, libbeat, review

#16741 Cherry-pick #16671 to 7.x: Add cloudfoundry module to metricbeat
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/cloudfoundry.asciidoc
  metricbeat/docs/modules/cloudfoundry/container.asciidoc
  metricbeat/docs/modules/cloudfoundry/counter.asciidoc
  metricbeat/docs/modules/cloudfoundry/value.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/cloudfoundry/_meta/config.reference.yml
  x-pack/metricbeat/module/cloudfoundry/_meta/config.yml
  x-pack/metricbeat/module/cloudfoundry/_meta/docs.asciidoc
  x-pack/metricbeat/module/cloudfoundry/_meta/fields.yml
  x-pack/metricbeat/module/cloudfoundry/cloudfoundry.go
  x-pack/metricbeat/module/cloudfoundry/container/_meta/data.json
  x-pack/metricbeat/module/cloudfoundry/container/_meta/docs.asciidoc
  x-pack/metricbeat/module/cloudfoundry/container/_meta/fields.yml
  x-pack/metricbeat/module/cloudfoundry/container/container.go
  x-pack/metricbeat/module/cloudfoundry/counter/_meta/data.json
  x-pack/metricbeat/module/cloudfoundry/counter/_meta/docs.asciidoc
  x-pack/metricbeat/module/cloudfoundry/counter/_meta/fields.yml
  x-pack/metricbeat/module/cloudfoundry/counter/counter.go
  x-pack/metricbeat/module/cloudfoundry/doc.go
  x-pack/metricbeat/module/cloudfoundry/fields.go
  x-pack/metricbeat/module/cloudfoundry/module.yml
  x-pack/metricbeat/module/cloudfoundry/value/_meta/data.json
  x-pack/metricbeat/module/cloudfoundry/value/_meta/docs.asciidoc
  x-pack/metricbeat/module/cloudfoundry/value/_meta/fields.yml
  x-pack/metricbeat/module/cloudfoundry/value/value.go
  x-pack/metricbeat/modules.d/cloudfoundry.yml.disabled
Labels: backport, review

#16688 [7.x] Adding missing metricset to list (#16401)
  metricbeat/docs/modules/elasticsearch.asciidoc
  metricbeat/module/elasticsearch/_meta/docs.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#16700 Move crawler to filebeat/beater
  filebeat/beater/crawler.go
  filebeat/beater/filebeat.go
Labels: Filebeat, Team:Services, [zube]: In Review, refactoring, review

#14706 Fix and extend logging of light modules load errors
  CHANGELOG.next.asciidoc
  metricbeat/mb/lightmodules.go
  metricbeat/mb/lightmodules_test.go
  metricbeat/mb/testdata/lightmodules/regular_file
  metricbeat/module/ceph/test_ceph.py
Labels: Metricbeat, Team:Integrations, [zube]: In Progress, bug, needs_backport, review, v7.7.0

#15630 [Auditbeat] macOS: Replace file.origin.raw with file.origin.text
  CHANGELOG.next.asciidoc
  auditbeat/_meta/fields.common.yml
  auditbeat/docs/fields.asciidoc
  auditbeat/include/fields.go
Labels: Auditbeat, Team:SIEM, breaking change, review

#16772 Fix documentation typo for kafka metricbeat module
  metricbeat/docs/modules/kafka.asciidoc
  metricbeat/module/kafka/_meta/docs.asciidoc
Labels: Team:Platforms, needs_backport, review

#16776 Generate haproxy module docs
  metricbeat/docs/modules/haproxy.asciidoc
Labels: docs, needs_backport, review, v8.0.0

#15967 Adding integration test for beat Metricbeat module, xpack code path
  metricbeat/docker-compose.yml
  metricbeat/module/beat/_meta/Dockerfile
  metricbeat/module/beat/beat_integration_test.go
Labels: Metricbeat, Stack monitoring, Team:Integrations, [zube]: In Review, module, needs_backport, v7.7.0, v8.0.0

#16561 Allowing users to override pipeline ID in fileset input config
  CHANGELOG.next.asciidoc
  filebeat/fileset/fileset.go
  filebeat/fileset/fileset_test.go
Labels: Filebeat, Team:Integrations, [zube]: Inbox, enhancement, needs_backport, review, v7.7.0, v8.0.0

#16789 Cherry-pick #16752 to 7.x: [Metricbeat] Add dashboard for redisenterprise
  CHANGELOG.next.asciidoc
  metricbeat/docs/images/metricbeat-redisenterprise-overview.png
  metricbeat/docs/modules/redisenterprise.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/redisenterprise/_meta/docs.asciidoc
  x-pack/metricbeat/module/redisenterprise/_meta/kibana/7/dashboard/Metricbeat-redisenterprise-overview.json
Labels: backport, review

#16596 Add OpenMetrics Metricbeat module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/openmetrics.asciidoc
  metricbeat/docs/modules/openmetrics/collector.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/module/prometheus/collector/collector.go
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/openmetrics/_meta/config.yml
  x-pack/metricbeat/module/openmetrics/_meta/docs.asciidoc
  x-pack/metricbeat/module/openmetrics/_meta/fields.yml
  x-pack/metricbeat/module/openmetrics/collector/_meta/data.json
  x-pack/metricbeat/module/openmetrics/collector/_meta/docs.asciidoc
  x-pack/metricbeat/module/openmetrics/collector/_meta/fields.yml
  x-pack/metricbeat/module/openmetrics/collector/_meta/testdata/config.yml
  x-pack/metricbeat/module/openmetrics/collector/_meta/testdata/docs.plain
  x-pack/metricbeat/module/openmetrics/collector/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/openmetrics/collector/collector.go
  x-pack/metricbeat/module/openmetrics/collector/collector_test.go
  x-pack/metricbeat/module/openmetrics/fields.go
  x-pack/metricbeat/modules.d/openmetrics.yml.disabled
Labels: Team:Integrations, Team:Platforms, [zube]: Inbox, containers, enhancement, module, needs_backport, review, test-plan, v7.7.0

#16790 fix: remove duplicate stage
  Jenkinsfile
Labels: automation, bug, ci

#16760 Remove beta messages in Docker & Kubernetes autodiscover providers
  libbeat/autodiscover/providers/docker/docker.go
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
Labels: needs_backport, review

#16692 Fix diskio struct alignment for windows 32 bit versions
  CHANGELOG.next.asciidoc
  metricbeat/module/system/diskio/disk_performance_386.go
  metricbeat/module/system/diskio/disk_performance_amd64.go
  metricbeat/module/system/diskio/diskstat_windows_helper.go
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, needs_backport

#16791 Cherry-pick #16596 to 7.x: Add OpenMetrics Metricbeat module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/openmetrics.asciidoc
  metricbeat/docs/modules/openmetrics/collector.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/module/prometheus/collector/collector.go
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/openmetrics/_meta/config.yml
  x-pack/metricbeat/module/openmetrics/_meta/docs.asciidoc
  x-pack/metricbeat/module/openmetrics/_meta/fields.yml
  x-pack/metricbeat/module/openmetrics/collector/_meta/data.json
  x-pack/metricbeat/module/openmetrics/collector/_meta/docs.asciidoc
  x-pack/metricbeat/module/openmetrics/collector/_meta/fields.yml
  x-pack/metricbeat/module/openmetrics/collector/_meta/testdata/config.yml
  x-pack/metricbeat/module/openmetrics/collector/_meta/testdata/docs.plain
  x-pack/metricbeat/module/openmetrics/collector/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/openmetrics/collector/collector.go
  x-pack/metricbeat/module/openmetrics/collector/collector_test.go
  x-pack/metricbeat/module/openmetrics/fields.go
  x-pack/metricbeat/modules.d/openmetrics.yml.disabled
Labels: backport, review

#16697 Fixed indentation of 'slowlog.enabled' in 'logstash.yml'
  filebeat/filebeat.reference.yml
  filebeat/module/logstash/_meta/config.reference.yml
  filebeat/module/logstash/_meta/config.yml
  filebeat/modules.d/logstash.yml.disabled
  x-pack/filebeat/filebeat.reference.yml
Labels: Team:Platforms, [zube]: In Review, docs, needs_backport, review

#16775 Cherry-pick #14706 to 7.x: Fix and extend logging of light modules load errors
  CHANGELOG.next.asciidoc
  metricbeat/mb/lightmodules.go
  metricbeat/mb/lightmodules_test.go
  metricbeat/mb/testdata/lightmodules/regular_file
  metricbeat/module/ceph/test_ceph.py
Labels: backport, review

#16795 Get ES password from the correct environment variable during testing
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/scripts/Makefile
  x-pack/libbeat/Makefile
Labels: Team:Services, [zube]: In Progress, needs_backport

#16635 Bump docs version for 6.8.7
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, review, v6.8.7

#16636 Bump version to 6.8.8
  libbeat/version/version.go
Labels: in progress, release, review, v6.8.8

#16632 Bump version to 7.6.2
  libbeat/version/version.go
Labels: in progress, release, review, v7.6.2

#16729 Cherry-pick #16624 to 7.x: Agent required changes for building the agent artifacts
  dev-tools/mage/common.go
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgspecs.go
  dev-tools/mage/pkgtypes.go
  dev-tools/packaging/packages.yml
Labels: Project:fleet, [zube]: In Review, backport, review

#16774 Cherry-pick #16700 to 7.x: Move crawler to filebeat/beater
  filebeat/beater/crawler.go
  filebeat/beater/filebeat.go
Labels: Filebeat, Team:Services, [zube]: In Review, backport, review

#15536 [Metricbeat] Add PubSub metricset to Google Cloud Platform module
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/googlecloud.asciidoc
  metricbeat/docs/modules/googlecloud/pubsub.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/googlecloud/_meta/config.yml
  x-pack/metricbeat/module/googlecloud/_meta/docs.asciidoc
  x-pack/metricbeat/module/googlecloud/fields.go
  x-pack/metricbeat/module/googlecloud/module.yml
  x-pack/metricbeat/module/googlecloud/pubsub/_meta/data_subscription.json
  x-pack/metricbeat/module/googlecloud/pubsub/_meta/data_topic.json
  x-pack/metricbeat/module/googlecloud/pubsub/_meta/docs.asciidoc
  x-pack/metricbeat/module/googlecloud/pubsub/_meta/fields.yml
  x-pack/metricbeat/module/googlecloud/pubsub/manifest.yml
  x-pack/metricbeat/modules.d/googlecloud.yml.disabled
Labels: Metricbeat, Team:Integrations, [zube]: In Review, enhancement

#16812 Cherry-pick #16795 to 7.x: Get ES password from the correct environment variable during testing
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/scripts/Makefile
  x-pack/libbeat/Makefile
Labels: backport, review

#16288 Fix generator jobs for go modules
  .travis.yml
  Jenkinsfile
  dev-tools/mage/gomod.go
  dev-tools/mage/gotool/get.go
  dev-tools/mage/gotool/go.go
  dev-tools/mage/gotool/modules.go
  dev-tools/mage/settings.go
  docs/devguide/newbeat.asciidoc
  generator/Makefile
  generator/_templates/beat/{beat}/Makefile
  generator/_templates/beat/{beat}/_meta/beat.reference.yml
  generator/_templates/beat/{beat}/include/include.go
  generator/_templates/beat/{beat}/magefile.go
  generator/_templates/beat/{beat}/tools/tools.go
  generator/_templates/metricbeat/{beat}/Makefile
  generator/_templates/metricbeat/{beat}/README.md
  generator/_templates/metricbeat/{beat}/include/include.go
  generator/_templates/metricbeat/{beat}/tools/tools.go
  generator/common/Makefile
  generator/common/beatgen/beatgen.go
  generator/common/beatgen/setup/creator.go
  generator/common/beatgen/setup/setup.go
Labels: Team:Services, [zube]: In Review, needs_backport

#16734 Moving outputs/transport => common/transport
  CHANGELOG-developer.next.asciidoc
  filebeat/input/kafka/config.go
  filebeat/input/mqtt/client.go
  filebeat/inputsource/tcp/server.go
  heartbeat/monitors/active/dialchain/builder.go
  heartbeat/monitors/active/dialchain/dialchain.go
  heartbeat/monitors/active/dialchain/net.go
  heartbeat/monitors/active/dialchain/socks5.go
  heartbeat/monitors/active/dialchain/tls.go
  heartbeat/monitors/active/dialchain/util.go
  heartbeat/monitors/active/http/http.go
  heartbeat/monitors/active/http/http_test.go
  heartbeat/monitors/active/http/simple_transp.go
  heartbeat/monitors/active/http/task.go
  heartbeat/monitors/active/tcp/config.go
  heartbeat/monitors/active/tcp/task.go
  heartbeat/monitors/active/tcp/tcp.go
  libbeat/common/transport/client.go
  libbeat/common/transport/proxy.go
  libbeat/common/transport/stats.go
  libbeat/common/transport/tcp.go
  libbeat/common/transport/tls.go
  libbeat/common/transport/transport.go
  libbeat/common/transport/transptest/ca_test.key
  libbeat/common/transport/transptest/ca_test.pem
  libbeat/common/transport/transptest/testing.go
  libbeat/common/transport/transptest/testing_test.go
  libbeat/common/transport/util.go
  libbeat/common/transport/wrap.go
  libbeat/kibana/client.go
  libbeat/monitoring/report/elasticsearch/elasticsearch.go
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/kafka/client.go
  libbeat/outputs/kafka/config.go
  libbeat/outputs/logstash/async.go
  libbeat/outputs/logstash/async_test.go
  libbeat/outputs/logstash/client_test.go
  libbeat/outputs/logstash/config.go
  libbeat/outputs/logstash/logstash.go
  libbeat/outputs/logstash/logstash_test.go
  libbeat/outputs/logstash/sync.go
  libbeat/outputs/logstash/sync_test.go
  libbeat/outputs/redis/client.go
  libbeat/outputs/redis/config.go
  libbeat/outputs/redis/redis.go
  libbeat/outputs/tls.go
  metricbeat/helper/dialer/dialer.go
  metricbeat/helper/dialer/dialer_posix.go
  metricbeat/helper/dialer/dialer_windows.go
  metricbeat/helper/http.go
  x-pack/filebeat/input/httpjson/input.go
Labels: Team:Integrations, [zube]: Inbox, libbeat, refactoring, release-note:dev_docs, v8.0.0

#16740 [docs] Add abbreviated title for add_cloudfoundry_metadata processor
  libbeat/docs/processors-list.asciidoc
  x-pack/libbeat/processors/add_cloudfoundry_metadata/docs/add_cloudfoundry_metadata.asciidoc
Labels: Team:Integrations, docs, libbeat, needs_backport, review

#16704 [docs] Clarify how ILM affects template setup options
  libbeat/docs/shared-ilm.asciidoc
  libbeat/docs/shared-template-load.asciidoc
Labels: Team:Integrations, docs, needs_backport, review

#13506 Update processors-using.asciidoc
  libbeat/docs/processors-using.asciidoc
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, docs, needs_backport

#16699 update 7.x test images to 7.7.0
  filebeat/module/system/auth/test/timestamp.log-expected.json
  filebeat/module/system/syslog/test/tz-offset.log-expected.json
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: enhancement

#16701 Decouple fileset from inputs
  filebeat/autodiscover/builder/hints/logs.go
  filebeat/beater/filebeat.go
  filebeat/fileset/factory.go
  filebeat/fileset/fileset.go
  filebeat/fileset/fileset_test.go
  filebeat/fileset/modules.go
  filebeat/fileset/modules_integration_test.go
  filebeat/fileset/modules_test.go
  filebeat/fileset/setup.go
Labels: Filebeat, Project:Filebeat-Input-v2, Team:Services, [zube]: In Review, review, test-plan, v7.7.0

#16801 [7.6] [docs] Add username and password to haproxy example (#16703)
  metricbeat/docs/modules/haproxy.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/haproxy/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Integrations, [zube]: In Review, backport

#16244 New input for Office 365 audit logs
  CHANGELOG.next.asciidoc
  go.mod
  x-pack/filebeat/docs/inputs/input-o365audit.asciidoc
  x-pack/filebeat/include/list.go
  x-pack/filebeat/input/o365audit/auth/auth.go
  x-pack/filebeat/input/o365audit/auth/cert.go
  x-pack/filebeat/input/o365audit/auth/secret.go
  x-pack/filebeat/input/o365audit/config.go
  x-pack/filebeat/input/o365audit/contentblob.go
  x-pack/filebeat/input/o365audit/contentblob_test.go
  x-pack/filebeat/input/o365audit/dates.go
  x-pack/filebeat/input/o365audit/input.go
  x-pack/filebeat/input/o365audit/listblobs.go
  x-pack/filebeat/input/o365audit/listblobs_test.go
  x-pack/filebeat/input/o365audit/pagination.go
  x-pack/filebeat/input/o365audit/poll/poll.go
  x-pack/filebeat/input/o365audit/schema.go
  x-pack/filebeat/input/o365audit/state.go
  x-pack/filebeat/input/o365audit/state_test.go
  x-pack/filebeat/input/o365audit/subscribe.go
Labels: Filebeat, Team:SIEM, enhancement, review

#16798 Cherry-pick #14271 to 7.6: Convert ticks to milliseconds for diskio metricset
  CHANGELOG.next.asciidoc
  metricbeat/module/system/diskio/diskstat_windows_helper.go
Labels: Team:Integrations, Team:Platforms, [zube]: Inbox, backport

#16797 Cherry-pick #14271 to 7.x: Convert ticks to milliseconds for diskio metricset
  CHANGELOG.next.asciidoc
  metricbeat/module/system/diskio/diskstat_windows_helper.go
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, backport

#16726 Move the metricbeat IIS module to x-pack
  metricbeat/docs/modules/iis.asciidoc
  metricbeat/docs/modules/iis/application_pool.asciidoc
  metricbeat/docs/modules/iis/webserver.asciidoc
  metricbeat/docs/modules/iis/website.asciidoc
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/iis/application_pool/_meta/data.json
  metricbeat/module/iis/application_pool/application_pool_test.go
  metricbeat/module/iis/application_pool/doc.go
  metricbeat/module/iis/doc.go
  metricbeat/module/iis/fields.go
  metricbeat/module/iis/webserver/_meta/data.json
  metricbeat/module/iis/webserver/doc.go
  metricbeat/module/iis/webserver/webserver_integration_test.go
  metricbeat/module/iis/webserver/webserver_test.go
  metricbeat/module/iis/website/_meta/data.json
  metricbeat/module/iis/website/doc.go
  metricbeat/module/iis/website/website_integration_test.go
  metricbeat/module/iis/website/website_test.go
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/module/iis/_meta/config.yml
  x-pack/metricbeat/module/iis/_meta/docs.asciidoc
  x-pack/metricbeat/module/iis/_meta/fields.yml
  x-pack/metricbeat/module/iis/application_pool/_meta/data.json
  x-pack/metricbeat/module/iis/application_pool/_meta/docs.asciidoc
  x-pack/metricbeat/module/iis/application_pool/_meta/fields.yml
  x-pack/metricbeat/module/iis/application_pool/application_integration_test.go
  x-pack/metricbeat/module/iis/application_pool/application_pool.go
  x-pack/metricbeat/module/iis/application_pool/application_pool_test.go
  x-pack/metricbeat/module/iis/application_pool/doc.go
  x-pack/metricbeat/module/iis/application_pool/reader.go
  x-pack/metricbeat/module/iis/application_pool/reader_test.go
  x-pack/metricbeat/module/iis/doc.go
  x-pack/metricbeat/module/iis/fields.go
  x-pack/metricbeat/module/iis/module.yml
  x-pack/metricbeat/module/iis/test/integration.go
  x-pack/metricbeat/module/iis/webserver/_meta/data.json
  x-pack/metricbeat/module/iis/webserver/_meta/docs.asciidoc
  x-pack/metricbeat/module/iis/webserver/_meta/fields.yml
  x-pack/metricbeat/module/iis/webserver/doc.go
  x-pack/metricbeat/module/iis/webserver/manifest.yml
  x-pack/metricbeat/module/iis/webserver/webserver_integration_test.go
  x-pack/metricbeat/module/iis/webserver/webserver_test.go
  x-pack/metricbeat/module/iis/website/_meta/data.json
  x-pack/metricbeat/module/iis/website/_meta/docs.asciidoc
  x-pack/metricbeat/module/iis/website/_meta/fields.yml
  x-pack/metricbeat/module/iis/website/doc.go
  x-pack/metricbeat/module/iis/website/manifest.yml
  x-pack/metricbeat/module/iis/website/website_integration_test.go
  x-pack/metricbeat/module/iis/website/website_test.go
  x-pack/metricbeat/modules.d/iis.yml.disabled
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, needs_backport

#16570 Add support for histogram type in fields.yml
  CHANGELOG.next.asciidoc
  libbeat/mapping/field.go
  libbeat/template/processor.go
  libbeat/template/processor_test.go
Labels: enhancement, in progress, libbeat

#16829 Add changelog entry about new dependency management method of generated Beats
  CHANGELOG-developer.next.asciidoc
Labels: Team:Services, [zube]: In Review, needs_backport

#16828 Cherry-pick #16288 to 7.x: Fix generator jobs for go modules
  .travis.yml
  dev-tools/mage/gomod.go
  dev-tools/mage/gotool/get.go
  dev-tools/mage/gotool/go.go
  dev-tools/mage/gotool/modules.go
  dev-tools/mage/settings.go
  docs/devguide/newbeat.asciidoc
  generator/Makefile
  generator/_templates/beat/{beat}/Makefile
  generator/_templates/beat/{beat}/_meta/beat.reference.yml
  generator/_templates/beat/{beat}/include/include.go
  generator/_templates/beat/{beat}/magefile.go
  generator/_templates/beat/{beat}/tools/tools.go
  generator/_templates/metricbeat/{beat}/Makefile
  generator/_templates/metricbeat/{beat}/README.md
  generator/_templates/metricbeat/{beat}/include/include.go
  generator/_templates/metricbeat/{beat}/tools/tools.go
  generator/common/Makefile
  generator/common/beatgen/beatgen.go
  generator/common/beatgen/setup/creator.go
  generator/common/beatgen/setup/setup.go
Labels: Team:Services, [zube]: In Review, backport

#16792 Cherry-pick #16760 to 7.x: Remove beta messages in Docker & Kubernetes autodiscover providers
  libbeat/autodiscover/providers/docker/docker.go
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
Labels: backport, review

#15980 Cherry-pick #10760 to 6.8: Adding Cisco support for the Syslog parser
  CHANGELOG.next.asciidoc
  filebeat/_meta/fields.common.yml
  filebeat/docs/fields.asciidoc
  filebeat/include/fields.go
  filebeat/input/syslog/event.go
  filebeat/input/syslog/input.go
  filebeat/input/syslog/input_test.go
  filebeat/input/syslog/parser.go
  filebeat/input/syslog/parser.rl
  filebeat/input/syslog/parser_test.go
  filebeat/input/syslog/syslog_rfc3164.rl
Labels: backport, review

#16805 Cherry-pick #16772 to 7.6: Fix documentation typo for kafka metricbeat module
  metricbeat/docs/modules/kafka.asciidoc
  metricbeat/module/kafka/_meta/docs.asciidoc
Labels: backport, review

#16804 Cherry-pick #16772 to 7.x: Fix documentation typo for kafka metricbeat module
  metricbeat/docs/modules/kafka.asciidoc
  metricbeat/module/kafka/_meta/docs.asciidoc
Labels: backport, review

#16761 Remove global logger from outputs and monitoring
  CHANGELOG-developer.next.asciidoc
  heartbeat/monitors/active/dialchain/socks5.go
  libbeat/common/transport/client.go
  libbeat/common/transport/proxy.go
  libbeat/common/transport/tcp.go
  libbeat/common/transport/tlscommon/tls.go
  libbeat/common/transport/tlscommon/tls_config.go
  libbeat/common/transport/transport.go
  libbeat/common/transport/util.go
  libbeat/monitoring/adapter/go-metrics.go
  libbeat/monitoring/report/elasticsearch/client.go
  libbeat/monitoring/report/elasticsearch/elasticsearch.go
  libbeat/outputs/console/console.go
  libbeat/outputs/elasticsearch/api_test.go
  libbeat/outputs/elasticsearch/bulkapi.go
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/elasticsearch/elasticsearch.go
  libbeat/outputs/fileout/file.go
  libbeat/outputs/kafka/client.go
  libbeat/outputs/kafka/config.go
  libbeat/outputs/kafka/config_test.go
  libbeat/outputs/kafka/kafka.go
  libbeat/outputs/kafka/log.go
  libbeat/outputs/kafka/partition.go
  libbeat/outputs/kafka/partition_test.go
  libbeat/outputs/logstash/async.go
  libbeat/outputs/logstash/enc.go
  libbeat/outputs/logstash/logstash.go
  libbeat/outputs/logstash/sync.go
  libbeat/outputs/redis/client.go
  libbeat/outputs/redis/redis.go
Labels: Team:Services, [zube]: In Review, enhancement, needs_backport, refactoring, release-note:dev_docs, review

#16813 Cherry-pick #16735 to 7.x: [Elastic Log Driver] magefile cleanup, fix bug on plugin uninstall
  x-pack/dockerlogbeat/magefile.go
Labels: backport, review

#16832 Cherry-pick #16726 to 7.x: Move the metricbeat IIS module to x-pack
  metricbeat/docs/modules/iis.asciidoc
  metricbeat/docs/modules/iis/application_pool.asciidoc
  metricbeat/docs/modules/iis/webserver.asciidoc
  metricbeat/docs/modules/iis/website.asciidoc
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/iis/application_pool/_meta/data.json
  metricbeat/module/iis/application_pool/application_pool_test.go
  metricbeat/module/iis/application_pool/doc.go
  metricbeat/module/iis/doc.go
  metricbeat/module/iis/fields.go
  metricbeat/module/iis/webserver/_meta/data.json
  metricbeat/module/iis/webserver/doc.go
  metricbeat/module/iis/webserver/webserver_integration_test.go
  metricbeat/module/iis/webserver/webserver_test.go
  metricbeat/module/iis/website/_meta/data.json
  metricbeat/module/iis/website/doc.go
  metricbeat/module/iis/website/website_integration_test.go
  metricbeat/module/iis/website/website_test.go
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/module/iis/_meta/config.yml
  x-pack/metricbeat/module/iis/_meta/docs.asciidoc
  x-pack/metricbeat/module/iis/_meta/fields.yml
  x-pack/metricbeat/module/iis/application_pool/_meta/data.json
  x-pack/metricbeat/module/iis/application_pool/_meta/docs.asciidoc
  x-pack/metricbeat/module/iis/application_pool/_meta/fields.yml
  x-pack/metricbeat/module/iis/application_pool/application_integration_test.go
  x-pack/metricbeat/module/iis/application_pool/application_pool.go
  x-pack/metricbeat/module/iis/application_pool/application_pool_test.go
  x-pack/metricbeat/module/iis/application_pool/doc.go
  x-pack/metricbeat/module/iis/application_pool/reader.go
  x-pack/metricbeat/module/iis/application_pool/reader_test.go
  x-pack/metricbeat/module/iis/doc.go
  x-pack/metricbeat/module/iis/fields.go
  x-pack/metricbeat/module/iis/module.yml
  x-pack/metricbeat/module/iis/test/integration.go
  x-pack/metricbeat/module/iis/webserver/_meta/data.json
  x-pack/metricbeat/module/iis/webserver/_meta/docs.asciidoc
  x-pack/metricbeat/module/iis/webserver/_meta/fields.yml
  x-pack/metricbeat/module/iis/webserver/doc.go
  x-pack/metricbeat/module/iis/webserver/manifest.yml
  x-pack/metricbeat/module/iis/webserver/webserver_integration_test.go
  x-pack/metricbeat/module/iis/webserver/webserver_test.go
  x-pack/metricbeat/module/iis/website/_meta/data.json
  x-pack/metricbeat/module/iis/website/_meta/docs.asciidoc
  x-pack/metricbeat/module/iis/website/_meta/fields.yml
  x-pack/metricbeat/module/iis/website/doc.go
  x-pack/metricbeat/module/iis/website/manifest.yml
  x-pack/metricbeat/module/iis/website/website_integration_test.go
  x-pack/metricbeat/module/iis/website/website_test.go
  x-pack/metricbeat/modules.d/iis.yml.disabled
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, backport

#15504 Add layouts to the String method of the timestamp processor
  libbeat/processors/timestamp/timestamp.go
Labels: Team:Services, [zube]: In Review, review

#16765 Cherry-pick #16691 to 7.x: [libbeat] rename queue.Eventer -> queue.ACKListener
  CHANGELOG-developer.next.asciidoc
  libbeat/monitoring/report/elasticsearch/elasticsearch.go
  libbeat/publisher/pipeline/client_test.go
  libbeat/publisher/pipeline/module.go
  libbeat/publisher/pipeline/pipeline.go
  libbeat/publisher/queue/memqueue/ackloop.go
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/queue.go
  libbeat/publisher/queue/spool/inbroker.go
  libbeat/publisher/queue/spool/module.go
  libbeat/publisher/queue/spool/spool.go
Labels: backport, cleanup, libbeat, review

#16693 [libbeat] [cleanup] make spool.{Spool, Settings} internal
  CHANGELOG-developer.next.asciidoc
  libbeat/publisher/queue/spool/module.go
  libbeat/publisher/queue/spool/spool.go
  libbeat/publisher/queue/spool/spool_test.go
Labels: cleanup, libbeat

#16816 [7.x][docs] Backport: Add abbreviated title for add_cloudfoundry_metadata processor …
  libbeat/docs/processors-list.asciidoc
  x-pack/libbeat/processors/add_cloudfoundry_metadata/docs/add_cloudfoundry_metadata.asciidoc
Labels: backport, docs, v7.7.0

#16822 [7.6][docs] Backport: Update processors-using.asciidoc (#13506)
  libbeat/docs/processors-using.asciidoc
Labels: backport, docs, v7.6.0

#16823 [7.x][docs] Backport: Update processors-using.asciidoc (#13506)
  libbeat/docs/processors-using.asciidoc
Labels: backport, docs, v7.7.0

#16847 Disable Travis CI jobs in non-master branches
  .travis.yml
Labels: [zube]: In Review, v7.6.2, v7.7.0

#16861 Cherry-pick #16847 to 7.x: Disable Travis CI jobs in non-master branches
  .travis.yml
Labels: backport, review

#16862 Cherry-pick #16847 to 7.6: Disable Travis CI jobs in non-master branches
  .travis.yml
Labels: backport, review

#16831 Cherry-pick #16692 to 7.6: Fix diskio struct alignment for windows 32 bit versions
  CHANGELOG.next.asciidoc
  metricbeat/module/system/diskio/disk_performance_386.go
  metricbeat/module/system/diskio/disk_performance_amd64.go
  metricbeat/module/system/diskio/diskstat_windows_helper.go
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, backport

#16830 Cherry-pick #16692 to 7.x: Fix diskio struct alignment for windows 32 bit versions
  CHANGELOG.next.asciidoc
  metricbeat/module/system/diskio/disk_performance_386.go
  metricbeat/module/system/diskio/disk_performance_amd64.go
  metricbeat/module/system/diskio/diskstat_windows_helper.go
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, backport

#16836 Install mage and goimports from vendor folder
  .ci/scripts/install-tools.bat
  auditbeat/make.bat
  filebeat/make.bat
  heartbeat/make.bat
  libbeat/make.bat
  libbeat/scripts/Makefile
  make.bat
  metricbeat/make.bat
  packetbeat/make.bat
  winlogbeat/make.bat
  x-pack/filebeat/make.bat
  x-pack/winlogbeat/make.bat
Labels: Team:Services, [zube]: In Review

#16842 ci: avoid to modify go.mod file
  .ci/scripts/install-go.sh
Labels: [zube]: In Review, automation, bug, ci

#16837 mage: optionally mount module cache for crossbuild
  dev-tools/mage/common.go
  dev-tools/mage/config.go
  dev-tools/mage/crossbuild.go
  dev-tools/mage/godaemon.go
  dev-tools/mage/gomod.go
  dev-tools/mage/gotool/go.go
  dev-tools/mage/gotool/modules.go
  dev-tools/mage/settings.go
  generator/common/beatgen/beatgen.go
  generator/common/beatgen/setup/setup.go
Labels: [zube]: In Review, bug, enhancement, needs_backport

#16872 Fix link in an entry of CHANGELOG.next.asciidoc
  CHANGELOG.next.asciidoc
Labels: Team:Services, [zube]: In Review

#16783 [7.x] Adding integration test for beat Metricbeat module, xpack code path (#15967)
  metricbeat/docker-compose.yml
  metricbeat/module/beat/_meta/Dockerfile
  metricbeat/module/beat/beat_integration_test.go
Labels: Team:Integrations, Team:Services, [zube]: In Review, backport

#16857 Fix NewContainerMetadataEnricher to use default config for kubernetes module.
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/metadata/config.go
  libbeat/common/kubernetes/metadata/resource.go
  libbeat/common/kubernetes/metadata/resource_test.go
Labels: Team:Platforms, [zube]: In Review, containers, review

#16668 [Filebeat] Improve ECS categorization field mappings in logstash module
  CHANGELOG.next.asciidoc
  filebeat/module/logstash/log/ingest/pipeline-json.json
  filebeat/module/logstash/log/ingest/pipeline-json.yml
  filebeat/module/logstash/log/ingest/pipeline-plain.json
  filebeat/module/logstash/log/ingest/pipeline-plain.yml
  filebeat/module/logstash/log/manifest.yml
  filebeat/module/logstash/log/test/logstash-json.log-expected.json
  filebeat/module/logstash/log/test/logstash-plain-7.4.log-expected.json
  filebeat/module/logstash/log/test/logstash-plain.log-expected.json
  filebeat/module/logstash/slowlog/ingest/pipeline-json.json
  filebeat/module/logstash/slowlog/ingest/pipeline-json.yml
  filebeat/module/logstash/slowlog/ingest/pipeline-plain.json
  filebeat/module/logstash/slowlog/ingest/pipeline-plain.yml
  filebeat/module/logstash/slowlog/manifest.yml
  filebeat/module/logstash/slowlog/test/slowlog-json.log-expected.json
  filebeat/module/logstash/slowlog/test/slowlog-plain.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, needs_backport

#16871 Add Kerberos support to Kafka input and output
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  filebeat/input/kafka/config.go
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config.reference.yml.tmpl
  libbeat/common/transport/kerberos/config.go
  libbeat/outputs/kafka/config.go
  libbeat/outputs/kafka/config_test.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Services, [zube]: In Review, needs testing notes, test-plan

#16807 Cherry-pick #16697 to 7.6: Fixed indentation of 'slowlog.enabled' in 'logstash.yml'
  filebeat/filebeat.reference.yml
  filebeat/module/logstash/_meta/config.reference.yml
  filebeat/module/logstash/_meta/config.yml
  filebeat/modules.d/logstash.yml.disabled
  x-pack/filebeat/filebeat.reference.yml
Labels: backport, review

#16867 Remove integrations from CODEOWNERS (backport to 7.7)
  .github/CODEOWNERS
Labels: [zube]: In Review

#16868 Remove integrations from CODEOWNERS (#16841)
  .github/CODEOWNERS
Labels: [zube]: In Review

#16638 [Metricbeat] Expand docker/blkio data
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/docker/diskio/_meta/data.json
  metricbeat/module/docker/diskio/_meta/fields.yml
  metricbeat/module/docker/diskio/data.go
  metricbeat/module/docker/diskio/diskio.go
  metricbeat/module/docker/diskio/diskio_test.go
  metricbeat/module/docker/diskio/helper.go
  metricbeat/module/docker/fields.go
Labels: Team:Integrations, [zube]: In Review, enhancement, needs_backport

#16806 Cherry-pick #16697 to 7.x: Fixed indentation of 'slowlog.enabled' in 'logstash.yml'
  filebeat/filebeat.reference.yml
  filebeat/module/logstash/_meta/config.reference.yml
  filebeat/module/logstash/_meta/config.yml
  filebeat/modules.d/logstash.yml.disabled
  x-pack/filebeat/filebeat.reference.yml
Labels: backport, review

#16873 Cherry-pick #16857 to 7.x: Fix NewContainerMetadataEnricher to use default config for kubernetes module.
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/metadata/config.go
  libbeat/common/kubernetes/metadata/resource.go
  libbeat/common/kubernetes/metadata/resource_test.go
Labels: Team:Platforms, backport, containers, review

#16770 Cherry-pick #13808 to 7.x: Fix renaming cloud metadata processor fields
  CHANGELOG.next.asciidoc
  libbeat/processors/add_cloud_metadata/add_cloud_metadata.go
Labels: backport, review

#16569 [Metricbeat] Add a system/users metricset
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/system.asciidoc
  metricbeat/docs/modules/system/users.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/module/system/_meta/config.yml
  metricbeat/module/system/fields.go
  metricbeat/module/system/users/_meta/data.json
  metricbeat/module/system/users/_meta/docs.asciidoc
  metricbeat/module/system/users/_meta/fields.yml
  metricbeat/module/system/users/dbus.go
  metricbeat/module/system/users/doc.go
  metricbeat/module/system/users/users.go
  metricbeat/module/system/users/users_test.go
  metricbeat/modules.d/system.yml
  vendor/github.com/godbus/dbus/.travis.yml
  vendor/github.com/godbus/dbus/CONTRIBUTING.md
  vendor/github.com/godbus/dbus/LICENSE
  vendor/github.com/godbus/dbus/MAINTAINERS
  vendor/github.com/godbus/dbus/README.markdown
  vendor/github.com/godbus/dbus/auth.go
  vendor/github.com/godbus/dbus/auth_anonymous.go
  vendor/github.com/godbus/dbus/auth_external.go
  vendor/github.com/godbus/dbus/auth_sha1.go
  vendor/github.com/godbus/dbus/call.go
  vendor/github.com/godbus/dbus/conn.go
  vendor/github.com/godbus/dbus/conn_darwin.go
  vendor/github.com/godbus/dbus/conn_other.go
  vendor/github.com/godbus/dbus/conn_unix.go
  vendor/github.com/godbus/dbus/conn_windows.go
  vendor/github.com/godbus/dbus/dbus.go
  vendor/github.com/godbus/dbus/decoder.go
  vendor/github.com/godbus/dbus/default_handler.go
  vendor/github.com/godbus/dbus/doc.go
  vendor/github.com/godbus/dbus/encoder.go
  vendor/github.com/godbus/dbus/export.go
  vendor/github.com/godbus/dbus/go.mod
  vendor/github.com/godbus/dbus/homedir.go
  vendor/github.com/godbus/dbus/homedir_dynamic.go
  vendor/github.com/godbus/dbus/homedir_static.go
  vendor/github.com/godbus/dbus/message.go
  vendor/github.com/godbus/dbus/object.go
  vendor/github.com/godbus/dbus/server_interfaces.go
  vendor/github.com/godbus/dbus/sig.go
  vendor/github.com/godbus/dbus/transport_darwin.go
  vendor/github.com/godbus/dbus/transport_generic.go
  vendor/github.com/godbus/dbus/transport_nonce_tcp.go
  vendor/github.com/godbus/dbus/transport_tcp.go
  vendor/github.com/godbus/dbus/transport_unix.go
  vendor/github.com/godbus/dbus/transport_unixcred_dragonfly.go
  vendor/github.com/godbus/dbus/transport_unixcred_freebsd.go
  vendor/github.com/godbus/dbus/transport_unixcred_linux.go
  vendor/github.com/godbus/dbus/transport_unixcred_openbsd.go
  vendor/github.com/godbus/dbus/variant.go
  vendor/github.com/godbus/dbus/variant_lexer.go
  vendor/github.com/godbus/dbus/variant_parser.go
  vendor/modules.txt
Labels: Team:Integrations, [zube]: In Review, needs_backport

#16788 [7.x] Allowing users to override pipeline ID in fileset input config (#16561)
  CHANGELOG.next.asciidoc
  filebeat/fileset/fileset.go
  filebeat/fileset/fileset_test.go
Labels: Team:Integrations, Team:Services, [zube]: In Review, backport

#16800 [7.x] [docs] Add username and password to haproxy example (#16703)
  metricbeat/docs/modules/haproxy.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/haproxy/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Integrations, Team:Services, [zube]: In Review, backport

#16875 Cherry-pick #16668 to 7.x: Improve ECS categorization field mappings in logstash module (#16668)
  CHANGELOG.next.asciidoc
  filebeat/module/logstash/log/ingest/pipeline-json.json
  filebeat/module/logstash/log/ingest/pipeline-json.yml
  filebeat/module/logstash/log/ingest/pipeline-plain.json
  filebeat/module/logstash/log/ingest/pipeline-plain.yml
  filebeat/module/logstash/log/manifest.yml
  filebeat/module/logstash/log/test/logstash-json.log-expected.json
  filebeat/module/logstash/log/test/logstash-plain-7.4.log-expected.json
  filebeat/module/logstash/log/test/logstash-plain.log-expected.json
  filebeat/module/logstash/slowlog/ingest/pipeline-json.json
  filebeat/module/logstash/slowlog/ingest/pipeline-json.yml
  filebeat/module/logstash/slowlog/ingest/pipeline-plain.json
  filebeat/module/logstash/slowlog/ingest/pipeline-plain.yml
  filebeat/module/logstash/slowlog/manifest.yml
  filebeat/module/logstash/slowlog/test/slowlog-json.log-expected.json
  filebeat/module/logstash/slowlog/test/slowlog-plain.log-expected.json
Labels: Team:SIEM, backport, review

#16858 [libbeat] Document / clean up parts of the publisher queue interface
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/memqueue/consume.go
  libbeat/publisher/queue/memqueue/produce.go
  libbeat/publisher/queue/queue.go
  libbeat/publisher/queue/spool/produce.go
Labels: Team:Services, [zube]: Inbox, cleanup, libbeat

#16888 Cherry-pick #16693 to 7.x: [libbeat] [cleanup] make spool.{Spool, Settings} internal
  CHANGELOG-developer.next.asciidoc
  libbeat/publisher/queue/spool/module.go
  libbeat/publisher/queue/spool/spool.go
  libbeat/publisher/queue/spool/spool_test.go
Labels: backport, review

#16866 Improve some logging messages for add_kubernetes_metadata processor
  CHANGELOG.next.asciidoc
  filebeat/processor/add_kubernetes_metadata/matchers.go
  filebeat/processor/add_kubernetes_metadata/matchers_test.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  libbeat/processors/add_kubernetes_metadata/kubernetes_test.go
Labels: Team:Platforms, [zube]: In Review

#16894 Cherry-pick #16063 to 7.6: Make use of secure port when accessing Kubelet API
  CHANGELOG.next.asciidoc
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Platforms, [zube]: In Review, backport, review

#16768 Cherry-pick #16766 to 7.6: Fix zeek pipelines to include millisecond precision
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/zeek/files/ingest/pipeline.json
  x-pack/filebeat/module/zeek/files/test/files-json.log-expected.json
  x-pack/filebeat/module/zeek/http/ingest/pipeline.json
  x-pack/filebeat/module/zeek/http/test/http-json.log-expected.json
  x-pack/filebeat/module/zeek/notice/ingest/pipeline.json
  x-pack/filebeat/module/zeek/notice/test/notice-json.log-expected.json
Labels: Filebeat, Team:SIEM, backport, review

#16899 Disable x-pack/agent from build
  Makefile
Labels: Project:fleet, [zube]: In Review, review

#16881 Cherry-pick #16638 to 7.x: [Metricbeat] Expand docker/blkio data
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/docker/diskio/_meta/data.json
  metricbeat/module/docker/diskio/_meta/fields.yml
  metricbeat/module/docker/diskio/data.go
  metricbeat/module/docker/diskio/diskio.go
  metricbeat/module/docker/diskio/diskio_test.go
  metricbeat/module/docker/diskio/helper.go
  metricbeat/module/docker/fields.go
Labels: Team:Integrations, Team:Services, [zube]: In Review, backport, enhancement, review, v7.7.0

#16739 Cherry-pick #16618 to 7.x: [Filebeat] Improve ECS categorization field mappings in iis module
  CHANGELOG.next.asciidoc
  filebeat/module/iis/access/ingest/default.json
  filebeat/module/iis/access/ingest/pipeline.yml
  filebeat/module/iis/access/manifest.yml
  filebeat/module/iis/access/test/test-iis-7.2.log-expected.json
  filebeat/module/iis/access/test/test-iis-7.5.log-expected.json
  filebeat/module/iis/access/test/test-ipv6zone.log-expected.json
  filebeat/module/iis/access/test/test.log-expected.json
  filebeat/module/iis/error/ingest/default.json
  filebeat/module/iis/error/ingest/pipeline.yml
  filebeat/module/iis/error/manifest.yml
  filebeat/module/iis/error/test/iis_error_url.log-expected.json
  filebeat/module/iis/error/test/ipv6_zone_id.log-expected.json
  filebeat/module/iis/error/test/test.log-expected.json
Labels: Team:SIEM, backport, review

#16745 [master][docs] Forward port: fix pattern for java stacktrace (#13516)
  filebeat/docs/multiline.asciidoc
Labels: Team:Integrations, backport, docs

#16886 [Libbeat] Remove global logger from libbeat publisher and reader
  libbeat/publisher/pipeline/output.go
  libbeat/publisher/pipeline/stress/gen.go
  libbeat/publisher/pipeline/stress/run.go
  libbeat/publisher/processing/processors.go
  libbeat/reader/multiline/multiline.go
  libbeat/reader/readfile/line.go
  libbeat/reader/readjson/docker_json.go
  libbeat/reader/readjson/json.go
Labels: Team:Platforms, Team:Services, [zube]: In Review

#16897 Cherry-pick #16858 to 7.x: [libbeat] Document / clean up parts of the publisher queue interface
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/memqueue/consume.go
  libbeat/publisher/queue/memqueue/produce.go
  libbeat/publisher/queue/queue.go
  libbeat/publisher/queue/spool/produce.go
Labels: backport, review

#16915 Add missing logger init in New() functions
  libbeat/publisher/pipeline/output.go
  libbeat/reader/multiline/multiline.go
  libbeat/reader/readfile/line.go
  libbeat/reader/readjson/docker_json.go
  libbeat/reader/readjson/json.go
  libbeat/reader/readjson/json_test.go
Labels: Team:Platforms, review

#16321 Add support for kubernetes provider to recognize namespace level defaults
  CHANGELOG.next.asciidoc
  filebeat/docs/autodiscover-hints.asciidoc
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/autodiscover/providers/kubernetes/service.go
  libbeat/autodiscover/providers/kubernetes/service_test.go
  metricbeat/docs/autodiscover-hints.asciidoc
Labels: Team:Platforms, [zube]: In Review, autodiscovery, containers, enhancement, needs tests, needs_docs, review

#16916 [Metricbeat] Remove error message when no metrics are collected from gcp
  x-pack/metricbeat/module/googlecloud/stackdriver/metrics_requester.go
  x-pack/metricbeat/module/googlecloud/stackdriver/metricset.go
Labels: Team:Platforms, [zube]: In Review, needs_backport, review

#16918 Skip flaky docker watcher tests
  libbeat/common/docker/watcher_test.go
Labels: Team:Platforms, [zube]: In Review, flaky-test, needs_backport, review, v7.7.0

#16905 Cherry-pick #16569 to 7.x: [Metricbeat] Add a system/users metricset
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/system.asciidoc
  metricbeat/docs/modules/system/users.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/module/system/_meta/config.yml
  metricbeat/module/system/fields.go
  metricbeat/module/system/users/_meta/data.json
  metricbeat/module/system/users/_meta/docs.asciidoc
  metricbeat/module/system/users/_meta/fields.yml
  metricbeat/module/system/users/dbus.go
  metricbeat/module/system/users/doc.go
  metricbeat/module/system/users/users.go
  metricbeat/module/system/users/users_test.go
  metricbeat/modules.d/system.yml
  vendor/github.com/godbus/dbus/.travis.yml
  vendor/github.com/godbus/dbus/CONTRIBUTING.md
  vendor/github.com/godbus/dbus/LICENSE
  vendor/github.com/godbus/dbus/MAINTAINERS
  vendor/github.com/godbus/dbus/README.markdown
  vendor/github.com/godbus/dbus/auth.go
  vendor/github.com/godbus/dbus/auth_anonymous.go
  vendor/github.com/godbus/dbus/auth_external.go
  vendor/github.com/godbus/dbus/auth_sha1.go
  vendor/github.com/godbus/dbus/call.go
  vendor/github.com/godbus/dbus/conn.go
  vendor/github.com/godbus/dbus/conn_darwin.go
  vendor/github.com/godbus/dbus/conn_other.go
  vendor/github.com/godbus/dbus/conn_unix.go
  vendor/github.com/godbus/dbus/conn_windows.go
  vendor/github.com/godbus/dbus/dbus.go
  vendor/github.com/godbus/dbus/decoder.go
  vendor/github.com/godbus/dbus/default_handler.go
  vendor/github.com/godbus/dbus/doc.go
  vendor/github.com/godbus/dbus/encoder.go
  vendor/github.com/godbus/dbus/export.go
  vendor/github.com/godbus/dbus/go.mod
  vendor/github.com/godbus/dbus/homedir.go
  vendor/github.com/godbus/dbus/homedir_dynamic.go
  vendor/github.com/godbus/dbus/homedir_static.go
  vendor/github.com/godbus/dbus/message.go
  vendor/github.com/godbus/dbus/object.go
  vendor/github.com/godbus/dbus/server_interfaces.go
  vendor/github.com/godbus/dbus/sig.go
  vendor/github.com/godbus/dbus/transport_darwin.go
  vendor/github.com/godbus/dbus/transport_generic.go
  vendor/github.com/godbus/dbus/transport_nonce_tcp.go
  vendor/github.com/godbus/dbus/transport_tcp.go
  vendor/github.com/godbus/dbus/transport_unix.go
  vendor/github.com/godbus/dbus/transport_unixcred_dragonfly.go
  vendor/github.com/godbus/dbus/transport_unixcred_freebsd.go
  vendor/github.com/godbus/dbus/transport_unixcred_linux.go
  vendor/github.com/godbus/dbus/transport_unixcred_openbsd.go
  vendor/github.com/godbus/dbus/variant.go
  vendor/github.com/godbus/dbus/variant_lexer.go
  vendor/github.com/godbus/dbus/variant_parser.go
  vendor/modules.txt
Labels: Team:Services, [zube]: In Review, backport, review, v7.7.0

#16920 Add label to flaky test template
  .github/ISSUE_TEMPLATE/flaky-test.md
Labels: [zube]: In Review

#16925 Cherry-pick #16918 to 7.x: Skip flaky docker watcher tests
  libbeat/common/docker/watcher_test.go
Labels: backport, review

#16040 Update error codes for Sysmon DNS
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js
  x-pack/winlogbeat/module/sysmon/gen_dns_error_codes.go
Labels: Team:SIEM, Winlogbeat, enhancement, needs_backport, review

#16844 mb k8s module: Adding RBAC reqs and apiserver
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/module/kubernetes/_meta/docs.asciidoc
Labels: Team:Platforms, [zube]: In Review, docs

#16906 [Metricbeat] Fix config file name from services => service
  metricbeat/module/system/_meta/config.yml
  metricbeat/modules.d/system.yml
Labels: Metricbeat, Team:Services, [zube]: In Review, bug, v7.6.2, v7.7.0

#16924 Cherry-pick #16916 to 7.x: [Metricbeat] Remove error message when no metrics are collected from gcp
  x-pack/metricbeat/module/googlecloud/stackdriver/metrics_requester.go
  x-pack/metricbeat/module/googlecloud/stackdriver/metricset.go
Labels: Team:Platforms, [zube]: In Review, backport, review

#16913 update add_kubernetes_metadata processor to use *logp.Logger
  filebeat/processor/add_kubernetes_metadata/matchers.go
Labels: Team:Platforms, [zube]: In Review, needs_backport, review

#16929 Cherry-pick #16906 to 7.x: [Metricbeat] Fix config file name from services => service
  metricbeat/module/system/_meta/config.yml
  metricbeat/modules.d/system.yml
Labels: backport, bug, review

#16930 Cherry-pick #16906 to 7.6: [Metricbeat] Fix config file name from services => service
  metricbeat/module/system/_meta/config.yml
  metricbeat/modules.d/system.yml
Labels: backport, bug, review

#16909 [7.6][docs] Backport: Clarify how ILM affects template setup options (#16704)
  libbeat/docs/shared-ilm.asciidoc
  libbeat/docs/shared-template-load.asciidoc
Labels: Team:Services, backport, docs, v7.6.0

#16910 [7.x][docs] Backport: Clarify how ILM affects template setup options (#16704)
  libbeat/docs/shared-ilm.asciidoc
  libbeat/docs/shared-template-load.asciidoc
Labels: Team:Services, [zube]: In Review, backport, v7.7.0

#16605 [Metricbeat] add collecting tags for rds metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/aws/_meta/config.reference.yml
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/aws.go
  x-pack/metricbeat/module/aws/ec2/ec2.go
  x-pack/metricbeat/module/aws/ec2/ec2_test.go
  x-pack/metricbeat/module/aws/rds/_meta/data.json
  x-pack/metricbeat/module/aws/rds/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/rds/rds.go
  x-pack/metricbeat/module/aws/rds/rds_test.go
Labels: Team:Platforms, [zube]: In Review, enhancement, needs_backport, review, test-plan

#16354 Update filebeat httpjson input to support pagination via Header and Okta module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/config.go
  x-pack/filebeat/input/httpjson/httpjson_test.go
  x-pack/filebeat/input/httpjson/input.go
Labels: Filebeat, Team:SIEM, review

#16758 Add debugging dump option to Jenkins
  Jenkinsfile
Labels: automation, ci

#16922 [Agent] Fixed test to pass on windows
  x-pack/agent/CHANGELOG.asciidoc
  x-pack/agent/pkg/agent/operation/common_test.go
  x-pack/agent/pkg/agent/operation/monitoring_test.go
  x-pack/agent/pkg/agent/operation/operator_test.go
  x-pack/agent/pkg/core/plugin/app/monitoring/beats/beats_monitor.go
  x-pack/agent/pkg/core/plugin/app/monitoring/beats/drop_test.go
Labels: Project:fleet, agent, needs_backport

#16939 Cherry-pick #16605 to 7.x: [Metricbeat] add collecting tags for rds metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/aws/_meta/config.reference.yml
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/aws.go
  x-pack/metricbeat/module/aws/ec2/ec2.go
  x-pack/metricbeat/module/aws/ec2/ec2_test.go
  x-pack/metricbeat/module/aws/rds/_meta/data.json
  x-pack/metricbeat/module/aws/rds/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/rds/rds.go
  x-pack/metricbeat/module/aws/rds/rds_test.go
Labels: Team:Platforms, [zube]: In Review, backport, review

#16927 Fix issue when building Agent snapshot and enable building the agent.
  Makefile
  dev-tools/packaging/packages.yml
Labels: Packaging, Project:fleet, needs_backport

#16931 Fleet gateway had a deadlocking test
  x-pack/agent/pkg/agent/application/fleet_gateway_test.go
Labels: Project:fleet, [zube]: In Review, needs_backport, review

#16952 Temporarily disable generator jobs on Travis
  .travis.yml
Labels: Team:Services, [zube]: In Review, needs_backport

#16954 Cherry-pick #16952 to 7.x: Temporarily disable generator jobs on Travis
  .travis.yml
Labels: Team:Services, [zube]: In Review, backport

#16533 [Filebeat] Improve ECS categorization field mapping in icinga
  CHANGELOG.next.asciidoc
  filebeat/module/icinga/debug/ingest/pipeline.json
  filebeat/module/icinga/debug/ingest/pipeline.yml
  filebeat/module/icinga/debug/manifest.yml
  filebeat/module/icinga/debug/test/test.log-expected.json
  filebeat/module/icinga/main/ingest/pipeline.json
  filebeat/module/icinga/main/ingest/pipeline.yml
  filebeat/module/icinga/main/manifest.yml
  filebeat/module/icinga/main/test/test.log-expected.json
  filebeat/module/icinga/startup/ingest/pipeline.json
  filebeat/module/icinga/startup/ingest/pipeline.yml
  filebeat/module/icinga/startup/manifest.yml
  filebeat/module/icinga/startup/test/test.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, needs_backport

#16903 [Agent] Inject index with sane defaults to configuration
  x-pack/agent/CHANGELOG.asciidoc
  x-pack/agent/_meta/agent.docker.yml
  x-pack/agent/_meta/agent.yml
  x-pack/agent/_meta/common.p2.yml
  x-pack/agent/_meta/common.reference.p2.yml
  x-pack/agent/agent.docker.yml
  x-pack/agent/agent.reference.yml
  x-pack/agent/agent.yml
  x-pack/agent/dev-tools/cmd/fakewebapi/action_example.json
  x-pack/agent/pkg/agent/application/action_store.go
  x-pack/agent/pkg/agent/application/action_store_test.go
  x-pack/agent/pkg/agent/application/fleet_gateway_test.go
  x-pack/agent/pkg/agent/application/handler_action_policy_change.go
  x-pack/agent/pkg/agent/application/handler_action_policy_change_test.go
  x-pack/agent/pkg/agent/application/managed_mode.go
  x-pack/agent/pkg/agent/application/monitoring_decorator.go
  x-pack/agent/pkg/agent/application/monitoring_decorator_test.go
  x-pack/agent/pkg/agent/operation/config/config.go
  x-pack/agent/pkg/agent/operation/monitoring.go
  x-pack/agent/pkg/agent/program/program.go
  x-pack/agent/pkg/agent/program/program_test.go
  x-pack/agent/pkg/agent/program/supported.go
  x-pack/agent/pkg/agent/program/testdata/enabled_false.yml
  x-pack/agent/pkg/agent/program/testdata/enabled_output_false.yml
  x-pack/agent/pkg/agent/program/testdata/enabled_output_true-filebeat.yml
  x-pack/agent/pkg/agent/program/testdata/enabled_output_true.yml
  x-pack/agent/pkg/agent/program/testdata/enabled_true-filebeat.yml
  x-pack/agent/pkg/agent/program/testdata/enabled_true.yml
  x-pack/agent/pkg/agent/program/testdata/single_config-filebeat.yml
  x-pack/agent/pkg/agent/program/testdata/single_config-metricbeat.yml
  x-pack/agent/pkg/agent/program/testdata/single_config.yml
  x-pack/agent/pkg/agent/transpiler/rules.go
  x-pack/agent/pkg/agent/transpiler/rules_test.go
  x-pack/agent/pkg/fleetapi/ack_cmd_test.go
  x-pack/agent/pkg/fleetapi/action.go
  x-pack/agent/pkg/fleetapi/checkin_cmd.go
  x-pack/agent/pkg/fleetapi/checkin_cmd_test.go
  x-pack/agent/spec/filebeat.yml
  x-pack/agent/spec/metricbeat.yml
Labels: Project:fleet, agent, needs_backport

#16532 [Filebeat] Improve ECS categorization field mappings in ibmmq
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/ibmmq/errorlog/ingest/pipeline.json
  x-pack/filebeat/module/ibmmq/errorlog/ingest/pipeline.yml
  x-pack/filebeat/module/ibmmq/errorlog/manifest.yml
  x-pack/filebeat/module/ibmmq/errorlog/test/AMQERR01.log-expected.json
  x-pack/filebeat/module/ibmmq/errorlog/test/AMQERR01_QM1.log-expected.json
  x-pack/filebeat/module/ibmmq/errorlog/test/AMQERR01_QM2.log-expected.json
Labels: Filebeat, Team:SIEM, ecs, enhancement, needs_backport

#16762 Cherry-pick #16652 to 7.x: [Filebeat] Improve ECS categorization field mappings in kibana module
  CHANGELOG.next.asciidoc
  filebeat/module/kibana/log/ingest/pipeline.json
  filebeat/module/kibana/log/ingest/pipeline.yml
  filebeat/module/kibana/log/manifest.yml
  filebeat/module/kibana/log/test/log.624.log-expected.json
  filebeat/module/kibana/log/test/log.verbose.624.log-expected.json
  filebeat/module/kibana/log/test/test.log-expected.json
Labels: Team:SIEM, backport, review

#16742 Cherry-pick #16645 to 7.x: [Filebeat] Improve ECS categorization field mapping in kafka module
  CHANGELOG.next.asciidoc
  filebeat/module/kafka/log/ingest/pipeline.json
  filebeat/module/kafka/log/ingest/pipeline.yml
  filebeat/module/kafka/log/manifest.yml
  filebeat/module/kafka/log/test/controller-2.0.0.log-expected.json
  filebeat/module/kafka/log/test/controller.log-expected.json
  filebeat/module/kafka/log/test/server-2.0.0.log-expected.json
  filebeat/module/kafka/log/test/server.log-expected.json
  filebeat/module/kafka/log/test/state-change-1.1.0.log-expected.json
  filebeat/module/kafka/log/test/state-change-2.0.0.log-expected.json
  filebeat/module/kafka/log/test/state-change.log-expected.json
Labels: Team:SIEM, backport, review

#16940 Check if sub-directories have changes
  .ci/scripts/travis_has_changes.sh
  .travis.yml
Labels: Team:Services, [zube]: In Review, automation
