Repository elastic/beats, pull requests merged in 2020-11, with the labels that each got.

#22299 Cherry-pick #22295 to 7.10: [Filebeat][Cisco Umbrella module] Adding missing timeout options and fixing module config.yml
  filebeat/docs/modules/cisco.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/cisco/_meta/config.yml
  x-pack/filebeat/module/cisco/_meta/docs.asciidoc
  x-pack/filebeat/module/cisco/umbrella/config/input.yml
  x-pack/filebeat/module/cisco/umbrella/manifest.yml
  x-pack/filebeat/modules.d/cisco.yml.disabled
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#22298 Cherry-pick #22295 to 7.x: [Filebeat][Cisco Umbrella module] Adding missing timeout options and fixing module config.yml
  filebeat/docs/modules/cisco.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/cisco/_meta/config.yml
  x-pack/filebeat/module/cisco/_meta/docs.asciidoc
  x-pack/filebeat/module/cisco/umbrella/config/input.yml
  x-pack/filebeat/module/cisco/umbrella/manifest.yml
  x-pack/filebeat/modules.d/cisco.yml.disabled
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#22300 [packetbeat][sip] Change to default analyzer
  packetbeat/protos/sip/_meta/fields.yml
  packetbeat/protos/sip/fields.go
Labels: Packetbeat, Team:Security-External Integrations, enhancement, needs_backport

#22308 Cherry-pick to 7.x: [CI] Report error in the catch section (#22297)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#22309 Cherry-pick to 7.10: [CI] Report error in the catch section (#22297)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#22318 Cherry-pick to 7.x: [CI] Support Windows-8 (#22307)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#22310 Cherry-pick to 7.9: [CI] Report error in the catch section (#22297)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#19797 [CI] support windows-7-32 bits
  .ci/scripts/install-tools.bat
  Jenkinsfile
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, Team:Ingest Management, automation, windows-7-32

#22294 Cherry-pick #22152 to 7.10: Add interval documentation to `monitor` metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/azure.asciidoc
  x-pack/metricbeat/module/azure/_meta/docs.asciidoc
Labels: Team:Platforms, [zube]: In Review, backport

#22292 Cherry-pick #22152 to 7.x: Add interval documentation to `monitor` metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/azure.asciidoc
  x-pack/metricbeat/module/azure/_meta/docs.asciidoc
Labels: Team:Platforms, [zube]: In Review, backport

#22328 Adding Kafka version 2.2
  CHANGELOG.next.asciidoc
  libbeat/common/kafka/version.go
Labels: Team:Services, libbeat, needs_reviewer

#19803 [CI] support windows-7
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, Team:Ingest Management, automation, windows-7

#22342 Add reference to Kerberos in Kafka input and output documentation
  filebeat/docs/inputs/input-kafka.asciidoc
  libbeat/outputs/kafka/docs/kafka.asciidoc
Labels: Team:Services

#22344 [Elastic Agent] Fix agent composable processor promotion to fix duplicates
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/emitter.go
  x-pack/elastic-agent/pkg/agent/application/emitter_test.go
Labels: Team:Ingest Management, review

#22319 Cherry-pick to 7.10: [CI] Support Windows-8 (#22307)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci, windows-8

#22346 Cherry-pick #22344 to 7.x: [Elastic Agent] Fix agent composable processor promotion to fix duplicates
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/emitter.go
  x-pack/elastic-agent/pkg/agent/application/emitter_test.go
Labels: Team:Ingest Management, [zube]: In Review, backport

#22349 [Elastic Agent] Fix TestEQL on Windows 32-bit
  x-pack/elastic-agent/pkg/eql/eql_test.go
Labels: Team:Ingest Management

#22331 Cherry-pick #21664 to 7.x: [Filebeat] Copy tag names from MISP data into event
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/misp/threat/config/pipeline.js
  x-pack/filebeat/module/misp/threat/test/misp-test.json.log
  x-pack/filebeat/module/misp/threat/test/misp-test.json.log-expected.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#22348 Cherry-pick to 7.10: [CI] enable Windows-2016 and support 32 bits build requirements (#19199)
  .ci/scripts/install-tools.bat
  dev-tools/mage/gotest.go
Labels: Team:Automation, automation, backport, ci, windows-2016

#22347 Cherry-pick to 7.x: [CI] enable Windows-2016 and support 32 bits build requirements (#19199)
  .ci/scripts/install-tools.bat
  dev-tools/mage/gotest.go
Labels: Team:Automation, automation, backport, ci, windows-2016

#22338 Docs: Add link to Elastic Contributor Program
  docs/devguide/contributing.asciidoc
Labels: Team:Docs, v7.10.0, v7.9.0

#22334 Cherry-pick #22300 to 7.10: [packetbeat][sip] Change to default analyzer
  packetbeat/protos/sip/_meta/fields.yml
  packetbeat/protos/sip/fields.go
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#22333 Cherry-pick #22300 to 7.x: [packetbeat][sip] Change to default analyzer
  packetbeat/protos/sip/_meta/fields.yml
  packetbeat/protos/sip/fields.go
Labels: Team:Security-External Integrations, [zube]: Inbox, backport

#22275 Cherry-pick to 7.10: Typo (#22272)
  libbeat/docs/template-config.asciidoc
Labels: Team:Docs, backport

#22274 Cherry-pick to 7.x: Typo (#22272)
  libbeat/docs/template-config.asciidoc
Labels: Team:Docs, backport

#22198 Cherry-pick to 7.x: [DOCS] Warn about compression and Azure Event Hub for Kafka (#21578)
  libbeat/outputs/kafka/docs/kafka.asciidoc
Labels: Team:Docs, backport

#22199 Cherry-pick to 7.10: [DOCS] Warn about compression and Azure Event Hub for Kafka (#21578)
  libbeat/outputs/kafka/docs/kafka.asciidoc
Labels: Team:Docs, backport

#22353 Cherry-pick to 7.x: Update contributing content (#22338)
  docs/devguide/contributing.asciidoc
Labels: Team:Docs, backport

#22354 Cherry-pick to 7.10: Update contributing content (#22338)
  docs/devguide/contributing.asciidoc
Labels: Team:Docs, backport

#22355 Cherry-pick to 7.9: Update contributing content (#22338)
  docs/devguide/contributing.asciidoc
Labels: Team:Docs, backport

#22343 Cherry-pick to 7.x: [CI] support windows-7 (#19803)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci, windows-7

#21696 Add ja3 fields to Zeek SSL log
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/zeek.asciidoc
  x-pack/filebeat/module/zeek/_meta/docs.asciidoc
  x-pack/filebeat/module/zeek/_meta/kibana/7/dashboard/Filebeat-Zeek-Overview.json
  x-pack/filebeat/module/zeek/ssl/config/ssl.yml
  x-pack/filebeat/module/zeek/ssl/ingest/pipeline.yml
  x-pack/filebeat/module/zeek/ssl/test/ssl-json.log-expected.json
  x-pack/filebeat/module/zeek/ssl/test/ssl-with-ja3-and-custom-fields-json.log
  x-pack/filebeat/module/zeek/ssl/test/ssl-with-ja3-and-custom-fields-json.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, enhancement, review

#22351 Fix build of Packetbeat test under windows/386
  packetbeat/Jenkinsfile.yml
  packetbeat/procs/procs_windows_test.go
Labels: Team:Automation, failed-test, review, windows-7-32

#22361 [Filebeat][Fortinet] Fixing kv split for when assign-ip is not an IP and for date checking when eventtime is missing
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/fortinet/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/fortinet/firewall/test/fortinet.log
  x-pack/filebeat/module/fortinet/firewall/test/fortinet.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, enhancement

#22336 Cherry-pick to 7.10: [CI] support windows-7-32 bits (#19797)
  .ci/scripts/install-tools.bat
  Jenkinsfile
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci, windows-7-32

#22363 Cherry-pick #22361 to 7.x: [Filebeat][Fortinet] Fixing kv split for when assign-ip is not an IP and for date checking when eventtime is missing
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/fortinet/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/fortinet/firewall/test/fortinet.log
  x-pack/filebeat/module/fortinet/firewall/test/fortinet.log-expected.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#22364 Cherry-pick #22361 to 7.10: [Filebeat][Fortinet] Fixing kv split for when assign-ip is not an IP and for date checking when eventtime is missing
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/fortinet/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/fortinet/firewall/test/fortinet.log
  x-pack/filebeat/module/fortinet/firewall/test/fortinet.log-expected.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#22357 Add warning about setup.template.overwrite to documentation and reference configuration
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/setup.template.reference.yml.tmpl
  libbeat/docs/howto/load-index-templates.asciidoc
  libbeat/docs/template-config.asciidoc
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Services

#22205 Cherry-pick #22177 to 7.10: Skip flaky gateway tests
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway_test.go
Labels: Ingest Management:beta2, Team:Ingest Management, backport, bug

#22206 Cherry-pick #22177 to 7.x: Skip flaky gateway tests
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway_test.go
Labels: Ingest Management:beta2, Team:Ingest Management, backport, bug

#22345 Cherry-pick to 7.10: [CI] support windows-7 (#19803)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci, windows-7

#22356 [CI] cleanup terraform when errors
  Jenkinsfile
Labels: Team:Automation, automation, ci

#22340 Cherry-pick to 7.x: Adding Kafka version 2.2 (#22328)
  CHANGELOG.next.asciidoc
  libbeat/common/kafka/version.go
Labels: Team:Services, backport

#22341 Cherry-pick to 7.10: Adding Kafka version 2.2 (#22328)
  CHANGELOG.next.asciidoc
  libbeat/common/kafka/version.go
Labels: Team:Services, backport

#22249 ci: add a check for changes to deploy/kubernetes pipeline
  deploy/kubernetes/Jenkinsfile.yml
Labels: Team:Automation, [zube]: In Review, automation, bug, ci, needs_backport, v7.0.0, v7.11.0, v7.9.0

#22335 Cherry-pick to 7.x: [CI] support windows-7-32 bits (#19797)
  .ci/scripts/install-tools.bat
  Jenkinsfile
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci, windows-7-32

#22261 Fix instance name in perfmon metricset
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/reader_test.go
Labels: Team:Platforms, [zube]: In Review, needs_backport, windows-7-32

#22231 Cherry-pick #22217 to 7.x: [Winlogbeat] Add pe fields to Sysmon module
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js
  x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-12-loadimage.evtx
  x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-12-loadimage.evtx.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-12-processcreate.evtx
  x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-12-processcreate.evtx.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-9.01.evtx.golden.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#22384 [JJBB] Add 6.8+ branches
  .ci/jobs/beats.yml
Labels: Team:Automation, automation, ci

#22374 Cherry-pick to 7.10: [CI] cleanup terraform when errors (#22356)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#22375 Cherry-pick to 7.9: [CI] cleanup terraform when errors (#22356)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#22376 Cherry-pick to 6.8: Use google storage to keep artifact (#21910)(#22220)(#22297)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#22359 Treat session ID as a string in system/users
  CHANGELOG.next.asciidoc
  metricbeat/module/system/users/dbus.go
  metricbeat/module/system/users/users_test.go
Labels: Team:Integrations, bug, needs_backport

#22277 [libbeat] Update error message for regenerating files during build
  dev-tools/mage/check.go
Labels: Team:Integrations, build-system, docs, libbeat, needs_backport

#22373 Cherry-pick to 7.x: [CI] cleanup terraform when errors (#22356)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#22134 [Packetbeat] Refactor packetbeat for use with Elastic Agent
  CHANGELOG.next.asciidoc
  libbeat/cfgfile/list.go
  packetbeat/_meta/config/beat.reference.yml.tmpl
  packetbeat/beater/packetbeat.go
  packetbeat/beater/processor.go
  packetbeat/beater/reloader.go
  packetbeat/beater/setup.go
  packetbeat/beater/worker.go
  packetbeat/config/agent.go
  packetbeat/config/agent_test.go
  packetbeat/config/config.go
  packetbeat/docs/packetbeat-options.asciidoc
  packetbeat/flows/flows.go
  packetbeat/flows/flows_test.go
  packetbeat/flows/worker.go
  packetbeat/flows/worker_test.go
  packetbeat/packetbeat.reference.yml
  packetbeat/procs/procs.go
  packetbeat/protos/amqp/amqp.go
  packetbeat/protos/amqp/amqp_parser.go
  packetbeat/protos/amqp/amqp_test.go
  packetbeat/protos/cassandra/cassandra.go
  packetbeat/protos/cassandra/trans.go
  packetbeat/protos/dhcpv4/dhcpv4.go
  packetbeat/protos/dhcpv4/dhcpv4_test.go
  packetbeat/protos/dns/dns.go
  packetbeat/protos/dns/dns_tcp.go
  packetbeat/protos/dns/dns_test.go
  packetbeat/protos/dns/dns_udp.go
  packetbeat/protos/http/http.go
  packetbeat/protos/http/http_test.go
  packetbeat/protos/icmp/icmp.go
  packetbeat/protos/icmp/icmp_test.go
  packetbeat/protos/memcache/memcache.go
  packetbeat/protos/memcache/memcache_test.go
  packetbeat/protos/memcache/plugin_tcp.go
  packetbeat/protos/memcache/plugin_udp.go
  packetbeat/protos/mongodb/mongodb.go
  packetbeat/protos/mongodb/mongodb_test.go
  packetbeat/protos/mysql/mysql.go
  packetbeat/protos/mysql/mysql_test.go
  packetbeat/protos/nfs/rpc.go
  packetbeat/protos/pgsql/pgsql.go
  packetbeat/protos/pgsql/pgsql_test.go
  packetbeat/protos/protos.go
  packetbeat/protos/redis/redis.go
  packetbeat/protos/registry.go
  packetbeat/protos/sip/parser.go
  packetbeat/protos/sip/plugin.go
  packetbeat/protos/sip/plugin_test.go
  packetbeat/protos/tcp/tcp_test.go
  packetbeat/protos/thrift/thrift.go
  packetbeat/protos/thrift/thrift_test.go
  packetbeat/protos/tls/tls.go
  packetbeat/protos/tls/tls_test.go
  packetbeat/publish/publish.go
  packetbeat/scripts/tcp-protocol/{protocol}/trans.go.tmpl
  packetbeat/scripts/tcp-protocol/{protocol}/{protocol}.go.tmpl
  x-pack/packetbeat/packetbeat.reference.yml
Labels: Packetbeat, Team:Ingest Management, Team:Security-External Integrations, enhancement

#22380 Cherry-pick to 7.10: ci: add a check for changes to deploy/kubernetes pipeline (#22249)
  deploy/kubernetes/Jenkinsfile.yml
Labels: Team:Automation, [zube]: In Review, automation, backport, ci

#22378 Cherry-pick to 7.x: ci: add a check for changes to deploy/kubernetes pipeline (#22249)
  deploy/kubernetes/Jenkinsfile.yml
Labels: Team:Automation, [zube]: In Review, automation, backport, ci

#22289 Update the CLI reference for Elastic Agent
  x-pack/elastic-agent/docs/elastic-agent-command-line.asciidoc
Labels: Team:Ingest Management, docs, v7.10.0

#22386 Fixed typo in rename processor docs
  libbeat/processors/actions/docs/rename.asciidoc
Labels: Team:Docs, docs

#22397 Cherry-pick to 7.x: Update the CLI reference for Elastic Agent (#22289)
  x-pack/elastic-agent/docs/elastic-agent-command-line.asciidoc
Labels: backport, docs, needs_team, v7.11.0

#22398 Cherry-pick to 7.10: Update the CLI reference for Elastic Agent (#22289)
  x-pack/elastic-agent/docs/elastic-agent-command-line.asciidoc
Labels: backport, docs, needs_team, v7.10.0

#22366 Do not require sudo to run filebeat in Java tutorial
  libbeat/docs/tab-widgets/start-filebeat.asciidoc
  libbeat/docs/tab-widgets/start-widget-filebeat.asciidoc
Labels: docs, needs_team, v7.10.0

#22204 docs: Update scenario when CA is self-signed. (#21090)
  libbeat/docs/shared-ssl-config.asciidoc
Labels: Team:Docs, v7.10.0

#22325 Duplicate system.process.cmdline field with process.command_line ECS field name
  CHANGELOG.next.asciidoc
  metricbeat/module/system/process/_meta/data.json
  metricbeat/module/system/process/process.go
  metricbeat/module/system/test_system.py
  metricbeat/tests/system/test_processors.py
Labels: Team:Platforms, needs_backport

#22391 Cherry-pick #22359 to 7.x: Treat session ID as a string in system/users
  CHANGELOG.next.asciidoc
  metricbeat/module/system/users/dbus.go
  metricbeat/module/system/users/users_test.go
Labels: Team:Integrations, [zube]: In Review, backport

#22245 [libbeat] Document the disk queue settings
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/general.reference.yml.tmpl
  libbeat/docs/queueconfig.asciidoc
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Integrations, docs, libbeat, needs_backport

#22403 Cherry-pick to 7.10: Do not require sudo to run filebeat in Java tutorial (#22366)
  libbeat/docs/tab-widgets/start-filebeat.asciidoc
  libbeat/docs/tab-widgets/start-widget-filebeat.asciidoc
Labels: backport, docs, needs_team, v7.10.0

#22402 Cherry-pick to 7.x: Do not require sudo to run filebeat in Java tutorial (#22366)
  libbeat/docs/tab-widgets/start-filebeat.asciidoc
  libbeat/docs/tab-widgets/start-widget-filebeat.asciidoc
Labels: backport, docs, needs_team, v7.11.0

#22193 [Ingest Manager] Make TestFleetGateway tests faster
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway_test.go
Labels: Ingest Management:beta2, Team:Ingest Management, bug, needs_backport

#22379 Cherry-pick to 7.9: ci: add a check for changes to deploy/kubernetes pipeline (#22249)
  deploy/kubernetes/Jenkinsfile.yml
Labels: Team:Automation, [zube]: In Review, automation, backport, ci

#22411 Cherry-pick #22261 to 7.10: Fix instance name in perfmon metricset
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/reader_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#22410 Cherry-pick #22261 to 7.x: Fix instance name in perfmon metricset
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/reader_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#22377 Fix for `field [source] not present as part of path [source.ip]` error in azure pipelines
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/azure/activitylogs/ingest/pipeline.yml
  x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.yml
Labels: Team:Platforms, [zube]: In Review, needs_backport

#22424 Cherry-pick #22377 to 7.x: Fix for `field [source] not present as part of path [source.ip]` error in azure pipelines
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/azure/activitylogs/ingest/pipeline.yml
  x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.yml
Labels: Team:Platforms, [zube]: In Review, backport

#22421 Cherry-pick #22377 to 7.10: Fix for `field [source] not present as part of path [source.ip]` error in azure pipelines
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/azure/activitylogs/ingest/pipeline.yml
  x-pack/filebeat/module/azure/signinlogs/ingest/pipeline.yml
Labels: Team:Platforms, [zube]: In Review, backport

#22332 [Docs] Fixes fields documentation for php_fpm metricbeat module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/php_fpm/fields.go
  metricbeat/module/php_fpm/process/_meta/fields.yml
Labels: Team:Docs, docs, needs_backport, v6.8.13, v7.10.0, v7.9.4

#22401 Cherry-pick to 7.9: docs: Fixed typo (#22386)
  libbeat/processors/actions/docs/rename.asciidoc
Labels: Team:Docs, backport

#22400 Cherry-pick to 7.10: docs: Fixed typo (#22386)
  libbeat/processors/actions/docs/rename.asciidoc
Labels: Team:Docs, backport

#22399 Cherry-pick to 7.x: docs: Fixed typo (#22386)
  libbeat/processors/actions/docs/rename.asciidoc
Labels: Team:Docs, backport

#22389 Autodiscover ephemeral containers in kubernetes
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
Labels: Team:Platforms, needs_backport, v7.11.0

#22382 Cherry-pick to 6.8: ci: improve linting speed (#22103)
  Jenkinsfile
  Jenkinsfile.yml
  Makefile
  auditbeat/Jenkinsfile.yml
  deploy/kubernetes/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/libbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#22358 Cherry-pick #21696 to 7.x: Add ja3 fields to Zeek SSL log
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/zeek.asciidoc
  x-pack/filebeat/module/zeek/_meta/docs.asciidoc
  x-pack/filebeat/module/zeek/_meta/kibana/7/dashboard/Filebeat-Zeek-Overview.json
  x-pack/filebeat/module/zeek/ssl/config/ssl.yml
  x-pack/filebeat/module/zeek/ssl/ingest/pipeline.yml
  x-pack/filebeat/module/zeek/ssl/test/ssl-json.log-expected.json
  x-pack/filebeat/module/zeek/ssl/test/ssl-with-ja3-and-custom-fields-json.log
  x-pack/filebeat/module/zeek/ssl/test/ssl-with-ja3-and-custom-fields-json.log-expected.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#22435 Cherry-pick #22245 to 7.x: [libbeat] Document the disk queue settings
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/general.reference.yml.tmpl
  libbeat/docs/queueconfig.asciidoc
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Integrations, [zube]: In Review, backport

#22436 Cherry-pick #22245 to 7.10: [libbeat] Document the disk queue settings
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/general.reference.yml.tmpl
  libbeat/docs/queueconfig.asciidoc
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Integrations, [zube]: In Review, backport

#22381 Cherry-pick to 6.8: ci: add a check for changes to deploy/kubernetes pipeline (#22249)
  deploy/kubernetes/Jenkinsfile.yml
Labels: Team:Automation, [zube]: In Review, automation, backport, ci

#22431 Cherry-pick to 7.x: fixes fields documentation for php_fpm metricbeat module (#22332)
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/php_fpm/fields.go
  metricbeat/module/php_fpm/process/_meta/fields.yml
Labels: Team:Docs, backport

#22429 Cherry-pick to 7.9: fixes fields documentation for php_fpm metricbeat module (#22332)
  metricbeat/docs/fields.asciidoc
  metricbeat/module/php_fpm/fields.go
  metricbeat/module/php_fpm/process/_meta/fields.yml
Labels: Team:Docs, backport

#22428 Cherry-pick to 7.10: fixes fields documentation for php_fpm metricbeat module (#22332)
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/php_fpm/fields.go
  metricbeat/module/php_fpm/process/_meta/fields.yml
Labels: Team:Docs, backport

#22434 Cherry-pick #22389 to 7.x: Autodiscover ephemeral containers in kubernetes
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#22432 [packaging] add SNAPSHOT in the metadata labels if required
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Packaging, Team:Automation, automation

#22412 [Filebeat] Add event.ingested to Netflow module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/netflow/log/ingest/pipeline.yml
Labels: Filebeat, Team:Security-External Integrations, enhancement, needs_backport

#22367 remove working in progress comment
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
Labels: Team:Docs

#22451 Cherry-pick to 7.10: remove working in progress comment (#22367)
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
Labels: backport, docs, needs_team

#22450 Cherry-pick to 7.x: remove working in progress comment (#22367)
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
Labels: backport, docs, needs_team

#22393 [libbeat] Document the Kafka output backoff settings
  libbeat/outputs/kafka/docs/kafka.asciidoc
Labels: Team:Integrations, docs, libbeat, needs_backport

#22291 [Filebeat] Refactor Suricata pipeline to use Ingest Node more
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/suricata/eve/config/eve.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns-answer-v1.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns-answer-v2.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns.yml
  x-pack/filebeat/module/suricata/eve/ingest/pipeline.yml
  x-pack/filebeat/module/suricata/eve/ingest/tls.yml
  x-pack/filebeat/module/suricata/eve/manifest.yml
  x-pack/filebeat/module/suricata/eve/test/eve-dns-4.1.4.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, enhancement, needs_backport

#22452 Cherry-pick to master: remove working in progress comment (#22367)
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
Labels: backport, docs, needs_team

#22406 Cherry-pick #22325 to 7.x: Duplicate system.process.cmdline field with process.command_line ECS field name
  CHANGELOG.next.asciidoc
  metricbeat/module/system/process/_meta/data.json
  metricbeat/module/system/process/process.go
  metricbeat/module/system/test_system.py
  metricbeat/tests/system/test_processors.py
Labels: Team:Platforms, [zube]: In Review, backport

#22409 Add docs about configuring dynamic inputs
  x-pack/elastic-agent/docs/elastic-agent-dynamic-inputs.asciidoc
  x-pack/elastic-agent/docs/elastic-agent.asciidoc
Labels: Team:Docs, Team:Ingest Management, docs, v7.10.0

#22454 Cherry-pick to 7.x: Add docs about configuring dynamic inputs (#22409)
  x-pack/elastic-agent/docs/elastic-agent-dynamic-inputs.asciidoc
  x-pack/elastic-agent/docs/elastic-agent.asciidoc
Labels: backport, docs, needs_team

#22455 Cherry-pick to 7.10: Add docs about configuring dynamic inputs (#22409)
  x-pack/elastic-agent/docs/elastic-agent-dynamic-inputs.asciidoc
  x-pack/elastic-agent/docs/elastic-agent.asciidoc
Labels: backport, docs, needs_team

#22417 Cherry-pick #21814 to 7.x: Add tests of reader of filestream input
  filebeat/input/filestream/filestream.go
  filebeat/input/filestream/filestream_test.go
  filebeat/input/filestream/filestream_test_non_windows.go
Labels: Team:Services, [zube]: In Review, backport

#22418 Cherry-pick #21814 to 7.10: Add tests of reader of filestream input
  filebeat/input/filestream/filestream.go
  filebeat/input/filestream/filestream_test.go
  filebeat/input/filestream/filestream_test_non_windows.go
Labels: Team:Services, [zube]: In Review, backport

#22419 Cherry-pick #21615 to 7.x: Add documentation of filestream input
  filebeat/docs/filebeat-options.asciidoc
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/docs/inputs/input-filestream-reader-options.asciidoc
  filebeat/docs/inputs/input-filestream.asciidoc
Labels: Team:Services, [zube]: In Review, backport

#22420 Cherry-pick #21615 to 7.10: Add documentation of filestream input
  filebeat/docs/filebeat-options.asciidoc
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/docs/inputs/input-filestream-reader-options.asciidoc
  filebeat/docs/inputs/input-filestream.asciidoc
Labels: Team:Services, [zube]: In Review, backport

#22422 Cherry-pick #20450 to 7.x: Check if Filebeat log harvester tries to open named pipe
  filebeat/input/log/harvester.go
Labels: Team:Services, [zube]: In Review, backport

#22423 Cherry-pick #20450 to 7.10: Check if Filebeat log harvester tries to open named pipe
  filebeat/input/log/harvester.go
Labels: Team:Services, [zube]: In Review, backport

#22425 Cherry-pick #20727 to 7.x: feature - parallelization factor kinesis functionbeat config
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/_meta/config/beat.reference.yml.tmpl
  x-pack/functionbeat/_meta/config/beat.yml.tmpl
  x-pack/functionbeat/docs/config-options-aws.asciidoc
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/functionbeat/functionbeat.yml
  x-pack/functionbeat/provider/aws/aws/kinesis.go
  x-pack/functionbeat/provider/aws/aws/kinesis_test.go
Labels: Team:Services, [zube]: In Review, backport

#22426 Cherry-pick #20727 to 7.10: feature - parallelization factor kinesis functionbeat config
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/_meta/config/beat.reference.yml.tmpl
  x-pack/functionbeat/_meta/config/beat.yml.tmpl
  x-pack/functionbeat/docs/config-options-aws.asciidoc
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/functionbeat/functionbeat.yml
  x-pack/functionbeat/provider/aws/aws/kinesis.go
  x-pack/functionbeat/provider/aws/aws/kinesis_test.go
Labels: Team:Services, [zube]: In Review, backport

#22446 Cherry-pick to 7.x: [packaging] add SNAPSHOT in the metadata labels if required (#22432)
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Automation, automation, backport, ci

#22447 Cherry-pick to 7.10: [packaging] add SNAPSHOT in the metadata labels if required (#22432)
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Automation, automation, backport, ci

#22443 [CI] install tools failed in some workers
  .ci/scripts/install-tools.bat
Labels: Team:Automation, automation, ci

#22416 Cherry-pick #22357 to 7.10: Add warning about setup.template.overwrite to documentation and reference configuration
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/setup.template.reference.yml.tmpl
  libbeat/docs/howto/load-index-templates.asciidoc
  libbeat/docs/template-config.asciidoc
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Services, [zube]: In Review, backport

#22461 ci: job to launch beat-tester only with the version
  .ci/beats-tester-bc.groovy
  .ci/jobs/beats-tester-bc.yml
Labels: Team:Automation, automation, ci, enhancement

#22463 Cherry-pick to 7.x: [CI] install tools fail in some workers (#22443)
  .ci/scripts/install-tools.bat
Labels: Team:Automation, automation, backport, ci

#22465 ci: set script-path to .ci/beats-tester-bc.groovy
  .ci/beats-tester-bc.groovy
  .ci/jobs/beats-tester-bc.yml
Labels: Team:Automation, automation, bug, ci

#22415 Cherry-pick #22357 to 7.x: Add warning about setup.template.overwrite to documentation and reference configuration
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/setup.template.reference.yml.tmpl
  libbeat/docs/howto/load-index-templates.asciidoc
  libbeat/docs/template-config.asciidoc
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Services, [zube]: In Review, backport

#22467 ci: fix params definition
  .ci/beats-tester-bc.groovy
Labels: Team:Automation, automation, bug, ci

#22464 Cherry-pick to 7.10: [CI] install tools fail in some workers (#22443)
  .ci/scripts/install-tools.bat
Labels: Team:Automation, automation, backport, ci

#22352 [Elastic Agent] Add priority to dynamic input provider mappings
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/composable/controller.go
  x-pack/elastic-agent/pkg/composable/dynamic.go
  x-pack/elastic-agent/pkg/composable/providers/docker/docker.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/config.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/kubernetes.go
  x-pack/elastic-agent/pkg/composable/providers/localdynamic/localdynamic.go
  x-pack/elastic-agent/pkg/composable/providers/localdynamic/localdynamic_test.go
  x-pack/elastic-agent/pkg/composable/testing/dynamic.go
Labels: Team:Ingest Management, review

#22469 ci: split version ID to run beats-tester
  .ci/beats-tester-bc.groovy
Labels: Team:Automation, automation, bug, ci

#22453 Cherry-pick #22291 to 7.x: [Filebeat] Refactor Suricata pipeline to use Ingest Node more
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/suricata/eve/config/eve.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns-answer-v1.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns-answer-v2.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns.yml
  x-pack/filebeat/module/suricata/eve/ingest/pipeline.yml
  x-pack/filebeat/module/suricata/eve/ingest/tls.yml
  x-pack/filebeat/module/suricata/eve/manifest.yml
  x-pack/filebeat/module/suricata/eve/test/eve-dns-4.1.4.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#22449 Cherry-pick #22412 to 7.x: [Filebeat] Add event.ingested to Netflow module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/netflow/log/ingest/pipeline.yml
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#22470 Cherry-pick #22352 to 7.x: [Elastic Agent] Add priority to dynamic input provider mappings
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/composable/controller.go
  x-pack/elastic-agent/pkg/composable/dynamic.go
  x-pack/elastic-agent/pkg/composable/providers/docker/docker.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/config.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/kubernetes.go
  x-pack/elastic-agent/pkg/composable/providers/localdynamic/localdynamic.go
  x-pack/elastic-agent/pkg/composable/providers/localdynamic/localdynamic_test.go
  x-pack/elastic-agent/pkg/composable/testing/dynamic.go
Labels: Team:Ingest Management, [zube]: In Review, backport

#22466 Update template-config.asciidoc
  libbeat/docs/template-config.asciidoc
Labels: Team:Docs, docs

#22471 Cherry-pick to 7.x: [packaging][beats-tester] use commit id binaries (#22027)
  .ci/beats-tester.groovy
  .ci/jobs/beats-tester.yml
  .ci/packaging.groovy
  Jenkinsfile
  Makefile
Labels: Team:Automation, automation, backport, ci

#22472 Cherry-pick to 7.10: [packaging][beats-tester] use commit id binaries (#22027)
  .ci/beats-tester.groovy
  .ci/jobs/beats-tester.yml
  .ci/packaging.groovy
  Jenkinsfile
  Makefile
Labels: Team:Automation, automation, backport, ci

#22339 docs: Prepare Changelog for 7.10.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Automation, Team:Docs, automation, docs, in progress, release

#21282 stop monitoring excluded paths
  CHANGELOG.next.asciidoc
  auditbeat/module/file_integrity/eventreader_fsnotify.go
  auditbeat/module/file_integrity/monitor/monitor.go
  auditbeat/module/file_integrity/monitor/monitor_test.go
  auditbeat/module/file_integrity/monitor/recursive.go
Labels: Team:SIEM

#22383 [CI]: run packaging if ^go.mod changes
  Jenkinsfile
Labels: Packaging, Team:Automation, automation, ci

#22438 Fix duplicated events in kubernetes autodiscover for pods with init or ephemeral containers
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
Labels: Team:Platforms, needs_backport, review, v7.11.0

#22439 Add support for ephemeral containers in add_kubernetes_metadata
  CHANGELOG.next.asciidoc
  libbeat/processors/add_kubernetes_metadata/indexers.go
  libbeat/processors/add_kubernetes_metadata/indexers_test.go
Labels: Team:Platforms, needs_backport, review, v7.11.0

#22484 Cherry-pick to master: docs: Prepare Changelog for 7.10.0 (#22339)
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Automation, automation, backport

#22483 Cherry-pick to 7.x: docs: Prepare Changelog for 7.10.0 (#22339)
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Automation, automation, backport

#22489 Cherry-pick to 7.10: [CI]: run packaging if ^go.mod changes (#22383)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#22492 Cherry-pick #22438 to 7.x: Fix duplicated events in kubernetes autodiscover for pods with init or ephemeral containers
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
Labels: Team:Platforms, [zube]: In Review, backport

#22487 Fix typo in the changelog pull/issue formats
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
Labels: Team:Docs, docs

#22488 Cherry-pick to 7.x: [CI]: run packaging if ^go.mod changes (#22383)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#22480 Removed duplicate sentence in documentation on metricbeat import
  docs/devguide/newdashboards.asciidoc
Labels: Team:Docs

#22213 Rename google-pubsub Filebeat input to gcp-pubsub
  CHANGELOG.next.asciidoc
  filebeat/docs/filebeat-options.asciidoc
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/filebeat.yml
  x-pack/filebeat/_meta/config/filebeat.inputs.reference.xpack.yml.tmpl
  x-pack/filebeat/docs/inputs/input-gcp-pubsub.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/include/list.go
  x-pack/filebeat/input/gcppubsub/_meta/Dockerfile
  x-pack/filebeat/input/gcppubsub/_meta/supported-versions.yml
  x-pack/filebeat/input/gcppubsub/config.go
  x-pack/filebeat/input/gcppubsub/config_test.go
  x-pack/filebeat/input/gcppubsub/docker-compose.yml
  x-pack/filebeat/input/gcppubsub/input.go
  x-pack/filebeat/input/gcppubsub/pubsub_test.go
  x-pack/filebeat/input/gcppubsub/testdata/fake.json
  x-pack/filebeat/module/googlecloud/audit/config/input.yml
  x-pack/filebeat/module/googlecloud/audit/manifest.yml
  x-pack/filebeat/module/googlecloud/firewall/config/input.yml
  x-pack/filebeat/module/googlecloud/firewall/manifest.yml
  x-pack/filebeat/module/googlecloud/vpcflow/config/input.yml
Labels: Team:Ingest Management, Team:Platforms, in progress

#22502 Remove sip.timestamp field
  packetbeat/docs/fields.asciidoc
  packetbeat/protos/sip/_meta/fields.yml
  packetbeat/protos/sip/event.go
  packetbeat/protos/sip/fields.go
  packetbeat/protos/sip/plugin.go
Labels: Packetbeat, Team:Security-External Integrations, bug

#22503 Cherry-pick #22502 to 7.10: Remove sip.timestamp field
  packetbeat/docs/fields.asciidoc
  packetbeat/protos/sip/_meta/fields.yml
  packetbeat/protos/sip/event.go
  packetbeat/protos/sip/fields.go
  packetbeat/protos/sip/plugin.go
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#22475 Remove what's new and add breaking changes
  libbeat/docs/index.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.10.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
  libbeat/docs/release-notes/redirects.asciidoc
  libbeat/docs/release-notes/whats-new.asciidoc
Labels: docs, needs_team, v7.10.0

#22506 Cherry-pick to 7.x: Remove what's new and add breaking changes (#22475)
  libbeat/docs/index.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.10.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
  libbeat/docs/release-notes/redirects.asciidoc
Labels: backport, needs_team

#22507 Cherry-pick to 7.10: Remove what's new and add breaking changes (#22475)
  libbeat/docs/index.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.10.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
  libbeat/docs/release-notes/redirects.asciidoc
Labels: backport, needs_team

#22473 Cherry-pick to 7.x: docs: update template-config.asciidoc (#22466)
  libbeat/docs/template-config.asciidoc
Labels: Team:Docs, backport

#22474 Cherry-pick to 7.10: docs: update template-config.asciidoc (#22466)
  libbeat/docs/template-config.asciidoc
Labels: Team:Docs, backport

#22496 Cherry-pick to master: Deleted duplicate sentence (#22480)
  docs/devguide/newdashboards.asciidoc
Labels: Team:Docs, backport

#22498 Cherry-pick to 7.x: Deleted duplicate sentence (#22480)
  docs/devguide/newdashboards.asciidoc
Labels: Team:Docs, backport
