Repository elastic/beats, pull requests merged in 2021-05, with the labels that each got.

#25468 Fix `go vet` failure on TestDNSProcessorRunInParallel
  libbeat/processors/dns/dns_test.go
Labels: Team:Agent, backport-v7.14.0

#25419 libbeat: add support for defining unit and metric_type field metadata in ES templates
  CHANGELOG.next.asciidoc
  libbeat/mapping/field.go
  libbeat/mapping/field_test.go
  libbeat/template/processor.go
  libbeat/template/processor_test.go
Labels: Team:Agent, backport-v7.14.0, enhancement, v7.14.0

#25439 Update Cyberarkpas/audit pipeline to use the new set processor with type ip
  x-pack/filebeat/module/cyberarkpas/audit/ingest/pipeline.yml
Labels: Team:Security-External Integrations, backport-v7.13.0, cleanup

#25421 [Filebeat] Allow m365 defender to receive incidents with no alerts
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/microsoft/m365_defender/ingest/pipeline.yml
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test-empty.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test-empty.ndjson.log-expected.json
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log-expected.json
Labels: needs_team

#25394 Add support to set gc percentage
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
  x-pack/elastic-agent/pkg/agent/cmd/container.go
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/apm-server.yml
  x-pack/elastic-agent/spec/filebeat.yml
  x-pack/elastic-agent/spec/metricbeat.yml
Labels: Team:Agent, backport-v7.13.0, backport-v7.14.0, v7.13.0

#25483 Cherry-pick #25439 to 7.13: Update Cyberarkpas/audit pipeline to use the new set processor with type ip
  x-pack/filebeat/module/cyberarkpas/audit/ingest/pipeline.yml
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#25460 Cherry-pick #25423 to 7.13: Do not use unversioned home with watcher binary path
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/paths/common.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/rollback.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/service.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/service_darwin.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/service_windows.go
Labels: Team:Agent, Team:Ingest Management, backport, bug, v7.13.0

#25484 Cherry-pick #25421 to 7.x: [Filebeat] Allow m365 defender to receive incidents with no alerts
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/microsoft/m365_defender/ingest/pipeline.yml
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test-empty.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test-empty.ndjson.log-expected.json
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log-expected.json
Labels: backport, needs_team, review

#25485 Cherry-pick #25421 to 7.12: [Filebeat] Allow m365 defender to receive incidents with no alerts
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/microsoft/m365_defender/ingest/pipeline.yml
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test-empty.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test-empty.ndjson.log-expected.json
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log-expected.json
Labels: backport, needs_team, review

#25486 Cherry-pick #25421 to 7.13: [Filebeat] Allow m365 defender to receive incidents with no alerts
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/microsoft/m365_defender/ingest/pipeline.yml
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test-empty.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test-empty.ndjson.log-expected.json
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log-expected.json
Labels: backport, needs_team, review

#25482 [Filebeat] Additional parsing for `haproxy.http.request.raw_request_line`
  CHANGELOG.next.asciidoc
  filebeat/module/haproxy/log/ingest/pipeline.yml
  filebeat/module/haproxy/log/test/haproxy.log-expected.json
  filebeat/module/haproxy/log/test/httplog-no-headers.log-expected.json
Labels: Filebeat, Team:Integrations, enhancement

#24312 Adjust host fields in Metricbeat to use ECS 1.9.0 field names
  CHANGELOG.next.asciidoc
  auditbeat/include/fields.go
  filebeat/include/fields.go
  heartbeat/include/fields.go
  journalbeat/include/fields.go
  libbeat/_meta/fields.ecs.yml
  metricbeat/_meta/fields.common.yml
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/cpu/_meta/data.json
  metricbeat/module/system/cpu/data.go
  metricbeat/module/system/network/_meta/data.json
  metricbeat/module/system/network/network.go
  metricbeat/module/system/test_system.py
  packetbeat/include/fields.go
  winlogbeat/include/fields.go
  x-pack/functionbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
  x-pack/metricbeat/module/aws/ec2/_meta/data.json
  x-pack/metricbeat/module/aws/ec2/ec2.go
  x-pack/metricbeat/module/aws/ec2/ec2_test.go
  x-pack/metricbeat/module/azure/add_metadata.go
  x-pack/metricbeat/module/azure/compute_vm/_meta/data.json
  x-pack/metricbeat/module/gcp/compute/_meta/data.json
  x-pack/metricbeat/module/gcp/compute/_meta/data_cpu.json
  x-pack/metricbeat/module/gcp/compute/_meta/data_disk.json
  x-pack/metricbeat/module/gcp/compute/_meta/data_firewall.json
  x-pack/metricbeat/module/gcp/compute/_meta/data_network.json
  x-pack/metricbeat/module/gcp/metrics/metricset.go
  x-pack/osquerybeat/include/fields.go
Labels: Team:Integrations, breaking change, needs_backport, review

#25472 Fix `make check` failure in matchers.go, Go 1.16
  libbeat/common/match/matchers.go
Labels: Team:Agent, cleanup

#25466 Cherry-pick #25448 to 7.x: Fix libbeat path docs
  CHANGELOG.next.asciidoc
  libbeat/docs/shared-path-config.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#25467 Cherry-pick #25448 to 7.13: Fix libbeat path docs
  CHANGELOG.next.asciidoc
  libbeat/docs/shared-path-config.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#25496 Cherry-pick #25482 to 7.x: [Filebeat] Additional parsing for `haproxy.http.request.raw_request_line`
  CHANGELOG.next.asciidoc
  filebeat/module/haproxy/log/ingest/pipeline.yml
  filebeat/module/haproxy/log/test/haproxy.log-expected.json
  filebeat/module/haproxy/log/test/httplog-no-headers.log-expected.json
Labels: needs_team

#25446 Allow role_arn work with access keys for AWS
  CHANGELOG.next.asciidoc
  x-pack/libbeat/autodiscover/providers/aws/elb/provider.go
  x-pack/libbeat/common/aws/credentials.go
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Integrations, needs_backport, review

#25499 [Heartbeat] Add context to HTTP body read errors
  CHANGELOG.next.asciidoc
  heartbeat/monitors/active/http/respbody.go
Labels: Heartbeat, Team:Uptime, bug, v7.13.0

#25477 Cherry-pick to 7.12: Update command-reference.asciidoc (#25404)
  libbeat/docs/command-reference.asciidoc
Labels: Team:Docs, backport, docs

#25475 Cherry-pick to 7.x: Update command-reference.asciidoc (#25404)
  libbeat/docs/command-reference.asciidoc
Labels: Team:Docs, backport, docs

#25476 Cherry-pick to 7.13: Update command-reference.asciidoc (#25404)
  libbeat/docs/command-reference.asciidoc
Labels: Team:Docs, backport, docs

#25250 [Filebeat] Remove space from field `sophos.xg.trans_src_ ip`
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/sophos/fields.go
  x-pack/filebeat/module/sophos/xg/_meta/fields.yml
Labels: Team:Security-External Integrations, bug

#25303 Update documentation of `filestream` input with the new improvements
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/docs/inputs/input-filestream-reader-options.asciidoc
  filebeat/docs/inputs/input-filestream.asciidoc
Labels: Team:Agent, docs

#25459 Cherry-pick #25423 to 7.x: Do not use unversioned home with watcher binary path
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/paths/common.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/rollback.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/service.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/service_darwin.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/service_windows.go
Labels: Team:Agent, Team:Ingest Management, backport, bug, v7.13.0

#25520 [Elastic Agent] Adjust some naming to fleet-server
  x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway.go
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/enroll_cmd.go
Labels: Team:Agent, backport-v7.13.0, backport-v7.14.0

#25517 Revert "Revert "[CI] googleStorageUploadExt step (#24048)""
  .ci/packaging.groovy
  Jenkinsfile
Labels: Team:Automation, backport-v7.13.0, backport-v7.14.0

#25519 Revert "[7.13](backport #25454) Revert "[CI] googleStorageUploadExt step (#24048)""
  .ci/packaging.groovy
  Jenkinsfile
Labels: Team:Automation

#25518 Revert "[7.x](backport #25454) Revert "[CI] googleStorageUploadExt step (#24048)""
  .ci/packaging.groovy
  Jenkinsfile
Labels: Team:Automation

#25503 Cherry-pick #25446 to 7.x: Allow role_arn work with access keys for AWS
  CHANGELOG.next.asciidoc
  x-pack/libbeat/autodiscover/providers/aws/elb/provider.go
  x-pack/libbeat/common/aws/credentials.go
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#25504 Cherry-pick #25446 to 7.13: Allow role_arn work with access keys for AWS
  CHANGELOG.next.asciidoc
  x-pack/libbeat/autodiscover/providers/aws/elb/provider.go
  x-pack/libbeat/common/aws/credentials.go
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#24892 Fix related.ip field
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/security/config/winlogbeat-security.js
  x-pack/winlogbeat/module/security/test/testdata/security-windows2012_4768.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2012_4769.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2012_4770.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/security-windows2012r2-logon.evtx.golden.json
Labels: Team:Security-External Integrations, backport-v7.14.0, review

#25512 Osquerybeat: Set elastic_agent on the output data
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/osquerybeat.yml
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/internal/config/config.go
Labels: Team:Asset Mgt, backport-v7.13.0, backport-v7.14.0, bug

#25538 [automation] update elastic stack version for testing 7.13.0-e9675cbf
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, dependency, needs_team

#25464 New option `suffix` in `logging.files` to control how Beat log files are rotated
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/logging.reference.yml.tmpl
  libbeat/common/file/interval_rotator.go
  libbeat/common/file/interval_rotator_test.go
  libbeat/common/file/rotator.go
  libbeat/common/file/rotator_test.go
  libbeat/common/file/trigger.go
  libbeat/docs/loggingconfig.asciidoc
  libbeat/logp/config.go
  libbeat/logp/core.go
  libbeat/outputs/fileout/config.go
  libbeat/outputs/fileout/file.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/elastic-agent/pkg/core/logger/logger.go
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Agent

#25516 [Ingest Management] Fix Insert when array is empty
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/controller.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/modifiers/fleet_decorator.go
  x-pack/elastic-agent/pkg/agent/install/uninstall.go
  x-pack/elastic-agent/pkg/agent/transpiler/ast.go
  x-pack/elastic-agent/pkg/agent/transpiler/ast_test.go
  x-pack/elastic-agent/pkg/agent/transpiler/rules.go
Labels: Team:Agent, Team:Ingest Management, bug, needs_backport, v7.13.0

#25544 Cherry-pick #25516 to 7.13: Fix Insert when array is empty
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/controller.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/modifiers/fleet_decorator.go
  x-pack/elastic-agent/pkg/agent/install/uninstall.go
  x-pack/elastic-agent/pkg/agent/transpiler/ast.go
  x-pack/elastic-agent/pkg/agent/transpiler/ast_test.go
  x-pack/elastic-agent/pkg/agent/transpiler/rules.go
Labels: Team:Agent, backport, bug, v7.13.0

#25505 Mark cyberark module as deprecated
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/cyberark.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/cyberark/_meta/config.yml
  x-pack/filebeat/module/cyberark/_meta/docs.asciidoc
  x-pack/filebeat/modules.d/cyberark.yml.disabled
Labels: Team:Security-External Integrations, backport-v7.13.0, backport-v7.14.0, breaking change, cleanup, docs

#25543 Cherry-pick #25516 to 7.x: Fix Insert when array is empty
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/controller.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/modifiers/fleet_decorator.go
  x-pack/elastic-agent/pkg/agent/install/uninstall.go
  x-pack/elastic-agent/pkg/agent/transpiler/ast.go
  x-pack/elastic-agent/pkg/agent/transpiler/ast_test.go
  x-pack/elastic-agent/pkg/agent/transpiler/rules.go
Labels: Team:Agent, backport, bug, v7.13.0

#25501 Cherry-pick #24312 to 7.x: Adjust host fields in Metricbeat to use ECS 1.9.0 field names
  CHANGELOG.next.asciidoc
  auditbeat/include/fields.go
  filebeat/include/fields.go
  heartbeat/include/fields.go
  journalbeat/include/fields.go
  libbeat/_meta/fields.ecs.yml
  metricbeat/_meta/fields.common.yml
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/cpu/_meta/data.json
  metricbeat/module/system/cpu/data.go
  metricbeat/module/system/network/_meta/data.json
  metricbeat/module/system/network/network.go
  metricbeat/module/system/test_system.py
  packetbeat/include/fields.go
  winlogbeat/include/fields.go
  x-pack/functionbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
  x-pack/metricbeat/module/aws/ec2/_meta/data.json
  x-pack/metricbeat/module/aws/ec2/ec2.go
  x-pack/metricbeat/module/aws/ec2/ec2_test.go
  x-pack/metricbeat/module/azure/add_metadata.go
  x-pack/metricbeat/module/azure/compute_vm/_meta/data.json
  x-pack/metricbeat/module/gcp/compute/_meta/data.json
  x-pack/metricbeat/module/gcp/compute/_meta/data_cpu.json
  x-pack/metricbeat/module/gcp/compute/_meta/data_disk.json
  x-pack/metricbeat/module/gcp/compute/_meta/data_firewall.json
  x-pack/metricbeat/module/gcp/compute/_meta/data_network.json
  x-pack/metricbeat/module/gcp/metrics/metricset.go
  x-pack/osquerybeat/include/fields.go
Labels: Team:Integrations, [zube]: In Review, backport

#25409 Fix `community_id` processor so that ports greater than 65535 aren't valid
  CHANGELOG.next.asciidoc
  libbeat/processors/communityid/communityid.go
  libbeat/processors/communityid/communityid_test.go
  x-pack/filebeat/module/zeek/connection/test/connection-json.log
  x-pack/filebeat/module/zeek/connection/test/connection-json.log-expected.json
Labels: Team:Security-External Integrations, backport-v7.12.0, backport-v7.13.0, backport-v7.14.0, bug

#25525 Cherry-pick #25250 to 7.12: [Filebeat] Remove space from field `sophos.xg.trans_src_ ip`
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/sophos/fields.go
  x-pack/filebeat/module/sophos/xg/_meta/fields.yml
Labels: needs_team

#25526 Cherry-pick #25250 to 7.13: [Filebeat] Remove space from field `sophos.xg.trans_src_ ip`
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/sophos/fields.go
  x-pack/filebeat/module/sophos/xg/_meta/fields.yml
Labels: needs_team

#25524 Cherry-pick #25250 to 7.x: [Filebeat] Remove space from field `sophos.xg.trans_src_ ip`
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/sophos/fields.go
  x-pack/filebeat/module/sophos/xg/_meta/fields.yml
Labels: needs_team

#25506 docs(heartbeat): add browser monitor configuration
  heartbeat/docs/heartbeat-options.asciidoc
  heartbeat/docs/monitors/monitor-browser.asciidoc
Labels: Team:Uptime, docs, v7.13.0

#25562 [Elastic Agent] Fix AckBatch to do nothing when no actions passed.
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/fleetapi/acker/fleet/fleet_acker.go
  x-pack/elastic-agent/pkg/fleetapi/acker/fleet/fleet_acker_test.go
Labels: Team:Agent, backport-v7.13.0, backport-v7.14.0

#25422 libbeat: support explicit dynamic templates
  CHANGELOG.next.asciidoc
  libbeat/mapping/field.go
  libbeat/mapping/field_test.go
  libbeat/template/processor.go
  libbeat/template/processor_test.go
Labels: Team:Agent, backport-v7.14.0, enhancement, v7.14.0

#25545 Update python dependencies
  libbeat/tests/system/requirements.txt
  metricbeat/module/kubernetes/_meta/terraform/eks/requirements.txt
Labels: :Testing, Team:Integrations, needs_backport, review

#25572 [automation] update elastic stack version for testing 7.14.0-5b4d7537
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, dependency, needs_team

#25554 Fix for azure billing dashboard
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/azure/_meta/fields.yml
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-storage-overview.json
  x-pack/metricbeat/module/azure/billing/data.go
  x-pack/metricbeat/module/azure/fields.go
Labels: Team:Integrations

#25547 Enable TestConfigurableFailed as logging behaviour has changed
  x-pack/elastic-agent/pkg/agent/operation/operator_test.go
Labels: Team:Agent

#25560 Mark filestream input Beta
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-filestream.asciidoc
  filebeat/input/filestream/input.go
Labels: Team:Agent, needs_backport

#25579 Cherry-pick #25554 to 7.x: Fix for azure billing dashboard
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/azure/_meta/fields.yml
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-storage-overview.json
  x-pack/metricbeat/module/azure/billing/data.go
  x-pack/metricbeat/module/azure/fields.go
Labels: Team:Integrations, [zube]: In Review, backport

#25578 Cherry-pick #25554 to 7.12: Fix for azure billing dashboard
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/azure/_meta/fields.yml
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-storage-overview.json
  x-pack/metricbeat/module/azure/billing/data.go
  x-pack/metricbeat/module/azure/fields.go
Labels: Team:Integrations, [zube]: In Review, backport

#25587 Remove `:` from rotated file names when date suffix is selected
  libbeat/common/file/rotator.go
  libbeat/common/file/rotator_test.go
Labels: backport-v7.13.0, backport-v7.14.0, needs_team

#25502 Add error log for listener creation failure
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/control/server/server.go
Labels: Team:Agent, backport-v7.14.0, enhancement, review, v7.14.0

#25354 Add detailed docker network summary stats
  CHANGELOG.next.asciidoc
  go.mod
  go.sum
  libbeat/metric/system/network/helpers.go
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/docker.asciidoc
  metricbeat/docs/modules/docker/network_summary.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_docker.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/docker/_meta/config.reference.yml
  metricbeat/module/docker/_meta/config.yml
  metricbeat/module/docker/fields.go
  metricbeat/module/docker/network/_meta/data.json
  metricbeat/module/docker/network_summary/_meta/data.json
  metricbeat/module/docker/network_summary/_meta/docs.asciidoc
  metricbeat/module/docker/network_summary/_meta/fields.yml
  metricbeat/module/docker/network_summary/config.go
  metricbeat/module/docker/network_summary/doc.go
  metricbeat/module/docker/network_summary/helper.go
  metricbeat/module/docker/network_summary/network_summary.go
  metricbeat/module/docker/network_summary/network_summary_test.go
  metricbeat/module/system/network_summary/data.go
  metricbeat/module/system/network_summary/network_summary.go
  metricbeat/module/system/network_summary/network_summary_test.go
  metricbeat/modules.d/docker.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Metricbeat, Team:Integrations, enhancement, v7.13.0

#25592 [Heartbeat] Disable default monitor from heartbeat.yml for agent compat
  heartbeat/_meta/config/beat.yml.tmpl
  heartbeat/heartbeat.yml
  x-pack/heartbeat/heartbeat.yml
Labels: bug, needs_team, v7.13.0

#25568 docs: `filestream` input review updates
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/docs/inputs/input-filestream-reader-options.asciidoc
  filebeat/docs/inputs/input-filestream.asciidoc
Labels: Team:Docs, v7.13.0

#25605 Cherry-pick to 7.13: docs: `filestream` review updates (#25568)
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/docs/inputs/input-filestream-reader-options.asciidoc
  filebeat/docs/inputs/input-filestream.asciidoc
Labels: Team:Docs, backport

#25604 Cherry-pick to 7.x: docs: `filestream` review updates (#25568)
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/docs/inputs/input-filestream-reader-options.asciidoc
  filebeat/docs/inputs/input-filestream.asciidoc
Labels: Team:Docs, backport

#25611 [automation] update elastic stack version for testing 7.14.0-8ba10577
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, dependency, needs_team

#25627 [automation] update elastic stack version for testing 7.13.0-4c96d7bf
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, dependency, needs_team

#25626 [automation] update elastic stack version for testing 7.14.0-7d5ea6dc
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, dependency, needs_team

#25609 [Filebeat] Fix `checkpoint.action_reason` when its a string, not a Long
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/checkpoint/fields.go
  x-pack/filebeat/module/checkpoint/firewall/_meta/fields.yml
  x-pack/filebeat/module/checkpoint/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/checkpoint/firewall/test/checkpoint_with_time.log
  x-pack/filebeat/module/checkpoint/firewall/test/checkpoint_with_time.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, bug

#24665 [filebeat][tomcat][bug] fixed error from beats about non iterable list for tomcat module
  filebeat/docs/modules/tomcat.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/tomcat/_meta/config.yml
  x-pack/filebeat/module/tomcat/_meta/docs.asciidoc
  x-pack/filebeat/modules.d/tomcat.yml.disabled
Labels: Team:Integrations, Team:Security-External Integrations

#25632 [mergify] automerge PRs for mergify prs with auto-bumps
  .mergify.yml
Labels: Team:Automation, automation

#25629 Update Golang to 1.15.12
  .go-version
  CHANGELOG-developer.next.asciidoc
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: Team:Agent, backport-v7.13.0, backport-v7.14.0

#25617 Reduce Winlogbeat info log level verbosity
  CHANGELOG.next.asciidoc
  winlogbeat/beater/eventlogger.go
  winlogbeat/beater/winlogbeat.go
  winlogbeat/tests/system/test_config.py
Labels: Team:Security-External Integrations, Winlogbeat, backport-v7.14.0, enhancement, review

#17110 Use the correct timezone in panos module
  x-pack/filebeat/module/panw/panos/config/input.yml
  x-pack/filebeat/module/panw/panos/ingest/pipeline.yml
  x-pack/filebeat/module/panw/panos/test/pan_inc_traffic_ietf.log
  x-pack/filebeat/module/panw/panos/test/pan_inc_traffic_ietf.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, backport-v7.14.0, needs_integration_sync, review

#25550 Add server id to zookeeper events
  CHANGELOG.next.asciidoc
  metricbeat/module/zookeeper/connection/_meta/data.json
  metricbeat/module/zookeeper/connection/connection.go
  metricbeat/module/zookeeper/mntr/_meta/data.json
  metricbeat/module/zookeeper/mntr/data.go
  metricbeat/module/zookeeper/mntr/mntr.go
  metricbeat/module/zookeeper/server/_meta/data.json
  metricbeat/module/zookeeper/server/server.go
  metricbeat/module/zookeeper/zookeeper.go
  metricbeat/module/zookeeper/zookeeper_integration_test.go
Labels: Team:Integrations, needs_backport

#25652 Update FreeBSD vagrantbox
  CHANGELOG.next.asciidoc
  Vagrantfile
Labels: Team:Integrations, bug

#24927 [Filebeat] Add PanOS Global Protect & User ID logs
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/panw/fields.go
  x-pack/filebeat/module/panw/panos/_meta/fields.yml
  x-pack/filebeat/module/panw/panos/config/input.yml
  x-pack/filebeat/module/panw/panos/ingest/globalprotect.yml
  x-pack/filebeat/module/panw/panos/ingest/pipeline.yml
  x-pack/filebeat/module/panw/panos/ingest/threat.yml
  x-pack/filebeat/module/panw/panos/ingest/traffic.yml
  x-pack/filebeat/module/panw/panos/ingest/userid.yml
  x-pack/filebeat/module/panw/panos/manifest.yml
  x-pack/filebeat/module/panw/panos/test/global_protect.log
  x-pack/filebeat/module/panw/panos/test/global_protect.log-expected.json
  x-pack/filebeat/module/panw/panos/test/pan_inc_other.log-expected.json
  x-pack/filebeat/module/panw/panos/test/pan_inc_threat.log-expected.json
  x-pack/filebeat/module/panw/panos/test/pan_inc_traffic.log-expected.json
  x-pack/filebeat/module/panw/panos/test/userid.log
  x-pack/filebeat/module/panw/panos/test/userid.log-expected.json
Labels: 7.14 Candidate, Team:Security-External Integrations, backport-v7.14.0, enhancement, needs_integration_sync

#25664 [Elastic Agent] Inject only when state is not restored
  x-pack/elastic-agent/pkg/agent/application/gateway/fleetserver/fleet_gateway_local.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
Labels: Team:Agent, bug, needs_backport, v7.13.0

#25584 [Elastic Agent] Fixed status reporting
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/core/monitoring/server/handler.go
  x-pack/elastic-agent/pkg/core/monitoring/server/process_test.go
Labels: Team:Agent, bug, needs_backport, v7.13.0

#25673 Fix Vagrantfile function names
  Vagrantfile
Labels: Team:Integrations, bug

#25679 Don't update bind-license in ARM docker build
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Agent, Team:Integrations, v7.13.0

#25688 Cherry-pick #25656 to 7.13: Disable flaky test
  x-pack/elastic-agent/pkg/agent/operation/operator_test.go
Labels: Team:Agent, backport, bug

#25687 Cherry-pick #25656 to 7.x Disable flaky test
  x-pack/elastic-agent/pkg/agent/operation/operator_test.go
Labels: Team:Agent, backport, bug

#25576 Cherry-pick #25545 to 7.x: Update python dependencies
  libbeat/tests/system/requirements.txt
Labels: Team:Integrations, [zube]: In Review, backport

#25682 Cherry-pick #25664 to 7.13: Inject only when state is not restored
  x-pack/elastic-agent/pkg/agent/application/gateway/fleetserver/fleet_gateway_local.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
Labels: Team:Agent, [zube]: 7.13, backport, bug

#24918 [Filebeat] Enable HMAC Signature Validation for http_endpoint input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
  x-pack/filebeat/input/http_endpoint/config.go
  x-pack/filebeat/input/http_endpoint/handler.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/http_endpoint/validate.go
  x-pack/filebeat/tests/system/test_http_endpoint.py
Labels: Team:Security-External Integrations, enhancement, needs_backport

#25701 [Elastic Agent] Do not apply config if newer is available during restart
  x-pack/elastic-agent/pkg/agent/operation/operator_test.go
  x-pack/elastic-agent/pkg/core/plugin/process/start.go
  x-pack/elastic-agent/pkg/core/plugin/process/status.go
  x-pack/elastic-agent/pkg/core/plugin/service/app.go
Labels: Team:Agent, bug, needs_backport, v7.13.0

#25707 [Elastic Agent] Handle case where policy doesn't contain Fleet connection information
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go
Labels: Team:Agent, backport-v7.13.0, backport-v7.14.0

#25716 [automation] update elastic stack version for testing 7.14.0-e8048b9e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, dependency, needs_team

#25704 Cherry-pick #25701 to 7.13: Do not apply config if newer is available during restart
  x-pack/elastic-agent/pkg/agent/operation/operator_test.go
  x-pack/elastic-agent/pkg/core/plugin/process/start.go
  x-pack/elastic-agent/pkg/core/plugin/process/status.go
  x-pack/elastic-agent/pkg/core/plugin/service/app.go
Labels: Team:Agent, backport, bug, v7.13.0

#25681 Cherry-pick #25664 to 7.x: Inject only when state is not restored
  x-pack/elastic-agent/pkg/agent/application/gateway/fleetserver/fleet_gateway_local.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
Labels: Team:Agent, backport, bug, v7.13.0

#25684 Cherry-pick #25584 to 7.x: Fixed status reporting
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/core/monitoring/server/handler.go
  x-pack/elastic-agent/pkg/core/monitoring/server/process_test.go
Labels: Team:Agent, backport, bug, v7.13.0

#25683 Cherry-pick #25584 to 7.13: Fixed status reporting
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/core/monitoring/server/handler.go
  x-pack/elastic-agent/pkg/core/monitoring/server/process_test.go
Labels: Team:Agent, backport, bug, v7.13.0

#25590 [Elastic Agent] Retry deamon reload during enroll
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
Labels: Team:Agent, bug, needs_backport

#25718 Cherry-pick #25590 to 7.13: Retry deamon reload during enroll
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
Labels: Team:Agent, backport, bug, v7.13.0

#25719 Cherry-pick #25590 to 7.x: Retry deamon reload during enroll
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
Labels: Team:Agent, backport, bug, v7.13.0

#25703 Cherry-pick #25701 to 7.x: Do not apply config if newer is available during restart
  x-pack/elastic-agent/pkg/agent/operation/operator_test.go
  x-pack/elastic-agent/pkg/core/plugin/process/start.go
  x-pack/elastic-agent/pkg/core/plugin/process/status.go
  x-pack/elastic-agent/pkg/core/plugin/service/app.go
Labels: Team:Agent, backport, bug, v7.13.0

#25616 [Filebeat] Update Grok pattern for UDM logs
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/iptables/log/ingest/pipeline.yml
  x-pack/filebeat/module/iptables/log/test/ubiquiti.log
  x-pack/filebeat/module/iptables/log/test/ubiquiti.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, enhancement, needs_integration_sync

#25631 [Metricbeat] In jolokia jmx mbean canonization the keys should be sorted first
  CHANGELOG.next.asciidoc
  metricbeat/module/jolokia/jmx/config.go
  metricbeat/module/jolokia/jmx/config_test.go
Labels: Team:Integrations, backport-v7.13.0, backport-v7.14.0

#25601 Cherry-pick #25354 to 7.x: Add detailed docker network summary stats
  go.mod
  go.sum
  libbeat/metric/system/network/helpers.go
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/docker.asciidoc
  metricbeat/docs/modules/docker/network_summary.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_docker.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/docker/_meta/config.reference.yml
  metricbeat/module/docker/_meta/config.yml
  metricbeat/module/docker/fields.go
  metricbeat/module/docker/network/_meta/data.json
  metricbeat/module/docker/network_summary/_meta/data.json
  metricbeat/module/docker/network_summary/_meta/docs.asciidoc
  metricbeat/module/docker/network_summary/_meta/fields.yml
  metricbeat/module/docker/network_summary/config.go
  metricbeat/module/docker/network_summary/doc.go
  metricbeat/module/docker/network_summary/helper.go
  metricbeat/module/docker/network_summary/network_summary.go
  metricbeat/module/docker/network_summary/network_summary_test.go
  metricbeat/module/system/network_summary/data.go
  metricbeat/module/system/network_summary/network_summary.go
  metricbeat/module/system/network_summary/network_summary_test.go
  metricbeat/modules.d/docker.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Integrations, [zube]: In Review, backport

#25710 Add multiline support to awss3 input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/collector.go
  x-pack/filebeat/input/awss3/collector_test.go
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/ftest/sample2.txt
  x-pack/filebeat/input/awss3/s3_integration_test.go
Labels: Team:Security-External Integrations, backport-v7.14.0, enhancement

#25741 [Elastic Agent] Fix fleet-server.yml spec to not overwrite existing keys
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/pkg/agent/program/testdata/fleet_server-fleet-server.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/fleet_server.yml
  x-pack/elastic-agent/pkg/agent/transpiler/rules.go
  x-pack/elastic-agent/pkg/agent/transpiler/rules_test.go
  x-pack/elastic-agent/spec/fleet-server.yml
Labels: Team:Agent, backport-v7.13.0, backport-v7.14.0

#25711 [Filebeat] Instrument aws-s3 with metrics
  CHANGELOG.next.asciidoc
  filebeat/input/v2/compat/compat.go
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/collector.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/metrics.go
Labels: Filebeat, Team:Integrations, Team:Security-External Integrations, backport-v7.14.0, enhancement, review

#25746 Add env for http monitor container command
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/container.go
Labels: Team:Agent, backport-v7.14.0

#25752 [automation] update elastic stack version for testing 7.14.0-c4ef352d
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, dependency, needs_team

#25551 [Elastic Agent] Add hint on how to build and test the container for Elastic Agent
  x-pack/elastic-agent/README.md
  x-pack/elastic-agent/docs/README.md
Labels: Team:Agent, backport-v7.14.0

#25640 Refactor state_* metricsets to share response from endpoint
  CHANGELOG.next.asciidoc
  metricbeat/helper/prometheus/prometheus.go
  metricbeat/module/kubernetes/kubernetes.go
  metricbeat/module/kubernetes/state_container/state_container.go
  metricbeat/module/kubernetes/state_cronjob/state_cronjob.go
  metricbeat/module/kubernetes/state_daemonset/state_daemonset.go
  metricbeat/module/kubernetes/state_deployment/state_deployment.go
  metricbeat/module/kubernetes/state_node/state_node.go
  metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume.go
  metricbeat/module/kubernetes/state_persistentvolumeclaim/state_persistentvolumeclaim.go
  metricbeat/module/kubernetes/state_pod/state_pod.go
  metricbeat/module/kubernetes/state_replicaset/state_replicaset.go
  metricbeat/module/kubernetes/state_resourcequota/state_resourcequota.go
  metricbeat/module/kubernetes/state_service/state_service.go
  metricbeat/module/kubernetes/state_statefulset/state_statefulset.go
  metricbeat/module/kubernetes/state_storageclass/state_storageclass.go
Labels: Team:Integrations, kubernetes, refactoring, test-plan, v7.14.0

#25759 Cherry-pick #25640 to 7.x: Refactor state_* metricsets to share response from endpoint
  CHANGELOG.next.asciidoc
  metricbeat/helper/prometheus/prometheus.go
  metricbeat/module/kubernetes/kubernetes.go
  metricbeat/module/kubernetes/state_container/state_container.go
  metricbeat/module/kubernetes/state_cronjob/state_cronjob.go
  metricbeat/module/kubernetes/state_daemonset/state_daemonset.go
  metricbeat/module/kubernetes/state_deployment/state_deployment.go
  metricbeat/module/kubernetes/state_node/state_node.go
  metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume.go
  metricbeat/module/kubernetes/state_persistentvolumeclaim/state_persistentvolumeclaim.go
  metricbeat/module/kubernetes/state_pod/state_pod.go
  metricbeat/module/kubernetes/state_replicaset/state_replicaset.go
  metricbeat/module/kubernetes/state_resourcequota/state_resourcequota.go
  metricbeat/module/kubernetes/state_service/state_service.go
  metricbeat/module/kubernetes/state_statefulset/state_statefulset.go
  metricbeat/module/kubernetes/state_storageclass/state_storageclass.go
Labels: Team:Integrations, [zube]: In Review, backport

#25760 Osquerybeat: Fix osqueryd binary on linux executable permissions
  x-pack/osquerybeat/scripts/mage/package.go
Labels: Team:Asset Mgt, backport-v7.13.0, backport-v7.14.0, bug, v7.13.0, v7.14.0

#25763 [Filebeat] Fix aws-s3 config initialization plus cleanup
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/collector.go
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/config_test.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/s3_integration_test.go
Labels: Filebeat, Team:Security-External Integrations, backport-v7.14.0, bug, review

#25757 Revert "Add env for http monitor container command (#25746)"
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/container.go
Labels: Team:Agent

#25772 aws-s3 input default content-type
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/collector.go
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/config_test.go
Labels: Filebeat, Team:Security-External Integrations, backport-v7.14.0, enhancement

#25784 Fix license header for osquery-extension
  x-pack/osquerybeat/ext/osquery-extension/main.go
Labels: Team:Asset Mgt, backport-v7.14.0, cleanup

#25778 [Filebeat] Mitigate deadlock in aws-s3 ACKHandler
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/_meta/s3-input.asciidoc
  x-pack/filebeat/input/awss3/collector.go
  x-pack/filebeat/input/awss3/testdata/sample1.txt
  x-pack/filebeat/input/awss3/testdata/sample2.txt
Labels: Filebeat, Team:Security-External Integrations, bug, review

#25790 Cherry-pick #25784 to 7.x: Fix license header for osquery-extension
  x-pack/osquerybeat/ext/osquery-extension/main.go
Labels: Team:Asset Mgt, [zube]: In Review, backport

#25792 [Filebeat] Fix file_selectors only using first selector in aws-s3 input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/collector.go
Labels: Filebeat, Team:Integrations, Team:Security-External Integrations, backport-v7.14.0, bug

#25694 Add breaking changes for 7.13
  libbeat/docs/release-notes/breaking/breaking-7.13.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
Labels: Team:Docs, docs, v7.13.0

#25795 Cherry-pick to 7.13: Add breaking changes for 7.13 (#25694)
  libbeat/docs/release-notes/breaking/breaking-7.13.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
Labels: backport, needs_team

#25794 Cherry-pick to 7.x: Add breaking changes for 7.13 (#25694)
  libbeat/docs/release-notes/breaking/breaking-7.13.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
Labels: backport, needs_team

#25787 [mergify] allow backports in any direction
  .mergify.yml
Labels: Team:Automation, automation

#25660 Use `filestream` input for internal log collection in Agent
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
Labels: Team:Agent, backport-v7.14.0

#25806 Disable flaky filesteam harvester test
  filebeat/input/filestream/internal/input-logfile/harvester_test.go
Labels: Team:Agent, backport-v7.14.0, flaky-test, v7.14.0

#25802 [httpjson] Add ignore_empty_value option to prevent cursor override with empty values
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/internal/v2/config.go
  x-pack/filebeat/input/httpjson/internal/v2/config_test.go
  x-pack/filebeat/input/httpjson/internal/v2/cursor.go
  x-pack/filebeat/input/httpjson/internal/v2/cursor_test.go
Labels: Filebeat, Team:Security-External Integrations, backport-v7.13.0, backport-v7.14.0, bug

#25820 [automation] update elastic stack version for testing 7.13.0-d325823f
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#25822 docs: Prepare Changelog for 6.8.16
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Automation, Team:Docs, automation, docs, in progress, release

#25832 Add breaking change around licensing
  libbeat/docs/release-notes/breaking/breaking-7.13.asciidoc
Labels: docs, needs_team, v7.13.0

#25834 Cherry-pick to 7.13: Add breaking change around licensing (#25832)
  libbeat/docs/release-notes/breaking/breaking-7.13.asciidoc
Labels: backport, needs_team

#25833 Cherry-pick to 7.x: Add breaking change around licensing (#25832)
  libbeat/docs/release-notes/breaking/breaking-7.13.asciidoc
Labels: backport, needs_team

#25187 chore: Update version to 7.13.1
  libbeat/version/version.go
Labels: Team:Automation, automation, release

#25803 [Jenkins] Light checkout
  Jenkinsfile
Labels: Team:Automation

#25837 [automation] update elastic stack version for testing 7.13.0-b10ff4f4
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#25823 docs: Prepare Changelog for 7.13.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Automation, automation, docs, in progress, release

#25788 Fix cyberarkpas XSLT handling of TAB and Carriage Return special chars
  x-pack/filebeat/module/cyberarkpas/_meta/assets/elastic-json-v1.0.xsl
Labels: Team:Security-External Integrations, backport-v7.13.0, backport-v7.14.0, bug, review

#25843 chore: Update version to 6.8.17
  libbeat/version/version.go
Labels: Team:Automation, automation, release

#25849 Forward port to 7.x: Prepare Changelog for 7.13.0 (#25823)
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#25674 [Filebeat] Fix bad append for abusechmalware
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/threatintel/abusemalware/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/abusemalware/test/abusechmalware.ndjson.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, enhancement

#25842 chore: update test environments for 6.8.16
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: Team:Automation, automation, release

#25852 Forward port to master: Prepare Changelog for 7.13.0 (#25823)
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#25776 adding a for loop with script processor to add values from cisco.umbrella.identities to related.user field
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/umbrella/ingest/pipeline.yml
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-dnslogs.log
  x-pack/filebeat/module/cisco/umbrella/test/umbrella-dnslogs.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, backport-v7.14.0, enhancement

#22970 [libbeat] Track frame counts in saved segments in the disk queue
  libbeat/publisher/queue/diskqueue/acks.go
  libbeat/publisher/queue/diskqueue/config.go
  libbeat/publisher/queue/diskqueue/consumer.go
  libbeat/publisher/queue/diskqueue/core_loop.go
  libbeat/publisher/queue/diskqueue/core_loop_test.go
  libbeat/publisher/queue/diskqueue/queue.go
  libbeat/publisher/queue/diskqueue/reader_loop.go
  libbeat/publisher/queue/diskqueue/segments.go
  libbeat/publisher/queue/diskqueue/serialize.go
  libbeat/publisher/queue/diskqueue/state_file.go
  libbeat/publisher/queue/diskqueue/writer_loop.go
Labels: Team:Integrations, enhancement, libbeat

#25859 Disable heartbeat and metricbeat tests
  heartbeat/monitors/active/http/http_test.go
  heartbeat/monitors/active/tcp/tls_test.go
  metricbeat/module/golang/test_golang.py
Labels: Team:Integrations, Team:Uptime, backport-v7.14.0, flaky-test, v7.14.0

#25841 [google_workspace] Use fingerprint to generate fixed document id to avoid having duplicates
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/google_workspace/config/common.js
Labels: Filebeat, Team:Security-External Integrations, backport-v7.14.0, enhancement

#25869 Increase wait time to stabilize `TestRotateDateSuffix`
  libbeat/common/file/rotator_test.go
Labels: backport-v7.13.0, backport-v7.14.0, needs_team

#25864 ci: exclude builds with changes on the k8s templates files
  Jenkinsfile
Labels: Team:Automation, backport-v7.12.0, backport-v7.13.0, backport-v7.14.0

#25756 Log input: remove states more eagerly
  CHANGELOG.next.asciidoc
  filebeat/input/log/input.go
  filebeat/registrar/registrar.go
Labels: Team:Agent, backport-v7.13.0, backport-v7.14.0, enhancement

#25105 chore: Update test environments 7.12.2
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Automation, automation, release

#25971 Clean up fixture files
  x-pack/filebeat/module/crowdstrike/falcon/test/falcon-sample.log
  x-pack/filebeat/module/crowdstrike/falcon/test/falcon-sample.log-expected.json
Labels: Team:Security-External Integrations, backport-v7.11.0, backport-v7.12.0, backport-v7.13.0, backport-v7.14.0, backport-v7.15.0, cleanup

#25782 Refactor kubelet metricsets to share response from endpoint
  CHANGELOG.next.asciidoc
  metricbeat/module/kubernetes/container/container.go
  metricbeat/module/kubernetes/kubernetes.go
  metricbeat/module/kubernetes/node/node.go
  metricbeat/module/kubernetes/pod/pod.go
  metricbeat/module/kubernetes/state_container/state_container.go
  metricbeat/module/kubernetes/state_cronjob/state_cronjob.go
  metricbeat/module/kubernetes/state_daemonset/state_daemonset.go
  metricbeat/module/kubernetes/state_deployment/state_deployment.go
  metricbeat/module/kubernetes/state_node/state_node.go
  metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume.go
  metricbeat/module/kubernetes/state_persistentvolumeclaim/state_persistentvolumeclaim.go
  metricbeat/module/kubernetes/state_pod/state_pod.go
  metricbeat/module/kubernetes/state_replicaset/state_replicaset.go
  metricbeat/module/kubernetes/state_resourcequota/state_resourcequota.go
  metricbeat/module/kubernetes/state_service/state_service.go
  metricbeat/module/kubernetes/state_statefulset/state_statefulset.go
  metricbeat/module/kubernetes/state_storageclass/state_storageclass.go
  metricbeat/module/kubernetes/system/system.go
  metricbeat/module/kubernetes/volume/volume.go
Labels: Team:Integrations, kubernetes, v7.14.0

#25977 Disable armv7 packaging
  Jenkinsfile
Labels: Team:Automation, backport-v7.13.0, backport-v7.14.0

#25982 Cherry-pick #25782 to 7.x: Refactor kubelet metricsets to share response from endpoint
  CHANGELOG.next.asciidoc
  metricbeat/module/kubernetes/container/container.go
  metricbeat/module/kubernetes/kubernetes.go
  metricbeat/module/kubernetes/node/node.go
  metricbeat/module/kubernetes/pod/pod.go
  metricbeat/module/kubernetes/state_container/state_container.go
  metricbeat/module/kubernetes/state_cronjob/state_cronjob.go
  metricbeat/module/kubernetes/state_daemonset/state_daemonset.go
  metricbeat/module/kubernetes/state_deployment/state_deployment.go
  metricbeat/module/kubernetes/state_node/state_node.go
  metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume.go
  metricbeat/module/kubernetes/state_persistentvolumeclaim/state_persistentvolumeclaim.go
  metricbeat/module/kubernetes/state_pod/state_pod.go
  metricbeat/module/kubernetes/state_replicaset/state_replicaset.go
  metricbeat/module/kubernetes/state_resourcequota/state_resourcequota.go
  metricbeat/module/kubernetes/state_service/state_service.go
  metricbeat/module/kubernetes/state_statefulset/state_statefulset.go
  metricbeat/module/kubernetes/state_storageclass/state_storageclass.go
  metricbeat/module/kubernetes/system/system.go
  metricbeat/module/kubernetes/volume/volume.go
Labels: Team:Integrations, [zube]: In Review, backport

#25854 [Elastic Agent] Fix invalid log level sent to endpoint
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_id.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_info.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_metadata.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_settings.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/modifiers/fleet_decorator.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/storage/disk_store.go
  x-pack/elastic-agent/pkg/agent/storage/handler_store.go
  x-pack/elastic-agent/pkg/agent/storage/null_store.go
  x-pack/elastic-agent/pkg/agent/storage/replace_store.go
  x-pack/elastic-agent/pkg/agent/storage/storage.go
  x-pack/elastic-agent/pkg/core/logger/logger.go
Labels: Team:Agent, backport-v7.13.0, bug, needs_backport, v7.13.0

#25969 [7.13](backport #25756) Log input: remove states more eagerly
  CHANGELOG.next.asciidoc
  filebeat/input/log/input.go
  filebeat/registrar/registrar.go
Labels: needs_team

#26002 [automation] update elastic stack version for testing 7.13.1-1ba26435
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26001 [automation] update elastic stack version for testing 7.14.0-62d7f45e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#24100 chore: update docs to next minor 7.14.0
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: Team:Automation, automation, docs, in progress, release
