Repository elastic/beats, pull requests merged in 2021-10, with the labels that each got.

#28207 [automation] update elastic stack version for testing 7.15.1-a28dd8b0
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency, backport-skip

#28208 [automation] update elastic stack version for testing 7.16.0-806be5a9
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency, backport-skip

#28196 Remove deprecated coredns fields for 8.0
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/coredns/_meta/fields.yml
  x-pack/filebeat/module/coredns/fields.go
  x-pack/filebeat/module/coredns/log/ingest/pipeline-entry.yml
  x-pack/filebeat/module/coredns/log/test/coredns-json.log-expected.json
  x-pack/filebeat/module/coredns/log/test/coredns.log-expected.json
Labels: enhancement, Team:Integrations, breaking change, Team:Security-External Integrations, 8.0-candidate, backport-skip

#28048 libbeat/beat: introduce Beat.OutputConfigReloader
  CHANGELOG-developer.next.asciidoc
  libbeat/beat/beat.go
  libbeat/cmd/instance/beat.go
Labels: enhancement, Team:Agent, v7.16.0, backport-v7.16.0

#28224 [automation] update elastic stack version for testing 7.16.0-76e5f71e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency, backport-skip

#28225 [automation] update elastic stack version for testing 7.15.1-3517e2e9
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency, backport-skip

#28120 Remove deprecated AWS config options
  CHANGELOG.next.asciidoc
  x-pack/libbeat/common/aws/credentials.go
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
  x-pack/metricbeat/module/aws/aws.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/elb/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/mtest/integration.go
  x-pack/metricbeat/module/aws/mtest/scripts/test_cloudwatch_metricset.yml
Labels: Team:Integrations, backport-skip

#28161 Move aws-cloudwatch input to GA
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-cloudwatch.asciidoc
Labels: needs_team, backport-v7.16.0

#28170 Remove overwriting AWS config with endpoint in aws-cloudwatch input
  x-pack/filebeat/input/awscloudwatch/input.go
Labels: Team:Integrations, backport-v7.15.0, backport-v7.16.0

#28163 fix(ci): use the right parent directory for uploading GoIntegTests artifacts
  Jenkinsfile
Labels: Team:Automation, backport-v7.15.0, backport-v7.16.0

#28235 [mergify] remove backport-skip if added a backport label
  .mergify.yml
Labels: Team:Automation, backport-skip

#28247 Port IncludeAnnotations setting to Agent and small manifest fix
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/config.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/kubernetes.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/node.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/pod.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/service.go
Labels: Team:Integrations, backport-v7.16.0

#28180 use 0s ttl
  x-pack/metricbeat/module/airflow/statsd/data_test.go
Labels: Team:Integrations, backport-v7.15.0, backport-v7.16.0

#28242 Rename Fleet User Guide
  libbeat/docs/upgrading.asciidoc
Labels: docs, Team:Docs, backport-v7.14.0, v7.16.0, backport-v7.15.0, backport-v7.16.0

#28268 [automation] update elastic stack version for testing 6.8.20-431ef06e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency, backport-skip

#28276 Fix build with lint change
  metricbeat/docs/modules/linux/memory.asciidoc
Labels: Team:Integrations

#28264 [7.x] [DOCS] Update ES ingest pipeline refs (#28239)
  auditbeat/auditbeat.reference.yml
  auditbeat/docs/fields.asciidoc
  auditbeat/module/auditd/_meta/fields.yml
  auditbeat/module/auditd/fields.go
  docs/devguide/modules-dev-guide.asciidoc
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/beater/filebeat.go
  filebeat/docs/filebeat-modules-options.asciidoc
  filebeat/docs/include/what-happens.asciidoc
  filebeat/docs/inputs/input-common-options.asciidoc
  filebeat/docs/modules-overview.asciidoc
  filebeat/docs/modules/iptables.asciidoc
  filebeat/docs/modules/netflow.asciidoc
  filebeat/filebeat.reference.yml
  heartbeat/_meta/config/beat.reference.yml.tmpl
  heartbeat/docs/monitors/monitor-common-options.asciidoc
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/output-elasticsearch.reference.yml.tmpl
  libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
  libbeat/docs/shared-config-ingest.asciidoc
  libbeat/docs/shared-geoip.asciidoc
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/dockerlogbeat/docs/configuration.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/iptables/_meta/docs.asciidoc
  x-pack/filebeat/module/netflow/_meta/docs.asciidoc
  x-pack/functionbeat/docs/overview.asciidoc
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: backport, Team:Docs

#28165 [elastic-agent] proxy requests to subprocesses to their metrics endpoints
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/core/monitoring/server/process.go
  x-pack/elastic-agent/pkg/core/monitoring/server/process_linux_test.go
  x-pack/elastic-agent/pkg/core/monitoring/server/server.go
Labels: enhancement, Agent, Team:Elastic-Agent, backport-v7.16.0

#28191 [Winlogbeat] Tolerate faults when Windows Event Log session is interrupted
  CHANGELOG.next.asciidoc
  filebeat/input/winlog/input.go
  winlogbeat/beater/eventlogger.go
  winlogbeat/eventlog/errors_unix.go
  winlogbeat/eventlog/errors_windows.go
  winlogbeat/sys/wineventlog/syscall_windows.go
Labels: bug, Winlogbeat, Team:Security-External Integrations, backport-v7.16.0

#27771 Do not load ML jobs to 8.x from 7.x releases
  CHANGELOG.next.asciidoc
  filebeat/beater/filebeat.go
  filebeat/fileset/modules.go
  libbeat/beat/beat.go
  libbeat/cmd/instance/beat.go
  libbeat/cmd/setup.go
  libbeat/docs/command-reference.asciidoc
  libbeat/ml-importer/importer.go
Labels: Team:Elastic-Agent
