Repository elastic/beats, pull requests merged in 2021-03, with the labels that each got.

#24234 Cherry-pick #24219 to 7.x: Store cloudfoundry.container.cpu.pct in decimal form
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/cloudfoundry/container/_meta/fields.yml
  x-pack/metricbeat/module/cloudfoundry/container/container.go
  x-pack/metricbeat/module/cloudfoundry/container/container_test.go
  x-pack/metricbeat/module/cloudfoundry/fields.go
  x-pack/metricbeat/module/cloudfoundry/util.go
  x-pack/metricbeat/module/cloudfoundry/util_test.go
  x-pack/metricbeat/module/cloudfoundry/value/value.go
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, backport

#24261 [CI]: if corrupted installation in workers then install tools
  .ci/scripts/install-docker-compose.sh
  .ci/scripts/install-kind.sh
  .ci/scripts/install-kubectl.sh
  .ci/scripts/install-terraform.sh
Labels: Team:Automation

#24232 Cherry-pick #24218 to 7.x: [Metricbeat] Google Cloud: Do not try to setup region filter on Cloudfunctions metrics
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/gcp/constants.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
Labels: Metricbeat, Team:Services, [zube]: In Review, backport, bug

#24243 Cherry-pick #24140 to 7.x: [Filebeat] Format and spell check Threat Intel module docs
  filebeat/docs/modules/threatintel.asciidoc
  x-pack/filebeat/module/threatintel/_meta/docs.asciidoc
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#24276 Cherry-pick to 7.x: [CI]: if corrupted installation in workers then install tools (#24261)
  .ci/scripts/install-docker-compose.sh
  .ci/scripts/install-kind.sh
  .ci/scripts/install-kubectl.sh
  .ci/scripts/install-terraform.sh
Labels: Team:Automation, automation, backport, ci

#24281 [Elastic Agent] Fix #24273 - Fix SIGSEGV due to missing err check
  x-pack/elastic-agent/pkg/agent/application/application.go
Labels: Team:Agent, Team:Ingest Management

#24220 [Elastic Agent] Add support for Fleet Server inside Docker
  dev-tools/packaging/templates/docker/docker-entrypoint.elastic-agent.tmpl
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_policy_change.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/cmd/common.go
  x-pack/elastic-agent/pkg/agent/cmd/container.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
  x-pack/elastic-agent/pkg/core/process/cmd.go
  x-pack/elastic-agent/pkg/core/process/cmd_darwin.go
  x-pack/elastic-agent/pkg/core/process/cmd_linux.go
  x-pack/elastic-agent/pkg/core/process/process.go
  x-pack/elastic-agent/pkg/fleetapi/enroll_cmd.go
Labels: Team:Fleet, Team:Ingest Management

#24254 Cherry-pick #24247 to 7.x: [Heartbeat] Remove extraneous factory log
  heartbeat/monitors/factory.go
Labels: Heartbeat, Team:Uptime, [zube]: In Review, backport

#24226 Cherry-pick #23970 to 7.12: Rewrite check for admin
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/install.go
  x-pack/elastic-agent/pkg/agent/cmd/uninstall.go
  x-pack/elastic-agent/pkg/agent/install/root_unix.go
  x-pack/elastic-agent/pkg/agent/install/root_windows.go
  x-pack/elastic-agent/pkg/agent/install/root_windows_test.go
Labels: Team:Agent, Team:Ingest Management, [zube]: In Review, backport

#24227 Cherry-pick #23970 to 7.x: Rewrite check for admin
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/install.go
  x-pack/elastic-agent/pkg/agent/cmd/uninstall.go
  x-pack/elastic-agent/pkg/agent/install/root_unix.go
  x-pack/elastic-agent/pkg/agent/install/root_windows.go
  x-pack/elastic-agent/pkg/agent/install/root_windows_test.go
Labels: Team:Agent, Team:Ingest Management, [zube]: In Review, backport

#24277 Cherry-pick to 7.12: [CI]: if corrupted installation in workers then install tools (#24261)
  .ci/scripts/install-docker-compose.sh
  .ci/scripts/install-kind.sh
  .ci/scripts/install-kubectl.sh
  .ci/scripts/install-terraform.sh
Labels: Team:Automation, automation, backport, ci

#24282 Cherry-pick #24281 to 7.x: [Elastic Agent] Fix #24273 - Fix SIGSEGV due to missing err check
  x-pack/elastic-agent/pkg/agent/application/application.go
Labels: Team:Agent, Team:Ingest Management, [zube]: In Review, backport

#24191 Cherry-pick #24142 to 7.x: [Elastic Agent] Add options to bootstrap Fleet Server with TLS
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/config.go
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
  x-pack/elastic-agent/pkg/agent/configuration/fleet_server.go
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/fleet-server.yml
Labels: Team:Agent, Team:Ingest Management, [zube]: In Review, backport

#24248 Use `timed.Periodic` when running the periodic scans of filestream
  filebeat/input/filestream/fswatch.go
Labels: Team:Agent

#24290 [Ingest Manager] Uninstall do not fail on state not present
  x-pack/elastic-agent/pkg/config/operations/inspector.go
Labels: Team:Agent, Team:Ingest Management, bug

#24253 [Ingest Manager] Make installer atomic on windows
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/operation/operator.go
  x-pack/elastic-agent/pkg/artifact/install/atomic/atomic_installer.go
  x-pack/elastic-agent/pkg/artifact/install/awaitable/awaitable_installer.go
  x-pack/elastic-agent/pkg/artifact/install/installer.go
  x-pack/elastic-agent/pkg/artifact/install/tar/tar_installer.go
  x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go
Labels: Team:Agent, Team:Ingest Management, bug, needs_backport

#24291 Cherry-pick #24220 to 7.x: [Elastic Agent] Add support for Fleet Server inside Docker
  dev-tools/packaging/templates/docker/docker-entrypoint.elastic-agent.tmpl
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_policy_change.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/cmd/common.go
  x-pack/elastic-agent/pkg/agent/cmd/container.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
  x-pack/elastic-agent/pkg/core/process/cmd.go
  x-pack/elastic-agent/pkg/core/process/cmd_darwin.go
  x-pack/elastic-agent/pkg/core/process/cmd_linux.go
  x-pack/elastic-agent/pkg/core/process/process.go
  x-pack/elastic-agent/pkg/fleetapi/enroll_cmd.go
Labels: Team:Fleet, Team:Ingest Management, [zube]: In Review, backport

#24257 Alphabetize AWS S3 input in list
  filebeat/docs/filebeat-options.asciidoc
Labels: Filebeat, Team:Docs, docs

#24296 Cherry-pick #24253 to 7.12: Make installer atomic on windows
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/operation/operator.go
  x-pack/elastic-agent/pkg/artifact/install/atomic/atomic_installer.go
  x-pack/elastic-agent/pkg/artifact/install/awaitable/awaitable_installer.go
  x-pack/elastic-agent/pkg/artifact/install/installer.go
  x-pack/elastic-agent/pkg/artifact/install/tar/tar_installer.go
  x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go
Labels: Team:Agent, Team:Ingest Management, backport, bug

#24258 Fix admonition tag to render text correctly
  filebeat/docs/inputs/input-log.asciidoc
Labels: Filebeat, Team:Docs, docs

#24303 Cherry-pick to 7.11: Fix admonition tag to render text correctly (#24258)
  filebeat/docs/inputs/input-log.asciidoc
Labels: backport, docs, needs_team

#24302 Cherry-pick to 7.12: Fix admonition tag to render text correctly (#24258)
  filebeat/docs/inputs/input-log.asciidoc
Labels: backport, docs, needs_team

#24301 Cherry-pick to 7.x: Fix admonition tag to render text correctly (#24258)
  filebeat/docs/inputs/input-log.asciidoc
Labels: backport, docs, needs_team

#24300 Cherry-pick to 7.11: Alphabetize AWS S3 input in list (#24257)
  filebeat/docs/filebeat-options.asciidoc
Labels: backport, docs, needs_team

#24298 Cherry-pick to 7.x: Alphabetize AWS S3 input in list (#24257)
  filebeat/docs/filebeat-options.asciidoc
Labels: backport, docs, needs_team

#24306 chore(ci): rename variable for E2E tests
  .ci/packaging.groovy
Labels: Team:Automation

#24307 Cherry-pick to 7.x: chore(ci): rename variable for E2E tests (#24306)
  .ci/packaging.groovy
Labels: Team:Automation, backport

#24308 Cherry-pick to 7.12: chore(ci): rename variable for E2E tests (#24306)
  .ci/packaging.groovy
Labels: Team:Automation, backport

#24309 Cherry-pick to 7.11: chore(ci): rename variable for E2E tests (#24306)
  .ci/packaging.groovy
Labels: Team:Automation, backport

#24289 [CI] resilience when windows workers fail with deleteDir
  Jenkinsfile
  script/fix_permissions.sh
Labels: Team:Automation, macOS

#24215 Cherry-pick #24139 to 7.x: Add running aws module on docker doc
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#24216 Cherry-pick #24139 to 7.12: Add running aws module on docker doc
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#24297 Cherry-pick #24253 to 7.x: Make installer atomic on windows
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/operation/operator.go
  x-pack/elastic-agent/pkg/artifact/install/atomic/atomic_installer.go
  x-pack/elastic-agent/pkg/artifact/install/awaitable/awaitable_installer.go
  x-pack/elastic-agent/pkg/artifact/install/installer.go
  x-pack/elastic-agent/pkg/artifact/install/tar/tar_installer.go
  x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go
Labels: Team:Agent, Team:Ingest Management, backport, bug

#24313 Cherry-pick to 7.x: [CI] resilience when windows workers fail with deleteDir (#24289)
  Jenkinsfile
  script/fix_permissions.sh
Labels: Team:Automation, automation, backport, ci, macOS

#24314 Cherry-pick to 7.12: [CI] resilience when windows workers fail with deleteDir (#24289)
  Jenkinsfile
  script/fix_permissions.sh
Labels: Team:Automation, automation, backport, ci

#24318 Fix event time calculation on docker events
  CHANGELOG.next.asciidoc
  libbeat/common/docker/watcher.go
Labels: Team:Integrations, bug, containers, needs_backport, test-plan, v7.11.2, v7.12.0, v7.13.0

#24316 CI: add resilience when ephemeral windows workers are reused
  Jenkinsfile
Labels: Team:Automation, macOS

#24206 [Heartbeat] Added synthetics step status field
  heartbeat/_meta/fields.common.yml
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
Labels: Team:Uptime

#24322 Cherry-pick #24318 to 7.12: Fix event time calculation on docker events
  CHANGELOG.next.asciidoc
  libbeat/common/docker/watcher.go
Labels: Team:Integrations, [zube]: In Review, backport

#24320 Cherry-pick #24318 to 7.x: Fix event time calculation on docker events
  CHANGELOG.next.asciidoc
  libbeat/common/docker/watcher.go
Labels: Team:Integrations, [zube]: In Review, backport

#24321 Cherry-pick #24318 to 7.11: Fix event time calculation on docker events
  CHANGELOG.next.asciidoc
  libbeat/common/docker/watcher.go
Labels: Team:Integrations, [zube]: In Review, backport

#24339 x-pack/metricbeat: Disable Windows 7 32 bit builder
  x-pack/metricbeat/Jenkinsfile.yml
Labels: Team:Automation, Team:Integrations

#24324 Cherry-pick to 7.x: CI: add resilience when ephemeral windows workers are reused (#24316)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci, macOS

#24325 Cherry-pick to 7.12: CI: add resilience when ephemeral windows workers are reused (#24316)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci, macOS

#24123 Add supported versions file in Metricbeat module for Consul
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/consul.asciidoc
  metricbeat/module/consul/_meta/docs.asciidoc
  metricbeat/module/consul/_meta/supported-versions.yml
  metricbeat/module/consul/docker-compose.yml
  metricbeat/module/consul/test_consul.py
Labels: Team:Integrations, needs_backport

#24326 Cherry-pick to 7.11: CI: add resilience when ephemeral windows workers are reused (#24316)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci, macOS

#24264 support defining metrics_filters for prometheus module in annotations
  CHANGELOG.next.asciidoc
  metricbeat/autodiscover/builder/hints/metrics.go
  metricbeat/autodiscover/builder/hints/metrics_test.go
  metricbeat/docs/autodiscover-hints.asciidoc
Labels: Team:Integrations, enhancement, needs_backport, review, test-plan, v7.13.0

#24278 Cherry-pick #24110 to 7.x: [Filebeat] Document netflow internal_networks and set default
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/netflow.asciidoc
  x-pack/filebeat/docs/inputs/input-netflow.asciidoc
  x-pack/filebeat/input/netflow/config.go
  x-pack/filebeat/module/netflow/_meta/docs.asciidoc
  x-pack/filebeat/module/netflow/log/config/netflow.yml
  x-pack/filebeat/module/netflow/log/manifest.yml
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#24172 [Heartbeat] Add sandbox options, defaulted to off
  CHANGELOG.next.asciidoc
  x-pack/heartbeat/monitors/browser/browser.go
  x-pack/heartbeat/monitors/browser/config.go
  x-pack/heartbeat/monitors/browser/suite_runner.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
Labels: Heartbeat, Team:Uptime, enhancement, v7.13.0

#24358 Cherry-pick #24172 to 7.x: [Heartbeat] Add sandbox options, defaulted to off
  CHANGELOG.next.asciidoc
  x-pack/heartbeat/monitors/browser/browser.go
  x-pack/heartbeat/monitors/browser/config.go
  x-pack/heartbeat/monitors/browser/suite_runner.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
Labels: Heartbeat, Team:Uptime, [zube]: In Review, backport

#24223 [Heartbeat] Handle data streams
  CHANGELOG.next.asciidoc
  heartbeat/monitors/factory.go
  heartbeat/monitors/factory_test.go
  heartbeat/monitors/stdfields/unnest.go
  heartbeat/monitors/stdfields/unnest_test.go
  libbeat/processors/add_data_stream_index/add_data_stream_index.go
  libbeat/processors/add_data_stream_index/add_data_stream_index_test.go
  libbeat/processors/add_data_stream_index/datastream.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/sample-synthetics-config/heartbeat.yml
Labels: Heartbeat, Team:Uptime, enhancement

#24360 Cherry-pick to 7.x: [Heartbeat] Handle data streams (#24223)
  CHANGELOG.next.asciidoc
  heartbeat/monitors/factory.go
  heartbeat/monitors/factory_test.go
  heartbeat/monitors/stdfields/unnest.go
  heartbeat/monitors/stdfields/unnest_test.go
  libbeat/processors/add_data_stream_index/add_data_stream_index.go
  libbeat/processors/add_data_stream_index/add_data_stream_index_test.go
  libbeat/processors/add_data_stream_index/datastream.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/sample-synthetics-config/heartbeat.yml
Labels: Team:Uptime, backport

#24319 [Elastic Agent] Fix issues with enrollment key fetching
  x-pack/elastic-agent/pkg/agent/cmd/container.go
Labels: Team:Agent, Team:Fleet, Team:Ingest Management

#24365 Cherry-pick #24319 to 7.x: [Elastic Agent] Fix issues with enrollment key fetching
  x-pack/elastic-agent/pkg/agent/cmd/container.go
Labels: Team:Agent, Team:Fleet, Team:Ingest Management, [zube]: In Review, backport

#24366 [Heartbeat] Remove warning around messages sent outside journeys
  x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer.go
Labels: Heartbeat, bug, needs_team, v7.12.0

#24174 Allow credential_profile_name and shared_credential_file with role_arn
  CHANGELOG.next.asciidoc
  metricbeat/docs/aws-credentials-examples.asciidoc
  x-pack/libbeat/common/aws/credentials.go
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Integrations, test-plan

#24348 Cherry-pick #24264 to 7.x: support defining metrics_filters for prometheus module in annotations
  CHANGELOG.next.asciidoc
  metricbeat/autodiscover/builder/hints/metrics.go
  metricbeat/autodiscover/builder/hints/metrics_test.go
  metricbeat/docs/autodiscover-hints.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#24362 [CI] Use MacOS for x86_64 arch
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  generator/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/heartbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: Team:Automation, Team:Ingest Management, automation, macOS

#24285 Support for running the container with an arbitrary UID:GID
  dev-tools/packaging/package_test.go
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Agent, enhancement, needs_backport

#24359 Convert postgresql.statement.query.id to number
  metricbeat/module/postgresql/statement/_meta/data.json
  metricbeat/module/postgresql/statement/data.go
Labels: Team:Integrations, review

#24349 Ensure k8s secrets do not enable access by default
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-role.yaml
  libbeat/common/kubernetes/k8skeystore/kubernetes_keystore.go
  metricbeat/docs/autodiscover-kubernetes-config.asciidoc
Labels: Team:Integrations, review, v7.13.0

#24377 Cherry-pick #24359 to 7.x: Convert postgresql.statement.query.id to number
  metricbeat/module/postgresql/statement/_meta/data.json
  metricbeat/module/postgresql/statement/data.go
Labels: Team:Integrations, [zube]: In Review, backport

#24378 Cherry-pick #24359 to 7.12: Convert postgresql.statement.query.id to number
  metricbeat/module/postgresql/statement/_meta/data.json
  metricbeat/module/postgresql/statement/data.go
Labels: Team:Integrations, [zube]: In Review, backport

#24373 Cherry-pick to 7.x: [CI] Use MacOS for x86_64 arch (#24362)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  generator/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/heartbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci, macOS

#24382 Cherry-pick #24349 to 7.x: Ensure k8s secrets do not enable access by default
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-role.yaml
  libbeat/common/kubernetes/k8skeystore/kubernetes_keystore.go
  metricbeat/docs/autodiscover-kubernetes-config.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#24347 Cherry-pick #24123 to 7.x: Add supported versions file in Metricbeat module for Consul
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/consul.asciidoc
  metricbeat/module/consul/_meta/docs.asciidoc
  metricbeat/module/consul/_meta/supported-versions.yml
  metricbeat/module/consul/docker-compose.yml
  metricbeat/module/consul/test_consul.py
Labels: Team:Integrations, [zube]: In Review, backport

#24379 Cherry-pick to 7.x: [Heartbeat] Added synthetics step status field (#24206)
  heartbeat/_meta/fields.common.yml
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
Labels: Team:Uptime, backport

#24343 [Ingest-Manager] Fix windows installer during enroll
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/artifact/install/atomic/atomic_installer.go
  x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go
Labels: Team:Agent, Team:Ingest Management, bug, v7.12.0

#24294 Cherry-pick #24248 to 7.x: Use `timed.Periodic` when running the periodic scans of filestream
  filebeat/input/filestream/fswatch.go
Labels: Team:Agent, [zube]: In Review, backport

#24384 [docker][elastic-agent] minor fixes for setup
  x-pack/elastic-agent/pkg/agent/cmd/container.go
Labels: Team:Ingest Management

#24129 [ILM][Docs] Clarify how to change setup.ilm.pattern
  libbeat/docs/shared-ilm.asciidoc
Labels: Team:Agent, docs, libbeat, review

#24386 [Elastic Agent] Fix FLEET_SERVER_INSECURE_HTTP to use correct parameter on bootstrap.
  x-pack/elastic-agent/pkg/agent/cmd/container.go
Labels: Team:Fleet, Team:Ingest Management

#24389 Cherry-pick #24343 to 7.12: Fix windows installer during enroll
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/artifact/install/atomic/atomic_installer.go
  x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go
Labels: Team:Agent, Team:Ingest Management, backport, bug, v7.12.0

#24346 [Ingest-Manager] Fix capabilities resolution in inspect command
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/capabilities/input.go
  x-pack/elastic-agent/pkg/capabilities/output.go
  x-pack/elastic-agent/pkg/capabilities/upgrade.go
Labels: Team:Agent, Team:Ingest Management, bug, needs_backport, v7.12.0

#24394 Cherry-pick to 7.x: [docker][elastic-agent] minor fixes for setup (#24384)
  x-pack/elastic-agent/pkg/agent/cmd/container.go
Labels: Team:Fleet, backport

#24398 Cherry-pick #24386 to 7.x: [Elastic Agent] Fix FLEET_SERVER_INSECURE_HTTP to use correct parameter on bootstrap.
  x-pack/elastic-agent/pkg/agent/cmd/container.go
Labels: Team:Fleet, Team:Ingest Management, [zube]: In Review, backport

#24399 Cherry-pick #24346 to 7.12: Fix capabilities resolution in inspect command
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/capabilities/input.go
  x-pack/elastic-agent/pkg/capabilities/output.go
  x-pack/elastic-agent/pkg/capabilities/upgrade.go
Labels: Team:Agent, Team:Ingest Management, backport, bug, v7.12.0

#24400 Cherry-pick #24346 to 7.x: Fix capabilities resolution in inspect command
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/capabilities/input.go
  x-pack/elastic-agent/pkg/capabilities/output.go
  x-pack/elastic-agent/pkg/capabilities/upgrade.go
Labels: Team:Agent, Team:Ingest Management, backport, bug

#24374 Cherry-pick to 7.12: [CI] Use MacOS for x86_64 arch (#24362)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  generator/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/heartbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci, macOS

#24387 [Ingest Manager] Fix failing installation on windows 7
  libbeat/common/backoff/exponential.go
  libbeat/common/file/helper_windows.go
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/application/filelock/locker.go
  x-pack/elastic-agent/pkg/agent/application/filelock/locker_test.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_id.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_info.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/paths/files.go
  x-pack/elastic-agent/pkg/agent/cmd/install.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/cmd/watch.go
Labels: Team:Agent, Team:Ingest Management, bug, needs_backport, v7.12.0

#24370 Cherry-pick #24174 to 7.x: Allow credential_profile_name and shared_credential_file with role_arn
  CHANGELOG.next.asciidoc
  metricbeat/docs/aws-credentials-examples.asciidoc
  x-pack/libbeat/common/aws/credentials.go
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#24408 [Ingest Manager] Remove unwanted line
  x-pack/elastic-agent/pkg/agent/application/paths/files.go
Labels: Team:Agent, Team:Ingest Management

#24375 Cherry-pick to 7.11: [CI] Use MacOS for x86_64 arch (#24362)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  generator/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci, macOS

#24414 [fix][auditbeat] Reset file offset when re-reading from the beginning
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/login/login_test.go
  x-pack/auditbeat/module/system/login/utmp.go
Labels: Team:Security-External Integrations, bug

#24336 [Filebeat] httpjson input set Content-Type correctly
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/internal/v2/encoding.go
  x-pack/filebeat/input/httpjson/internal/v2/encoding_test.go
Labels: Filebeat, Team:Security-External Integrations, bug, needs_backport

#24421 Cherry-pick #24336 to 7.x: [Filebeat] httpjson input set Content-Type correctly
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/internal/v2/encoding.go
  x-pack/filebeat/input/httpjson/internal/v2/encoding_test.go
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#24422 Cherry-pick #24336 to 7.12: [Filebeat] httpjson input set Content-Type correctly
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/internal/v2/encoding.go
  x-pack/filebeat/input/httpjson/internal/v2/encoding_test.go
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#23901 [SM] Elasticsearch Mapping
  metricbeat/docs/fields.asciidoc
  metricbeat/module/elasticsearch/_meta/fields.yml
  metricbeat/module/elasticsearch/ccr/_meta/data.json
  metricbeat/module/elasticsearch/ccr/_meta/fields.yml
  metricbeat/module/elasticsearch/ccr/_meta/test/ccr_stats.700.json
  metricbeat/module/elasticsearch/ccr/data.go
  metricbeat/module/elasticsearch/cluster_stats/_meta/data-oss.json
  metricbeat/module/elasticsearch/cluster_stats/_meta/data.json
  metricbeat/module/elasticsearch/cluster_stats/_meta/fields.yml
  metricbeat/module/elasticsearch/cluster_stats/data.go
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/fields.go
  metricbeat/module/elasticsearch/index/_meta/data.json
  metricbeat/module/elasticsearch/index/_meta/fields.yml
  metricbeat/module/elasticsearch/index/data.go
  metricbeat/module/elasticsearch/index_recovery/_meta/data.json
  metricbeat/module/elasticsearch/index_recovery/_meta/fields.yml
  metricbeat/module/elasticsearch/index_recovery/data.go
  metricbeat/module/elasticsearch/index_summary/_meta/data.json
  metricbeat/module/elasticsearch/index_summary/_meta/fields.yml
  metricbeat/module/elasticsearch/index_summary/data.go
  metricbeat/module/elasticsearch/index_summary/data_test.go
  metricbeat/module/elasticsearch/ml_job/_meta/data.json
  metricbeat/module/elasticsearch/ml_job/_meta/fields.yml
  metricbeat/module/elasticsearch/ml_job/data.go
  metricbeat/module/elasticsearch/ml_job/data_test.go
  metricbeat/module/elasticsearch/node_stats/_meta/data.json
  metricbeat/module/elasticsearch/node_stats/_meta/fields.yml
  metricbeat/module/elasticsearch/node_stats/data.go
  metricbeat/module/elasticsearch/shard/data.go
  metricbeat/module/elasticsearch/test_elasticsearch.py
  metricbeat/module/logstash/_meta/fields.yml
  metricbeat/module/logstash/fields.go
  metricbeat/module/logstash/node_stats/_meta/fields.yml
Labels: Metricbeat, Stack monitoring, Team:Integrations

#23976 [SM] Kibana mapping to remove extra fields
  metricbeat/helper/elastic/elastic.go
  metricbeat/module/kibana/_meta/fields.yml
  metricbeat/module/kibana/fields.go
  metricbeat/module/kibana/settings/_meta/data.json
  metricbeat/module/kibana/settings/_meta/fields.yml
  metricbeat/module/kibana/settings/data.go
  metricbeat/module/kibana/stats/_meta/data.json
  metricbeat/module/kibana/stats/_meta/fields.yml
  metricbeat/module/kibana/stats/data.go
Labels: needs_team

#24409 Cherry-pick #24387 to 7.x: Fix failing installation on windows 7
  libbeat/common/backoff/exponential.go
  libbeat/common/file/helper_windows.go
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/application/filelock/locker.go
  x-pack/elastic-agent/pkg/agent/application/filelock/locker_test.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_id.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_info.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/cmd/install.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/cmd/watch.go
Labels: Team:Agent, Team:Ingest Management, backport, bug, v7.12.0

#24330 Update input-common-file-options.asciidoc
  filebeat/docs/inputs/input-common-file-options.asciidoc
Labels: Team:Docs, docs, libbeat

#24259 Cherry-pick #24104 to 7.x: [Metricbeat] Update Cockroachdb Overview and add SQL dashboard
  x-pack/metricbeat/module/cockroachdb/_meta/kibana/7/dashboard/Metricbeat-cockroachdb-overview.json
  x-pack/metricbeat/module/cockroachdb/_meta/kibana/7/dashboard/Metricbeat-cockroachdb-sql.json
Labels: Team:Integrations, [zube]: In Review, backport

#24411 Cherry-pick #24387 to 7.12: Fix failing installation on windows 7
  libbeat/common/backoff/exponential.go
  libbeat/common/file/helper_windows.go
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/application/filelock/locker.go
  x-pack/elastic-agent/pkg/agent/application/filelock/locker_test.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_id.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_info.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/cmd/install.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/cmd/watch.go
Labels: Team:Agent, Team:Ingest Management, backport, bug, v7.12.0

#24438 Cherry-pick #24429 to 7.x: [Elastic Agent] Improve Endpoint installation logging
  x-pack/elastic-agent/.gitignore
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/magefile.go
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/pkg/agent/transpiler/steps.go
  x-pack/elastic-agent/pkg/agent/transpiler/steps_test.go
  x-pack/elastic-agent/pkg/agent/transpiler/tests/exec-1.0-darwin-x86_64/main.go
  x-pack/elastic-agent/spec/endpoint.yml
Labels: Team:Agent, Team:Ingest Management, [zube]: In Review, backport

#24275 [Filebeat] Fix pensando viz
  filebeat/docs/modules/pensando.asciidoc
  filebeat/module/pensando/_meta/docs.asciidoc
  filebeat/module/pensando/_meta/kibana/7/dashboard/pensando-dfw-overview.json
Labels: Team:Security-External Integrations, bug, v7.12.0

#24439 Cherry-pick #24429 to 7.12: [Elastic Agent] Improve Endpoint installation logging
  x-pack/elastic-agent/.gitignore
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/magefile.go
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/pkg/agent/transpiler/steps.go
  x-pack/elastic-agent/pkg/agent/transpiler/steps_test.go
  x-pack/elastic-agent/pkg/agent/transpiler/tests/exec-1.0-darwin-x86_64/main.go
  x-pack/elastic-agent/spec/endpoint.yml
Labels: Team:Agent, Team:Ingest Management, [zube]: In Review, backport

#24376 Cherry-pick #24285 to 7.x: Support for running the container with an arbitrary UID:GID
  dev-tools/packaging/package_test.go
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Agent, [zube]: In Review, backport

#24436 Add support for X-Forwarded-For in IIS logs
  CHANGELOG.next.asciidoc
  filebeat/module/iis/access/ingest/pipeline.yml
  filebeat/module/iis/access/test/test-x-forward-for-extended.log
  filebeat/module/iis/access/test/test-x-forward-for-extended.log-expected.json
  filebeat/module/iis/access/test/test-x-forward-for.log
  filebeat/module/iis/access/test/test-x-forward-for.log-expected.json
Labels: Filebeat, Team:Integrations, module, needs_backport, review, v7.13.0

#24437 docs: Prepare Changelog for 7.11.2
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Automation, automation, docs, in progress, release

#24332 Do not drop errors when checking for templates
  CHANGELOG.next.asciidoc
  libbeat/template/load.go
  libbeat/template/load_integration_test.go
Labels: Team:Agent, needs_backport, review

#24450 Forward-port 7.11.2 changelog to 7.x
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#24452 Forward-port 7.11.2 changelog to master
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#24270 Fix detect_sequence_reset flag in netflow module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/netflow/log/config/netflow.yml
  x-pack/filebeat/module/netflow/log/manifest.yml
Labels: Filebeat, Team:Security-External Integrations, bug, needs_backport, review

#24295 netflow: Use internal and external for locality fields
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/netflow/convert.go
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Barracuda-extended-uniflow-template-256.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Barracuda-firewall.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Mikrotik-RouterOS-6.39.2.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Netscaler-with-variable-length-fields.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Nokia-BRAS.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-OpenBSD-pflow.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Procera.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-VMware-virtual-distributed-switch.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-YAF-basic-with-applabel.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-configured-with-include_flowset_id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-vIPtela-with-VPN-id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-1941-K9-release-15.1.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASA-2.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASA.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASR-9000-series-template-260.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASR1001--X.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-NBAR-flowset-262.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-WLC.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Fortigate-FortiOS-5.2.1.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Fortigate-FortiOS-54x-appid.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-H3C-Netstream-with-varstring.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-H3C.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Huawei-Netstream.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-IE150-IE151.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Palo-Alto-1-flowset-in-large-zero-filled-packet.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Palo-Alto-PAN--OS-with-app--id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Streamcore.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Ubiquiti-Edgerouter-with-MPLS-labels.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-field-layer2segmentid.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-ipt_netflow-reduced-size-encoding.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-macaddress.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-multiple-netflow-exporters.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-nprobe-DPI-L7.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-template-with-0-length-fields.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-valid-01.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/ipfix_cisco.pcap.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/netflow9_e10s_4_7byte_pad.pcap.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/netflow9_ubiquiti_edgerouter.pcap.golden.json
Labels: Team:Security-External Integrations, enhancement, needs_backport, review

#24441 Cherry-pick #24275 to 7.x: [Filebeat] Fix pensando viz
  filebeat/docs/modules/pensando.asciidoc
  filebeat/module/pensando/_meta/docs.asciidoc
  filebeat/module/pensando/_meta/kibana/7/dashboard/pensando-dfw-overview.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#24380 Use alias to report container image in k8s parts
  CHANGELOG.next.asciidoc
  auditbeat/docs/fields.asciidoc
  auditbeat/include/fields.go
  filebeat/docs/fields.asciidoc
  filebeat/include/fields.go
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  journalbeat/docs/fields.asciidoc
  journalbeat/include/fields.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/processors/add_kubernetes_metadata/_meta/fields.yml
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/state_container/_meta/data.json
  metricbeat/module/kubernetes/state_container/_meta/test/ksm.v1.3.0.expected
  metricbeat/module/kubernetes/state_container/_meta/test/ksm.v1.8.0.expected
  metricbeat/module/kubernetes/state_container/_meta/testdata/ksm-v1_3_0.plain-expected.json
  metricbeat/module/kubernetes/state_container/state_container.go
  packetbeat/docs/fields.asciidoc
  packetbeat/include/fields.go
  winlogbeat/docs/fields.asciidoc
  winlogbeat/include/fields.go
  x-pack/functionbeat/docs/fields.asciidoc
  x-pack/functionbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
Labels: Team:Integrations, containers, kubernetes, test-plan, v7.13.0

#24469 Add helper functions for filestream integration tests
  filebeat/input/filestream/environment_test.go
Labels: Team:Agent

#24181 Cherry-pick #24156 to 7.x: Empty configuration options generate `<no value>` string for azure-eventhub input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/azureeventhub/config.go
  x-pack/filebeat/module/azure/activitylogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/auditlogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/platformlogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/signinlogs/config/azure-eventhub.yml
Labels: Team:Integrations, [zube]: In Review, backport

#24440 Cherry-pick #24275 to 7.12: [Filebeat] Fix pensando viz
  filebeat/docs/modules/pensando.asciidoc
  filebeat/module/pensando/_meta/docs.asciidoc
  filebeat/module/pensando/_meta/kibana/7/dashboard/pensando-dfw-overview.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#24340 chore: Update version to 7.11.3
  libbeat/version/version.go
Labels: Team:Automation, automation, release

#24463 [Winlogbeat] remove eventlogger
  CHANGELOG.next.asciidoc
  winlogbeat/_meta/fields.common.yml
  winlogbeat/docs/fields.asciidoc
  winlogbeat/eventlog/bench_test.go
  winlogbeat/eventlog/eventlogging.go
  winlogbeat/eventlog/eventlogging_test.go
  winlogbeat/eventlog/retry.go
  winlogbeat/eventlog/wineventlog.go
  winlogbeat/eventlog/wineventlog_experimental.go
  winlogbeat/eventlog/wineventlog_test.go
  winlogbeat/include/fields.go
  winlogbeat/sys/eventlogging/doc.go
  winlogbeat/sys/eventlogging/eventlogging_windows.go
  winlogbeat/sys/eventlogging/stringinserts_windows.go
  winlogbeat/sys/eventlogging/syscall_windows.go
  winlogbeat/sys/eventlogging/syscall_windows_test.go
  winlogbeat/sys/eventlogging/zsyscall_windows.go
  winlogbeat/tests/system/test_eventlogging.py
Labels: Team:Security-External Integrations, Winlogbeat, enhancement, v7.13.0

#24466 [Ingest Manager] Logging to file disabled on enroll
  libbeat/logp/config.go
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
  x-pack/elastic-agent/pkg/core/logger/logger.go
Labels: Team:Agent, Team:Ingest Management, backport, bug, v7.12.0

#24471 Cherry-pick #24380 to 7.x: Use alias to report container image in k8s parts
  CHANGELOG.next.asciidoc
  auditbeat/docs/fields.asciidoc
  auditbeat/include/fields.go
  filebeat/docs/fields.asciidoc
  filebeat/include/fields.go
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  journalbeat/docs/fields.asciidoc
  journalbeat/include/fields.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/processors/add_kubernetes_metadata/_meta/fields.yml
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/state_container/_meta/data.json
  metricbeat/module/kubernetes/state_container/_meta/test/ksm.v1.3.0.expected
  metricbeat/module/kubernetes/state_container/_meta/test/ksm.v1.8.0.expected
  metricbeat/module/kubernetes/state_container/_meta/testdata/ksm-v1_3_0.plain-expected.json
  metricbeat/module/kubernetes/state_container/state_container.go
  packetbeat/docs/fields.asciidoc
  packetbeat/include/fields.go
  winlogbeat/docs/fields.asciidoc
  winlogbeat/include/fields.go
  x-pack/functionbeat/docs/fields.asciidoc
  x-pack/functionbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
Labels: Team:Integrations, [zube]: In Review, backport

#24338 docs: update docs versions 7.11.2
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: Team:Automation, automation, docs, in progress, release

#24107 Add unit tests for harvester.go of input-logfile package
  filebeat/input/filestream/internal/input-logfile/harvester.go
  filebeat/input/filestream/internal/input-logfile/harvester_test.go
  libbeat/tests/resources/goroutines.go
Labels: Team:Agent, needs_backport

#24433 Cherry-pick to 7.11: Update input-common-file-options.asciidoc (#24330)
  filebeat/docs/inputs/input-common-file-options.asciidoc
Labels: backport, docs, needs_team

#24431 Cherry-pick to 7.x: Update input-common-file-options.asciidoc (#24330)
  filebeat/docs/inputs/input-common-file-options.asciidoc
Labels: backport, docs, needs_team

#24342 [DOCS] Restructure content for SSL settings
  libbeat/docs/shared-ssl-config.asciidoc
Labels: Team:Integrations, docs, v7.11.0, v7.12.0

#24473 Cherry-pick #24466 to 7.x: Logging to file disabled on enroll
  libbeat/logp/config.go
  x-pack/elastic-agent/CHANGELOG.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
  x-pack/elastic-agent/pkg/core/logger/logger.go
Labels: Team:Agent, Team:Ingest Management, backport, bug, v7.12.0

#24250 Port four Harvester tests of log input to filestream in Golang
  filebeat/input/filestream/input_integration_test.go
  libbeat/reader/readfile/line_test.go
Labels: Team:Agent

#24207 Add syntax for multiple selector logging
  libbeat/docs/loggingconfig.asciidoc
Labels: Team:Docs, v7.11.0, v7.12.0

#24465 Cherry-pick #24339 to 7.x: x-pack/metricbeat: Disable Windows 7 32 bit builder
  x-pack/metricbeat/Jenkinsfile.yml
Labels: Team:Automation, Team:Integrations, [zube]: In Review, backport

#24445 Cherry-pick #24436 to 7.x: Add support for X-Forwarded-For in IIS logs
  CHANGELOG.next.asciidoc
  filebeat/module/iis/access/ingest/pipeline.yml
  filebeat/module/iis/access/test/test-x-forward-for-extended.log
  filebeat/module/iis/access/test/test-x-forward-for-extended.log-expected.json
  filebeat/module/iis/access/test/test-x-forward-for.log
  filebeat/module/iis/access/test/test-x-forward-for.log-expected.json
Labels: Team:Integrations, [zube]: In Review, backport

#24504 [Ingest Manager] Sync on rename on windows
  x-pack/elastic-agent/pkg/artifact/install/atomic/atomic_installer.go
  x-pack/elastic-agent/pkg/artifact/install/zip/zip_installer.go
Labels: Team:Agent, Team:Ingest Management, bug, v7.12.0

#24426 Add tests for encoding setting of filestream input
  filebeat/input/filestream/config.go
  filebeat/input/filestream/input.go
  filebeat/input/filestream/input_integration_test.go
Labels: Team:Agent, needs_backport

#24486 [Elastic Agent] Add the ability to provide custom CA's inside of docker.
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/config.go
  x-pack/elastic-agent/pkg/agent/application/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/cmd/container.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
Labels: Team:Agent, Team:Ingest Management

#24442 Update Golang to 1.15.9
  .go-version
  CHANGELOG-developer.next.asciidoc
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: Team:Agent, needs_backport

#24492 Cherry-pick to 7.x: [DOCS] Restructure content for SSL settings (#24342)
  libbeat/docs/shared-ssl-config.asciidoc
Labels: Team:Docs, backport

#24493 Cherry-pick to 7.12: [DOCS] Restructure content for SSL settings (#24342)
  libbeat/docs/shared-ssl-config.asciidoc
Labels: Team:Docs, backport

#24494 Cherry-pick to 7.11: [DOCS] Restructure content for SSL settings (#24342)
  libbeat/docs/shared-ssl-config.asciidoc
Labels: Team:Docs, backport

#24497 Cherry-pick to master: Add syntax for multiple selector logging (#24207)
  libbeat/docs/loggingconfig.asciidoc
Labels: Team:Docs, backport

#24498 Cherry-pick to 7.x: Add syntax for multiple selector logging (#24207)
  libbeat/docs/loggingconfig.asciidoc
Labels: Team:Docs, backport

#24499 Cherry-pick to 7.12: Add syntax for multiple selector logging (#24207)
  libbeat/docs/loggingconfig.asciidoc
Labels: Team:Docs, backport

#24446 chore(ci): use beat_version instead of PR version
  .ci/packaging.groovy
Labels: Team:Automation

#24395 Cherry-pick #24129 to 7.x: [ILM][Docs] Clarify how to change setup.ilm.pattern
  libbeat/docs/shared-ilm.asciidoc
Labels: Team:Agent, [zube]: In Review, backport, docs, review

#24423 Add test for close.reader.after_interval of filestream input
  filebeat/input/filestream/input_integration_test.go
Labels: Team:Agent

#24334 Refactor use of system.hostfs to fix cgroup metrics
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
  libbeat/cmd/instance/metrics/metrics.go
  libbeat/cmd/root.go
  libbeat/docs/command-reference.asciidoc
  libbeat/docs/shared-path-config.asciidoc
  libbeat/paths/paths.go
  metricbeat/module/system/diskio/diskio_test.go
  metricbeat/module/system/entropy/entropy.go
  metricbeat/module/system/entropy/entropy_test.go
  metricbeat/module/system/filesystem/helper.go
  metricbeat/module/system/process/process.go
  metricbeat/module/system/raid/raid.go
  metricbeat/module/system/socket/socket.go
  metricbeat/module/system/socket_summary/socket_summary.go
  metricbeat/module/system/socket_summary/sockstat_linux.go
  metricbeat/module/system/socket_summary/sockstat_other.go
  metricbeat/module/system/system.go
  metricbeat/module/system/system_linux.go
  metricbeat/module/system/system_other.go
  metricbeat/module/system/system_windows.go
Labels: Team:Integrations, bug, v7.11.2

#24489 [Elastic Agent] Add verification check when updating communication to Kibana.
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_policy_change.go
Labels: Team:Agent, Team:Ingest Management, needs_backport

#24483 Cherry-pick to 7.11: Move example to the correct location in reference docs (#24455)
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
Labels: backport, docs, needs_team

#24481 Cherry-pick to 7.x: Move example to the correct location in reference docs (#24455)
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
Labels: backport, docs, needs_team

#24299 Cherry-pick to 7.12: Alphabetize AWS S3 input in list (#24257)
  filebeat/docs/filebeat-options.asciidoc
Labels: backport, docs, needs_team

#24432 Cherry-pick to 7.12: Update input-common-file-options.asciidoc (#24330)
  filebeat/docs/inputs/input-common-file-options.asciidoc
Labels: backport, docs, needs_team

#24509 Fix typo incorrect callout in mqtt input docs
  filebeat/docs/inputs/input-mqtt.asciidoc
Labels: Filebeat, docs, needs_team

#24490 Fix typo in input-http-endpoint.asciidoc
  x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
Labels: Team:Docs, docs, review

#24510 Cherry-pick to 7.x: chore(ci): use beat_version instead of PR version (#24446)
  .ci/packaging.groovy
Labels: Team:Automation, backport

#24511 Cherry-pick to 7.12: chore(ci): use beat_version instead of PR version (#24446)
  .ci/packaging.groovy
Labels: Team:Automation, backport

#24512 Cherry-pick to 7.11: chore(ci): use beat_version instead of PR version (#24446)
  .ci/packaging.groovy
Labels: Team:Automation, backport

#24416 Cherry-pick #24414 to 7.x: [fix][auditbeat] Reset file offset when re-reading from the beginning
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/login/login_test.go
  x-pack/auditbeat/module/system/login/utmp.go
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#24417 Cherry-pick #24414 to 7.11: [fix][auditbeat] Reset file offset when re-reading from the beginning
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/login/login_test.go
  x-pack/auditbeat/module/system/login/utmp.go
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#24501 Cherry-pick #24463 to 7.12: [Winlogbeat] remove eventlogger
  CHANGELOG.next.asciidoc
  winlogbeat/_meta/fields.common.yml
  winlogbeat/docs/fields.asciidoc
  winlogbeat/eventlog/bench_test.go
  winlogbeat/eventlog/eventlogging.go
  winlogbeat/eventlog/eventlogging_test.go
  winlogbeat/eventlog/retry.go
  winlogbeat/eventlog/wineventlog.go
  winlogbeat/eventlog/wineventlog_experimental.go
  winlogbeat/eventlog/wineventlog_test.go
  winlogbeat/include/fields.go
  winlogbeat/sys/eventlogging/doc.go
  winlogbeat/sys/eventlogging/eventlogging_windows.go
  winlogbeat/sys/eventlogging/stringinserts_windows.go
  winlogbeat/sys/eventlogging/syscall_windows.go
  winlogbeat/sys/eventlogging/syscall_windows_test.go
  winlogbeat/sys/eventlogging/zsyscall_windows.go
  winlogbeat/tests/system/test_eventlogging.py
Labels: Team:Security-External Integrations, [zube]: In Review, backport
