Repository elastic/beats, pull requests merged in 2021-08, with the labels that each got.

#27181 [automation] update elastic stack version for testing 7.14.0-8d3ee29d
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#27153 Increase Agent's mem limits in k8s
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
Labels: Team:Integrations, backport-v7.15.0

#27183 Add missing headers
  x-pack/osquerybeat/internal/ecs/mapping.go
  x-pack/osquerybeat/internal/ecs/mapping_test.go
Labels: Team:Agent, backport-v7.13.0, backport-v7.14.0, bug

#26642 [fix][metricbeat] Change default value for server_status_path in nginx module
  CHANGELOG.next.asciidoc
  metricbeat/module/nginx/_meta/Dockerfile
  metricbeat/module/nginx/_meta/config.yml
  metricbeat/module/nginx/_meta/nginx.conf
  metricbeat/module/nginx/stubstatus/stubstatus.go
  metricbeat/modules.d/nginx.yml.disabled
Labels: Metricbeat, Team:Security-External Integrations, backport-v7.14.0, backport-v7.15.0, bug

#27109 [Filebeat] decode_cef - allow MACs without separators
  CHANGELOG.next.asciidoc
  x-pack/filebeat/processors/decode_cef/cef/types.go
  x-pack/filebeat/processors/decode_cef/cef/types_test.go
Labels: :Processors, Filebeat, Team:Security-External Integrations, backport-v7.15.0, enhancement

#27150 docs: Prepare Changelog for 7.14.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Automation, automation, docs, in progress, release

#26622 chore: update docs to next minor 7.15.0
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: Team:Automation, automation, docs, in progress, release

#26952 Adding functionality to death letter index instead of dropping events.
  CHANGELOG.next.asciidoc
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/elasticsearch/config.go
  libbeat/outputs/elasticsearch/config_test.go
  libbeat/outputs/elasticsearch/death_letter_selector.go
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
  libbeat/outputs/elasticsearch/elasticsearch.go
  libbeat/outputs/elasticsearch/elasticsearch_test.go
  libbeat/outputs/elasticsearch/non_indexable_policy.go
Labels: Team:Agent, backport-v7.15.0, enhancement

#27142 Cherry-pick to 7.x: docs: fix example (#27117)
  libbeat/docs/http-endpoint.asciidoc
Labels: backport, needs_team

#27086 Osquerybeat: Update ECS mapping implementation based on the latest developers feedback
  x-pack/osquerybeat/beater/config_plugin.go
  x-pack/osquerybeat/beater/config_plugin_test.go
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/internal/config/config.go
  x-pack/osquerybeat/internal/ecs/mapping.go
  x-pack/osquerybeat/internal/ecs/mapping_test.go
Labels: Team:Asset Mgt, backport-v7.15.0

#27198 Forward port 7.14.0 changelog to 7.x
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, docs, release

#27110 docs: update docs versions 6.8.18
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: Team:Automation, automation, docs, in progress, release

#27111 chore: Update version to 6.8.19
  libbeat/version/version.go
Labels: Team:Automation, automation, release

#26618 chore: Update version to 7.14.1
  libbeat/version/version.go
Labels: Team:Automation, automation, release

#27192 [Elastic Agent] Do not watch monitors
  x-pack/elastic-agent/pkg/agent/operation/operator.go
Labels: Team:Agent, backport-v7.14.0, bug

#27207 Forward port 7.14.0 changelog to master
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, docs

#27209 [7.x](backport #27192) [Elastic Agent] Do not watch monitors
  x-pack/elastic-agent/pkg/agent/operation/operator.go
Labels: Team:Agent, backport, bug

#27139 Improve RDS overview dashboard
  metricbeat/docs/images/metricbeat-aws-rds-overview.png
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-rds-overview.json
Labels: Team:Integrations, backport-v7.15.0, needs_integration_sync

#27210 Ignore context cancelled in operator
  x-pack/elastic-agent/pkg/agent/operation/operator.go
Labels: Team:Agent, backport-v7.15.0, bug

#27224 [automation] update elastic stack version for testing 8.0.0-0c340354
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#27225 [automation] update elastic stack version for testing 7.14.0-1738ccc6
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26982 [Metricbeat] gcp: log metrics without descriptors
  x-pack/metricbeat/module/gcp/metrics/metricset.go
Labels: Team:Integrations, backport-v7.15.0, enhancement

#27168 [Filebeat] Add HMAC template function for httpjson input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/internal/v2/value_tpl.go
  x-pack/filebeat/input/httpjson/internal/v2/value_tpl_test.go
Labels: Team:Security-External Integrations, backport-v7.15.0

#27123 [automation] update elastic stack version for testing 7.15.0-2cefb6a4
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26885 Add missing outputs to apm server spec file
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/apm-server.yml
Labels: Team:Agent, backport-v7.14.0, backport-v7.15.0

#27248 Fix cloudwatch metricset collecting duplicate data points
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0, bug

#26886 Perfmon metricset improvements
  CHANGELOG.next.asciidoc
  metricbeat/helper/windows/pdh/pdh_query_windows.go
  metricbeat/helper/windows/pdh/pdh_windows.go
  metricbeat/helper/windows/pdh/zpdh_windows.go
  metricbeat/module/windows/perfmon/_meta/docs.asciidoc
  metricbeat/module/windows/perfmon/config.go
  metricbeat/module/windows/perfmon/data.go
  metricbeat/module/windows/perfmon/data_test.go
  metricbeat/module/windows/perfmon/perfmon.go
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/reader_test.go
Labels: Team:Platforms

#27215 Fix serialization/deserialization of proxy URI
  libbeat/common/transport/httpcommon/httpcommon.go
  libbeat/common/transport/httpcommon/proxy.go
  libbeat/common/transport/httpcommon/proxy_headers.go
  libbeat/common/transport/httpcommon/proxy_headers_test.go
  libbeat/common/transport/httpcommon/proxy_uri.go
  libbeat/common/transport/httpcommon/proxy_uri_test.go
  libbeat/esleg/eslegclient/connection.go
  libbeat/esleg/eslegclient/connection_integration_test.go
  libbeat/outputs/elasticsearch/client_proxy_test.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
Labels: Team:Agent, backport-v7.14.0, backport-v7.15.0, bug

#27243 update the path listed in the source generated by buildspec
  x-pack/elastic-agent/dev-tools/cmd/buildspec/buildspec.go
  x-pack/elastic-agent/pkg/agent/program/supported.go
Labels: bug, Team:Agent

#27261 Osquerybeat: Add event.module into the result data
  x-pack/osquerybeat/beater/osquerybeat.go
Labels: enhancement, Team:Asset Mgt, backport-v7.15.0, backport-v7.16.0

#27260 Osquerybeat: Upgrade osquery to 4.9.0
  x-pack/osquerybeat/internal/distro/distro.go
  x-pack/osquerybeat/internal/tar/tar.go
Labels: enhancement, Team:Asset Mgt, backport-v7.15.0, backport-v7.16.0

#27166 Remove watch poll feature
  CHANGELOG.next.asciidoc
  heartbeat/_meta/config/beat.reference.yml.tmpl
  heartbeat/beater/heartbeat.go
  heartbeat/heartbeat.reference.yml
  heartbeat/monitors/factory.go
  heartbeat/monitors/monitor.go
  heartbeat/monitors/monitor_test.go
  x-pack/heartbeat/heartbeat.reference.yml
Labels: enhancement, Team:Uptime, breaking change, v8.0.0

#27268 [automation] update elastic stack version for testing 7.14.1-22366df8
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27275 [automation] update elastic stack version for testing 7.14.1-8dd23e93
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27233 Osquerybeat: Add support for input/integration level osquery platform/version/discovery configuration
  x-pack/osquerybeat/beater/config_plugin.go
  x-pack/osquerybeat/beater/config_plugin_test.go
  x-pack/osquerybeat/internal/config/config.go
Labels: enhancement, Team:Asset Mgt, backport-v7.15.0, backport-v7.16.0

#27290 [automation] update elastic stack version for testing 7.14.1-899a999b
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27254 Cherry-pick #26886 to 7.x: Perfmon metricset improvements
  CHANGELOG.next.asciidoc
  metricbeat/helper/windows/pdh/pdh_query_windows.go
  metricbeat/helper/windows/pdh/pdh_windows.go
  metricbeat/helper/windows/pdh/zpdh_windows.go
  metricbeat/module/windows/perfmon/_meta/docs.asciidoc
  metricbeat/module/windows/perfmon/config.go
  metricbeat/module/windows/perfmon/data.go
  metricbeat/module/windows/perfmon/data_test.go
  metricbeat/module/windows/perfmon/perfmon.go
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/reader_test.go
Labels: backport, [zube]: In Review, Team:Platforms

#26983 [Metricbeat] gcp: add README
  x-pack/metricbeat/module/gcp/DEVELOPMENT.md
Labels: enhancement, Team:Integrations

#27141 [Filebeat] Update Threatinteal Anomali pipeline
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/threatintel/anomali/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/anomali/test/anomali_limo.ndjson.log-expected.json
Labels: Team:Security-External Integrations

#27294 Pass correct config to standalone
  x-pack/elastic-agent/pkg/agent/application/application.go
Labels: bug, Team:Agent, backport-v7.15.0

#27239 Add redirect pages for removed central management docs
  filebeat/docs/index.asciidoc
  libbeat/docs/redirects.asciidoc
  metricbeat/docs/index.asciidoc
Labels: docs, needs_team, v7.14.0, v7.15.0

#27303 [Uptime] Document `params` browser option, fix docs hierarchy.
  heartbeat/docs/monitors/monitor-browser.asciidoc
Labels: docs, Heartbeat, Team:Uptime, v7.15.0

#27301 Cherry-pick to 7.x: Add redirect pages for removed central management docs (#27239)
  filebeat/docs/index.asciidoc
  libbeat/docs/redirects.asciidoc
  metricbeat/docs/index.asciidoc
Labels: backport, needs_team

#27302 Cherry-pick to 7.14: Add redirect pages for removed central management docs (#27239)
  filebeat/docs/index.asciidoc
  libbeat/docs/redirects.asciidoc
  metricbeat/docs/index.asciidoc
Labels: backport, needs_team

#27160 [Heartbeat]: limit parallelization of tasks by jobtype
  heartbeat/beater/heartbeat.go
  heartbeat/config/config.go
  heartbeat/monitors/task.go
  heartbeat/scheduler/scheduler.go
  heartbeat/scheduler/scheduler_test.go
Labels: Heartbeat, Team:Uptime, v7.15.0, backport-v7.15.0

#27308 [automation] update elastic stack version for testing 7.14.1-a5e22cba
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27313 Fix flaky test `TestAddCounterInvalidArgWhenQueryClosed`
  CHANGELOG.next.asciidoc
  metricbeat/helper/windows/pdh/pdh_query_windows.go
Labels: needs_team

#27317 Add filestream to the list of inputs in the "Configure inputs" section of the docs
  filebeat/docs/filebeat-options.asciidoc
Labels: Team:Agent

#27314 Osquerybeat: Add osquery client reconnect on broken pipe error
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/internal/osqdcli/client.go
Labels: bug, Team:Asset Mgt

#27315 Osquerybeat: Add osquery client reconnect on broken pipe error
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/internal/osqdcli/client.go
Labels: bug, Team:Asset Mgt, backport-v7.15.0, backport-v7.16.0

#27052 [Heartbeat] Build elastic agent with synthetics support / offline mode
  CHANGELOG.next.asciidoc
  dev-tools/mage/dockerbuilder.go
  dev-tools/mage/pkgtypes.go
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  x-pack/elastic-agent/README.md
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/osquerybeat/beater/config_plugin_test.go
Labels: enhancement, Heartbeat, Team:Uptime, v7.15.0

#27297 Do not cancel context before reading body
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd.go
  x-pack/elastic-agent/pkg/remote/client.go
Labels: bug, Team:Agent, backport-v7.14.0, backport-v7.15.0

#27316 Cherry-pick #27313 to 7.x: Fix flaky test `TestAddCounterInvalidArgWhenQueryClosed`
  CHANGELOG.next.asciidoc
  metricbeat/helper/windows/pdh/pdh_query_windows.go
Labels: review, backport, Team:Integrations

#26828 Add definition for logging.metrics.enabled, pass config from agent to beats
  libbeat/logp/config.go
  libbeat/tests/system/config/mockbeat.yml.j2
  libbeat/tests/system/test_cmd_export_config.py
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/_meta/config/common.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/common.reference.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/elastic-agent.docker.yml.tmpl
  x-pack/elastic-agent/_meta/elastic-agent.yml
  x-pack/elastic-agent/elastic-agent.docker.yml
  x-pack/elastic-agent/elastic-agent.reference.yml
  x-pack/elastic-agent/elastic-agent.yml
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
  x-pack/elastic-agent/pkg/core/monitoring/config/config.go
  x-pack/elastic-agent/pkg/core/monitoring/monitor.go
Labels: enhancement, Team:Agent, v7.15.0, backport-v7.15.0

#27345 [Synthetics] Upgrade node to latest LTS
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Heartbeat, Team:Uptime

#26619 chore: Update test environments 7.14.1
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, automation, Team:Automation

#27286 [Metricbeat] gcp: use ServiceMetrixPrefix in field extractor too
  x-pack/metricbeat/module/gcp/metrics/metricset.go
  x-pack/metricbeat/module/gcp/metrics/metricset_test.go
  x-pack/metricbeat/module/gcp/metrics/response_parser.go
  x-pack/metricbeat/module/gcp/metrics/response_parser_test.go
Labels: bug, Team:Integrations, backport-v7.14.0, backport-v7.15.0

#27352 [automation] update elastic stack version for testing 7.15.0-ba42231a
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27353 [automation] update elastic stack version for testing 7.14.1-3af02427
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27358 [Filebeat] Fixes for Snyk API changes
  CHANGELOG.next.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/snyk/_meta/config.yml
  x-pack/filebeat/module/snyk/audit/config/config.yml
  x-pack/filebeat/module/snyk/vulnerabilities/config/config.yml
  x-pack/filebeat/module/snyk/vulnerabilities/manifest.yml
  x-pack/filebeat/modules.d/snyk.yml.disabled
Labels: Team:Security-External Integrations, backport-v7.14.0, 7.15 Candidate, backport-v7.15.0

#27362 Fix application.Stop on windows
  x-pack/elastic-agent/pkg/core/plugin/process/app.go
Labels: bug, Team:Agent, backport-v7.14.0, backport-v7.15.0

#25727 Report dataset metrics in monitoring log reporter
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/general.reference.yml.tmpl
  libbeat/_meta/config/logging.reference.yml.tmpl
  libbeat/docs/loggingconfig.asciidoc
  libbeat/monitoring/report/log/config.go
  libbeat/monitoring/report/log/log.go
  libbeat/monitoring/report/log/log_test.go
  libbeat/processors/dns/resolver.go
  libbeat/tests/system/test_base.py
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: review, libbeat, Team:Security-External Integrations, Team:Agent, backport-v7.15.0

#27344 Add changelog for cgroupsV2
  CHANGELOG.next.asciidoc
Labels: Team:Integrations, v7.15.0

#27336 [Agent] Fix os.ErrNotExist handling for Agent upgrade marker
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_mark.go
Labels: bug, review, Agent, Team:Agent, backport-v7.14.0, backport-v7.15.0

#27328 Fix formatting of Filebeat name
  libbeat/docs/shared-kerberos-config.asciidoc
Labels: docs, Filebeat, cleanup, needs_team

#27236 Add versioned troubleshooting message on non-zero exits.
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/common.go
  x-pack/elastic-agent/pkg/agent/cmd/container.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
  x-pack/elastic-agent/pkg/agent/cmd/inspect.go
  x-pack/elastic-agent/pkg/agent/cmd/install.go
  x-pack/elastic-agent/pkg/agent/cmd/reexec_windows.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/cmd/status.go
  x-pack/elastic-agent/pkg/agent/cmd/uninstall.go
  x-pack/elastic-agent/pkg/agent/cmd/upgrade.go
  x-pack/elastic-agent/pkg/agent/cmd/watch.go
Labels: enhancement, Team:Agent, v7.15.0, backport-v7.15.0

#27379 Cherry-pick to 7.12: Fix formatting of Filebeat name (#27328)
  libbeat/docs/shared-kerberos-config.asciidoc
Labels: docs, backport, needs_team

#27378 Cherry-pick to 7.13: Fix formatting of Filebeat name (#27328)
  libbeat/docs/shared-kerberos-config.asciidoc
Labels: docs, backport, needs_team

#27377 Cherry-pick to 7.14: Fix formatting of Filebeat name (#27328)
  libbeat/docs/shared-kerberos-config.asciidoc
Labels: docs, backport, needs_team

#27376 Cherry-pick to 7.x: Fix formatting of Filebeat name (#27328)
  libbeat/docs/shared-kerberos-config.asciidoc
Labels: docs, backport, needs_team

#27350 [elastic-agent] Rename 'offline' image to 'complete'
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Labels: enhancement, Team:Uptime, Agent, v7.15.0

#27391 [automation] update elastic stack version for testing 7.14.1-c6219279
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27392 Fix go mod in apm beats update CI job
  .ci/apm-beats-update.groovy
Labels: Team:Automation, backport-v7.14.0, backport-v7.15.0, backport-v7.16.0, apm-server

#24263 Disable aws module integration tests
  x-pack/metricbeat/module/aws/billing/billing_integration_test.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_integration_test.go
  x-pack/metricbeat/module/aws/ec2/ec2_integration_test.go
  x-pack/metricbeat/module/aws/kinesis/kinesis_integration_test.go
  x-pack/metricbeat/module/aws/rds/rds_integration_test.go
  x-pack/metricbeat/module/aws/s3_daily_storage/s3_daily_storage_integration_test.go
  x-pack/metricbeat/module/aws/s3_request/s3_request_integration_test.go
  x-pack/metricbeat/module/aws/sqs/sqs_integration_test.go
Labels: review, Team:Integrations, aws

#27400 Revert project assigner changes
  .github/workflows/project-assigner.yml
Labels: bug, needs_team

#27327 Change to use one period between start and end time
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0

#27381 Fix doc build issues happening in linux/memory
  CHANGELOG.next.asciidoc
  metricbeat/internal/metrics/memory/memory_helpers.go
  metricbeat/internal/metrics/memory/memory_linux.go
  metricbeat/module/linux/memory/data.go
  metricbeat/module/linux/memory/memory.go
  metricbeat/module/linux/memory/memory_linux_test.go
Labels: bug, Team:Integrations

#27399 [elastic-agent] Use -complete in docker image name, not tag
  dev-tools/mage/dockerbuilder.go
Labels: bug, Heartbeat, Team:Uptime, v7.15.0

#27374 Add formatting to pressure fields in system/process
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/fields.go
  metricbeat/module/system/process/_meta/fields.yml
Labels: Team:Integrations, v7.15.0

#27347 Heartbeat: add support for filtering journeys
  heartbeat/_meta/fields.common.yml
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
  x-pack/heartbeat/monitors/browser/config.go
  x-pack/heartbeat/monitors/browser/suite.go
  x-pack/heartbeat/monitors/browser/suite_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
  x-pack/heartbeat/monitors/browser/synthexec/synthtypes_test.go
Labels: Heartbeat, Team:Uptime, v7.15.0, backport-v7.15.0

#27348 Heartbeat: add browser monitor docs
  heartbeat/docs/heartbeat-options.asciidoc
  heartbeat/docs/heartbeat-scheduler.asciidoc
  heartbeat/docs/monitors/monitor-browser.asciidoc
Labels: docs, Team:Uptime, v7.15.0, backport-v7.15.0

#27401 [elastic-agent] Use -complete in docker image name, not tag
  dev-tools/mage/dockerbuilder.go
Labels: backport, Team:Uptime, v7.15.0

#27407 Remove unnecessary changelog entries from 7.x
  CHANGELOG.next.asciidoc
Labels: Team:Agent

#27332 [Filebeat] Add option for S3 input to work without SQS notification
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/aws.asciidoc
  libbeat/publisher/testing/testing.go
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/_meta/terraform/README.md
  x-pack/filebeat/input/awss3/acker.go
  x-pack/filebeat/input/awss3/acker_test.go
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/config_test.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_benchmark_test.go
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/interfaces.go
  x-pack/filebeat/input/awss3/metrics.go
  x-pack/filebeat/input/awss3/mock_interfaces_test.go
  x-pack/filebeat/input/awss3/s3.go
  x-pack/filebeat/input/awss3/s3_objects.go
  x-pack/filebeat/input/awss3/s3_objects_test.go
  x-pack/filebeat/input/awss3/s3_test.go
  x-pack/filebeat/input/awss3/state.go
  x-pack/filebeat/input/awss3/state_test.go
  x-pack/filebeat/input/awss3/states.go
  x-pack/filebeat/input/awss3/states_test.go
  x-pack/filebeat/input/default-inputs/inputs.go
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/cloudtrail/config/aws-s3.yml
  x-pack/filebeat/module/aws/cloudtrail/manifest.yml
  x-pack/filebeat/module/aws/cloudwatch/config/aws-s3.yml
  x-pack/filebeat/module/aws/cloudwatch/manifest.yml
  x-pack/filebeat/module/aws/ec2/config/aws-s3.yml
  x-pack/filebeat/module/aws/ec2/manifest.yml
  x-pack/filebeat/module/aws/elb/config/aws-s3.yml
  x-pack/filebeat/module/aws/elb/manifest.yml
  x-pack/filebeat/module/aws/s3access/config/aws-s3.yml
  x-pack/filebeat/module/aws/s3access/manifest.yml
  x-pack/filebeat/module/aws/vpcflow/config/input.yml
  x-pack/filebeat/module/aws/vpcflow/manifest.yml
  x-pack/libbeat/common/aws/credentials.go
Labels: enhancement, review, Filebeat, Team:Integrations, Team:Security-External Integrations, backport-v7.15.0

#27363 [Metricbeat] gcp: fix instance machineType reporting
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/gcp/metrics/compute/metadata.go
Labels: bug, Team:Integrations, backport-v7.14.0, backport-v7.15.0

#27412 Ignore https errors
  heartbeat/docs/monitors/monitor-browser.asciidoc
  x-pack/heartbeat/monitors/browser/config.go
  x-pack/heartbeat/monitors/browser/suite.go
  x-pack/heartbeat/monitors/browser/suite_test.go
Labels: enhancement, Heartbeat, Team:Uptime, v7.15.0

#27222 Disable monitoring during fleetserver bootstrap process
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/fleet_server_bootstrap.go
Labels: Team:Agent

#27416 [Metricbeat] CI: update stack to 7.14
  metricbeat/docker-compose.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Integrations

#27396 [Elastic Agent] Adjust installation path in container
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/paths/common.go
  x-pack/elastic-agent/pkg/agent/cmd/common.go
  x-pack/elastic-agent/pkg/agent/cmd/container.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
  x-pack/elastic-agent/pkg/artifact/config.go
  x-pack/elastic-agent/pkg/artifact/download/fs/downloader.go
  x-pack/elastic-agent/pkg/artifact/install/atomic/atomic_installer.go
Labels: Team:Agent, backport-v7.15.0

#27426 Disable monitoring during fleetserver bootstrap process (backport #27222)
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/fleet_server_bootstrap.go
Labels: backport, needs_team

#27430 Cherry-pick #27374 to 7.x: Add formatting to pressure fields in system/process
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/fields.go
  metricbeat/module/system/process/_meta/fields.yml
Labels: backport, [zube]: In Review, Team:Integrations

#27429 Inject inferred queue settings into agent config generation
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/pkg/agent/program/testdata/enabled_output_true-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/enabled_true-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/namespace-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/namespace-heartbeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/namespace-metricbeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/namespace-packetbeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-endpoint-security.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-heartbeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-metricbeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-packetbeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/synthetics_config-heartbeat.yml
  x-pack/elastic-agent/pkg/agent/transpiler/rules.go
  x-pack/elastic-agent/pkg/agent/transpiler/rules_test.go
  x-pack/elastic-agent/spec/apm-server.yml
  x-pack/elastic-agent/spec/filebeat.yml
  x-pack/elastic-agent/spec/heartbeat.yml
  x-pack/elastic-agent/spec/metricbeat.yml
  x-pack/elastic-agent/spec/osquerybeat.yml
  x-pack/elastic-agent/spec/packetbeat.yml
Labels: enhancement, Team:Agent, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0

#27433 Remove event.dataset from logp ecs attributes
  CHANGELOG-developer.next.asciidoc
  libbeat/logp/core.go
  libbeat/logp/core_test.go
Labels: bug, Team:Agent, v7.15.0, backport-v7.15.0

#27428 Move AWS Filebeat module to GA
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/_meta/fields.yml
  x-pack/filebeat/module/aws/cloudtrail/_meta/fields.yml
  x-pack/filebeat/module/aws/cloudwatch/_meta/fields.yml
  x-pack/filebeat/module/aws/ec2/_meta/fields.yml
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/module/aws/vpcflow/_meta/fields.yml
Labels: Team:Integrations, backport-v7.15.0

#26515 Docs - Fix small typo "promtheus" -> "prometheus"
  metricbeat/module/prometheus/query/_meta/docs.asciidoc
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0

#27445 [automation] update elastic stack version for testing 7.14.1-904a8260
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27446 [automation] update elastic stack version for testing 7.15.0-4b8a78a4
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27422 [DOCS] Remove PKI mentions
  libbeat/docs/shared-kibana-config.asciidoc
  libbeat/docs/shared-ssl-config.asciidoc
Labels: release-note:skip, Team:Docs, v7.14.0

#27454 Add vars in modules.d/aws.yml.disabled
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/input/awss3/acker.go
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/config_test.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_benchmark_test.go
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/s3.go
  x-pack/filebeat/input/awss3/s3_objects.go
  x-pack/filebeat/input/awss3/s3_test.go
  x-pack/filebeat/module/aws/_meta/config.yml
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/cloudtrail/config/aws-s3.yml
  x-pack/filebeat/module/aws/cloudtrail/manifest.yml
  x-pack/filebeat/module/aws/cloudwatch/config/aws-s3.yml
  x-pack/filebeat/module/aws/cloudwatch/manifest.yml
  x-pack/filebeat/module/aws/ec2/config/aws-s3.yml
  x-pack/filebeat/module/aws/ec2/manifest.yml
  x-pack/filebeat/module/aws/elb/config/aws-s3.yml
  x-pack/filebeat/module/aws/elb/manifest.yml
  x-pack/filebeat/module/aws/s3access/config/aws-s3.yml
  x-pack/filebeat/module/aws/s3access/manifest.yml
  x-pack/filebeat/module/aws/vpcflow/config/input.yml
  x-pack/filebeat/module/aws/vpcflow/manifest.yml
  x-pack/filebeat/modules.d/aws.yml.disabled
Labels: Team:Integrations, backport-v7.15.0, backport-v7.16.0

#27449 backport: Add 7.15 branch
  .backportrc.json
  .mergify.yml
Labels: release, automation, Team:Automation, impact:critical

#27460 Be more lenient when checking for Saved Objects API in Kibana
  libbeat/kibana/client.go
  metricbeat/tests/system/test_base.py
  testing/environments/latest.yml
Labels: Team:Agent, backport-v7.15.0, backport-v7.16.0

#27434 docs: add note about aws creds
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: release-note:skip, Team:Docs, v7.14.0, v7.15.0

#27355 [Metricbeat] Add Linux pressure metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/linux.asciidoc
  metricbeat/docs/modules/linux/pressure.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/linux/_meta/config.yml
  metricbeat/module/linux/fields.go
  metricbeat/module/linux/pressure/_meta/data.json
  metricbeat/module/linux/pressure/_meta/docs.asciidoc
  metricbeat/module/linux/pressure/_meta/fields.yml
  metricbeat/module/linux/pressure/_meta/testdata/proc/pressure/cpu
  metricbeat/module/linux/pressure/_meta/testdata/proc/pressure/io
  metricbeat/module/linux/pressure/_meta/testdata/proc/pressure/memory
  metricbeat/module/linux/pressure/pressure.go
  metricbeat/module/linux/pressure/pressure_test.go
  metricbeat/modules.d/linux.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: enhancement, Metricbeat, Team:Integrations, :integrations

#27480 Transform json.Number values from http_endpoint
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/http_endpoint/handler.go
  x-pack/filebeat/input/http_endpoint/handler_test.go
Labels: bug, review, Team:Security-External Integrations, backport-v7.14.0, backport-v7.15.0, backport-v7.16.0

#27265 Osquerybeat: Add ECS Mapping support for ad-hoc/live queries
  x-pack/osquerybeat/beater/action_handler.go
  x-pack/osquerybeat/beater/action_handler_test.go
Labels: enhancement, Team:Asset Mgt, backport-v7.15.0, backport-v7.16.0

#27450 chore: update version to next minor 7.16.0
  libbeat/version/version.go
Labels: in progress, release, automation, Team:Automation

#27481 [agent] fix the inject_headers transpiler rule
  x-pack/elastic-agent/pkg/agent/program/testdata/enabled_output_true-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/enabled_true-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/fleet_server-fleet-server.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/namespace-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/namespace-fleet-server.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/namespace-metricbeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-filebeat.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-fleet-server.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/single_config-metricbeat.yml
  x-pack/elastic-agent/pkg/agent/transpiler/rules.go
  x-pack/elastic-agent/pkg/agent/transpiler/rules_test.go
Labels: bug, Team:Agent, backport-v7.14.0, backport-v7.15.0, backport-v7.16.0

#27484 Cherry-pick to 7.15: docs: add note about aws creds (#27434)
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: backport, needs_team

#27483 Cherry-pick to 7.14: docs: add note about aws creds (#27434)
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: backport, needs_team

#27482 Cherry-pick to 7.x: docs: add note about aws creds (#27434)
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: backport, needs_team

#26703 Update change-index-name.asciidoc
  libbeat/docs/howto/change-index-name.asciidoc
Labels: docs, Team:Docs

#27455 Cherry-pick to 7.x: [DOCS] Remove PKI mentions (#27422)
  libbeat/docs/shared-kibana-config.asciidoc
  libbeat/docs/shared-ssl-config.asciidoc
Labels: backport, Team:Docs

#27457 Cherry-pick to 7.14: [DOCS] Remove PKI mentions (#27422)
  libbeat/docs/shared-kibana-config.asciidoc
  libbeat/docs/shared-ssl-config.asciidoc
Labels: backport, Team:Docs

#27456 Cherry-pick to 7.15: [DOCS] Remove PKI mentions (#27422)
  libbeat/docs/shared-kibana-config.asciidoc
  libbeat/docs/shared-ssl-config.asciidoc
Labels: backport, Team:Docs

#27504 Cherry-pick to 7.14: Update change-index-name.asciidoc (#26703)
  libbeat/docs/howto/change-index-name.asciidoc
Labels: backport, needs_team

#27503 Cherry-pick to 7.x: Update change-index-name.asciidoc (#26703)
  libbeat/docs/howto/change-index-name.asciidoc
Labels: backport, needs_team

#27505 Cherry-pick to 7.15: Update change-index-name.asciidoc (#26703)
  libbeat/docs/howto/change-index-name.asciidoc
Labels: backport, needs_team

#27459 Add default evenhub settings for each log type
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
Labels: docs, Team:Docs

#27479 Osquerybeat: Support custom namespaces for scheduled queries
  x-pack/osquerybeat/beater/action_handler.go
  x-pack/osquerybeat/beater/config_plugin.go
  x-pack/osquerybeat/beater/config_plugin_test.go
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/internal/config/config.go
  x-pack/osquerybeat/internal/config/watcher.go
Labels: enhancement, Team:Asset Mgt, backport-v7.16.0

#27517 [automation] update elastic stack version for testing 7.15.0-e06b4078
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#26824 [Metricbeat] gcp: add GKE metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/gcp/constants.go
  x-pack/metricbeat/module/gcp/fields.go
  x-pack/metricbeat/module/gcp/gke/_meta/fields.yml
  x-pack/metricbeat/module/gcp/gke/gke_test.go
  x-pack/metricbeat/module/gcp/gke/manifest.yml
  x-pack/metricbeat/module/gcp/metrics/helpers.go
  x-pack/metricbeat/module/gcp/metrics/helpers_test.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
  x-pack/metricbeat/module/gcp/metrics/metricset_test.go
  x-pack/metricbeat/module/gcp/module.yml
Labels: enhancement, Team:Integrations, backport-v7.15.0, backport-v7.16.0

#27523 var.bucket renamed to var.bucket_arn in docs
  filebeat/docs/modules/aws.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
Labels: Team:Integrations, backport-v7.15.0, backport-v7.16.0

#27520 [Azure] Update metrics configuration and dashboards since the changes in the metrics azure api for container_registry
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-container-registry-overview.ndjson
  x-pack/metricbeat/module/azure/container_registry/manifest.yml
Labels: Team:Platforms

#27528 Cherry-pick #27520 to 7.x: [Azure] Update metrics configuration and dashboards since the changes in the metrics azure api for container_registry
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-container-registry-overview.ndjson
  x-pack/metricbeat/module/azure/container_registry/manifest.yml
Labels: backport, [zube]: In Review, Team:Platforms

#27529 Cherry-pick #27520 to 7.15: [Azure] Update metrics configuration and dashboards since the changes in the metrics azure api for container_registry
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/_meta/kibana/7/dashboard/Metricbeat-azure-container-registry-overview.ndjson
  x-pack/metricbeat/module/azure/container_registry/manifest.yml
Labels: backport, [zube]: In Review, Team:Platforms

#27515 [libbeat] Mark disk queue as GA
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/general.reference.yml.tmpl
  libbeat/docs/queueconfig.asciidoc
  libbeat/publisher/queue/diskqueue/queue.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: docs, Team:Agent, backport-v7.15.0, backport-v7.16.0

#27514 Fix logging in cgroup/process code
  libbeat/metric/system/cgroup/util.go
  libbeat/metric/system/process/process.go
Labels: bug, needs_team, backport-v7.15.0, backport-v7.16.0

#27444 [automation] update elastic stack version for testing 8.0.0-7e122dd9
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27519 [automation] update elastic stack version for testing 7.16.0-ab6de48d
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27295 feat: add a mage command to package system tests
  .ci/scripts/search_system_tests.py
  Jenkinsfile
  dev-tools/mage/common.go
  dev-tools/mage/target/common/package.go
Labels: Team:Automation, build-system, backport-v7.15.0, backport-v7.16.0

#26604 Indenting correction for module configuration example
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
Labels: docs, Team:Integrations

#27311 Fix: Allow non-padded base64 data to be decoded by decode_base64_field
  CHANGELOG.next.asciidoc
  libbeat/processors/actions/decode_base64_field.go
  libbeat/processors/actions/decode_base64_field_test.go
Labels: enhancement, review, Team:Agent, backport-v7.16.0

#27531 Osquerybeat: Improve unit test coverage. Consolidate ECS mapping.
  x-pack/osquerybeat/beater/action_handler.go
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/internal/action/action.go
  x-pack/osquerybeat/internal/action/action_test.go
Labels: cleanup, Team:Asset Mgt, backport-v7.16.0

#27473 Fix used memory calculations in docker/memory
  metricbeat/module/docker/memory/_meta/data.json
  metricbeat/module/docker/memory/helper.go
  metricbeat/module/docker/memory/memory_test.go
Labels: bug, Team:Integrations, backport-v7.15.0, backport-v7.16.0

#27546 [automation] update elastic stack version for testing 7.15.0-a7c04a10
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27510 Cherry-pick to master: Add default evenhub settings for each log type (#27459)
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
Labels: backport, Team:Docs

#27511 Cherry-pick to 7.15: Add default evenhub settings for each log type (#27459)
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
Labels: needs_team

#27512 Cherry-pick to 7.x: Add default evenhub settings for each log type (#27459)
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
Labels: needs_team

#27487 [automation] update elastic stack version for testing 7.14.1-a6cb01c7
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27502 Cherry-pick to master: Update change-index-name.asciidoc (#26703)
  libbeat/docs/howto/change-index-name.asciidoc
Labels: backport, Team:Docs

#27562 [automation] update elastic stack version for testing 7.15.0-ab91276c
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27563 [automation] update elastic stack version for testing 7.16.0-c3b80e7b
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27565 Cherry-pick #26604 to 7.x: Indenting correction for module configuration example
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
Labels: backport, [zube]: In Review, Team:Integrations

#27508 Do not try to load ILM if check_exists if false
  CHANGELOG.next.asciidoc
  libbeat/docs/shared-ilm.asciidoc
  libbeat/idxmgmt/ilm/ilm_test.go
  libbeat/idxmgmt/ilm/std.go
Labels: Team:Agent, backport-v7.15.0, backport-v7.16.0

#27559 [Heartbeat] Fix scheduler job type limit algorithm
  heartbeat/_meta/config/beat.reference.yml.tmpl
  heartbeat/heartbeat.reference.yml
  heartbeat/scheduler/schedjob.go
  heartbeat/scheduler/schedjob_test.go
  heartbeat/scheduler/scheduler.go
  heartbeat/scheduler/scheduler_test.go
  x-pack/heartbeat/heartbeat.reference.yml
Labels: bug, Heartbeat, Team:Uptime, v7.15.0

#27581 [automation] update elastic stack version for testing 7.15.0-b20b12b2
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, needs_team, build-monitoring, dependency

#27575 Remove fargate from aws module config
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/aws/_meta/config.yml
  x-pack/filebeat/modules.d/aws.yml.disabled
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0, backport-v7.16.0

#27621 [elastic-agent] Fix docker tar.gz generation for complete image
  dev-tools/mage/dockerbuilder.go
  dev-tools/mage/pkgtypes.go
Labels: bug, Packaging, Team:Uptime, v7.15.0

#27638 Filebeat auditd: Fix Top Exec Commands dashboard visualization
  CHANGELOG.next.asciidoc
  filebeat/module/auditd/_meta/kibana/7/visualization/5ebdbe50-0a0f-11e7-825f-6748cda7d858-ecs.json
Labels: bug, review, Team:Security-External Integrations, backport-v7.14.0, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0

#27646 [7.x](backport #27638) Filebeat auditd: Fix Top Exec Commands dashboard visualization
  CHANGELOG.next.asciidoc
  filebeat/module/auditd/_meta/kibana/7/dashboard/Filebeat-auditd.ndjson
Labels: bug, Team:Security-External Integrations, backport-v7.14.0, backport-v7.15.0
