Repository elastic/beats, pull requests merged in 2021-07, with the labels that each got.

#26613 CI: jenkins labels are less time consuming now
  Jenkinsfile
Labels: Team:Automation, backport-v7.13.0, backport-v7.14.0

#26620 backport: Add 7.14 branch
  .backportrc.json
  .mergify.yml
Labels: Team:Automation, automation, release

#26220 [Metricbeat] Add Airflow module in xpack
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/airflow.asciidoc
  metricbeat/docs/modules/airflow/statsd.asciidoc
  metricbeat/docs/modules/statsd.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/airflow/_meta/README.md
  x-pack/metricbeat/module/airflow/_meta/config.yml
  x-pack/metricbeat/module/airflow/_meta/docs.asciidoc
  x-pack/metricbeat/module/airflow/_meta/fields.yml
  x-pack/metricbeat/module/airflow/fields.go
  x-pack/metricbeat/module/airflow/module.yml
  x-pack/metricbeat/module/airflow/statsd/_meta/data.json
  x-pack/metricbeat/module/airflow/statsd/_meta/docs.asciidoc
  x-pack/metricbeat/module/airflow/statsd/_meta/fields.yml
  x-pack/metricbeat/module/airflow/statsd/data_test.go
  x-pack/metricbeat/module/airflow/statsd/manifest.yml
  x-pack/metricbeat/module/airflow/test_airflow.py
  x-pack/metricbeat/module/statsd/_meta/docs.asciidoc
  x-pack/metricbeat/module/statsd/server/data.go
  x-pack/metricbeat/module/statsd/server/data_test.go
  x-pack/metricbeat/module/statsd/server/mapping.go
  x-pack/metricbeat/module/statsd/server/server.go
  x-pack/metricbeat/modules.d/airflow.yml.disabled
Labels: Metricbeat, Team:Integrations, backport-v7.14.0, enhancement

#26641 [mergify] automate PRs that change the backport rules
  .mergify.yml
Labels: Team:Automation, automation

#26617 [CI] fight the flakiness with some retry option in the CI only for the Pull Requests
  Jenkinsfile
Labels: Team:Automation, backport-v7.13.0, backport-v7.14.0, backport-v7.15.0

#26607 Fix memory leak in SQL helper when database is not available
  CHANGELOG.next.asciidoc
  metricbeat/helper/sql/sql.go
  metricbeat/helper/sql/sql_test.go
Labels: Metricbeat, Team:Integrations, backport-v7.13.0, backport-v7.14.0, backport-v7.15.0, module, review

#26616 [Metricbeat] Fix jvm old / young collector
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/node_stats/data_xpack.go
Labels: Metricbeat, Stack monitoring, Team:Services, backport-v7.12.0, backport-v7.13.0, backport-v7.14.0, bug, needs_team

#26648 [mergify] set title and allow bp in any direction
  .mergify.yml
Labels: Team:Automation, automation

#26660 Cherry-pick #26524 to 7.14: [filebeat][fortinet] Use default add_locale for fortinet.firewall
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/fortinet.asciidoc
  x-pack/filebeat/module/fortinet/_meta/docs.asciidoc
  x-pack/filebeat/module/fortinet/firewall/config/firewall.yml
  x-pack/filebeat/module/fortinet/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/fortinet/firewall/test/event.log-expected.json
  x-pack/filebeat/module/fortinet/firewall/test/traffic.log-expected.json
  x-pack/filebeat/module/fortinet/firewall/test/utm.log-expected.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#26653 Bump up version to 7.15
  libbeat/version/version.go
Labels: Team:Agent

#26639 Cherry-pick #26561 to 7.x: Move openmetrics module to oss
  CHANGELOG.next.asciidoc
  Jenkinsfile
  metricbeat/docs/modules/openmetrics.asciidoc
  metricbeat/docs/modules/openmetrics/collector.asciidoc
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/openmetrics/_meta/Dockerfile
  metricbeat/module/openmetrics/_meta/config.yml
  metricbeat/module/openmetrics/_meta/docs.asciidoc
  metricbeat/module/openmetrics/_meta/fields.yml
  metricbeat/module/openmetrics/collector/_meta/data.json
  metricbeat/module/openmetrics/collector/_meta/docs.asciidoc
  metricbeat/module/openmetrics/collector/_meta/fields.yml
  metricbeat/module/openmetrics/collector/_meta/testdata/config.yml
  metricbeat/module/openmetrics/collector/_meta/testdata/docs.plain
  metricbeat/module/openmetrics/collector/_meta/testdata/docs.plain-expected.json
  metricbeat/module/openmetrics/collector/collector.go
  metricbeat/module/openmetrics/collector/collector_test.go
  metricbeat/module/openmetrics/docker-compose.yml
  metricbeat/module/openmetrics/fields.go
  metricbeat/module/openmetrics/test_openmetrics.py
  metricbeat/modules.d/openmetrics.yml.disabled
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/openmetrics/collector/collector.go
  x-pack/metricbeat/module/openmetrics/collector/collector_test.go
Labels: Team:Automation, Team:Integrations, [zube]: In Review, backport

#26663 Cherry-pick #26616 to 6.8.10: [Metricbeat] Fix jvm old / young collector
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/node_stats/data_xpack.go
Labels: Team:Services, [zube]: In Review, backport

#26662 Cherry-pick #26616 to 7.8: [Metricbeat] Fix jvm old / young collector
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/node_stats/data_xpack.go
Labels: Team:Services, [zube]: In Review, backport

#26674 [Heartbeat] use --params flag for synthetics
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
Labels: Heartbeat, Team:Uptime, bug, v7.14.0

#26649 Cherry-pick of: Update urllib to 1.26.5. (#26380)
  libbeat/tests/system/requirements.txt
Labels: Team:Integrations, backport

#26679 [Build] Disable armv7 packaging
  Jenkinsfile
Labels: Team:Agent, Team:Automation, backport-v7.13.0, backport-v7.14.0, bug

#26661 Cherry-pick #26557 to 7.14: Cherry-pick #26226 to 7.x: Set SM Filebeat modules as GA
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/elasticsearch.asciidoc
  filebeat/docs/modules/kibana.asciidoc
  filebeat/module/elasticsearch/_meta/docs.asciidoc
  filebeat/module/elasticsearch/_meta/fields.yml
  filebeat/module/elasticsearch/fields.go
  filebeat/module/kibana/_meta/docs.asciidoc
  filebeat/module/kibana/_meta/fields.yml
  filebeat/module/kibana/fields.go
  filebeat/module/logstash/_meta/fields.yml
  filebeat/module/logstash/fields.go
Labels: backport, needs_team, review

#26676 Make network_direction, registered_domain and convert processors compatible with ES older than 7.13.0
  CHANGELOG.next.asciidoc
  filebeat/fileset/compatibility.go
  filebeat/fileset/compatibility_test.go
Labels: Filebeat, Team:Security-External Integrations, backport-v7.13.0, backport-v7.14.0, backport-v7.15.0, bug, review

#26614 cyberarkpas: Link to official docs on how to setup syslog over TLS
  filebeat/docs/modules/cyberarkpas.asciidoc
  x-pack/filebeat/module/cyberarkpas/_meta/docs.asciidoc
Labels: Team:Security-External Integrations, backport-v7.13.0, backport-v7.14.0, backport-v7.15.0, docs, enhancement, review

#26702 [automation] update elastic stack version for testing 7.14.0-e1afed34
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26706 Packaging: linux/armv7 is not supported
  .ci/packaging.groovy
Labels: Team:Automation, automation, backport-v7.13.0, backport-v7.14.0, backport-v7.15.0

#26704 Revert "[CI] fight the flakiness with some retry option in the CI only for the Pull Requests"
  Jenkinsfile
Labels: Team:Automation

#26643 Add instructions on testing metricbeat kubernetes module
  metricbeat/module/kubernetes/_meta/test/docs/01_playground/ek_stack.yaml
  metricbeat/module/kubernetes/_meta/test/docs/01_playground/metricbeat.yaml
  metricbeat/module/kubernetes/_meta/test/docs/01_playground/playground-ubuntu.yaml
  metricbeat/module/kubernetes/_meta/test/docs/README.md
  metricbeat/module/kubernetes/_meta/test/docs/darwin.md
Labels: Team:Integrations, backport-v7.15.0, enhancement

#26583 Reduce the verbosity of the debug log for monitoring
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
Labels: Team:Agent, backport-v7.14.0, backport-v7.15.0, review

#26259 chore: Update test environments 7.13.3
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Automation, automation, release

#26631 [Filebeat] Replace copy_from with templated value
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/audit/ingest/pipeline-json.yml
  filebeat/module/nginx/ingress_controller/ingest/pipeline.yml
  x-pack/filebeat/module/cyberarkpas/audit/ingest/pipeline.yml
  x-pack/filebeat/module/panw/panos/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/abuseurl/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/anomali/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/anomalithreatstream/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/misp/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/otx/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/recordedfuture/ingest/pipeline.yml
  x-pack/filebeat/module/zoom/webhook/ingest/meeting.yml
Labels: Filebeat, Team:Security-External Integrations, backport-v7.13.0, backport-v7.14.0, bug

#26739 Osquerybeat: Fix the configuration poll interval setting
  x-pack/osquerybeat/internal/osqd/osqueryd.go
  x-pack/osquerybeat/internal/osqd/osqueryd_test.go
Labels: Team:Asset Mgt, backport-v7.14.0, backport-v7.15.0, bug

#26736 CI: retry the step only
  Jenkinsfile
Labels: Team:Automation, backport-v7.14.0, backport-v7.15.0

#26732 docs: Prepare Changelog for 6.8.17
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Agent, Team:Automation, Team:Docs, automation, docs, in progress, release

#26731 docs: Prepare Changelog for 7.13.3
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Agent, Team:Automation, Team:Docs, automation, docs, in progress, release

#26744 Forward port changelog for 7.13.3 (#26731) to 7.14
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#26566 Add agent fleet enrolment k8s manifest
  deploy/kubernetes/Makefile
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role-binding.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-service-account.yaml
Labels: Team:Integrations, backport-v7.15.0, enhancement, review

#26746 Upgrade PyYAML test dependency to 5.4.1
  libbeat/tests/system/requirements.txt
Labels: needs_team

#26752 Forward port changelog for 7.13.3 (#26731) to 7.x
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#26714 chore: Update version to 7.13.4
  libbeat/version/version.go
Labels: Team:Automation, automation, release

#26712 docs: update docs versions 7.13.3
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: Team:Automation, automation, docs, in progress, release

#26718 chore: Update version to 6.8.18
  libbeat/version/version.go
Labels: Team:Automation, automation, release

#26717 docs: update docs versions 6.8.17
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: Team:Automation, automation, docs, in progress, release

#26754 Forward port changelog for 7.13.3 (#26731) to master
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#26737 Filebeat: Ensure module pipelines compatibility with previous versions of Elasticsearch
  filebeat/Jenkinsfile.yml
  filebeat/fileset/compatibility.go
  filebeat/fileset/compatibility_test.go
  filebeat/tests/system/test_modules.py
  testing/environments/7.11.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/filebeat/module/fortinet/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/abuseurl/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/anomali/ingest/pipeline.yml
Labels: Filebeat, Team:Security-External Integrations, review

#26756 Update agent managed manifest to include enrolment token variable
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
Labels: Team:Integrations, backport-v7.15.0, enhancement

#26749 [Elastic Agent] Fix broken enrollment command
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
Labels: Team:Agent, backport-v7.14.0, backport-v7.15.0, bug

#26699 change type of max_bytes to ByteType
  CHANGELOG.next.asciidoc
  libbeat/reader/parser/parser.go
  libbeat/reader/parser/parser_example_test.go
Labels: Team:Security-External Integrations, backport-v7.14.0, bug

#26729 Add latest k8s versions in testing
  .ci/scripts/kind-setup.sh
  Jenkinsfile
  deploy/kubernetes/Jenkinsfile.yml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/module/kubernetes/_meta/docs.asciidoc
  metricbeat/module/kubernetes/controllermanager/controllermanager_integration_test.go
  metricbeat/module/kubernetes/test/integration.go
Labels: Team:Automation, Team:Integrations, backport-v7.14.0, backport-v7.15.0

#26762 [Elastic Agent] Remove experimental warning for inputs with variables
  x-pack/elastic-agent/pkg/composable/controller.go
Labels: Team:Agent, backport-v7.14.0, backport-v7.15.0

#26775 Osquerybeat: Change the query timeout from 3 secs to 60 secs
  x-pack/osquerybeat/beater/osquerybeat.go
Labels: Team:Asset Mgt, backport-v7.14.0, backport-v7.15.0, bug

#26774 Heartbeat: add datastream fields to synthetics
  heartbeat/monitors/factory.go
Labels: Team:Uptime, bug, v7.14.0

#26764 CI: increase timeout
  .ci/scripts/generate_build_table.py
  Jenkinsfile
Labels: Team:Automation, backport-v7.14.0, backport-v7.15.0

#26719 chore: Update test environments 6.8.18
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: Team:Automation, automation, release

#26715 chore: Update test environments 7.13.4
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Automation, automation, release

#26745 Osquerybeat: Change configuration plugin to map integrations to osquery packs configuration
  x-pack/osquerybeat/beater/action_handler.go
  x-pack/osquerybeat/beater/config_plugin.go
  x-pack/osquerybeat/beater/config_plugin_test.go
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/internal/config/config.go
  x-pack/osquerybeat/internal/osqd/osqueryd.go
Labels: Team:Asset Mgt, backport-v7.15.0, enhancement

#26765 Change the type of threatintel.indicator.first_seen to date
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/threatintel/_meta/fields.yml
  x-pack/filebeat/module/threatintel/fields.go
Labels: Filebeat, Team:Security-External Integrations, backport-v7.14.0, backport-v7.15.0, breaking change, review

#26794 threatintel: Add dashboards for RecordedFuture and Anomali ThreatStream
  filebeat/docs/images/filebeat-threatintel-anomali-limo.png
  filebeat/docs/images/filebeat-threatintel-anomali.png
  filebeat/docs/images/filebeat-threatintel-recordedfuture.png
  filebeat/docs/modules/threatintel.asciidoc
  x-pack/filebeat/module/threatintel/_meta/docs.asciidoc
  x-pack/filebeat/module/threatintel/_meta/kibana/7/dashboard/Filebeat-threatintel-anomali.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/dashboard/Filebeat-threatintel-overview.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/dashboard/Filebeat-threatintel-recordedfuture.json
  x-pack/filebeat/module/threatintel/module.yml
Labels: Filebeat, Team:Security-External Integrations, backport-v7.14.0, backport-v7.15.0, enhancement, review

#26785 [Elastic Agent] Remove symlink.prev from previously failed upgrade
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/rollback.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_relink.go
Labels: Team:Agent, bug, v7.14.0

#26804 [automation] update elastic stack version for testing 7.14.0-6fb865c2
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26789 CI: resilience with the new MacOS workers
  Jenkinsfile
  dev-tools/common.bash
  script/fix_permissions.sh
Labels: Team:Automation, backport-v7.13.0, backport-v7.14.0, backport-v7.15.0, macOS

#26808 Add daemonset name in pods controlled by DaemonSets
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/metadata/pod.go
  libbeat/common/kubernetes/metadata/pod_test.go
  libbeat/common/kubernetes/metadata/resource.go
Labels: Team:Integrations, backport-v7.15.0, enhancement

#26806 Cherry-pick #26785 to 7.14: Remove symlink.prev from previously failed upgrade
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/rollback.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_relink.go
Labels: Team:Agent, backport, bug, v7.14.0

#26807 Cherry-pick #26785 to 7.x: Remove symlink.prev from previously failed upgrade
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/rollback.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_relink.go
Labels: Team:Agent, backport, bug, v7.14.0

#26829 add_process_metadata: Support different integer types for pid field
  CHANGELOG.next.asciidoc
  libbeat/processors/add_process_metadata/add_process_metadata.go
  libbeat/processors/add_process_metadata/add_process_metadata_test.go
Labels: Filebeat, Team:Security-External Integrations, backport-v7.13.0, backport-v7.14.0, backport-v7.15.0, bug

#26723 CI: use withMageEnv
  .ci/scripts/install-go.bat
  .ci/scripts/install-tools.bat
  .ci/scripts/install-tools.sh
  Jenkinsfile
Labels: Team:Automation, automation, backport-v7.14.0, backport-v7.15.0

#26776 Set agent.id to Fleet Agent ID for each metric/log monitoring input
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
Labels: Agent, Team:Agent, backport-v7.14.0, backport-v7.15.0, bug, review

#26826 [Winlogbeat] Fixes for wineventlog experimental api
  CHANGELOG.next.asciidoc
  winlogbeat/sys/wineventlog/format_message.go
  winlogbeat/sys/wineventlog/metadata_store.go
  winlogbeat/sys/wineventlog/stringinserts.go
  winlogbeat/sys/wineventlog/syscall_windows.go
  winlogbeat/sys/wineventlog/template.go
  winlogbeat/sys/wineventlog/wineventlog_windows.go
  winlogbeat/sys/wineventlog/wineventlog_windows_test.go
  winlogbeat/sys/wineventlog/zsyscall_windows.go
Labels: Team:Security-External Integrations, Winlogbeat, backport-v7.15.0, bug, enhancement, review

#26781 [Heartbeat]: capture error from journey/end events
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
Labels: Team:Uptime, bug, v7.14.0

#26847 [httpjson] Add value_type parameter to httpjson transforms
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/internal/v2/pagination.go
  x-pack/filebeat/input/httpjson/internal/v2/response.go
  x-pack/filebeat/input/httpjson/internal/v2/transform.go
  x-pack/filebeat/input/httpjson/internal/v2/transform_append.go
  x-pack/filebeat/input/httpjson/internal/v2/transform_append_test.go
  x-pack/filebeat/input/httpjson/internal/v2/transform_set.go
  x-pack/filebeat/input/httpjson/internal/v2/transform_set_test.go
  x-pack/filebeat/input/httpjson/internal/v2/transform_test.go
  x-pack/filebeat/input/httpjson/internal/v2/value_tpl.go
  x-pack/filebeat/input/httpjson/internal/v2/value_tpl_test.go
Labels: Filebeat, Team:Security-External Integrations, backport-v7.15.0, enhancement

#26848 [fix][httpjson] Fix incorrect key for template data
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/internal/v2/response.go
  x-pack/filebeat/input/httpjson/internal/v2/response_test.go
Labels: Team:Security-External Integrations, backport-v7.14.0, backport-v7.15.0, bug

#26845 Update Golang version to 1.15.14
  .go-version
  CHANGELOG-developer.next.asciidoc
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/elastic-agent/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: Team:Agent

#26867 [Heartbeat]: update Node.js version for synthetics
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Uptime, backport-v7.14.0, backport-v7.15.0, bug, v7.14.0

#26864 Fix release state of k8s metricsets
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/kubernetes/controllermanager.asciidoc
  metricbeat/docs/modules/kubernetes/proxy.asciidoc
  metricbeat/docs/modules/kubernetes/scheduler.asciidoc
  metricbeat/docs/modules/kubernetes/state_cronjob.asciidoc
  metricbeat/docs/modules/kubernetes/state_resourcequota.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/module/kubernetes/controllermanager/_meta/fields.yml
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/proxy/_meta/fields.yml
  metricbeat/module/kubernetes/scheduler/_meta/fields.yml
  metricbeat/module/kubernetes/state_cronjob/_meta/fields.yml
  metricbeat/module/kubernetes/state_resourcequota/_meta/fields.yml
Labels: Team:Integrations

#26786 Clarify the scope of start/end multiline example
  filebeat/docs/multiline.asciidoc
Labels: docs, needs_team

#26882 [automation] update elastic stack version for testing 7.14.0-c78a4632
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26881 [automation] update elastic stack version for testing 8.0.0-2f008f4a
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26831 docs: update apm-server.auth
  libbeat/docs/command-reference.asciidoc
Labels: Team:Docs, release-note:skip, v7.14.0, v7.15.0

#26887 Cherry-pick to 7.x: docs: apm-server.auth (#26831)
  libbeat/docs/command-reference.asciidoc
Labels: backport, needs_team

#26888 Cherry-pick to 7.14: docs: apm-server.auth (#26831)
  libbeat/docs/command-reference.asciidoc
Labels: backport, needs_team

#26627 [Filebeat] Remove alias fields from Suricata and Traefik module mappings
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/module/traefik/access/_meta/fields.yml
  filebeat/module/traefik/fields.go
  x-pack/filebeat/module/suricata/eve/_meta/fields.yml
  x-pack/filebeat/module/suricata/fields.go
Labels: Filebeat, Team:Security-External Integrations, backport-v7.15.0, breaking change, release-note:breaking, review

#26728 Skip flaky test: filestream and harvester group
  filebeat/input/filestream/input_integration_test.go
  filebeat/input/filestream/internal/input-logfile/harvester_test.go
Labels: Team:Agent, Team:Integrations, backport-v7.14.0, backport-v7.15.0

#26899 [automation] update elastic stack version for testing 7.14.0-11e92b49
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26898 [automation] update elastic stack version for testing 7.15.0-588e7872
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26860 [automation] Update go release version 1.16.6
  .go-version
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/elastic-agent/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: automation, backport-v7.14.0, backport-v7.15.0, dependency, needs_team

#26904 Use common host parser in vsphere module
  CHANGELOG.next.asciidoc
  metricbeat/module/vsphere/datastore/_meta/data.json
  metricbeat/module/vsphere/datastore/datastore.go
  metricbeat/module/vsphere/host/_meta/data.json
  metricbeat/module/vsphere/host/host.go
  metricbeat/module/vsphere/metricset.go
  metricbeat/module/vsphere/test_vsphere.py
  metricbeat/module/vsphere/virtualmachine/_meta/data.json
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0, bug

#26265 Update asa-ftd-pipeline.yml
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/asa-fix.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/asa.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/filtered.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/not-ip.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/asa-fix.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/asa.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/dns.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/intrusion.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/not-ip.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/security-connection.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/security-malware-site.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: Integration:Cisco, Team:Security-External Integrations, backport-v7.13.0, backport-v7.14.0, backport-v7.15.0, bug

#26669 Add custom suffix to identifiers in filestream input when needed
  filebeat/input/filestream/identifier.go
  filebeat/input/filestream/identifier_test.go
  filebeat/input/filestream/prospector_creator.go
  libbeat/reader/parser/parser.go
  libbeat/reader/parser/parser_test.go
Labels: Team:Agent, backport-v7.15.0

#26400 Update breaking changes to mention removal of Beats central management
  libbeat/docs/release-notes/breaking/breaking-7.14.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
Labels: Team:Docs, docs, v7.14.0

#26922 Cherry-pick to 7.14: Add Beats central management removal to BCs (#26400)
  libbeat/docs/release-notes/breaking/breaking-7.14.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
Labels: Team:Docs, backport

#26921 Cherry-pick to 7.x: Add Beats central management removal to BCs (#26400)
  libbeat/docs/release-notes/breaking/breaking-7.14.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
Labels: backport, needs_team

#26924 [7.x](backport #26786) Clarify the scope of start/end multiline example
  filebeat/docs/multiline.asciidoc
Labels: needs_team

#26925 [7.13](backport #26786) Clarify the scope of start/end multiline example
  filebeat/docs/multiline.asciidoc
Labels: needs_team

#26870 [gcp/billing] always quote table name identifier
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/gcp/billing/billing.go
  x-pack/metricbeat/module/gcp/billing/billing_test.go
Labels: Team:Integrations, needs_backport

#26929 [automation] update elastic stack version for testing 7.14.0-02415b60
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26912 Expose custom process metrics
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring_test.go
  x-pack/elastic-agent/pkg/agent/program/spec.go
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/apm-server.yml
Labels: needs_team

#26892 [Heartbeat] redact authorization headers from logger
  libbeat/common/config_test.go
  libbeat/common/logging.go
Labels: Team:Uptime, backport-v7.13.0, backport-v7.14.0, backport-v7.15.0, bug, v7.14.0

#26911 Add disk queue unit tests based on the queuetest package
  libbeat/publisher/queue/diskqueue/consumer.go
  libbeat/publisher/queue/diskqueue/queue.go
  libbeat/publisher/queue/diskqueue/queue_test.go
Labels: Team:Agent, backport-v7.14.0, backport-v7.15.0, cleanup

#26933 Cherry-pick #26912 to 7.x: Expose custom process metrics
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring_test.go
  x-pack/elastic-agent/pkg/agent/program/spec.go
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/apm-server.yml
Labels: Team:Agent, enhancement, v7.15.0

#26926 [7.14](backport #26786) Clarify the scope of start/end multiline example
  filebeat/docs/multiline.asciidoc
Labels: needs_team

#26919 Add Cluster filter on Kubernetes Overview ECS dashboard
  CHANGELOG.next.asciidoc
  metricbeat/docs/images/metricbeat-kubernetes-clusteroverview.png
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/module/kubernetes/_meta/docs.asciidoc
  metricbeat/module/kubernetes/_meta/kibana/7/dashboard/Metricbeat-kubernetes-overview.json
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0, bug, docs, needs_backport

#26943 [automation] update elastic stack version for testing 7.15.0-876ab971
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26944 [automation] update elastic stack version for testing 7.14.0-de591ade
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26841 Increase timeout to 30secs
  x-pack/metricbeat/module/airflow/statsd/data_test.go
Labels: Team:Integrations, backport-v7.15.0

#26940 [Filebeat] Allow - for source IP for AWS S3 Access pipeline
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/aws/s3access/ingest/pipeline.yml
  x-pack/filebeat/module/aws/s3access/test/s3_server_access.log
  x-pack/filebeat/module/aws/s3access/test/s3_server_access.log-expected.json
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0, bug, needs_integration_sync

#21111 add_process_metadata: enrich process info with process owner (#21068)
  CHANGELOG.next.asciidoc
  auditbeat/docs/fields.asciidoc
  auditbeat/include/fields.go
  filebeat/docs/fields.asciidoc
  filebeat/include/fields.go
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  journalbeat/docs/fields.asciidoc
  journalbeat/include/fields.go
  libbeat/processors/add_process_metadata/_meta/fields.yml
  libbeat/processors/add_process_metadata/add_process_metadata.go
  libbeat/processors/add_process_metadata/add_process_metadata_test.go
  libbeat/processors/add_process_metadata/config.go
  libbeat/processors/add_process_metadata/docs/add_process_metadata.asciidoc
  libbeat/processors/add_process_metadata/gosigar_provider.go
  libbeat/processors/add_process_metadata/gosysinfo_provider.go
  metricbeat/docs/fields.asciidoc
  packetbeat/docs/fields.asciidoc
  packetbeat/include/fields.go
  winlogbeat/docs/fields.asciidoc
  winlogbeat/include/fields.go
  x-pack/functionbeat/docs/fields.asciidoc
  x-pack/functionbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
  x-pack/osquerybeat/docs/fields.asciidoc
  x-pack/osquerybeat/include/fields.go
Labels: Team:Security-External Integrations

#26907 Use MustAddMetricSet in all metricsets
  docs/devguide/create-metricset.asciidoc
  metricbeat/module/golang/expvar/expvar.go
  metricbeat/module/golang/heap/heap.go
  metricbeat/module/http/json/json.go
  metricbeat/module/http/server/server.go
  metricbeat/module/jolokia/jmx/jmx.go
  metricbeat/module/kubernetes/event/event.go
  metricbeat/module/kubernetes/state_container/state_container.go
  metricbeat/module/kubernetes/state_daemonset/state_daemonset.go
  metricbeat/module/kubernetes/state_deployment/state_deployment.go
  metricbeat/module/kubernetes/state_job/state_job.go
  metricbeat/module/kubernetes/state_node/state_node.go
  metricbeat/module/kubernetes/state_pod/state_pod.go
  metricbeat/module/kubernetes/state_replicaset/state_replicaset.go
  metricbeat/module/kubernetes/state_statefulset/state_statefulset.go
  metricbeat/module/php_fpm/process/process.go
Labels: Metricbeat, Team:Integrations, backport-v7.15.0, module, technical debt

#26958 docs: Prepare Changelog for 7.13.4
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Automation, automation, docs, in progress, release

#26961 Forward Port 7.13.4 changelog to 7.14
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, release

#26962 Cherry-pick #26852 to 7.x: Use aws sdk paginator for FilterLogEvents and GetMetricData
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
Labels: Team:Integrations, [zube]: In Review, backport

#26963 Cherry-pick #26852 to 7.14: Use aws sdk paginator for FilterLogEvents and GetMetricData
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
Labels: Team:Integrations, [zube]: In Review, backport

#26965 Forward port 7.13.4 changelog to 7.x
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, release

#26971 Forward port 7.13.4 to master
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, release

#26813 chore: Update version to 7.13.5
  libbeat/version/version.go
Labels: Team:Automation, automation, release

#26834 Osquerybeat: ECS mapping for scheduled queries
  x-pack/osquerybeat/beater/action_handler.go
  x-pack/osquerybeat/beater/config_plugin.go
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/internal/config/config.go
  x-pack/osquerybeat/internal/ecs/mapping.go
  x-pack/osquerybeat/internal/ecs/mapping_test.go
Labels: Team:Asset Mgt, backport-v7.15.0, enhancement

#26763 [Elastic Agent] Remove beta warn and warn module
  x-pack/elastic-agent/pkg/agent/application/application.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
  x-pack/elastic-agent/pkg/agent/cmd/install.go
  x-pack/elastic-agent/pkg/agent/warn/warn.go
Labels: Team:Agent, backport-v7.14.0, backport-v7.15.0

#26523 Expose region in AWS configuration so Functionbeat can deploy the Lamba in the correct place
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/manager/aws/cli_manager.go
  x-pack/functionbeat/provider/aws/aws/config.go
Labels: Team:Agent, backport-v7.14.0, needs_integration_sync

#26972 Fix k8s overview dashboard version
  dev-tools/mage/pytest.go
  metricbeat/module/kubernetes/_meta/kibana/7/dashboard/Metricbeat-kubernetes-overview.json
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0

#26984 Add action timeout. Use previously defined default of 1 minute if the action timeout is not specified.
  x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_application.go
  x-pack/elastic-agent/pkg/fleetapi/action.go
Labels: Team:Asset Mgt, backport-v7.15.0

#25976 Add support to combine update operations
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/internal/input-logfile/clean_test.go
  filebeat/input/filestream/internal/input-logfile/cursor.go
  filebeat/input/filestream/internal/input-logfile/cursor_test.go
  filebeat/input/filestream/internal/input-logfile/harvester.go
  filebeat/input/filestream/internal/input-logfile/input.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/filestream/internal/input-logfile/publish.go
  filebeat/input/filestream/internal/input-logfile/publish_test.go
  filebeat/input/filestream/internal/input-logfile/store.go
  filebeat/input/filestream/internal/input-logfile/store_test.go
  filebeat/input/filestream/internal/input-logfile/update_writer.go
  filebeat/input/filestream/internal/input-logfile/update_writer_test.go
Labels: Team:Agent, backport-v7.15.0

#26973 [Metricbeat] gcp: refactor service based metric filter creation
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester_test.go
Labels: Team:Integrations, backport-v7.15.0, enhancement

#26989 Document and test the diskQueueACKs helper in the disk queue
  libbeat/publisher/queue/diskqueue/acks.go
  libbeat/publisher/queue/diskqueue/acks_test.go
  libbeat/publisher/queue/diskqueue/segments.go
Labels: Team:Agent, backport-v7.14.0, backport-v7.15.0, bug, cleanup

#27009 [automation] update elastic stack version for testing 7.15.0-192e1003
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26801 [Agent] Support Node and Service autodiscovery in k8s provider
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/config.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/kubernetes.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/node.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/node_test.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/pod.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/pod_test.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/service.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/service_test.go
Labels: Team:Integrations, autodiscovery, backport-v7.15.0, kubernetes, v7.15.0

#27003 Fix aws dashboards and reenable test
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-billing-overview.json
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-kinesis-overview.json
  x-pack/metricbeat/tests/system/test_xpack_base.py
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0

#27006 Fix timer failure
  heartbeat/scheduler/timerqueue/queue.go
  heartbeat/scheduler/timerqueue/queue_test.go
Labels: Heartbeat, Team:Uptime, bug, v7.14.0

#27002 Osquerybeat: Improve logging for osqueryd log messages captured in our logging plugin
  x-pack/osquerybeat/beater/logger_plugin.go
  x-pack/osquerybeat/beater/osquerybeat.go
Labels: Team:Asset Mgt, backport-v7.15.0, enhancement, v7.15.0

#27007 Fix service name for cloudwatch logs
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awscloudwatch/input.go
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0

#26665 [Elastic Agent] Set permissions during installation
  libbeat/api/npipe/listener_windows.go
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/control/server/listener_windows.go
  x-pack/elastic-agent/pkg/agent/install/install.go
  x-pack/elastic-agent/pkg/agent/install/perms_unix.go
  x-pack/elastic-agent/pkg/agent/install/perms_windows.go
Labels: Team:Agent, backport-v7.14.0, backport-v7.15.0

#27031 packaging: retryWithSleep the google storage upload
  Jenkinsfile
Labels: Team:Automation, backport-v7.14.0, backport-v7.15.0

#27040 [automation] update elastic stack version for testing 7.15.0-514bcfaf
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#27039 [automation] update elastic stack version for testing 7.14.0-0ce5c542
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26640 upstream.response.status_code handling fix
  filebeat/module/nginx/ingress_controller/ingest/pipeline.yml
Labels: Filebeat, backport-v7.15.0, bug, module, needs_team

#26814 chore: Update test environments 7.13.5
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Automation, automation, release

#26977 Do not add all contextual information to the same logger in `filestream` prospector
  filebeat/input/filestream/copytruncate_prospector.go
  filebeat/input/filestream/logger.go
  filebeat/input/filestream/prospector.go
Labels: Team:Agent, backport-v7.14.0, backport-v7.15.0, bug

#27054 [automation] update elastic stack version for testing 7.15.0-6e66e5d1
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#27056 [automation] update elastic stack version for testing 7.14.0-de25a427
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#27045 Preserve annotations in a kubernetes namespace metadata
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/metadata/namespace.go
  libbeat/common/kubernetes/metadata/namespace_test.go
Labels: Team:Integrations, backport-v7.15.0

#27063 No changelog for 8.0.0-alpha1
  CHANGELOG.asciidoc
  libbeat/docs/release.asciidoc
  x-pack/osquerybeat/internal/ecs/mapping.go
  x-pack/osquerybeat/internal/ecs/mapping_test.go
Labels: Team:Agent, Team:Docs, docs

#27051 Fix typo in redis docs
  metricbeat/docs/fields.asciidoc
  metricbeat/module/redis/fields.go
  metricbeat/module/redis/info/_meta/fields.yml
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0

#26832 Add Proxy settings to AWS Common
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/aws.asciidoc
  libbeat/common/transport/httpcommon/proxy.go
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/s3_integration_test.go
  x-pack/filebeat/module/aws/_meta/docs.asciidoc
  x-pack/filebeat/module/aws/cloudtrail/config/aws-s3.yml
  x-pack/filebeat/module/aws/cloudtrail/manifest.yml
  x-pack/filebeat/module/aws/cloudwatch/config/aws-s3.yml
  x-pack/filebeat/module/aws/cloudwatch/manifest.yml
  x-pack/filebeat/module/aws/ec2/config/aws-s3.yml
  x-pack/filebeat/module/aws/ec2/manifest.yml
  x-pack/filebeat/module/aws/elb/config/aws-s3.yml
  x-pack/filebeat/module/aws/elb/manifest.yml
  x-pack/filebeat/module/aws/s3access/config/aws-s3.yml
  x-pack/filebeat/module/aws/s3access/manifest.yml
  x-pack/filebeat/module/aws/vpcflow/config/input.yml
  x-pack/filebeat/module/aws/vpcflow/manifest.yml
  x-pack/functionbeat/manager/aws/cli_manager.go
  x-pack/libbeat/autodiscover/providers/aws/ec2/provider.go
  x-pack/libbeat/autodiscover/providers/aws/elb/provider.go
  x-pack/libbeat/common/aws/credentials.go
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
  x-pack/metricbeat/module/aws/aws.go
Labels: Team:Integrations, backport-v7.15.0, needs_integration_sync

#26960 [Metricbeat] gcp: allow service metric prefix override
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/gcp.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/gcp/_meta/config.yml
  x-pack/metricbeat/module/gcp/metrics/_meta/docs.asciidoc
  x-pack/metricbeat/module/gcp/metrics/metricset.go
  x-pack/metricbeat/module/gcp/metrics/metricset_test.go
  x-pack/metricbeat/modules.d/gcp.yml.disabled
Labels: Team:Integrations, backport-v7.15.0, enhancement

#27092 [automation] update elastic stack version for testing 7.14.0-cd696777
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26880 [Filebeat] Update Elasticsearch Deprecation fileset parsing
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/deprecation/ingest/pipeline-json.yml
  filebeat/module/elasticsearch/deprecation/ingest/pipeline-plaintext.yml
  filebeat/module/elasticsearch/deprecation/test/elasticsearch_deprecation.log
  filebeat/module/elasticsearch/deprecation/test/elasticsearch_deprecation.log-expected.json
  filebeat/module/elasticsearch/deprecation/test/test-json.log
  filebeat/module/elasticsearch/deprecation/test/test-json.log-expected.json
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0, needs_integration_sync

#27089 [automation] update elastic stack version for testing 6.8.18-a4ab6ea8
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#26947 Update DiscoverKubernetesNode with error handling
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/node.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/common/kubernetes/util.go
  libbeat/common/kubernetes/util_test.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  metricbeat/module/kubernetes/util/kubernetes.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/kubernetes.go
Labels: Team:Integrations, backport-v7.15.0, enhancement

#27090 [automation] update elastic stack version for testing 7.15.0-bd471fd6
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#27098 Fix version placeholder for elastic-agent k8s manifest
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
Labels: Team:Integrations, backport-v7.15.0

#27072 Close monitored files after 5 minutes of inactivity
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
Labels: Team:Agent, backport-v7.14.0, backport-v7.15.0

#27080 [CI] use try to avoid a global abort
  Jenkinsfile
Labels: Team:Automation, backport-v7.14.0, backport-v7.15.0

#27106 [7.x](backport #27098) Fix version placeholder for elastic-agent k8s manifest
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
Labels: Team:Automation

#27122 [automation] update elastic stack version for testing 7.14.0-9fdd79d4
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, needs_team

#27125 [libbeat] Remove experimental flags from decode_xml processor
  libbeat/processors/decode_xml/decode_xml.go
  libbeat/processors/decode_xml/docs/decode_xml.asciidoc
Labels: Team:Security-External Integrations, backport-v7.15.0, enhancement

#27131 Set the default value for KIBANA_FLEET_PASSWORD in elastic-agent-managed-daemonset
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
Labels: Team:Integrations, backport-v7.15.0

#27119 Fix AWS Kinesis dashboard
  metricbeat/docs/images/metricbeat-aws-kinesis-overview.png
  x-pack/metricbeat/module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-kinesis-overview.json
Labels: Team:Integrations, backport-v7.14.0, backport-v7.15.0
