Repository elastic/beats, pull requests merged in 2021-01, with the labels that each got.

#23219 Cherry-pick #22668 to 7.x: Honor kube event resysncs to handle missed watch events
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/autodiscover.go
  libbeat/autodiscover/autodiscover_test.go
  libbeat/autodiscover/providers/docker/docker.go
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
  libbeat/autodiscover/providers/kubernetes/node.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/autodiscover/providers/kubernetes/service.go
  libbeat/autodiscover/providers/kubernetes/service_test.go
  libbeat/common/kubernetes/watcher.go
Labels: Team:Platforms, [zube]: In Review, backport, test-plan

#23282 Cherry-pick #21719 to 7.x: Fix stress test package list
  libbeat/scripts/Makefile
Labels: Team:Services, [zube]: In Review, backport

#23283 Cherry-pick #20366 to 7.x: Pipeline client test log progress
  libbeat/publisher/pipeline/output_test.go
Labels: Team:Services, [zube]: In Review, backport

#23336 Cherry-pick #22342 to 7.10: Add reference to Kerberos in Kafka input and output documentation
  filebeat/docs/inputs/input-kafka.asciidoc
  libbeat/outputs/kafka/docs/kafka.asciidoc
Labels: Team:Services, [zube]: In Review, backport

#23305 Cherry-pick #23227 to 7.x: Add user-facing changelog entry for dynamic cpu changes
  CHANGELOG.next.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#23343 Cherry-pick #23320 to 7.x: Skip flaky TestAutodiscoverWithMutlipleEntries test
  libbeat/autodiscover/autodiscover_test.go
Labels: Team:Integrations, Team:Platforms, [zube]: In Review, backport

#23361 [Filebeat] Fixing test logs for mysqlenterprise and changing date format
  x-pack/filebeat/module/mysqlenterprise/audit/ingest/pipeline.yml
  x-pack/filebeat/module/mysqlenterprise/audit/test/mysql_audit_test.log-expected.json
Labels: Filebeat, Team:Integrations, enhancement, needs_backport

#23234 [docs] Make shared content about autodiscovery beats-agnostic
  libbeat/docs/shared-autodiscover.asciidoc
Labels: docs, needs_backport, needs_team, review

#23230 Update monitoring-metricbeat.asciidoc (#21863)
  libbeat/docs/monitoring/monitoring-metricbeat.asciidoc
Labels: backport, docs, needs_team

#23236 [Filebeat] Improve Suricata error handling
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/suricata/eve/_meta/fields.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns-answer-v1.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns-answer-v2.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns.yml
  x-pack/filebeat/module/suricata/eve/ingest/pipeline.yml
  x-pack/filebeat/module/suricata/eve/ingest/tls.yml
  x-pack/filebeat/module/suricata/eve/test/eve-small.log
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
  x-pack/filebeat/module/suricata/fields.go
Labels: Filebeat, Team:Security-External Integrations, bug, needs_backport

#23367 Cherry-pick to 7.x: Make shared content beats-agnostic (#23234)
  libbeat/docs/shared-autodiscover.asciidoc
Labels: backport, docs, needs_team

#23368 Cherry-pick to 7.10: Make shared content beats-agnostic (#23234)
  libbeat/docs/shared-autodiscover.asciidoc
Labels: backport, docs, needs_team

#23364 Cherry-pick #21325 to 7.x: [Winlogbeat] Add IP validation to Security module
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/security/config/winlogbeat-security.js
Labels: Team:SIEM, [zube]: In Review, backport

#23365 Cherry-pick #21325 to 7.11: [Winlogbeat] Add IP validation to Security module
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/security/config/winlogbeat-security.js
Labels: Team:SIEM, [zube]: In Review, backport

#23372 Update suricata fields in filebeat
  filebeat/docs/fields.asciidoc
Labels: Team:Integrations, Team:Security-External Integrations

#23370 Fix flaky test case TestAutodiscoverWithMutlipleEntries in autodiscover
  libbeat/autodiscover/autodiscover_test.go
Labels: Team:Integrations, needs_backport

#23363 Cherry-pick #23361 #23361 to 7.x: [Filebeat] Fixing test logs for Ciscao ASA logs mysqlenterprise and changing date format
  x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json
  x-pack/filebeat/module/mysqlenterprise/audit/ingest/pipeline.yml
  x-pack/filebeat/module/mysqlenterprise/audit/test/mysql_audit_test.log-expected.json
Labels: Team:Services, [zube]: In Review, backport

#23374 Cherry-pick #23370 to 7.x: Fix flaky test case TestAutodiscoverWithMutlipleEntries in autodiscover
  libbeat/autodiscover/autodiscover_test.go
Labels: Team:Integrations, [zube]: In Review, backport

#23376 Cherry-pick #23362 to 7.10: [Filebeat] Fixing timestamps on some golden files for cisco asa without a year
  x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json
Labels: Team:Services, [zube]: In Review, backport

#23375 Cherry-pick #23363 to 7.11: Cherry-pick #23361 #23361 to 7.x: [Filebeat] Fixing test logs for Ciscao ASA logs mysqlenterprise and changing date format
  x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json
  x-pack/filebeat/module/mysqlenterprise/audit/ingest/pipeline.yml
  x-pack/filebeat/module/mysqlenterprise/audit/test/mysql_audit_test.log-expected.json
Labels: Team:Services, [zube]: In Review, backport

#23274 Synthetics docker image
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Heartbeat, Team:Uptime, enhancement

#23335 Fix types for response fields of kubelet api
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/_meta/test/stats_summary.json
  metricbeat/module/kubernetes/container/_meta/fields.yml
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/node/_meta/fields.yml
  metricbeat/module/kubernetes/node/node_test.go
  metricbeat/module/kubernetes/pod/_meta/fields.yml
  metricbeat/module/kubernetes/pod/data.go
  metricbeat/module/kubernetes/state_daemonset/_meta/data.json
  metricbeat/module/kubernetes/system/_meta/fields.yml
  metricbeat/module/kubernetes/types.go
  metricbeat/module/kubernetes/volume/_meta/fields.yml
Labels: Team:Platforms, [zube]: In Review, needs_reviewer, review, v7.11.0, v7.12.0

#23344 Provide more ways to set AWS credentials in Functionbeat
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/_meta/config/beat.reference.yml.tmpl
  x-pack/functionbeat/docs/config-options-aws.asciidoc
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/functionbeat/manager/aws/cli_manager.go
  x-pack/functionbeat/manager/aws/template_builder.go
  x-pack/functionbeat/provider/aws/aws/config.go
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Functionbeat, Team:Agent

#23382 chore: rename variable for e2e tests
  .ci/packaging.groovy
Labels: Team:Automation, needs_backport

#23186 [CI] disable aws cloud testing by default
  .ci/jobs/beats-schedule-weekly.yml
  .ci/schedule-weekly.groovy
  Jenkinsfile
  x-pack/metricbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, aws, ci

#23389 Cherry-pick to 7.11: [CI] disable aws cloud testing by default (#23186)
  .ci/jobs/beats-schedule-weekly.yml
  .ci/schedule-weekly.groovy
  Jenkinsfile
  x-pack/metricbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23388 Cherry-pick to 7.10: [CI] disable aws cloud testing by default (#23186)
  .ci/jobs/beats-schedule-weekly.yml
  .ci/schedule-weekly.groovy
  Jenkinsfile
  x-pack/metricbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23383 Cherry-pick #23335 to 7.x: Fix types for response fields of kubelet api
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/_meta/test/stats_summary.json
  metricbeat/module/kubernetes/container/_meta/fields.yml
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/node/_meta/fields.yml
  metricbeat/module/kubernetes/node/node_test.go
  metricbeat/module/kubernetes/pod/_meta/fields.yml
  metricbeat/module/kubernetes/pod/data.go
  metricbeat/module/kubernetes/state_daemonset/_meta/data.json
  metricbeat/module/kubernetes/system/_meta/fields.yml
  metricbeat/module/kubernetes/types.go
  metricbeat/module/kubernetes/volume/_meta/fields.yml
Labels: Team:Platforms, [zube]: In Review, backport

#23384 Cherry-pick #23335 to 7.11: Fix types for response fields of kubelet api
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/_meta/test/stats_summary.json
  metricbeat/module/kubernetes/container/_meta/fields.yml
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/node/_meta/fields.yml
  metricbeat/module/kubernetes/node/node_test.go
  metricbeat/module/kubernetes/pod/_meta/fields.yml
  metricbeat/module/kubernetes/pod/data.go
  metricbeat/module/kubernetes/state_daemonset/_meta/data.json
  metricbeat/module/kubernetes/system/_meta/fields.yml
  metricbeat/module/kubernetes/types.go
  metricbeat/module/kubernetes/volume/_meta/fields.yml
Labels: Team:Platforms, [zube]: In Review, backport

#23387 Cherry-pick to 7.x: [CI] disable aws cloud testing by default (#23186)
  .ci/jobs/beats-schedule-weekly.yml
  .ci/schedule-weekly.groovy
  Jenkinsfile
  x-pack/metricbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23386 Cherry-pick #23344 to 7.x: Provide more ways to set AWS credentials in Functionbeat
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/_meta/config/beat.reference.yml.tmpl
  x-pack/functionbeat/docs/config-options-aws.asciidoc
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/functionbeat/manager/aws/cli_manager.go
  x-pack/functionbeat/manager/aws/template_builder.go
  x-pack/functionbeat/provider/aws/aws/config.go
  x-pack/libbeat/docs/aws-credentials-config.asciidoc
Labels: Team:Services, [zube]: In Review, backport

#23142 Cherry-pick #22076 to 7.x: Cherry-pick to 7.10: packaging backports
  .ci/packaging.groovy
Labels: Team:Automation, [zube]: In Review, backport, needs_backport, v7.11.0

#23378 [CI][lint] Enable OSS linting when x-pack changes
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, ci, needs_backport, v7.11.0, v7.12.0

#23401 Fix heartbeat build
  Jenkinsfile
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Automation, Team:Integrations, needs_backport, v7.11.0, v7.12.0

#23407 Cherry-pick #23401 to 7.x: Launch packaging jobs when packaging files are changed
  Jenkinsfile
Labels: Team:Automation, Team:Integrations, [zube]: In Review, backport

#23403 Cherry-pick to 7.x: [CI][lint] Enable OSS linting when x-pack changes (#23378)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23404 Cherry-pick to 7.10: [CI][lint] Enable OSS linting when x-pack changes (#23378)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23405 Cherry-pick to 7.11: [CI][lint] Enable OSS linting when x-pack changes (#23378)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23413 libbeat/cmd/instance/metrics: fix error message
  libbeat/cmd/instance/metrics/metrics.go
Labels: Team:Services, bug

#23327 Update default config in windows.yml
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/_meta/config.yml
  metricbeat/modules.d/windows.yml.disabled
Labels: Team:Platforms, [zube]: In Review, needs_backport

#23369 Cherry-pick #23236 to 7.x: [Filebeat] Improve Suricata error handling
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/suricata/eve/_meta/fields.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns-answer-v1.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns-answer-v2.yml
  x-pack/filebeat/module/suricata/eve/ingest/dns.yml
  x-pack/filebeat/module/suricata/eve/ingest/pipeline.yml
  x-pack/filebeat/module/suricata/eve/ingest/tls.yml
  x-pack/filebeat/module/suricata/eve/test/eve-small.log
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
  x-pack/filebeat/module/suricata/fields.go
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#23381 [Auditbeat] Fix docs and config for arm builds
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/docs/modules/system.asciidoc
  x-pack/auditbeat/module/system/_meta/config.yml.tmpl
  x-pack/auditbeat/module/system/_meta/docs.asciidoc
Labels: Team:Integrations, bug, docs, v7.10.2, v7.11.0, v7.12.0, v8.0.0

#21065 add support for multiple regions
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/config/config.go
  x-pack/functionbeat/config/config_test.go
  x-pack/functionbeat/manager/aws/template_builder.go
Labels: Functionbeat, Team:Integrations, Team:Services

#23409 [CI] cross linting with full match support
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, ci

#23270 DaemonSet is supposed to be camelCase
  libbeat/docs/shared-autodiscover.asciidoc
Labels: Team:Docs

#23352 Clean up naming conventions for namespace and dataset settings
  x-pack/elastic-agent/_meta/config/common.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/common.reference.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/elastic-agent.docker.yml.tmpl
  x-pack/elastic-agent/_meta/elastic-agent.yml
  x-pack/elastic-agent/elastic-agent.docker.yml
  x-pack/elastic-agent/elastic-agent.reference.yml
  x-pack/elastic-agent/elastic-agent.yml
Labels: Team:Ingest Management, docs, v7.11.0

#23434 Cherry-pick to 7.x: Clean up naming conventions for namespace and dataset settings (#23352)
  x-pack/elastic-agent/_meta/config/common.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/common.reference.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/elastic-agent.docker.yml.tmpl
  x-pack/elastic-agent/_meta/elastic-agent.yml
  x-pack/elastic-agent/elastic-agent.docker.yml
  x-pack/elastic-agent/elastic-agent.reference.yml
  x-pack/elastic-agent/elastic-agent.yml
Labels: backport, docs, needs_team

#23435 Cherry-pick to 7.11: Clean up naming conventions for namespace and dataset settings (#23352)
  x-pack/elastic-agent/_meta/config/common.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/common.reference.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/elastic-agent.docker.yml.tmpl
  x-pack/elastic-agent/_meta/elastic-agent.yml
  x-pack/elastic-agent/elastic-agent.docker.yml
  x-pack/elastic-agent/elastic-agent.reference.yml
  x-pack/elastic-agent/elastic-agent.yml
Labels: backport, docs, needs_team

#23432 Cherry-pick to 7.10: DaemonSet is supposed to be camelCase (#23270)
  libbeat/docs/shared-autodiscover.asciidoc
Labels: backport, docs, needs_team

#23431 Cherry-pick to 7.x: DaemonSet is supposed to be camelCase (#23270)
  libbeat/docs/shared-autodiscover.asciidoc
Labels: backport, docs, needs_team

#23421 Cherry-pick to 7.11: [CI] cross linting with full match support (#23409)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23423 Cherry-pick to 7.10: [CI] cross linting with full match support (#23409)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23422 Cherry-pick to 7.x: [CI] cross linting with full match support (#23409)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23419 Handle DeletedFinalStateUnknown in k8s OnDelete
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/service.go
  libbeat/common/kubernetes/watcher.go
Labels: Team:Integrations, bug, v7.11.0, v7.12.0

#23444 [Elastic-Agent] Do not take ownership of Endpoint log path
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
Labels: Team:Agent, Team:Ingest Management

#23426 Cherry-pick #23381 to 7.11: [Auditbeat] Fix docs and config for arm builds
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/docs/modules/system.asciidoc
  x-pack/auditbeat/module/system/_meta/config.yml.tmpl
  x-pack/auditbeat/module/system/_meta/docs.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#23425 Cherry-pick #23381 to 7.x: [Auditbeat] Fix docs and config for arm builds
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/docs/modules/system.asciidoc
  x-pack/auditbeat/module/system/_meta/config.yml.tmpl
  x-pack/auditbeat/module/system/_meta/docs.asciidoc
Labels: Team:Integrations, [zube]: In Review, backport

#23427 docs: fix CHANGELOG links
  CHANGELOG-developer.asciidoc
  CHANGELOG.asciidoc
Labels: Team:Docs, v7.10.0

#23443 Cherry-pick #23419 to 7.x: Handle DeletedFinalStateUnknown in k8s OnDelete
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/service.go
  libbeat/common/kubernetes/watcher.go
Labels: Team:Integrations, [zube]: In Review, backport

#23448 Update .backportrc.json
  .backportrc.json
Labels: Team:Automation

#23449 Cherry-pick to 7.x: docs: fix changelog links (#23427)
  CHANGELOG.asciidoc
Labels: Team:Docs, backport

#23451 Cherry-pick to 7.11: docs: fix changelog links (#23427)
  CHANGELOG.asciidoc
Labels: Team:Docs, backport

#23450 Cherry-pick to 7.10: docs: fix changelog links (#23427)
  CHANGELOG.asciidoc
Labels: Team:Docs, backport

#23445 Cherry-pick #23444 to 7.x: [Elastic-Agent] Do not take ownership of Endpoint log path
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
Labels: Team:Agent, Team:Ingest Management, [zube]: In Review, backport

#23446 Cherry-pick #23444 to 7.11: [Elastic-Agent] Do not take ownership of Endpoint log path
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
Labels: Team:Agent, Team:Ingest Management, [zube]: In Review, backport

#23456 [Ingest Manager] Skip top level files when unziping archive during upgrade
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_unpack.go
Labels: Ingest Management:beta2, Team:Ingest Management, bug, needs_backport, v7.10.2, v7.11.0

#23455 [7.x] Sync changelog
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#23461 7.10 sync changelog
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#23454 Sync beats changelog [master]
  CHANGELOG.asciidoc
Labels: Team:Docs

#23458 Cherry-pick #23456 to 7.x: Skip top level files when unziping archive during upgrade
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_unpack.go
Labels: Team:Ingest Management, backport, bug, v7.10.2, v7.11.0

#23460 Cherry-pick #23456 to 7.11: Skip top level files when unziping archive during upgrade
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_unpack.go
Labels: backport, bug, needs_team, v7.10.2, v7.11.0

#23459 Cherry-pick #23456 to 7.10: Skip top level files when unziping archive during upgrade
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_unpack.go
Labels: backport, bug, needs_team, v7.10.2, v7.11.0

#23464 [7.11] Sync changelog (#23455)
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#23373 [docs] Update misleading phrasing for logging.metrics.enabled
  libbeat/docs/loggingconfig.asciidoc
Labels: Team:Docs

#23433 Cherry-pick to 7.11: DaemonSet is supposed to be camelCase (#23270)
  libbeat/docs/shared-autodiscover.asciidoc
Labels: backport, docs, needs_team

#23415 Cherry-pick #23413 to 7.11: libbeat/cmd/instance/metrics: fix error message
  libbeat/cmd/instance/metrics/metrics.go
Labels: Team:Services, [zube]: In Review, backport

#23414 Cherry-pick #23413 to 7.x: libbeat/cmd/instance/metrics: fix error message
  libbeat/cmd/instance/metrics/metrics.go
Labels: Team:Services, [zube]: In Review, backport

#23439 Update geoip info to include Autonomous System
  libbeat/docs/shared-geoip.asciidoc
Labels: Team:Security-External Integrations, docs

#23442 Cherry-pick #23419 to 7.11: Handle DeletedFinalStateUnknown in k8s OnDelete
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/service.go
  libbeat/common/kubernetes/watcher.go
Labels: Team:Integrations, [zube]: In Review, backport

#23331 [Filebeat] Fix malformed IP address in Cisco ASA test logs
  x-pack/filebeat/module/cisco/asa/test/sample.log
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/sample.log
  x-pack/filebeat/module/cisco/ftd/test/sample.log-expected.json
Labels: Filebeat, Team:Security-External Integrations

#23416 docs: Prepare Changelog for 7.10.2
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Automation, automation, docs, in progress, release

#23420 Cherry-pick #21065 to 7.x: add support for multiple regions
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/config/config.go
  x-pack/functionbeat/config/config_test.go
  x-pack/functionbeat/manager/aws/template_builder.go
Labels: Team:Services, [zube]: In Review, backport

#23474 Cherry-pick #23331 to 7.x: [Filebeat] Fix malformed IP address in Cisco ASA test logs
  x-pack/filebeat/module/cisco/asa/test/sample.log
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/sample.log
  x-pack/filebeat/module/cisco/ftd/test/sample.log-expected.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#23475 Cherry-pick #23331 to 7.11: [Filebeat] Fix malformed IP address in Cisco ASA test logs
  x-pack/filebeat/module/cisco/asa/test/sample.log
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/sample.log
  x-pack/filebeat/module/cisco/ftd/test/sample.log-expected.json
Labels: Team:Security-External Integrations, [zube]: Inbox, backport

#23483 [CI] Use branches instead all
  .ci/jobs/beats-schedule-weekly.yml
Labels: Team:Automation, automation, ci

#23476 Forward port 7.10.2 changelog to 7.x
  CHANGELOG.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#23437 [Filebeat][httpjson] Adding possibility to use first_event in cursor context
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/internal/v2/request.go
  x-pack/filebeat/input/httpjson/internal/v2/request_test.go
  x-pack/filebeat/input/httpjson/internal/v2/transform.go
  x-pack/filebeat/input/httpjson/internal/v2/transform_test.go
  x-pack/filebeat/input/httpjson/internal/v2/value_tpl.go
  x-pack/filebeat/input/httpjson/internal/v2/value_tpl_test.go
Labels: Filebeat, Team:Security-External Integrations, enhancement

#23481 Remove duplicate line from the reference config
  auditbeat/auditbeat.reference.yml
  auditbeat/module/file_integrity/_meta/config.yml.tmpl
  x-pack/auditbeat/auditbeat.reference.yml
Labels: Auditbeat, Team:Security-External Integrations, enhancement, review

#23330 [Rate limit processor] Add counter metric for dropped events
  CHANGELOG.next.asciidoc
  libbeat/processors/ratelimit/docs/rate_limit.asciidoc
  libbeat/processors/ratelimit/rate_limit.go
  libbeat/processors/ratelimit/rate_limit_test.go
Labels: Team:Platforms, needs_backport, review, test-plan, v7.12.0, v8.0.0

#23157 add tcp flags to aws/vpcflow fileset
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/module/aws/vpcflow/_meta/fields.yml
  x-pack/filebeat/module/aws/vpcflow/ingest/pipeline.yml
  x-pack/filebeat/module/aws/vpcflow/test/custom-transit-gateway.log-expected.json
  x-pack/filebeat/module/aws/vpcflow/test/tcp-flag-sequence.log
  x-pack/filebeat/module/aws/vpcflow/test/tcp-flag-sequence.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, enhancement, needs_backport

#23472 Cherry-pick to 7.11: [docs] Update misleading phrasing in filebeat's logging.metrics.enabled docs (#23373)
  libbeat/docs/loggingconfig.asciidoc
Labels: Team:Docs, backport

#23471 Cherry-pick to 7.x: [docs] Update misleading phrasing in filebeat's logging.metrics.enabled docs (#23373)
  libbeat/docs/loggingconfig.asciidoc
Labels: Team:apm, backport

#23470 Cherry-pick to master: [docs] Update misleading phrasing in filebeat's logging.metrics.enabled docs (#23373)
  libbeat/docs/loggingconfig.asciidoc
Labels: Team:Docs, backport

#23493 [7.x] [Rate limit processor] Add counter metric for dropped events (#23330)
  CHANGELOG.next.asciidoc
  libbeat/processors/ratelimit/docs/rate_limit.asciidoc
  libbeat/processors/ratelimit/rate_limit.go
  libbeat/processors/ratelimit/rate_limit_test.go
Labels: Team:Integrations, backport

#23478 [Filebeat][httpjson] Allow for custom encoders and decoders
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/internal/v2/config_request.go
  x-pack/filebeat/input/httpjson/internal/v2/config_response.go
  x-pack/filebeat/input/httpjson/internal/v2/encoding.go
  x-pack/filebeat/input/httpjson/internal/v2/input_manager.go
  x-pack/filebeat/input/httpjson/internal/v2/pagination.go
  x-pack/filebeat/input/httpjson/internal/v2/request.go
Labels: Filebeat, Team:Security-External Integrations, enhancement

#23487 [CI] Run mandatory stages when only x-pack changes on branches/tags
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, ci

#23411 [Packetbeat] Fix SIP parser logic related to line length check
  CHANGELOG.next.asciidoc
  packetbeat/protos/sip/parser.go
  packetbeat/tests/system/golden/sip-expected.json
  packetbeat/tests/system/golden/sip_authenticated_register-expected.json
Labels: Packetbeat, Team:Security-External Integrations, bug

#23485 Cherry-pick #23327 to 7.x: Update default config in windows.yml
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/_meta/config.yml
  metricbeat/modules.d/windows.yml.disabled
Labels: Team:Platforms, [zube]: In Review, backport

#23486 Cherry-pick #23327 to 7.11: Update default config in windows.yml
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/_meta/config.yml
  metricbeat/modules.d/windows.yml.disabled
Labels: Team:Platforms, [zube]: In Review, backport

#23490 Fix flaky tests for Metricbeat on Windows 2008 R2
  metricbeat/Jenkinsfile.yml
Labels: Team:Integrations, windows-2008

#23500 Cherry-pick to 7.10: [CI] Run mandatory stages when only x-pack changes on branches/tags (#23487)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23468 Update awsfargate documentation
  x-pack/metricbeat/module/awsfargate/task_stats/_meta/docs.asciidoc
Labels: Team:Platforms, needs_backport

#23354 chore: update test environments for 7.10.2
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Automation, automation, release

#23355 chore: Update version to 7.10.3
  libbeat/version/version.go
Labels: Team:Automation, automation, release

#23509 Cherry-pick #23468 to 7.x: Update awsfargate documentation
  x-pack/metricbeat/module/awsfargate/task_stats/_meta/docs.asciidoc
Labels: Team:Platforms, [zube]: In Review, backport

#23510 Cherry-pick #23468 to 7.11: Update awsfargate documentation
  x-pack/metricbeat/module/awsfargate/task_stats/_meta/docs.asciidoc
Labels: Team:Platforms, [zube]: In Review, backport

#23477 Forward port 7.10.2 changelog to master
  CHANGELOG.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#23504 [CI] Async mode for weekly tasks
  .ci/schedule-weekly.groovy
Labels: Team:Automation, automation, ci

#23463 [Elastic Agent] elastic-agent install -f should reinstall. closes #21990
  x-pack/elastic-agent/pkg/agent/cmd/install.go
Labels: Team:Ingest Management, bug, v7.12.0

#23494 Cherry-pick #23157 to 7.x: add tcp flags to aws/vpcflow fileset
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/aws/fields.go
  x-pack/filebeat/module/aws/vpcflow/_meta/fields.yml
  x-pack/filebeat/module/aws/vpcflow/ingest/pipeline.yml
  x-pack/filebeat/module/aws/vpcflow/test/custom-transit-gateway.log-expected.json
  x-pack/filebeat/module/aws/vpcflow/test/tcp-flag-sequence.log
  x-pack/filebeat/module/aws/vpcflow/test/tcp-flag-sequence.log-expected.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#23514 [Elastic Agent] Capture the rollover files for logging
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
Labels: Team:Agent, Team:Ingest Management

#23094 Bug: Set netflow event.created to use current timestamp
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/netflow/convert.go
  x-pack/filebeat/input/netflow/netflow_test.go
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Barracuda-extended-uniflow-template-256.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Barracuda-firewall.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Mikrotik-RouterOS-6.39.2.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Netscaler-with-variable-length-fields.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Nokia-BRAS.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-OpenBSD-pflow.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Procera.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-VMware-virtual-distributed-switch.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-YAF-basic-with-applabel.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-configured-with-include_flowset_id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-options-template-from-Juniper-MX240-JunOS-15.1-R6-S3.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-vIPtela-with-VPN-id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-1941-K9-release-15.1.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASA-2.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASA.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASR-9000-series-options-template-256.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASR-9000-series-template-260.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASR1001--X.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-NBAR-flowset-262.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-NBAR-options-template-260.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-WLC.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Fortigate-FortiOS-5.2.1.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Fortigate-FortiOS-54x-appid.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-H3C-Netstream-with-varstring.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-H3C.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Huawei-Netstream.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-IE150-IE151.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Palo-Alto-1-flowset-in-large-zero-filled-packet.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Palo-Alto-PAN--OS-with-app--id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Streamcore.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Ubiquiti-Edgerouter-with-MPLS-labels.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-field-layer2segmentid.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-ipt_netflow-reduced-size-encoding.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-macaddress.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-multiple-netflow-exporters.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-nprobe-DPI-L7.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-options-template-with-scope-fields.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-template-with-0-length-fields.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-valid-01.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow9-Juniper-SRX-options-template-with-0-scope-field-length.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/ipfix_cisco.pcap.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/netflow9_e10s_4_7byte_pad.pcap.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/netflow9_ubiquiti_edgerouter.pcap.golden.json
Labels: Filebeat, Team:Security-External Integrations

#23484 [libbeat] Fix Kafka output "circuit breaker is open" errors
  CHANGELOG.next.asciidoc
  go.mod
  libbeat/outputs/kafka/client.go
Labels: Team:Agent, Team:Integrations, bug, libbeat, needs_backport

#23499 Cherry-pick to 7.11: [CI] Run mandatory stages when only x-pack changes on branches/tags (#23487)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23498 Cherry-pick to 7.x: [CI] Run mandatory stages when only x-pack changes on branches/tags (#23487)
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, automation, backport, ci

#23496 [Ingest Manager] Agent fetching DBus service PID fix
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/service.go
Labels: Team:Agent, Team:Ingest Management, bug, v7.11.0

#23507 Cherry-pick #23490 to 7.x: Fix flaky tests for Metricbeat on Windows 2008 R2
  metricbeat/Jenkinsfile.yml
Labels: Team:Integrations, [zube]: In Review, backport, windows-2008

#23508 Cherry-pick #23490 to 7.11: Fix flaky tests for Metricbeat on Windows 2008 R2
  metricbeat/Jenkinsfile.yml
Labels: Team:Integrations, [zube]: In Review, backport, windows-2008

#23519 Cherry-pick to 7.11: docs: Prepare Changelog for 7.10.2 (#23416)
  CHANGELOG.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, backport

#23380 Cherry-pick #23274 to 7.x: Synthetics docker image
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Heartbeat, Team:Uptime, [zube]: In Review, backport

#23396 Cherry-pick #23142 to 7.11: Cherry-pick #22076 to 7.x: Cherry-pick to 7.10: packaging backports
  .ci/packaging.groovy
Labels: Team:Automation, [zube]: In Review, backport

#23515 Cherry-pick #23514 to 7.x: [Elastic Agent] Capture the rollover files for logging
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
Labels: Team:Agent, Team:Ingest Management, [zube]: In Review, backport

#23516 Cherry-pick #23514 to 7.11: [Elastic Agent] Capture the rollover files for logging
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
Labels: Team:Agent, Team:Ingest Management, [zube]: In Review, backport

#23528 Cherry-pick #23484 to 7.x: [libbeat] Fix Kafka output "circuit breaker is open" errors
  CHANGELOG.next.asciidoc
  go.mod
  libbeat/outputs/kafka/client.go
Labels: Team:Agent, Team:Integrations, [zube]: In Review, backport

#23534 [Filebeat] Prevent mutable script params reference from leaking into pipeline
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/suricata/eve/ingest/pipeline.yml
Labels: Filebeat, Team:Security-External Integrations, bug, needs_backport

#23527 Cherry-pick #23484 to 7.11: [libbeat] Fix Kafka output "circuit breaker is open" errors
  CHANGELOG.next.asciidoc
  go.mod
  libbeat/outputs/kafka/client.go
Labels: Team:Agent, Team:Integrations, [zube]: In Review, backport

#23520 Cherry-pick #23094 to 7.x: Bug: Set netflow event.created to use current timestamp
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/netflow/convert.go
  x-pack/filebeat/input/netflow/netflow_test.go
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Barracuda-extended-uniflow-template-256.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Barracuda-firewall.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Mikrotik-RouterOS-6.39.2.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Netscaler-with-variable-length-fields.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Nokia-BRAS.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-OpenBSD-pflow.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Procera.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-VMware-virtual-distributed-switch.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-YAF-basic-with-applabel.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-configured-with-include_flowset_id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-options-template-from-Juniper-MX240-JunOS-15.1-R6-S3.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-vIPtela-with-VPN-id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-1941-K9-release-15.1.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASA-2.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASA.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASR-9000-series-options-template-256.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASR-9000-series-template-260.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASR1001--X.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-NBAR-flowset-262.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-NBAR-options-template-260.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-WLC.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Fortigate-FortiOS-5.2.1.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Fortigate-FortiOS-54x-appid.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-H3C-Netstream-with-varstring.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-H3C.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Huawei-Netstream.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-IE150-IE151.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Palo-Alto-1-flowset-in-large-zero-filled-packet.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Palo-Alto-PAN--OS-with-app--id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Streamcore.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Ubiquiti-Edgerouter-with-MPLS-labels.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-field-layer2segmentid.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-ipt_netflow-reduced-size-encoding.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-macaddress.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-multiple-netflow-exporters.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-nprobe-DPI-L7.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-options-template-with-scope-fields.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-template-with-0-length-fields.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-valid-01.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow9-Juniper-SRX-options-template-with-0-scope-field-length.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/ipfix_cisco.pcap.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/netflow9_e10s_4_7byte_pad.pcap.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/netflow9_ubiquiti_edgerouter.pcap.golden.json
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#23521 [Filebeat] add encode form and decode ndjson to httpjson input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/internal/v2/encoding.go
  x-pack/filebeat/input/httpjson/internal/v2/encoding_test.go
  x-pack/filebeat/input/httpjson/internal/v2/pagination.go
  x-pack/filebeat/input/httpjson/internal/v2/request.go
Labels: Filebeat, Team:Security-External Integrations, enhancement, needs_backport

#23525 Cherry-pick #23496 to 7.x: Agent fetching DBus service PID fix
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/service.go
Labels: Team:Agent, Team:Ingest Management, backport, bug, v7.11.0

#23524 Cherry-pick #23496 to 7.11: Agent fetching DBus service PID fix
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/service.go
Labels: Team:Agent, Team:Ingest Management, backport, bug, v7.11.0

#23538 Recover x-pack Packetbeat packaging in 7.x
  .ci/packaging.groovy
  Jenkinsfile.yml
Labels: :Testing, Team:Automation, Team:Security-External Integrations

#23286 [DOCS] Re-add Stack Monitoring section in elasticsearch module
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/elasticsearch.asciidoc
  metricbeat/module/elasticsearch/_meta/docs.asciidoc
Labels: Stack monitoring, Team:Docs, Team:Integrations, v7.11.0, v7.12.0, v8.0.0

#23356 chore: Update test environments 7.10.3
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: Team:Automation, automation, release

#23480 Fixing flaky tests for windows 7 32bit
  metricbeat/Jenkinsfile.yml
  metricbeat/helper/elastic/elastic_test.go
  metricbeat/mb/testing/data/data_test.go
  metricbeat/module/ceph/cluster_status/cluster_status_test.go
  metricbeat/module/etcd/metrics/_meta/testdata/metrics.plain
  metricbeat/module/etcd/metrics/_meta/testdata/metrics.plain-expected.json
  metricbeat/module/etcd/metrics/metrics_integration_test.go
  metricbeat/module/etcd/metrics/metrics_test.go
  metricbeat/module/kubernetes/apiserver/apiserver_test.go
  metricbeat/module/kubernetes/container/container_test.go
  metricbeat/module/kubernetes/node/node_test.go
  metricbeat/module/kubernetes/proxy/proxy_test.go
  metricbeat/module/kubernetes/scheduler/scheduler_test.go
  metricbeat/module/kubernetes/system/system_test.go
  metricbeat/module/rabbitmq/node/node_test.go
  metricbeat/module/system/test_system.py
  metricbeat/module/vsphere/host/data_test.go
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/metricbeat/module/cockroachdb/status/status_test.go
  x-pack/metricbeat/module/coredns/stats/stats_test.go
  x-pack/metricbeat/module/istio/citadel/citadel_test.go
  x-pack/metricbeat/module/istio/galley/galley_test.go
  x-pack/metricbeat/module/istio/mesh/mesh_test.go
  x-pack/metricbeat/module/istio/proxy/proxy_test.go
  x-pack/metricbeat/module/prometheus/collector/histogram_test.go
Labels: Team:Integrations, windows-10, windows-2008, windows-2012, windows-2016, windows-7, windows-7-32, windows-8

#23553 [CI] Run make notice linting
  Jenkinsfile
Labels: Team:Automation, automation, needs_backport, v7.11.0, v7.12.0

#23558 Cherry-pick #23480 to 7.x: Fixing flaky tests for windows 7 32bit
  metricbeat/Jenkinsfile.yml
  metricbeat/helper/elastic/elastic_test.go
  metricbeat/mb/testing/data/data_test.go
  metricbeat/module/ceph/cluster_status/cluster_status_test.go
  metricbeat/module/etcd/metrics/_meta/testdata/metrics.plain
  metricbeat/module/etcd/metrics/_meta/testdata/metrics.plain-expected.json
  metricbeat/module/etcd/metrics/metrics_integration_test.go
  metricbeat/module/etcd/metrics/metrics_test.go
  metricbeat/module/kubernetes/apiserver/apiserver_test.go
  metricbeat/module/kubernetes/container/container_test.go
  metricbeat/module/kubernetes/node/node_test.go
  metricbeat/module/kubernetes/proxy/proxy_test.go
  metricbeat/module/kubernetes/scheduler/scheduler_test.go
  metricbeat/module/kubernetes/system/system_test.go
  metricbeat/module/rabbitmq/node/node_test.go
  metricbeat/module/system/test_system.py
  metricbeat/module/vsphere/host/data_test.go
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/metricbeat/module/cockroachdb/status/status_test.go
  x-pack/metricbeat/module/coredns/stats/stats_test.go
  x-pack/metricbeat/module/istio/citadel/citadel_test.go
  x-pack/metricbeat/module/istio/galley/galley_test.go
  x-pack/metricbeat/module/istio/mesh/mesh_test.go
  x-pack/metricbeat/module/istio/proxy/proxy_test.go
  x-pack/metricbeat/module/prometheus/collector/histogram_test.go
Labels: :Windows, Team:Integrations, [zube]: In Review, backport, windows-10, windows-2008, windows-2012, windows-2016, windows-7, windows-7-32, windows-8

#23562 Cherry-pick to 7.10: [CI] Run make notice linting (#23553)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#23560 Cherry-pick to 7.x: [CI] Run make notice linting (#23553)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#23561 Cherry-pick to 7.11: [CI] Run make notice linting (#23553)
  Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#23536 Fix typo in input-httpjson.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
Labels: Team:Platforms, needs_backport, review

#23559 Cherry-pick #23480 to 7.11: Fixing flaky tests for windows 7 32bit
  metricbeat/Jenkinsfile.yml
  metricbeat/helper/elastic/elastic_test.go
  metricbeat/mb/testing/data/data_test.go
  metricbeat/module/ceph/cluster_status/cluster_status_test.go
  metricbeat/module/etcd/metrics/_meta/testdata/metrics.plain
  metricbeat/module/etcd/metrics/_meta/testdata/metrics.plain-expected.json
  metricbeat/module/etcd/metrics/metrics_integration_test.go
  metricbeat/module/etcd/metrics/metrics_test.go
  metricbeat/module/kubernetes/apiserver/apiserver_test.go
  metricbeat/module/kubernetes/container/container_test.go
  metricbeat/module/kubernetes/node/node_test.go
  metricbeat/module/kubernetes/proxy/proxy_test.go
  metricbeat/module/kubernetes/scheduler/scheduler_test.go
  metricbeat/module/kubernetes/system/system_test.go
  metricbeat/module/rabbitmq/node/node_test.go
  metricbeat/module/system/test_system.py
  metricbeat/module/vsphere/host/data_test.go
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/metricbeat/module/cockroachdb/status/status_test.go
  x-pack/metricbeat/module/coredns/stats/stats_test.go
  x-pack/metricbeat/module/istio/citadel/citadel_test.go
  x-pack/metricbeat/module/istio/galley/galley_test.go
  x-pack/metricbeat/module/istio/mesh/mesh_test.go
  x-pack/metricbeat/module/istio/proxy/proxy_test.go
  x-pack/metricbeat/module/prometheus/collector/histogram_test.go
Labels: :Windows, Team:Integrations, [zube]: In Review, backport, windows-10, windows-2008, windows-2012, windows-2016, windows-7, windows-7-32, windows-8

#23452 Agent actions token support
  x-pack/elastic-agent/pkg/agent/application/action_store.go
  x-pack/elastic-agent/pkg/agent/application/action_store_test.go
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway_test.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_application.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_unenroll.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_id.go
  x-pack/elastic-agent/pkg/agent/application/inspect_config_cmd.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/state_store.go
  x-pack/elastic-agent/pkg/agent/application/state_store_test.go
  x-pack/elastic-agent/pkg/agent/operation/operation_retryable.go
  x-pack/elastic-agent/pkg/agent/storage/storage.go
  x-pack/elastic-agent/pkg/fleetapi/action.go
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd.go
Labels: Team:Agent, Team:Ingest Management

#23360 Fix docs of MSSQL filebeat module referencing Traefik plus change paths from Linux to MS Windows
  filebeat/docs/modules/mssql.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/mssql/_meta/config.yml
  x-pack/filebeat/module/mssql/_meta/docs.asciidoc
  x-pack/filebeat/modules.d/mssql.yml.disabled
Labels: Filebeat, Team:Services, docs

#23568 [Elastic Agent] Increase checkin grace period.
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/core/server/server.go
Labels: Team:Agent, Team:Ingest Management

#23469 Rename s3 input to aws-s3 input
  CHANGELOG.next.asciidoc
  filebeat/docs/aws-credentials-examples.asciidoc
  filebeat/docs/filebeat-options.asciidoc
  filebeat/docs/modules/cisco.asciidoc
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/filebeat.yml
  x-pack/filebeat/_meta/config/filebeat.inputs.reference.xpack.yml.tmpl
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/include/list.go
  x-pack/filebeat/input/awss3/_meta/fields.yml
  x-pack/filebeat/input/awss3/_meta/s3-input.asciidoc
  x-pack/filebeat/input/awss3/collector.go
  x-pack/filebeat/input/awss3/collector_test.go
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/fields.go
  x-pack/filebeat/input/awss3/ftest/sample1.txt
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/s3_integration_test.go
  x-pack/filebeat/input/default-inputs/inputs.go
  x-pack/filebeat/module/aws/cloudtrail/config/aws-s3.yml
  x-pack/filebeat/module/aws/cloudtrail/manifest.yml
  x-pack/filebeat/module/aws/cloudwatch/config/aws-s3.yml
  x-pack/filebeat/module/aws/cloudwatch/manifest.yml
  x-pack/filebeat/module/aws/ec2/config/aws-s3.yml
  x-pack/filebeat/module/aws/ec2/manifest.yml
  x-pack/filebeat/module/aws/elb/config/aws-s3.yml
  x-pack/filebeat/module/aws/elb/manifest.yml
  x-pack/filebeat/module/aws/s3access/config/aws-s3.yml
  x-pack/filebeat/module/aws/s3access/manifest.yml
  x-pack/filebeat/module/aws/vpcflow/config/input.yml
  x-pack/filebeat/module/aws/vpcflow/manifest.yml
  x-pack/filebeat/module/cisco/_meta/config.yml
  x-pack/filebeat/module/cisco/_meta/docs.asciidoc
  x-pack/filebeat/module/cisco/umbrella/config/input.yml
  x-pack/filebeat/modules.d/cisco.yml.disabled
Labels: Team:Ingest Management, Team:Platforms, needs_backport

#23569 Agent actions token support (#23452)
  x-pack/elastic-agent/pkg/agent/application/action_store.go
  x-pack/elastic-agent/pkg/agent/application/action_store_test.go
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway.go
  x-pack/elastic-agent/pkg/agent/application/fleet_gateway_test.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_application.go
  x-pack/elastic-agent/pkg/agent/application/handler_action_unenroll.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_id.go
  x-pack/elastic-agent/pkg/agent/application/inspect_config_cmd.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/state_store.go
  x-pack/elastic-agent/pkg/agent/application/state_store_test.go
  x-pack/elastic-agent/pkg/agent/operation/operation_retryable.go
  x-pack/elastic-agent/pkg/agent/storage/storage.go
  x-pack/elastic-agent/pkg/fleetapi/action.go
  x-pack/elastic-agent/pkg/fleetapi/checkin_cmd.go
Labels: Team: Ingest, Team:Agent, backport, enhancement

#23495 Cherry-pick #23478 to 7.x: [Filebeat][httpjson] Allow for custom encoders and decoders
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/internal/v2/config_request.go
  x-pack/filebeat/input/httpjson/internal/v2/config_response.go
  x-pack/filebeat/input/httpjson/internal/v2/encoding.go
  x-pack/filebeat/input/httpjson/internal/v2/input_manager.go
  x-pack/filebeat/input/httpjson/internal/v2/pagination.go
  x-pack/filebeat/input/httpjson/internal/v2/request.go
Labels: Team:Security-External Integrations, [zube]: In Review, backport

#23564 Add kubernetes.volume.fs.used.pct field
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/volume/_meta/fields.yml
  metricbeat/module/kubernetes/volume/data.go
  metricbeat/module/kubernetes/volume/volume_test.go
Labels: Team:Integrations, needs_backport, v7.12.0

#23506 Prepare for Golang 1.14.14 release
  .go-version
  CHANGELOG-developer.next.asciidoc
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  journalbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: Team:Agent

#23584 Start doppler consumer loop only after a subscription is configured
  x-pack/metricbeat/module/cloudfoundry/v1.go
Labels: Metricbeat, Team:Integrations, flaky-test, module, needs_backport
