Repository elastic/beats, pull requests merged in 2021-11, with the labels that each got.

#28733 [automation] update elastic stack version for testing 7.15.2-fecae5f4
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28729 Cleanup CHANGELOG.next.asciidoc (master)
  CHANGELOG.next.asciidoc
Labels: Team:Docs, backport-skip

#28730 Cleanup CHANGELOG.next.asciidoc (8.0)
  CHANGELOG.next.asciidoc
Labels: Team:Docs, backport-skip

#28731 Cleanup CHANGELOG.next.asciidoc (7.16)
  CHANGELOG.next.asciidoc
Labels: Team:Docs, backport-skip

#28728 No changelog for 8.0.0-beta1
  CHANGELOG.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#28735 Skip generator tests
  Jenkinsfile.yml
Labels: backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane

#28727 Fix changelog entry for #28354
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
Labels: Team:Security-External Integrations, backport-v8.0.0, backport-v7.16.0

#28745 [heartbeat][docs] Fix markdown bugs in browser/http docs
  heartbeat/docs/monitors/monitor-browser.asciidoc
  heartbeat/docs/monitors/monitor-http.asciidoc
Labels: bug, docs, Heartbeat, Team:Uptime, v7.16.0, backport-v7.15.0, backport-v7.16.0

#28590 Add request id to HTTP transactions to allow tracking.
  x-pack/elastic-agent/pkg/remote/client.go
  x-pack/elastic-agent/pkg/remote/client_test.go
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane

#28742 Remove multiline entries (8.0)
  CHANGELOG.next.asciidoc
Labels: Team:Docs, backport-skip

#28743 Remove multiline entries (master)
  CHANGELOG.next.asciidoc
Labels: Team:Docs, backport-skip

#28744 Remove multiline entries (7.16)
  CHANGELOG.next.asciidoc
Labels: Team:Docs, backport-skip

#28752 [automation] update elastic stack version for testing 7.15.2-5325c15b
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28715 chore(ci): disable E2E tests in Beats
  .ci/packaging.groovy
  Jenkinsfile
Labels: Team:Automation, backport-v7.15.0, backport-v7.16.0

#28480 CI: remove journalbeat references from the CI
  Jenkinsfile.yml
  journalbeat/Jenkinsfile.yml
Labels: backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane

#28151 add options to configure k8s client qps/burst
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/config.go
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
  libbeat/common/kubernetes/options.go
  libbeat/common/kubernetes/util.go
  libbeat/docs/shared-autodiscover.asciidoc
  libbeat/processors/add_kubernetes_metadata/config.go
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/_meta/config.yml
  metricbeat/module/kubernetes/event/config.go
  metricbeat/module/kubernetes/event/event.go
  metricbeat/module/kubernetes/util/kubernetes.go
  metricbeat/modules.d/kubernetes.yml.disabled
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/config.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/kubernetes.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetesleaderelection/config.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetesleaderelection/kubernetes_leaderelection.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetessecrets/config.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetessecrets/kubernetes_secrets.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetessecrets/kubernetes_secrets_test.go
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Integrations, backport-skip

#28754 [Filebeat] Update Oracle release to GA
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/oracle.asciidoc
  x-pack/filebeat/module/oracle/_meta/docs.asciidoc
  x-pack/filebeat/module/oracle/database_audit/_meta/fields.yml
  x-pack/filebeat/module/oracle/database_audit/ingest/pipeline.yml
  x-pack/filebeat/module/oracle/fields.go
Labels: Team:Security-External Integrations, backport-v8.0.0, backport-v7.16.0

#28675 Update standalone agent manifest conditions and scheduler and controllermanager default hosts
  CHANGELOG.next.asciidoc
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
Labels: bug, Team:Integrations, backport-v8.0.0, backport-v7.16.0

#28705 [libbeat] Allow fingerprint processor to read @timestamp
  CHANGELOG.next.asciidoc
  libbeat/processors/fingerprint/docs/fingerprint.asciidoc
  libbeat/processors/fingerprint/errors.go
  libbeat/processors/fingerprint/fingerprint.go
  libbeat/processors/fingerprint/fingerprint_test.go
Labels: bug, review, libbeat, :Processors, Team:Security-External Integrations, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0

#28774 [Heartbeat] Stop logging sensitive params
  CHANGELOG.next.asciidoc
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
Labels: bug, Heartbeat, Team:Uptime, v7.16.0, backport-v7.16.0

#28085 name all k8s workqueue
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/node.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/service.go
  libbeat/common/kubernetes/watcher.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  metricbeat/module/kubernetes/event/event.go
  metricbeat/module/kubernetes/util/kubernetes.go
Labels: Team:Integrations, backport-skip

#28777 [automation] update elastic stack version for testing 7.15.2-54cb1d1b
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28528 Fix metricbeat magefile to generate metricbeat/include/fields.go and …
  dev-tools/mage/fields.go
  metricbeat/docs/fields.asciidoc
  metricbeat/include/fields/fields.go
  metricbeat/magefile.go
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_pod/_meta/fields.yml
Labels: Team:Integrations

#28781 Fixup to remove uneeded 8.0 comment from GenerateK8s metadata
  libbeat/common/kubernetes/metadata/pod.go
Labels: bug, Team:Integrations, backport-v8.0.0, backport-skip

#28787 Convert required fields to string in embeddedConfig recursively
  libbeat/dashboards/modify_json.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#28725 Change proxy_url from url.URL to string
  CHANGELOG.next.asciidoc
  x-pack/libbeat/common/aws/credentials.go
Labels: Team:Integrations, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0

#28716 Upgrade prometheus library
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  libbeat/tests/docker/docker.go
  metricbeat/module/docker/event/event_integration_test.go
  x-pack/dockerlogbeat/magefile.go
Labels: Team:Integrations, backport-skip

#28779 auditbeat/module/file_integrity: recompile flatbuffers with flatc v2.0.0
  auditbeat/module/file_integrity/flatbuffers.go
  auditbeat/module/file_integrity/schema/Action.go
  auditbeat/module/file_integrity/schema/Event.go
  auditbeat/module/file_integrity/schema/Hash.go
  auditbeat/module/file_integrity/schema/Metadata.go
  auditbeat/module/file_integrity/schema/Source.go
  auditbeat/module/file_integrity/schema/Type.go
Labels: cleanup, Team:Security-External Integrations, backport-v8.0.0

#28786 licenses: Add Elastic License 2.0 (`Elasticv2`)
  NOTICE.txt
  dev-tools/cmd/license/license_generate.go
  dev-tools/mage/fmt.go
  go.mod
  go.sum
  licenses/ELASTIC-LICENSE-2.0-header.txt
  licenses/ELASTIC-LICENSE-2.0.txt
  licenses/license_header.go
Labels: enhancement, v8.0.0, Team:apm, backport-v8.0.0

#28807 Cleanup CHANGELOG.next.asciidoc (7.15)
  CHANGELOG.next.asciidoc
Labels: Team:Docs

#28363 Update latest to 8.x release and run tests against it
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  libbeat/tests/system/idxmgmt.py
  libbeat/tests/system/test_cmd_setup_index_management.py
  testing/environments/next-major.yml
Labels: Team:Elastic-Agent-Data-Plane

#28080 Spelling
  auditbeat/module/file_integrity/eventreader_test.go
  auditbeat/module/file_integrity/fileinfo_windows.go
  dev-tools/ecs-migration.yml
  dev-tools/jenkins_release.sh
  dev-tools/mage/gotest_test.go
  dev-tools/mage/integtest.go
  dev-tools/mage/kubernetes/kubectl.go
Labels: Team:Security-External Integrations, backport-v8.0.0, backport-v7.16.0

#28623 Deprecate log input in favour of filestream
  CHANGELOG.next.asciidoc
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/_meta/config/filebeat.inputs.yml.tmpl
  filebeat/docs/inputs/input-log.asciidoc
  filebeat/filebeat.reference.yml
  filebeat/filebeat.yml
  filebeat/input/log/input.go
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/filebeat.yml
Labels: backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane

#28818 Filebeat: Error on startup for unconfigured module
  filebeat/beater/filebeat.go
  filebeat/fileset/modules.go
Labels: review, Team:Security-External Integrations, backport-v8.0.0

#28772 Mark logging.ecs and json as deprecated
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/logging.reference.yml.tmpl
  libbeat/docs/loggingconfig.asciidoc
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: docs, v7.16.0, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane

#28573 Force ECS and JSON logging for libbeat/logp
  CHANGELOG-developer.next.asciidoc
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  auditbeat/tests/system/test_file_integrity.py
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/logging.reference.yml.tmpl
  libbeat/docs/loggingconfig.asciidoc
  libbeat/logp/config.go
  libbeat/logp/core.go
  libbeat/logp/core_test.go
  libbeat/logp/encoding.go
  libbeat/logp/options.go
  libbeat/tests/system/test_logging.py
  libbeat/tests/system/test_template.py
  metricbeat/metricbeat.reference.yml
  metricbeat/module/elasticsearch/test_elasticsearch.py
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/elastic-agent/_meta/config/common.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/common.reference.p2.yml.tmpl
  x-pack/elastic-agent/_meta/elastic-agent.yml
  x-pack/elastic-agent/elastic-agent.reference.yml
  x-pack/elastic-agent/elastic-agent.yml
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: enhancement, libbeat, breaking change, v8.0.0, backport-skip, Team:Elastic-Agent-Control-Plane

#28827 Osquerybeat: Fix restart flags after previously bad config
  x-pack/osquerybeat/beater/osquery_runner.go
Labels: bug, Team:Asset Mgt, v7.16.0, backport-v7.16.0

#28832 [automation] update elastic stack version for testing 7.15.2-e203d324
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28094 [Metricbeat] upgrade flatbuffers to 1.12.1
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Integrations, backport-v7.15.0, backport-v7.16.0

#28814 Deprecate generating custom Beats
  CHANGELOG-developer.next.asciidoc
  docs/devguide/creating-beat-from-metricbeat.asciidoc
  docs/devguide/newbeat.asciidoc
  generator/common/beatgen/beatgen.go
  libbeat/docs/communitybeats.asciidoc
Labels: backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane

#28812 Revert "chore(ci): disable E2E tests in Beats (#28715)"
  .ci/packaging.groovy
  Jenkinsfile
Labels: Team:Automation, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0

#28836 chore: upload files to Google Storage when they exist
  Jenkinsfile
Labels: Team:Automation, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0

#28850 Remove the now deprecated appsearch module from metricbeat
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/appsearch.asciidoc
  metricbeat/docs/modules/appsearch/stats.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/appsearch/_meta/Dockerfile
  x-pack/metricbeat/module/appsearch/_meta/config.yml
  x-pack/metricbeat/module/appsearch/_meta/docker-entrypoint-dependencies.sh
  x-pack/metricbeat/module/appsearch/_meta/docs.asciidoc
  x-pack/metricbeat/module/appsearch/_meta/fields.yml
  x-pack/metricbeat/module/appsearch/doc.go
  x-pack/metricbeat/module/appsearch/docker-compose.yml
  x-pack/metricbeat/module/appsearch/fields.go
  x-pack/metricbeat/module/appsearch/stats/_meta/data.json
  x-pack/metricbeat/module/appsearch/stats/_meta/docs.asciidoc
  x-pack/metricbeat/module/appsearch/stats/_meta/fields.yml
  x-pack/metricbeat/module/appsearch/stats/_meta/test/required.stats.json
  x-pack/metricbeat/module/appsearch/stats/_meta/test/stats.json
  x-pack/metricbeat/module/appsearch/stats/data.go
  x-pack/metricbeat/module/appsearch/stats/data_test.go
  x-pack/metricbeat/module/appsearch/stats/stats.go
  x-pack/metricbeat/module/appsearch/stats/stats_integration_test.go
  x-pack/metricbeat/module/appsearch/test_appsearch.py
  x-pack/metricbeat/modules.d/appsearch.yml.disabled
Labels: Team:Integrations, cleanup, backport-v8.0.0

#28790 Add crawler metrics into the stats metricset for Enterprise Search
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/enterprisesearch/_meta/Dockerfile
  x-pack/metricbeat/module/enterprisesearch/docker-compose.yml
  x-pack/metricbeat/module/enterprisesearch/fields.go
  x-pack/metricbeat/module/enterprisesearch/stats/_meta/fields.yml
  x-pack/metricbeat/module/enterprisesearch/stats/_meta/testdata/stats.json
  x-pack/metricbeat/module/enterprisesearch/stats/_meta/testdata/stats.json-expected.json
  x-pack/metricbeat/module/enterprisesearch/stats/data.go
Labels: enhancement, Metricbeat, Team:Integrations, backport-v8.0.0

#28848 Osquerybeat: Improve osquery client connect code. Update config_refresh to 60 seconds.
  x-pack/osquerybeat/internal/osqd/args.go
  x-pack/osquerybeat/internal/osqdcli/client.go
  x-pack/osquerybeat/internal/osqdcli/retry.go
  x-pack/osquerybeat/internal/osqdcli/retry_test.go
Labels: bug, cleanup, Team:Asset Mgt, v7.16.0, backport-v7.16.0

#28861 [automation] update elastic stack version for testing 7.15.2-616feb9e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28817 Remove Docker input from Filebeat
  CHANGELOG.next.asciidoc
  filebeat/docs/filebeat-options.asciidoc
  filebeat/docs/inputs/input-docker.asciidoc
  filebeat/include/list.go
  filebeat/input/docker/config.go
  filebeat/input/docker/input.go
  filebeat/input/docker/input_test.go
  filebeat/tests/system/test_registrar.py
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane

#28521 allows disable pod events enrichment with deployment name
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  libbeat/common/kubernetes/metadata/config.go
  libbeat/common/kubernetes/metadata/metadata.go
  libbeat/common/kubernetes/metadata/pod.go
  libbeat/common/kubernetes/metadata/pod_test.go
  libbeat/docs/shared-autodiscover.asciidoc
  libbeat/processors/add_kubernetes_metadata/indexers_test.go
  metricbeat/module/kubernetes/util/kubernetes.go
Labels: Team:Integrations, backport-skip

#28810 [Release] Update version to 7.15.3
  libbeat/version/version.go
Labels: release, Team:Automation

#28866 docs: Prepare Changelog for 7.15.2
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, Team:Docs

#28739 [Heartbeat] Decode gzip content when content encoding header is specified
  heartbeat/hbtest/hbtestutil.go
  heartbeat/monitors/active/http/http_test.go
  heartbeat/monitors/active/http/simple_transp.go
Labels: bug, Heartbeat, Team:Uptime, v8.0.0, backport-skip

#28800 Add support in aws-s3 input for s3 notification from SNS to SQS
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/_meta/terraform/README.md
  x-pack/filebeat/input/awss3/_meta/terraform/main.tf
  x-pack/filebeat/input/awss3/_meta/terraform/outputs.tf
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/sqs_s3_event.go
  x-pack/filebeat/input/awss3/sqs_s3_event_test.go
  x-pack/filebeat/input/awss3/sqs_test.go
Labels: Team:Integrations, backport-v8.0.0

#28871 Forward-port 7.15.2 changelog to 7.16
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: backport, Team:Docs, backport-skip

#28876 [automation] update elastic stack version for testing 7.15.2-dab700a8
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28879 Forward port 7.15.2 changelog to 8.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: backport, Team:Docs, backport-skip

#28872 fix: use array length properly
  Jenkinsfile
Labels: Team:Automation, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0

#28882 Forward port 8.0.0-beta 1 and 7.15.2 changelogs to master
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: backport, Team:Docs, backport-skip

#28881 Revert "[Release] update version (#28810)"
  libbeat/version/version.go
Labels: Team:Integrations

#28888 Remove reference to Beat generators from README.md
  README.md
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#28670 Add how to for testing filebeat on kubernetes; minor docs adjustments
  filebeat/_meta/test/docs/01_playground/filebeat.yaml
  filebeat/_meta/test/docs/testing.md
  metricbeat/docs/autodiscover-hints.asciidoc
  metricbeat/docs/autodiscover-kubernetes-config.asciidoc
  metricbeat/module/kubernetes/_meta/test/docs/01_playground/ek_stack.yaml
  metricbeat/module/kubernetes/_meta/test/docs/README.md
Labels: Team:Integrations, backport-skip

#28853 [heartbeat][agent] Remove unnecessary cups dependency
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: bug, Heartbeat, Team:Uptime, v7.16.0, backport-v7.16.0

#28580 x-pack/auditbeat/tracing: fix invalid span in array punning
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/tracing/decoder.go
Labels: bug, Team:Security-External Integrations, backport-v7.16.0, 8.0-candidate

#28868 Enhance add_kubernetes_metadata matcher
  CHANGELOG.next.asciidoc
  filebeat/processor/add_kubernetes_metadata/matchers.go
  filebeat/processor/add_kubernetes_metadata/matchers_test.go
  libbeat/processors/add_kubernetes_metadata/config.go
  libbeat/processors/add_kubernetes_metadata/config_test.go
  libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc
Labels: enhancement, Team:Integrations, backport-skip

#28903 [automation] update elastic stack version for testing 7.15.2-f9b0a84b
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28907 Limit MBP branch discovery
  .ci/jobs/beats.yml
Labels: Team:Observability, Team:Automation, backport-skip

#28809 docs: update docs versions 7.15.2
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#28826 Get AIX to build and run Metricbeat
  dev-tools/mage/crossbuild.go
  dev-tools/mage/pkgtypes.go
  dev-tools/mage/platforms.go
  dev-tools/mage/pytest.go
  dev-tools/packaging/packages.yml
  libbeat/metric/system/cpu/cpu.go
  libbeat/metric/system/process/process.go
  libbeat/tests/system/requirements_aix.txt
  metricbeat/module/system/load/load.go
  metricbeat/module/system/load/load_test.go
  metricbeat/module/system/memory/memory.go
  metricbeat/module/system/network/network.go
  metricbeat/module/system/network/network_test.go
  metricbeat/module/system/process/process.go
  metricbeat/module/system/process/process_test.go
  metricbeat/module/system/process_summary/process_summary.go
Labels: enhancement, Team:Integrations, backport-v8.0.0

#28546 Fix behavior of hostfs under agent
  libbeat/metric/system/cgroup/util.go
  libbeat/paths/paths.go
  metricbeat/module/linux/conntrack/conntrack.go
  metricbeat/module/linux/ksm/ksm.go
  metricbeat/module/linux/linux.go
  metricbeat/module/linux/pageinfo/pageinfo.go
  metricbeat/module/linux/pressure/pressure.go
  metricbeat/module/linux/rapl/rapl.go
  metricbeat/module/linux/rapl/rapl_test.go
  metricbeat/module/system/_meta/config.yml
  metricbeat/module/system/core/core.go
  metricbeat/module/system/cpu/cpu.go
  metricbeat/module/system/diskio/diskio.go
  metricbeat/module/system/entropy/entropy.go
  metricbeat/module/system/memory/memory.go
  metricbeat/module/system/process/process.go
  metricbeat/module/system/raid/raid.go
  metricbeat/module/system/system.go
  metricbeat/modules.d/system.yml
Labels: bug, Team:Integrations, backport-v8.0.0, backport-v7.16.0

#28811 chore: Update test enviroments after 7.15.2 release
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation, Team:Elastic-Agent-Data-Plane

#28958 [automation] update elastic stack version for testing 7.15.3-b30acc1a
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28919 Update reference to github.com/Azure/azure-event-hubs-go
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Integrations, backport-v8.0.0, backport-v7.16.0

#28960 typo in aws.rds.write_iops field in processor
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/rds/manifest.yml
Labels: Team:Platforms, backport-v8.0.0

#28933 Fix failing tests on libbeat/common/fmtstr
  libbeat/common/fmtstr/formatevents_test.go
  libbeat/common/fmtstr/formattimestamp_test.go
Labels: needs_team, backport-v8.0.0, backport-v7.16.0

#28963 fix getProviderFromDomain function, move from integration test
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/input_test.go
Labels: Team:Platforms, backport-v8.0.0

#28938 [Heartbeat] Allow dup3 and dup syscalls
  CHANGELOG.next.asciidoc
  heartbeat/security/security.go
Labels: bug, Heartbeat, Team:Uptime, v7.16.0, backport-v7.16.0

#28902 Add config option to attach pprof endpoints to http socket
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/http.reference.yml.tmpl
  libbeat/api/routes.go
  libbeat/cmd/instance/beat.go
  libbeat/docs/http-endpoint.asciidoc
  libbeat/tests/system/test_http.py
  libbeat/tests/system/test_http_pprof.py
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: enhancement, backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Control-Plane

#28926 libbeat: add support for defining analyzers in-line in fields.yml files
  CHANGELOG.next.asciidoc
  docs/devguide/fields-yml.asciidoc
  libbeat/mapping/field.go
  libbeat/mapping/field_test.go
  libbeat/template/load_test.go
  libbeat/template/processor.go
  libbeat/template/processor_test.go
  libbeat/template/template.go
  libbeat/template/template_test.go
  libbeat/tests/system/template/template.go
Labels: enhancement, libbeat, Team:Security-External Integrations, backport-v8.0.0, 8.1-candidate

#28483 x-pack/winlogbeat/module/powershell: don't split tokens on hyphen
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/powershell/_meta/fields.yml
  x-pack/winlogbeat/module/powershell/fields.go
Labels: bug, Team:Security-External Integrations, backport-v8.0.0, 8.1-candidate

#28980 Add beta label to browser monitors
  heartbeat/docs/monitors/monitor-browser.asciidoc
Labels: bug, docs, Heartbeat, Team:Uptime, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0

#28908 Initialise beat early
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
  libbeat/cmd/instance/beat_integration_test.go
  libbeat/cmd/instance/testdata/mockbeat.yml
Labels: review, backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane

#28994 [mergify] notify the backport policy for open PRs
  .mergify.yml
Labels: automation, Team:Automation, backport-skip

#28909 Update gosigar package
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/fields.go
  metricbeat/module/system/filesystem/_meta/fields.yml
  metricbeat/module/system/filesystem/filesystem.go
  metricbeat/module/system/filesystem/helper.go
  metricbeat/module/system/filesystem/helper_test.go
  metricbeat/module/system/fsstat/fsstat.go
Labels: Team:Integrations, backport-v8.0.0, backport-v7.16.0

#28971 Add SASL/SCRAM support to the Kafka test container
  libbeat/outputs/kafka/kafka.go
  libbeat/outputs/kafka/kafka_integration_test.go
  testing/environments/docker/kafka/Dockerfile
  testing/environments/docker/kafka/README.md
  testing/environments/docker/kafka/certs/broker-cert
  testing/environments/docker/kafka/certs/broker-cert-signed
  testing/environments/docker/kafka/certs/broker.keystore.jks
  testing/environments/docker/kafka/certs/ca-cert
  testing/environments/docker/kafka/certs/ca-cert.srl
  testing/environments/docker/kafka/certs/ca-key
  testing/environments/docker/kafka/certs/client.truststore.jks
  testing/environments/docker/kafka/run.sh
Labels: cleanup, backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane

#29007 [automation] update elastic stack version for testing 6.8.21-89aea7c7
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28995 Revert usageDetails api version to 2019-01-01
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/metricbeat/module/azure/billing/billing.go
  x-pack/metricbeat/module/azure/billing/client.go
  x-pack/metricbeat/module/azure/billing/client_test.go
  x-pack/metricbeat/module/azure/billing/data.go
  x-pack/metricbeat/module/azure/billing/data_test.go
  x-pack/metricbeat/module/azure/billing/mock_service.go
  x-pack/metricbeat/module/azure/billing/service.go
Labels: Team:Integrations, backport-v8.0.0, backport-v7.16.0

#29019 [automation] update elastic stack version for testing 6.8.21-40a8ccf4
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29018 [automation] update elastic stack version for testing 7.15.3-a2dc0d3c
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28946 [filebeat][s3] Add custom parsing script for S3 notifications
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_benchmark_test.go
  x-pack/filebeat/input/awss3/script.go
  x-pack/filebeat/input/awss3/script_jss3event_v2.go
  x-pack/filebeat/input/awss3/script_jss3event_v2_test.go
  x-pack/filebeat/input/awss3/script_session.go
  x-pack/filebeat/input/awss3/script_session_test.go
  x-pack/filebeat/input/awss3/sqs_s3_event.go
  x-pack/filebeat/input/awss3/sqs_s3_event_test.go
Labels: Team:Integrations, Team:Security-External Integrations, backport-v8.0.0, backport-v7.16.0

#29045 [automation] update elastic stack version for testing 7.15.3-d16f4bc8
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28964 [mergify] report open backported PRs once a week
  .mergify.yml
Labels: automation, Team:Automation, backport-skip

#29042 [automation] update elastic stack version for testing 6.8.21-ff3c5676
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29050 ci: daily/weekly jobs
  .ci/schedule-daily.groovy
  .ci/schedule-weekly.groovy
Labels: Team:Automation, backport-skip

#28782 Fix Beat module mapping on "info" subkey
  metricbeat/docs/fields.asciidoc
  metricbeat/module/beat/_meta/fields.yml
  metricbeat/module/beat/fields.go
  metricbeat/module/beat/stats/_meta/fields.yml
Labels: bug, Metricbeat, Team:Integrations, backport-v8.0.0

#29016 [Winlogbeat] Fix AccessList & AccessMask processing in security data_stream
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/security/config/winlogbeat-security.js
Labels: bug, Team:Security-External Integrations, backport-v8.0.0, backport-v7.16.0

#28324 x-pack/filebeat/module: add note for default var.input
  filebeat/docs/modules/barracuda.asciidoc
  filebeat/docs/modules/bluecoat.asciidoc
  filebeat/docs/modules/cisco.asciidoc
  filebeat/docs/modules/cylance.asciidoc
  filebeat/docs/modules/f5.asciidoc
  filebeat/docs/modules/fortinet.asciidoc
  filebeat/docs/modules/imperva.asciidoc
  filebeat/docs/modules/infoblox.asciidoc
  filebeat/docs/modules/juniper.asciidoc
  filebeat/docs/modules/microsoft.asciidoc
  filebeat/docs/modules/netscout.asciidoc
  filebeat/docs/modules/proofpoint.asciidoc
  filebeat/docs/modules/radware.asciidoc
  filebeat/docs/modules/snort.asciidoc
  filebeat/docs/modules/sonicwall.asciidoc
  filebeat/docs/modules/sophos.asciidoc
  filebeat/docs/modules/squid.asciidoc
  filebeat/docs/modules/tomcat.asciidoc
  filebeat/docs/modules/zscaler.asciidoc
  x-pack/filebeat/module/barracuda/_meta/docs.asciidoc
  x-pack/filebeat/module/bluecoat/_meta/docs.asciidoc
  x-pack/filebeat/module/cisco/_meta/docs.asciidoc
  x-pack/filebeat/module/cylance/_meta/docs.asciidoc
  x-pack/filebeat/module/f5/_meta/docs.asciidoc
  x-pack/filebeat/module/fortinet/_meta/docs.asciidoc
  x-pack/filebeat/module/imperva/_meta/docs.asciidoc
  x-pack/filebeat/module/infoblox/_meta/docs.asciidoc
  x-pack/filebeat/module/juniper/_meta/docs.asciidoc
  x-pack/filebeat/module/microsoft/_meta/docs.asciidoc
  x-pack/filebeat/module/netscout/_meta/docs.asciidoc
  x-pack/filebeat/module/proofpoint/_meta/docs.asciidoc
  x-pack/filebeat/module/radware/_meta/docs.asciidoc
  x-pack/filebeat/module/snort/_meta/docs.asciidoc
  x-pack/filebeat/module/sonicwall/_meta/docs.asciidoc
  x-pack/filebeat/module/sophos/_meta/docs.asciidoc
  x-pack/filebeat/module/squid/_meta/docs.asciidoc
  x-pack/filebeat/module/tomcat/_meta/docs.asciidoc
  x-pack/filebeat/module/zscaler/_meta/docs.asciidoc
Labels: enhancement, Stalled, Team:Security-External Integrations, backport-v7.16.0

#29062 [automation] update elastic stack version for testing 6.8.21-92088553
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29063 [automation] update elastic stack version for testing 7.15.3-2ab3d0ac
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28927 Remove `logging.files.suffix` option and always use datetime suffixes
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  filebeat/tests/system/filebeat.py
  filebeat/tests/system/test_harvester.py
  filebeat/tests/system/test_input.py
  filebeat/tests/system/test_load.py
  filebeat/tests/system/test_multiline.py
  filebeat/tests/system/test_registrar.py
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/logging.reference.yml.tmpl
  libbeat/common/file/interval_rotator.go
  libbeat/common/file/interval_rotator_test.go
  libbeat/common/file/rotator.go
  libbeat/common/file/rotator_test.go
  libbeat/common/file/trigger.go
  libbeat/docs/loggingconfig.asciidoc
  libbeat/logp/config.go
  libbeat/logp/core.go
  libbeat/logp/core_test.go
  libbeat/outputs/fileout/config.go
  libbeat/outputs/fileout/file.go
  libbeat/tests/system/base.py
  libbeat/tests/system/beat/beat.py
  libbeat/tests/system/test_base.py
  libbeat/tests/system/test_logging.py
  libbeat/tests/system/test_umask.py
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  packetbeat/tests/system/packetbeat.py
  packetbeat/tests/system/test_0002_thrift_basics.py
  packetbeat/tests/system/test_0006_wsgi.py
  winlogbeat/tests/system/test_config.py
  winlogbeat/tests/system/test_wineventlog.py
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/elastic-agent/pkg/agent/operation/monitoring.go
  x-pack/elastic-agent/pkg/core/logger/logger.go
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
  x-pack/elastic-agent/pkg/core/monitoring/beats/monitoring.go
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane

#28998 Add null (`\u0000`) as a valid line terminator
  CHANGELOG.next.asciidoc
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/filebeat.reference.yml
  libbeat/reader/readfile/line_terminator.go
  x-pack/filebeat/filebeat.reference.yml
Labels: enhancement, review, libbeat, backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane

#28700 Fix discovery of Nomad allocations
  CHANGELOG.next.asciidoc
  x-pack/libbeat/common/nomad/watcher.go
  x-pack/libbeat/common/nomad/watcher_test.go
Labels: bug, Team:Integrations, backport-v8.0.0, backport-v7.16.0

#29040 Fix environmental var setup under agent
  libbeat/cmd/instance/metrics/metrics.go
  metricbeat/module/system/system.go
Labels: bug, Team:Integrations

#29076 Remove TestFetch from kinesis metricset
  x-pack/metricbeat/module/aws/kinesis/kinesis_integration_test.go
Labels: Team:Integrations, aws

#28983 Enable pprof for elastic-agent and beats
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/_meta/config/common.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/common.reference.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/elastic-agent.docker.yml.tmpl
  x-pack/elastic-agent/elastic-agent.docker.yml
  x-pack/elastic-agent/elastic-agent.reference.yml
  x-pack/elastic-agent/elastic-agent.yml
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
  x-pack/elastic-agent/pkg/core/monitoring/config/config.go
Labels: enhancement, backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Control-Plane

#29041 [Heartbeat] Log error on dupe monitor ID instead of strict req
  CHANGELOG.next.asciidoc
  heartbeat/beater/heartbeat.go
  heartbeat/monitors/factory.go
  heartbeat/monitors/factory_test.go
  heartbeat/monitors/monitor.go
  heartbeat/monitors/monitor_test.go
Labels: bug, Heartbeat, Team:Uptime, v7.16.0, backport-v8.0.0, backport-v7.16.0

#29085 [automation] update elastic stack version for testing 7.15.3-4c145d2b
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#28993 [Elastic-Agent] IUse itnernal port for local fleet server
  x-pack/elastic-agent/pkg/agent/cmd/enroll.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/configuration/fleet_server.go
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/fleet-server.yml
Labels: bug, v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Control-Plane

#28717 Fix parsing of apache trace log levels
  CHANGELOG.next.asciidoc
  filebeat/module/apache/error/ingest/pipeline.yml
  filebeat/module/apache/error/test/sublevel.log
  filebeat/module/apache/error/test/sublevel.log-expected.json
Labels: Team:Integrations, backport-v8.0.0, backport-v7.16.0

#28870 Remove deprecated `--template` and `--index-policy` flags
  CHANGELOG.next.asciidoc
  auditbeat/tests/system/test_base.py
  filebeat/tests/system/test_base.py
  heartbeat/cmd/root.go
  heartbeat/tests/system/test_base.py
  libbeat/cmd/setup.go
  libbeat/docs/command-reference.asciidoc
  libbeat/tests/system/test_ilm.py
  libbeat/tests/system/test_template.py
  metricbeat/tests/system/test_base.py
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane

#29093 heartbeat: remove w2008 in the CI
  heartbeat/Jenkinsfile.yml
Labels: Heartbeat, Team:Automation, backport-v8.0.0, backport-v7.16.0

#29094 Add `beat` field back to beat.stats
  metricbeat/docs/fields.asciidoc
  metricbeat/module/beat/fields.go
  metricbeat/module/beat/stats/_meta/fields.yml
  metricbeat/module/beat/test_beat.py
Labels: bug, Stack monitoring, needs_team, backport-v8.0.0

#29075 Default to legacy format if JSON template is loaded
  libbeat/docs/template-config.asciidoc
  libbeat/idxmgmt/std.go
  libbeat/template/config.go
  libbeat/tests/system/config/mockbeat.yml.j2
  libbeat/tests/system/test_template.py
Labels: Team:Elastic-Agent-Data-Plane

#28869 Remove deprecated spool queue from Beats
  CHANGELOG-developer.next.asciidoc
  NOTICE.txt
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  go.mod
  go.sum
  heartbeat/heartbeat.reference.yml
  journalbeat/journalbeat.reference.yml
  libbeat/_meta/config/general.reference.yml.tmpl
  libbeat/docs/queueconfig.asciidoc
  libbeat/publisher/includes/includes.go
  libbeat/publisher/pipeline/stress/configs/pipeline/small_spool.yml
  libbeat/publisher/pipeline/stress/stress_test.go
  libbeat/publisher/queue/spool/codec.go
  libbeat/publisher/queue/spool/codec_test.go
  libbeat/publisher/queue/spool/config.go
  libbeat/publisher/queue/spool/consume.go
  libbeat/publisher/queue/spool/inbroker.go
  libbeat/publisher/queue/spool/internal_api.go
  libbeat/publisher/queue/spool/log.go
  libbeat/publisher/queue/spool/module.go
  libbeat/publisher/queue/spool/outbroker.go
  libbeat/publisher/queue/spool/produce.go
  libbeat/publisher/queue/spool/spool.go
  libbeat/publisher/queue/spool/spool_test.go
  libbeat/publisher/queue/spool/timer.go
  libbeat/scripts/cmd/stress_pipeline/main.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/dockerlogbeat/main.go
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane

#28769 Change "filebeat.config.modules.enabled" to "true"
  filebeat/_meta/config/filebeat.global.reference.yml.tmpl
  filebeat/filebeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
Labels: docs, Team:Docs, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0

#29048 Skip config check in autodiscover for duplicated configurations
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/autodiscover.go
  libbeat/autodiscover/autodiscover_test.go
Labels: Team:Integrations, Team:Uptime, backport-v8.0.0, backport-v7.16.0

#29103 override host on statsd metricset
  CHANGELOG.next.asciidoc
  metricbeat/helper/server/udp/udp.go
  x-pack/metricbeat/module/statsd/server/server.go
Labels: Team:Platforms, backport-v8.0.0, backport-v7.16.0

#29095 Use NamedWatcher in Agent's k8s provider
  libbeat/common/kubernetes/watcher.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/node.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/pod.go
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/service.go
Labels: Team:Integrations, backport-skip

#29122 [mergify]: notify conflicts in PRs that are still open
  .mergify.yml
Labels: automation, Team:Automation, backport-skip

#28941 Re-enable tests in aws module
  x-pack/metricbeat/module/aws/billing/billing_integration_test.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_integration_test.go
  x-pack/metricbeat/module/aws/ec2/ec2_integration_test.go
  x-pack/metricbeat/module/aws/kinesis/kinesis_integration_test.go
  x-pack/metricbeat/module/aws/rds/rds_integration_test.go
  x-pack/metricbeat/module/aws/sqs/sqs_integration_test.go
Labels: Team:Integrations, aws

#29106 Fix rds metadata in cloudwatch metricset
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/metadata/rds/rds.go
Labels: Team:Integrations, backport-v8.0.0, backport-v7.16.0

#29134 Remove links to Journalbeat
  libbeat/docs/getting-started.asciidoc
  libbeat/docs/overview.asciidoc
Labels: v8.0.0, Team:Docs, v7.16.0, backport-v8.0.0, backport-v7.16.0

#29143 [automation] update elastic stack version for testing 7.15.3-ba00df8f
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29047 CI: enable AWS cloud testing on a PR basis if changes in certain files
  Jenkinsfile
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
Labels: Team:Automation, backport-v8.0.0, backport-v7.16.0

#29137 Indicate in banner that Journalbeat has been removed in 7.16
  journalbeat/docs/page_header.html
Labels: v8.0.0, needs_team, v7.16.0, v8.1.0

#29148 Added workflow file for builds with macos
  .github/workflows/macos-build.yml
Labels: Team:Automation, backport-v8.0.0, backport-v7.16.0

#29039 Fix agent download timeout values in yaml files
  x-pack/elastic-agent/_meta/config/common.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/common.reference.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/elastic-agent.docker.yml.tmpl
  x-pack/elastic-agent/_meta/elastic-agent.fleet.yml
  x-pack/elastic-agent/_meta/elastic-agent.yml
  x-pack/elastic-agent/elastic-agent.docker.yml
  x-pack/elastic-agent/elastic-agent.reference.yml
  x-pack/elastic-agent/elastic-agent.yml
  x-pack/elastic-agent/pkg/agent/application/configuration_embed.go
Labels: docs, Team:Elastic-Agent, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0, Team:Elastic-Agent-Control-Plane

#29162 [automation] update elastic stack version for testing 6.8.21-f133bac8
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29163 [automation] update elastic stack version for testing 7.15.3-57b973bf
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29156 Workflow for macos
  .github/workflows/macos-build.yml
Labels: needs_team, backport-skip

#29173 [automation] update elastic stack version for testing 7.15.3-e51e78d3
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29107 Fix `decode_json_fields` processor to always add error key
  CHANGELOG.next.asciidoc
  libbeat/processors/actions/decode_json_fields.go
  libbeat/processors/actions/decode_json_fields_test.go
Labels: bug, review, backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane

#29174 Workflow for macos
  .github/workflows/macos-build.yml
Labels: needs_team, backport-skip

#28797 Add note that there is no warranty or support for generator code
  docs/devguide/create-metricset.asciidoc
  docs/devguide/generator-support-note.asciidoc
  docs/devguide/modules-dev-guide.asciidoc
Labels: docs, Team:Docs, v7.16.0, backport-skip

#29191 [automation] update elastic stack version for testing 6.8.21-fa5fd3ab
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29190 winlogbeat/sys/winevent: use reflect IsZero method
  winlogbeat/sys/winevent/event_test.go
  winlogbeat/sys/winevent/maputil.go
Labels: cleanup, Team:Security-External Integrations, backport-v8.0.0, 8.1-candidate

#29152 [Elastic Agent] Add process error handling guidelines
  x-pack/elastic-agent/GUIDELINES.md
Labels: Team:Elastic-Agent, backport-skip

#29155 Change elastic-agent pprof default to false
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/_meta/config/common.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/common.reference.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/elastic-agent.docker.yml.tmpl
  x-pack/elastic-agent/elastic-agent.docker.yml
  x-pack/elastic-agent/elastic-agent.reference.yml
  x-pack/elastic-agent/elastic-agent.yml
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
  x-pack/elastic-agent/pkg/core/monitoring/config/config.go
Labels: configuration, backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Control-Plane
