Repository elastic/beats, pull requests merged in 2022-08, with the labels that each got.

#32556 [automation] update elastic stack version for testing 7.17.6-74b6df3e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32543 Osquerybeat: Add missing data_stream to events in order to support logstash configuration better
  x-pack/osquerybeat/internal/config/config.go
  x-pack/osquerybeat/internal/pub/publisher.go
Labels: enhancement, Team:Asset Mgt, 8.4-candidate, backport-v8.4.0

#32554 Osquerybeat: Upgrade osquery to version 5.4.0
  x-pack/osquerybeat/internal/distro/distro.go
Labels: enhancement, Team:Asset Mgt, v8.4.0, 8.4-candidate, backport-v8.4.0

#32564 [Heartbeat] Limit browser jobs to 2 by default
  CHANGELOG.next.asciidoc
  heartbeat/config/config.go
  heartbeat/scheduler/schedjob_test.go
  heartbeat/scheduler/scheduler.go
  heartbeat/scheduler/scheduler_test.go
Labels: bug, Heartbeat, Team:Uptime, backport-v8.4.0

#32559 fix: use beats profile when running the e2e for Beats PRs
  Jenkinsfile
Labels: ci, Team:Automation, backport-v8.3.0, backport-v7.17.0, backport-v8.4.0

#32573 [automation] update elastic stack version for testing 8.5.0-c54c3404
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32571 [automation] update elastic stack version for testing 8.3.4-9c50d4cb
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32575 [automation] update elastic stack version for testing 8.5.0-7dbc10f8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32536 update dependency elastic/go-structform from v0.0.9 to v0.0.10
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#32580 Add ulimit setting to debian containers in mage build
  CHANGELOG.next.asciidoc
  dev-tools/mage/crossbuild.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#32582 Fix string used to check image name in crossbuild
  dev-tools/mage/crossbuild.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v7.17.0, backport-v8.4.0

#32585 [automation] update elastic stack version for testing 7.17.6-02b91d00
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
  x-pack/elastic-agent/pkg/artifact/download/http/downloader_test.go
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32570 Clarify that at least one fileset must be enabled in a filebeat
  filebeat/docs/getting-started.asciidoc
  filebeat/docs/include/configuring-intro.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v8.4.0

#32604 [automation] update elastic stack version for testing 7.17.6-308858b9
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32605 [automation] update elastic stack version for testing 8.3.4-ce266bfe
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32572 [automation] update elastic stack version for testing 8.4.0-5954f776
  metricbeat/docker-compose.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32601 unique working dir for python system_tests
  libbeat/tests/system/beat/beat.py
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-v8.4.0

#32551 [Auditbeat] Upgrade go-libaudit@f8f7d5c
  NOTICE.txt
  go.mod
  go.sum
Labels: Auditbeat, Team:Security-External Integrations, backport-v8.4.0

#32616 [automation] update elastic stack version for testing 7.17.6-39f8da8e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32614 [automation] update elastic stack version for testing 8.4.0-43c061d1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32615 [automation] update elastic stack version for testing 8.3.4-73c9af3c
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32624 [automation] update elastic stack version for testing 7.17.6-49d2f2df
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32625 [automation] update elastic stack version for testing 8.4.0-4b3e8f6e
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32617 [AWS] Add missing metrics in Transit Gateway module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/transitgateway/_meta/fields.yml
  x-pack/metricbeat/module/aws/transitgateway/manifest.yml
Labels: bug, Team:Cloud-Monitoring

#32542 [Heartbeat] Add functional-ish tests in golang
  CHANGELOG.next.asciidoc
  heartbeat/beater/heartbeat.go
  heartbeat/ecserr/ecserr.go
  heartbeat/hbtestllext/isdefs.go
  heartbeat/monitors/factory.go
  heartbeat/monitors/factory_test.go
  heartbeat/monitors/mocks.go
  heartbeat/monitors/monitor.go
  heartbeat/monitors/monitor_test.go
  heartbeat/monitors/syncpipeclient.go
  heartbeat/monitors/task.go
  heartbeat/monitors/task_test.go
  x-pack/heartbeat/monitors/browser/browser.go
  x-pack/heartbeat/monitors/browser/source/local.go
  x-pack/heartbeat/monitors/browser/source/project.go
  x-pack/heartbeat/monitors/browser/source/zipurl.go
  x-pack/heartbeat/monitors/browser/source/zipurl_test.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
  x-pack/heartbeat/scenarios/basics_test.go
  x-pack/heartbeat/scenarios/framework.go
  x-pack/heartbeat/scenarios/scenarios.go
Labels: bug, Heartbeat, Team:Uptime

#32636 [automation] update elastic stack version for testing 8.3.4-fd43be48
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32635 [automation] update elastic stack version for testing 7.17.6-a65acb36
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32634 [automation] update elastic stack version for testing 8.4.0-96568c7b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32607 Enhance dev-tools/kubernetes to support multi node clusters
  dev-tools/kubernetes/README.md
  dev-tools/kubernetes/Tiltfile
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/filebeat/manifest.debug.yaml
  dev-tools/kubernetes/filebeat/manifest.run.prod.yaml
  dev-tools/kubernetes/filebeat/manifest.run.yaml
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/manifest.debug.multi.yaml
  dev-tools/kubernetes/metricbeat/manifest.debug.yaml
  dev-tools/kubernetes/metricbeat/manifest.run.yaml
Labels: enhancement, Team:Cloudnative-Monitoring

#32643 [automation] update elastic stack version for testing 7.17.6-e11a9305
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32646 [automation] update elastic stack version for testing 8.3.4-b4aa6143
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32645 [automation] update elastic stack version for testing 8.5.0-41aadc32
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32644 [automation] update elastic stack version for testing 8.4.0-9adc8090
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32541 Add entry IDs to the memory queue
  libbeat/publisher/pipeline/client.go
  libbeat/publisher/pipeline/client_test.go
  libbeat/publisher/pipeline/pipeline.go
  libbeat/publisher/pipeline/pipeline_test.go
  libbeat/publisher/pipeline/ttl_batch.go
  libbeat/publisher/queue/diskqueue/benchmark_test.go
  libbeat/publisher/queue/diskqueue/consumer.go
  libbeat/publisher/queue/diskqueue/producer.go
  libbeat/publisher/queue/memqueue/ackloop.go
  libbeat/publisher/queue/memqueue/batchbuf.go
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/memqueue/eventloop.go
  libbeat/publisher/queue/memqueue/internal_api.go
  libbeat/publisher/queue/memqueue/produce.go
  libbeat/publisher/queue/memqueue/queue_test.go
  libbeat/publisher/queue/memqueue/ringbuf.go
  libbeat/publisher/queue/queue.go
  libbeat/publisher/queue/queuetest/producer_cancel.go
  libbeat/publisher/queue/queuetest/queuetest.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#32649 Fix debug mode for dev-tools/kubernetes
  dev-tools/kubernetes/Tiltfile
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/filebeat/manifest.debug.yaml
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/manifest.debug.multi.yaml
  dev-tools/kubernetes/metricbeat/manifest.debug.yaml
Labels: enhancement, Team:Cloudnative-Monitoring

#32611 Fixes to support Go 1.18
  .github/workflows/golangci-lint.yml
  .golangci.yml
  CHANGELOG.next.asciidoc
  dev-tools/templates/.golangci.yml
  libbeat/outputs/kafka/kafka_integration_test.go
  testing/environments/docker/kafka/Dockerfile
  testing/environments/docker/kafka/README.md
  testing/environments/docker/kafka/certs/broker-cert
  testing/environments/docker/kafka/certs/broker-cert-signed
  testing/environments/docker/kafka/certs/broker.keystore.jks
  testing/environments/docker/kafka/certs/ca-cert
  testing/environments/docker/kafka/certs/ca-cert.srl
  testing/environments/docker/kafka/certs/ca-key
  testing/environments/docker/kafka/certs/client.truststore.jks
Labels: Team:Elastic-Agent-Data-Plane

#32653 Update go 1.18 fixes
  .github/workflows/golangci-lint.yml
  .golangci.yml
  CHANGELOG.next.asciidoc
  NOTICE.txt
  dev-tools/templates/.golangci.yml
  go.mod
  go.sum
  libbeat/outputs/kafka/kafka_integration_test.go
  testing/environments/docker/kafka/Dockerfile
  testing/environments/docker/kafka/README.md
  testing/environments/docker/kafka/certs/broker-cert
  testing/environments/docker/kafka/certs/broker-cert-signed
  testing/environments/docker/kafka/certs/broker.keystore.jks
  testing/environments/docker/kafka/certs/ca-cert
  testing/environments/docker/kafka/certs/ca-cert.srl
  testing/environments/docker/kafka/certs/ca-key
  testing/environments/docker/kafka/certs/client.truststore.jks
Labels: needs_team

#32656 [automation] update elastic stack version for testing 7.17.6-9b06d311
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32657 [automation] update elastic stack version for testing 8.4.0-c17572db
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32655 [automation] update elastic stack version for testing 8.3.4-a5e24e15
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32658 [automation] update elastic stack version for testing 8.5.0-60a4c029
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32626 bugfix break infinite loop on aws billing
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/billing/billing.go
Labels: bug, Team:Cloud-Monitoring, backport-v8.4.0

#32652 transform beat.cgroup.memory.mem.usage.bytes to Gauge
  CHANGELOG-developer.next.asciidoc
  libbeat/monitoring/report/log/log.go
Labels: Team:Elastic-Agent-Data-Plane

#32666 [automation] update elastic stack version for testing 8.3.4-adc3e57f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32539 Feature/remove k8s cache
  CHANGELOG.next.asciidoc
  metricbeat/module/kubernetes/_meta/test/stats_summary_multiple_containers.json
  metricbeat/module/kubernetes/container/container.go
  metricbeat/module/kubernetes/container/container_test.go
  metricbeat/module/kubernetes/container/data.go
  metricbeat/module/kubernetes/kubernetes.go
  metricbeat/module/kubernetes/node/node.go
  metricbeat/module/kubernetes/pod/data.go
  metricbeat/module/kubernetes/pod/pod.go
  metricbeat/module/kubernetes/pod/pod_test.go
  metricbeat/module/kubernetes/state_container/state_container.go
  metricbeat/module/kubernetes/state_cronjob/state_cronjob.go
  metricbeat/module/kubernetes/state_daemonset/state_daemonset.go
  metricbeat/module/kubernetes/state_deployment/state_deployment.go
  metricbeat/module/kubernetes/state_job/state_job.go
  metricbeat/module/kubernetes/state_node/state_node.go
  metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume.go
  metricbeat/module/kubernetes/state_persistentvolumeclaim/state_persistentvolumeclaim.go
  metricbeat/module/kubernetes/state_pod/state_pod.go
  metricbeat/module/kubernetes/state_replicaset/state_replicaset.go
  metricbeat/module/kubernetes/state_service/state_service.go
  metricbeat/module/kubernetes/state_statefulset/state_statefulset.go
  metricbeat/module/kubernetes/util/kubernetes.go
  metricbeat/module/kubernetes/util/metrics_cache.go
  metricbeat/module/kubernetes/util/metrics_cache_test.go
  metricbeat/module/kubernetes/util/metrics_repo.go
  metricbeat/module/kubernetes/util/metrics_repo_test.go
Labels: bug, backport-v8.0.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0, Team:Cloudnative-Monitoring, backport-v8.4.0

#32654 packetbeat: clean up and add docs
  packetbeat/beater/processor.go
  packetbeat/beater/setup.go
  packetbeat/flows/flowid.go
  packetbeat/flows/flows.go
  packetbeat/flows/flows_test.go
  packetbeat/flows/table.go
  packetbeat/flows/util.go
  packetbeat/flows/worker.go
  packetbeat/flows/worker_test.go
  packetbeat/procs/procs.go
  packetbeat/procs/procs_linux.go
  packetbeat/procs/procs_linux_test.go
  packetbeat/procs/procs_test.go
  packetbeat/procs/procs_windows.go
  packetbeat/procs/procs_windows_test.go
  packetbeat/procs/syscall_windows.go
  packetbeat/sniffer/afpacket.go
  packetbeat/sniffer/afpacket_linux.go
  packetbeat/sniffer/file.go
  packetbeat/sniffer/sniffer.go
Labels: enhancement, docs, Packetbeat, cleanup, Team:Security-External Integrations, 8.5-candidate

#32675 packetbeat/flows: use canonical GCD algorithm
  packetbeat/flows/worker.go
Labels: cleanup, Team:Security-External Integrations, backport-skip, 8.5 candidate

#32677 packetbeat/sniffer: remove unused error return on Sniffer.Stop
  packetbeat/beater/processor.go
  packetbeat/sniffer/sniffer.go
Labels: cleanup, Team:Security-External Integrations, backport-skip, 8.5 candidate

#32678 packetbeat/procs: don't unnecessarily set localAddrs
  packetbeat/procs/procs.go
Labels: cleanup, Team:Security-External Integrations, backport-skip, 8.5 candidate

#32684 [automation] update elastic stack version for testing 7.17.6-efe703c7
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32686 [automation] update elastic stack version for testing 8.4.0-fea9abbe
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32685 [automation] update elastic stack version for testing 8.3.4-6d6eaf28
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32672 fix bug for tests in metrics_repo_test.go
  metricbeat/module/kubernetes/util/metrics_repo_test.go
Labels: bug, Team:Cloudnative-Monitoring

#32689 Update .mergify.yml with missing 8.1.0 backport
  .mergify.yml
Labels: Team:Cloudnative-Monitoring

#32574 [automation] Update go release version 1.18.5
  .github/workflows/golangci-lint.yml
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  NOTICE.txt
  auditbeat/Dockerfile
  dev-tools/templates/.golangci.yml
  go.mod
  go.sum
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  libbeat/outputs/kafka/kafka_integration_test.go
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  testing/environments/docker/kafka/Dockerfile
  testing/environments/docker/kafka/README.md
  testing/environments/docker/kafka/certs/broker-cert
  testing/environments/docker/kafka/certs/broker-cert-signed
  testing/environments/docker/kafka/certs/broker.keystore.jks
  testing/environments/docker/kafka/certs/ca-cert
  testing/environments/docker/kafka/certs/ca-cert.srl
  testing/environments/docker/kafka/certs/ca-key
  testing/environments/docker/kafka/certs/client.truststore.jks
  winlogbeat/sys/wineventlog/publisher_metadata.go
  winlogbeat/sys/wineventlog/syscall_windows.go
  x-pack/functionbeat/Dockerfile
Labels: automation, dependency, backport-skip, Team:Elastic-Agent-Data-Plane

#32696 Run linter across some files that Will deal with the V2 agent update
  filebeat/beater/filebeat.go
  libbeat/common/reload/reload.go
  libbeat/common/reload/reload_test.go
  metricbeat/beater/metricbeat.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#32697 winlogbeat/eventlog: reduce severity of message salvage failure logging
  CHANGELOG.next.asciidoc
  winlogbeat/eventlog/wineventlog.go
Labels: enhancement, Winlogbeat, Team:Security-External Integrations, 8.5 candidate

#32699 [automation] update elastic stack version for testing 7.17.6-03b746cb
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32700 [automation] update elastic stack version for testing 8.3.4-58ddca7b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32701 [automation] update elastic stack version for testing 8.4.0-9bd354a1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32702 Revert "Update .mergify.yml with missing 8.1.0 backport"
  .mergify.yml
Labels: automation, Team:Automation

#32705 mergify: backport policy
  .mergify.yml
Labels: automation, Team:Automation

#32698 packetbeat/protos/tcp: fix formatting of debug logs
  CHANGELOG.next.asciidoc
  packetbeat/protos/tcp/tcp.go
Labels: bug, Packetbeat, cleanup, Team:Security-External Integrations, backport-skip, 8.5 candidate

#32712 [Filebeat] gcp-pubsub: Restart Pub/Sub client on errors
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/gcppubsub/_meta/Dockerfile
  x-pack/filebeat/input/gcppubsub/_meta/supported-versions.yml
  x-pack/filebeat/input/gcppubsub/docker-compose.yml
  x-pack/filebeat/input/gcppubsub/input.go
Labels: bug, Filebeat, Team:Security-External Integrations, backport-v7.17.0, backport-v8.4.0

#32719 [automation] update elastic stack version for testing 7.17.6-202119fd
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32713 [Filebeat] gcp-pubsub: Remove github.com/pkg/errors
  x-pack/filebeat/input/gcppubsub/input.go
Labels: Filebeat, Team:Security-External Integrations

#32709 mergify remove 8.2 backports
  .mergify.yml
Labels: automation, Team:Automation

#32524 [filebeat] [AWS Cloudwatch] fix request canceled error check
  x-pack/filebeat/input/awscloudwatch/cloudwatch.go
Labels: Team:Cloud-Monitoring, backport-v8.4.0

#32729 [automation] update elastic stack version for testing 8.3.4-e23a59c6
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32730 [automation] update elastic stack version for testing 7.17.6-091e6fb1
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32728 [automation] update elastic stack version for testing 8.4.0-b95305c2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32731 [automation] update elastic stack version for testing 8.5.0-6b9f92c0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32706 Refactor tests in metricbeat in kubernetes module
  metricbeat/module/kubernetes/container/container_test.go
  metricbeat/module/kubernetes/node/node_test.go
  metricbeat/module/kubernetes/pod/pod_test.go
  metricbeat/module/kubernetes/util/metrics_repo_test.go
Labels: enhancement, cleanup, Team:Cloudnative-Monitoring

#32175 [Filebeat] Add lumberjack input
  NOTICE.txt
  filebeat/docs/fields.asciidoc
  go.mod
  go.sum
  x-pack/filebeat/include/list.go
  x-pack/filebeat/input/default-inputs/inputs_aix.go
  x-pack/filebeat/input/default-inputs/inputs_other.go
  x-pack/filebeat/input/lumberjack/_meta/fields.yml
  x-pack/filebeat/input/lumberjack/ack.go
  x-pack/filebeat/input/lumberjack/ack_test.go
  x-pack/filebeat/input/lumberjack/config.go
  x-pack/filebeat/input/lumberjack/config_test.go
  x-pack/filebeat/input/lumberjack/fields.go
  x-pack/filebeat/input/lumberjack/generate_certs_test.go
  x-pack/filebeat/input/lumberjack/input.go
  x-pack/filebeat/input/lumberjack/logger.go
  x-pack/filebeat/input/lumberjack/metrics.go
  x-pack/filebeat/input/lumberjack/server.go
  x-pack/filebeat/input/lumberjack/server_test.go
Labels: review, Filebeat, Team:Security-External Integrations

#32472 httpjson: Add toJSON helper function
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/value_tpl.go
  x-pack/filebeat/input/httpjson/value_tpl_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations

#32740 [automation] update elastic stack version for testing 7.17.6-b8ca5a33
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32737 [automation] update elastic stack version for testing 8.3.4-70c0b53c
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32739 [automation] update elastic stack version for testing 8.5.0-0616acda
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32711 actions: run check for x-pack/packetbeat and packebeat
  .github/workflows/check-packetbeat.yml
  .github/workflows/check-xpack-packetbeat.yml
  .github/workflows/opentelemetry.yml
  packetbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0

#32756 docs: update docs versions 7.17.6
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#32738 [automation] update elastic stack version for testing 8.4.0-910fe5e1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32722 [filebeat][httpjson][bugfix] - root request pagination now working with chaining
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/chain.go
  x-pack/filebeat/input/httpjson/input_test.go
  x-pack/filebeat/input/httpjson/request.go
  x-pack/filebeat/input/httpjson/response.go
Labels: Team:Security-External Integrations, backport-v8.4.0, bugfix

#32265 libbeat/processors/util: make mac address rendering conform to ECS
  CHANGELOG.next.asciidoc
  libbeat/processors/util/netinfo.go
  libbeat/processors/util/netinfo_test.go
Labels: bug, backport-skip, Team:Elastic-Agent-Data-Plane, 8.4-candidate

#32680 packetbeat/procs: simplify construction of port and IPv4 values
  packetbeat/procs/procs_windows.go
  packetbeat/procs/procs_windows_test.go
Labels: cleanup, Team:Security-External Integrations, backport-skip, 8.5 candidate

#32721 packetbeat: reduce levels of indirection, simplify and document
  packetbeat/beater/packetbeat.go
  packetbeat/beater/processor.go
  packetbeat/sniffer/decoders.go
  packetbeat/sniffer/sniffer.go
Labels: docs, Packetbeat, cleanup, Team:Security-External Integrations, 8.5 candidate

#32773 [automation] update elastic stack version for testing 8.3.4-45336fec
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32772 [automation] update elastic stack version for testing 7.17.6-a9c53531
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32770 [automation] update elastic stack version for testing 8.4.0-7f4eb04b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32771 [automation] update elastic stack version for testing 8.5.0-dd6f2bb0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32762 Add codeowners for S3, CloudWatch, and Lumberjack.
  .github/CODEOWNERS
Labels: Team:Cloud-Monitoring

#32733 added extra docs on metrics for cpu/memory for pod/container in the kubernetes module
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/container/_meta/fields.yml
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/pod/_meta/fields.yml
Labels: docs, Team:Cloudnative-Monitoring

#32759 [AWS CloudTrail] use json.digestS3Object for file.path
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/aws/cloudtrail/ingest/pipeline.yml
  x-pack/filebeat/module/aws/cloudtrail/test/cloudtrail-digest-json.log-expected.json
Labels: backport-v7.17.0, Team:Cloud-Monitoring, backport-v8.4.0

#32708 Add persistence acknowledgement support for shipper
  NOTICE.txt
  go.mod
  go.sum
  libbeat/outputs/shipper/api/shipper_mock.go
  libbeat/outputs/shipper/config.go
  libbeat/outputs/shipper/shipper.go
  libbeat/outputs/shipper/shipper_test.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane, v8.5.0

#32620 [Filebeat] Add Cloudflare R2 to provider list
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_test.go
Labels: Team:Security-External Integrations, Team:Cloud-Monitoring

#32760 docs: Prepare Changelog for 8.4.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#32768 Add Beats breaking changes for 8.4
  libbeat/docs/release-notes/breaking/breaking-8.4.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
Labels: Team:Docs, Team:Elastic-Agent-Data-Plane, backport-v8.4.0

#32622 auditbeat,filebeat,packetbeat: format mac addresses according to ECS
  CHANGELOG.next.asciidoc
  packetbeat/_meta/sample_outputs/flow.json
  packetbeat/docs/packetbeat-options.asciidoc
  packetbeat/flows/flows_test.go
  packetbeat/flows/worker.go
  packetbeat/flows/worker_test.go
  packetbeat/protos/dhcpv4/dhcpv4.go
  packetbeat/protos/dhcpv4/dhcpv4_test.go
  packetbeat/tests/system/test_0060_flows.py
  packetbeat/tests/system/test_0066_dhcp.py
  x-pack/auditbeat/module/system/host/_meta/data.json
  x-pack/auditbeat/module/system/host/host.go
  x-pack/filebeat/input/netflow/convert.go
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Barracuda-extended-uniflow-template-256.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Barracuda-firewall.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-1941-K9-release-15.1.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-NBAR-flowset-262.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-WLC.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Ubiquiti-Edgerouter-with-MPLS-labels.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-ipt_netflow-reduced-size-encoding.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-macaddress.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/netflow9_ubiquiti_edgerouter.pcap.golden.json
  x-pack/filebeat/processors/decode_cef/decode_cef.go
  x-pack/filebeat/processors/decode_cef/keys.ecs.go
  x-pack/filebeat/processors/decode_cef/testdata/samples.log.golden.json
Labels: bug, Team:Security-External Integrations, backport-skip, 8.4-candidate

#32792 [automation] update elastic stack version for testing 8.3.4-97a7bb79
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32793 [automation] update elastic stack version for testing 7.17.6-4816e9ef
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32790 [automation] update elastic stack version for testing 8.5.0-feb644de
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32791 [automation] update elastic stack version for testing 8.4.0-fa661330
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32780 actions: use v3 and mage install
  .github/workflows/check-default.yml
  .github/workflows/check-docs.yml
  .github/workflows/check-packetbeat.yml
  .github/workflows/check-xpack-packetbeat.yml
  .github/workflows/macos-build.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0

#32753 action: checks for x-pack/osquerybeat
  .github/workflows/check-xpack-osquerybeat.yml
  .github/workflows/opentelemetry.yml
  x-pack/osquerybeat/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0

#32755 action: checks for dev-tools
  .github/workflows/check-dev-tools.yml
  .github/workflows/opentelemetry.yml
  Jenkinsfile.yml
  dev-tools/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0

#32750 action: checks for winlogbeat and x-pack/winlogbeat
  .github/workflows/check-winlogbeat.yml
  .github/workflows/check-xpack-winlogbeat.yml
  .github/workflows/opentelemetry.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: automation, Team:Automation, Team:Security-External Integrations, backport-v7.17.0, backport-v8.4.0

#32761 docs: Prepare Changelog for 7.17.6
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#32735 [ci] Use 'go install' in Github Action setup
  .github/workflows/macos-auditbeat.yml
  .github/workflows/macos-filebeat.yml
  .github/workflows/macos-heartbeat.yml
  .github/workflows/macos-metricbeat.yml
  .github/workflows/macos-packetbeat.yml
  .github/workflows/macos-xpack-auditbeat.yml
  .github/workflows/macos-xpack-filebeat.yml
  .github/workflows/macos-xpack-functionbeat.yml
  .github/workflows/macos-xpack-heartbeat.yml
  .github/workflows/macos-xpack-metricbeat.yml
  .github/workflows/macos-xpack-osquerybeat.yml
  .github/workflows/macos-xpack-packetbeat.yml
  libbeat/tests/system/requirements.txt
  libbeat/tests/system/requirements_aix.txt
Labels: ci, Team:Automation

#32757 [Release] Update version to 7.17.7
  libbeat/version/version.go
Labels: release, Team:Automation

#32522 [Release] Update version to 8.4.1
  libbeat/version/version.go
Labels: release, Team:Automation

#32710 ci: enable synthetics tests for heartbeats
  Jenkinsfile
  x-pack/heartbeat/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-v8.4.0

#32745 action: checks for auditbeat and x-pack/auditbeat
  .github/workflows/check-audtibeat.yml
  .github/workflows/check-xpack-auditbeat.yml
  .github/workflows/opentelemetry.yml
  auditbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0

#32523 [Release] Update test environments for 8.4.1
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#32823 Upgrade to go-libaudit v2.3.2
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, Auditbeat, Team:Security-External Integrations, backport-v8.4.0

#32789 x-pack/filebeat/module/cisco/asa: add handling of AAA operations and non-canonical log formats
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/test/additional_messages.log
  x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/non-canonical.log
  x-pack/filebeat/module/cisco/asa/test/non-canonical.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.5 candidate

#32767 allow for json/ndjson content type with charset
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/s3_objects.go
Labels: backport-v7.17.0, Team:Cloud-Monitoring, backport-v8.4.0

#32746 action: checks for filebeat and x-pack/filebeat
  .github/workflows/check-filebeat.yml
  .github/workflows/check-xpack-filebeat.yml
  .github/workflows/opentelemetry.yml
  filebeat/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0

#32748 action: checks for metricbeat and x-pack/metricbeat
  .github/workflows/check-metricbeat.yml
  .github/workflows/check-xpack-metricbeat.yml
  .github/workflows/opentelemetry.yml
  metricbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0

#32801 Update HB k8s template to use <Mi> metric
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/heartbeat/heartbeat-deployment.yaml
Labels: docs, Team:Uptime, release-note:skip, backport-v8.4.0, bugfix

#32811 [Filebeat] [httpjson] Add support for single string containing multiple relation-types in getRFC5988Link
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/value_tpl.go
  x-pack/filebeat/input/httpjson/value_tpl_test.go
Labels: Filebeat, Team:Security-External Integrations, backport-v8.4.0, bugfix

#32724 Fix a couple of bugs in the logic for how AWS metric periods are calculated
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/billing/billing.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
Labels: backport-v7.17.0, Team:Cloud-Monitoring, backport-v8.4.0

#32839 ci: pre-commit stage within Jenkins
  .github/workflows/opentelemetry.yml
  .github/workflows/pre-commit.yml
  Jenkinsfile
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0

#32867 update ironbank image product name
  dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0

#32884 elastic agent ironbank product name
  dev-tools/packaging/templates/ironbank/elastic-agent/hardening_manifest.yaml
Labels: automation, Team:Automation

#32912 Skip broken ceph tests.
  metricbeat/module/ceph/test_ceph.py
Labels: ci, Team:Elastic-Agent-Data-Plane, backport-v7.17.0, backport-v8.4.0

#32758 [Release] Update test environments for 7.17.7
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#32870 docs: Prepare Changelog for 8.4.1
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#32919 [automation] update elastic stack version for testing 8.5.0-440e0896
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32920 [automation] update elastic stack version for testing 7.17.7-18723602
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32918 [automation] update elastic stack version for testing 8.4.1-b72ec52c
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32905 Preallocate memory to reduce GC load
  libbeat/template/load_integration_test.go
  x-pack/filebeat/input/httpjson/transform_registry.go
Labels: enhancement, cleanup, backport-skip, Team:Elastic-Agent-Data-Plane

#32845 conflict 7.17
  x-pack/libbeat/processors/add_cloudfoundry_metadata/_meta/fields.yml
Labels: needs_team

#32821 [Release] Update version to 8.4.2
  libbeat/version/version.go
Labels: release, Team:Automation

#32930 [automation] update elastic stack version for testing 8.5.0-fedc3e60
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32931 [automation] update elastic stack version for testing 8.4.1-65181fd0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32785 Make event acknowledgment asynchronous in shipper output
  libbeat/outputs/shipper/README.md
  libbeat/outputs/shipper/api/shipper_mock.go
  libbeat/outputs/shipper/config.go
  libbeat/outputs/shipper/shipper.go
  libbeat/outputs/shipper/shipper_test.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane, v8.5.0

#32749 action: checks for heartbeat and x-pack/heartbeat
  .github/workflows/check-heartbeat.yml
  .github/workflows/check-xpack-heartbeat.yml
  .github/workflows/opentelemetry.yml
  heartbeat/Jenkinsfile.yml
  x-pack/heartbeat/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0

#32822 [Release] Update test environments for 8.4.2
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#32940 Update to Go 1.18 in go.mod.
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane

#32754 action: checks for x-pack/libbeat and libbeat
  .github/workflows/check-libbeat.yml
  .github/workflows/check-xpack-libbeat.yml
  .github/workflows/opentelemetry.yml
  libbeat/Jenkinsfile.yml
  x-pack/libbeat/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0
