Repository elastic/beats, pull requests merged in 2022-03, with the labels that each got.

#30614 Update breaking-8.0.asciidoc (#30565)
  libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
Labels: docs, needs_team, backport-skip

#30521 [Release] Update test environments for 7.17.2
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  testing/environments/prev-minor.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#28659 [Release] Update test environments for 8.0.1
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  testing/environments/prev-minor.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#30591 [ci][daily]: disable builds as long as Orka VMs are not provisioned
  .ci/schedule-daily.groovy
Labels: automation, Team:Automation, backport-skip

#30618 Alert elastic agent control team of elastic-agent changes
  .github/CODEOWNERS
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#30414 refactor pushDockerImages
  .ci/packaging.groovy
  .ci/scripts/docker-tag-push.sh
Labels: Team:Automation, backport-v8.1.0, backport-v7.17.0

#30619 Curate k8s testing versions to only keep the actively maintained
  deploy/kubernetes/Jenkinsfile.yml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/module/kubernetes/_meta/docs.asciidoc
Labels: backport-v8.1.0, Team:Cloudnative-Monitoring

#30503 [Release] Update version to 8.0.2
  libbeat/version/version.go
Labels: release, Team:Automation

#30528 ci: add windows-2022 in the extended meta-stage
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/osquerybeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-v8.0.0, backport-v8.1.0

#30633 [automation] update elastic stack version for testing 8.2.0-43df679f
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30635 [automation] update elastic stack version for testing 7.17.2-3e73f87b
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30589 [automation] update elastic stack version for testing 8.1.0-f6199768
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30401 input/filestream: filestream input ID is required
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/_meta/config/filebeat.inputs.yml.tmpl
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/docs/inputs/input-filestream.asciidoc
  filebeat/filebeat.reference.yml
  filebeat/filebeat.yml
  filebeat/input/filestream/internal/input-logfile/manager.go
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/filebeat.yml
Labels: bug, backport-skip, Team:Elastic-Agent-Data-Plane

#30409 ci: refactor packaging with a new step
  .ci/packaging.groovy
Labels: Team:Automation, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#30534 [libbeat | filebeat] Log error when parsing config block and disabled input on filebeat
  CHANGELOG.next.asciidoc
  filebeat/beater/crawler.go
  filebeat/input/log/harvester.go
  filebeat/tests/system/test_stdin.py
  libbeat/tests/system/beat/beat.py
  x-pack/libbeat/management/manager.go
Labels: backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v8.1.0, backport-v7.17.0

#30631 Update filesystem and fsstat docs to update the definition of a "file"
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/fields.go
  metricbeat/module/system/filesystem/_meta/fields.yml
  metricbeat/module/system/filesystem/helper.go
  metricbeat/module/system/fsstat/_meta/fields.yml
Labels: docs, Team:Elastic-Agent-Data-Plane, v8.2.0, backport-v8.2.0

#30664 [automation] update elastic stack version for testing 8.2.0-fdde08ec
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30663 [automation] update elastic stack version for testing 8.1.0-fbfb1f9e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30665 [automation] update elastic stack version for testing 7.17.2-e8098595
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30661 x-pack/filebeat/module/panw/panos: fix broken test case
  x-pack/filebeat/module/panw/panos/test/global_protect.log
  x-pack/filebeat/module/panw/panos/test/global_protect.log-expected.json
Labels: bug, Team:Security-External Integrations, backport-skip, 8.2-candidate

#30471 Enable monitoring buffer for elastic-agent
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/_meta/config/common.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/common.reference.p2.yml.tmpl
  x-pack/elastic-agent/_meta/config/elastic-agent.docker.yml.tmpl
  x-pack/elastic-agent/_meta/elastic-agent.yml
  x-pack/elastic-agent/control.proto
  x-pack/elastic-agent/elastic-agent.docker.yml
  x-pack/elastic-agent/elastic-agent.reference.yml
  x-pack/elastic-agent/elastic-agent.yml
  x-pack/elastic-agent/pkg/agent/cmd/diagnostics.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/control/client/client.go
  x-pack/elastic-agent/pkg/agent/control/proto/control.pb.go
  x-pack/elastic-agent/pkg/agent/control/server/server.go
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
  x-pack/elastic-agent/pkg/core/monitoring/config/config.go
  x-pack/elastic-agent/pkg/core/monitoring/server/server.go
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane, v8.2.0

#30682 [automation] update elastic stack version for testing 8.0.2-ae36dda7
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30681 [automation] update elastic stack version for testing 8.1.0-5eb67818
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30504 [Release] Update test environments for 8.0.2
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  testing/environments/prev-minor.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#30688 filebeat: rename `source` log key to `source_file`
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/internal/input-logfile/harvester.go
  filebeat/input/log/logger.go
Labels: bug, Filebeat, backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0

#30706 [automation] update elastic stack version for testing 8.0.2-901e2b50
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30705 [automation] update elastic stack version for testing 8.1.0-52a8d1d4
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30668 libbeat: Don't force an ignore_above limit on wildcard fields
  CHANGELOG-developer.next.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/template/processor.go
  libbeat/template/processor_test.go
Labels: bug, libbeat, Team:Integrations, Team:Security-External Integrations, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#30684 docs: Prepare Changelog for 8.1.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, Team:Docs

#30669 testing: Update docker and docker-compose versions
  libbeat/tests/system/requirements.txt
  metricbeat/module/prometheus/docker-compose.yml
Labels: Team:apm, backport-skip

#30711 Forward-port 8.1.0 changelog to main
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: release, backport-skip, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane

#30704 [automation] update elastic stack version for testing 8.2.0-a12f7069
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30679 Fix 32-bit rollovers and add rounding in iostat metrics
  CHANGELOG.next.asciidoc
  libbeat/metric/system/diskio/diskstat_linux.go
  libbeat/metric/system/diskio/diskstat_linux_test.go
  metricbeat/module/linux/iostat/_meta/data.json
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#30709 Page formatting issue
  libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc
Labels: docs, Team:Docs

#30722 Page formatting issue (#30709)
  libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc
Labels: Team:Docs, backport-v8.0.0, backport-v8.1.0

#30695 Add 8.1 Beats breaking changes
  libbeat/docs/release-notes/breaking/breaking-8.1.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
Labels: docs, needs_team, v8.1.0, backport-v8.1.0

#30727 libbeat/processors/add_process_metadata: place parent process information directly in parent object
  CHANGELOG.next.asciidoc
  libbeat/processors/add_process_metadata/add_process_metadata.go
  libbeat/processors/add_process_metadata/add_process_metadata_test.go
  libbeat/processors/add_process_metadata/config.go
Labels: bug, Team:Integrations, breaking change, Team:Security-External Integrations, backport-skip, 8.2-candidate

#30732 Upgrade kind version used for k8s testing
  Jenkinsfile
  deploy/kubernetes/Jenkinsfile.yml
Labels: Team:Automation, backport-v8.2.0, Team:Cloudnative-Monitoring

#30714 improve filebeat scan performance when symlinks is enabled
  filebeat/input/filestream/fswatch.go
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#30735 Remove incorrect changelog entries
  CHANGELOG.next.asciidoc
Labels: Team:Elastic-Agent-Data-Plane

#29863 enhancement: add hostname to Microsoft 365 defender ingest pipeline
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/microsoft/m365_defender/ingest/pipeline.yml
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log-expected.json
Labels: enhancement, Team:Security-External Integrations, backport-skip, 8.2-candidate

#30720 Fix add_kubernetes_metadata matcher: support rotated logs when 'resource_type: pod'
  CHANGELOG.next.asciidoc
  filebeat/processor/add_kubernetes_metadata/matchers.go
  filebeat/processor/add_kubernetes_metadata/matchers_test.go
Labels: backport-v8.0.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0, Team:Cloudnative-Monitoring

#30742 Update testing to test agains Snapshot Logstash version
  testing/environments/snapshot.yml
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#30157 [Release] Update version to 8.1.1
  filebeat/Jenkinsfile.yml
  libbeat/version/version.go
  x-pack/filebeat/Jenkinsfile.yml
Labels: release, Team:Automation

#30699 cloudbeat libbeat changes
  libbeat/common/kubernetes/informer.go
  libbeat/common/kubernetes/types.go
Labels: enhancement, backport-skip, Team:Cloud-Security-Posture, Team:Cloudnative-Monitoring

#30741 Remove old unused testing env files
  .ci/bump-stack-version.sh
  testing/environments/5.x.yml
  testing/environments/6.0.yml
  testing/environments/snapshot-oss.yml
Labels: Team:Automation, backport-skip, Team:Elastic-Agent-Data-Plane

#30746 Ignore bugfix version when running version compatibility check against Elasticsearch
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
  libbeat/common/version.go
  libbeat/common/version_test.go
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0

#30747 ci: configure kind/k8s for k8s in metricbeat only
  Jenkinsfile
  metricbeat/Jenkinsfile.yml
Labels: Team:Automation, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#30733 Fix cronjob version in manifest used for tests
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-role.yaml
  dev-tools/mage/kubernetes/kind.go
  metricbeat/module/kubernetes/_meta/test/docs/02_objects/cronjob.yaml
  metricbeat/module/kubernetes/kubernetes.yml
Labels: Team:Automation, backport-v8.2.0, Team:Cloudnative-Monitoring

#30740 Fix double-counted metrics in docker/diskio
  metricbeat/docs/modules/docker.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/docker/_meta/config.reference.yml
  metricbeat/module/docker/_meta/config.yml
  metricbeat/module/docker/diskio/_meta/data.json
  metricbeat/module/docker/diskio/diskio.go
  metricbeat/module/docker/diskio/diskio_test.go
  metricbeat/module/docker/diskio/helper.go
  metricbeat/modules.d/docker.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: backport-skip, Team:Elastic-Agent-Data-Plane, v8.2.0

#30755 Update to distribution/distribution 2.8.1
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-v8.0.0, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30637 Add cronjob metadata by default
  CHANGELOG.next.asciidoc
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/filebeat/filebeat-role.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/heartbeat/heartbeat-role.yaml
  libbeat/common/kubernetes/metadata/config.go
  libbeat/common/kubernetes/metadata/pod.go
  libbeat/docs/shared-autodiscover.asciidoc
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/_meta/config.yml
  metricbeat/module/kubernetes/kubernetes.yml
  metricbeat/module/kubernetes/state_cronjob/_meta/docs.asciidoc
  metricbeat/module/kubernetes/state_cronjob/state_cronjob.go
  metricbeat/module/kubernetes/state_cronjob/state_cronjob_integration_test.go
  metricbeat/module/kubernetes/test/integration.go
  metricbeat/modules.d/kubernetes.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: backport-v8.2.0, Team:Cloudnative-Monitoring

#30561 Documentation about the hints annotation for processors
  CHANGELOG.next.asciidoc
  filebeat/docs/autodiscover-hints.asciidoc
Labels: docs, backport-v8.0.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0, Team:Cloudnative-Monitoring

#30739 [Filebeat] httpjson update docs
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
Labels: docs, Team:Security-External Integrations, backport-v8.1.0, backport-v7.17.0

#30774 Fix missing swap fields in linux/memory
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/linux/fields.go
  metricbeat/module/linux/memory/_meta/data.json
  metricbeat/module/linux/memory/_meta/fields.yml
  metricbeat/module/linux/memory/data.go
Labels: bug, backport-skip, Team:Elastic-Agent-Data-Plane

#30779 [automation] update elastic stack version for testing 8.1.1-b9a6c108
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30780 [automation] update elastic stack version for testing 8.2.0-63265ec9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29662 Get each command stats from INFO all command on redis module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/redis.asciidoc
  metricbeat/module/redis/_meta/docs.asciidoc
  metricbeat/module/redis/_meta/supported-versions.yml
  metricbeat/module/redis/fields.go
  metricbeat/module/redis/info/_meta/data.json
  metricbeat/module/redis/info/_meta/fields.yml
  metricbeat/module/redis/info/data.go
  metricbeat/module/redis/info/info.go
  metricbeat/module/redis/info/info_integration_test.go
  metricbeat/module/redis/redis.go
  metricbeat/module/redis/test_redis.py
Labels: Team:Integrations, backport-v8.2.0

#30790 [automation] update elastic stack version for testing 8.1.1-da392dcd
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30788 [automation] update elastic stack version for testing 8.2.0-d02c907a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30763 Remove temporary "Allow older" for 8.1
  filebeat/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
Labels: Team:Elastic-Agent-Data-Plane

#30798 Update doc following 7.11 change on index pattern.
  libbeat/docs/shared-faq.asciidoc
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#30778 [Docs] Clarify cipher_suites parameter in TLS 1.3
  libbeat/docs/shared-ssl-config.asciidoc
Labels: docs, backport-skip, Team:Elastic-Agent-Data-Plane, v8.2.0

#30694 Fix/change the initialization of management layer
  CHANGELOG.next.asciidoc
  filebeat/beater/filebeat.go
  heartbeat/beater/heartbeat.go
  libbeat/cmd/instance/beat.go
  libbeat/management/management.go
  metricbeat/beater/metricbeat.go
  packetbeat/beater/packetbeat.go
  x-pack/libbeat/management/manager.go
  x-pack/osquerybeat/beater/osquerybeat.go
Labels: backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30817 [automation] update elastic stack version for testing 8.2.0-fee3b8d2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30818 [automation] update elastic stack version for testing 8.1.1-2d188131
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30781 ci: split windows in mandatory and ext_win stages
  Jenkinsfile
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/heartbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/osquerybeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30783 [Auditbeat] Add auditbeat.elastic-agent.yml config
  CHANGELOG.next.asciidoc
  auditbeat/scripts/mage/package.go
  dev-tools/packaging/package_test.go
  x-pack/auditbeat/auditbeat.elastic-agent.yml
Labels: Auditbeat, Team:Security-External Integrations, backport-v8.2.0

#30812 Attempt to fix the flaky test_file_no_permission test filebeat test.
  filebeat/tests/system/test_crawler.py
Labels: flaky-test, Team:Elastic-Agent-Data-Plane, v8.2.0, backport-v8.1.0, backport-v7.17.0

#30829 docs: correct example of --strict.perms usage
  libbeat/docs/shared-docker.asciidoc
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30821 packetbeat/{beater,npcap}: prevent panic when querying Npcap version and perform install before all other work
  CHANGELOG.next.asciidoc
  packetbeat/beater/install_npcap.go
  packetbeat/beater/packetbeat.go
  packetbeat/beater/processor.go
  packetbeat/npcap/npcap.go
  x-pack/packetbeat/magefile.go
  x-pack/packetbeat/tests/system/app_test.go
Labels: bug, Team:Security-External Integrations, 8.2-candidate, 8.1-candidate, backport-v8.1.0

#30839 [automation] update elastic stack version for testing 8.1.1-31faf00b
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30154 [Metricbeat] improve efficiency of quering instance metadata in GCP metrics
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/gcp/metrics/compute/metadata.go
Labels: backport-skip, Team:Cloud-Monitoring

#30826 Extend `kubernetes.node.network.*` metrics documentation regarding default interface
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/node/_meta/fields.yml
Labels: docs, backport-v8.0.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0, Team:Cloudnative-Monitoring

#30795 ci: refactor pushDockerImages main pipeline
  Jenkinsfile
Labels: Team:Automation, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30796 ci: refactor publishPackages main pipeline
  Jenkinsfile
Labels: Team:Automation, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30808 refactor code to support fsFS
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/cmdline.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/cmdline_test.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/io.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/io_test.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/link.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/list.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/list_test.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/stat.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/stat_test.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/uptime.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/uptime_test.go
Labels: enhancement, backport-skip, Team:Cloud-Security-Posture

#30386 Propagate input id from the Agent policy into Filebeat configuration
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/pkg/agent/program/testdata/usecases/generated/single_config.filebeat.golden.yml
  x-pack/elastic-agent/pkg/agent/program/testdata/usecases/single_config.yml
  x-pack/elastic-agent/spec/filebeat.yml
Labels: backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30658 Fix dissect trim panics from DELETE (\u007f) character
  CHANGELOG.next.asciidoc
  libbeat/processors/dissect/trim.go
  libbeat/processors/dissect/trim_test.go
Labels: bug, Team:Security-External Integrations, backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#30870 Fix scheduler and controllermanager k8s tests
  metricbeat/module/kubernetes/test/integration.go
Labels: Team:Cloudnative-Monitoring

#30872 Fix scheduler and controllermanager k8s tests
  metricbeat/module/kubernetes/test/integration.go
Labels: needs_team

#30883 [automation] update elastic stack version for testing 8.2.0-ff67d7b8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30884 [automation] update elastic stack version for testing 7.17.2-8f7db3a8
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30885 [automation] update elastic stack version for testing 8.1.1-9bb65a23
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30871 Fix the name `close.reader.on_eof` in reference configuration and documentation
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/filebeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
Labels: backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#30785 Add field kubernetes.volume.fs.inodes.pct
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/volume/_meta/fields.yml
  metricbeat/module/kubernetes/volume/data.go
  metricbeat/module/kubernetes/volume/volume_test.go
Labels: backport-v8.2.0, Team:Cloudnative-Monitoring

#30848 ci: extended meta-stage for ARM and extended_win for Windows-2019
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30825 Emit summaries when synthetics exits without emitting journey/end [#30729]
  CHANGELOG.next.asciidoc
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
Labels: enhancement, backport, Team:Uptime, v8.1.0, v8.2.0, v7.17.1

#30853 [Release] Update test environments for 8.1.1
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#30771 [Metricbeat] gcp: update gke example documentation
  metricbeat/docs/modules/gcp.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/gcp/_meta/config.yml
  x-pack/metricbeat/modules.d/gcp.yml.disabled
Labels: backport-v8.1.0, Team:Cloud-Monitoring

#30874 Upgrade osquery to 5.2.2
  x-pack/osquerybeat/internal/distro/distro.go
Labels: enhancement, Team:Asset Mgt, backport-skip

#30882 packetbeat/sniffer: update error check to match github.com/google/gopacket/afpacket API
  CHANGELOG.next.asciidoc
  packetbeat/sniffer/afpacket_linux.go
  packetbeat/sniffer/afpacket_nonlinux.go
  packetbeat/sniffer/sniffer.go
Labels: bug, Team:Security-External Integrations, 8.2-candidate, 8.1-candidate, backport-v8.1.0

#30880 Update module dependencies
  NOTICE.txt
  go.mod
  go.sum
Labels: cleanup, backport-skip, Team:Elastic-Agent-Data-Plane

#30908 [automation] update elastic stack version for testing 8.2.0-82b803a1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30910 [automation] update elastic stack version for testing 7.17.2-15b5bc7a
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30909 [automation] update elastic stack version for testing 8.1.1-da22c151
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30923 [automation] update elastic stack version for testing 8.2.0-5cc993c1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30925 [automation] update elastic stack version for testing 7.17.2-3b3b663d
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30924 [automation] update elastic stack version for testing 8.1.1-0d572bb7
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30861 Adjust pdhcollectquerydataex sample interval
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/perfmon.go
  metricbeat/module/windows/perfmon/perfmon_test.go
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/reader_integration_test.go
  x-pack/metricbeat/module/iis/application_pool/reader.go
Labels: windows-2016, windows-2012, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30921 Align `add_resource_metadata` documentation
  libbeat/docs/shared-autodiscover.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: docs, backport-v8.0.0, backport-skip, backport-v8.1.0, Team:Cloudnative-Monitoring

#30904 ci: packaging speed up
  .ci/packaging.groovy
Labels: Team:Automation, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30541 [libbeat] Add Syslog parser and processor
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-filestream-reader-options.asciidoc
  libbeat/cmd/instance/imports_common.go
  libbeat/processors/syslog/docs/syslog.asciidoc
  libbeat/processors/syslog/syslog.go
  libbeat/processors/syslog/syslog_test.go
  libbeat/reader/parser/parser.go
  libbeat/reader/parser/parser_test.go
  libbeat/reader/syslog/docs/syslog.asciidoc
  libbeat/reader/syslog/message.go
  libbeat/reader/syslog/message_test.go
  libbeat/reader/syslog/parser/common.rl
  libbeat/reader/syslog/parser/parser_rfc3164.rl
  libbeat/reader/syslog/parser/parser_rfc5424.rl
  libbeat/reader/syslog/parser/rfc3164.rl
  libbeat/reader/syslog/parser/rfc5424.rl
  libbeat/reader/syslog/rfc3164_gen.go
  libbeat/reader/syslog/rfc3164_test.go
  libbeat/reader/syslog/rfc5424_gen.go
  libbeat/reader/syslog/rfc5424_test.go
  libbeat/reader/syslog/syslog.go
  libbeat/reader/syslog/syslog_test.go
  libbeat/reader/syslog/util.go
  libbeat/reader/syslog/util_test.go
Labels: enhancement, libbeat, Team:Security-External Integrations, backport-skip

#30935 Osquerybeat: Add darwin/arm64 packaging support
  x-pack/osquerybeat/dev-tools/packaging/packages.yml
  x-pack/osquerybeat/internal/distro/distro.go
Labels: enhancement, Team:Asset Mgt

#30918 Update repositories.asciidoc
  libbeat/docs/repositories.asciidoc
Labels: release-note:skip, Team:Docs, v8.2.0, backport-v8.1.0

#30939 [automation] update elastic stack version for testing 8.2.0-63942b4d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30941 [automation] update elastic stack version for testing 7.17.2-81597e21
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29424 feat: report Otel data on Python tests
  Jenkinsfile
  libbeat/tests/system/requirements.txt
  libbeat/tests/system/requirements_aix.txt
Labels: enhancement, Team:Automation, backport-v8.0.0, backport-v7.16.0, backport-v8.1.0

#30945 Forward port 8.1.1 changelog to main
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, backport-skip

#30917 Add README to elasticsearch module
  metricbeat/module/elasticsearch/_meta/README.md
Labels: Team:Integrations, backport-skip

#30787 [automation] Update go release version 1.17.8
  .go-version
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: automation, needs_team, dependency, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30854 [Release] Update version to 8.1.2
  libbeat/version/version.go
Labels: release, Team:Automation

#30913 Improve k8s dashboard
  CHANGELOG.next.asciidoc
  metricbeat/module/kubernetes/_meta/kibana/7/dashboard/e0381d10-e4a6-11eb-9d53-3b3d1d47c519.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/022a54c0-2bf5-11e7-859b-f78b612cde28-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/16fa4470-2bfd-11e7-859b-f78b612cde28-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/174a6ad0-30e0-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/294546b0-30d6-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/408fccf0-30d6-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/44f12b40-2bf4-11e7-859b-f78b612cde28-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/58e644f0-30d6-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/7aac4fd0-30e0-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/a4c9d360-30df-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/cd059410-2bfb-11e7-859b-f78b612cde28-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/d54c65f0-e4a6-11eb-9d53-3b3d1d47c519.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/d6564360-2bfc-11e7-859b-f78b612cde28-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/da1ff7c0-30ed-11e7-b9e5-2b5b07213ab3-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/e1018b90-2bfb-11e7-859b-f78b612cde28-ecs.json
Labels: backport-v8.2.0, Team:Cloudnative-Monitoring

#30896 Add linter to the building pipeline
  .golangci.yml
  CHANGELOG-developer.asciidoc
  Jenkinsfile
  Makefile
  NOTICE.txt
  dev-tools/make/mage-install.mk
  dev-tools/templates/.golangci.yml
  docs/devguide/contributing.asciidoc
  go.mod
  go.sum
  libbeat/scripts/Makefile
  magefile.go
  tools/tools.go
Labels: enhancement, Team:Automation, backport-skip, Team:Elastic-Agent-Data-Plane

#30929 Fix export dashboards scripts
  dev-tools/cmd/dashboards/export_dashboards.go
  metricbeat/magefile.go
Labels: Team:Integrations, backport-v8.1.0, backport-v8.2.0

#30965 [automation] update elastic stack version for testing 8.2.0-4509f321
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30966 [automation] update elastic stack version for testing 7.17.2-70a05b08
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29585 [Beats] Build darwin/arm64 and universal binary
  .ci/packaging.groovy
  auditbeat/magefile.go
  dev-tools/mage/common.go
  dev-tools/mage/crossbuild.go
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgtypes.go
  dev-tools/mage/platforms.go
  dev-tools/mage/settings.go
  dev-tools/mage/target/build/build.go
  filebeat/magefile.go
  libbeat/magefile.go
  packetbeat/magefile.go
  x-pack/auditbeat/magefile.go
  x-pack/dockerlogbeat/magefile.go
  x-pack/filebeat/magefile.go
  x-pack/functionbeat/magefile.go
  x-pack/libbeat/magefile.go
  x-pack/metricbeat/magefile.go
  x-pack/osquerybeat/dev-tools/packaging/packages.yml
  x-pack/osquerybeat/internal/distro/distro.go
  x-pack/osquerybeat/magefile.go
  x-pack/packetbeat/magefile.go
Labels: enhancement, Team:Automation, backport-skip, Team:Elastic-Agent-Control-Plane, v8.2.0

#30964 [Heartbeat] Remove accidentally committed monitors.d directory from root
  monitors.d/plaintodos.yml
Labels: Heartbeat, Team:Uptime, cleanup, backport-v7.17.0

#30891 metricbeat/module/system/memory: fix dropped error
  metricbeat/module/system/memory/memory.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#30982 [automation] update elastic stack version for testing 8.1.2-2393b0c1
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30926 Remove prev-minor testing as not needed anymore
  filebeat/Jenkinsfile.yml
  testing/environments/prev-minor.yml
  x-pack/filebeat/Jenkinsfile.yml
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#30985 Move linting to a Github action for better integration
  .github/workflows/golangci-lint.yml
  CHANGELOG-developer.next.asciidoc
  Jenkinsfile
Labels: enhancement, Team:Automation, backport-skip, Team:Elastic-Agent-Data-Plane

#30987 add printf debug to mage package
  dev-tools/mage/crossbuild.go
  dev-tools/mage/target/build/build.go
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#30980 Update Jinja2 version used in tests to 2.11.3.
  libbeat/tests/system/requirements.txt
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#30981 [automation] update elastic stack version for testing 7.17.2-1941719d
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30717 filebeat: ID for filestream is required
  .golangci.yml
  CHANGELOG.next.asciidoc
  dev-tools/templates/.golangci.yml
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/input/filestream/environment_test.go
  filebeat/input/filestream/input_integration_test.go
  filebeat/input/filestream/internal/input-logfile/harvester_test.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/filestream/internal/input-logfile/manager_test.go
  filebeat/input/filestream/internal/input-logfile/prospector.go
  filebeat/input/filestream/internal/input-logfile/store.go
  filebeat/input/filestream/internal/input-logfile/store_test.go
  filebeat/input/filestream/parsers_integration_test.go
  filebeat/input/filestream/prospector.go
  filebeat/input/filestream/prospector_test.go
  filebeat/tests/system/config/filestream-fixup-id.yml.j2
  filebeat/tests/system/filebeat.py
  filebeat/tests/system/input/filestream-fix-registry-global-id.j2
  filebeat/tests/system/input/registry-meta.json
  filebeat/tests/system/test_input.py
  testing/environments/local.yml
Labels: bug, review, Filebeat, backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#31000 Disable the failing k8s scheduler integration test.
  metricbeat/module/kubernetes/scheduler/scheduler_integration_test.go
  metricbeat/module/kubernetes/scheduler/scheduler_test.go
Labels: needs_team

#30983 metricbeat/module/linux/memory: fix dropped error
  metricbeat/module/linux/memory/data.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#31003 [automation] update elastic stack version for testing 8.2.0-dcff22d7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31004 [automation] update elastic stack version for testing 8.1.2-5d446358
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31010 [automation] update elastic stack version for testing 7.17.2-cf7cf1eb
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30986 Fix k8s dashboard to use proper timerange
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/module/kubernetes/_meta/docs.asciidoc
  metricbeat/module/kubernetes/_meta/kibana/7/dashboard/e0381d10-e4a6-11eb-9d53-3b3d1d47c519.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/022a54c0-2bf5-11e7-859b-f78b612cde28-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/16fa4470-2bfd-11e7-859b-f78b612cde28-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/174a6ad0-30e0-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/294546b0-30d6-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/408fccf0-30d6-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/44f12b40-2bf4-11e7-859b-f78b612cde28-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/58e644f0-30d6-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/7aac4fd0-30e0-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/a4c9d360-30df-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/cd059410-2bfb-11e7-859b-f78b612cde28-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/d54c65f0-e4a6-11eb-9d53-3b3d1d47c519.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/d6564360-2bfc-11e7-859b-f78b612cde28-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/da1ff7c0-30ed-11e7-b9e5-2b5b07213ab3-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/e1018b90-2bfb-11e7-859b-f78b612cde28-ecs.json
Labels: backport-v8.2.0, Team:Cloudnative-Monitoring

#31012 [Stack Monitoring] Readme for logstash module
  metricbeat/module/logstash/_meta/README.md
Labels: docs, backport-skip, v8.2.0, Team:Infra Monitoring UI

#31020 Add container fields
  CHANGELOG.next.asciidoc
  auditbeat/docs/fields.asciidoc
  auditbeat/include/fields.go
  filebeat/docs/fields.asciidoc
  filebeat/include/fields.go
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  libbeat/_meta/fields.ecs.yml
  metricbeat/docs/fields.asciidoc
  metricbeat/include/fields/fields.go
  metricbeat/tests/system/test_base.py
  packetbeat/docs/fields.asciidoc
  packetbeat/include/fields.go
  winlogbeat/docs/fields.asciidoc
  winlogbeat/include/fields.go
  x-pack/functionbeat/docs/fields.asciidoc
  x-pack/functionbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
  x-pack/osquerybeat/docs/fields.asciidoc
  x-pack/osquerybeat/include/fields.go
Labels: backport-v8.2.0, Team:Cloudnative-Monitoring

#31017 docs: update docs versions 7.17.2
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#31002 Add workaround to cgroups self-monitoring error messages in 7.17 releases
  libbeat/cmd/instance/metrics/metrics.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#30978 Deal with docker reporting different capitalization for disk usage metrics
  CHANGELOG.next.asciidoc
  metricbeat/module/docker/diskio/_meta/data.json
  metricbeat/module/docker/diskio/diskio.go
  metricbeat/module/docker/diskio/diskio_integration_test.go
  metricbeat/module/docker/diskio/diskio_test.go
  metricbeat/module/docker/diskio/helper.go
Labels: bug, backport-skip, Team:Elastic-Agent-Data-Plane

#31008 {,x-pack/}{auditbeat,packetbeat,winlogbeat,filebeat/input/httpjson}: fix lint and silence linters
  auditbeat/main_test.go
  packetbeat/main.go
  packetbeat/main_test.go
  winlogbeat/main_test.go
  x-pack/auditbeat/main_test.go
  x-pack/filebeat/input/httpjson/config_auth.go
  x-pack/filebeat/input/httpjson/config_request.go
  x-pack/filebeat/input/httpjson/encoding.go
  x-pack/filebeat/input/httpjson/input_cursor.go
  x-pack/filebeat/input/httpjson/input_stateless.go
  x-pack/filebeat/input/httpjson/input_test.go
  x-pack/filebeat/input/httpjson/pagination.go
  x-pack/filebeat/input/httpjson/rate_limiter.go
  x-pack/filebeat/input/httpjson/rate_limiter_test.go
  x-pack/filebeat/input/httpjson/request.go
  x-pack/filebeat/input/httpjson/response.go
  x-pack/filebeat/input/httpjson/split.go
  x-pack/filebeat/input/httpjson/transform.go
  x-pack/filebeat/input/httpjson/transform_append.go
  x-pack/filebeat/input/httpjson/transform_append_test.go
  x-pack/filebeat/input/httpjson/transform_delete.go
  x-pack/filebeat/input/httpjson/transform_delete_test.go
  x-pack/filebeat/input/httpjson/transform_set.go
  x-pack/filebeat/input/httpjson/transform_set_test.go
  x-pack/filebeat/input/httpjson/transform_test.go
  x-pack/filebeat/input/httpjson/value_tpl.go
  x-pack/winlogbeat/main_test.go
Labels: cleanup, Team:Security-External Integrations, backport-skip, 8.2-candidate

#30730 x-pack/filebeat/input/httpjson: make sure interval data clearing happens before processing
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/request.go
  x-pack/filebeat/input/httpjson/response.go
Labels: bug, Team:Security-External Integrations, backport-v8.0.0, 8.2-candidate, backport-v8.1.0, backport-v7.17.0

#31033 [automation] update elastic stack version for testing 7.17.2-99f889e2
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30793 [Discuss] Update Codeowners file
  .github/CODEOWNERS
Labels: Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#30938 x-pack/filebeat/processors/decode_cef/cef: allow (*Event).Unpack to attempt to recover extensions
  CHANGELOG.next.asciidoc
  x-pack/filebeat/processors/decode_cef/cef/.gitignore
  x-pack/filebeat/processors/decode_cef/cef/cef.go
  x-pack/filebeat/processors/decode_cef/cef/cef.rl
  x-pack/filebeat/processors/decode_cef/cef/cef_actions.rl
  x-pack/filebeat/processors/decode_cef/cef/cef_test.go
  x-pack/filebeat/processors/decode_cef/cef/cmd/cef2json/cef2json.go
  x-pack/filebeat/processors/decode_cef/cef/parser.go
  x-pack/filebeat/processors/decode_cef/cef/parser.rl
  x-pack/filebeat/processors/decode_cef/cef/parser_recover.go
  x-pack/filebeat/processors/decode_cef/cef/parser_recover.rl
  x-pack/filebeat/processors/decode_cef/cef/types.go
  x-pack/filebeat/processors/decode_cef/decode_cef_test.go
Labels: bug, Team:Security-External Integrations, 8.2-candidate, 8.1-candidate, backport-v8.1.0

#30181 Populate ecs fields by pod and container metricsets
  CHANGELOG.next.asciidoc
  metricbeat/module/kubernetes/container/container.go
  metricbeat/module/kubernetes/container/container_test.go
  metricbeat/module/kubernetes/container/data.go
  metricbeat/module/kubernetes/pod/data.go
  metricbeat/module/kubernetes/pod/pod.go
Labels: backport-skip, Team:Cloudnative-Monitoring

#30399 Populate new container ecs fields by docker module
  CHANGELOG.next.asciidoc
  metricbeat/module/docker/cpu/data.go
  metricbeat/module/docker/diskio/data.go
  metricbeat/module/docker/memory/data.go
  metricbeat/module/docker/memory/memory_test.go
  metricbeat/module/docker/network/data.go
Labels: enhancement, Team:Integrations, backport-v8.1.0

#29816 [Filebeat][httpjson] httpjson chain calls
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/images/input-httpjson-chain-lifecycle.png
  x-pack/filebeat/docs/inputs/images/input-httpjson-lifecycle.png
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/chain.go
  x-pack/filebeat/input/httpjson/config.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/input_test.go
  x-pack/filebeat/input/httpjson/pagination.go
  x-pack/filebeat/input/httpjson/request.go
  x-pack/filebeat/input/httpjson/request_test.go
  x-pack/filebeat/input/httpjson/response.go
Labels: enhancement, Team:Integrations, Team:Security-External Integrations, Team:Elastic-Agent-Data-Plane, backport-v8.1.0

#30155 [winlogbeat] Retry EvtSubscribe from start if fails with strict mode
  CHANGELOG.next.asciidoc
  winlogbeat/beater/winlogbeat.go
  winlogbeat/eventlog/wineventlog.go
  winlogbeat/eventlog/wineventlog_experimental.go
  winlogbeat/sys/wineventlog/zsyscall_windows.go
  winlogbeat/tests/system/test_wineventlog.py
Labels: bug, Winlogbeat, Team:Security-External Integrations, backport-v8.0.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#31026 docs: update docs versions 8.1.2
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#31025 Populate container ecs fields in containerd module
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/containerd/blkio/_meta/test/containerd.v1.5.2.expected
  x-pack/metricbeat/module/containerd/blkio/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/containerd/blkio/blkio.go
  x-pack/metricbeat/module/containerd/cpu/_meta/test/containerd.v1.5.2.expected
  x-pack/metricbeat/module/containerd/cpu/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/containerd/cpu/cpu.go
  x-pack/metricbeat/module/containerd/memory/_meta/test/containerd.v1.5.2.expected
  x-pack/metricbeat/module/containerd/memory/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/containerd/memory/memory.go
Labels: backport-skip, Team:Cloudnative-Monitoring

#31041 Fix panic in the filestream harvester
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/internal/input-logfile/store.go
  filebeat/input/filestream/internal/input-logfile/store_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, v8.2.0, backport-v8.1.0
