Repository elastic/beats, pull requests merged in 2022-04, with the labels that each got.

#31099 [automation] update elastic stack version for testing 7.17.3-22be2d34
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#23221 Added Link to timebeat
  libbeat/docs/communitybeats.asciidoc
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#31081 Update CODEOWNERS file for 7.17
  .github/CODEOWNERS
Labels: needs_team

#31100 [automation] update elastic stack version for testing 8.1.2-ed029c28
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31103 Remove elastic agent kubernetes templates
  deploy/kubernetes/Makefile
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role-binding.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-service-account.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role-binding.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-service-account.yaml
Labels: needs_team, Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#31080 Enable k8s scheduler test
  metricbeat/module/kubernetes/scheduler/scheduler_integration_test.go
  metricbeat/module/kubernetes/test/integration.go
Labels: needs_team, kubernetes

#31105 Forward port 8.1.2 changelog to 8.2
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, backport-skip

#31108 Forward port 8.1.2 changelog to main
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#31119 [automation] update elastic stack version for testing 7.17.3-42e5086c
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31098 [automation] update elastic stack version for testing 8.3.0-1ecd9720
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31092 DRA: support for staging
  .ci/packaging.groovy
  .ci/scripts/prepare-release-manager.sh
Labels: Team:Automation, backport-v8.3.0, backport-v8.2.0

#31128 Skip branch 7.17
  .ci/packaging.groovy
Labels: automation, needs_team

#31135 ci: e2e-testing should fail the build
  .ci/packaging.groovy
Labels: Team:Automation, backport-v8.3.0, backport-v8.2.0

#31133 Remove functionbeat log message
  x-pack/functionbeat/function/beater/functionbeat.go
  x-pack/functionbeat/manager/beater/functionbeat.go
  x-pack/functionbeat/manager/cmd/root.go
Labels: Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v8.2.0

#31059 [Release] Update test environment to 8.3.0
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: in progress, release, automation, Team:Automation, backport-skip

#31062 Add missing fields in azure signin logs
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/azure/fields.go
  x-pack/filebeat/module/azure/signinlogs/_meta/fields.yml
  x-pack/filebeat/module/azure/signinlogs/test/test-non-interactive-user-signin.log
  x-pack/filebeat/module/azure/signinlogs/test/test-non-interactive-user-signin.log-expected.json
Labels: backport-v8.1.0, backport-v8.2.0, backport-v7.17.0, Team:Cloud-Monitoring

#31140 Remove the unused "fmt" import.
  x-pack/functionbeat/manager/cmd/root.go
Labels: Team:Elastic-Agent-Data-Plane, backport-v8.2.0

#31131 [Auditbeat] Mount /etc/machine-id in auditbeat test container
  x-pack/auditbeat/docker-compose.yml
Labels: Auditbeat, Team:Security-External Integrations

#26877 processors/util: ensure hardware addresses are not duplicated
  libbeat/processors/util/netinfo.go
  libbeat/processors/util/netinfo_test.go
Labels: Team:Security-External Integrations, 8.3-candidate

#31136 Fix typo in it-compliance pack name
  filebeat/docs/modules/osquery.asciidoc
  filebeat/module/osquery/_meta/docs.asciidoc
Labels: Team:Docs, backport-v8.0.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#31148 [automation] update elastic stack version for testing 8.3.0-657f2d50
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31149 [automation] update elastic stack version for testing 7.17.3-206df1ed
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31107 wrap all optional mapStr.Put in kuberntes module with debug logs
  metricbeat/module/docker/container/container.go
  metricbeat/module/docker/container/data.go
  metricbeat/module/kubernetes/apiserver/metricset.go
  metricbeat/module/kubernetes/container/container.go
  metricbeat/module/kubernetes/container/container_test.go
  metricbeat/module/kubernetes/container/data.go
  metricbeat/module/kubernetes/event/event.go
  metricbeat/module/kubernetes/event/event_test.go
  metricbeat/module/kubernetes/kubernetes.go
  metricbeat/module/kubernetes/node/data.go
  metricbeat/module/kubernetes/node/node.go
  metricbeat/module/kubernetes/node/node_test.go
  metricbeat/module/kubernetes/pod/data.go
  metricbeat/module/kubernetes/pod/pod.go
  metricbeat/module/kubernetes/pod/pod_test.go
  metricbeat/module/kubernetes/state_container/state_container.go
  metricbeat/module/kubernetes/system/data.go
  metricbeat/module/kubernetes/system/system.go
  metricbeat/module/kubernetes/system/system_test.go
  metricbeat/module/kubernetes/util/kubernetes.go
  metricbeat/module/kubernetes/util/kubernetes_test.go
  metricbeat/module/kubernetes/volume/data.go
  metricbeat/module/kubernetes/volume/volume.go
  metricbeat/module/kubernetes/volume/volume_test.go
Labels: enhancement, cleanup, backport-skip, Team:Cloudnative-Monitoring

#31158 Make the stale message for issues more friendly
  .github/stale.yml
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#31095 Fix export dashboards
  libbeat/kibana/client_test.go
  libbeat/tests/system/test_dashboard.py
Labels: cleanup, backport-skip, Team:Elastic-Agent-Data-Plane

#31164 Add automation for project board
  .github/workflows/elastic-agent-project-board.yml
Labels: Team:Elastic-Agent-Control-Plane

#31167 Support SASL/SCRAM authentication in the Kafka input.
  CHANGELOG.next.asciidoc
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/docs/inputs/input-kafka.asciidoc
  filebeat/filebeat.reference.yml
  filebeat/input/kafka/config.go
  filebeat/input/kafka/kafka_integration_test.go
  x-pack/filebeat/filebeat.reference.yml
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#31087 Include missing reference to syslog processor docs
  CHANGELOG.next.asciidoc
  libbeat/docs/processors-list.asciidoc
  libbeat/processors/syslog/docs/syslog.asciidoc
Labels: bug, docs, Team:Security-External Integrations, Team:Elastic-Agent-Data-Plane, backport-v8.2.0

#30962 [Filebeat] Add URL Encode template function for httpjson input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/value_tpl.go
  x-pack/filebeat/input/httpjson/value_tpl_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-v8.3.0

#31102 x-pack/winlogbeat: add parent process ID to new process creation events
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/security/ingest/security.yml
  x-pack/winlogbeat/module/security/test/testdata/security-windows2019_4688_Process_Created.evtx.golden.json
Labels: enhancement, Team:Security-External Integrations, backport-skip, 8.3-candidate

#31172 [automation] update elastic stack version for testing 8.3.0-00f4f855
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31175 [automation] update elastic stack version for testing 7.17.3-60b577ee
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31173 [automation] update elastic stack version for testing 8.1.3-c3f4b7e6
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31048 Put data stream so there is no need for additional permissions
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  libbeat/_meta/config/setup.template.reference.yml.tmpl
  libbeat/docs/template-config.asciidoc
  libbeat/esleg/eslegclient/connection.go
  libbeat/template/config.go
  libbeat/template/load.go
  libbeat/template/load_integration_test.go
  libbeat/template/load_test.go
  libbeat/template/testdata/fields-data-stream.json
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Elastic-Agent-Data-Plane, backport-v8.2.0

#31177 Update elastic-agent-project-board.yml
  .github/workflows/elastic-agent-project-board.yml
Labels: Team:Elastic-Agent-Data-Plane

#31014 [libbeat][aws] Fix AWS config initialization issue when using a role
  CHANGELOG.next.asciidoc
  x-pack/libbeat/common/aws/credentials.go
Labels: bug, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0, Team:Cloud-Monitoring

#27869 Add dashboard string_replacements config
  libbeat/dashboards/config.go
  libbeat/dashboards/kibana_loader.go
  libbeat/docs/dashboardsconfig.asciidoc
Labels: Team:Elastic-Agent, backport-skip, Team:Elastic-Agent-Data-Plane

#16369 Remove docker and kubernetes tests and metadata for AIX
  dev-tools/mage/config.go
  libbeat/scripts/Makefile
  metricbeat/mb/testing/data/data_test.go
Labels: [zube]: In Review, Team:Services, backport-skip

#31072 libbeat/instrumentation: Update apm dep to v2.0.0
  NOTICE.txt
  go.mod
  go.sum
  libbeat/common/transport/httpcommon/httpcommon.go
  libbeat/esleg/eslegclient/bulkapi.go
  libbeat/esleg/eslegclient/connection.go
  libbeat/instrumentation/instrumentation.go
  libbeat/monitoring/report/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/publisher/pipeline/client_worker.go
  libbeat/publisher/pipeline/client_worker_test.go
  libbeat/publisher/pipeline/module.go
Labels: enhancement, Team:apm, backport-skip

#31184 Extend wait timeout in python tests
  libbeat/tests/system/beat/beat.py
Labels: Team:Elastic-Agent-Data-Plane

#31114 [Heartbeat] Allow browser monitors on ARM
  CHANGELOG.next.asciidoc
  heartbeat/security/security.go
Labels: bug, Heartbeat, Team:Uptime, backport-v8.2.0

#31174 [automation] update elastic stack version for testing 8.2.0-fdfc79e3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31199 [automation] update elastic stack version for testing 8.3.0-5bb6f468
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31198 [automation] update elastic stack version for testing 8.2.0-c56d8262
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31201 [automation] update elastic stack version for testing 7.17.3-0bbada2a
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31006 Docs: Adjust connection string
  metricbeat/docs/modules/oracle.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/oracle/_meta/config.yml
  x-pack/metricbeat/modules.d/oracle.yml.disabled
Labels: backport-skip, Team:Service-Integrations

#31200 [automation] update elastic stack version for testing 8.1.3-6f211282
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29728 [DOC] Typo for Juniper module / Junos fileset example
  filebeat/docs/modules/juniper.asciidoc
  x-pack/filebeat/module/juniper/_meta/docs.asciidoc
Labels: docs, Team:Docs, backport-v7.12.0

#30029 Skip flaky: test_http_endpoint_missing_auth_value
  x-pack/filebeat/tests/system/test_http_endpoint.py
Labels: Team:SIEM, Team:Integrations, backport-v8.0.0

#30395 Add event data generation to dev docs
  docs/devguide/testing.asciidoc
Labels: docs, Team:Integrations, backport-skip

#31197 Checkpoint firewall: Allow for trailing space
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/checkpoint/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/checkpoint/firewall/test/trailing-space.log
  x-pack/filebeat/module/checkpoint/firewall/test/trailing-space.log-expected.json
Labels: bug, Filebeat, Team:Security-External Integrations, needs_integration_sync, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#31214 Add known issue entry to changelog about Beats not loading data streams correctly in 8.1
  CHANGELOG.asciidoc
Labels: Team:Elastic-Agent-Data-Plane

#31217 Add known issue entry to changelog about Beats not loading data streams correctly in 8.0
  CHANGELOG.asciidoc
Labels: Team:Elastic-Agent-Data-Plane

#31192 Backport elastic-agent/pull/255
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
  x-pack/elastic-agent/pkg/agent/operation/common_test.go
  x-pack/elastic-agent/pkg/agent/operation/operation_verify.go
  x-pack/elastic-agent/pkg/artifact/download/composed/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/composed/verifier_test.go
  x-pack/elastic-agent/pkg/artifact/download/fs/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/fs/verifier_test.go
  x-pack/elastic-agent/pkg/artifact/download/http/elastic_test.go
  x-pack/elastic-agent/pkg/artifact/download/http/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/verifier.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.1.0

#31195 Remove Npcap install prerequisite for Windows
  packetbeat/docs/gettingstarted.asciidoc
  packetbeat/docs/tab-widgets/install-libpcap.asciidoc
Labels: Packetbeat, needs_team, backport-v8.1.0, backport-v8.2.0

#31229 [automation] update elastic stack version for testing 8.3.0-76e0128f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31230 [automation] update elastic stack version for testing 7.17.3-2d046908
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31228 [automation] update elastic stack version for testing 8.1.3-25093d2a
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31236 [automation] update elastic stack version for testing 8.2.0-bcbc1a13
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31235 [automation] update elastic stack version for testing 8.3.0-8d19ff01
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31238 [automation] update elastic stack version for testing 7.17.3-4c0e3956
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31237 [automation] update elastic stack version for testing 8.1.3-91a16370
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31191 doc: fix multiline examples in documentation
  filebeat/docs/inputs/input-filestream-reader-options.asciidoc
Labels: docs, Team:Elastic-Agent-Data-Plane, backport-v8.1.0

#31226 Document mage and GVM in the developer guide
  Jenkinsfile
  docs/devguide/contributing.asciidoc
Labels: Team:Automation, Team:Elastic-Agent-Data-Plane

#31244 ci: cancel after gitCheckout to avoid DoS
  Jenkinsfile
Labels: Team:Automation, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#31240 filestream: use try lock instead of lock when migrating identifiers
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/internal/input-logfile/store.go
Labels: bug, review, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#31227 [Filebeat] fix m365_defender pipeline bug
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/microsoft/m365_defender/ingest/pipeline.yml
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log-expected.json
Labels: bug, Filebeat, Team:Security-External Integrations, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#31256 [automation] update elastic stack version for testing 8.3.0-2c8f9574
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31257 [automation] update elastic stack version for testing 8.1.3-9689383f
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31146 [heartbeat][docs] Add note about ensuring correct index settings for uptime
  libbeat/docs/upgrading.asciidoc
Labels: docs, Heartbeat, Team:Uptime

#31130 libbeat: log debug for `proxy_url` and fixed docs
  libbeat/common/transport/proxy.go
  libbeat/esleg/eslegclient/connection.go
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
  libbeat/outputs/elasticsearch/elasticsearch.go
Labels: docs, libbeat, Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v7.17.0

#31260 Update qa-labels.yml to fix type mismatch
  .github/workflows/qa-labels.yml
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane

#31243 Add support for port mapping in docker hints
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/docker/docker.go
  metricbeat/docs/autodiscover-hints.asciidoc
Labels: autodiscovery, needs_team, 8.3 candidate

#31262 docs: update docs versions 7.17.3
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#31272 [automation] update elastic stack version for testing 8.2.0-a99722cc
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31273 [automation] update elastic stack version for testing 7.17.3-b688e1c0
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31274 [automation] update elastic stack version for testing 8.1.3-f8a17b61
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31268 Detect new files under known paths in filestream input
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/fswatch.go
  filebeat/input/filestream/fswatch_test.go
  filebeat/input/filestream/fswatch_test_non_windows.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#31168 Simplify TLS config deserialization
  libbeat/common/transport/tlscommon/types.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#30971 removing info log
  filebeat/input/filestream/fswatch.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#31288 Small pipeline cleanup removing some unused data fields
  libbeat/publisher/pipeline/pipeline.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#31291 x-pack/winlogbeat/module/routing/ingest: fix typo for channel name
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/routing/ingest/routing.yml
Labels: bug, Team:Security-External Integrations, backport-v8.0.0, 8.3-candidate, backport-v8.1.0, backport-v8.2.0

#31297 [automation] update elastic stack version for testing 8.2.0-39d3fe7f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31296 [automation] update elastic stack version for testing 8.3.0-4be61f32
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31298 [automation] update elastic stack version for testing 7.17.3-d599ee07
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31299 [automation] update elastic stack version for testing 8.1.3-bb164e02
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31276 [Stack Monitoring] Readme for kibana module
  metricbeat/module/kibana/_meta/README.md
Labels: docs, Feature: Stack Monitoring, Team:Infra Monitoring UI

#31302 [libbeat] Remove unused fields and functions in the memory queue
  libbeat/publisher/queue/memqueue/ackloop.go
  libbeat/publisher/queue/memqueue/batchbuf.go
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/memqueue/buf.go
  libbeat/publisher/queue/memqueue/consume.go
  libbeat/publisher/queue/memqueue/doc.go
  libbeat/publisher/queue/memqueue/eventloop.go
  libbeat/publisher/queue/memqueue/internal_api.go
  libbeat/publisher/queue/memqueue/log.go
  libbeat/publisher/queue/memqueue/produce.go
  libbeat/publisher/queue/memqueue/queue_test.go
  libbeat/publisher/queue/memqueue/ringbuf.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#31311 [automation] update elastic stack version for testing 8.3.0-55ba6f37
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31314 [automation] update elastic stack version for testing 7.17.3-a0d290fb
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31313 [automation] update elastic stack version for testing 8.2.0-edf55ea1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31312 [automation] update elastic stack version for testing 8.1.3-5c80e943
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31254 libbeat/reader/syslog: relax timestamp parsing to allow leading zero
  CHANGELOG.next.asciidoc
  libbeat/reader/syslog/docs/syslog.asciidoc
  libbeat/reader/syslog/parser/common.rl
  libbeat/reader/syslog/rfc3164_gen.go
  libbeat/reader/syslog/rfc3164_test.go
Labels: enhancement, Team:Security-External Integrations, 8.3-candidate, backport-v8.2.0

#31259 [Oracle Module] Change tablespace metricset collection period
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/oracle.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/oracle/_meta/config.yml
  x-pack/metricbeat/module/oracle/tablespace/data_test.go
  x-pack/metricbeat/module/oracle/tablespace/metricset.go
  x-pack/metricbeat/modules.d/oracle.yml.disabled
Labels: Team:Service-Integrations

#31289 Define a queue metrics reporter interface
  libbeat/publisher/pipeline/pipeline_test.go
  libbeat/publisher/queue/diskqueue/queue.go
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/queue.go
Labels: Team:Elastic-Agent-Data-Plane, v8.3.0

#31323 [automation] update elastic stack version for testing 8.2.0-c65cb8e3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31322 [automation] update elastic stack version for testing 8.3.0-c655cda8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31320 [automation] update elastic stack version for testing 7.17.3-feda78d8
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31321 [automation] update elastic stack version for testing 8.1.3-28740185
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31325 docs: Prepare Changelog for 7.17.3
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#31326 docs: Prepare Changelog for 8.1.3
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#31331 x-pack/winlogbeat: set event.module to module name
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/powershell/ingest/powershell.yml
  x-pack/winlogbeat/module/powershell/ingest/powershell_operational.yml
  x-pack/winlogbeat/module/security/ingest/security.yml
  x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml
Labels: bug, Team:Security-External Integrations, 8.3-candidate, backport-v8.1.0, backport-v8.2.0

#31336 [automation] update elastic stack version for testing 8.2.0-3a7e2f99
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31338 [automation] update elastic stack version for testing 8.1.3-2a8b1f31
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31279 Azure: add storage_account_container config option
  CHANGELOG.next.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/input/azureeventhub/config.go
  x-pack/filebeat/module/azure/_meta/config.yml
  x-pack/filebeat/module/azure/activitylogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/activitylogs/manifest.yml
  x-pack/filebeat/module/azure/auditlogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/auditlogs/manifest.yml
  x-pack/filebeat/module/azure/platformlogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/platformlogs/manifest.yml
  x-pack/filebeat/module/azure/signinlogs/config/azure-eventhub.yml
  x-pack/filebeat/module/azure/signinlogs/manifest.yml
  x-pack/filebeat/modules.d/azure.yml.disabled
Labels: enhancement, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0, Team:Cloud-Monitoring

#31328 Forward port 8.1.3 changelog to 8.2
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs

#31354 fix: use Debian 10 for mips, ppc, and s390x
  dev-tools/mage/crossbuild.go
Labels: Team:Automation, backport-v8.2.0

#31353 Forward port 8.1.3 changelog to main
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, Team:Elastic-Agent-Data-Plane

#31333 changelog: fix missed pr number
  CHANGELOG.next.asciidoc
Labels: bug, Team:Security-External Integrations, 8.3-candidate, backport-v8.1.0, backport-v8.2.0

#31295 x-pack/filebeat/input/netflow: replace invalid field value
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/netflow/convert.go
  x-pack/filebeat/input/netflow/testdata/golden/ipfix_cisco.pcap.golden.json
Labels: bug, Team:Security-External Integrations, 8.3-candidate, backport-v8.1.0, backport-v8.2.0

#31366 [automation] update elastic stack version for testing 8.2.0-a7e9513d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31365 [automation] update elastic stack version for testing 7.17.3-b148b9ca
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31367 [automation] update elastic stack version for testing 8.1.3-0c4e7b42
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31341 Add orchestrator cluster ECS fields in k8s events
  CHANGELOG.next.asciidoc
  metricbeat/module/kubernetes/event/event.go
Labels: needs_team, v8.3.0, backport-v8.3.0

#31266 [Release] Update version to 8.1.4
  libbeat/version/version.go
Labels: release, Team:Automation

#31376 [automation] update elastic stack version for testing 8.2.0-000e1c18
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31375 [automation] update elastic stack version for testing 7.17.3-e9aee937
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31372 [filebeat] Fix pagination bug that skipped events when more than one page is present
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/google_workspace/admin/config/config.yml
  x-pack/filebeat/module/google_workspace/drive/config/config.yml
  x-pack/filebeat/module/google_workspace/groups/config/config.yml
  x-pack/filebeat/module/google_workspace/login/config/config.yml
  x-pack/filebeat/module/google_workspace/saml/config/config.yml
  x-pack/filebeat/module/google_workspace/user_accounts/config/config.yml
Labels: bug, Team:Security-External Integrations, backport-v8.0.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#31369 Update Go to v1.17.9
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: enhancement, Team:Elastic-Agent-Control-Plane, v8.2.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#31390 [automation] update elastic stack version for testing 8.2.0-c47183cf
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31391 [automation] update elastic stack version for testing 7.17.4-51efa5cc
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31392 [automation] update elastic stack version for testing 8.1.4-4911e5d4
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31402 [automation] update elastic stack version for testing 8.2.0-14a8abdc
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31404 [automation] update elastic stack version for testing 7.17.4-4d7a6e74
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31403 [automation] update elastic stack version for testing 8.1.4-bc369beb
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31265 [Release] Update test environments for 7.17.4
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#30869 [Heartbeat] Enable Heartbeat to run when elastic-agent container is executed as root
  CHANGELOG.next.asciidoc
  heartbeat/security/security.go
  libbeat/paths/paths.go
Labels: bug, Team:Uptime, release-note:fix, Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#31410 correction on custom beat generator
  libbeat/docs/communitybeats.asciidoc
Labels: needs_team

#31388 [Filebeat] sophos.xg - Handle new log field names
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/sophos/fields.go
  x-pack/filebeat/module/sophos/xg/_meta/fields.yml
  x-pack/filebeat/module/sophos/xg/config/config.yml
  x-pack/filebeat/module/sophos/xg/ingest/antispam.yml
  x-pack/filebeat/module/sophos/xg/ingest/antivirus.yml
  x-pack/filebeat/module/sophos/xg/ingest/atp.yml
  x-pack/filebeat/module/sophos/xg/ingest/cfilter.yml
  x-pack/filebeat/module/sophos/xg/ingest/event.yml
  x-pack/filebeat/module/sophos/xg/ingest/firewall.yml
  x-pack/filebeat/module/sophos/xg/ingest/idp.yml
  x-pack/filebeat/module/sophos/xg/ingest/pipeline.yml
  x-pack/filebeat/module/sophos/xg/ingest/sandstorm.yml
  x-pack/filebeat/module/sophos/xg/ingest/systemhealth.yml
  x-pack/filebeat/module/sophos/xg/ingest/waf.yml
  x-pack/filebeat/module/sophos/xg/ingest/wifi.yml
  x-pack/filebeat/module/sophos/xg/manifest.yml
  x-pack/filebeat/module/sophos/xg/test/anti-spam.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/anti-virus.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/atp.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/cfilter.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/event.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/firewall.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/idp.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/sandbox.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/system-health.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/waf.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/wifi.log-expected.json
Labels: Filebeat, Team:Security-External Integrations

#30859 allow multi instance sql server
  CHANGELOG-developer.next.asciidoc
  x-pack/metricbeat/module/mssql/performance/_meta/data.json
  x-pack/metricbeat/module/mssql/performance/performance.go
Labels: Team:Integrations, backport-skip

#31415 [automation] update elastic stack version for testing 8.2.0-63f66f47
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31412 [automation] update elastic stack version for testing 7.17.4-073e030e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31413 [automation] update elastic stack version for testing 8.1.4-96de35ab
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31013 Improve handling of disabled commands in Zookeeper Metricbeat module
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/zookeeper.asciidoc
  metricbeat/module/zookeeper/_meta/docs.asciidoc
  metricbeat/module/zookeeper/connection/connection.go
  metricbeat/module/zookeeper/connection/connection_test.go
  metricbeat/module/zookeeper/connection/data.go
Labels: backport-v8.1.0, backport-v8.2.0, Team:Service-Integrations

#31409 Add breaking changes for Beats 8.2
  libbeat/docs/release-notes/breaking/breaking-8.2.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
Labels: docs, needs_team, v7.8.2, backport-v8.2.0

#31425 List the CHANGELOG files without code owners.
  .github/CODEOWNERS
Labels: Team:Elastic-Agent-Data-Plane

#31414 [automation] update elastic stack version for testing 8.3.0-ed7759bd
  libbeat/docker-compose.yml
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  testing/environments/snapshot.yml
  x-pack/libbeat/docker-compose.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31432 [automation] update elastic stack version for testing 8.2.0-bdd1c93d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31429 [automation] update elastic stack version for testing 8.3.0-6b041601
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31430 [automation] update elastic stack version for testing 7.17.4-a30db1f9
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31431 [automation] update elastic stack version for testing 8.1.4-483e60fd
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31241 Example document added to data.json file
  x-pack/metricbeat/module/cockroachdb/status/_meta/data.json
Labels: needs_team

#31399 fix Go Report badge
  README.md
Labels: needs_team

#31433 Linters: remove `godox` and add exclude rule for `forbidigo` in mage files
  .golangci.yml
  dev-tools/templates/.golangci.yml
Labels: Team:Elastic-Agent-Data-Plane

#31405 Add heartbeat telemetry logs (step count and duration)
  heartbeat/hbtest/hbtestutil.go
  heartbeat/look/look.go
  heartbeat/look/look_test.go
  heartbeat/monitors/active/http/http_test.go
  heartbeat/monitors/active/tcp/socks5_test.go
  heartbeat/monitors/active/tcp/tcp_test.go
  heartbeat/monitors/logger/logger.go
  heartbeat/monitors/logger/logger_test.go
  heartbeat/monitors/mocks_test.go
  heartbeat/monitors/wrappers/wrappers.go
  heartbeat/monitors/wrappers/wrappers_test.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
Labels: enhancement, Team:Uptime, backport-v8.3.0, backport-v8.2.0

#31384 [azureeventhub] SA container: replace underscores(_) with hyphens(-)
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/azureeventhub/config.go
  x-pack/filebeat/input/azureeventhub/config_test.go
Labels: enhancement, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0, Team:Cloud-Monitoring

#31446 [libbeat] Store syslog version as string
  CHANGELOG.next.asciidoc
  libbeat/processors/syslog/syslog_test.go
  libbeat/reader/syslog/message.go
  libbeat/reader/syslog/message_test.go
  libbeat/reader/syslog/rfc3164_test.go
  libbeat/reader/syslog/rfc5424_test.go
  libbeat/reader/syslog/syslog_test.go
Labels: bug, :Processors, Team:Security-External Integrations, backport-v8.3.0, backport-v8.2.0

#31449 [7.17](backport #312) Improve sync handling and errors
  libbeat/common/file/helper_aix.go
  libbeat/common/file/helper_other.go
  libbeat/common/file/helper_windows.go
  x-pack/elastic-agent/pkg/agent/storage/disk_store.go
  x-pack/elastic-agent/pkg/agent/storage/replace_store.go
Labels: Team:Elastic-Agent-Control-Plane

#31442 [8.2] ci: configure GCP at the stage level
  Jenkinsfile
Labels: automation, Team:Automation

#31443 [7.17] ci: configure GCP at the stage level
  Jenkinsfile
Labels: automation, Team:Automation
