Repository elastic/beats, pull requests merged in 2022-10, with the labels that each got.

#33242 docs: Prepare Changelog for 8.4.3
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#33247 [automation] update elastic stack version for testing 8.4.3-5e0dd488
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33246 [automation] update elastic stack version for testing 8.5.0-49b2dce3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33214 [Metricbeat] Fix index and cluster_stats schemas in the ES module to account for missing fields
  metricbeat/docs/fields.asciidoc
  metricbeat/module/elasticsearch/cluster_stats/_meta/data.json
  metricbeat/module/elasticsearch/cluster_stats/_meta/fields.yml
  metricbeat/module/elasticsearch/cluster_stats/data.go
  metricbeat/module/elasticsearch/fields.go
  metricbeat/module/elasticsearch/index/_meta/data.json
  metricbeat/module/elasticsearch/index/data.go
Labels: bug, Team:Infra Monitoring UI, backport-v8.5.0

#33026 First pass at auditbeat support
  x-pack/auditbeat/cmd/root.go
Labels: Team:Elastic-Agent-Data-Plane, v8.6.0

#33222 Fix logstash loadavg types (non-xpack cases)
  metricbeat/docs/fields.asciidoc
  metricbeat/module/logstash/fields.go
  metricbeat/module/logstash/node_stats/_meta/fields.yml
Labels: bug, Feature: Stack Monitoring, backport-skip, Team:Infra Monitoring UI

#33253 [automation] update elastic stack version for testing 8.6.0-0fca2953
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33252 [automation] update elastic stack version for testing 8.4.3-ff95b7c5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33251 [automation] update elastic stack version for testing 7.17.7-70d4ef7d
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33236 [filebeat] Fix ingest pipeline overwriting module field values
  filebeat/module/kibana/log/config/log.yml
  filebeat/module/kibana/log/ingest/pipeline-7.yml
  filebeat/module/kibana/log/ingest/pipeline-ecs.yml
  filebeat/module/kibana/log/test/log.830.log-expected.json
Labels: bug, Team:Infra Monitoring UI, Module:kibana, backport-v8.4.0, backport-v8.5.0

#33265 [automation] update elastic stack version for testing 8.6.0-e4c15f15
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33266 [automation] update elastic stack version for testing 7.17.7-a343880e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33267 [automation] update elastic stack version for testing 8.5.0-58624073
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33198 [Release] Update version to 8.4.4
  libbeat/version/version.go
Labels: release, Team:Automation

#33199 [Release] Update test environments for 8.4.4
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#33259 [Filebeat] Fix input metrics not being unregistered for aws-s3, aws-cloudwatch, lumberjack
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awscloudwatch/metrics.go
  x-pack/filebeat/input/awss3/metrics.go
  x-pack/filebeat/input/awss3/metrics_test.go
  x-pack/filebeat/input/lumberjack/metrics.go
Labels: bug, Filebeat, Team:Security-External Integrations, backport-v7.17.0, Team:Cloud-Monitoring, backport-v8.4.0, backport-v8.5.0

#33283 [automation] update elastic stack version for testing 8.4.4-ac374c4b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33281 [automation] update elastic stack version for testing 7.17.7-f9849b81
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33280 [automation] update elastic stack version for testing 8.5.0-c52257ee
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32715 packetbeat/decoder: reset multilayer decoding layers for each sniffed packet
  packetbeat/decoder/decoder.go
Labels: bug, Packetbeat, Team:Security-External Integrations, backport-skip, 8.6-candidate

#33291 [automation] update elastic stack version for testing 8.4.4-17ce02d0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33288 [automation] update elastic stack version for testing 8.5.0-7d416dc4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33290 [automation] update elastic stack version for testing 7.17.7-3947c049
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33289 [automation] update elastic stack version for testing 8.6.0-7c9f25a9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33293 [Heartbeat] Fix enabled flag usage in case of streams
  CHANGELOG.next.asciidoc
  heartbeat/monitors/factory.go
  heartbeat/monitors/factory_test.go
Labels: bug, Team:Uptime, v8.5.0, backport-v8.5.0

#33263 Remove incorrect ES field
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/elasticsearch/fields.go
  metricbeat/module/elasticsearch/node_stats/_meta/fields.yml
Labels: bug, Team:Infra Monitoring UI, backport-v8.5.0

#33105 Change max query size for GetMetricData API to 500 and add RecentlyActive config
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/billing/billing.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
  x-pack/metricbeat/module/azure/billing/billing.go
Labels: bug, Team:Automation, Team:Cloud-Monitoring, backport-v8.4.0, backport-v8.5.0

#33302 [automation] update elastic stack version for testing 8.4.4-221d2ff4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33305 [automation] update elastic stack version for testing 8.6.0-c49fac70
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33304 [automation] update elastic stack version for testing 7.17.7-32fc38cc
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33303 [automation] update elastic stack version for testing 8.5.0-4f4df9f4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33240 Add not dedoted k8s pod labels in autodiscover provider to be used for templating, exactly like annotations
  NOTICE.txt
  go.mod
  go.sum
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/pod_test.go
Labels: Team:Cloudnative-Monitoring

#33287 [automation] Update go release version 1.18.7
  .go-version
  .golangci.yml
  auditbeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
Labels: automation, needs_team, dependency, backport-skip, backport-v8.5.0

#33157 Add heartbeat support for V2
  x-pack/heartbeat/cmd/root.go
Labels: Team:Elastic-Agent-Data-Plane, v8.6.0

#33315 [Heartbeat] Only use one provider list in k8s configmap example
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/heartbeat/heartbeat-configmap.yaml
Labels: bug, Team:Uptime, backport-skip

#33231 [Heartbeat] Fix expiration of cert chains calculation
  CHANGELOG.next.asciidoc
  heartbeat/hbtest/hbtestutil.go
  heartbeat/monitors/active/dialchain/tlsmeta/tlsmeta.go
  heartbeat/monitors/active/dialchain/tlsmeta/tlsmeta_test.go
  heartbeat/monitors/active/http/task.go
  heartbeat/monitors/active/tcp/tcp.go
Labels: bug, Team:Uptime

#33310 Fix errors for non-synth capable instances
  heartbeat/ecserr/ecserr.go
  heartbeat/monitors/monitor.go
  heartbeat/monitors/wrappers/wrappers.go
  heartbeat/monitors/wrappers/wrappers_test.go
  x-pack/heartbeat/monitors/browser/browser.go
Labels: bug, Team:Uptime, backport-v8.5.0

#33326 [automation] update elastic stack version for testing 8.4.4-5fbb5bd0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33325 [automation] update elastic stack version for testing 7.17.7-8081bbcb
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33323 [automation] update elastic stack version for testing 8.6.0-5a8d757d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33169 add pid awareness to file locking
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  libbeat/cmd/instance/beat.go
  libbeat/cmd/instance/locker.go
  libbeat/cmd/instance/locker_test.go
  libbeat/cmd/instance/locks/lock.go
  libbeat/cmd/instance/locks/lock_test.go
  libbeat/cmd/instance/locks/process_lookup_cgo.go
  libbeat/cmd/instance/locks/process_lookup_stub.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#33306 Fix sample config in log rotation docs
  filebeat/docs/filebeat-log-rotation.asciidoc
Labels: Team:Elastic-Agent-Data-Plane, backport-v7.17.0, backport-v8.5.0

#33297 [DOCS] Add banner to encourage Functionbeat users to move to ESF
  x-pack/functionbeat/docs/page_header.html
Labels: Functionbeat, Team:Docs, v8.5.0, backport-v8.5.0

#33286 packetbeat/protos/dns: clean up package
  packetbeat/protos/dns/dns.go
  packetbeat/protos/dns/dns_tcp.go
  packetbeat/protos/dns/dns_test.go
  packetbeat/protos/dns/dns_udp.go
  packetbeat/protos/dns/names.go
  packetbeat/protos/dns/names_test.go
Labels: Packetbeat, cleanup, Team:Security-External Integrations, backport-skip, 8.6 candidate

#33340 [automation] update elastic stack version for testing 8.5.0-fe2e6147
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33338 [automation] update elastic stack version for testing 8.4.4-1129f33b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33339 [automation] update elastic stack version for testing 8.6.0-40086bc7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33330 Update mage to fix the CI
  NOTICE.txt
  dev-tools/make/mage-install.mk
  go.mod
  go.sum
Labels: ci, Team:Elastic-Agent-Data-Plane

#33335 Fix unchecked stream_id
  x-pack/libbeat/management/generate.go
Labels: bug, Team:Elastic-Agent-Data-Plane, 8.6-candidate

#33269 Fix docker provider add_fields processors
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/composable/providers/docker/docker.go
  x-pack/elastic-agent/pkg/composable/providers/docker/docker_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane

#33336 Update elastic-agent-libs for output panic fix
  CHANGELOG.next.asciidoc
  NOTICE.txt
  filebeat/docs/filebeat-log-rotation.asciidoc
  go.mod
  go.sum
  heartbeat/ecserr/ecserr.go
  heartbeat/monitors/monitor.go
  heartbeat/monitors/wrappers/wrappers.go
  heartbeat/monitors/wrappers/wrappers_test.go
  libbeat/cmd/instance/beat.go
  libbeat/cmd/instance/locker.go
  libbeat/cmd/instance/locker_test.go
  libbeat/cmd/instance/locks/lock.go
  libbeat/cmd/instance/locks/lock_test.go
  libbeat/cmd/instance/locks/process_lookup_cgo.go
  libbeat/cmd/instance/locks/process_lookup_stub.go
  packetbeat/protos/dns/dns.go
  packetbeat/protos/dns/dns_tcp.go
  packetbeat/protos/dns/dns_test.go
  packetbeat/protos/dns/dns_udp.go
  packetbeat/protos/dns/names.go
  packetbeat/protos/dns/names_test.go
  testing/environments/snapshot.yml
  x-pack/functionbeat/docs/page_header.html
  x-pack/heartbeat/monitors/browser/browser.go
Labels: bug, Team:Elastic-Agent-Data-Plane, 8.6-candidate

#33349 [automation] update elastic stack version for testing 8.6.0-233dc5d4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33351 [automation] update elastic stack version for testing 8.4.4-fdf1902b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33350 [automation] update elastic stack version for testing 7.17.7-40d7eba9
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33348 [automation] update elastic stack version for testing 8.5.0-976bca07
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33368 [automation] update elastic stack version for testing 8.5.0-f8c98e5d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33366 [automation] update elastic stack version for testing 7.17.7-e7a47621
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33365 [automation] update elastic stack version for testing 8.4.4-2db0c963
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33367 [automation] update elastic stack version for testing 8.6.0-54a302f0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33294 ci: enable next minor for daily and weekly automation
  .ci/schedule-daily.groovy
  .ci/schedule-weekly.groovy
Labels: automation, Team:Automation, backport-skip

#33358 [Metricbeat] Add time_throttled in ES node_stats metricset (#143337)
  metricbeat/module/elasticsearch/node_stats/data.go
Labels: bug, Team:Infra Monitoring UI, Module:elasticsearch, backport-v8.5.0

#33370 ci: remove e2e-testing in the main pipeline for elastic-agent
  x-pack/elastic-agent/Jenkinsfile.yml
Labels: automation, Team:Automation, backport-skip

#33094 filebeat: fix check against nil
  filebeat/input/log/harvester.go
  filebeat/input/log/input.go
Labels: Team:Elastic-Agent-Data-Plane, bugfix

#33362 [Heartbeat] Use stack_release label for synthetics npm install
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: enhancement, Heartbeat, Team:Uptime

#33379 [automation] update elastic stack version for testing 8.6.0-cae815eb
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33381 [automation] update elastic stack version for testing 8.4.4-93b2bfdf
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33378 [automation] update elastic stack version for testing 8.5.0-7c74e950
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33380 [automation] update elastic stack version for testing 7.17.7-f82fb944
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33308 Update README.md for Metricbeat on K8s
  CHANGELOG.next.asciidoc
  deploy/kubernetes/metricbeat/README.md
Labels: review, Metricbeat, Team:Cloudnative-Monitoring

#33384 Update and rename elastic-agent-project-board.yml to platform-ingest-…
  .github/workflows/elastic-agent-project-board.yml
  .github/workflows/platform-ingest-project-board.yml
Labels: needs_team

#33388 docs: update docs versions 7.17.7
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#33397 [automation] update elastic stack version for testing 7.17.7-c42c4e01
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33399 [automation] update elastic stack version for testing 8.5.0-792499b4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33396 [automation] update elastic stack version for testing 8.6.0-6545f2df
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33398 [automation] update elastic stack version for testing 8.4.4-e97ba82f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33400 [filebeat] Fix httpjson page number initialization and docs
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/input_test.go
  x-pack/filebeat/input/httpjson/pagination.go
  x-pack/filebeat/input/httpjson/request_test.go
Labels: bug, Filebeat, Team:Security-External Integrations, backport-v7.17.0, backport-v8.5.0

#33387 docs: Prepare Changelog for 7.17.7
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#33386 docs: Prepare Changelog for 8.5.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#33406 [Heartbeat] Remove monitor ID from state ID
  heartbeat/monitors/wrappers/monitorstate/monitorstate.go
Labels: Team:Uptime, technical debt, v8.6.0

#33411 [automation] update elastic stack version for testing 8.6.0-055acc83
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33412 [automation] update elastic stack version for testing 7.17.7-55166c00
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32126 [iptables module] Accept TOS to not provide 0x HEX format
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/iptables/log/ingest/pipeline.yml
  x-pack/filebeat/module/iptables/log/test/iptables.log
  x-pack/filebeat/module/iptables/log/test/iptables.log-expected.json
Labels: enhancement, Team:Integrations, Team:Security-External Integrations, needs_integration_sync

#33428 [automation] update elastic stack version for testing 7.17.7-60386d02
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33429 [automation] update elastic stack version for testing 8.5.0-754ef325
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33426 [automation] update elastic stack version for testing 8.6.0-baf193e8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33427 [automation] update elastic stack version for testing 8.4.4-4edb5c6b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33394 [Filebeat aws] Use default limit for FilterLogEvents API
  x-pack/filebeat/input/awscloudwatch/cloudwatch.go
  x-pack/filebeat/input/cometd/cometd_integration_test.go
Labels: needs_team

#33437 [automation] update elastic stack version for testing 8.4.4-9b801d60
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33436 [automation] update elastic stack version for testing 7.17.7-e6ce36d2
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33435 [automation] update elastic stack version for testing 8.5.0-d7b01592
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33438 [automation] update elastic stack version for testing 8.6.0-22d60ec9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33440 update docs to remove reference to /var/lib/docker/containers
  filebeat/docs/running-on-kubernetes.asciidoc
Labels: docs, needs_team, Team:Cloudnative-Monitoring

#33422 Osquerybeat: Fix the logging with the wrong logger
  x-pack/osquerybeat/internal/osqdcli/client.go
Labels: bug, Team:Asset Mgt, backport-v8.4.0, bugfix, backport-v8.5.0

#33420 Osquerybeat: Upgrade to osquery 5.5.1
  x-pack/osquerybeat/internal/distro/distro.go
Labels: enhancement, Team:Asset Mgt

#33430 auditbeat/module/file_integrity: improve documentation and ensure paths are absolute
  CHANGELOG.next.asciidoc
  auditbeat/docs/modules/file_integrity.asciidoc
  auditbeat/module/file_integrity/_meta/docs.asciidoc
  auditbeat/module/file_integrity/config.go
  auditbeat/module/file_integrity/metricset.go
  auditbeat/module/file_integrity/scanner.go
Labels: Auditbeat, Team:Security-External Integrations, backport-v7.17.0, 8.6 candidate

#32896 filebeat/module/crowdstrike: fix LocalIP and UserIP with N/A value
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/crowdstrike/falcon/ingest/auth_activity_audit.yml
  x-pack/filebeat/module/crowdstrike/falcon/ingest/detection_summary.yml
  x-pack/filebeat/module/crowdstrike/falcon/ingest/user_activity_audit.yml
  x-pack/filebeat/module/crowdstrike/falcon/test/falcon-audit-events.log
  x-pack/filebeat/module/crowdstrike/falcon/test/falcon-audit-events.log-expected.json
Labels: bug, Team:Security-External Integrations

#33452 [automation] update elastic stack version for testing 8.6.0-b8b35931
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33450 [automation] update elastic stack version for testing 7.17.7-0a02d958
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33451 [automation] update elastic stack version for testing 8.4.4-46f2f222
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33342 Change OAuth2 Authorization Style to Auto Detection, Avoid Client.Sec…
  x-pack/filebeat/input/httpjson/config_auth.go
  x-pack/filebeat/input/httpjson/config_test.go
Labels: needs_team

#33166 [Metricbeat] Add Data Granularity config option for AWS Cloudwatch metrics
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/aws.go
  x-pack/metricbeat/module/aws/billing/billing.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
Labels: aws, Team:Cloud-Monitoring

#33082 test: use `T.TempDir` to create temporary test directory
  CHANGELOG-developer.next.asciidoc
  libbeat/publisher/queue/diskqueue/benchmark_test.go
  libbeat/publisher/queue/diskqueue/segments_test.go
  packetbeat/npcap/npcap_test.go
  x-pack/osquerybeat/internal/osqd/osqueryd_test.go
Labels: Team:Security-External Integrations

#33390 [Release] Update version to 7.17.8
  libbeat/version/version.go
Labels: release, Team:Automation

#33391 [Release] Update test environments for 7.17.8
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#33385 [x-pack/filebeat/module/cisco] Fix pipline for nexus type
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/module/cisco/nexus/config/pipeline.js
  x-pack/filebeat/module/cisco/nexus/test/nexus.log
  x-pack/filebeat/module/cisco/nexus/test/nexus.log-expected.json
Labels: bug, Team:Security-External Integrations, Integration:Cisco, backport-v7.17.0, 8.6 candidate

#33462 [automation] update elastic stack version for testing 8.5.0-bdb74671
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33461 x-pack/filebeat/input: move httpjson/internal to be visible to all input packages
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/internal/httplog/roundtripper.go
Labels: enhancement, Team:Security-External Integrations, backport-skip, 8.6 candidate

#33464 changelog: remove duplicate auditbeat and filebeat headings
  CHANGELOG.next.asciidoc
Labels: cleanup, Team:Security-External Integrations, backport-skip, 8.6 candidate

#33377 x-pack/filebeat/input/http_endpoint: allow http_endpoint instances to share ports
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
  x-pack/filebeat/input/http_endpoint/handler_test.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/http_endpoint/input_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.6 candidate

#33468 [automation] update elastic stack version for testing 8.4.4-d66e996a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33467 [automation] update elastic stack version for testing 8.6.0-a892f234
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33473 x-pack/filebeat/input/httpjson: test and document empty split behaviour
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/input_test.go
Labels: docs, cleanup, Team:Security-External Integrations, backport-skip, 8.6 candidate

#33478 [automation] update elastic stack version for testing 8.5.0-4028b295
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33475 [automation] update elastic stack version for testing 8.6.0-89d224d2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33476 [automation] update elastic stack version for testing 7.17.8-d89bf16d
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33477 [automation] update elastic stack version for testing 8.4.4-6eb63640
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33466 Add docs on `run_from` fields
  heartbeat/docs/heartbeat-observer-options.asciidoc
  heartbeat/docs/monitors/monitor-common-options.asciidoc
Labels: docs, Heartbeat, Team:Uptime, v8.5.0

#33319 [DOCS] Fix hard-coded mapping type doc link
  docs/devguide/metricset-details.asciidoc
Labels: docs, Team:Docs, backport-v7.13.0, backport-v7.12.0, backport-v7.11.0, backport-v7.14.0, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0, v8.6.0, backport-v8.4.0, backport-v8.5.0

#33491 [DOCS] Fix hard-coded mapping type doc link
  docs/devguide/metricset-details.asciidoc
  metricbeat/module/elasticsearch/node/_meta/docs.asciidoc
  metricbeat/module/elasticsearch/node_stats/_meta/docs.asciidoc
Labels: docs, Team:Docs

#33497 [automation] update elastic stack version for testing 8.6.0-949a38d2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33496 [automation] update elastic stack version for testing 8.5.0-f48cdca0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33498 [automation] update elastic stack version for testing 8.4.4-f3b8851a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33318 [DOCS] Fix hard-coded documentation link
  docs/devguide/create-module.asciidoc
Labels: docs, Team:Docs, backport-v7.13.0, backport-v7.12.0, backport-v7.11.0, backport-v7.14.0, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0, v8.6.0, backport-v8.4.0, backport-v8.5.0

#33506 [Heartbeat] Update node to v18.12.0 in container image
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: enhancement, Heartbeat, Team:Uptime, v8.6.0
