Repository elastic/beats, pull requests merged in 2022-12, with the labels that each got.

#33848 filebeat/docs: link cel input documentation into inputs page
  filebeat/docs/filebeat-options.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: bug, Filebeat, Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#33854 packetbeat/procs: don't log at ERROR for file not found
  CHANGELOG.next.asciidoc
  packetbeat/procs/procs_linux.go
Labels: enhancement, Packetbeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#33910 [automation] update elastic stack version for testing 8.5.3-268167d7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33911 [automation] update elastic stack version for testing 8.6.0-87c26073
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33728 [metricbeat] [gcp] add redis regions support
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/gcp/constants.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
Labels: Team:Cloud-Monitoring

#33915 Add workaround for expried GPG keys for auditbeat packaging
  x-pack/auditbeat/magefile.go
Labels: Team:Elastic-Agent-Data-Plane, forwardport-main

#33878 docs: Prepare Changelog for 8.5.3
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#33892 Rename GCP resource label constants
  x-pack/metricbeat/module/gcp/constants.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester_test.go
Labels: Team:Cloud-Monitoring

#33870 filebeat/input/udp: add initial UDP metrics support
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-udp.asciidoc
  filebeat/input/udp/input.go
  filebeat/inputsource/common/dgram/handler.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#33919 Fix doc build
  CHANGELOG.asciidoc
  libbeat/docs/release.asciidoc
Labels: needs_team

#33920 filebeat/input/udp: fix inverted nil check logic
  filebeat/input/udp/input.go
Labels: bug, Filebeat, needs_team, 8.7-candidate

#33925 [automation] update elastic stack version for testing 8.6.0-f96862e0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33923 [automation] update elastic stack version for testing 8.7.0-1b0dc867
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33924 [automation] update elastic stack version for testing 8.5.3-1625ae9f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33830 x-pack/filebeat/module/panw: work around already set event.original field
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/panw/panos/ingest/pipeline.yml
Labels: bug, Filebeat, Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#33853 packetbeat/protos/memcache: don't panic when a transaction is empty
  CHANGELOG.next.asciidoc
  packetbeat/protos/memcache/memcache.go
  packetbeat/protos/memcache/plugin_udp.go
Labels: bug, Packetbeat, Team:Security-External Integrations, backport-v7.17.0, 8.7-candidate, backport-v8.6.0

#33931 [automation] update elastic stack version for testing 8.6.0-368aeeae
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33933 [automation] update elastic stack version for testing 8.5.3-0a7c209d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33932 [automation] update elastic stack version for testing 8.7.0-1fff43d4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33655 [metricbeat] [gcp] remove compute metadata cache
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/gcp/metrics/compute/metadata.go
  x-pack/metricbeat/module/gcp/metrics/compute/metadata_test.go
Labels: backport-v7.17.0, Team:Cloud-Monitoring, backport-v8.4.0

#33954 [automation] update elastic stack version for testing 8.7.0-7fe23b13
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33955 [automation] update elastic stack version for testing 8.5.3-55d94167
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33654 Azure Platform Logs: rename identity as identity_name when the value is a string
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/azure/fields.go
  x-pack/filebeat/module/azure/platformlogs/_meta/fields.yml
  x-pack/filebeat/module/azure/platformlogs/ingest/pipeline.yml
  x-pack/filebeat/module/azure/platformlogs/test/platformlogs-identity-raw.log
  x-pack/filebeat/module/azure/platformlogs/test/platformlogs-identity-raw.log-expected.json
Labels: bug, backport-v7.17.0, Team:Cloud-Monitoring, backport-v8.5.0, backport-v8.6.0

#33937 Avoid panic if gRPC server did to start before call to Stop
  CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/core/server/server.go
Labels: bug, needs_team, 7.17-candidate

#33921 Type field fixes in central management
  x-pack/auditbeat/cmd/root.go
  x-pack/filebeat/cmd/agent.go
  x-pack/heartbeat/cmd/root.go
  x-pack/libbeat/management/generate.go
  x-pack/libbeat/management/generate_test.go
  x-pack/libbeat/management/managerV2.go
  x-pack/libbeat/management/tests/fbtest/filebeat_v2_test.go
  x-pack/metricbeat/cmd/agent.go
  x-pack/packetbeat/cmd/root.go
Labels: bug, Team:Elastic-Agent, v8.7.0, backport-v8.6.0

#33940 Add callback to report rendered beat config under elastic-agent
  NOTICE.txt
  go.mod
  go.sum
  x-pack/libbeat/management/managerV2.go
Labels: Team:Elastic-Agent, v8.7.0, backport-v8.6.0

#33968 x-pack/filebeat/input/cel: fix handling of cancellation
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/cel/input.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#33930 filebeat/input/udp: convert to v2 input
  CHANGELOG.next.asciidoc
  filebeat/include/list.go
  filebeat/input/default-inputs/inputs.go
  filebeat/input/udp/config.go
  filebeat/input/udp/input.go
  filebeat/input/udp/input_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#33975 [automation] update elastic stack version for testing 8.5.3-e63a0e72
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33976 [automation] update elastic stack version for testing 8.7.0-2c7c2bad
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33974 mod,x-pack/filebeat/input/cel: update mito dependency
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/config.go
  x-pack/filebeat/input/cel/input.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#33947 Correct hardening manifest for ironbank
  dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml
Labels: needs_team

#33946 Correct hardening manifest for ironbank
  dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml
Labels: needs_team

#33945 Correct hardening manifest for ironbank
  dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml
Labels: needs_team

#33939 Correct hardening manifest for ironbank
  dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml
Labels: needs_team

#33994 [automation] update elastic stack version for testing 8.6.0-7c9fd7a8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33996 x-pack/filebeat/input/cel: fix eval state return on error
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/cel/input.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#34000 docs: Prepare Changelog for 7.17.8
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#33859 [Filebeat] Add /inputs/ route for Filebeat input metrics
  CHANGELOG.next.asciidoc
  NOTICE.txt
  filebeat/beater/filebeat.go
  filebeat/docs/index.asciidoc
  go.mod
  go.sum
  libbeat/api/config.go
  libbeat/api/routes.go
  libbeat/api/server.go
  libbeat/api/server_test.go
  libbeat/api/server_windows_test.go
  libbeat/beat/beat.go
  libbeat/cmd/instance/beat.go
  libbeat/docs/http-endpoint.asciidoc
  libbeat/docs/loggingconfig.asciidoc
  libbeat/monitoring/inputmon/httphandler.go
  libbeat/monitoring/inputmon/httphandler_test.go
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awscloudwatch/input_integration_test.go
  x-pack/filebeat/input/awss3/input_integration_test.go
Labels: needs_team

#34002 x-pack/filebeat/input/cel: fix handling of non-200/non-429 status codes
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#34009 [automation] update elastic stack version for testing 8.6.0-3bb8e729
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34008 [automation] update elastic stack version for testing 8.7.0-59d5589a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34007 [automation] update elastic stack version for testing 8.5.3-91bdfab4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34016 [automation] update elastic stack version for testing 8.6.0-febebae1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34017 [automation] update elastic stack version for testing 8.7.0-e9833f49
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33979 packetbeat/sniffer: fix shutdown logic
  CHANGELOG.next.asciidoc
  packetbeat/sniffer/sniffer.go
Labels: bug, Packetbeat, Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#33722 fix in handling states and purging
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/s3.go
  x-pack/filebeat/input/awss3/state.go
  x-pack/filebeat/input/awss3/states.go
  x-pack/filebeat/input/awss3/states_test.go
Labels: Team:Cloud-Monitoring, backport-v8.5.0, backport-v8.6.0

#33875 [Release] Update test environments for 8.5.4
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#34015 [automation] Update go release version 1.18.9
  .go-version
  .golangci.yml
  auditbeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
Labels: automation, Team:Elastic-Agent, dependency, backport-skip

#34004 Fix issues with bare fields in expected config
  x-pack/libbeat/management/generate.go
  x-pack/libbeat/management/managerV2.go
Labels: bug, Team:Elastic-Agent, backport-v8.6.0

#33981 [filebeat][azure-blob-storage] Added support for more mime types, offset tracking via cursor
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-azure-blob-storage.asciidoc
  x-pack/filebeat/input/azureblobstorage/input_test.go
  x-pack/filebeat/input/azureblobstorage/job.go
  x-pack/filebeat/input/azureblobstorage/mock/data_files.go
  x-pack/filebeat/input/azureblobstorage/mock/mock.go
  x-pack/filebeat/input/azureblobstorage/mock/testdata/events-array.json
  x-pack/filebeat/input/azureblobstorage/mock/testdata/log.json
  x-pack/filebeat/input/azureblobstorage/mock/testdata/log.ndjson
  x-pack/filebeat/input/azureblobstorage/mock/testdata/multiline.json
  x-pack/filebeat/input/azureblobstorage/mock/testdata/multiline.json.gz
  x-pack/filebeat/input/azureblobstorage/scheduler.go
  x-pack/filebeat/input/azureblobstorage/state.go
  x-pack/filebeat/input/azureblobstorage/types.go
Labels: Team:Security-External Integrations, 8.7-candidate, backport-v8.5.0

#34027 [automation] update elastic stack version for testing 8.6.0-6538107d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34026 [automation] update elastic stack version for testing 8.7.0-08cd8ac3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33819 [Heartbeat] Refactor browser summary as a job wrapper
  CHANGELOG.next.asciidoc
  heartbeat/monitors/wrappers/wrappers.go
  heartbeat/monitors/wrappers/wrappers_test.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
Labels: bug, Team:Uptime, v8.6.0

#34036 [Release] Update test environments for 7.17.9
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#34035 [Release] Update version to 7.17.9
  libbeat/version/version.go
Labels: release, Team:Automation

#34034 docs: update docs versions 7.17.8
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#33988 Disable lockfile under fleet mode
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
Labels: bug, Team:Elastic-Agent

#34038 [automation] update elastic stack version for testing 8.6.0-6aa72183
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34030 x-pack/filebeat/module/okta: make extra efforts to extract risk information from debug_data
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/okta/system/ingest/pipeline.yml
  x-pack/filebeat/module/okta/system/test/okta-system-test.json.log
  x-pack/filebeat/module/okta/system/test/okta-system-test.json.log-expected.json
Labels: bug, enhancement, Filebeat, Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#33956 filestream: fix 'requires pointer' error
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/prospector.go
  filebeat/input/filestream/prospector_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-v7.17.0, backport-v8.6.0

#33593 [functionbeat] [kinesis] use record timestamp instead of current time
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/provider/aws/aws/transformer/transformer.go
Labels: Team:Cloud-Monitoring

#34001 [Heartbeat] add known issue for 8.5.3
  CHANGELOG.asciidoc
Labels: Team:Uptime

#34052 [automation] update elastic stack version for testing 8.7.0-4441fcfd
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34051 [automation] update elastic stack version for testing 8.6.0-919399a0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34044 Adding filenames from the zip to the response for httpjson
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/encoding.go
  x-pack/filebeat/input/httpjson/encoding_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#34063 [automation] update elastic stack version for testing 8.7.0-319a9bee
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34062 [automation] update elastic stack version for testing 7.17.9-90a80afe
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34014 x-pack/filebeat/input/{cel,httpjson}: make transport keep-alives configurable
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/cel/config.go
  x-pack/filebeat/input/cel/config_test.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/httpjson/config_request.go
  x-pack/filebeat/input/httpjson/config_test.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/request_chain_helper.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#34061 Change heartbeat config formatting
  x-pack/heartbeat/cmd/root.go
Labels: bug, Team:Elastic-Agent, backport-v8.6.0

#34073 [automation] update elastic stack version for testing 8.6.0-d5c0a6be
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34070 filebeat/input/udp: add support for /proc/net/udp metrics
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-udp.asciidoc
  filebeat/input/udp/input.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#34055 [AWS Cloudwatch] Changed module to call ListMetrics API only once per region
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
Labels: enhancement, needs_team, aws

#34068 Fix global processors in beats agent client
  x-pack/libbeat/management/generate.go
  x-pack/libbeat/management/generate_test.go
Labels: bug, Team:Elastic-Agent, backport-v8.6.0

#34080 [automation] update elastic stack version for testing 8.7.0-bb19a9d1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34079 [automation] update elastic stack version for testing 8.5.4-9a613070
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34084 [automation] update elastic stack version for testing 8.7.0-19f30181
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34086 [automation] update elastic stack version for testing 7.17.9-ab98c430
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34085 [automation] update elastic stack version for testing 8.6.0-734df845
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33960 Add append in docs
  libbeat/docs/processors-list.asciidoc
Labels: Team:Elastic-Agent-Data-Plane

#33458 [libbeeat] add DropFields processor to js API
  CHANGELOG-developer.next.asciidoc
  libbeat/processors/actions/drop_fields.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#34095 [automation] update elastic stack version for testing 8.5.4-880022a5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34094 [automation] update elastic stack version for testing 8.6.0-55d181cf
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34096 [automation] update elastic stack version for testing 7.17.9-dea3eaf3
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34075 [azure-eventhub input] Switch the run EPH run mode to non-blocking
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/azureeventhub/eph.go
  x-pack/filebeat/input/azureeventhub/eph_test.go
  x-pack/filebeat/input/azureeventhub/input.go
  x-pack/filebeat/input/azureeventhub/input_test.go
  x-pack/libbeat/management/generate_test.go
Labels: bug, Team:Cloud-Monitoring, backport-v8.4.0, backport-v8.5.0, backport-v8.6.0

#34066 Fix BeatV2Manager to configure inputs and set log level
  NOTICE.txt
  go.mod
  go.sum
  libbeat/management/management.go
  x-pack/libbeat/management/config.go
  x-pack/libbeat/management/generate.go
  x-pack/libbeat/management/managerV2.go
  x-pack/libbeat/management/managerV2_test.go
  x-pack/libbeat/management/tests/init.go
  x-pack/libbeat/management/tests/mock_server.go
Labels: Team:Elastic-Agent, backport-v8.6.0

#34107 [automation] update elastic stack version for testing 8.5.4-9612e66a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34108 [automation] update elastic stack version for testing 8.6.0-33529ee6
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34106 [automation] update elastic stack version for testing 7.17.9-89f6cb7d
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34097 Add option to disable pod events enrichment with deployment name
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/metadata/config.go
  libbeat/common/kubernetes/metadata/pod.go
  libbeat/docs/shared-autodiscover.asciidoc
Labels: Team:Automation

#33254 [filebeat] Change how we debug tpl values in httpjson
  x-pack/filebeat/input/httpjson/cursor.go
  x-pack/filebeat/input/httpjson/rate_limiter.go
  x-pack/filebeat/input/httpjson/request_chain_helper.go
  x-pack/filebeat/input/httpjson/transform_append.go
  x-pack/filebeat/input/httpjson/transform_set.go
  x-pack/filebeat/input/httpjson/value_tpl.go
  x-pack/filebeat/input/httpjson/value_tpl_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-v7.17.0, backport-v8.5.0, backport-v8.6.0

#34105 [elasticsearch] ccr supports enterprise license
  metricbeat/module/elasticsearch/ccr/ccr.go
Labels: Team:Infra Monitoring UI, v8.7.0, Module:elasticsearch, >bug, backport-v8.6.0

#34117 [automation] update elastic stack version for testing 8.7.0-0f74a2e9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34116 [automation] update elastic stack version for testing 8.5.4-09ced402
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34118 [automation] update elastic stack version for testing 8.6.0-f6d7d537
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34115 [automation] update elastic stack version for testing 7.17.9-917139ef
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33555 Fix kafka dashboard field names: kafka.topic.name & kafka.broker.id.
  CHANGELOG.next.asciidoc
  metricbeat/module/kafka/_meta/kibana/7/visualization/587f2360-8f21-11e8-8fa2-3d5f811fbd0f-ecs.json
  metricbeat/module/kafka/_meta/kibana/7/visualization/944188f0-8e79-11e8-8fa2-3d5f811fbd0f-ecs.json
  metricbeat/module/kafka/_meta/kibana/7/visualization/dc89f8d0-8e8e-11e8-8fa2-3d5f811fbd0f-ecs.json
Labels: bug, Team:Service-Integrations

#34122 [automation] update elastic stack version for testing 8.6.0-a026c2fe
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34120 [automation] update elastic stack version for testing 8.5.4-53cae6e0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34121 [automation] update elastic stack version for testing 7.17.9-0c41c515
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34127 [filebeat][httpjson]- improved error handling during pagination with chaining & split processor
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/request.go
Labels: Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#34132 [automation] update elastic stack version for testing 8.7.0-b3da67ae
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34130 [automation] update elastic stack version for testing 8.5.4-b44284e8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34131 [automation] update elastic stack version for testing 8.6.0-7e55dcb1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34129 [automation] update elastic stack version for testing 7.17.9-590749d6
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34140 [automation] update elastic stack version for testing 8.5.4-63dd32c9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34138 [automation] update elastic stack version for testing 8.6.0-08909b84
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34139 [automation] update elastic stack version for testing 7.17.9-fb6ed84b
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34134 Fix make clean
  Makefile
  dev-tools/mage/clean.go
Labels: bug, needs_team, backport-skip, 8.6-candidate

#34141 Fix make clean (#34134)
  Makefile
  dev-tools/mage/clean.go
Labels: bug, Team:Elastic-Agent, 8.7-candidate

#34147 [automation] update elastic stack version for testing 8.7.0-d6e7f5ec
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34145 [automation] update elastic stack version for testing 8.6.0-2d1af9b1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34146 [automation] update elastic stack version for testing 8.5.4-2ce7df52
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34148 [automation] update elastic stack version for testing 7.17.9-9b93f6c8
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34149 Inject Beat specific default processors
  x-pack/auditbeat/cmd/root.go
  x-pack/filebeat/cmd/agent.go
  x-pack/libbeat/management/generate.go
  x-pack/metricbeat/cmd/agent.go
  x-pack/osquerybeat/cmd/root.go
  x-pack/packetbeat/cmd/root.go
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, backport-v8.6.0
