Repository elastic/beats, pull requests merged in 2022-05, with the labels that each got.

#31477 [automation] update elastic stack version for testing 7.17.4-ed667030
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31479 [automation] update elastic stack version for testing 8.2.0-e7ad9ef0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31478 [automation] update elastic stack version for testing 8.3.0-eb27d7ab
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31480 [automation] update elastic stack version for testing 8.1.4-76569f3d
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30979 [Metricbeat] gcp: fix dataproc fields
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/gcp/dataproc/_meta/fields.yml
  x-pack/metricbeat/module/gcp/dataproc/manifest.yml
  x-pack/metricbeat/module/gcp/fields.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
  x-pack/metricbeat/module/gcp/metrics/metricset.go
  x-pack/metricbeat/module/gcp/metrics/response_parser.go
  x-pack/metricbeat/module/gcp/metrics/timeseries.go
  x-pack/metricbeat/module/gcp/timeseries_metadata_collector.go
Labels: backport-v8.1.0, Team:Cloud-Monitoring

#31424 Add regex support functionality
  CHANGELOG-developer.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  libbeat/processors/actions/drop_fields.go
  libbeat/processors/actions/drop_fields_test.go
Labels: libbeat, Team:Integrations, v8.3.0

#31485 Revert "[Filebeat][CometD] Add CometD input for Salesforce connector …
  CHANGELOG.asciidoc
  NOTICE.txt
  filebeat/docs/filebeat-options.asciidoc
  go.mod
  go.sum
  testing/environments/docker/cometd/Dockerfile
  testing/environments/docker/cometd/files/config.yml
  x-pack/filebeat/docker-compose.yml
  x-pack/filebeat/docs/inputs/input-cometd.asciidoc
  x-pack/filebeat/include/list.go
  x-pack/filebeat/input/cometd/client_mocked.go
  x-pack/filebeat/input/cometd/cometd_integration_test.go
  x-pack/filebeat/input/cometd/config.go
  x-pack/filebeat/input/cometd/config_auth.go
  x-pack/filebeat/input/cometd/config_test.go
  x-pack/filebeat/input/cometd/input.go
  x-pack/filebeat/input/cometd/input_test.go
Labels: needs_team

#31494 [automation] update elastic stack version for testing 7.17.4-9ca33e9a
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31496 [automation] update elastic stack version for testing 8.3.0-0b6ea9f2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31493 [automation] update elastic stack version for testing 8.2.0-56396fd0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31472 docs: Prepare Changelog for 8.2.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#31495 [automation] update elastic stack version for testing 8.1.4-1cdc80b6
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31461 Backport elastic/elastic-agent #308
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
  x-pack/elastic-agent/pkg/artifact/config.go
  x-pack/elastic-agent/pkg/artifact/download/http/downloader.go
  x-pack/elastic-agent/pkg/artifact/download/http/downloader_test.go
  x-pack/elastic-agent/pkg/artifact/download/http/elastic_test.go
  x-pack/elastic-agent/pkg/artifact/download/localremote/downloader.go
  x-pack/elastic-agent/pkg/artifact/download/snapshot/downloader.go
Labels: needs_team

#31507 [automation] update elastic stack version for testing 7.17.4-cd92752d
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31506 [automation] update elastic stack version for testing 8.3.0-7f585873
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31498 [filebeat][httpjson] Add missing docs for the delegated_account option
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
Labels: docs, Team:Security-External Integrations, backport-v8.0.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#31505 [automation] update elastic stack version for testing 8.1.4-86899ed7
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31218 [awsfargate] Add undocumented fields
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/awsfargate/_meta/fields.yml
  x-pack/metricbeat/module/awsfargate/fields.go
  x-pack/metricbeat/module/awsfargate/task_stats/_meta/data.json
  x-pack/metricbeat/module/awsfargate/task_stats/_meta/fields.yml
  x-pack/metricbeat/module/awsfargate/task_stats/task_stats_integration_test.go
Labels: bug, Team:Cloud-Monitoring

#31513 Forward port 8.2.0 changelog to main
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane

#31054 [Release] Update version to 8.2.1
  libbeat/version/version.go
Labels: release, Team:Automation

#31519 [Auditbeat] Update to go-libaudit v2.3.0
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: enhancement, Auditbeat, Team:Security-External Integrations, backport-v8.3.0

#31488 Rename awscloudwatch.* fields to aws.cloudwatch.*
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/input/awscloudwatch/_meta/fields.yml
  x-pack/filebeat/input/awscloudwatch/cloudwatch.go
  x-pack/filebeat/input/awscloudwatch/fields.go
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/filebeat/input/awscloudwatch/input_test.go
  x-pack/filebeat/input/awscloudwatch/processor.go
Labels: bug, backport-v8.2.0, Team:Cloud-Monitoring

#31524 [automation] update elastic stack version for testing 7.17.4-c570579f
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31525 [automation] update elastic stack version for testing 8.3.0-a1c5cfff
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31538 [automation] update elastic stack version for testing 7.17.4-2fe5353f
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31540 [automation] update elastic stack version for testing 8.1.4-6c818705
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31492 [Filebeat][CometD] Add CometD input for Salesforce connector
  CHANGELOG.asciidoc
  NOTICE.txt
  filebeat/docs/filebeat-options.asciidoc
  go.mod
  go.sum
  testing/environments/docker/cometd/Dockerfile
  testing/environments/docker/cometd/files/config.yml
  x-pack/filebeat/docker-compose.yml
  x-pack/filebeat/docs/inputs/input-cometd.asciidoc
  x-pack/filebeat/include/list.go
  x-pack/filebeat/input/cometd/client_mocked.go
  x-pack/filebeat/input/cometd/cometd_integration_test.go
  x-pack/filebeat/input/cometd/config.go
  x-pack/filebeat/input/cometd/config_auth.go
  x-pack/filebeat/input/cometd/config_test.go
  x-pack/filebeat/input/cometd/input.go
  x-pack/filebeat/input/cometd/input_test.go
Labels: needs_team

#31539 [automation] update elastic stack version for testing 8.3.0-6ba9f710
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31543 [Heartbeat] Fix unintentional use of no-op logger
  CHANGELOG.next.asciidoc
  heartbeat/autodiscover/builder/hints/monitors.go
  heartbeat/autodiscover/builder/hints/monitors_test.go
  heartbeat/monitors/active/icmp/stdloop.go
  heartbeat/monitors/factory.go
  heartbeat/monitors/logger/logger.go
  heartbeat/monitors/monitor.go
  heartbeat/scheduler/schedjob.go
Labels: bug, Heartbeat, Team:Uptime, technical debt, backport-v7.17.0

#31544 [Heartbeat] Support map syntax for throttling browser monitors
  heartbeat/docs/monitors/monitor-browser.asciidoc
  x-pack/heartbeat/monitors/browser/suite.go
  x-pack/heartbeat/monitors/browser/suite_test.go
Labels: enhancement, Heartbeat, Team:Uptime, v8.3.0

#31535 [auditbeat] Add backlog_wait_time_actual to show-status output
  CHANGELOG.next.asciidoc
  auditbeat/module/auditd/show_linux.go
Labels: enhancement, Auditbeat, Team:Security-External Integrations, backport-v8.3.0

#31546 libbeat/common/encoding/xml: ignore encoding declarations in proc inst
  CHANGELOG.next.asciidoc
  libbeat/common/encoding/xml/decode.go
  libbeat/processors/decode_xml/decode_xml_test.go
Labels: bug, Filebeat, libbeat, Team:Security-External Integrations, 8.3-candidate, backport-v8.2.0, backport-v7.17.0

#31551 [automation] update elastic stack version for testing 7.17.4-1ffd290e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31483 [Oracle Module] Improve connection documentation
  metricbeat/docs/modules/oracle.asciidoc
  x-pack/metricbeat/module/oracle/_meta/docs.asciidoc
Labels: Team:Service-Integrations

#31527 packetbeat/procs: be more careful in recovering process names on linux
  CHANGELOG.next.asciidoc
  packetbeat/procs/procs.go
  packetbeat/procs/procs_linux.go
  packetbeat/procs/procs_other.go
  packetbeat/procs/procs_windows.go
Labels: bug, Packetbeat, Team:Security-External Integrations, 8.3-candidate, backport-v8.2.0, backport-v7.17.0

#31559 packaging: avoid propagate and wait for the e2e-testing
  .ci/packaging.groovy
Labels: Team:Automation

#31504 winlogbeat/eventlog: cache winevent.WinMeta values
  CHANGELOG.next.asciidoc
  winlogbeat/eventlog/wineventlog.go
Labels: bug, enhancement, Winlogbeat, Team:Security-External Integrations, 8.3-candidate, backport-v8.2.0, backport-v7.17.0

#31565 [automation] update elastic stack version for testing 7.17.4-37e626ca
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31564 [automation] update elastic stack version for testing 8.2.1-d6d75d75
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31566 [automation] update elastic stack version for testing 8.3.0-d380914f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31542 Update getting-started.asciidoc
  filebeat/docs/getting-started.asciidoc
Labels: docs, Team:Elastic-Agent-Data-Plane

#31557 List individual beat docs without a CODEOWNER.
  .github/CODEOWNERS
Labels: Team:Elastic-Agent-Data-Plane

#31531 chore: use a different e2e profile for running them from Beats
  .ci/packaging.groovy
Labels: Team:Automation, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#31556 [Winlogbeat] Update sysmon pipeline with latest changes from integration
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml
Labels: bug, enhancement, review, Winlogbeat, Team:Security-External Integrations

#31581 threatintel: Correct references to Recorded Future and ThreatQ in docs and dashboards
  filebeat/docs/modules/threatintel.asciidoc
  x-pack/filebeat/module/threatintel/_meta/docs.asciidoc
  x-pack/filebeat/module/threatintel/_meta/kibana/7/visualization/f13f5650-df5b-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/module.yml
Labels: docs, review, Team:Security-External Integrations, backport-v8.2.0

#31584 [automation] update elastic stack version for testing 8.2.1-2eb01953
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31585 [automation] update elastic stack version for testing 8.3.0-53513548
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31286 [filebeat] add 8.x kibana logs ingest pipeline
  filebeat/docs/fields.asciidoc
  filebeat/module/kibana/fields.go
  filebeat/module/kibana/log/_meta/fields.yml
  filebeat/module/kibana/log/ingest/pipeline-7.yml
  filebeat/module/kibana/log/ingest/pipeline-ecs.yml
  filebeat/module/kibana/log/ingest/pipeline.yml
  filebeat/module/kibana/log/manifest.yml
  filebeat/module/kibana/log/test/log.830.log
  filebeat/module/kibana/log/test/log.830.log-expected.json
Labels: bug, backport-v8.2.0, backport-v7.17.0, Team:Infra Monitoring UI, Module:kibana

#31589 fix: proper file name
  .ci/packaging.groovy
Labels: Team:Automation

#31558 Add tests for shipper output and add support for partial results
  libbeat/outputs/shipper/api/shipper_mock.go
  libbeat/outputs/shipper/shipper.go
  libbeat/outputs/shipper/shipper_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, v8.3.0

#31580 [8.2] (backport #31476) to fix docs typo (#31476)
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/input/awscloudwatch/_meta/fields.yml
  x-pack/filebeat/input/awscloudwatch/fields.go
Labels: docs, backport, needs_team, v8.2.0

#31552 x-pack/filebeat/module/threatintel/malwarebazaar: properly handle code_sign array
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/threatintel/fields.go
  x-pack/filebeat/module/threatintel/malwarebazaar/_meta/fields.yml
  x-pack/filebeat/module/threatintel/malwarebazaar/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/malwarebazaar/test/malwarebazaar.ndjson.log
  x-pack/filebeat/module/threatintel/malwarebazaar/test/malwarebazaar.ndjson.log-expected.json
Labels: bug, Filebeat, Team:Security-External Integrations, 8.3-candidate, backport-v8.2.0, backport-v7.17.0

#31599 packetbeat: move "protocol" term from event.category to event.type in SIP events
  CHANGELOG.next.asciidoc
  packetbeat/_meta/sample_outputs/sip.json
  packetbeat/protos/sip/README.md
  packetbeat/protos/sip/plugin.go
  packetbeat/tests/system/golden/sip-expected.json
  packetbeat/tests/system/golden/sip_authenticated_register-expected.json
Labels: bug, Packetbeat, Team:Security-External Integrations, 8.3-candidate, backport-v8.2.0, backport-v7.17.0

#31604 [automation] update elastic stack version for testing 7.17.4-6a00b8d7
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31603 [automation] update elastic stack version for testing 8.2.1-91d7a53f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30972 Add How to guide for migrating to filestream input
  filebeat/docs/howto/howto.asciidoc
  filebeat/docs/howto/migrate-to-filestream.asciidoc
Labels: docs, Team:Docs, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#31590 Add metadata for missing k8s resources/metricsets
  CHANGELOG.next.asciidoc
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-role.yaml
  libbeat/common/kubernetes/informer.go
  libbeat/common/kubernetes/types.go
  metricbeat/module/kubernetes/_meta/test/docs/01_playground/metricbeat.yaml
  metricbeat/module/kubernetes/event/event.go
  metricbeat/module/kubernetes/state_container/_meta/test/ksm.v2.0.0.expected
  metricbeat/module/kubernetes/state_daemonset/state_daemonset.go
  metricbeat/module/kubernetes/state_persistentvolume/_meta/test/ksm.unit.v1.8.0.expected
  metricbeat/module/kubernetes/state_persistentvolume/_meta/test/ksm.v1.8.0.expected
  metricbeat/module/kubernetes/state_persistentvolume/_meta/test/ksm.v2.0.0.expected
  metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume.go
  metricbeat/module/kubernetes/state_persistentvolumeclaim/_meta/test/ksm.unit.v1.8.0.expected
  metricbeat/module/kubernetes/state_persistentvolumeclaim/_meta/test/ksm.v1.8.0.expected
  metricbeat/module/kubernetes/state_persistentvolumeclaim/_meta/test/ksm.v2.0.0.expected
  metricbeat/module/kubernetes/state_persistentvolumeclaim/state_persistentvolumeclaim.go
  metricbeat/module/kubernetes/util/kubernetes.go
  metricbeat/module/kubernetes/volume/volume.go
Labels: 8.3-candidate, Team:Cloudnative-Monitoring

#31595 Fix bug in filtering, cleanup
  libbeat/metric/system/process/helpers.go
  libbeat/metric/system/process/process.go
  libbeat/metric/system/process/process_aix.go
  libbeat/metric/system/process/process_darwin.go
  libbeat/metric/system/process/process_linux_common.go
  libbeat/metric/system/process/process_test.go
  libbeat/metric/system/process/process_types.go
  libbeat/metric/system/process/process_windows.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-v8.2.0

#31619 Osquerybeat: Populate host.name field
  x-pack/osquerybeat/cmd/root.go
Labels: enhancement, Team:Asset Mgt, backport-v8.3.0, >enhancement

#31624 [automation] update elastic stack version for testing 8.2.1-05a5ca87
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31625 [automation] update elastic stack version for testing 8.3.0-b85385ff
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31626 [automation] update elastic stack version for testing 7.17.4-153c53bf
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31533 Add parsing for 434001 and 434003
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/test/sample.log
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: enhancement, module, Filebeat, Team:Security-External Integrations, needs_integration_sync

#31631 [automation] update elastic stack version for testing 7.17.4-191b5600
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31633 [automation] update elastic stack version for testing 8.2.1-3d12787c
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31632 [automation] update elastic stack version for testing 8.3.0-19aba912
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31628 x-pack/filebeat/module/cisco: remove invalid values from ECS fields
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: bug, Filebeat, Team:Security-External Integrations, Integration:Cisco, 8.3-candidate, backport-v8.2.0

#31484 Add ascii documentation for regexp support in drop_fields processor
  libbeat/processors/actions/docs/drop_fields.asciidoc
Labels: docs, Team:Observability, v8.3.0

#31553 Add support for nanosecond precision timestamps
  CHANGELOG.next.asciidoc
  libbeat/common/datetime.go
  libbeat/common/datetime_test.go
  libbeat/common/dtfmt/builder.go
  libbeat/common/dtfmt/ctx.go
  libbeat/common/dtfmt/doc.go
  libbeat/common/dtfmt/dtfmt_test.go
  libbeat/common/dtfmt/elems.go
  libbeat/common/dtfmt/fields.go
  libbeat/common/dtfmt/fmt.go
  libbeat/common/dtfmt/prog.go
  libbeat/common/dtfmt/util.go
  libbeat/outputs/codec/common.go
  packetbeat/tests/system/test_0032_dns.py
  packetbeat/tests/system/test_0050_icmp.py
  packetbeat/tests/system/test_0060_flows.py
  packetbeat/tests/system/test_0062_cassandra.py
  x-pack/filebeat/module/gcp/audit/test/audit-log-entries.json.log-expected.json
  x-pack/filebeat/module/gcp/firewall/test/rare.log-expected.json
  x-pack/filebeat/module/gcp/firewall/test/test.log-expected.json
  x-pack/filebeat/module/gcp/vpcflow/test/vpc-flow-log-entries.json.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-6.0.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-alerts.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-dns-4.1.4.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-metadata.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
Labels: Team:Elastic-Agent-Data-Plane

#31642 [automation] update elastic stack version for testing 8.2.1-736d131e
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31641 [automation] update elastic stack version for testing 7.17.4-16fc7c23
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31640 [automation] update elastic stack version for testing 8.3.0-4149272f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31185 Upgrade Mongodb library in Beats to v5
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/module/mongodb/collstats/_meta/data.json
  metricbeat/module/mongodb/collstats/collstats.go
  metricbeat/module/mongodb/collstats/collstats_integration_test.go
  metricbeat/module/mongodb/collstats/data.go
  metricbeat/module/mongodb/collstats/data_test.go
  metricbeat/module/mongodb/dbstats/_meta/data.json
  metricbeat/module/mongodb/dbstats/data.go
  metricbeat/module/mongodb/dbstats/dbstats.go
  metricbeat/module/mongodb/dbstats/dbstats_integration_test.go
  metricbeat/module/mongodb/metrics/_meta/data.json
  metricbeat/module/mongodb/metrics/data.go
  metricbeat/module/mongodb/metrics/metrics.go
  metricbeat/module/mongodb/metricset.go
  metricbeat/module/mongodb/mongodb.go
  metricbeat/module/mongodb/replstatus/_meta/data.json
  metricbeat/module/mongodb/replstatus/data.go
  metricbeat/module/mongodb/replstatus/info.go
  metricbeat/module/mongodb/replstatus/replstatus.go
  metricbeat/module/mongodb/replstatus/replstatus_integration_test.go
  metricbeat/module/mongodb/replstatus/status.go
  metricbeat/module/mongodb/status/_meta/data.json
  metricbeat/module/mongodb/status/data.go
  metricbeat/module/mongodb/status/status.go
  metricbeat/module/mongodb/status/status_integration_test.go
  packetbeat/protos/mongodb/mongodb_parser.go
Labels: bug, enhancement, Team:Service-Integrations

#31645 Add missing changelog entry for system/process fixes
  CHANGELOG.next.asciidoc
Labels: Team:Elastic-Agent-Data-Plane, backport-v8.2.0

#31639 Make Beat generator deprecation and removal more obvious in the docs
  libbeat/docs/communitybeats.asciidoc
Labels: Team:Docs, backport-v8.0.0, backport-v8.1.0, backport-v8.2.0

#31537 Fix View Commit links in Beats relnotes
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#31656 packetbeat: fix doc formatting
  packetbeat/docs/packetbeat-options.asciidoc
Labels: bug, docs, Team:Security-External Integrations, 8.3-candidate, backport-v8.2.0, backport-v7.17.0

#31660 [automation] update elastic stack version for testing 7.17.4-3585da41
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31659 [automation] update elastic stack version for testing 8.3.0-e4aa1f83
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31661 [automation] update elastic stack version for testing 8.2.1-8d9ffca9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31473 filebeat/config: set filebeat.registry.flush default to 1s
  CHANGELOG.next.asciidoc
  filebeat/_meta/config/filebeat.global.reference.yml.tmpl
  filebeat/config/config.go
  filebeat/docs/filebeat-general-options.asciidoc
  filebeat/filebeat.reference.yml
  filebeat/tests/system/test_harvester.py
  filebeat/tests/system/test_publisher.py
  filebeat/tests/system/test_registrar.py
  x-pack/filebeat/filebeat.reference.yml
Labels: Team:Elastic-Agent-Data-Plane

#31669 Fix Winlogbeat registry flush not working
  CHANGELOG.next.asciidoc
  winlogbeat/checkpoint/checkpoint.go
  winlogbeat/checkpoint/checkpoint_test.go
Labels: bug, Team:Security-External Integrations, backport-v8.2.0, backport-v7.17.0

#31677 [automation] update elastic stack version for testing 8.2.1-93582d09
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29760 [Metricbeat] etcd: fix leader metricset fields
  metricbeat/docs/fields.asciidoc
  metricbeat/module/etcd/_meta/test/leaderstats.json
  metricbeat/module/etcd/fields.go
  metricbeat/module/etcd/leader/_meta/data.json
  metricbeat/module/etcd/leader/_meta/fields.yml
  metricbeat/module/etcd/leader/data.go
  metricbeat/module/etcd/leader/leader.go
  metricbeat/module/etcd/leader/leader_integration_test.go
  metricbeat/module/etcd/leader/leader_test.go
  metricbeat/module/etcd/test_etcd.py
Labels: enhancement, Team:Integrations, backport-skip

#31679 [automation] update elastic stack version for testing 8.3.0-a55286cc
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31674 x-pack/{auditbeat,filebeat}: remove ECS-invalid term from event.category
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/socket/_meta/data.json
  x-pack/auditbeat/module/system/socket/state.go
  x-pack/auditbeat/module/system/socket/state_test.go
  x-pack/auditbeat/tests/system/test_system_socket.py
  x-pack/filebeat/input/netflow/convert.go
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Barracuda-extended-uniflow-template-256.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Barracuda-firewall.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Mikrotik-RouterOS-6.39.2.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Netscaler-with-variable-length-fields.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Nokia-BRAS.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-OpenBSD-pflow.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-Procera.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-VMware-virtual-distributed-switch.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-YAF-basic-with-applabel.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-configured-with-include_flowset_id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-options-template-from-Juniper-MX240-JunOS-15.1-R6-S3.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX-vIPtela-with-VPN-id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/IPFIX.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-1941-K9-release-15.1.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASA-2.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASA.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASR-9000-series-options-template-256.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASR-9000-series-template-260.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-ASR1001--X.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-NBAR-flowset-262.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-NBAR-options-template-260.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Cisco-WLC.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Fortigate-FortiOS-5.2.1.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Fortigate-FortiOS-54x-appid.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-H3C-Netstream-with-varstring.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-H3C.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Huawei-Netstream.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-IE150-IE151.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Palo-Alto-1-flowset-in-large-zero-filled-packet.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Palo-Alto-PAN--OS-with-app--id.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Streamcore.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-Ubiquiti-Edgerouter-with-MPLS-labels.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-field-layer2segmentid.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-ipt_netflow-reduced-size-encoding.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-macaddress.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-multiple-netflow-exporters.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-nprobe-DPI-L7.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-options-template-with-scope-fields.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-template-with-0-length-fields.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow-9-valid-01.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/Netflow9-Juniper-SRX-options-template-with-0-scope-field-length.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/netflow9_e10s_4_7byte_pad.pcap.golden.json
  x-pack/filebeat/input/netflow/testdata/golden/netflow9_ubiquiti_edgerouter.pcap.golden.json
  x-pack/filebeat/module/cisco/ios/config/pipeline.js
  x-pack/filebeat/module/cisco/ios/pipeline_test.go
  x-pack/filebeat/module/cisco/ios/test/cisco-ios-syslog.log-expected.json
  x-pack/filebeat/module/panw/_meta/kibana/7/search/290685e0-7569-11e9-976e-65a8f47cc4c1.json
  x-pack/filebeat/module/panw/panos/ingest/traffic.yml
  x-pack/filebeat/module/panw/panos/test/pan_inc_other.log-expected.json
  x-pack/filebeat/module/panw/panos/test/pan_inc_traffic.log-expected.json
  x-pack/filebeat/module/panw/panos/test/pan_inc_traffic_ietf.log-expected.json
  x-pack/filebeat/module/panw/panos/test/traffic.log-expected.json
  x-pack/filebeat/module/panw/panos/test/traffic_nanos_time.log-expected.json
Labels: bug, Filebeat, Auditbeat, breaking change, Team:Security-External Integrations, 8.3-candidate, backport-v8.2.0

#31688 [Heartbeat] Rename push->project / add source
  heartbeat/_meta/fields.common.yml
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  heartbeat/monitors/stdfields/stdfields.go
  heartbeat/monitors/wrappers/wrappers.go
  heartbeat/monitors/wrappers/wrappers_test.go
  x-pack/heartbeat/include/fields.go
  x-pack/heartbeat/monitors/browser/source/project.go
  x-pack/heartbeat/monitors/browser/source/project_test.go
  x-pack/heartbeat/monitors/browser/source/source.go
  x-pack/heartbeat/monitors/browser/source/zipurl.go
Labels: enhancement, Heartbeat, Team:Uptime

#31691 [automation] update elastic stack version for testing 7.17.4-60cd01b1
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31689 [automation] update elastic stack version for testing 8.3.0-d754f94f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31690 [automation] update elastic stack version for testing 8.2.1-54274789
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31422 [Heartbeat] ARM seccomp profile
  CHANGELOG.next.asciidoc
  heartbeat/security/policy_linux_386.go
  heartbeat/security/policy_linux_amd64.go
  heartbeat/security/policy_linux_arm64.go
  heartbeat/security/security.go
Labels: enhancement, Team:Uptime, release-note:skip, backport-skip

#31693 [Threatintel] Change from beta to GA
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/threatintel.asciidoc
  x-pack/filebeat/module/threatintel/_meta/docs.asciidoc
  x-pack/filebeat/module/threatintel/_meta/fields.yml
  x-pack/filebeat/module/threatintel/fields.go
Labels: enhancement, Team:Security-External Integrations

#31695 Automatically update the golangci-lint Go versions
  .ci/bump-go-release-version.sh
  .golangci.yml
Labels: enhancement, Team:Automation, Team:Elastic-Agent-Data-Plane

#31663 ci: use withTerraformEnv
  .ci/scripts/install-terraform.sh
  .ci/scripts/install-tools.sh
  Jenkinsfile
Labels: automation, Team:Automation, aws, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#31694 Upgrade elastic-agent-libs to pick up fix to keystore package
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  heartbeat/autodiscover/builder/hints/monitors_test.go
  libbeat/tests/system/test_keystore.py
  metricbeat/autodiscover/builder/hints/metrics_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#31701 [Heartbeat] Fix source conflict, improve project naming
  heartbeat/_meta/fields.common.yml
  heartbeat/config/config.go
  heartbeat/docs/fields.asciidoc
  heartbeat/docs/heartbeat-options.asciidoc
  heartbeat/docs/monitors/monitor-browser.asciidoc
  heartbeat/include/fields.go
  heartbeat/monitors/stdfields/stdfields.go
  heartbeat/monitors/wrappers/wrappers.go
  heartbeat/monitors/wrappers/wrappers_test.go
  x-pack/heartbeat/include/fields.go
  x-pack/heartbeat/monitors/browser/browser.go
  x-pack/heartbeat/monitors/browser/project.go
  x-pack/heartbeat/monitors/browser/project_test.go
  x-pack/heartbeat/monitors/browser/source/fixtures/todos/package.json
  x-pack/heartbeat/monitors/browser/source/local.go
  x-pack/heartbeat/monitors/browser/suite.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
Labels: enhancement, Heartbeat, Team:Uptime, v8.3.0

#31675 [Heartbeat] Update agent-complete node version to 16.15.0
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: enhancement, Heartbeat, Team:Uptime

#31707 [automation] update elastic stack version for testing 7.17.4-1170b674
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31705 [automation] update elastic stack version for testing 8.2.1-539cf6f5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31706 [automation] update elastic stack version for testing 8.3.0-3a5a0cd2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31708 Remove `libbeat/service`
  libbeat/cmd/instance/beat.go
  libbeat/scripts/cmd/stress_pipeline/main.go
  libbeat/service/service.go
  libbeat/service/service_unix.go
  libbeat/service/service_windows.go
  packetbeat/beater/packetbeat.go
  x-pack/dockerlogbeat/main.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#31682 New option `timestamp.precision` to control timestamp precision
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  filebeat/tests/system/config/filebeat_modules.yml.j2
  heartbeat/heartbeat.reference.yml
  libbeat/_meta/config.yml.tmpl
  libbeat/_meta/config/general.reference.yml.tmpl
  libbeat/cmd/instance/beat.go
  libbeat/common/datetime.go
  libbeat/common/datetime_test.go
  libbeat/docs/generalconfig.asciidoc
  libbeat/outputs/codec/common.go
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  packetbeat/tests/system/config/packetbeat.yml.j2
  packetbeat/tests/system/test_0032_dns.py
  packetbeat/tests/system/test_0050_icmp.py
  packetbeat/tests/system/test_0062_cassandra.py
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/tests/system/config/filebeat_modules.yml.j2
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Elastic-Agent-Data-Plane

#31676 x-pack/filebeat/module/okta: add extended okta.debug_context.debug_data handling
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  x-pack/filebeat/module/okta/fields.go
  x-pack/filebeat/module/okta/system/_meta/fields.yml
  x-pack/filebeat/module/okta/system/ingest/pipeline.yml
  x-pack/filebeat/module/okta/system/test/okta-system-test.json.log
  x-pack/filebeat/module/okta/system/test/okta-system-test.json.log-expected.json
Labels: bug, enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.3-candidate

#31709 ci: publish docker images in the internal docker registry
  .ci/packaging.groovy
Labels: automation, Team:Automation, backport-v8.3.0, backport-v8.2.0

#31711 docs: Prepare Changelog for 8.2.1
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#31001 Filesystem refactor
  CHANGELOG.next.asciidoc
  go.sum
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/fields.go
  metricbeat/module/system/filesystem/_meta/docs.asciidoc
  metricbeat/module/system/filesystem/_meta/fields.yml
  metricbeat/module/system/filesystem/filesystem.go
  metricbeat/module/system/filesystem/filesystem_test.go
  metricbeat/module/system/filesystem/helper.go
  metricbeat/module/system/filesystem/helper_test.go
  metricbeat/module/system/fsstat/_meta/data.json
  metricbeat/module/system/fsstat/fsstat.go
  metricbeat/module/system/test_system.py
Labels: bug, enhancement, backport-skip, Team:Elastic-Agent-Data-Plane

#31710 auditbeat: update import of github.com/elastic/go-libaudit
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, Auditbeat, Team:Security-External Integrations, backport-skip, 8.3-candidate

#31630 x-pack/filebeat/input/httpjson: add hash template function
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/value_tpl.go
  x-pack/filebeat/input/httpjson/value_tpl_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.3-candidate

#31724 [automation] update elastic stack version for testing 8.2.1-e97da867
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31723 [automation] update elastic stack version for testing 7.17.4-1572020b
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31727 docs: Prepare Changelog for 7.17.4
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#31733 Remove the 'Add QA labels to Elastic Agent issues'
  .github/workflows/qa-labels.yml
Labels: needs_team

#31730 [Release] Update version to 7.17.5
  libbeat/version/version.go
Labels: release, Team:Automation

#31728 docs: update docs versions 7.17.4
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#31719 [Release] Update version to 8.2.2
  libbeat/version/version.go
Labels: release, Team:Automation

#29899 [ResponseOps] New metricsets for Kibana stack monitoring
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/kibana.asciidoc
  metricbeat/docs/modules/kibana/cluster_actions.asciidoc
  metricbeat/docs/modules/kibana/cluster_rules.asciidoc
  metricbeat/docs/modules/kibana/node_actions.asciidoc
  metricbeat/docs/modules/kibana/node_rules.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/module/kibana/cluster_actions/_meta/data.json
  metricbeat/module/kibana/cluster_actions/_meta/docs.asciidoc
  metricbeat/module/kibana/cluster_actions/_meta/fields.yml
  metricbeat/module/kibana/cluster_actions/cluster_actions.go
  metricbeat/module/kibana/cluster_actions/data.go
  metricbeat/module/kibana/cluster_rules/_meta/data.json
  metricbeat/module/kibana/cluster_rules/_meta/docs.asciidoc
  metricbeat/module/kibana/cluster_rules/_meta/fields.yml
  metricbeat/module/kibana/cluster_rules/cluster_rules.go
  metricbeat/module/kibana/cluster_rules/data.go
  metricbeat/module/kibana/fields.go
  metricbeat/module/kibana/kibana.go
  metricbeat/module/kibana/mtest/testing.go
  metricbeat/module/kibana/node_actions/_meta/data.json
  metricbeat/module/kibana/node_actions/_meta/docs.asciidoc
  metricbeat/module/kibana/node_actions/_meta/fields.yml
  metricbeat/module/kibana/node_actions/data.go
  metricbeat/module/kibana/node_actions/node_actions.go
  metricbeat/module/kibana/node_rules/_meta/data.json
  metricbeat/module/kibana/node_rules/_meta/docs.asciidoc
  metricbeat/module/kibana/node_rules/_meta/fields.yml
  metricbeat/module/kibana/node_rules/data.go
  metricbeat/module/kibana/node_rules/node_rules.go
  metricbeat/module/kibana/settings/settings_test.go
  metricbeat/module/kibana/stats/stats_integration_test.go
  metricbeat/module/kibana/stats/stats_test.go
  metricbeat/module/kibana/status/status_integration_test.go
Labels: Team:Integrations, Feature: Stack Monitoring, backport-skip, Team:Elastic-Agent-Data-Plane, Team:Infra Monitoring UI

#31737 [Heartbeat] Add 'playwright_options' browser option
  CHANGELOG.next.asciidoc
  heartbeat/docs/monitors/monitor-browser.asciidoc
  x-pack/heartbeat/monitors/browser/config.go
  x-pack/heartbeat/monitors/browser/project.go
  x-pack/heartbeat/monitors/browser/project_test.go
Labels: enhancement, Heartbeat, Team:Uptime, v8.3.0

#31741 [automation] update elastic stack version for testing 7.17.4-d3844d00
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31720 [Release] Update test environments for 8.2.2
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#31731 [Release] Update test environments for 7.17.5
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#31751 docs: Prepare Changelog for 8.2.2
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#31752 Forward-port 8.2.2 changelog to main
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, backport-v8.3.0

#31759 Remove entries that are for 8.3
  CHANGELOG.asciidoc
Labels: Team:Docs, backport-skip

#31755 backport: Add 8.3 branch
  .mergify.yml
Labels: release, Team:Automation, impact:critical

#31763 Fix broken view commit links
  CHANGELOG.asciidoc
Labels: docs, Team:Docs

#31699 Make the queue's public API accept interface{} instead of publisher.Event
  CHANGELOG-developer.next.asciidoc
  libbeat/publisher/pipeline/pipeline_test.go
  libbeat/publisher/pipeline/ttl_batch.go
  libbeat/publisher/queue/diskqueue/benchmark_test.go
  libbeat/publisher/queue/diskqueue/consumer.go
  libbeat/publisher/queue/diskqueue/producer.go
  libbeat/publisher/queue/diskqueue/serialize.go
  libbeat/publisher/queue/diskqueue/serialize_test.go
  libbeat/publisher/queue/memqueue/ackloop.go
  libbeat/publisher/queue/memqueue/batchbuf.go
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/memqueue/eventloop.go
  libbeat/publisher/queue/memqueue/internal_api.go
  libbeat/publisher/queue/memqueue/produce.go
  libbeat/publisher/queue/queue.go
  libbeat/publisher/queue/queuetest/producer_cancel.go
  libbeat/publisher/queue/queuetest/queuetest.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#31756 [Release] update version to next minor 8.4.0
  libbeat/version/version.go
Labels: in progress, release, automation, Team:Automation

#31743 docs: update docs versions 8.2.2
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#31757 [Release] Update docs for the 8.4.0 release
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#31745 [Release] Update version to 8.2.3
  libbeat/version/version.go
Labels: release, Team:Automation

#31746 [Release] Update test environments for 8.2.3
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#31770 [automation] update elastic stack version for testing 7.17.5-18de74ad
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31774 [automation] update elastic stack version for testing 7.17.5-5c3baac2
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31534 [elastic/beats] Rabbitmq_1015: Add shovel metricset
  CHANGELOG.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/rabbitmq.asciidoc
  metricbeat/docs/modules/rabbitmq/shovel.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/rabbitmq/_meta/config.reference.yml
  metricbeat/module/rabbitmq/_meta/config.yml
  metricbeat/module/rabbitmq/_meta/docs.asciidoc
  metricbeat/module/rabbitmq/_meta/testdata/shovel_sample_response.json
  metricbeat/module/rabbitmq/fields.go
  metricbeat/module/rabbitmq/mtest/server.go
  metricbeat/module/rabbitmq/shovel/_meta/data.json
  metricbeat/module/rabbitmq/shovel/_meta/docs.asciidoc
  metricbeat/module/rabbitmq/shovel/_meta/fields.yml
  metricbeat/module/rabbitmq/shovel/data.go
  metricbeat/module/rabbitmq/shovel/shovel.go
  metricbeat/module/rabbitmq/shovel/shovel_test.go
  metricbeat/module/rabbitmq/url.go
  metricbeat/modules.d/rabbitmq.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: needs_integration_sync, backport-v8.3.0, Team:Service-Integrations

#31764 dev-tools/mage/target/integtest: fix comment
  dev-tools/mage/target/integtest/integtest.go
Labels: bug, docs, backport-skip, Team:Elastic-Agent-Data-Plane

#31781 chore: allow disable e2e test on the package job
  .ci/packaging.groovy
Labels: ci, Team:Automation

#31783 [automation] update elastic stack version for testing 7.17.5-366dc66d
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31766 Osquerybeat: Address all the new linter complains as of today
  x-pack/osquerybeat/beater/action_handler_test.go
  x-pack/osquerybeat/beater/config_plugin.go
  x-pack/osquerybeat/beater/config_plugin_test.go
  x-pack/osquerybeat/beater/osquery_runner_test.go
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/ext/osquery-extension/main.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/list.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/tables/host_processes.go
  x-pack/osquerybeat/internal/action/action.go
  x-pack/osquerybeat/internal/command/command.go
  x-pack/osquerybeat/internal/config/watcher.go
  x-pack/osquerybeat/internal/ecs/mapping.go
  x-pack/osquerybeat/internal/fileutil/fileutil.go
  x-pack/osquerybeat/internal/install/verify.go
  x-pack/osquerybeat/internal/install/verify_test.go
  x-pack/osquerybeat/internal/osqdcli/client.go
  x-pack/osquerybeat/internal/osqdcli/retry_test.go
  x-pack/osquerybeat/internal/tar/tar.go
  x-pack/osquerybeat/main_test.go
Labels: cleanup, Team:Asset Mgt

#25000 Use max_primary_shard_size instead of max_size
  libbeat/idxmgmt/ilm/config.go
  libbeat/tests/system/idxmgmt.py
  libbeat/tests/system/test_ilm.py
Labels: Team:Elastic-Agent-Control-Plane

#31780 Let filebeat tests connect to older ES versions.
  dev-tools/mage/integtest_docker.go
  filebeat/tests/system/test_pipeline.py
  libbeat/tests/system/config/libbeat.yml.j2
Labels: Team:Elastic-Agent-Data-Plane

#31773 Fix for flaky filestream parser tests
  filebeat/input/filestream/environment_test.go
Labels: flaky-test, Team:Elastic-Agent-Data-Plane

#31683 Disable low value linters.
  .golangci.yml
  dev-tools/mage/integtest.go
  dev-tools/mage/integtest_docker.go
  dev-tools/templates/.golangci.yml
  filebeat/inputsource/unix/server_test.go
  heartbeat/monitors/active/dialchain/tlsmeta/tlsmeta.go
  heartbeat/monitors/active/icmp/stdloop.go
  libbeat/outputs/shipper/api/shipper.pb.go
  libbeat/publisher/pipeline/pipeline.go
  libbeat/publisher/queue/diskqueue/benchmark_test.go
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/memqueue/queue_test.go
  winlogbeat/eventlog/wineventlog.go
  x-pack/filebeat/input/http_endpoint/gzip.go
  x-pack/filebeat/input/http_endpoint/validate.go
  x-pack/filebeat/input/httpjson/input_cursor.go
  x-pack/filebeat/input/httpjson/input_test.go
  x-pack/filebeat/input/httpjson/transform.go
  x-pack/filebeat/input/httpjson/transform_append_test.go
  x-pack/filebeat/input/httpjson/transform_set_test.go
  x-pack/filebeat/input/httpjson/transform_test.go
  x-pack/filebeat/processors/decode_cef/cef/cef_test.go
  x-pack/filebeat/processors/decode_cef/decode_cef_test.go
  x-pack/heartbeat/monitors/browser/source/project.go
  x-pack/winlogbeat/module/testing_windows.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#31771 Upgrade dependencies
  NOTICE.txt
  go.mod
  go.sum
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#31787 Update packages in dockerfile for the Dockerlogbeat
  x-pack/dockerlogbeat/Dockerfile.tmpl
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-v8.2.0, backport-v7.17.0
