Repository elastic/beats, pull requests merged in 2022-01, with the labels that each got.

#29664 [automation] update elastic stack version for testing 6.8.23-147f9e5f
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29410 x-pack/auditbeat/module/system/socket: get full length path and arg from /proc when not available from kprobe
  CHANGELOG.next.asciidoc
  NOTICE.txt
  x-pack/auditbeat/module/system/socket/events.go
  x-pack/auditbeat/module/system/socket/socket_linux.go
Labels: bug, Team:Security-External Integrations, backport-v8.0.0, 8.1-candidate

#29670 [automation] update elastic stack version for testing 6.8.23-9608d49e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29566 ci: elastic-agent goIntegTest is not available
  x-pack/elastic-agent/Jenkinsfile.yml
Labels: backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Control-Plane, backport-v7.17.0

#28954 Add kubernetes job name as the controller
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/metadata/pod_test.go
  libbeat/common/kubernetes/metadata/resource.go
Labels: Team:Integrations, backport-skip

#29294 Add more filtering options to journald input
  CHANGELOG.next.asciidoc
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/docs/inputs/input-journald.asciidoc
  filebeat/filebeat.reference.yml
  filebeat/input/journald/config.go
  filebeat/input/journald/input.go
  filebeat/input/journald/input_filtering_test.go
  filebeat/input/journald/input_parsers_test.go
  filebeat/input/journald/pkg/journalfield/default.go
  filebeat/input/journald/pkg/journalfield/matcher.go
  filebeat/input/journald/pkg/journalfield/matcher_test.go
  x-pack/filebeat/filebeat.reference.yml
Labels: breaking change, release-note:breaking, Team:Elastic-Agent-Data-Plane, v8.1.0, backport-v8.1.0

#29295 Add warning about removing Functionbeat
  x-pack/functionbeat/function/beater/functionbeat.go
  x-pack/functionbeat/manager/beater/functionbeat.go
  x-pack/functionbeat/manager/cmd/root.go
Labels: needs_docs, backport-v8.0.0, Team:Elastic-Agent-Data-Plane, 8.1-candidate

#29632 Update Beats docs to include ES CA fingerprint
  libbeat/docs/tab-widgets/set-connection.asciidoc
Labels: docs, review, backport-v8.0.0, Team:Elastic-Agent-Data-Plane

#29435 [Winlogbeat] Switch to ingest node processing
  CHANGELOG.next.asciidoc
  filebeat/fileset/compatibility.go
  filebeat/fileset/compatibility_test.go
  filebeat/fileset/fileset.go
  filebeat/fileset/modules_integration_test.go
  filebeat/fileset/pipelines.go
  libbeat/docs/command-reference.asciidoc
  winlogbeat/_meta/config/header.yml.tmpl
  winlogbeat/beater/winlogbeat.go
  winlogbeat/config/config.go
  winlogbeat/docs/index.asciidoc
  winlogbeat/docs/winlogbeat-options.asciidoc
  winlogbeat/module/pipeline.go
  winlogbeat/winlogbeat.reference.yml
  x-pack/winlogbeat/_meta/config/output-elasticsearch.yml.tmpl
  x-pack/winlogbeat/_meta/config/winlogbeat.event_logs.yml.tmpl
  x-pack/winlogbeat/cmd/export.go
  x-pack/winlogbeat/cmd/root.go
  x-pack/winlogbeat/module/pipeline.go
  x-pack/winlogbeat/module/powershell/config/winlogbeat-powershell.js
  x-pack/winlogbeat/module/powershell/ingest/powershell.yml
  x-pack/winlogbeat/module/powershell/ingest/powershell_operational.yml
  x-pack/winlogbeat/module/powershell/test/powershell_windows_test.go
  x-pack/winlogbeat/module/routing/ingest/routing.yml
  x-pack/winlogbeat/module/security/config/winlogbeat-security.js
  x-pack/winlogbeat/module/security/ingest/security.yml
  x-pack/winlogbeat/module/security/test/security_windows_test.go
  x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js
  x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml
  x-pack/winlogbeat/module/sysmon/test/sysmon_windows_test.go
  x-pack/winlogbeat/winlogbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.yml
Labels: breaking change, release-note:breaking, Team:Security-External Integrations, backport-v8.0.0

#23872 [packaging] Bump golang-crossbuild version debian8
  dev-tools/mage/crossbuild.go
  x-pack/auditbeat/magefile.go
Labels: Packaging, Team:Automation, backport-v8.0.0, backport-v7.17.0

#29569 Fix example command to avoid showing system module under windows
  filebeat/docs/filebeat-modules-options.asciidoc
  filebeat/docs/getting-started.asciidoc
  libbeat/docs/tab-widgets/start.asciidoc
  metricbeat/docs/getting-started.asciidoc
Labels: v8.0.0, Team:Docs, v7.16.0, backport-v8.0.0, backport-v7.16.0, v7.17.0, backport-v7.17.0

#29702 [automation] update elastic stack version for testing 8.1.0-1f83f9c5
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29700 [automation] update elastic stack version for testing 8.0.0-f6fa8fcc
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29704 notice: update copyright year
  NOTICE.txt
Labels: needs_team, backport-v7.16.0

#29651 Allow elastic agent in containers to use basic auth to get service token
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/container.go
  x-pack/elastic-agent/pkg/agent/cmd/setup_config.go
Labels: enhancement, backport-v8.0.0, Team:Elastic-Agent-Control-Plane

#29443 docs: reorder kubernetes provider section
  libbeat/docs/shared-autodiscover.asciidoc
Labels: v8.0.0, Team:Docs, backport-v8.0.0

#29721 [automation] update elastic stack version for testing 8.1.0-af114d16
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29719 [automation] update elastic stack version for testing 8.0.0-37ccb579
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29711 cluster_stats: use correct license value
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/cluster_stats/data.go
  metricbeat/module/elasticsearch/test_elasticsearch.py
Labels: Team:Integrations, Stack monitoring, v8.0.0, backport-v8.0.0, v8.1.0

#29722 fix: resolve conflict in 455b052569
  libbeat/docs/shared-autodiscover.asciidoc
Labels: needs_team

#29697 [Heartbeat] Separate http req per task
  CHANGELOG.next.asciidoc
  heartbeat/monitors/active/http/task.go
  heartbeat/monitors/active/http/task_test.go
Labels: bug, Heartbeat, Team:Uptime, backport-v8.0.0, backport-v7.17.0

#29729 [Heartbeat] Use timer.reset now that golang has been updated
  heartbeat/scheduler/timerqueue/queue.go
Labels: enhancement, Heartbeat, Team:Uptime, technical debt, backport-v8.0.0, backport-v7.17.0

#29735 [automation] update elastic stack version for testing 6.8.23-7c0fa232
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29737 [automation] update elastic stack version for testing 8.1.0-5e490954
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29727 Do not mention removal if version is not specified in `cfgwarn` messages
  libbeat/common/cfgwarn/cfgwarn.go
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#29736 [automation] update elastic stack version for testing 8.0.0-fd4587f2
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29744 System/socket: Support kernel_clone() replacement for _do_fork()
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/socket/template.go
Labels: bug, review, Auditbeat, Team:Security-External Integrations, backport-v8.0.0, backport-v7.16.0, backport-v8.1.0, backport-v7.17.0

#29753 docs: update docs versions 7.16.3
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#29756 docs: update docs versions 6.8.23
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#29758 docs: Prepare Changelog for 6.8.23
  CHANGELOG.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#29759 docs: Prepare Changelog for 7.16.3
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#29601 auditd: Store program arguments in process.args array
  CHANGELOG.next.asciidoc
  filebeat/module/auditd/log/ingest/pipeline.yml
  filebeat/module/auditd/log/test/audit-cent7-node.log-expected.json
  filebeat/module/auditd/log/test/audit-rhel6.log-expected.json
  filebeat/module/auditd/log/test/audit-rhel7.log-expected.json
  filebeat/module/auditd/log/test/audit-ubuntu1604.log-expected.json
  filebeat/module/auditd/log/test/avc.log-expected.json
  filebeat/module/auditd/log/test/execve.log
  filebeat/module/auditd/log/test/execve.log-expected.json
  filebeat/module/auditd/log/test/test.log-expected.json
  filebeat/module/auditd/log/test/useradd.log-expected.json
  filebeat/tests/system/test_modules.py
Labels: breaking change, Team:Security-External Integrations, backport-v8.0.0, backport-v8.1.0

#29766 Forward port changelog for 7.16.3 to 7.17
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: release, Team:Automation, backport-skip

#29768 Regenerate golden files for Cisco ASA and Cyberarkpas modules
  x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/288_auto_clear_users_history_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/289_auto_clear_users_history_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/310_monitor_dr_replication_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/311_monitor_dr_replication_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/357_monitor_fw_rules_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/358_monitor_fw_rules_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/479_security_warning_the_signature_hash_algorithm_of_the_vault_certificate_is_sha1.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/59_clear_safe_history.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/88_set_password.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/legacysyslog.log-expected.json
Labels: Team:Integrations, Team:Security-External Integrations, 7.16 candidate

#29770 Forward port 7.16.3 changelog to 8.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: release, Team:Automation, backport-skip

#29769 Regenerate golden files for Cisco ASA and Cyberarkpas modules
  x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/288_auto_clear_users_history_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/289_auto_clear_users_history_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/310_monitor_dr_replication_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/311_monitor_dr_replication_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/357_monitor_fw_rules_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/358_monitor_fw_rules_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/479_security_warning_the_signature_hash_algorithm_of_the_vault_certificate_is_sha1.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/59_clear_safe_history.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/88_set_password.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/legacysyslog.log-expected.json
Labels: Team:Integrations, Team:Security-External Integrations

#29777 Forward port 7.16.3 changelog to master
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: release, Team:Automation, backport-skip

#29723 Warn users when connecting to older Elasticsearch instances
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
Labels: Team:Elastic-Agent-Data-Plane

#29706 ci: uses aliases for the branches
  .ci/schedule-daily.groovy
  .ci/schedule-weekly.groovy
Labels: automation, Team:Automation, backport-skip

#29784 [automation] update elastic stack version for testing 7.17.0-9b8314f9
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29775 Do not add date to index if `@meta.index` is set
  libbeat/beat/events/util.go
  libbeat/idxmgmt/std.go
  libbeat/idxmgmt/std_test.go
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane

#29773 ibmmq: Fix timestamp parsing
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/module/ibmmq/errorlog/ingest/pipeline.yml
  x-pack/filebeat/module/ibmmq/errorlog/test/AMQERR01.log-expected.json
  x-pack/filebeat/module/ibmmq/errorlog/test/AMQERR01_QM1.log-expected.json
  x-pack/filebeat/module/ibmmq/errorlog/test/AMQERR01_QM2.log-expected.json
Labels: review, Filebeat, Team:Integrations, backport-v8.0.0

#29572 Add k8s metadata in state_cronjob metricset
  CHANGELOG.next.asciidoc
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-role.yaml
  libbeat/common/kubernetes/informer.go
  libbeat/common/kubernetes/metadata/pod.go
  libbeat/common/kubernetes/metadata/resource.go
  libbeat/common/kubernetes/types.go
  metricbeat/module/kubernetes/state_cronjob/_meta/docs.asciidoc
  metricbeat/module/kubernetes/state_cronjob/state_cronjob.go
  metricbeat/module/kubernetes/state_cronjob/state_cronjob_integration_test.go
  metricbeat/module/kubernetes/test/integration.go
  metricbeat/module/kubernetes/util/kubernetes.go
Labels: Team:Integrations, backport-v8.1.0

#29707 jjbb: remove obsoleted branches (<7.16)
  .ci/jobs/apm-beats-update.yml
  .ci/jobs/beats-tester.yml
  .ci/jobs/beats.yml
  .ci/jobs/packaging.yml
Labels: Team:Automation, backport-skip

#29679 Cherry-pick #28954 to 7.17: Add kubernetes job name as the controller
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/metadata/pod_test.go
  libbeat/common/kubernetes/metadata/resource.go
Labels: backport, [zube]: In Review, Team:Integrations

#29785 [automation] update elastic stack version for testing 8.0.0-ed041828
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29676 Remove overriding of index pattern on the Kubernetes overview dashboard
  CHANGELOG.next.asciidoc
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/174a6ad0-30e0-11e7-8df8-6d3604a72912-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/da1ff7c0-30ed-11e7-b9e5-2b5b07213ab3-ecs.json
  metricbeat/module/kubernetes/_meta/kibana/7/visualization/e1018b90-2bfb-11e7-859b-f78b612cde28-ecs.json
Labels: Team:Integrations, backport-v7.17.0

#28213 Add a readme for k8s autodiscover provider
  libbeat/autodiscover/README.md
  x-pack/elastic-agent/pkg/composable/providers/kubernetes/README.md
Labels: docs, Team:Integrations, backport-skip

#29795 Prepare 8.0.0-rc1 changelog
  CHANGELOG.asciidoc
  libbeat/docs/release.asciidoc
Labels: release, Team:Docs, backport-skip

#29783 [automation] update elastic stack version for testing 8.1.0-7004acda
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29717 libbeat/processors/add_process_metadata: implement a process cache eviction policy
  CHANGELOG.next.asciidoc
  libbeat/processors/add_process_metadata/add_process_metadata.go
  libbeat/processors/add_process_metadata/cache.go
  libbeat/processors/add_process_metadata/cache_test.go
Labels: bug, Team:Security-External Integrations, backport-v8.0.0, 8.1-candidate

#29681 Change docker image from CentOS 7 to Ubuntu 20.04
  .ci/packer_cache.sh
  CHANGELOG.next.asciidoc
  auditbeat/Dockerfile
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
  filebeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/Dockerfile
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: Team:Automation, backport-skip, Team:Elastic-Agent-Control-Plane

#29803 [automation] update elastic stack version for testing 6.8.23-d234ee69
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29606 Add summary to journeys which don't emit journey:end (early node subprocess exits)
  CHANGELOG.next.asciidoc
  libbeat/README.md
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer.go
  x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
Labels: bug, Team:Uptime, backport-v8.0.0, backport-v7.17.0

#29781 [Winlogbeat] Add provider name to Security routing pipeline check
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/routing/ingest/routing.yml
Labels: bug, Team:Security-External Integrations, backport-v8.1.0

#29800 [Elastic Agent] Fix issue with ensureServiceToken.
  x-pack/elastic-agent/pkg/agent/cmd/container.go
Labels: backport-v8.0.0, Team:Elastic-Agent-Control-Plane

#29683 Only connect to Elasticsearch instances with the same version or newer
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/Jenkinsfile.yml
  filebeat/filebeat.reference.yml
  filebeat/tests/system/test_modules.py
  heartbeat/heartbeat.reference.yml
  libbeat/_meta/config/output-elasticsearch.reference.yml.tmpl
  libbeat/cmd/instance/beat.go
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/config.go
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
  libbeat/tests/system/config/mockbeat.yml.j2
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Elastic-Agent-Data-Plane, backport-v8.1.0

#29821 Update ECS field definitions to latest 8.0.0-dev
  auditbeat/docs/fields.asciidoc
  auditbeat/include/fields.go
  filebeat/docs/fields.asciidoc
  filebeat/include/fields.go
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  libbeat/_meta/fields.ecs.yml
  metricbeat/docs/fields.asciidoc
  metricbeat/include/fields/fields.go
  packetbeat/docs/fields.asciidoc
  packetbeat/include/fields.go
  winlogbeat/docs/fields.asciidoc
  winlogbeat/include/fields.go
  x-pack/functionbeat/docs/fields.asciidoc
  x-pack/functionbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
  x-pack/osquerybeat/docs/fields.asciidoc
  x-pack/osquerybeat/include/fields.go
Labels: bug, review, ecs, Team:Integrations, Team:Security-External Integrations, backport-v8.0.0

#29605 Fix annotation enrichment
  CHANGELOG.next.asciidoc
  libbeat/common/kubernetes/metadata/metadata.go
  libbeat/common/kubernetes/metadata/node_test.go
  libbeat/common/kubernetes/metadata/pod.go
  libbeat/common/kubernetes/metadata/pod_test.go
  libbeat/common/kubernetes/metadata/service_test.go
Labels: bug, Team:Integrations, backport-v7.17.0

#29814 Update containerd library
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Integrations, backport-skip

#29032 CI: add GitHub actions for macos (push based)
  .github/workflows/macos-auditbeat.yml
  .github/workflows/macos-filebeat.yml
  .github/workflows/macos-heartbeat.yml
  .github/workflows/macos-metricbeat.yml
  .github/workflows/macos-packetbeat.yml
  .github/workflows/macos-xpack-auditbeat.yml
  .github/workflows/macos-xpack-filebeat.yml
  .github/workflows/macos-xpack-functionbeat.yml
  .github/workflows/macos-xpack-heartbeat.yml
  .github/workflows/macos-xpack-metricbeat.yml
  .github/workflows/macos-xpack-osquerybeat.yml
  .github/workflows/macos-xpack-packetbeat.yml
Labels: automation, Team:Automation, backport-skip

#29780 Replace location of apoydence/eachers to poy/eachers
  NOTICE.txt
  go.mod
  go.sum
Labels: review, backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v7.17.0

#29835 Update version of jinja2
  libbeat/tests/system/requirements_aix.txt
Labels: Team:Integrations, backport-skip

#29819 Follow up changes in documentation about data streams
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  libbeat/_meta/config/output-elasticsearch.reference.yml.tmpl
  libbeat/_meta/config/setup.ilm.reference.yml.tmpl
  libbeat/docs/howto/change-index-name.asciidoc
  libbeat/docs/howto/load-index-templates.asciidoc
  libbeat/docs/shared-ilm.asciidoc
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane

#29563 [Elastic Agent] Add doc on how Fleet Server is bootstrapped.
  x-pack/elastic-agent/docs/fleet-server-bootstrap.asciidoc
Labels: backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v7.17.0

#29757 [Release] Update version to 6.8.24
  libbeat/version/version.go
Labels: release, Team:Automation

#29754 [Release] Update version to 7.16.4
  libbeat/version/version.go
Labels: release, Team:Automation

#29844 Remove deprecated old name for aws cloudwatch input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awscloudwatch/input.go
Labels: Team:Integrations, backport-v8.0.0

#29829 Add links to azure docs
  filebeat/docs/modules/azure.asciidoc
  x-pack/filebeat/module/azure/_meta/docs.asciidoc
Labels: docs, Team:Docs, backport-v7.14.0, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0, backport-v7.17.0

#29794 Add note on docker container as a requirement for browser monitors
  heartbeat/docs/monitors/monitor-browser.asciidoc
Labels: docs, Heartbeat, Team:Uptime, v8.0.0

#29857 [automation] update elastic stack version for testing 7.17.0-560490e9
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29708 Move `umask` from code to service files
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/darwin/launchd-daemon.plist.tmpl
  dev-tools/packaging/templates/linux/beatname.sh.tmpl
  dev-tools/packaging/templates/linux/elastic-agent.sh.tmpl
  dev-tools/packaging/templates/linux/elastic-agent.unit.tmpl
  dev-tools/packaging/templates/linux/systemd.unit.tmpl
  filebeat/docs/filebeat-general-options.asciidoc
  libbeat/cmd/instance/beat.go
  libbeat/cmd/instance/settings.go
  libbeat/cmd/instance/umask_other.go
  libbeat/cmd/instance/umask_windows.go
  libbeat/docs/loggingconfig.asciidoc
  libbeat/docs/shared-brew-run.asciidoc
  libbeat/docs/shared-systemd.asciidoc
  libbeat/tests/system/test_umask.py
Labels: review, backport-skip, Team:Elastic-Agent-Data-Plane, v8.1.0

#29247 Containerd metricbeat module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/containerd.asciidoc
  metricbeat/docs/modules/containerd/blkio.asciidoc
  metricbeat/docs/modules/containerd/cpu.asciidoc
  metricbeat/docs/modules/containerd/memory.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/containerd/_meta/config.yml
  x-pack/metricbeat/module/containerd/_meta/docs.asciidoc
  x-pack/metricbeat/module/containerd/_meta/fields.yml
  x-pack/metricbeat/module/containerd/_meta/test/containerd.v1.5.2
  x-pack/metricbeat/module/containerd/blkio/_meta/data.json
  x-pack/metricbeat/module/containerd/blkio/_meta/docs.asciidoc
  x-pack/metricbeat/module/containerd/blkio/_meta/fields.yml
  x-pack/metricbeat/module/containerd/blkio/_meta/test/containerd.v1.5.2.expected
  x-pack/metricbeat/module/containerd/blkio/blkio.go
  x-pack/metricbeat/module/containerd/blkio/blkio_test.go
  x-pack/metricbeat/module/containerd/config.go
  x-pack/metricbeat/module/containerd/containerd.go
  x-pack/metricbeat/module/containerd/cpu/_meta/data.json
  x-pack/metricbeat/module/containerd/cpu/_meta/docs.asciidoc
  x-pack/metricbeat/module/containerd/cpu/_meta/fields.yml
  x-pack/metricbeat/module/containerd/cpu/_meta/test/containerd.v1.5.2.expected
  x-pack/metricbeat/module/containerd/cpu/_meta/testdata/config.yml
  x-pack/metricbeat/module/containerd/cpu/_meta/testdata/docs.plain
  x-pack/metricbeat/module/containerd/cpu/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/containerd/cpu/cpu.go
  x-pack/metricbeat/module/containerd/cpu/cpu_test.go
  x-pack/metricbeat/module/containerd/doc.go
  x-pack/metricbeat/module/containerd/fields.go
  x-pack/metricbeat/module/containerd/helper.go
  x-pack/metricbeat/module/containerd/memory/_meta/data.json
  x-pack/metricbeat/module/containerd/memory/_meta/docs.asciidoc
  x-pack/metricbeat/module/containerd/memory/_meta/fields.yml
  x-pack/metricbeat/module/containerd/memory/_meta/test/containerd.v1.5.2.expected
  x-pack/metricbeat/module/containerd/memory/memory.go
  x-pack/metricbeat/module/containerd/memory/memory_test.go
  x-pack/metricbeat/modules.d/containerd.yml.disabled
Labels: enhancement, Team:Integrations, backport-v8.1.0

#29869 Update Index template loading guide to use the correct endpoint
  libbeat/docs/howto/load-index-templates.asciidoc
  libbeat/docs/upgrading.asciidoc
Labels: backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#29881 [automation] update elastic stack version for testing 8.1.0-677b9ef0
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29867 Copy small helpers to Elastic Agent from Beats to reduce dependency on Libbeat
  x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway.go
  x-pack/elastic-agent/pkg/agent/application/info/agent_id.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/rollback.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/cmd/install.go
  x-pack/elastic-agent/pkg/cli/confirm.go
  x-pack/elastic-agent/pkg/cli/input.go
  x-pack/elastic-agent/pkg/core/backoff/backoff.go
  x-pack/elastic-agent/pkg/core/backoff/backoff_test.go
  x-pack/elastic-agent/pkg/core/backoff/equal_jitter.go
  x-pack/elastic-agent/pkg/core/backoff/exponential.go
  x-pack/elastic-agent/pkg/core/retry/retrystrategy.go
  x-pack/elastic-agent/pkg/core/retry/retrystrategy_test.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#29680 doc: update filebeat dissect processor field tokenization example
  libbeat/processors/dissect/docs/dissect.asciidoc
Labels: docs, Filebeat, Team:Elastic-Agent, backport-v8.0.0, backport-v7.16.0, backport-v7.17.0

#29879 Enable require_alias for Bulk requests for all actions when target is a write alias
  CHANGELOG.next.asciidoc
  libbeat/esleg/eslegclient/bulkapi.go
  libbeat/idxmgmt/std.go
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/elasticsearch/death_letter_selector.go
  libbeat/outputs/outil/select.go
  libbeat/outputs/output_reg.go
Labels: Team:Elastic-Agent-Data-Plane

#29887 Note that filesets are disabled by default in Filebeat documentation
  filebeat/docs/getting-started.asciidoc
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane

#29302 Check that `info.NCPU` is not zero
  dev-tools/mage/common.go
Labels: bug, Team:Elastic-Agent, backport-skip

#29413 [Heartbeat] Defer monitor / ICMP errors to monitor runtime / ES
  CHANGELOG.next.asciidoc
  heartbeat/monitors/active/icmp/icmp.go
  heartbeat/monitors/active/icmp/loop.go
  heartbeat/monitors/active/icmp/stdloop.go
  heartbeat/monitors/factory_test.go
  heartbeat/monitors/mocks_test.go
  heartbeat/monitors/monitor.go
  heartbeat/monitors/monitor_test.go
  heartbeat/monitors/stdfields/stdfields.go
  heartbeat/monitors/task.go
  heartbeat/tests/system/test_icmp.py
  x-pack/heartbeat/.gitignore
Labels: bug, Heartbeat, Team:Uptime, v8.0.0, backport-v8.0.0, backport-v7.16.0, v7.17.0

#29864 [automation] update elastic stack version for testing 7.17.0-079761a0
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29663 Fix YAML indentation in `parsers` examples
  filebeat/docs/inputs/input-filestream-reader-options.asciidoc
Labels: Team:Elastic-Agent, backport-v8.0.0, forwardport-master, backport-v7.17.0

#29866 [automation] update elastic stack version for testing 8.0.0-b44c2e43
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29900 [Heartbeat] Fix broken macOS ICMP test
  CHANGELOG.next.asciidoc
  heartbeat/tests/system/test_icmp.py
Labels: bug, Team:Uptime, backport-skip

#29698 x-pack/filebeat/module/cisco: fix event.{outcome,type} handling
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/asa-fix.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/asa.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/filtered.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/not-ip.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/asa-fix.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/asa.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/not-ip.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/security-connection.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: bug, Team:Security-External Integrations, backport-v8.0.0, 8.1-candidate

#29786 x-pack/auditbeat/module/system/process: don't try to hash files in other namespaces
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/process/namepace_linux.go
  x-pack/auditbeat/module/system/process/namepace_other.go
  x-pack/auditbeat/module/system/process/process.go
Labels: enhancement, Team:Security-External Integrations, backport-v8.0.0, 8.1-candidate

#29904 [automation] update elastic stack version for testing 7.17.0-68da5d12
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29903 [automation] update elastic stack version for testing 8.1.0-f5a18001
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29905 [automation] update elastic stack version for testing 8.0.0-129ef708
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29913 [Metricbeat] gcp.gke: fix overview dashboard
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/gcp/_meta/kibana/7/dashboard/1ae960c0-f9f8-11eb-bc38-79936db7c106.json
Labels: bug, Team:Integrations, backport-v8.0.0, backport-v7.17.0

#29924 [automation] update elastic stack version for testing 6.8.24-7dcce198
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29923 [automation] update elastic stack version for testing 8.0.0-f196e060
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29922 [automation] update elastic stack version for testing 7.17.0-e1efbe3a
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29873 [Documentation] Istio Module documentation clarification
  metricbeat/docs/modules/istio.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/istio/_meta/config.reference.yml
  x-pack/metricbeat/module/istio/_meta/config.yml
  x-pack/metricbeat/module/istio/_meta/docs.asciidoc
  x-pack/metricbeat/modules.d/istio.yml.disabled
Labels: Team:Integrations, backport-v8.1.0

#28813 Packaging: rename arm64 suffix to aarch64 in the tar.gz artifacts ONLY
  CHANGELOG.next.asciidoc
  dev-tools/mage/pkgtypes.go
  x-pack/elastic-agent/magefile.go
  x-pack/elastic-agent/pkg/artifact/artifact.go
  x-pack/elastic-agent/pkg/artifact/download/http/elastic_test.go
Labels: Packaging, Team:Automation, backport-v8.0.0

#29875 Fix istio docs regarding default metricsets
  metricbeat/docs/modules/istio.asciidoc
  x-pack/metricbeat/module/istio/_meta/docs.asciidoc
Labels: Team:Integrations, needs_reviewer, backport-v8.1.0

#29930 Re add the ability for container commands to access kibana env vars
  x-pack/elastic-agent/pkg/agent/cmd/setup_config.go
Labels: bug, backport-v8.0.0, Team:Elastic-Agent-Control-Plane

#29931 [Elastic Agent] Change to check for fleet server enable not fleet enrollment for ensureServiceToken
  x-pack/elastic-agent/pkg/agent/cmd/container.go
Labels: backport-v8.0.0, Team:Elastic-Agent-Control-Plane

#29902 Add beat/process config to elastic agent diagnostics collect
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/diagnostics.go
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane

#29937 [automation] update elastic stack version for testing 6.8.24-98b58fc7
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29938 [automation] update elastic stack version for testing 7.17.0-1bd58b32
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29955 [automation] update elastic stack version for testing 6.8.24-249d8e5f
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29954 [automation] update elastic stack version for testing 8.0.0-6ce456eb
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29956 [automation] update elastic stack version for testing 7.17.0-ab4975a2
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29755 [Release] Update test environments for 7.16.4
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  testing/environments/prev-minor.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#29960 ci: docker login for pulling
  .ci/packaging.groovy
Labels: automation, Team:Automation, backport-v8.0.0, backport-v7.17.0

#29908 Allign k8s configuration settings
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/config.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/processors/add_kubernetes_metadata/config.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/_meta/config.yml
  metricbeat/module/kubernetes/util/kubernetes.go
  metricbeat/modules.d/kubernetes.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Integrations, backport-v8.1.0

#29724 Return early from IsRestartNeeded()
  x-pack/elastic-agent/pkg/core/plugin/common.go
Labels: cleanup, backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v8.1.0

#29957 x-pack/winlogbeat/module/sysmon: add eventid 26 handler
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml
  x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-11-filedeletedetected.evtx
  x-pack/winlogbeat/module/sysmon/test/testdata/sysmon-11-filedeletedetected.evtx.golden.json
Labels: enhancement, Team:Security-External Integrations, backport-v8.0.0, 8.1-candidate

#29969 [Filebeat] Improve aws-s3 gzip file detection to avoid false negatives
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/s3_objects.go
Labels: bug, Filebeat, Team:Integrations, Team:Security-External Integrations, backport-v8.0.0, backport-v7.17.0

#29457 Increase recommended k8s resource requests / limits
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/heartbeat/heartbeat-deployment.yaml
Labels: bug, Team:Uptime, backport-v8.0.0, backport-v7.17.0

#29948 [Heartbeat] Change size of data on ICMP packet
  CHANGELOG.next.asciidoc
  heartbeat/monitors/active/icmp/stdloop.go
Labels: Team:Uptime, backport-v8.0.0, backport-v7.17.0

#29983 [automation] update elastic stack version for testing 7.16.4-206b88b5
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29890 [Elastic Agent] Fix some typos
  dev-tools/mage/crossbuild.go
  libbeat/common/backoff/equal_jitter.go
  libbeat/logp/configure/logging.go
  libbeat/logp/core.go
  x-pack/elastic-agent/magefile.go
  x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/pipeline.go
  x-pack/elastic-agent/pkg/agent/application/reexec/manager.go
  x-pack/elastic-agent/pkg/core/server/server.go
  x-pack/elastic-agent/pkg/core/status/reporter.go
Labels: cleanup, backport-skip, Team:Elastic-Agent-Control-Plane

#29985 Add note to documentation about dashboard loading in Beats
  libbeat/docs/dashboardsconfig.asciidoc
Labels: docs, backport-v7.13.0, backport-v7.14.0, backport-v8.0.0, backport-v7.15.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#29695 Support running multiple log groups in cloudwatch input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-cloudwatch.asciidoc
  x-pack/filebeat/input/awscloudwatch/_meta/terraform/.gitignore
  x-pack/filebeat/input/awscloudwatch/_meta/terraform/.terraform.lock.hcl
  x-pack/filebeat/input/awscloudwatch/_meta/terraform/README.md
  x-pack/filebeat/input/awscloudwatch/_meta/terraform/main.tf
  x-pack/filebeat/input/awscloudwatch/_meta/terraform/outputs.tf
  x-pack/filebeat/input/awscloudwatch/_meta/terraform/variables.tf
  x-pack/filebeat/input/awscloudwatch/cloudwatch.go
  x-pack/filebeat/input/awscloudwatch/config.go
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/filebeat/input/awscloudwatch/input_integration_test.go
  x-pack/filebeat/input/awscloudwatch/input_test.go
  x-pack/filebeat/input/awscloudwatch/metrics.go
  x-pack/filebeat/input/awscloudwatch/processor.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_benchmark_test.go
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/interfaces.go
  x-pack/filebeat/input/awss3/mock_interfaces_test.go
  x-pack/filebeat/input/awss3/s3.go
  x-pack/filebeat/input/awss3/s3_objects.go
  x-pack/filebeat/input/awss3/s3_objects_test.go
  x-pack/filebeat/input/awss3/s3_test.go
  x-pack/filebeat/input/awss3/sqs.go
  x-pack/filebeat/input/awss3/sqs_s3_event.go
  x-pack/filebeat/input/awss3/sqs_s3_event_test.go
  x-pack/filebeat/input/awss3/sqs_test.go
  x-pack/filebeat/input/default-inputs/inputs_other.go
  x-pack/libbeat/common/aws/acker.go
  x-pack/libbeat/common/aws/acker_test.go
  x-pack/libbeat/common/aws/semaphore.go
  x-pack/libbeat/common/aws/semaphore_test.go
Labels: Team:Integrations, backport-v8.0.0

#29994 [auditbeat] Flaky: use CI=true to skip test
  auditbeat/module/file_integrity/metricset_test.go
Labels: Team:SIEM, backport-v8.0.0

#29966 Add the Elastic product origin header when talking to Elasticsearch or Kibana.
  libbeat/common/productorigin/productorigin.go
  libbeat/esleg/eslegclient/connection.go
  libbeat/esleg/eslegclient/connection_test.go
  metricbeat/module/elasticsearch/metricset.go
  metricbeat/module/kibana/settings/settings.go
  metricbeat/module/kibana/stats/stats.go
  metricbeat/module/kibana/status/status.go
Labels: enhancement, backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#30007 Revert changes in the artifact build from #29890
  dev-tools/mage/crossbuild.go
Labels: build-system, backport-skip, Team:Elastic-Agent-Control-Plane

#30011 [automation] update elastic stack version for testing 6.8.24-3c1da3a7
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29961 [Elastic Agent] Keep debug symbols, no inline and no optimisations for dev builds
  dev-tools/mage/build.go
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane, v8.1.0

#29761 [automation] Update go release version 1.17.6
  .go-version
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/elastic-agent/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
Labels: automation, Team:Automation, dependency, backport-v8.0.0, backport-v7.17.0

#29993 osquerybeat/ext: Make packages non-internal.
  x-pack/osquerybeat/ext/osquery-extension/main_darwin.go
  x-pack/osquerybeat/ext/osquery-extension/main_linux.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/hostfs/common.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/hostfs/group.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/hostfs/passwd.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/cmdline.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/io.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/link.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/list.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/stat.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/strconv.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/uptime.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/tables/host_groups.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/tables/host_processes.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/tables/host_users.go
Labels: enhancement, backport-v8.0.0, Team:Cloud-Security-Posture

#29999 ci: fail fast when installing the windows tools
  .ci/scripts/install-tools.bat
Labels: automation, Team:Automation, backport-v8.0.0, backport-v7.17.0

#29584 [Metricbeat] support credentials_json in gcp module
  CHANGELOG-developer.next.asciidoc
  x-pack/metricbeat/module/gcp/billing/billing.go
  x-pack/metricbeat/module/gcp/metrics/metricset.go
Labels: Team:Integrations

#30027 Update prev-minor testing environment to 8.0 on master (8.1)
  testing/environments/prev-minor.yml
Labels: needs_team, backport-skip

#30025 Document how timestamps set in Kafka messages affect retention
  libbeat/outputs/kafka/docs/kafka.asciidoc
Labels: docs, backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane, v8.1.0, backport-v7.17.0

#30039 Correctly fixe how selected packages are defined
  dev-tools/mage/crossbuild.go
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#30038 [Filebeat] Fix panic in decode_cef when recovering from invalid data
  CHANGELOG.next.asciidoc
  x-pack/filebeat/processors/decode_cef/cef/cef.go
  x-pack/filebeat/processors/decode_cef/cef/cef.rl
  x-pack/filebeat/processors/decode_cef/cef/cef_test.go
  x-pack/filebeat/processors/decode_cef/cef/parser.go
Labels: bug, Filebeat, needs_team, backport-v8.0.0, backport-v7.17.0

#29112 x-pack/packetbeat: install Npcap at start-up when required
  CHANGELOG.next.asciidoc
  NOTICE.txt
  dev-tools/mage/config.go
  dev-tools/mage/crossbuild.go
  dev-tools/mage/settings.go
  dev-tools/notice/NOTICE.txt.tmpl
  dev-tools/packaging/package_test.go
  go.mod
  packetbeat/README.md
  packetbeat/_meta/config/beat.reference.yml.tmpl
  packetbeat/_meta/config/beat.yml.tmpl
  packetbeat/_meta/config/windows_npcap.yml.tmpl
  packetbeat/beater/install_npcap.go
  packetbeat/beater/packetbeat.go
  packetbeat/npcap/npcap.go
  packetbeat/npcap/npcap_other.go
  packetbeat/npcap/npcap_test.go
  packetbeat/npcap/npcap_windows.go
  packetbeat/npcap/testdata/mock_installer.go
  packetbeat/npcap/testdata/mock_uninstaller.go
  packetbeat/scripts/mage/package.go
  x-pack/packetbeat/LICENSE-Npcap.txt
  x-pack/packetbeat/cmd/root.go
  x-pack/packetbeat/magefile.go
  x-pack/packetbeat/npcap/installer/.gitignore
  x-pack/packetbeat/npcap/installer/LICENSE
  x-pack/packetbeat/npcap/installer/README
  x-pack/packetbeat/npcap/installer/npcap-0.00.exe
  x-pack/packetbeat/npcap/npcap_other.go
  x-pack/packetbeat/npcap/npcap_windows.go
Labels: enhancement, Packetbeat, Team:Automation, Team:Security-External Integrations, backport-v8.0.0, 8.1-candidate

#30045 [automation] update elastic stack version for testing 7.16.4-1b320a84
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30046 [automation] update elastic stack version for testing 8.0.0-e2e78bad
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30047 [automation] update elastic stack version for testing 7.17.0-b9de125e
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29997 probot: update stale dates
  .github/stale.yml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane

#29918 [Metricbeat] gcp: add firestore metricset
  CHANGELOG-developer.next.asciidoc
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/gcp.asciidoc
  metricbeat/docs/modules/gcp/firestore.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/gcp/_meta/config.yml
  x-pack/metricbeat/module/gcp/constants.go
  x-pack/metricbeat/module/gcp/fields.go
  x-pack/metricbeat/module/gcp/firestore/_meta/data.json
  x-pack/metricbeat/module/gcp/firestore/_meta/data_document.json
  x-pack/metricbeat/module/gcp/firestore/_meta/docs.asciidoc
  x-pack/metricbeat/module/gcp/firestore/_meta/fields.yml
  x-pack/metricbeat/module/gcp/firestore/firestore_integration_test.go
  x-pack/metricbeat/module/gcp/firestore/firestore_test.go
  x-pack/metricbeat/module/gcp/firestore/manifest.yml
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
  x-pack/metricbeat/module/gcp/metrics/response_parser.go
  x-pack/metricbeat/module/gcp/module.yml
  x-pack/metricbeat/modules.d/gcp.yml.disabled
Labels: Team:Integrations, backport-v8.1.0

#30009 [Auditbeat] Include the error message with auditd module events
  CHANGELOG.next.asciidoc
  auditbeat/module/auditd/audit_linux.go
Labels: Auditbeat, Team:Security-External Integrations, backport-skip

#29943 filebeat/generator/fields: fix dropped error
  filebeat/generator/fields/fields.go
Labels: bug, Filebeat, backport-skip, Team:Elastic-Agent-Data-Plane

#30040 Remove msitools install for windows build, using the latest docker image with msitools preinstalled
  x-pack/osquerybeat/magefile.go
Labels: cleanup, Team:Asset Mgt, backport-skip

#30058 Revert "Enable require_alias for Bulk requests for all actions when t…
  CHANGELOG.next.asciidoc
  libbeat/esleg/eslegclient/bulkapi.go
  libbeat/idxmgmt/std.go
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/elasticsearch/death_letter_selector.go
  libbeat/outputs/outil/select.go
  libbeat/outputs/output_reg.go
Labels: needs_team, v7.17.0

#30012 [automation] update elastic stack version for testing 8.1.0-aa69d697
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30034 [DOCS] Add redirect for GSuite module
  filebeat/docs/redirects.asciidoc
Labels: docs, v8.0.0, Team:Docs, backport-v8.0.0, v8.1.0

#30078 [automation] update elastic stack version for testing 6.8.24-8cc6db42
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30079 [automation] update elastic stack version for testing 7.16.4-42a1f428
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30065 probot[stale]: ignore issues with the tag flaky-test
  .github/stale.yml
Labels: automation, needs_team, backport-skip

#30057 libbeat/reader: Fix messge conversion to beat.Event
  libbeat/reader/message.go
  libbeat/reader/message_test.go
Labels: review, backport-v8.0.0, Team:Elastic-Agent-Data-Plane

#29861 Add fonts to support more different types of characters for multiple languages
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: backport, Team:Uptime, backport-v8.0.0, backport-v8.1.0

#29752 [libbeat] Add script processor to all beats
  CHANGELOG.next.asciidoc
  filebeat/cmd/root.go
  heartbeat/beater/heartbeat.go
  libbeat/cmd/instance/imports_common.go
  metricbeat/cmd/root.go
  winlogbeat/cmd/root.go
Labels: needs_docs, backport-skip, Team:Elastic-Agent-Data-Plane

#30083 Revert "Packaging: rename arm64 suffix to aarch64 in the tar.gz artifacts ONLY"
  CHANGELOG.next.asciidoc
  dev-tools/mage/pkgtypes.go
  x-pack/elastic-agent/magefile.go
  x-pack/elastic-agent/pkg/artifact/artifact.go
  x-pack/elastic-agent/pkg/artifact/download/http/elastic_test.go
Labels: Packaging, automation, needs_team, backport-skip

#30071 Remove SSL3 support from libbeat and its documentation.
  CHANGELOG.next.asciidoc
  libbeat/common/transport/tlscommon/versions_default.go
  libbeat/common/transport/tlscommon/versions_legacy.go
  libbeat/common/transport/tlscommon/versions_test.go
  libbeat/docs/shared-ssl-config.asciidoc
  packetbeat/docs/packetbeat-options.asciidoc
Labels: enhancement, cleanup, Team:Elastic-Agent-Data-Plane, v8.1.0, backport-v8.1.0, backport-v8.2.0
