Repository elastic/beats, pull requests merged in 2022-06, with the labels that each got.

#31692 [Oracle Module] Refactor module to properly use host parsers instead of doing its own parsing of hosts
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/oracle/connection.go
  x-pack/metricbeat/module/oracle/performance/metricset.go
  x-pack/metricbeat/module/oracle/tablespace/metricset.go
Labels: Team:Service-Integrations

#31791 [automation] update elastic stack version for testing 8.2.3-e78add13
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31793 [automation] update elastic stack version for testing 8.4.0-481759a3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31792 [automation] update elastic stack version for testing 7.17.5-7c990f83
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31776 add listPrefix in awsS3WriteCommitPrefix
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/input_benchmark_test.go
  x-pack/filebeat/input/awss3/s3.go
  x-pack/filebeat/input/awss3/state.go
  x-pack/filebeat/input/awss3/states.go
  x-pack/filebeat/input/awss3/states_test.go
Labels: backport-v8.2.0, backport-v7.17.0, Team:Cloud-Monitoring

#31803 [automation] update elastic stack version for testing 8.2.3-656a5d89
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31804 [automation] update elastic stack version for testing 7.17.5-a303ce60
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31805 [automation] update elastic stack version for testing 8.4.0-df27a645
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31797 Add v1.24 k8s version in testing list
  Jenkinsfile
  deploy/kubernetes/Jenkinsfile.yml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/module/kubernetes/_meta/docs.asciidoc
Labels: Team:Automation, Team:Cloudnative-Monitoring

#31814 [automation] update elastic stack version for testing 8.4.0-3525aaf7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31816 [automation] update elastic stack version for testing 8.2.3-f986a1ff
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31815 [automation] update elastic stack version for testing 7.17.5-f01fee6a
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31779 fix: use multiarch ARM Docker images on any architecture
  dev-tools/mage/crossbuild.go
Labels: ci, Team:Automation

#31818 libbeat: fix logging bug
  x-pack/libbeat/management/manager.go
Labels: Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v8.2.0

#31809 Change library used by libbeat queue metrics
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/queue.go
Labels: bug, Team:Elastic-Agent-Data-Plane, v8.4.0

#31830 [automation] update elastic stack version for testing 7.17.5-572a2baf
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31829 [automation] update elastic stack version for testing 8.2.3-def79f93
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31831 [automation] update elastic stack version for testing 8.4.0-42ce0eef
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31825 Update to go-sysinfo v1.8.0
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Security-External Integrations, Team:Elastic-Agent-Data-Plane, backport-v8.3.0

#31837 [libbeat] Fix flaky TestTimeString/empty_config
  libbeat/common/datetime.go
Labels: libbeat, flaky-test, Team:Elastic-Agent-Data-Plane

#31811 Remove github.com/golang/glog dependency
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, libbeat, Team:Security-External Integrations, Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v8.2.0

#31836 [libbeat] Modify npipe to get directly get the user SID
  libbeat/api/npipe/listener_windows.go
Labels: libbeat, Team:Security-External Integrations, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v8.2.0

#31835 [libbeat] Register uid/gid monitoring metrics asychronously
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
Labels: bug, libbeat, Team:Security-External Integrations, Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v8.2.0

#31802 [automation] update elastic stack version for testing 8.3.0-17c7e5c0
  metricbeat/docker-compose.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31851 [automation] update elastic stack version for testing 7.17.5-1c762894
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31824 [Filebeat] keep track of bytes read when max_bytes exceeded
  libbeat/reader/readfile/line.go
  libbeat/reader/readfile/line_test.go
Labels: Team:Elastic-Agent-Data-Plane

#31852 [automation] update elastic stack version for testing 8.4.0-b8fce3f8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31796 [Filebeat][Salesforce] Add Salesforce dashboard screenshots to documentation
  filebeat/docs/images/filebeat-salesforce-login-dashboard.png
  filebeat/docs/images/filebeat-salesforce-logout-dashboard.png
  filebeat/docs/modules/salesforce.asciidoc
  x-pack/filebeat/module/salesforce/_meta/docs.asciidoc
  x-pack/filebeat/module/salesforce/login-rest/manifest.yml
  x-pack/filebeat/module/salesforce/login-stream/manifest.yml
  x-pack/filebeat/module/salesforce/logout-rest/manifest.yml
  x-pack/filebeat/module/salesforce/logout-stream/manifest.yml
  x-pack/filebeat/module/salesforce/setupaudittrail-rest/manifest.yml
Labels: :Dashboards, Team:Docs, backport-v8.3.0, backport-v8.2.0

#28479 adding code to ingest indexing pressure stats
  metricbeat/docs/fields.asciidoc
  metricbeat/module/elasticsearch/fields.go
  metricbeat/module/elasticsearch/node_stats/_meta/fields.yml
  metricbeat/module/elasticsearch/node_stats/_meta/test/node_stats.623.json
  metricbeat/module/elasticsearch/node_stats/_meta/test/node_stats.715.json
  metricbeat/module/elasticsearch/node_stats/data.go
Labels: enhancement, Metricbeat, Team:Integrations, Team:Automation, low-hanging-fruit, backport-skip

#31860 [automation] update elastic stack version for testing 8.2.3-7def4c60
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31862 [automation] update elastic stack version for testing 8.3.0-f13a89b4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31864 docs: update docs versions 8.2.3
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#31853 Add HealthyHostCount and UnHealthyHostCount for application ELB
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/aws/elb/_meta/data_alb.json
  x-pack/metricbeat/module/aws/elb/_meta/fields.yml
  x-pack/metricbeat/module/aws/elb/manifest.yml
  x-pack/metricbeat/module/aws/fields.go
Labels: backport-v8.3.0, backport-v7.17.0, Team:Cloud-Monitoring

#31769 Update docs.asciidoc
  x-pack/metricbeat/module/istio/proxy/_meta/docs.asciidoc
Labels: Team:Docs

#31858 winlogbeat: disentangle test data from x-pack/winlogbeat
  winlogbeat/sys/wineventlog/testdata/4752.evtx
  winlogbeat/sys/wineventlog/util_test.go
Labels: bug, Winlogbeat, Team:Security-External Integrations, backport-skip, 8.4-candidate

#31883 [automation] update elastic stack version for testing 8.2.3-a46e98e9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31884 [automation] update elastic stack version for testing 8.3.0-3c22a7f7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31822 Remove `metricbeat/internal/metrics/{cpu,memory}` package and use it from `elastic-agent-system-metrics`
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/internal/metrics/cpu/doc.go
  metricbeat/internal/metrics/cpu/metrics.go
  metricbeat/internal/metrics/cpu/metrics_aix.go
  metricbeat/internal/metrics/cpu/metrics_darwin.go
  metricbeat/internal/metrics/cpu/metrics_freebsd.go
  metricbeat/internal/metrics/cpu/metrics_linux.go
  metricbeat/internal/metrics/cpu/metrics_linux_test.go
  metricbeat/internal/metrics/cpu/metrics_openbsd.go
  metricbeat/internal/metrics/cpu/metrics_procfs_common.go
  metricbeat/internal/metrics/cpu/metrics_test.go
  metricbeat/internal/metrics/cpu/metrics_windows.go
  metricbeat/internal/metrics/cpu/testdata/cpuinfo
  metricbeat/internal/metrics/cpu/testdata/cpuinfo-armv7
  metricbeat/internal/metrics/cpu/testdata/cpuinfo-armv7.expected.json
  metricbeat/internal/metrics/cpu/testdata/cpuinfo-quad-socket
  metricbeat/internal/metrics/cpu/testdata/cpuinfo-quad-socket.expected.json
  metricbeat/internal/metrics/cpu/testdata/cpuinfo.expected.json
  metricbeat/internal/metrics/memory/memory.go
  metricbeat/internal/metrics/memory/memory_aix.go
  metricbeat/internal/metrics/memory/memory_darwin.go
  metricbeat/internal/metrics/memory/memory_freebsd.go
  metricbeat/internal/metrics/memory/memory_helpers.go
  metricbeat/internal/metrics/memory/memory_linux.go
  metricbeat/internal/metrics/memory/memory_openbsd.go
  metricbeat/internal/metrics/memory/memory_test.go
  metricbeat/internal/metrics/memory/memory_windows.go
  metricbeat/internal/metrics/memory/oldkern/proc/meminfo
  metricbeat/module/linux/memory/data.go
  metricbeat/module/system/core/config.go
  metricbeat/module/system/core/core.go
  metricbeat/module/system/cpu/config.go
  metricbeat/module/system/cpu/cpu.go
  metricbeat/module/system/memory/memory.go
Labels: Team:Elastic-Agent-Data-Plane

#31881 dev-tools/mage: add BuildArgs.BuildMode
  dev-tools/mage/build.go
Labels: Team:Elastic-Agent-Data-Plane

#31880 Add float tags to fix broken topic structure
  metricbeat/module/kibana/settings/_meta/docs.asciidoc
  metricbeat/module/kibana/stats/_meta/docs.asciidoc
Labels: Team:Docs, backport-v8.0.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0

#31879 Update docs.asciidoc (#31769)
  x-pack/metricbeat/module/istio/proxy/_meta/docs.asciidoc
Labels: needs_team, backport-v8.0.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0

#31878 [DOCS] Use correct attribute for beat name in Kafka output docs
  libbeat/outputs/kafka/docs/kafka.asciidoc
Labels: docs, Team:Docs, backport-v8.3.0, backport-v8.2.0

#31882 [Filebeat] keep track of bytes read when max_bytes exceeded in last line
  libbeat/reader/readfile/line.go
  libbeat/reader/readfile/line_test.go
Labels: Team:Elastic-Agent-Data-Plane

#31887 docs: Prepare Changelog for 8.2.3
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#31877 [Heartbeat] Fix origin, Cleanup stdfields
  heartbeat/monitors/stdfields/stdfields.go
  heartbeat/monitors/wrappers/wrappers.go
  heartbeat/monitors/wrappers/wrappers_test.go
  x-pack/heartbeat/monitors/browser/project.go
  x-pack/heartbeat/monitors/browser/project_test.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
Labels: bug, Heartbeat, Team:Uptime

#31908 [automation] update elastic stack version for testing 8.3.0-158b3cba
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31912 [automation] update elastic stack version for testing 8.2.3-4b95b897
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31911 [automation] update elastic stack version for testing 8.3.0-db012561
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31903 rename queue.Batch.ACK -> queue.Batch.Done
  CHANGELOG-developer.next.asciidoc
  libbeat/publisher/pipeline/ttl_batch.go
  libbeat/publisher/queue/diskqueue/benchmark_test.go
  libbeat/publisher/queue/diskqueue/consumer.go
  libbeat/publisher/queue/memqueue/ackloop.go
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/memqueue/eventloop.go
  libbeat/publisher/queue/memqueue/internal_api.go
  libbeat/publisher/queue/memqueue/queue_test.go
  libbeat/publisher/queue/queue.go
  libbeat/publisher/queue/queuetest/producer_cancel.go
  libbeat/publisher/queue/queuetest/queuetest.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#31922 [automation] update elastic stack version for testing 8.3.0-e4e76686
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31921 [automation] update elastic stack version for testing 8.2.3-b55b20b5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31923 [automation] update elastic stack version for testing 8.4.0-7e67f5d9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31868 [Metricbeat] Discard partial Logstash pipeline documents
  metricbeat/module/logstash/node_stats/_meta/test/node_stats.710.json
  metricbeat/module/logstash/node_stats/_meta/test/node_stats.840.json
  metricbeat/module/logstash/node_stats/_meta/test/node_stats.840_partial.json
  metricbeat/module/logstash/node_stats/data.go
  metricbeat/module/logstash/node_stats/data_test.go
  metricbeat/module/logstash/node_stats/node_stats.go
Labels: bug, Feature: Stack Monitoring, Team:Infra Monitoring UI, v8.4.0

#31865 [Release] Update version to 8.2.4
  libbeat/version/version.go
Labels: release, Team:Automation

#31866 [Release] Update test environments for 8.2.4
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#31931 Osquerybeat: Exit osquerybeat process if orphaned
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/beater/watcher.go
  x-pack/osquerybeat/internal/osqd/osqueryd_unix.go
Labels: bug, Team:Asset Mgt, v8.3.0, backport-v8.3.0

#31939 [automation] update elastic stack version for testing 8.4.0-40cff009
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31462 [Oracle Module] New sysmetric metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/oracle.asciidoc
  metricbeat/docs/modules/oracle/sysmetric.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/oracle/_meta/config.yml
  x-pack/metricbeat/module/oracle/_meta/docs.asciidoc
  x-pack/metricbeat/module/oracle/_meta/kibana/7/dashboard/a3f4d080-c7d3-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/00b53be0-c87c-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/09929750-c87a-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/21744290-c87c-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/2ee49e30-c87b-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/3af08cd0-c843-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/400c71a0-c87c-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/4ae42710-c9e6-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/53dee3a0-c9e6-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/5e35d950-c87c-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/61d15a20-c87d-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/81c1f9a0-c843-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/84ef9e80-c9e6-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/8fb638f0-c90b-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/93361970-c922-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/a65d8eb0-c879-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/c2178960-c83f-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/c777ba10-c83f-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/d5e99370-c87b-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/_meta/kibana/7/visualization/ffd22450-c87a-11ec-891a-5f50c7522a3a.json
  x-pack/metricbeat/module/oracle/connection.go
  x-pack/metricbeat/module/oracle/fields.go
  x-pack/metricbeat/module/oracle/sysmetric/_meta/data.json
  x-pack/metricbeat/module/oracle/sysmetric/_meta/docs.asciidoc
  x-pack/metricbeat/module/oracle/sysmetric/_meta/fields.yml
  x-pack/metricbeat/module/oracle/sysmetric/collector.go
  x-pack/metricbeat/module/oracle/sysmetric/data.go
  x-pack/metricbeat/module/oracle/sysmetric/data_test.go
  x-pack/metricbeat/module/oracle/sysmetric/metricset.go
  x-pack/metricbeat/module/oracle/sysmetric/metricset_test.go
  x-pack/metricbeat/module/oracle/sysmetric/sysmetric_metric.go
  x-pack/metricbeat/module/oracle/sysmetric/sysmetric_metric_test.go
  x-pack/metricbeat/modules.d/oracle.yml.disabled
Labels: Team:Service-Integrations

#31748 Remote debug metricbeat running on docker/k8s from your laptop
  metricbeat/Dockerfile.debug
  metricbeat/module/kubernetes/_meta/remote-debugger/README.md
Labels: enhancement, Team:Cloudnative-Monitoring

#31918 Osquerybeat: Implement namespace info as a part of proc osquery_extension
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/namespace.go
  x-pack/osquerybeat/ext/osquery-extension/pkg/proc/namespace_test.go
Labels: enhancement, Team:Cloud-Security-Posture

#31934 Update shared-monitor-config.asciidoc monitoring.cluster_uuid missing…
  libbeat/docs/monitoring/shared-monitor-config.asciidoc
Labels: Team:Docs, backport-v8.0.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0

#31943 Skip metricbeat/module/mongodb/replstatus.TestFetch
  metricbeat/module/mongodb/replstatus/replstatus_integration_test.go
Labels: flaky-test, Team:Elastic-Agent-Data-Plane, Team:Cloud-Monitoring

#31952 [automation] update elastic stack version for testing 8.3.0-fe62331f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31953 [automation] update elastic stack version for testing 8.4.0-5e6770b1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31942 Add input identification support to the shipper output
  libbeat/outputs/shipper/api/shipper.pb.go
  libbeat/outputs/shipper/api/shipper_grpc.pb.go
  libbeat/outputs/shipper/shipper.go
  libbeat/outputs/shipper/shipper_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, v8.4.0

#31956 [automation] update elastic stack version for testing 8.2.4-4cc4fbfd
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31935 improve disk queue performance by coalescing writes
  CHANGELOG.next.asciidoc
  libbeat/publisher/queue/diskqueue/writer_loop.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#31680 x-pack/filebeat/module/rabbitmq: add handling of authentication data
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/rabbitmq/log/ingest/pipeline.yml
  x-pack/filebeat/module/rabbitmq/log/test/test.log
  x-pack/filebeat/module/rabbitmq/log/test/test.log-expected.json
Labels: enhancement, Team:Integrations, 8.4-candidate, Team:Service-Integrations

#31965 [automation] update elastic stack version for testing 8.2.4-01ccaf06
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31964 [automation] update elastic stack version for testing 8.4.0-da5a1c6d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31954 ci: create GitHub issue if build failure
  Jenkinsfile
Labels: Team:Automation, backport-v8.3.0, backport-v7.17.0

#31955 Fix flags for dev build
  CHANGELOG-developer.next.asciidoc
  dev-tools/mage/build.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#31368 [Oracle Module] Handle special characters for Oracle connection string properly
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/docs/modules/oracle.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/oracle/_meta/config.yml
  x-pack/metricbeat/module/oracle/_meta/docs.asciidoc
  x-pack/metricbeat/module/oracle/connection.go
  x-pack/metricbeat/module/oracle/testing.go
  x-pack/metricbeat/modules.d/oracle.yml.disabled
Labels: Team:Service-Integrations

#31983 Remove broken link from Oracle module docs.
  metricbeat/docs/modules/oracle.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/oracle/_meta/config.yml
  x-pack/metricbeat/modules.d/oracle.yml.disabled
Labels: Team:Docs, Team:Elastic-Agent-Data-Plane

#31992 [automation] update elastic stack version for testing 8.2.4-698e06ec
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31990 [automation] update elastic stack version for testing 8.4.0-b13123ee
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31886 x-pack/filebeat/input/httpjson: Add hexDecode function
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/value_tpl.go
  x-pack/filebeat/input/httpjson/value_tpl_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations

#31985 [Metricbeat] Stop continual error with multiple Logstash pipelines
  metricbeat/module/logstash/node/data.go
Labels: Feature: Stack Monitoring, Team:Infra Monitoring UI, v8.4.0

#31959 Fix root cgroups behavior
  libbeat/metric/system/cgroup/reader.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#31997 [Heartbeat] Fix missing check group field for browser monitors
  heartbeat/eventext/eventext.go
  heartbeat/monitors/stdfields/stdfields.go
  heartbeat/monitors/wrappers/wrappers.go
  heartbeat/monitors/wrappers/wrappers_test.go
  x-pack/heartbeat/monitors/browser/project.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
Labels: bug, Heartbeat, Team:Uptime, v8.3.0

#32002 [automation] update elastic stack version for testing 8.2.4-b657c8f5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31972 Save file size to registry of ignored files
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/input/filestream/copytruncate_prospector_test.go
  filebeat/input/filestream/prospector.go
  filebeat/input/filestream/prospector_test.go
Labels: Team:Elastic-Agent-Data-Plane

#32010 Expand fields in `decode_json_fields` if target is set
  CHANGELOG.next.asciidoc
  libbeat/common/jsontransform/expand.go
  libbeat/processors/actions/decode_json_fields.go
  libbeat/processors/actions/decode_json_fields_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v7.17.0

#32017 [automation] update elastic stack version for testing 8.2.4-589bdf37
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32016 [automation] update elastic stack version for testing 8.3.0-e0057e17
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31961 Add encryption to diskqueue
  libbeat/publisher/queue/diskqueue/benchmark_test.go
  libbeat/publisher/queue/diskqueue/config.go
  libbeat/publisher/queue/diskqueue/core_loop.go
  libbeat/publisher/queue/diskqueue/core_loop_test.go
  libbeat/publisher/queue/diskqueue/docs/Makefile
  libbeat/publisher/queue/diskqueue/docs/frameV0.pic
  libbeat/publisher/queue/diskqueue/docs/frameV0.svg
  libbeat/publisher/queue/diskqueue/docs/frameV1.pic
  libbeat/publisher/queue/diskqueue/docs/frameV1.svg
  libbeat/publisher/queue/diskqueue/docs/frameV2.pic
  libbeat/publisher/queue/diskqueue/docs/frameV2.svg
  libbeat/publisher/queue/diskqueue/docs/on-disk-structures.md
  libbeat/publisher/queue/diskqueue/docs/schemaV0.pic
  libbeat/publisher/queue/diskqueue/docs/schemaV0.svg
  libbeat/publisher/queue/diskqueue/docs/schemaV1.pic
  libbeat/publisher/queue/diskqueue/docs/schemaV1.svg
  libbeat/publisher/queue/diskqueue/docs/schemaV2.pic
  libbeat/publisher/queue/diskqueue/docs/schemaV2.svg
  libbeat/publisher/queue/diskqueue/encryption.go
  libbeat/publisher/queue/diskqueue/encryption_test.go
  libbeat/publisher/queue/diskqueue/reader_loop.go
  libbeat/publisher/queue/diskqueue/segments.go
  libbeat/publisher/queue/diskqueue/segments_test.go
  libbeat/publisher/queue/diskqueue/serialize.go
  libbeat/publisher/queue/diskqueue/writer_loop.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#31927 Extend multiline documentation with filestream syntax
  filebeat/docs/multiline.asciidoc
Labels: docs, Team:Docs, backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#31978 Remove outdated setting in Kafka output documentation
  libbeat/outputs/kafka/docs/kafka.asciidoc
Labels: docs, Team:Elastic-Agent-Data-Plane

#31969 fix some typos
  filebeat/beater/channels.go
  filebeat/input/journald/pkg/journalread/reader.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#31986 [7.17](backport elastic/elastic-agent#570) Add filemod times to contents of diagnostics collect command
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/diagnostics.go
Labels: backport, Team:Elastic-Agent-Control-Plane

#32046 Remove invalid entry
  CHANGELOG.asciidoc
Labels: backport-skip, Team:Service-Integrations

#32042 Pin the protobuf version in system tests.
  auditbeat/tests/system/requirements.txt
  dev-tools/requirements.txt
  heartbeat/tests/system/requirements.txt
  libbeat/tests/system/requirements.txt
  metricbeat/module/kubernetes/_meta/terraform/eks/requirements.txt
  metricbeat/tests/system/requirements.txt
  packetbeat/tests/system/gen/memcache/requirements.txt
  x-pack/functionbeat/tests/system/requirements.txt
Labels: ci, Team:Automation, Team:Elastic-Agent-Data-Plane

#32025 x-filebeat/modules/cisco: fix syslog priority handling
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/test/not-ip.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/sample.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/firepower-management.log
  x-pack/filebeat/module/cisco/ftd/test/firepower-management.log-expected.json
  x-pack/filebeat/module/cisco/ftd/test/not-ip.log-expected.json
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: bug, Team:Security-External Integrations, backport-v8.3.0, backport-v7.17.0, 8.4-candidate

#32067 [automation] update elastic stack version for testing 7.17.5-8d9f50d0
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32065 [automation] update elastic stack version for testing 8.3.0-47d97929
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32068 [automation] update elastic stack version for testing 8.4.0-2e32a640
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32032 Port `test_type_in_message` to filestream Golang tests
  libbeat/reader/parser/parser_test.go
Labels: Team:Elastic-Agent-Data-Plane

#32045 Port `test_rotating_close_inactive_low_write_rate` to Golang
  filebeat/input/filestream/environment_test.go
  filebeat/input/filestream/input_integration_test.go
Labels: Team:Elastic-Agent-Data-Plane

#30569 x-pack/winlogbeat: move event.ingested setting to routing
  x-pack/winlogbeat/module/powershell/ingest/powershell.yml
  x-pack/winlogbeat/module/powershell/ingest/powershell_operational.yml
  x-pack/winlogbeat/module/routing/ingest/routing.yml
  x-pack/winlogbeat/module/security/ingest/security.yml
  x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml
Labels: enhancement, Team:Security-External Integrations, backport-skip, 8.4-candidate

#32013 Fix backoff strategy for the shipper output
  libbeat/outputs/shipper/README.md
  libbeat/outputs/shipper/config.go
  libbeat/outputs/shipper/shipper.go
  libbeat/outputs/shipper/shipper_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, v8.4.0

#32055 docs: Prepare Changelog for 7.17.5
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#32079 Revert "ci: e2e-testing should fail the build (#31135)"
  .ci/packaging.groovy
Labels: ci, Team:Automation, Team:Elastic-Agent-Data-Plane

#32064 [Heartbeat] Always use synthetics data streams for browser
  CHANGELOG.next.asciidoc
  heartbeat/docs/monitors/monitor-common-options.asciidoc
  heartbeat/monitors/factory.go
  heartbeat/monitors/factory_test.go
Labels: enhancement, Heartbeat, Team:Uptime

#31914 packetbeat/route: new package for obtaining default route information
  NOTICE.txt
  go.sum
  packetbeat/route/doc.go
  packetbeat/route/route_bsd.go
  packetbeat/route/route_bsd_test.go
  packetbeat/route/route_linux.go
  packetbeat/route/route_linux_test.go
  packetbeat/route/route_other.go
  packetbeat/route/route_test.go
  packetbeat/route/route_windows.go
  packetbeat/route/route_windows_test.go
Labels: enhancement, Packetbeat, Team:Security-External Integrations, backport-skip, 8.4-candidate

#32083 [DOCS] Removed reference to the Stack GS
  libbeat/docs/tab-widgets/spinup-stack.asciidoc
Labels: docs, Team:Docs, v8.3.0, backport-v8.3.0, v8.4.0

#32039 Port `test_rotating_close_inactive_larger_write_rate` to Golang
  filebeat/input/filestream/input_integration_test.go
Labels: Team:Elastic-Agent-Data-Plane

#32087 [automation] update elastic stack version for testing 7.17.5-781a81f2
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32085 [automation] update elastic stack version for testing 8.3.0-3b390c7b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32086 [automation] update elastic stack version for testing 8.4.0-722a7d79
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#31898 Fix deduplication in Google workspace module
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/google_workspace/admin/test/admin-application-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-application-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-calendar-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-calendar-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-chat-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-chat-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-chromeos-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-chromeos-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-contacts-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-contacts-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-delegatedadmin-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-delegatedadmin-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-docs-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-docs-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-domain-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-domain-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-gmail-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-gmail-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-groups-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-groups-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-licenses-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-licenses-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-mobile-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-mobile-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-org-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-org-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-security-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-security-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-sites-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-sites-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/admin/test/admin-user-test.json.log
  x-pack/filebeat/module/google_workspace/admin/test/admin-user-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/config/common.js
  x-pack/filebeat/module/google_workspace/drive/test/drive-test.json.log
  x-pack/filebeat/module/google_workspace/drive/test/drive-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/groups/test/groups-test.json.log
  x-pack/filebeat/module/google_workspace/groups/test/groups-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/login/test/login-test.json.log
  x-pack/filebeat/module/google_workspace/login/test/login-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/saml/test/saml-test.json.log
  x-pack/filebeat/module/google_workspace/saml/test/saml-test.json.log-expected.json
  x-pack/filebeat/module/google_workspace/user_accounts/test/user_accounts-test.json.log
  x-pack/filebeat/module/google_workspace/user_accounts/test/user_accounts-test.json.log-expected.json
Labels: bug, module, Filebeat, Team:Security-External Integrations, backport-v8.3.0

#32092 mergify: remove backport automation for non active branches
  .mergify.yml
Labels: automation, Team:Automation, backport-skip

#31936 [Heartbeat] Include cmd/status errs , add ECS Errs
  CHANGELOG.next.asciidoc
  heartbeat/ecserr/ecserr.go
  heartbeat/ecserr/ecserr_test.go
  heartbeat/monitors/wrappers/wrappers.go
  heartbeat/monitors/wrappers/wrappers_test.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
  x-pack/heartbeat/monitors/browser/synthexec/synthtypes_test.go
  x-pack/heartbeat/monitors/browser/synthexec/testcmd/main.go
Labels: bug, Heartbeat, Team:Uptime

#32097 [Heartbeat] 'event.type: foo' should be 'event: {type: foo}' for browser
  CHANGELOG.next.asciidoc
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
Labels: bug, Heartbeat, Team:Uptime, backport-v8.3.0

#31987 Add Beats breaking changes for 8.3
  libbeat/docs/release-notes/breaking/breaking-8.3.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
Labels: Team:Elastic-Agent-Data-Plane, v8.3.0, backport-v8.3.0

#32105 [http_endpoint] fix incorrect TLSConfig initialization (#32104)
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/http_endpoint/input.go
Labels: bug, Filebeat, Team:Security-External Integrations, backport-v8.3.0, backport-v7.17.0, 8.4-candidate

#32110 [automation] update elastic stack version for testing 8.3.0-fdf97a2e
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32108 [automation] update elastic stack version for testing 8.4.0-210dd487
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32096 Add script to extract metrics from unstructured logs
  script/metrics_from_log_file.sh
  script/sample_logs/log_with_metrics.log
Labels: Team:Elastic-Agent-Data-Plane

#32094 Add new `parser` called `include_message` to filter messages
  CHANGELOG.next.asciidoc
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/_meta/config/filebeat.inputs.yml.tmpl
  filebeat/docs/inputs/input-filestream-reader-options.asciidoc
  filebeat/filebeat.reference.yml
  filebeat/filebeat.yml
  libbeat/reader/filter/filter.go
  libbeat/reader/filter/filter_test.go
  libbeat/reader/parser/parser.go
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/filebeat.yml
Labels: Team:Elastic-Agent-Data-Plane

#31798 [libbeat] Improve syslog parser/processor error handling
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  libbeat/processors/syslog/docs/syslog.asciidoc
  libbeat/processors/syslog/syslog.go
  libbeat/processors/syslog/syslog_test.go
  libbeat/reader/syslog/docs/syslog.asciidoc
  libbeat/reader/syslog/message.go
  libbeat/reader/syslog/message_test.go
  libbeat/reader/syslog/parser/common.rl
  libbeat/reader/syslog/parser/parser_rfc3164.rl
  libbeat/reader/syslog/parser/parser_rfc5424.rl
  libbeat/reader/syslog/parser/rfc3164.rl
  libbeat/reader/syslog/parser/rfc5424.rl
  libbeat/reader/syslog/rfc3164_gen.go
  libbeat/reader/syslog/rfc3164_test.go
  libbeat/reader/syslog/rfc5424_gen.go
  libbeat/reader/syslog/rfc5424_test.go
  libbeat/reader/syslog/syslog.go
  libbeat/reader/syslog/syslog_test.go
  libbeat/reader/syslog/util.go
  libbeat/reader/syslog/util_test.go
Labels: enhancement, libbeat, :Processors, Team:Security-External Integrations, backport-v8.3.0, backport-v8.2.0, 8.4-candidate

#32024 Add compression to disk queue
  NOTICE.txt
  go.mod
  go.sum
  libbeat/publisher/queue/diskqueue/benchmark_test.go
  libbeat/publisher/queue/diskqueue/compression.go
  libbeat/publisher/queue/diskqueue/compression_test.go
  libbeat/publisher/queue/diskqueue/config.go
  libbeat/publisher/queue/diskqueue/docs/on-disk-structures.md
  libbeat/publisher/queue/diskqueue/enc_compress_test.go
  libbeat/publisher/queue/diskqueue/segments.go
  libbeat/publisher/queue/diskqueue/segments_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#32121 [DOCS] Removed reference to the Stack GS (#32083)
  libbeat/docs/tab-widgets/spinup-stack.asciidoc
Labels: docs, Team:Docs, v8.4.0

#32123 [automation] update elastic stack version for testing 8.2.4-9b981623
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32124 [automation] update elastic stack version for testing 8.4.0-a6aa9f3b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32131 docs: Prepare Changelog for 8.3.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#32136 Forward port 8.2.3 and 8.3 change logs
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Elastic-Agent-Data-Plane

#32020 [Release] Update test environments for 7.17.6
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#32141 auditbeat: update version of go-libaudit
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, Auditbeat, Team:Security-External Integrations, backport-v8.3.0, 8.4-candidate

#32146 [automation] update elastic stack version for testing 7.17.5-b5794350
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32145 [automation] update elastic stack version for testing 8.2.4-62f5ece5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32144 [automation] update elastic stack version for testing 8.3.0-729c5564
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32143 [automation] update elastic stack version for testing 8.4.0-4ec2d3b3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32061 x-pack/filebeat/input/httpjson: use timer instead of ticker for singleshot
  x-pack/filebeat/input/httpjson/rate_limiter.go
Labels: enhancement, Team:Security-External Integrations, backport-skip, 8.4-candidate

#32132 Use external autodiscover library for hints helpers
  NOTICE.txt
  filebeat/autodiscover/builder/hints/logs.go
  go.mod
  go.sum
  heartbeat/autodiscover/builder/hints/monitors.go
  libbeat/autodiscover/builder/helper.go
  libbeat/autodiscover/builder/helper_test.go
  libbeat/autodiscover/providers/docker/docker.go
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
  libbeat/autodiscover/providers/kubernetes/node.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/service.go
  metricbeat/autodiscover/builder/hints/metrics.go
  metricbeat/module/docker/container/data.go
  metricbeat/module/kubernetes/container/data.go
  metricbeat/module/kubernetes/event/event.go
  metricbeat/module/kubernetes/node/data.go
  metricbeat/module/kubernetes/pod/data.go
  metricbeat/module/kubernetes/state_container/state_container.go
  metricbeat/module/kubernetes/system/data.go
  metricbeat/module/kubernetes/util/kubernetes.go
  metricbeat/module/kubernetes/util/kubernetes_test.go
  metricbeat/module/kubernetes/volume/data.go
  x-pack/libbeat/autodiscover/providers/nomad/nomad.go
Labels: Team:Cloudnative-Monitoring

#32167 [automation] update elastic stack version for testing 8.2.4-e7c42e26
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32166 [automation] update elastic stack version for testing 8.3.1-b95de5e6
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32165 [automation] update elastic stack version for testing 8.4.0-86cc80f3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#32156 docs: Prepare Changelog for 8.3.1
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#31827 [automation] Update go release version 1.17.11
  .go-version
  .golangci.yml
  auditbeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
Labels: automation, needs_team, dependency, backport-skip

#32154 [Release] Update version to 8.3.2
  libbeat/version/version.go
Labels: release, Team:Automation

#31950 packetbeat: wire default interface selection into config
  CHANGELOG.next.asciidoc
  packetbeat/_meta/config/beat.reference.yml.tmpl
  packetbeat/_meta/config/beat.yml.tmpl
  packetbeat/config/agent.go
  packetbeat/docs/packetbeat-options.asciidoc
  packetbeat/packetbeat.reference.yml
  packetbeat/packetbeat.yml
  packetbeat/scripts/mage/config.go
  packetbeat/sniffer/device.go
  packetbeat/tests/system/config/packetbeat.yml.j2
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/packetbeat/packetbeat.yml
Labels: enhancement, Packetbeat, Team:Security-External Integrations, 8.4-candidate
