Repository elastic/beats, pull requests merged in 2022-02, with the labels that each got.

#30103 Filebeat pytest improvements
  CHANGELOG-developer.next.asciidoc
  filebeat/tests/system/test_modules.py
  libbeat/tests/system/beat/beat.py
Labels: Filebeat, Team:Integrations, backport-v8.0.0

#30118 [8.0] Added info about ability to overwrite (#29944)
  libbeat/processors/actions/docs/add_fields.asciidoc
Labels: docs, backport, v8.0.0, Team:Docs

#30117 [7.17] Added info about ability to overwrite (#29944)
  libbeat/processors/actions/docs/add_fields.asciidoc
Labels: docs, backport, Team:Docs, v7.17.0

#30116 [master] Added info about ability to overwrite (#29944)
  libbeat/processors/actions/docs/add_fields.asciidoc
Labels: docs, backport, Team:Docs, v8.1.0

#29751 #29747: Fix Add Network Direction processor
  CHANGELOG.next.asciidoc
  libbeat/processors/actions/add_network_direction.go
Labels: Team:Security-External Integrations, backport-skip

#30013 [Heartbeat]: catch all error handler for browser jobs
  heartbeat/monitors/wrappers/wrappers.go
  heartbeat/monitors/wrappers/wrappers_test.go
  x-pack/heartbeat/monitors/browser/suite.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer.go
  x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
Labels: bug, Team:Uptime, backport-v8.0.0, v8.1.0, backport-v7.17.0

#30088 Add integration tests to containerd module
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/containerd.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/containerd/_meta/config.yml
  x-pack/metricbeat/module/containerd/blkio/_meta/data.json
  x-pack/metricbeat/module/containerd/blkio/_meta/fields.yml
  x-pack/metricbeat/module/containerd/blkio/_meta/testdata/config.yml
  x-pack/metricbeat/module/containerd/blkio/_meta/testdata/docs.plain
  x-pack/metricbeat/module/containerd/blkio/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/containerd/blkio/blkio.go
  x-pack/metricbeat/module/containerd/blkio/blkio_test.go
  x-pack/metricbeat/module/containerd/cpu/_meta/data.json
  x-pack/metricbeat/module/containerd/cpu/_meta/testdata/docs.plain
  x-pack/metricbeat/module/containerd/cpu/cpu.go
  x-pack/metricbeat/module/containerd/fields.go
  x-pack/metricbeat/module/containerd/memory/_meta/data.json
  x-pack/metricbeat/module/containerd/memory/_meta/testdata/config.yml
  x-pack/metricbeat/module/containerd/memory/_meta/testdata/docs.plain
  x-pack/metricbeat/module/containerd/memory/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/containerd/memory/memory.go
  x-pack/metricbeat/module/containerd/memory/memory_test.go
  x-pack/metricbeat/modules.d/containerd.yml.disabled
Labels: enhancement, Team:Integrations, backport-v8.1.0

#30128 [automation] update elastic stack version for testing 8.0.0-09bea260
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29031 [elastic-agent] initial instrumentation
  NOTICE.txt
  go.mod
  go.sum
  x-pack/elastic-agent/pkg/agent/application/application.go
  x-pack/elastic-agent/pkg/agent/application/fleet_server_bootstrap.go
  x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway.go
  x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  x-pack/elastic-agent/pkg/agent/application/gateway/fleetserver/fleet_gateway_local.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/agent/application/once.go
  x-pack/elastic-agent/pkg/agent/application/periodic.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change_test.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_unenroll.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/dispatcher/dispatcher.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/dispatcher/dispatcher_test.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/controller.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/emitter.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/pipeline.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/router/router.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/router/router_test.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/stream/operator_stream.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/cmd/inspect.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/control/control_test.go
  x-pack/elastic-agent/pkg/agent/control/server/server.go
  x-pack/elastic-agent/pkg/agent/operation/common_test.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring_test.go
  x-pack/elastic-agent/pkg/agent/operation/operator.go
  x-pack/elastic-agent/pkg/agent/storage/store/state_store.go
  x-pack/elastic-agent/pkg/artifact/download/composed/downloader.go
  x-pack/elastic-agent/pkg/artifact/download/fs/downloader.go
  x-pack/elastic-agent/pkg/basecmd/version/cmd_test.go
  x-pack/elastic-agent/pkg/core/monitoring/config/config.go
  x-pack/elastic-agent/pkg/core/monitoring/config/config_test.go
  x-pack/elastic-agent/pkg/core/monitoring/server/server.go
  x-pack/elastic-agent/pkg/core/server/config.go
  x-pack/elastic-agent/pkg/core/server/config_test.go
  x-pack/elastic-agent/pkg/core/server/server.go
  x-pack/elastic-agent/pkg/core/server/server_test.go
  x-pack/elastic-agent/pkg/fleetapi/ack_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/acker/fleet/fleet_acker.go
  x-pack/elastic-agent/pkg/fleetapi/acker/lazy/lazy_acker.go
  x-pack/elastic-agent/pkg/fleetapi/client/client.go
  x-pack/elastic-agent/pkg/remote/client.go
Labels: enhancement, Team:Elastic-Agent, backport-v8.0.0

#30030 New version of threatintel/recordedfuture dataset
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/modules/threatintel.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/threatintel/_meta/config.yml
  x-pack/filebeat/module/threatintel/_meta/docs.asciidoc
  x-pack/filebeat/module/threatintel/fields.go
  x-pack/filebeat/module/threatintel/recordedfuture/_meta/fields.yml
  x-pack/filebeat/module/threatintel/recordedfuture/config/config.yml
  x-pack/filebeat/module/threatintel/recordedfuture/ingest/decode_csv.yml
  x-pack/filebeat/module/threatintel/recordedfuture/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/recordedfuture/manifest.yml
  x-pack/filebeat/module/threatintel/recordedfuture/test/domain.ndjson.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/domain.ndjson.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/hash.ndjson.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/hash.ndjson.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/ip.ndjson.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/ip.ndjson.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_assorted.json.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_assorted.json.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_domain_default.csv.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_domain_default.csv.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_hash_default.csv.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_hash_default.csv.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_ip_default.csv.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_ip_default.csv.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_url_default.csv.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_url_default.csv.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/url.ndjson.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/url.ndjson.log-expected.json
  x-pack/filebeat/modules.d/threatintel.yml.disabled
Labels: enhancement, review, Filebeat, Team:Security-External Integrations, 8.1-candidate, backport-v8.1.0

#30111 docs: Prepare Changelog for 7.17.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#30112 8.0.0-rc2 Changelog
  CHANGELOG.asciidoc
  libbeat/docs/release.asciidoc
Labels: release, Team:Docs

#30101 [docs] fix minor typo
  heartbeat/docs/monitors/monitor-browser.asciidoc
Labels: docs, Team:Docs, backport-v7.16.0

#30026 Copy `@timestamp` to make sure we always have a timestamp in the event
  filebeat/module/apache/access/ingest/pipeline.yml
  filebeat/module/iis/access/ingest/pipeline.yml
  filebeat/module/iis/error/ingest/pipeline.yml
  filebeat/module/kafka/log/ingest/pipeline.yml
  filebeat/module/kibana/audit/ingest/pipeline.yml
  filebeat/module/kibana/log/ingest/pipeline.yml
  filebeat/module/logstash/log/ingest/pipeline.yml
  filebeat/module/logstash/slowlog/ingest/pipeline.yml
  filebeat/module/mongodb/log/ingest/pipeline.yml
  filebeat/module/mysql/error/ingest/pipeline.yml
  filebeat/module/nats/log/ingest/pipeline.yml
  filebeat/module/nginx/access/ingest/pipeline.yml
  filebeat/module/nginx/error/ingest/pipeline.yml
  filebeat/module/osquery/result/ingest/pipeline.json
  filebeat/module/redis/log/ingest/pipeline.yml
  filebeat/module/santa/log/test/santa.log-expected.json
  filebeat/module/traefik/access/ingest/pipeline.yml
  x-pack/filebeat/module/zookeeper/audit/ingest/pipeline.yml
  x-pack/filebeat/module/zookeeper/log/ingest/pipeline.yml
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane

#30133 Forward port 7.17.0 changelog to 8.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: release, Team:Docs

#30014 Updated dev guide instructions to work with master
  docs/devguide/contributing.asciidoc
  docs/devguide/index.asciidoc
  docs/devguide/modules-dev-guide.asciidoc
  docs/devguide/new_protocol.asciidoc
  docs/devguide/testing.asciidoc
Labels: docs, Team:Integrations, release-note:dev_docs, Team:Docs, backport-v8.0.0

#30137 mssql-doc updated with the list of tables which should have permission
  metricbeat/docs/modules/mssql.asciidoc
  x-pack/metricbeat/module/mssql/_meta/docs.asciidoc
Labels: docs, Team:Integrations, backport-skip

#29477 [Release] Bump version to 7.17.1
  libbeat/version/version.go
Labels: release, Stalled, Team:Automation, backport-skip

#30136 Forward port 7.17.0 and 8.0.0-rc2 changelogs to master
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: release, Team:Docs, backport-skip

#30087 Load inputs from external configuration files in Elastic Agent in standalone mode
  x-pack/elastic-agent/_meta/config/common.reference.p2.yml.tmpl
  x-pack/elastic-agent/elastic-agent.reference.yml
  x-pack/elastic-agent/pkg/agent/application/fleet_server_bootstrap.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/once.go
  x-pack/elastic-agent/pkg/agent/application/periodic.go
  x-pack/elastic-agent/pkg/agent/configuration/settings.go
  x-pack/elastic-agent/pkg/config/loader.go
  x-pack/elastic-agent/pkg/config/loader_test.go
  x-pack/elastic-agent/pkg/config/testdata/inputs/invalid-inputs.yml
  x-pack/elastic-agent/pkg/config/testdata/inputs/log-inputs.yml
  x-pack/elastic-agent/pkg/config/testdata/inputs/metrics-inputs.yml
  x-pack/elastic-agent/pkg/config/testdata/standalone-with-inputs.yml
  x-pack/elastic-agent/pkg/config/testdata/standalone1.yml
  x-pack/elastic-agent/pkg/config/testdata/standalone2.yml
Labels: needs tests, needs_docs, backport-skip, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane

#30144 Add missing changelog entry for #30087
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
Labels: needs_team, backport-skip

#30021 Add more details to changelog entry about changes in Beats and Agent logging
  CHANGELOG.next.asciidoc
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane

#30147 [automation] update elastic stack version for testing 7.17.1-7ef8bcb5
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30149 Use absolute path in external config glob when looking for external configuration files in Elastic Agent
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
Labels: needs_team, backport-skip

#30159 backport: Add 8.1 branch
  .mergify.yml
Labels: release, Team:Automation, impact:critical, backport-skip

#30097 Remove macOS preference panels and code related to DMG
  auditbeat/scripts/mage/package.go
  dev-tools/mage/dmgbuilder.go
  dev-tools/mage/kibana.go
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgtypes.go
  dev-tools/packaging/packages.yml
  dev-tools/packaging/preference-pane/.gitignore
  dev-tools/packaging/preference-pane/beats-preference-pane.xcodeproj/project.pbxproj
  dev-tools/packaging/preference-pane/beats-preference-pane.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  dev-tools/packaging/preference-pane/beats-preference-pane.xcodeproj/xcshareddata/IDETemplateMacros.plist
  dev-tools/packaging/preference-pane/beats-preference-pane.xcodeproj/xcuserdata/adrian.xcuserdatad/xcschemes/xcschememanagement.plist
  dev-tools/packaging/preference-pane/beats-preference-pane/Authorization.h
  dev-tools/packaging/preference-pane/beats-preference-pane/Base.lproj/BeatView.xib
  dev-tools/packaging/preference-pane/beats-preference-pane/Base.lproj/BeatsPrefPane.xib
  dev-tools/packaging/preference-pane/beats-preference-pane/Base.lproj/EditorWindow.xib
  dev-tools/packaging/preference-pane/beats-preference-pane/Base.lproj/pane.xib
  dev-tools/packaging/preference-pane/beats-preference-pane/BeatManager.m
  dev-tools/packaging/preference-pane/beats-preference-pane/BeatViewController.h
  dev-tools/packaging/preference-pane/beats-preference-pane/BeatViewController.m
  dev-tools/packaging/preference-pane/beats-preference-pane/Beats.icns
  dev-tools/packaging/preference-pane/beats-preference-pane/BeatsPrefPane.h
  dev-tools/packaging/preference-pane/beats-preference-pane/BeatsPrefPane.m
  dev-tools/packaging/preference-pane/beats-preference-pane/EditorWindow.h
  dev-tools/packaging/preference-pane/beats-preference-pane/EditorWindow.m
  dev-tools/packaging/preference-pane/beats-preference-pane/Info.plist
  dev-tools/packaging/preference-pane/beats-preference-pane/TabViewDelegate.h
  dev-tools/packaging/preference-pane/beats-preference-pane/TabViewDelegate.m
  dev-tools/packaging/preference-pane/beats-preference-pane/beats/Beats.h
  dev-tools/packaging/preference-pane/beats-preference-pane/beats/BeatsService.h
  dev-tools/packaging/preference-pane/beats-preference-pane/beats/BeatsService.m
  dev-tools/packaging/preference-pane/beats-preference-pane/common/common.h
  dev-tools/packaging/preference-pane/beats-preference-pane/common/common.m
  dev-tools/packaging/preference-pane/beats-preference-pane/config.h
  dev-tools/packaging/preference-pane/beats-preference-pane/en.lproj/beats_preference_pane.strings
  dev-tools/packaging/preference-pane/helper/main.m
  dev-tools/packaging/preference-pane/helper/setboot.m
  dev-tools/packaging/preference-pane/magefile.go
  dev-tools/packaging/templates/darwin/README.html.tmpl
  dev-tools/packaging/templates/darwin/component.plist.tmpl
  dev-tools/packaging/templates/darwin/distribution.plist.tmpl
  dev-tools/packaging/templates/darwin/dmg/Uninstall.app/Contents/Info.plist.tmpl
  dev-tools/packaging/templates/darwin/dmg/Uninstall.app/Contents/MacOS/uninstall.sh.tmpl
  dev-tools/packaging/templates/darwin/dmg/Uninstall.app/Contents/Resources/uninstaller.icns
  dev-tools/packaging/templates/darwin/icons/auditbeat.icns
  dev-tools/packaging/templates/darwin/icons/filebeat.icns
  dev-tools/packaging/templates/darwin/icons/heartbeat.icns
  dev-tools/packaging/templates/darwin/icons/metricbeat.icns
  dev-tools/packaging/templates/darwin/icons/packetbeat.icns
  dev-tools/packaging/templates/darwin/icons/winlogbeat.icns
  dev-tools/packaging/templates/darwin/launchd-daemon.plist.tmpl
  dev-tools/packaging/templates/darwin/requirements.plist.tmpl
  dev-tools/packaging/templates/darwin/scripts/postinstall.elastic-agent.tmpl
  dev-tools/packaging/templates/darwin/scripts/postinstall.tmpl
  dev-tools/packaging/templates/darwin/scripts/preinstall.tmpl
  filebeat/scripts/mage/package.go
  heartbeat/scripts/mage/package.go
  metricbeat/scripts/mage/package.go
  packetbeat/scripts/mage/package.go
  winlogbeat/scripts/mage/package.go
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#29936 Update gosputil to build and work under macOS Monterey 12.1
  NOTICE.txt
  go.mod
  go.sum
  libbeat/cmd/platformcheck/platformcheck.go
  libbeat/metric/system/diskio/diskstat.go
  libbeat/metric/system/diskio/diskstat_linux.go
  libbeat/metric/system/diskio/diskstat_linux_test.go
  libbeat/metric/system/diskio/diskstat_other.go
  libbeat/metric/system/diskio/diskstat_windows.go
  libbeat/metric/system/diskio/diskstat_windows_helper.go
  metricbeat/internal/metrics/cpu/metrics_darwin.go
  metricbeat/module/system/network/network.go
  metricbeat/module/system/socket_summary/socket_summary.go
  metricbeat/module/system/socket_summary/socket_summary_test.go
  metricbeat/module/system/socket_summary/sockstat_linux.go
  metricbeat/module/system/socket_summary/sockstat_other.go
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#30120 Add Beats breaking changes for 7.17
  libbeat/docs/release-notes/breaking/breaking-7.17.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
Labels: docs, Team:Docs, v7.17.0, backport-v7.17.0

#30176 [automation] update elastic stack version for testing 7.17.1-aa300c4a
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30175 [automation] update elastic stack version for testing 8.0.0-56a14b95
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#29710 use main default branch
  .ci/apm-beats-update.groovy
  .ci/beats-tester-bc.groovy
  .ci/beats-tester.groovy
  .ci/build-docker-images.groovy
  .ci/jobs/apm-beats-update.yml
  .ci/jobs/beats-schedule-daily.yml
  .ci/jobs/beats-schedule-weekly.yml
  .ci/jobs/beats-test-infra.yml
  .ci/jobs/beats-tester-bc.yml
  .ci/jobs/beats-tester.yml
  .ci/jobs/beats.yml
  .ci/jobs/build-it-docker-images.yml
  .ci/jobs/packaging.yml
  .ci/packer_cache.sh
  .ci/schedule-daily.groovy
  .ci/schedule-weekly.groovy
  .mergify.yml
  CHANGELOG-developer.asciidoc
  CHANGELOG-developer.next.asciidoc
  CHANGELOG.next.asciidoc
  Jenkinsfile
  README.md
  dev-tools/cherrypick_pr
  dev-tools/merge_pr
  dev-tools/open_pr
  docs/devguide/contributing.asciidoc
  docs/devguide/create-metricset.asciidoc
  docs/devguide/metricset-details.asciidoc
  docs/devguide/migrate-dashboards.asciidoc
  filebeat/_meta/test/docs/testing.md
  libbeat/docs/communitybeats.asciidoc
  libbeat/docs/upgrading.asciidoc
  x-pack/elastic-agent/README.md
Labels: Team:Automation, backport-v8.0.0, Team:Ecosystem, backport-v7.17.0

#30148 [automation] update elastic stack version for testing 8.1.0-1cb1f3ad
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30187 Heartbeat: add monitor.type to browser monitors
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
Labels: bug, Team:Uptime, backport-v8.0.0, v8.1.0, backport-v7.17.0

#30184 Revert "[7.17](backport #23872) [packaging] Bump golang-crossbuild version debian8"
  dev-tools/mage/crossbuild.go
  x-pack/auditbeat/magefile.go
Labels: needs_team

#30197 Revert #29031
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/metricbeat.yml
  x-pack/elastic-agent/pkg/agent/application/application.go
  x-pack/elastic-agent/pkg/agent/application/fleet_server_bootstrap.go
  x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway.go
  x-pack/elastic-agent/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
  x-pack/elastic-agent/pkg/agent/application/gateway/fleetserver/fleet_gateway_local.go
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode_test.go
  x-pack/elastic-agent/pkg/agent/application/once.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change_test.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/actions/handlers/handler_action_unenroll.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/dispatcher/dispatcher.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/dispatcher/dispatcher_test.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/controller.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/emitter.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/pipeline.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/router/router.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/router/router_test.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/stream/operator_stream.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/upgrade.go
  x-pack/elastic-agent/pkg/agent/cmd/diagnostics.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/cmd/inspect.go
  x-pack/elastic-agent/pkg/agent/cmd/run.go
  x-pack/elastic-agent/pkg/agent/control/control_test.go
  x-pack/elastic-agent/pkg/agent/control/server/server.go
  x-pack/elastic-agent/pkg/agent/operation/common_test.go
  x-pack/elastic-agent/pkg/agent/operation/monitoring_test.go
  x-pack/elastic-agent/pkg/agent/operation/operator.go
  x-pack/elastic-agent/pkg/agent/storage/store/state_store.go
  x-pack/elastic-agent/pkg/artifact/download/composed/downloader.go
  x-pack/elastic-agent/pkg/artifact/download/fs/downloader.go
  x-pack/elastic-agent/pkg/basecmd/version/cmd_test.go
  x-pack/elastic-agent/pkg/core/monitoring/config/config.go
  x-pack/elastic-agent/pkg/core/monitoring/config/config_test.go
  x-pack/elastic-agent/pkg/core/monitoring/server/server.go
  x-pack/elastic-agent/pkg/core/server/config.go
  x-pack/elastic-agent/pkg/core/server/config_test.go
  x-pack/elastic-agent/pkg/core/server/server.go
  x-pack/elastic-agent/pkg/core/server/server_test.go
  x-pack/elastic-agent/pkg/fleetapi/ack_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/acker/fleet/fleet_acker.go
  x-pack/elastic-agent/pkg/fleetapi/acker/lazy/lazy_acker.go
  x-pack/elastic-agent/pkg/fleetapi/client/client.go
  x-pack/elastic-agent/pkg/remote/client.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.1.0, backport-v8.2.0

#30211 [automation] update elastic stack version for testing 8.0.0-1018d5a4
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30214 Fix 7.17 changelog: 30077 was there
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
Labels: Team:Docs, backport-skip

#30212 Add pipeline in FB's supported hints
  CHANGELOG.next.asciidoc
  filebeat/autodiscover/builder/hints/logs.go
  filebeat/docs/autodiscover-hints.asciidoc
Labels: backport-v8.1.0, Team:Cloudnative-Monitoring

#30177 Create elastic-agent-pull-requests.yml
  .github/workflows/elastic-agent-pull-requests.yml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane

#30216 Revert "Revert "Merge remote-tracking branch 'upstream'""
  .ci/apm-beats-update.groovy
  .ci/beats-tester-bc.groovy
  .ci/beats-tester.groovy
  .ci/build-docker-images.groovy
  .ci/jobs/apm-beats-update.yml
  .ci/jobs/beats-schedule-daily.yml
  .ci/jobs/beats-schedule-weekly.yml
  .ci/jobs/beats-test-infra.yml
  .ci/jobs/beats-tester-bc.yml
  .ci/jobs/beats-tester.yml
  .ci/jobs/beats.yml
  .ci/jobs/build-it-docker-images.yml
  .ci/jobs/packaging.yml
  .ci/packer_cache.sh
  .ci/schedule-daily.groovy
  .ci/schedule-weekly.groovy
  .mergify.yml
  CHANGELOG-developer.asciidoc
  CHANGELOG-developer.next.asciidoc
  CHANGELOG.next.asciidoc
  Jenkinsfile
  README.md
  dev-tools/cherrypick_pr
  dev-tools/merge_pr
  dev-tools/open_pr
  docs/devguide/contributing.asciidoc
  docs/devguide/create-metricset.asciidoc
  docs/devguide/metricset-details.asciidoc
  docs/devguide/migrate-dashboards.asciidoc
  filebeat/_meta/test/docs/testing.md
  libbeat/docs/communitybeats.asciidoc
  libbeat/docs/upgrading.asciidoc
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
  winlogbeat/beater/eventlogger.go
  x-pack/elastic-agent/README.md
Labels: Team:Automation, backport-skip

#29712 tcp/unix input: Stop accepting connections after socket is closed
  CHANGELOG.next.asciidoc
  filebeat/inputsource/common/streaming/listener.go
  filebeat/tests/system/test_syslog.py
  filebeat/tests/system/test_tcp.py
  filebeat/tests/system/test_tcp_tls.py
  filebeat/tests/system/test_unix.py
Labels: bug, Filebeat, Team:Security-External Integrations, Team:Elastic-Agent-Data-Plane, backport-v8.1.0

#29478 [Release] Update test environments after 7.17.0 release
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  testing/environments/prev-minor.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation, backport-skip

#30183 Add metadata change support for processors
  CHANGELOG.next.asciidoc
  libbeat/beat/event.go
  libbeat/processors/actions/add_network_direction_test.go
  libbeat/processors/actions/copy_fields.go
  libbeat/processors/actions/copy_fields_test.go
  libbeat/processors/actions/decode_base64_field.go
  libbeat/processors/actions/decode_base64_field_test.go
  libbeat/processors/actions/decode_json_fields_test.go
  libbeat/processors/actions/decompress_gzip_field.go
  libbeat/processors/actions/decompress_gzip_field_test.go
  libbeat/processors/actions/detect_mime_type.go
  libbeat/processors/actions/detect_mime_type_test.go
  libbeat/processors/actions/docs/add_fields.asciidoc
  libbeat/processors/actions/docs/add_tags.asciidoc
  libbeat/processors/actions/docs/copy_fields.asciidoc
  libbeat/processors/actions/docs/detect_mime_type.asciidoc
  libbeat/processors/actions/docs/include_fields.asciidoc
  libbeat/processors/actions/docs/rename.asciidoc
  libbeat/processors/actions/docs/replace.asciidoc
  libbeat/processors/actions/docs/truncate_fields.asciidoc
  libbeat/processors/actions/drop_fields_test.go
  libbeat/processors/actions/extract_field_test.go
  libbeat/processors/actions/rename.go
  libbeat/processors/actions/rename_test.go
  libbeat/processors/actions/replace.go
  libbeat/processors/actions/replace_test.go
  libbeat/processors/actions/truncate_fields.go
  libbeat/processors/actions/truncate_fields_test.go
  libbeat/processors/add_id/add_id_test.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  libbeat/processors/add_process_metadata/add_process_metadata.go
  libbeat/processors/add_process_metadata/add_process_metadata_test.go
  libbeat/processors/communityid/communityid_test.go
  libbeat/processors/convert/convert.go
  libbeat/processors/convert/convert_test.go
  libbeat/processors/decode_csv_fields/decode_csv_fields.go
  libbeat/processors/decode_csv_fields/decode_csv_fields_test.go
  libbeat/processors/decode_xml/decode_xml_test.go
  libbeat/processors/decode_xml_wineventlog/processor_test.go
  libbeat/processors/dissect/processor.go
  libbeat/processors/dissect/processor_test.go
  libbeat/processors/dns/dns_test.go
  libbeat/processors/extract_array/extract_array.go
  libbeat/processors/extract_array/extract_array_test.go
  libbeat/processors/fingerprint/fingerprint_test.go
  libbeat/processors/registered_domain/registered_domain_test.go
  libbeat/processors/timestamp/timestamp_test.go
  libbeat/processors/translate_sid/translatesid_test.go
  libbeat/processors/urldecode/urldecode.go
  libbeat/processors/urldecode/urldecode_test.go
Labels: enhancement, libbeat, backport-v8.0.0, Team:Elastic-Agent-Data-Plane, v8.2.0, backport-v8.1.0

#30233 [automation] update elastic stack version for testing 6.8.24-873158e7
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30054 Update openshift documentation, manifests for metricbeat and elastic-agent standalone
  CHANGELOG.next.asciidoc
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
  deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset-configmap.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset.yaml
  metricbeat/docs/running-on-kubernetes.asciidoc
Labels: Team:Integrations, backport-skip

#30164 Drop not audit logs in elasticsearch/audit fileset ingest pipeline
  filebeat/module/elasticsearch/audit/ingest/pipeline-json.yml
  filebeat/module/elasticsearch/audit/test/test-audit-docker.log-expected.json
Labels: Team:Integrations, Stack monitoring, backport-skip

#30226 [libbeat] Fix script processor examples in docs
  libbeat/processors/script/docs/script.asciidoc
Labels: docs, libbeat, Team:Security-External Integrations, backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30238 Do not pass empty region configuration when deploying Lambdas using Functionbeat manager
  CHANGELOG.next.asciidoc
  x-pack/functionbeat/manager/aws/cli_manager.go
Labels: Team:Elastic-Agent-Data-Plane, backport-v8.1.0

#30160 [Release] update version to next minor 8.2.0
  libbeat/version/version.go
Labels: in progress, release, automation, Team:Automation, backport-skip

#30241 Change images to last released version: 7.17
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Automation

#30231 x-pack/auditbeat/module/system/socket: add process.entity_id capture for socket events
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/socket/socket_linux.go
  x-pack/auditbeat/module/system/socket/state.go
  x-pack/auditbeat/tests/system/test_system_socket.py
Labels: enhancement, Team:Security-External Integrations, 8.2-candidate, backport-v8.1.0

#30259 [automation] update elastic stack version for testing 6.8.24-1e7d7419
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30215 docs: Prepare Changelog for 8.0.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, Team:Docs

#30264 Forward port 8.0.0 changelog to 8.1
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, backport-skip

#30131 add mutex to listinfInfo
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/states.go
Labels: Team:Integrations, backport-v8.1.0

#29440 Add supported-versions and update docker-compose for logstash module
  metricbeat/module/logstash/_meta/supported-versions.yml
  metricbeat/module/logstash/docker-compose.yml
  metricbeat/module/logstash/test_logstash.py
Labels: Team:Integrations, Stack monitoring, backport-skip

#30265 Forward port 8.0.0 changelog to main
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, backport-skip

#30237 main: apm-server update pipeline and support for 8.minor in the packer-cache.sh
  .ci/apm-beats-update.groovy
  .ci/packer_cache.sh
Labels: Team:Automation, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#30263 Removing GA workflow
  .github/workflows/elastic-agent-pull-requests.yml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#30282 mergify: auto-assign PR owner
  .mergify.yml
Labels: automation, Team:Automation, backport-skip

#30182 docs: add statement about config file encoding
  libbeat/docs/config-file-format.asciidoc
Labels: review, backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#30167 filebeat/input/journald: fix field name translation
  filebeat/input/journald/conv.go
  filebeat/input/journald/input.go
  filebeat/input/journald/input_filtering_test.go
  filebeat/input/journald/input_test.go
Labels: bug, review, backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#30041 Update doc with use of $ as escape char
  libbeat/docs/shared-env-vars.asciidoc
Labels: Team:Docs, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#30122 Update breaking changes docs for 8.0.0-rc2
  libbeat/docs/release-notes/7.0.0.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.0.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.1.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.10.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.11.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.12.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.13.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.14.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.15.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.16.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.2.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.3.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.4.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.5.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.6.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.7.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.8.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.9.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
  libbeat/docs/release-notes/breaking/field-name-changes.asciidoc
  libbeat/docs/upgrading.asciidoc
Labels: v8.0.0, Team:Docs, backport-v8.0.0, backport-v8.1.0

#30063 libbeat/common/transport: fix log message about TLS
  CHANGELOG.next.asciidoc
  libbeat/common/transport/tls.go
Labels: review, backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#30254 Fix the orphan child processes on Windows
  libbeat/common/proc/job_unix.go
  libbeat/common/proc/job_windows.go
  x-pack/elastic-agent/main.go
  x-pack/elastic-agent/pkg/core/plugin/process/start.go
  x-pack/osquerybeat/internal/osqd/osqueryd.go
  x-pack/osquerybeat/main.go
Labels: bug, Team:Asset Mgt, Team:Elastic-Agent-Control-Plane, backport-v8.1.0

#30299 [automation] update elastic stack version for testing 8.2.0-ff5ac1e4
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30198 Remove unused code for fakeweb
  x-pack/elastic-agent/dev-tools/cmd/fakewebapi/README.md
  x-pack/elastic-agent/dev-tools/cmd/fakewebapi/action_example.json
  x-pack/elastic-agent/dev-tools/cmd/fakewebapi/checkin.json
  x-pack/elastic-agent/dev-tools/cmd/fakewebapi/fetch.sh
  x-pack/elastic-agent/dev-tools/cmd/fakewebapi/main.go
  x-pack/elastic-agent/dev-tools/cmd/fakewebapi/push.sh
Labels: refactoring, technical debt, backport-skip, Team:Elastic-Agent-Control-Plane

#30141 mage: add -trimpath flag to build process
  dev-tools/mage/build.go
Labels: enhancement, cleanup, Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#30243 filebeat/input/httpjson: drain and close response.Body
  x-pack/filebeat/input/httpjson/request.go
Labels: enhancement, review, Filebeat, backport-skip, Team:Elastic-Agent-Data-Plane

#30311 Remove support for Homebrew from the docs
  libbeat/docs/howto/load-index-templates.asciidoc
  libbeat/docs/shared-brew-install.asciidoc
  libbeat/docs/shared-brew-run.asciidoc
  libbeat/docs/shared-directory-layout.asciidoc
  libbeat/docs/tab-widgets/enable-modules-widget.asciidoc
  libbeat/docs/tab-widgets/enable-modules.asciidoc
  libbeat/docs/tab-widgets/install-widget-filebeat.asciidoc
  libbeat/docs/tab-widgets/install-widget-heartbeat.asciidoc
  libbeat/docs/tab-widgets/install-widget-metricbeat.asciidoc
  libbeat/docs/tab-widgets/install-widget.asciidoc
  libbeat/docs/tab-widgets/install.asciidoc
  libbeat/docs/tab-widgets/list-modules-widget.asciidoc
  libbeat/docs/tab-widgets/list-modules.asciidoc
  libbeat/docs/tab-widgets/load-dashboards-logstash-widget.asciidoc
  libbeat/docs/tab-widgets/load-dashboards-logstash.asciidoc
  libbeat/docs/tab-widgets/load-dashboards-widget.asciidoc
  libbeat/docs/tab-widgets/load-dashboards.asciidoc
  libbeat/docs/tab-widgets/setup-widget.asciidoc
  libbeat/docs/tab-widgets/setup.asciidoc
  libbeat/docs/tab-widgets/start-filebeat.asciidoc
  libbeat/docs/tab-widgets/start-widget-filebeat.asciidoc
  libbeat/docs/tab-widgets/start-widget-heartbeat.asciidoc
  libbeat/docs/tab-widgets/start-widget-metricbeat.asciidoc
  libbeat/docs/tab-widgets/start-widget.asciidoc
  libbeat/docs/tab-widgets/start.asciidoc
  packetbeat/docs/gettingstarted.asciidoc
  packetbeat/docs/tab-widgets/devices-widget.asciidoc
  packetbeat/docs/tab-widgets/devices.asciidoc
  packetbeat/docs/tab-widgets/install-libpcap-widget.asciidoc
  packetbeat/docs/tab-widgets/install-libpcap.asciidoc
Labels: docs, v8.0.0, Team:Docs, backport-v8.0.0, v8.1.0, backport-v8.1.0

#30318 [8.1](backport #30311) Remove support for Homebrew from the docs (#30311)
  libbeat/docs/howto/load-index-templates.asciidoc
  libbeat/docs/shared-brew-install.asciidoc
  libbeat/docs/shared-brew-run.asciidoc
  libbeat/docs/shared-directory-layout.asciidoc
  libbeat/docs/tab-widgets/enable-modules-widget.asciidoc
  libbeat/docs/tab-widgets/enable-modules.asciidoc
  libbeat/docs/tab-widgets/install-widget-filebeat.asciidoc
  libbeat/docs/tab-widgets/install-widget-heartbeat.asciidoc
  libbeat/docs/tab-widgets/install-widget-metricbeat.asciidoc
  libbeat/docs/tab-widgets/install-widget.asciidoc
  libbeat/docs/tab-widgets/install.asciidoc
  libbeat/docs/tab-widgets/list-modules-widget.asciidoc
  libbeat/docs/tab-widgets/list-modules.asciidoc
  libbeat/docs/tab-widgets/load-dashboards-logstash-widget.asciidoc
  libbeat/docs/tab-widgets/load-dashboards-logstash.asciidoc
  libbeat/docs/tab-widgets/load-dashboards-widget.asciidoc
  libbeat/docs/tab-widgets/load-dashboards.asciidoc
  libbeat/docs/tab-widgets/setup-widget.asciidoc
  libbeat/docs/tab-widgets/setup.asciidoc
  libbeat/docs/tab-widgets/start-filebeat.asciidoc
  libbeat/docs/tab-widgets/start-widget-filebeat.asciidoc
  libbeat/docs/tab-widgets/start-widget-heartbeat.asciidoc
  libbeat/docs/tab-widgets/start-widget-metricbeat.asciidoc
  libbeat/docs/tab-widgets/start-widget.asciidoc
  libbeat/docs/tab-widgets/start.asciidoc
  packetbeat/docs/tab-widgets/devices-widget.asciidoc
  packetbeat/docs/tab-widgets/devices.asciidoc
  packetbeat/docs/tab-widgets/install-libpcap-widget.asciidoc
  packetbeat/docs/tab-widgets/install-libpcap.asciidoc
Labels: backport, needs_team

#30320 Revert "libbeat/common/transport: fix log message about TLS (#30063)"
  CHANGELOG.next.asciidoc
  libbeat/common/transport/tls.go
Labels: Team:Elastic-Agent-Data-Plane

#30072 [Filebeat] Fix Cisco ASA/FTD configs that used var.input syslog
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/asa/config/input.yml
  x-pack/filebeat/module/cisco/ftd/config/input.yml
Labels: bug, module, Filebeat, Team:Security-External Integrations, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#30008 [Metricbeat] gcp: add dataproc metricset
  CHANGELOG-developer.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/gcp.asciidoc
  metricbeat/docs/modules/gcp/dataproc.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/gcp/_meta/config.yml
  x-pack/metricbeat/module/gcp/constants.go
  x-pack/metricbeat/module/gcp/dataproc/_meta/data.json
  x-pack/metricbeat/module/gcp/dataproc/_meta/data_cluster.json
  x-pack/metricbeat/module/gcp/dataproc/_meta/docs.asciidoc
  x-pack/metricbeat/module/gcp/dataproc/_meta/fields.yml
  x-pack/metricbeat/module/gcp/dataproc/dataproc_integration_test.go
  x-pack/metricbeat/module/gcp/dataproc/dataproc_test.go
  x-pack/metricbeat/module/gcp/dataproc/manifest.yml
  x-pack/metricbeat/module/gcp/fields.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
  x-pack/metricbeat/module/gcp/metrics/response_parser.go
  x-pack/metricbeat/module/gcp/module.yml
  x-pack/metricbeat/modules.d/gcp.yml.disabled
Labels: Team:Integrations, backport-v8.0.0

#29952 [Filebeat] Fix multiple modules in filebeat.yml
  CHANGELOG.next.asciidoc
  filebeat/fileset/factory.go
  filebeat/fileset/fileset.go
  filebeat/fileset/fileset_test.go
  filebeat/fileset/modules.go
  filebeat/fileset/modules_test.go
  filebeat/fileset/pipelines.go
  filebeat/fileset/pipelines_test.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#30322 Add notable Breaking Changes for 8.0
  libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
Labels: docs, Team:Docs, backport-v8.0.0, backport-v8.1.0

#30333 Fix new Recorded Future dashboard
  x-pack/filebeat/module/threatintel/_meta/kibana/7/dashboard/Filebeat-threatintel-recordedfuture.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/037e2af0-df50-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/06744e90-df52-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/139c7da0-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/176bf800-df58-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/2d365f10-8479-11ec-8aa9-11bf914a1ef2.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/3c996410-df52-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/4bcc4cb0-df50-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/5e76ef90-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/6b33edb0-8478-11ec-8aa9-11bf914a1ef2.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/739274d0-8479-11ec-8aa9-11bf914a1ef2.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/790cd040-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/7ed4ce00-df52-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/82fa7420-df58-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/8fb01a00-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/949bc180-df52-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/a0a31740-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/b0837690-df52-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/c2a5c180-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/c6079390-8478-11ec-8aa9-11bf914a1ef2.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/dd4a3da0-df50-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/f37f8350-df50-11eb-8f2b-753caedf727d.json
Labels: bug, Filebeat, :Dashboards, Team:Security-External Integrations, backport-v8.1.0

#30335 Give more time to multiline parser to aggregate logs into events during testing
  filebeat/input/filestream/parsers_integration_test.go
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0

#28658 [Release] Update version to 8.0.1
  libbeat/version/version.go
Labels: release, Team:Automation

#30324 [Heartbeat] Add keyword mapping for service.name
  CHANGELOG.next.asciidoc
  heartbeat/_meta/fields.common.yml
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
Labels: bug, Heartbeat, Team:Uptime, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#30161 [Release] Update docs for the 8.2.0 release
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, backport-skip

#30306 Add kubernetes.container.status.last.reason metric
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_container/_meta/fields.yml
  metricbeat/module/kubernetes/state_container/_meta/test/ksm.v2.0.0.expected
  metricbeat/module/kubernetes/state_container/state_container.go
Labels: backport-v8.0.0, Team:Cloudnative-Monitoring

#30305 tlscommon: fix race condition on TLS hostname validation
  CHANGELOG.next.asciidoc
  libbeat/common/transport/tlscommon/tls_config.go
Labels: bug, review, libbeat, Team:Elastic-Agent-Data-Plane

#30331 libbeat/common/transport: fix log message about TLS
  CHANGELOG.next.asciidoc
  libbeat/common/transport/tls.go
Labels: bug, backport-skip, Team:Elastic-Agent-Data-Plane

#30068 ZooKeeper module: Adapt to ZooKeeper 3.6+ `mntr` response fields' changes.
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/zookeeper.asciidoc
  metricbeat/module/zookeeper/_meta/Dockerfile
  metricbeat/module/zookeeper/_meta/docs.asciidoc
  metricbeat/module/zookeeper/_meta/supported-versions.yml
  metricbeat/module/zookeeper/docker-compose.yml
  metricbeat/module/zookeeper/fields.go
  metricbeat/module/zookeeper/mntr/_meta/fields.yml
  metricbeat/module/zookeeper/mntr/data.go
  metricbeat/module/zookeeper/mntr/mntr_integration_test.go
  metricbeat/module/zookeeper/mntr/mntr_test.go
  metricbeat/module/zookeeper/mntr/testdata/mntr.35.leader.txt
  metricbeat/module/zookeeper/mntr/testdata/mntr.37.leader.txt
  metricbeat/module/zookeeper/test_zookeeper.py
Labels: bug, Team:SIEM, Team:Integrations, needs_integration_sync, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#30227 Heartbeat: set duration to zero for syntax errors
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
Labels: bug, Team:Uptime, backport-v8.0.0, v8.1.0, backport-v8.1.0, backport-v7.17.0

#29940 [libbeat] kafka message support headers feature
  CHANGELOG.next.asciidoc
  libbeat/outputs/kafka/client.go
  libbeat/outputs/kafka/config.go
  libbeat/outputs/kafka/kafka.go
  libbeat/outputs/kafka/kafka_integration_test.go
  libbeat/outputs/kafka/message.go
Labels: libbeat, backport-skip, Team:Elastic-Agent-Data-Plane, v8.2.0

#30271 [Filebeat] Add message to register encode/decode debug logs
  filebeat/beater/crawler.go
  x-pack/filebeat/input/httpjson/encoding.go
Labels: enhancement, backport-skip, Team:Elastic-Agent-Data-Plane, v8.2.0

#29650 [Elastic Agent] Elastic Agent takes long to shut down
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/operation/operator.go
  x-pack/elastic-agent/pkg/core/plugin/process/app.go
  x-pack/elastic-agent/pkg/core/plugin/service/app.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#30357 jjbb: 6 major branch reached EOL
  .ci/jobs/beats.yml
Labels: automation, Team:Automation, backport-skip

#30369 Add support for non-unique keys in Kafka output headers
  CHANGELOG.next.asciidoc
  libbeat/outputs/kafka/client.go
  libbeat/outputs/kafka/config.go
  libbeat/outputs/kafka/docs/kafka.asciidoc
  libbeat/outputs/kafka/kafka_integration_test.go
Labels: enhancement, docs, libbeat, backport-skip, Team:Elastic-Agent-Data-Plane, v8.2.0

#30372 fix: report GitHub Check before the cache
  Jenkinsfile
Labels: ci, Team:Automation, backport-v8.0.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30371 [Elastic Agent] Adjust next changelog wording
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#30076 Refactor of metricbeat process-gathering metrics and system/process
  libbeat/cmd/instance/metrics/metrics.go
  libbeat/cmd/instance/metrics/metrics_file_descriptors.go
  libbeat/metric/system/process/helpers.go
  libbeat/metric/system/process/process.go
  libbeat/metric/system/process/process_aix.go
  libbeat/metric/system/process/process_darwin.go
  libbeat/metric/system/process/process_linux.go
  libbeat/metric/system/process/process_linux_common.go
  libbeat/metric/system/process/process_other.go
  libbeat/metric/system/process/process_test.go
  libbeat/metric/system/process/process_types.go
  libbeat/metric/system/process/process_windows.go
  libbeat/metric/system/resolve/resolve.go
  libbeat/opt/opt.go
  metricbeat/internal/sysinit/module.go
  metricbeat/module/system/process/_meta/data.json
  metricbeat/module/system/process/process.go
  metricbeat/module/system/process/process_test.go
  metricbeat/module/system/process_summary/process_summary.go
  metricbeat/tests/system/test_processors.py
Labels: Team:Elastic-Agent-Data-Plane, v8.2.0, backport-v8.2.0

#30373 update windows matrix support
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/heartbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/osquerybeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: Team:Automation, backport-v8.0.0, backport-v8.1.0

#30388 Osquerybeat: Add install verification for osquerybeat
  x-pack/elastic-agent/pkg/agent/program/supported.go
  x-pack/elastic-agent/spec/osquerybeat.yml
  x-pack/osquerybeat/cmd/root.go
  x-pack/osquerybeat/internal/install/verify.go
  x-pack/osquerybeat/internal/install/verify_test.go
  x-pack/osquerybeat/internal/osqd/osqueryd.go
  x-pack/osquerybeat/internal/osqd/osqueryd_unix.go
  x-pack/osquerybeat/internal/osqd/osqueryd_windows.go
Labels: enhancement, backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v8.1.0

#28750 Add a ring-buffer reporter to libbeat
  libbeat/api/server.go
  libbeat/api/server_test.go
  libbeat/cmd/instance/beat.go
  libbeat/monitoring/monitoring.go
  libbeat/monitoring/monitoring_test.go
  libbeat/monitoring/report/buffer/buffer.go
  libbeat/monitoring/report/buffer/buffer_test.go
  libbeat/monitoring/report/buffer/config.go
  libbeat/monitoring/report/buffer/reporter.go
Labels: enhancement, Team:Automation, Team:Elastic-Agent-Control-Plane, v8.2.0, backport-v8.2.0

#30396 packetbeat/beater: make sure Npcap installation runs before interfaces are needed
  CHANGELOG.next.asciidoc
  packetbeat/beater/packetbeat.go
  packetbeat/beater/processor.go
Labels: bug, Team:Security-External Integrations, 8.1-candidate, backport-v8.1.0

#30351 Apply light edits to 8.0 changelog
  CHANGELOG.asciidoc
Labels: v8.0.0, Team:Docs, backport-v8.0.0

#30258 Heartbeat: fix browser metrics and trace mappings
  heartbeat/_meta/fields.common.yml
  heartbeat/docs/fields.asciidoc
  heartbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
Labels: bug, Team:Uptime, backport-v8.0.0, v8.1.0, backport-v8.1.0, backport-v7.17.0

#30400 ci: use getBranchesFromAliases and support next-patch-8
  .ci/schedule-daily.groovy
  .ci/schedule-weekly.groovy
Labels: Team:Automation, backport-skip

#30343 Add docs about hints and templates autodiscovery priority
  filebeat/docs/autodiscover-hints.asciidoc
  heartbeat/docs/autodiscover-hints.asciidoc
  metricbeat/docs/autodiscover-hints.asciidoc
Labels: backport-v8.1.0, Team:Cloudnative-Monitoring

#30408 [elasticsearch module] serialize shards properties
  metricbeat/docs/fields.asciidoc
  metricbeat/module/elasticsearch/fields.go
  metricbeat/module/elasticsearch/index/_meta/data.json
  metricbeat/module/elasticsearch/index/_meta/fields.yml
  metricbeat/module/elasticsearch/index/data.go
Labels: Team:Integrations, Stack monitoring, v8.0.0, backport-v8.0.0, v8.1.0, v8.2.0, backport-v8.1.0

#30142 Clarify SelectedPackageTypes meaning and improve its usage
  dev-tools/mage/crossbuild.go
  dev-tools/mage/pkg.go
Labels: cleanup, Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#30445 Set `log.offset` to the start of the reported line in filestream
  CHANGELOG.next.asciidoc
  libbeat/reader/readfile/metafields.go
  libbeat/reader/readfile/metafields_test.go
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#30382 [Filebeat] [auditd]: Support EXECVE events with truncated argument list
  CHANGELOG.next.asciidoc
  filebeat/module/auditd/log/ingest/pipeline.yml
  filebeat/module/auditd/log/test/rare.log
  filebeat/module/auditd/log/test/rare.log-expected.json
Labels: bug, review, Team:Security-External Integrations, needs_integration_sync, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#30453 Fix TestNewModuleRegistry flaky test
  filebeat/fileset/modules_test.go
Labels: Filebeat, flaky-test, backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#30415 Clean up python-related system tests
  filebeat/tests/system/filebeat.py
  libbeat/tests/system/beat/beat.py
  metricbeat/module/system/test_system.py
  metricbeat/tests/system/metricbeat.py
  metricbeat/tests/system/test_cmd.py
  metricbeat/tests/system/test_processors.py
Labels: technical debt, backport-skip, Team:Elastic-Agent-Data-Plane

#30452 Install gawk as a replacement for mawk in Docker containers.
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v8.1.0, backport-v7.17.0

#30419 Add BC about Homebrew no longer being available in 8.0
  libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
Labels: docs, v8.0.0, Team:Docs, backport-v8.0.0, v8.1.0, backport-v8.1.0

#30438 packetbeat/beater: make sure Npcap installation runs before interfaces are needed in all cases
  CHANGELOG.next.asciidoc
  packetbeat/beater/packetbeat.go
  packetbeat/beater/processor.go
Labels: bug, Team:Security-External Integrations, 8.1-candidate, backport-v8.1.0

#30439 Spelling fix
  docs/devguide/modules-dev-guide.asciidoc
Labels: docs, Filebeat, Team:Integrations, backport-v8.0.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30440 Add drop and explicit tests to avoid duplicate ingest of elasticsearch logs
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/audit/test/test-audit-800.mixed.log
  filebeat/module/elasticsearch/audit/test/test-audit-800.mixed.log-expected.json
  filebeat/module/elasticsearch/deprecation/ingest/pipeline-json-8.yml
  filebeat/module/elasticsearch/deprecation/test/es_deprecation-json.800.mixed.log
  filebeat/module/elasticsearch/deprecation/test/es_deprecation-json.800.mixed.log-expected.json
  filebeat/module/elasticsearch/server/test/elasticsearch-json.800.mixed.log
  filebeat/module/elasticsearch/server/test/elasticsearch-json.800.mixed.log-expected.json
  filebeat/module/elasticsearch/slowlog/ingest/pipeline-json-8.yml
  filebeat/module/elasticsearch/slowlog/test/es_slowlog.800.mixed.log
  filebeat/module/elasticsearch/slowlog/test/es_slowlog.800.mixed.log-expected.json
Labels: Filebeat, Team:Integrations, Stack monitoring, backport-v8.0.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0

#30432 fix typos and improve sentences
  x-pack/elastic-agent/pkg/agent/application/paths/files.go
  x-pack/elastic-agent/pkg/agent/storage/store/state_store.go
  x-pack/elastic-agent/pkg/core/monitoring/beats/beats_monitor.go
  x-pack/elastic-agent/pkg/core/monitoring/monitor.go
  x-pack/elastic-agent/pkg/core/plugin/process/start.go
  x-pack/elastic-agent/pkg/core/plugin/service/app.go
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane, v8.2.0

#30500 Fix Docker module: rename fields on dashboards
  CHANGELOG.next.asciidoc
  metricbeat/module/docker/_meta/kibana/7/visualization/Docker-Network-IO-ecs.json
  metricbeat/module/docker/_meta/kibana/7/visualization/Docker-containers-ecs.json
Labels: Team:Integrations, backport-v8.0.0, backport-v8.1.0

#30509 packetbeat/beater: don't attempt to install npcap when already installed
  CHANGELOG.next.asciidoc
  packetbeat/beater/install_npcap.go
  packetbeat/npcap/npcap.go
  packetbeat/npcap/npcap_other.go
  packetbeat/npcap/npcap_windows.go
Labels: bug, Team:Security-External Integrations, 8.1-candidate, backport-v8.1.0

#30508 docs: Prepare Changelog for 8.0.1
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, Team:Docs

#30517 Forward-port 8.0.1 changelog to 8.1
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: release, Team:Docs, backport-skip

#30512 Switch skip to use `CI`
  auditbeat/tests/system/test_file_integrity.py
Labels: Team:Automation, Team:Security-External Integrations, backport-v8.0.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#30522 Forward-port 8.0.1 changelog to main
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Docs, backport-skip

#30519 docs: update docs versions 7.17.1
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#30518 extend documentation about setting orchestrator.cluster fields
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/module/kubernetes/_meta/docs.asciidoc
Labels: docs, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0, Team:Cloudnative-Monitoring

#30529 Add `parsers` examples to `filestream` reference configuration
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/filebeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#30441 [automation] update elastic stack version for testing 8.2.0-74785f8b
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#30490 {,x-pack/}auditbeat: remove unused fields and params and mark platform-specific code
  auditbeat/module/file_integrity/eventreader_test.go
  x-pack/auditbeat/module/system/package/rpm_common_test.go
  x-pack/auditbeat/module/system/socket/dns/afpacket/config.go
  x-pack/auditbeat/module/system/socket/guess/creds.go
  x-pack/auditbeat/module/system/user/config.go
Labels: cleanup, Team:Security-External Integrations, backport-skip, 8.2-candidate

#30543 [Winlogbeat] Improve registry error message
  CHANGELOG.next.asciidoc
  winlogbeat/beater/winlogbeat.go
  winlogbeat/checkpoint/checkpoint.go
Labels: bug, Winlogbeat, Team:Security-External Integrations, backport-v8.2.0

#30489 {,x-pack/}packetbeat: remove dead code and unused fields, vars, consts and comments
  packetbeat/flows/flowid_test.go
  packetbeat/npcap/npcap.go
  packetbeat/protos/cassandra/internal/gocql/marshal.go
  packetbeat/protos/memcache/errors.go
  packetbeat/scripts/mage/config.go
Labels: cleanup, Team:Security-External Integrations, backport-skip, 8.2-candidate

#30513 packetbeat/beater: help the GC clean up the Npcap installer if it's not used
  packetbeat/beater/install_npcap.go
Labels: bug, enhancement, Team:Security-External Integrations, 8.1-candidate, backport-v8.1.0

#30526 Cherry-pick #28868 to 7.17: Enhance add_kubernetes_metadata matcher
  CHANGELOG.next.asciidoc
  filebeat/processor/add_kubernetes_metadata/matchers.go
  filebeat/processor/add_kubernetes_metadata/matchers_test.go
  libbeat/processors/add_kubernetes_metadata/config.go
  libbeat/processors/add_kubernetes_metadata/config_test.go
  libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc
Labels: backport, [zube]: In Review, Team:Integrations

#30527 Cherry-pick #28868 to 8.0: Enhance add_kubernetes_metadata matcher
  CHANGELOG.next.asciidoc
  filebeat/processor/add_kubernetes_metadata/matchers.go
  filebeat/processor/add_kubernetes_metadata/matchers_test.go
  libbeat/processors/add_kubernetes_metadata/config.go
  libbeat/processors/add_kubernetes_metadata/config_test.go
  libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc
Labels: backport, [zube]: Inbox, Team:Integrations

#30552 Adjust the documentation of `backoff` options in filestream input
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/input/filestream/config.go
Labels: backport-v8.0.0, backport-v7.16.0, Team:Elastic-Agent-Data-Plane, backport-v8.1.0, backport-v7.17.0

#30549 {,x-pack/}winlogbeat: fix lint
  winlogbeat/beater/winlogbeat.go
  winlogbeat/eventlog/factory.go
  winlogbeat/eventlog/wineventlog.go
  winlogbeat/module/pipeline.go
  winlogbeat/sys/wineventlog/renderer.go
  winlogbeat/sys/wineventlog/wineventlog_windows.go
Labels: bug, cleanup, Team:Security-External Integrations, backport-skip, 8.2-candidate

#30548 {,x-pack/}auditbeat: fix lint
  auditbeat/module/file_integrity/action.go
  auditbeat/module/file_integrity/eventreader_fsevents.go
  auditbeat/module/file_integrity/eventreader_test.go
  auditbeat/scripts/mage/package.go
Labels: cleanup, Team:Security-External Integrations, backport-skip, 8.2-candidate

#30564 [Filebeat] Remove RecordedFuture dataset from Threat Intel module
  CHANGELOG.next.asciidoc
  filebeat/docs/fields.asciidoc
  filebeat/docs/images/filebeat-threatintel-recordedfuture.png
  filebeat/docs/modules/threatintel.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/threatintel/_meta/config.yml
  x-pack/filebeat/module/threatintel/_meta/docs.asciidoc
  x-pack/filebeat/module/threatintel/_meta/kibana/7/dashboard/Filebeat-threatintel-recordedfuture.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/037e2af0-df50-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/06744e90-df52-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/139c7da0-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/176bf800-df58-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/2d365f10-8479-11ec-8aa9-11bf914a1ef2.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/3c996410-df52-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/4bcc4cb0-df50-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/5e76ef90-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/6b33edb0-8478-11ec-8aa9-11bf914a1ef2.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/739274d0-8479-11ec-8aa9-11bf914a1ef2.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/790cd040-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/7ed4ce00-df52-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/82fa7420-df58-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/8fb01a00-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/949bc180-df52-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/a0a31740-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/b0837690-df52-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/c2a5c180-df51-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/c6079390-8478-11ec-8aa9-11bf914a1ef2.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/dd4a3da0-df50-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/_meta/kibana/7/lens/f37f8350-df50-11eb-8f2b-753caedf727d.json
  x-pack/filebeat/module/threatintel/fields.go
  x-pack/filebeat/module/threatintel/recordedfuture/_meta/fields.yml
  x-pack/filebeat/module/threatintel/recordedfuture/config/config.yml
  x-pack/filebeat/module/threatintel/recordedfuture/ingest/decode_csv.yml
  x-pack/filebeat/module/threatintel/recordedfuture/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/recordedfuture/manifest.yml
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_assorted.json.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_assorted.json.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_domain_default.csv.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_domain_default.csv.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_hash_default.csv.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_hash_default.csv.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_ip_default.csv.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_ip_default.csv.log-expected.json
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_url_default.csv.log
  x-pack/filebeat/module/threatintel/recordedfuture/test/rf_url_default.csv.log-expected.json
  x-pack/filebeat/modules.d/threatintel.yml.disabled
Labels: review, Filebeat, breaking change, release-note:breaking, Team:Security-External Integrations, backport-v8.1.0

#30547 {,x-pack/}packetbeat: fix staticcheck lint and spelling
  packetbeat/decoder/util.go
  packetbeat/flows/worker.go
  packetbeat/npcap/npcap.go
  packetbeat/procs/procs.go
  packetbeat/protos/amqp/amqp.go
  packetbeat/protos/dns/names.go
  packetbeat/protos/icmp/message.go
  packetbeat/protos/memcache/plugin_tcp.go
  packetbeat/protos/mongodb/mongodb_structs.go
  packetbeat/protos/mysql/mysql.go
  packetbeat/protos/sip/plugin.go
  packetbeat/protos/tls/parse.go
  packetbeat/protos/udp/udp.go
  packetbeat/scripts/mage/package.go
Labels: cleanup, Team:Security-External Integrations, backport-skip, 8.2-candidate

#30289 Alter agent install to detect installation from package
  Vagrantfile
  dev-tools/vagrant_scripts/unixProvision.sh
  x-pack/elastic-agent/CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/agent/cmd/install.go
  x-pack/elastic-agent/pkg/agent/install/install_unix.go
  x-pack/elastic-agent/pkg/agent/install/install_windows.go
  x-pack/elastic-agent/pkg/agent/install/installed.go
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane

#30469 Move linux/memory out of go-sysinfo, add support for hostfs
  metricbeat/module/linux/memory/_meta/data.json
  metricbeat/module/linux/memory/_meta/testdata/proc/meminfo
  metricbeat/module/linux/memory/_meta/testdata/proc/vmstat
  metricbeat/module/linux/memory/data.go
  metricbeat/module/linux/memory/memory_linux_test.go
Labels: enhancement, technical debt, Team:Elastic-Agent-Data-Plane, backport-v8.2.0

#30570 x-pack/filebeat/threatintel: make modules agree more with others in the beat
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/threatintel/abusemalware/config/config.yml
  x-pack/filebeat/module/threatintel/abusemalware/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/abusemalware/test/abusechmalware.ndjson.log-expected.json
  x-pack/filebeat/module/threatintel/abuseurl/config/config.yml
  x-pack/filebeat/module/threatintel/abuseurl/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/abuseurl/test/abusechurl.ndjson.log-expected.json
  x-pack/filebeat/module/threatintel/anomali/config/config.yml
  x-pack/filebeat/module/threatintel/anomali/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/anomali/test/anomali_limo.ndjson.log-expected.json
  x-pack/filebeat/module/threatintel/anomalithreatstream/config/config.yml
  x-pack/filebeat/module/threatintel/anomalithreatstream/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/anomalithreatstream/test/generated.log-expected.json
  x-pack/filebeat/module/threatintel/malwarebazaar/config/config.yml
  x-pack/filebeat/module/threatintel/malwarebazaar/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/malwarebazaar/test/malwarebazaar.ndjson.log-expected.json
  x-pack/filebeat/module/threatintel/misp/config/config.yml
  x-pack/filebeat/module/threatintel/misp/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/misp/test/misp_sample.ndjson.log-expected.json
  x-pack/filebeat/module/threatintel/misp/test/misp_sample_with_ext_attributes.ndjson.log-expected.json
  x-pack/filebeat/module/threatintel/otx/config/config.yml
  x-pack/filebeat/module/threatintel/otx/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/otx/test/otx_sample.ndjson.log-expected.json
  x-pack/filebeat/module/threatintel/threatq/config/config.yml
  x-pack/filebeat/module/threatintel/threatq/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/threatq/test/threatq_sample.ndjson.log-expected.json
Labels: bug, Team:Security-External Integrations, backport-skip, 8.2-candidate

#30583 docs: Prepare Changelog for 7.17.1
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#30562 Agent: populate action_input_type for the .fleet-actions-results
  CHANGELOG.next.asciidoc
  x-pack/elastic-agent/pkg/fleetapi/ack_cmd.go
  x-pack/elastic-agent/pkg/fleetapi/acker/fleet/fleet_acker.go
  x-pack/elastic-agent/pkg/fleetapi/acker/fleet/fleet_acker_test.go
Labels: Team:Asset Mgt, Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#30566 metricbeat - fix elasticsearch and kibana integration tests failures in 8.0
  metricbeat/docs/fields.asciidoc
  metricbeat/module/elasticsearch/fields.go
  metricbeat/module/elasticsearch/index/_meta/fields.yml
  metricbeat/module/elasticsearch/node_stats/_meta/fields.yml
  metricbeat/module/kibana/settings/settings_integration_test.go
Labels: Team:Integrations, Stack monitoring, backport-v8.0.0, backport-v8.1.0

#30586 x-pack/auditbeat/module/system/socket: defend against exec with zero arguments
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/socket/events.go
Labels: bug, Auditbeat, Team:Security-External Integrations, backport-v8.0.0, 8.2-candidate, backport-v8.1.0, backport-v7.17.0

#30520 [Release] Update version to 7.17.2
  libbeat/version/version.go
Labels: release, Team:Automation

#30601 Add infra-monitoring-ui team as codeowner
  .github/CODEOWNERS
Labels: needs_team, backport-skip

#30598 [MySQL Enterprise] Adding default paths values to manifest.yml
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/mysqlenterprise/audit/manifest.yml
Labels: Team:Security-External Integrations, backport-v8.2.0, backport-v7.17.0

#30599 bump test environments versions
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Automation, backport-v8.1.0

#30579 Remove references to gcp from the Functionbeat docs
  x-pack/functionbeat/docs/deploying.asciidoc
  x-pack/functionbeat/docs/getting-started.asciidoc
  x-pack/functionbeat/docs/iam-permissions.asciidoc
  x-pack/functionbeat/docs/overview.asciidoc
  x-pack/functionbeat/docs/tab-widgets/credentials-google-widget.asciidoc
  x-pack/functionbeat/docs/tab-widgets/credentials-google.asciidoc
  x-pack/functionbeat/docs/tab-widgets/deploy-google-widget.asciidoc
  x-pack/functionbeat/docs/tab-widgets/deploy-google.asciidoc
Labels: v8.0.0, Team:Docs, v7.16.0, backport-v8.0.0, backport-v7.16.0, v8.1.0, backport-v8.1.0, v7.17.0, backport-v7.17.0

#30355 Add Beats upgrade docs for 8.0
  libbeat/docs/images/confirm-index-template.png
  libbeat/docs/tab-widgets/load-index-template-widget.asciidoc
  libbeat/docs/tab-widgets/load-index-template.asciidoc
  libbeat/docs/upgrade-setup-commands.asciidoc
  libbeat/docs/upgrading.asciidoc
Labels: v8.0.0, Team:Docs, backport-v8.0.0, backport-v8.1.0

#30565 Update breaking-8.0.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
Labels: v8.0.0, Team:Docs, backport-v8.1.0
