Repository elastic/beats, pull requests merged in 2023-01, with the labels that each got.

#34082 Correct typo in error message
  libbeat/cmd/instance/locks/lock.go
Labels: Team:Elastic-Agent

#34165 Disable seccomp filter for osquerybeat
  NOTICE.txt
  libbeat/cmd/instance/beat.go
Labels: bug, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, backport-v8.6.0

#34128 Add elastic/obs-cloudnative-monitoring as a codeowner for some beats modules
  .github/CODEOWNERS
Labels: backport-skip, Team:Cloudnative-Monitoring

#34124 Update ironbank base image to ubi 8.7
  dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile
  dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/filebeat/Dockerfile
  dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile
  dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile
  dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile
  dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml
Labels: needs_team

#34181 [Filebeat] - regenerate module log timestamps for 2023
  x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/non-canonical.log-expected.json
  x-pack/filebeat/module/cisco/nexus/test/nexus.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/288_auto_clear_users_history_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/289_auto_clear_users_history_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/310_monitor_dr_replication_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/311_monitor_dr_replication_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/357_monitor_fw_rules_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/358_monitor_fw_rules_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/479_security_warning_the_signature_hash_algorithm_of_the_vault_certificate_is_sha1.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/59_clear_safe_history.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/88_set_password.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/legacysyslog.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, backport-v8.6.0

#33598 Fix logstash output config examples
  libbeat/outputs/logstash/docs/logstash.asciidoc
Labels: backport-v8.0.0, Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v8.4.0, backport-v8.5.0, backport-v8.6.0

#34196 [automation] update elastic stack version for testing 8.7.0-129a645f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34198 [automation] update elastic stack version for testing 8.6.0-08ebeaf7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34205 [automation] update elastic stack version for testing 8.7.0-df9bb536
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34204 [automation] update elastic stack version for testing 8.6.0-9105192d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34207 Updated notice to contain proper year
  NOTICE.txt
Labels: Team:Elastic-Agent, backport-skip, Team:Elastic-Agent-Data-Plane

#34206 Updated notice to contain proper year
  NOTICE.txt
Labels: Team:Elastic-Agent, backport-skip, Team:Elastic-Agent-Data-Plane

#34159 Recognize log level in Elasticsearch JVM logs
  CHANGELOG.next.asciidoc
  filebeat/module/elasticsearch/gc/ingest/pipeline.yml
  filebeat/module/elasticsearch/gc/test/gc.log
  filebeat/module/elasticsearch/gc/test/gc.log-expected.json
Labels: enhancement, Filebeat, needs_team, v8.7.0, Module:elasticsearch

#34209 [Metricbeat][Kubernetes] Fix scheduler and proxy dashboard
  metricbeat/module/kubernetes/_meta/kibana/7/dashboard/2ec26ce0-f5f1-11ec-8853-8b596bddf5f9.json
  metricbeat/module/kubernetes/_meta/kibana/7/dashboard/5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
  metricbeat/module/kubernetes/_meta/kibana/7/dashboard/f5ab5510-9c94-11e9-94fd-c91206cd5249.json
Labels: bug, Team:Cloudnative-Monitoring

#33833 packetbeat/{beater,protos/tcp,protos/udp,sniffer}: add initial metrics for TCP/UDP traffic
  CHANGELOG.next.asciidoc
  packetbeat/beater/packetbeat.go
  packetbeat/beater/processor.go
  packetbeat/protos/tcp/tcp.go
  packetbeat/protos/tcp/tcp_test.go
  packetbeat/protos/udp/udp.go
  packetbeat/protos/udp/udp_test.go
  packetbeat/sniffer/decoders.go
  packetbeat/sniffer/sniffer.go
Labels: enhancement, Packetbeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#33922 winlogbeat/eventlog: add initial event processing metrics support
  CHANGELOG.next.asciidoc
  winlogbeat/beater/winlogbeat.go
  winlogbeat/docs/configuring-howto.asciidoc
  winlogbeat/eventlog/eventlog.go
  winlogbeat/eventlog/wineventlog.go
  winlogbeat/eventlog/wineventlog_experimental.go
Labels: enhancement, Filebeat, Winlogbeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#34220 [automation] update elastic stack version for testing 8.7.0-61c35791
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33689 [Release] Update version to 8.6.1
  libbeat/version/version.go
Labels: release, Team:Automation

#34216 docs: Prepare Changelog for 8.6.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, Team:Elastic-Agent, forwardport-main

#33560 [metricbeat] [gcp] refactor metric filter builder
  x-pack/metricbeat/module/gcp/constants.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester_test.go
Labels: Team:Cloud-Monitoring

#34254 Set beats dir as safe for crossbuild
  dev-tools/mage/build.go
Labels: bug, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane

#34237 [Metricbeat][Kubernetes] Update proxy, scheduler and controller manager dashboards
  metricbeat/module/kubernetes/_meta/kibana/7/dashboard/2ec26ce0-f5f1-11ec-8853-8b596bddf5f9.json
  metricbeat/module/kubernetes/_meta/kibana/7/dashboard/5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
  metricbeat/module/kubernetes/_meta/kibana/7/dashboard/f5ab5510-9c94-11e9-94fd-c91206cd5249.json
Labels: enhancement, Team:Cloudnative-Monitoring, backport-v8.6.0

#34224 Remote debug heartbeat
  dev-tools/kubernetes/Tiltfile
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
  dev-tools/kubernetes/heartbeat/Dockerfile.run
  dev-tools/kubernetes/heartbeat/manifest.debug.yaml
  dev-tools/kubernetes/heartbeat/manifest.run.yaml
Labels: enhancement, Team:Cloudnative-Monitoring

#34238 Upgrade elastic-agent-libs to v0.2.16.
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent, backport-v8.6.0

#34246 Osquerybeat: Fix data_stream configuration, enforce the default values used before 8.6.0
  CHANGELOG.next.asciidoc
  x-pack/osquerybeat/cmd/root.go
Labels: bug, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, backport-v8.6.0

#34229 Sanitize test log files
  filebeat/module/elasticsearch/server/test/test.log
  filebeat/module/elasticsearch/server/test/test.log-expected.json
Labels: backport-v7.17.0, Team:Infra Monitoring UI, backport-v8.6.0

#34267 [automation] update elastic stack version for testing 8.6.1-436ca0d1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34276 action: use composite action
  .github/workflows/opentelemetry.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.6.0

#34266 [automation] Update go release version 1.18.10
  .go-version
  .golangci.yml
  auditbeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
Labels: automation, needs_team, dependency, backport-skip, backport-v8.6.0

#34285 [automation] update elastic stack version for testing 8.6.1-cc0796ca
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34221 Issue 34213 : Fixing Docker port mapping to avoid Integration test case failure
  CHANGELOG-developer.next.asciidoc
  x-pack/metricbeat/module/oracle/docker-compose.yml
Labels: Team:Service-Integrations

#34275 [Metricbeat][Kubernetes] Add support for 1.26 K8s version
  Jenkinsfile
  deploy/kubernetes/Jenkinsfile.yml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/module/kubernetes/_meta/docs.asciidoc
  metricbeat/module/kubernetes/controllermanager/_meta/data.json
  metricbeat/module/kubernetes/controllermanager/_meta/test/metrics.1.26
  metricbeat/module/kubernetes/controllermanager/_meta/test/metrics.1.26.expected
  metricbeat/module/kubernetes/controllermanager/controllermanager_test.go
  metricbeat/module/kubernetes/kubernetes.yml
  metricbeat/module/kubernetes/proxy/_meta/test/metrics.1.26
  metricbeat/module/kubernetes/proxy/_meta/test/metrics.1.26.expected
  metricbeat/module/kubernetes/proxy/proxy_test.go
  metricbeat/module/kubernetes/scheduler/_meta/data.json
  metricbeat/module/kubernetes/scheduler/_meta/test/metrics.1.26
  metricbeat/module/kubernetes/scheduler/_meta/test/metrics.1.26.expected
  metricbeat/module/kubernetes/scheduler/scheduler_test.go
Labels: Team:Automation, Team:Cloudnative-Monitoring

#34069 filebeat/module/auditd: teach kv about quoted spaces
  CHANGELOG.next.asciidoc
  filebeat/module/auditd/log/ingest/pipeline.yml
  filebeat/module/auditd/log/test/audit-rhel7_2.log
  filebeat/module/auditd/log/test/audit-rhel7_2.log-expected.json
Labels: bug, Filebeat, Team:Security-External Integrations, backport-v7.17.0, 8.7-candidate, backport-v8.6.0

#34300 [automation] update elastic stack version for testing 7.17.9-a4381da5
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34295 Validate Source IP "LOCAL" or "Unknown" in Windows Security Logs
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/security/ingest/security.yml
  x-pack/winlogbeat/module/security/test/testdata/collection/4778.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/collection/4779.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/ingest/4778.golden.json
  x-pack/winlogbeat/module/security/test/testdata/ingest/4779.golden.json
Labels: bug, Winlogbeat, Team:Security-External Integrations, backport-v7.17.0, 8.7-candidate, backport-v8.6.0

#34311 [automation] update elastic stack version for testing 7.17.9-62814092
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34296 `close.on_state_change.inactive` default value changed to 5m
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/config.go
Labels: Filebeat, Team:Elastic-Agent-Data-Plane, 8.7-candidate, backport-v8.6.0

#34294 Add event IDs 4797, 5379, 5380, 5381, and 5382
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/security/ingest/security.yml
  x-pack/winlogbeat/module/security/test/testdata/collection/4797.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/collection/5379.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/collection/5380.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/collection/5381.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/collection/5382.evtx.golden.json
  x-pack/winlogbeat/module/security/test/testdata/ingest/4797.golden.json
  x-pack/winlogbeat/module/security/test/testdata/ingest/5379.golden.json
  x-pack/winlogbeat/module/security/test/testdata/ingest/5380.golden.json
  x-pack/winlogbeat/module/security/test/testdata/ingest/5381.golden.json
  x-pack/winlogbeat/module/security/test/testdata/ingest/5382.golden.json
Labels: enhancement, Winlogbeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#34322 x-pack/filebeat/input/httpjson: fix handling of null or empty arrays during split
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/input_test.go
  x-pack/filebeat/input/httpjson/split.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#34195 [filebeat][threatintel] Ignore bad indicator IPs for MISP fileset
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/threatintel/misp/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/misp/test/misp_sample_cidr.ndjson.log
  x-pack/filebeat/module/threatintel/misp/test/misp_sample_cidr.ndjson.log-expected.json
Labels: Team:Security-External Integrations

#34337 [automation] update elastic stack version for testing 8.6.1-8f6887b9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34155 [filebeat][gcs] Added support for more mime types, offset tracking via cursor, automatic splitting at root level
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-gcs.asciidoc
  x-pack/filebeat/input/gcs/helper.go
  x-pack/filebeat/input/gcs/helper_test.go
  x-pack/filebeat/input/gcs/input_test.go
  x-pack/filebeat/input/gcs/job.go
  x-pack/filebeat/input/gcs/mock/data_files.go
  x-pack/filebeat/input/gcs/mock/mock.go
  x-pack/filebeat/input/gcs/mock/testdata/array-at-root.json
  x-pack/filebeat/input/gcs/mock/testdata/events-array.json
  x-pack/filebeat/input/gcs/mock/testdata/log.json
  x-pack/filebeat/input/gcs/mock/testdata/log.ndjson
  x-pack/filebeat/input/gcs/mock/testdata/multiline.json
  x-pack/filebeat/input/gcs/mock/testdata/multiline.json.gz
  x-pack/filebeat/input/gcs/mock/testdata/nested-arrays.json
  x-pack/filebeat/input/gcs/scheduler.go
  x-pack/filebeat/input/gcs/state.go
  x-pack/filebeat/input/gcs/types.go
Labels: enhancement, Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#34346 Add checks to ensure reloading of units if the configuration actually changed.
  CHANGELOG.next.asciidoc
  x-pack/libbeat/management/managerV2.go
Labels: Team:Elastic-Agent, backport-v8.6.0

#34349 Run make check and commit the changes.
  x-pack/libbeat/management/managerV2.go
Labels: Team:Elastic-Agent, backport-v8.6.0

#34347 Fix changelog after a bad backport
  CHANGELOG.next.asciidoc
Labels: Team:Elastic-Agent-Data-Plane

#34353 packetbeat/protos/{tcp,udp}: prevent metric namespace collision
  CHANGELOG.next.asciidoc
  packetbeat/protos/tcp/tcp.go
  packetbeat/protos/tcp/tcp_test.go
  packetbeat/protos/udp/udp.go
  packetbeat/protos/udp/udp_test.go
Labels: bug, Packetbeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#34352 Add processing of event ID's 5140 and 5145 to mirror Elastic Agent's …
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/security/ingest/security.yml
Labels: Winlogbeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#34315 ci: use ubuntu:22 workers
  .ci/apm-beats-update.groovy
  .ci/beats-tester.groovy
  .ci/build-docker-images.groovy
  .ci/heartbeat-synthetics.groovy
  .ci/ironbank-validation.groovy
  .ci/packaging.groovy
  Jenkinsfile
  auditbeat/Jenkinsfile.yml
  deploy/kubernetes/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  winlogbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/dockerlogbeat/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/heartbeat/Jenkinsfile.yml
  x-pack/libbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/osquerybeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
  x-pack/winlogbeat/Jenkinsfile.yml
Labels: automation, ci, Team:Automation, backport-v7.17.0, backport-v8.6.0

#34358 disabling flaky tests for now
  x-pack/filebeat/input/azureblobstorage/input_test.go
  x-pack/filebeat/input/gcs/input_test.go
Labels: Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#33893 [Filebeat] aws-s3 input - fix integration test with AWS
  x-pack/filebeat/input/awscloudwatch/_meta/terraform/.terraform.lock.hcl
  x-pack/filebeat/input/awscloudwatch/_meta/terraform/main.tf
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/filebeat/input/awscloudwatch/input_integration_test.go
  x-pack/filebeat/input/awss3/_meta/terraform/.terraform.lock.hcl
  x-pack/filebeat/input/awss3/_meta/terraform/main.tf
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/metrics.go
Labels: bug, Filebeat, Team:Security-External Integrations, aws, backport-skip, Team:Cloud-Monitoring

#34303 fix: update pytest versions and pytest_otel
  libbeat/tests/system/requirements.txt
  libbeat/tests/system/requirements_aix.txt
Labels: bug, Team:Automation

#33584 [Heartbeat] Drop only inheritable cap set and defer setuid to node fork
  CHANGELOG.next.asciidoc
  heartbeat/security/policy_linux_386.go
  heartbeat/security/policy_linux_amd64.go
  heartbeat/security/security.go
  heartbeat/security/security_unix.go
  x-pack/heartbeat/monitors/browser/browser.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_linux.go
Labels: bug, Team:Uptime, backport-skip

#34273 Add support for optional metricsets in xpack mode
  metricbeat/helper/elastic/elastic.go
  metricbeat/helper/elastic/elastic_test.go
  metricbeat/module/beat/beat.go
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/kibana/kibana.go
  metricbeat/module/logstash/logstash.go
Labels: backport-skip, Team:Infra Monitoring UI, >enhancement

#34333 filebeat/input/tcp: add support for TCP input metrics
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-tcp.asciidoc
  filebeat/include/list.go
  filebeat/input/default-inputs/inputs.go
  filebeat/input/tcp/config.go
  filebeat/input/tcp/input.go
  filebeat/input/tcp/input_test.go
  filebeat/input/udp/input.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#34383 ci: use ubuntu-22 for the aarch64 workers
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/dockerlogbeat/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/heartbeat/Jenkinsfile.yml
  x-pack/libbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: automation, Team:Automation, arm, backport-v7.17.0, backport-v8.6.0

#34368 [Release] Update test environments for 8.6.1
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#34394 docs: Prepare Changelog for 8.6.1
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#34335 filebeat/input/unix: add input metrics support
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-unix.asciidoc
  filebeat/input/unix/config.go
  filebeat/input/unix/input.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#34392 Log errors from v2 client errors channel
  CHANGELOG.next.asciidoc
  x-pack/libbeat/management/managerV2.go
Labels: Team:Elastic-Agent, backport-v8.6.0

#34280 Marshal heartbeat duration as int64,string to prevent int64 -> float conversion
  CHANGELOG.next.asciidoc
  heartbeat/monitors/wrappers/monitorstate/esloader_test.go
  heartbeat/monitors/wrappers/monitorstate/monitorstate.go
Labels: bug, Team:Uptime, v8.6.0, backport-v8.6.0

#34292 Add the `take_over` mode for filestream inputs
  CHANGELOG.next.asciidoc
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/backup/backup.go
  filebeat/backup/files.go
  filebeat/backup/files_test.go
  filebeat/backup/registry.go
  filebeat/backup/registry_test.go
  filebeat/beater/filebeat.go
  filebeat/docs/howto/migrate-to-filestream.asciidoc
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/filebeat.reference.yml
  filebeat/input/filestream/config.go
  filebeat/input/filestream/fswatch.go
  filebeat/input/filestream/takeover/config.go
  filebeat/input/filestream/takeover/takeover.go
  filebeat/input/filestream/takeover/takeover_test.go
  x-pack/filebeat/filebeat.reference.yml
Labels: enhancement, Filebeat, backport-skip, Team:Elastic-Agent-Data-Plane, 8.7-candidate, v8.7.0

#34065 [Salesforce] Add pagination support
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/salesforce/apex-rest/config/apex-rest.yml
  x-pack/filebeat/module/salesforce/login-rest/config/login-rest.yml
  x-pack/filebeat/module/salesforce/logout-rest/config/logout-rest.yml
  x-pack/filebeat/module/salesforce/setupaudittrail-rest/config/setupaudittrail-rest.yml
Labels: Filebeat, Team:Service-Integrations

#34403 fixed log naming syntax to not clash with ecs field names
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/azureblobstorage/input.go
Labels: Team:Security-External Integrations, backport-v8.6.0

#34370 [Release] Update test environments for 8.6.2
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#34369 [Release] Update version to 8.6.2
  libbeat/version/version.go
Labels: release, Team:Automation

#34405 Revert "[8.6](backport #34403) fixed log naming syntax to not clash with ecs field names"
  CHANGELOG.next.asciidoc
Labels: needs_team

#34012 Add elasticsearch/ingest_pipeline metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/elasticsearch.asciidoc
  metricbeat/docs/modules/elasticsearch/ingest_pipeline.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/elasticsearch/_meta/config.reference.yml
  metricbeat/module/elasticsearch/_meta/fields.yml
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/fields.go
  metricbeat/module/elasticsearch/ingest_pipeline/_meta/data.json
  metricbeat/module/elasticsearch/ingest_pipeline/_meta/docs.asciidoc
  metricbeat/module/elasticsearch/ingest_pipeline/_meta/fields.yml
  metricbeat/module/elasticsearch/ingest_pipeline/_meta/test/stats.json
  metricbeat/module/elasticsearch/ingest_pipeline/data.go
  metricbeat/module/elasticsearch/ingest_pipeline/data_test.go
  metricbeat/module/elasticsearch/ingest_pipeline/ingest_pipeline.go
  x-pack/metricbeat/metricbeat.reference.yml
Labels: enhancement, Team:Elastic-Agent, backport-skip, Team:Infra Monitoring UI, v8.7.0

#34306 Adding aws-s3 metric for delayed time
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/interfaces.go
  x-pack/filebeat/input/awss3/metrics.go
  x-pack/filebeat/input/awss3/sqs_s3_event.go
Labels: enhancement, Team:Security-External Integrations, backport-skip

#34302 x-pack/filebeat/input/cel: allow users to redact state fields in logs
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/config.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.7-candidate

#34411 [automation] update elastic stack version for testing 8.6.2-a887b34c
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34406 Clarify usage of kubernetes pod labels in condition matching in kubernetes autodiscover provider documentation
  libbeat/docs/shared-autodiscover.asciidoc
Labels: needs_team

#34412 [Azure Blob Storage] Allowing empty content encoding headers for system tests
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/azureblobstorage/job.go
Labels: enhancement, Team:Security-External Integrations, backport-v8.6.0

#34413 [Google Cloud Storage] Add support for alternative_host for system tests
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/gcs/client.go
  x-pack/filebeat/input/gcs/config.go
Labels: enhancement, Team:Security-External Integrations, backport-v8.6.0

#34341 Fix beats changelog docs
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
Labels: needs_team, backport-v8.6.0

#34424 packaging: use ubuntu-22 for the aarch64 workers
  .ci/packaging.groovy
Labels: Team:Automation

#34430 [automation] update elastic stack version for testing 8.6.2-6e25dbb4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34391 Only log publish event messages in trace log level under elastic-agent
  CHANGELOG.next.asciidoc
  libbeat/processors/actions/append.go
  libbeat/processors/actions/copy_fields.go
  libbeat/processors/actions/decode_base64_field.go
  libbeat/processors/actions/decompress_gzip_field.go
  libbeat/processors/actions/rename.go
  libbeat/processors/actions/replace.go
  libbeat/processors/actions/replace_test.go
  libbeat/processors/urldecode/urldecode.go
  libbeat/publisher/agent.go
  libbeat/publisher/processing/default.go
  libbeat/publisher/processing/processors.go
  x-pack/libbeat/management/managerV2.go
Labels: Team:Elastic-Agent, backport-v8.6.0

#34194 Refactor beats lockfile to use timeout, retry
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/locks/lock.go
  libbeat/cmd/instance/locks/lock_other.go
  libbeat/cmd/instance/locks/lock_test.go
  libbeat/cmd/instance/locks/lock_windows.go
Labels: bug, Team:Elastic-Agent, backport-v8.6.0
