Repository elastic/beats, pull requests merged in 2023-12, with the labels that each got.

#37251 [updatecli] update elastic stack version for testing 8.12.0-7281bcc7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37261 [updatecli] update elastic stack version for testing 8.11.2-8ec5d9e2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37262 [updatecli] update elastic stack version for testing 8.12.0-db26fd8b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37213 Add linux disk IO metrics to system/process
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/docs/fields.asciidoc
  metricbeat/module/system/fields.go
  metricbeat/module/system/process/_meta/data.json
  metricbeat/module/system/process/_meta/fields.yml
  metricbeat/module/system/test_system.py
Labels: Team:Elastic-Agent, backport-skip

#37248 1693: Buildkite infra for Filebeat pipeline
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/pull-requests.json
  catalog-info.yaml
Labels: enhancement, Team:Elastic-Agent, backport-v7.17.0, backport-v8.11.0

#37260 Buidlkite introduction: metricbeats
  .buildkite/metricbeat/pipeline.yml
  .buildkite/pull-requests.json
  catalog-info.yaml
Labels: needs_team, backport-v7.17.0, backport-v8.11.0

#37272 Fix log entry
  libbeat/outputs/elasticsearch/client.go
Labels: Team:Elastic-Agent, backport-v7.17.0, backport-v8.11.0

#37284 [updatecli] update elastic stack version for testing 7.17.16-460da4c1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37286 [updatecli] update elastic stack version for testing 8.11.2-851afa34
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37285 [updatecli] update elastic stack version for testing 8.12.0-9d443b17
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36634 [azure] [app_insights] Group metrics by dimensions (segments) and timestamp
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/app_insights/data.go
  x-pack/metricbeat/module/azure/app_insights/data_test.go
Labels: needs_team

#37240 [Kubernetes] Update KSM location to avoid updating all state tests
  metricbeat/helper/kubernetes/ktest/ktest.go
  metricbeat/module/kubernetes/_meta/test/KSM/ksm.v2.10.0.plain
  metricbeat/module/kubernetes/_meta/test/KSM/ksm.v2.8.2.plain
  metricbeat/module/kubernetes/_meta/test/KSM/ksm.v2.9.2.plain
  metricbeat/module/kubernetes/_meta/test/README.md
  metricbeat/module/kubernetes/controllermanager/controllermanager_test.go
  metricbeat/module/kubernetes/proxy/proxy_test.go
  metricbeat/module/kubernetes/scheduler/scheduler_test.go
  metricbeat/module/kubernetes/state_container/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_container/state_container_test.go
  metricbeat/module/kubernetes/state_cronjob/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_cronjob/state_cronjob_test.go
  metricbeat/module/kubernetes/state_daemonset/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_daemonset/state_daemonset_test.go
  metricbeat/module/kubernetes/state_deployment/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_deployment/state_deployment_test.go
  metricbeat/module/kubernetes/state_job/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_job/state_job_test.go
  metricbeat/module/kubernetes/state_namespace/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_namespace/state_namespace_test.go
  metricbeat/module/kubernetes/state_node/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_node/state_node_test.go
  metricbeat/module/kubernetes/state_persistentvolume/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume_test.go
  metricbeat/module/kubernetes/state_persistentvolumeclaim/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_persistentvolumeclaim/state_persistentvolumeclaim_test.go
  metricbeat/module/kubernetes/state_pod/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_pod/state_pod_test.go
  metricbeat/module/kubernetes/state_replicaset/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_replicaset/state_replicaset_test.go
  metricbeat/module/kubernetes/state_resourcequota/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_resourcequota/state_resourcequota_test.go
  metricbeat/module/kubernetes/state_service/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_service/state_service_test.go
  metricbeat/module/kubernetes/state_statefulset/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_statefulset/state_statefulset_test.go
  metricbeat/module/kubernetes/state_storageclass/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_storageclass/state_storageclass_test.go
Labels: Team:Cloudnative-Monitoring

#37289 ironbank: enable /usr/bin/tini
  dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile
  dev-tools/packaging/templates/ironbank/filebeat/Dockerfile
  dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile
  dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile
  dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile
Labels: Team:Elastic-Agent, backport-v7.17.0, backport-v8.11.0

#37294 [Kubernetes Test] Fix lint error on ktest.go
  metricbeat/helper/kubernetes/ktest/ktest.go
Labels: Team:Cloudnative-Monitoring

#37298 [updatecli] update elastic stack version for testing 7.17.16-9916f602
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37299 [updatecli] update elastic stack version for testing 8.12.0-33e8d7e1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37194 [AWS Fargate] Add memory hard limit from container metadata and remove usage percentage
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/awsfargate/fields.go
  x-pack/metricbeat/module/awsfargate/task_stats/_meta/data.json
  x-pack/metricbeat/module/awsfargate/task_stats/_meta/fields.yml
  x-pack/metricbeat/module/awsfargate/task_stats/_meta/testdata/task.json
  x-pack/metricbeat/module/awsfargate/task_stats/container.go
  x-pack/metricbeat/module/awsfargate/task_stats/data.go
  x-pack/metricbeat/module/awsfargate/task_stats/memory.go
  x-pack/metricbeat/module/awsfargate/task_stats/task_stats.go
  x-pack/metricbeat/module/awsfargate/task_stats/task_stats_integration_test.go
  x-pack/metricbeat/module/awsfargate/task_stats/task_stats_test.go
Labels: Team:Integrations

#37305 backport: Add 8.12 branch
  .mergify.yml
Labels: release, Team:Automation, impact:critical, backport-v8.12.0

#37311 [updatecli] update elastic stack version for testing 8.11.2-5d5f3e59
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37309 [Release] Update docs for the 8.13.0 release
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#37308 [Release] update version to next minor 8.13.0
  libbeat/version/version.go
Labels: in progress, release, automation, Team:Automation

#37317 Add benchmark for filestream input
  filebeat/input/filestream/input_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#37334 Make filestream benchmark more precise and more re-usable
  filebeat/input/filestream/input_test.go
Labels: enhancement, backport-skip, Team:Elastic-Agent-Data-Plane

#37333 [Metricbeat][Kubernetes] Move location of docs.plain for testing
  metricbeat/helper/kubernetes/ktest/ktest.go
  metricbeat/module/kubernetes/_meta/test/KSM/docs.plain
Labels: Team:Cloudnative-Monitoring

#37321 [Release] Update version to 8.11.3
  libbeat/version/version.go
Labels: release, Team:Automation

#37327 docs: Prepare Changelog for 8.11.2
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, forwardport-main

#37313 [updatecli] update elastic stack version for testing 7.17.16-e29c45be
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37339 [updatecli] update elastic stack version for testing 8.11.2-0fa17a74
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37330 Remove event fields from error log.
  libbeat/processors/script/javascript/session.go
Labels: Team:Elastic-Agent, backport-v7.17.0, backport-v8.11.0, backport-v8.12.0

#37322 [Release] Update test environments for 8.11.3
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#37352 [Automation][7.17] Bump Golang version to 1.20.12
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  auditbeat/Dockerfile
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  filebeat/Dockerfile
  go.mod
  heartbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  metricbeat/module/nats/_meta/Dockerfile
  metricbeat/module/vsphere/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
  x-pack/metricbeat/module/stan/_meta/Dockerfile
Labels: Team:Elastic-Agent, backport-skip

#37370 x-pack/packetbeat: bump npcap version to v1.78
  CHANGELOG.next.asciidoc
  x-pack/packetbeat/magefile.go
  x-pack/packetbeat/npcap/installer/LICENSE
  x-pack/packetbeat/tests/system/app_test.go
Labels: bug, enhancement, Packetbeat, Team:Security-External Integrations, 8.12-candidate, backport-v8.11.0, backport-v8.12.0

#37369 fix: format log message correctly for heartbeat
  heartbeat/beater/heartbeat.go
  x-pack/heartbeat/monitors/browser/source/project.go
Labels: Heartbeat, Team:obs-ds-hosted-services, v8.11.0, v8.12.0, backport-v8.11.0

#37384 [updatecli] update elastic stack version for testing 7.17.16-0c224de5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37385 [updatecli] update elastic stack version for testing 8.11.3-dce3355e
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37393 [Docs] Document memory leak in `8.11.0` and `8.11.1` release notes
  CHANGELOG.asciidoc
Labels: docs, Team:Docs, Team:Elastic-Agent, forwardport-main

#37310 [Release] Update test environment to 8.13.0
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: in progress, release, automation, Team:Automation, backport-v8.12.0

#37323 docs: update docs versions 7.17.16
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#37326 [Release] Update test environments for 7.17.17
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#37390 [Release] Update version to 8.11.4
  libbeat/version/version.go
Labels: release, Team:Automation

#37388 docs: update docs versions 8.11.3
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#37391 [Release] Update test environments for 8.11.4
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#37399 docs: Prepare Changelog for 8.11.3
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, forwardport-main

#37351 ci(action): auto-bump daily and split in two jobs
  .github/workflows/bump-golang.yml
Labels: Team:Elastic-Agent, backport-skip

#37398 docs: Prepare Changelog for 7.17.16
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#37405 [updatecli] update elastic stack version for testing 7.17.16-cf899701
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37404 Add security notice to Beats 8.11.3 Release Notes
  CHANGELOG.asciidoc
Labels: docs, Team:Docs, forwardport-main

#37411 Fixing 8.12 docs
  CHANGELOG.asciidoc
  libbeat/docs/release.asciidoc
Labels: Team:Elastic-Agent

#37407 Add security notice to Beats 8.11.2 release notes
  CHANGELOG.asciidoc
Labels: docs, release-note:skip, Team:Docs, backport-v8.11.0, backport-v8.12.0

#37413 Add security notice to Beats 7.17.16 release notes
  CHANGELOG.asciidoc
Labels: docs, release-note:skip, Team:Docs

#37418 [winlogbeat] Adding nanoseconds time unit to docs for `source_lag_time`, `batch_read_period`
  winlogbeat/docs/metrics-winlogbeat.asciidoc
Labels: docs, Team:Security-External Integrations, backport-skip

#37421 Revert 37407 to remove security notice in 8.11.2 RN
  CHANGELOG.asciidoc
Labels: docs, release-note:skip, Team:Docs, backport-v8.11.0, backport-v8.12.0

#37419 [beat] Set cluster UUID in state metricset correctly
  metricbeat/module/beat/state/_meta/test/uuid_es_output.json
  metricbeat/module/beat/state/_meta/test/uuid_es_output_pre_connect.json
  metricbeat/module/beat/state/_meta/test/uuid_monitoring_config.json
  metricbeat/module/beat/state/_meta/test/uuid_no_monitoring_config.json
  metricbeat/module/beat/state/data.go
  metricbeat/module/beat/state/data_test.go
Labels: Metricbeat, Team:Infra Monitoring UI, Module:beat, backport-v8.12.0

#37427 fix: adjust formatting for heartbeat monitor and state loader
  CHANGELOG.next.asciidoc
  heartbeat/monitors/active/icmp/stdloop.go
  heartbeat/monitors/monitor.go
  heartbeat/monitors/task.go
  heartbeat/monitors/wrappers/monitorstate/tracker.go
  x-pack/heartbeat/monitors/browser/sourcejob.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
  x-pack/heartbeat/monitors/browser/synthexec/synthtypes.go
Labels: Heartbeat, v8.12.0, backport-v8.11.0, Team:Uptime, backport-v8.12.0

#37340 [updatecli] update elastic stack version for testing 8.12.0-8db20ea5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37440 [Heartbeat] Remove duplicate seccomp syscalls
  CHANGELOG.next.asciidoc
  heartbeat/security/policy_linux_arm64.go
Labels: bug, Team:obs-ds-hosted-services, v8.11.0, backport-v8.11.0

#37443 [updatecli] update elastic stack version for testing 8.12.0-3faaf80d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37446 [updatecli] update elastic stack version for testing 8.12.0-bde01754
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37312 [updatecli] update elastic stack version for testing 8.13.0-6av99u5d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37345 Add filestream benchmarks for many files case, fix data race
  filebeat/input/filestream/input.go
  filebeat/input/filestream/input_test.go
Labels: enhancement, Filebeat, backport-skip, Team:Elastic-Agent-Data-Plane

#37456 [updatecli] update elastic stack version for testing 7.17.17-c7717eb7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37455 [updatecli] update elastic stack version for testing 8.12.0-0d7c3f79
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37454 [updatecli] update elastic stack version for testing 8.13.0-h30gube9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37073 filbeat/docs/inputs: Improve documentation for `httpjson` input
  CHANGELOG.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
Labels: Team:Docs

#37343 Update to elastic-agent-client with chunking support.
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/libbeat/management/managerV2.go
  x-pack/libbeat/management/managerV2_test.go
  x-pack/libbeat/management/simple_input_config_test.go
  x-pack/libbeat/management/tests/mock_server.go
Labels: Team:Elastic-Agent, backport-skip

#37336 Update codeowners
  .github/CODEOWNERS
Labels: cleanup, skip-test-plan, release-note:skip, Team:Elastic-Agent, backport-skip

#37461 [updatecli] update elastic stack version for testing 7.17.17-7f0b87e8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37462 [updatecli] update elastic stack version for testing 8.11.4-d6b1ea5a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37463 [updatecli] update elastic stack version for testing 8.13.0-ubdkmnyz
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37460 [updatecli] update elastic stack version for testing 8.12.0-83badc78
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37212 Replace EOL modules: github.com/golang/protobuf by google.golang.org/protobuf
  NOTICE.txt
  go.mod
  x-pack/functionbeat/provider/aws/aws/kinesis_test.go
  x-pack/functionbeat/provider/aws/aws/transformer/transformer_test.go
  x-pack/metricbeat/module/gcp/metrics/cloudsql/metadata_test.go
  x-pack/metricbeat/module/gcp/metrics/compute/metadata_test.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester_test.go
  x-pack/metricbeat/module/gcp/metrics/metricset.go
  x-pack/metricbeat/module/gcp/metrics/redis/metadata_test.go
Labels: Team:Integrations, Team:Elastic-Agent, backport-v7.17.0, 8.12-candidate

#37470 [updatecli] update elastic stack version for testing 8.11.4-baca29c6
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37472 [updatecli] update elastic stack version for testing 7.17.17-b3d55566
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37471 [updatecli] update elastic stack version for testing 8.13.0-9amqxdis
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37473 [updatecli] update elastic stack version for testing 8.12.0-152634ef
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37483 [updatecli] update elastic stack version for testing 8.11.4-eb79a552
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37484 [updatecli] update elastic stack version for testing 7.17.17-13e2edc2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37482 [updatecli] update elastic stack version for testing 8.13.0-yufkxnwm
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37481 [updatecli] update elastic stack version for testing 8.12.0-cf3c9e0f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37444 add dev-tools/kubernetes entry in codeowners
  .github/CODEOWNERS
Labels: enhancement, Team:obs-ds-hosted-services, Team:Elastic-Agent, backport-skip

#37401 Update k8s manifests for filebeat and metricbeat in dev-tools
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/filebeat/filebeat-configmap.yaml
  dev-tools/kubernetes/Tiltfile
  dev-tools/kubernetes/filebeat/manifest.debug.yaml
  dev-tools/kubernetes/filebeat/manifest.run.yaml
  dev-tools/kubernetes/metricbeat/manifest.debug.multi.yaml
  dev-tools/kubernetes/metricbeat/manifest.debug.yaml
  dev-tools/kubernetes/metricbeat/manifest.run.yaml
Labels: enhancement, Team:obs-ds-hosted-services, cleanup, Team:Elastic-Agent, backport-skip

#37489 [updatecli] update elastic stack version for testing 8.11.4-8b9cf48f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37488 [updatecli] update elastic stack version for testing 7.17.17-f615e8a5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37490 [updatecli] update elastic stack version for testing 8.13.0-vqaxdghw
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37487 [updatecli] update elastic stack version for testing 8.12.0-67b59f94
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37350 [Automation] Bump Golang version to 1.20.12
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  auditbeat/Dockerfile
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  metricbeat/module/nats/_meta/Dockerfile
  metricbeat/module/vsphere/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/metricbeat/module/stan/_meta/Dockerfile
Labels: Team:Elastic-Agent, backport-skip, backport-v8.11.0, backport-v8.12.0

#37500 [updatecli] update elastic stack version for testing 8.11.4-e0baf42b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37501 [updatecli] update elastic stack version for testing 7.17.17-6c067840
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37503 [updatecli] update elastic stack version for testing 8.12.0-fab43f98
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37506 [updatecli] update elastic stack version for testing 8.11.4-4f9102a1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37508 [updatecli] update elastic stack version for testing 7.17.17-514f2280
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37507 [updatecli] update elastic stack version for testing 8.12.0-01443900
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37458 Upgrade elastic-agent-autodiscover dependency; use InitDefaults() to init default configuration
  NOTICE.txt
  go.mod
  go.sum
  libbeat/processors/add_kubernetes_metadata/config.go
  libbeat/processors/add_kubernetes_metadata/config_test.go
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/_meta/config.yml
  metricbeat/module/kubernetes/util/kubernetes.go
  metricbeat/modules.d/kubernetes.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: needs_team, backport-v8.11.0, backport-v8.12.0

#37517 [updatecli] update elastic stack version for testing 8.11.4-b057e528
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37518 [updatecli] update elastic stack version for testing 7.17.17-ae5188ce
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37516 [updatecli] update elastic stack version for testing 8.12.0-e8c03076
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37521 [updatecli] update elastic stack version for testing 8.11.4-33860d30
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37520 [updatecli] update elastic stack version for testing 8.12.0-2df616a6
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37522 [updatecli] update elastic stack version for testing 8.11.4-c3b12837
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37523 [updatecli] update elastic stack version for testing 7.17.17-c6804173
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#37524 [updatecli] update elastic stack version for testing 8.12.0-32d47279
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call
