Repository elastic/beats, pull requests merged in 2023-03, with the labels that each got.

#34702 [Heartbeat] Fix tracking http url parsing error
  CHANGELOG.next.asciidoc
  heartbeat/monitors/active/http/http.go
Labels: bug, Team:Uptime, backport-skip, v8.7.0

#34698 Clean up outputController
  libbeat/publisher/pipeline/controller.go
Labels: cleanup, Team:Elastic-Agent

#34706 [updatecli] update elastic stack version for testing 8.6.3-05dd8895
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34710 update shipper client dependency
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent

#34547 [Heartbeat] Add status to monitor run log struct
  CHANGELOG.next.asciidoc
  heartbeat/monitors/logger/logger.go
  heartbeat/monitors/logger/logger_test.go
  heartbeat/monitors/wrappers/wrappers.go
  heartbeat/monitors/wrappers/wrappers_test.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich.go
Labels: enhancement, Team:Uptime, backport-skip, v8.8.0

#34722 [updatecli] update elastic stack version for testing 8.6.3-70d2e959
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34673 x-pack/filebeat/module/fortinet: include NAT and firewall IPs in related.ip
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/fortinet/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/fortinet/firewall/test/event.log-expected.json
  x-pack/filebeat/module/fortinet/firewall/test/traffic.log-expected.json
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.8-candidate

#34729 [updatecli] update elastic stack version for testing 8.6.3-3395a806
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34637 Make SQL Metricbeat GA.
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/sql.asciidoc
  metricbeat/docs/modules/sql/query.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/module/sql/_meta/docs.html
  x-pack/metricbeat/module/sql/_meta/fields.yml
  x-pack/metricbeat/module/sql/fields.go
  x-pack/metricbeat/module/sql/query/_meta/fields.yml
  x-pack/metricbeat/module/sql/query/query.go
Labels: enhancement, Team:Service-Integrations

#34668 [elasticsearch] Collect node roles as part of node_stats metricset
  metricbeat/module/elasticsearch/node_stats/data.go
Labels: Feature:Stack Monitoring, backport-skip, Team:Infra Monitoring UI, Module:elasticsearch

#34653 [elasticsearch] Collect shard recovery total time
  metricbeat/docs/fields.asciidoc
  metricbeat/module/elasticsearch/_meta/fields.yml
  metricbeat/module/elasticsearch/fields.go
  metricbeat/module/elasticsearch/index_recovery/data.go
Labels: Team:Infra Monitoring UI, Module:elasticsearch, backport-v8.7.0

#34737 [updatecli] update elastic stack version for testing 8.6.3-a99e7a4f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34565 Osquerybeat: Bundle osquery.app for macOS instead of osquery-*.pkg. Eliminates runtime dependency on pkgutil.
  dev-tools/mage/pkgtypes.go
  x-pack/osquerybeat/beater/install.go
  x-pack/osquerybeat/internal/cpio/filemode.go
  x-pack/osquerybeat/internal/cpio/reader.go
  x-pack/osquerybeat/internal/distro/distro.go
  x-pack/osquerybeat/internal/install/install.go
  x-pack/osquerybeat/internal/install/verify.go
  x-pack/osquerybeat/internal/pkgutil/expand.go
  x-pack/osquerybeat/internal/xar/reader.go
  x-pack/osquerybeat/internal/xar/toc.go
  x-pack/osquerybeat/scripts/mage/distro.go
  x-pack/osquerybeat/scripts/mage/package.go
Labels: enhancement, backport-skip, v8.8.0, 8.8-candidate, >enhancement, Team:Defend Workflows

#34715 winlogbeat/docs: adjust XPath query term limit warning
  CHANGELOG.next.asciidoc
  winlogbeat/docs/winlogbeat-options.asciidoc
Labels: bug, docs, Team:Security-External Integrations, backport-v7.17.0, 8.8-candidate, backport-v8.7.0

#34723 Support Unlicense go dependencies
  dev-tools/notice/rules.json
Labels: enhancement, backport-skip, Team:Cloud-Security-Posture

#34752 updatecli: force name of the branch for the bump golang version and update mergify
  .ci/bump-golang.yml
  .mergify.yml
Labels: Team:Automation, backport-v7.17.0, backport-v8.7.0

#34756 [updatecli] update elastic stack version for testing 8.6.3-749502f9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34755 [updatecli] update elastic stack version for testing 7.17.10-26a8527c
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34697 [Heartbeat] Fix reload policy hash consistency, browser monitor cleanup and semaphore release
  CHANGELOG.next.asciidoc
  heartbeat/scheduler/schedjob.go
  x-pack/heartbeat/cmd/root.go
  x-pack/heartbeat/monitors/browser/project.go
Labels: bug, Team:Uptime, v8.7.0, backport-v8.7.0

#34761 Stop re-using processors defined in the config
  CHANGELOG.next.asciidoc
  filebeat/channel/runner.go
  libbeat/processors/safe_processor.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-v7.17.0, backport-v8.6.0, backport-v8.7.0

#34689 x-pack/filebeat/input/cel: update mito extension version
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/config.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
Labels: bug, enhancement, Filebeat, Team:Security-External Integrations, 8.8-candidate, backport-v8.7.0

#34732 filebeat/module/nginx/ingress_controller: Add unix socket log parsing
  CHANGELOG.next.asciidoc
  filebeat/module/nginx/ingress_controller/ingest/pipeline.yml
  filebeat/module/nginx/ingress_controller/test/test.log
  filebeat/module/nginx/ingress_controller/test/test.log-expected.json
Labels: Team:Cloudnative-Monitoring

#34771 [updatecli] update elastic stack version for testing 8.6.3-fdab5f2a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34772 Run apt-get update before running apt-get install in GitHub actions
  .github/workflows/check-docs.yml
  .github/workflows/check-filebeat.yml
  .github/workflows/check-libbeat.yml
  .github/workflows/check-packetbeat.yml
  .github/workflows/check-xpack-auditbeat.yml
  .github/workflows/check-xpack-filebeat.yml
  .github/workflows/check-xpack-packetbeat.yml
Labels: Team:Elastic-Agent, backport-v7.17.0, backport-v8.6.0, backport-v8.7.0

#34743 x-pack/filebeat/input/httpjson: backport configurable keep-alives
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/config.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/internal/v2/config_request.go
  x-pack/filebeat/input/httpjson/internal/v2/config_test.go
  x-pack/filebeat/input/httpjson/internal/v2/input.go
Labels: enhancement, Team:Security-External Integrations, backport-skip, 7.17-candidate

#34769 Bump go-licence-detector to support license.mit files
  NOTICE.txt
  go.mod
  go.sum
Labels: enhancement, Team:Cloud-Security-Posture

#34762 Detect grpc size limit error to avoid infinite retry
  libbeat/outputs/shipper/shipper.go
  libbeat/outputs/shipper/shipper_test.go
Labels: bug, Team:Elastic-Agent

#34741 Prevent pipeline from queueing large batches before an output is set
  libbeat/publisher/pipeline/consumer.go
  libbeat/publisher/pipeline/consumer_test.go
  libbeat/publisher/pipeline/controller.go
  libbeat/publisher/pipeline/controller_test.go
Labels: bug, Team:Elastic-Agent

#34759 [7.17](backport #34376) [Heartbeat] Fix hint-based monitor gen
  CHANGELOG.next.asciidoc
  heartbeat/autodiscover/builder/hints/monitors.go
  heartbeat/autodiscover/builder/hints/monitors_test.go
Labels: needs_team

#34801 [Manual backport][Heartbeat] Fix hint generator test
  heartbeat/autodiscover/builder/hints/monitors_test.go
Labels: bug, Team:Uptime, release-note:skip

#34802 [updatecli][githubrelease] Bump version to 1.19.7
  .go-version
  .golangci.yml
  auditbeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
Labels: Team:Elastic-Agent, backport-skip, backport-v7.17.0, backport-v8.7.0

#34815 [updatecli] update elastic stack version for testing 8.6.3-f262dde5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34816 [updatecli] update elastic stack version for testing 7.17.10-58141e3d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34748 [filebeat][httpjson] - Fix first_response false positive error by making it a flag based object
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/config_response.go
  x-pack/filebeat/input/httpjson/encoding.go
  x-pack/filebeat/input/httpjson/input_test.go
  x-pack/filebeat/input/httpjson/pagination.go
  x-pack/filebeat/input/httpjson/request.go
Labels: bug, Team:Security-External Integrations, backport-v8.7.0

#34831 x-pack/filebeat/input/cel: improve user docs
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: docs, Filebeat, Team:Security-External Integrations, 8.7-candidate, backport-v8.6.0

#34826 [DOCS] Remove hard coded master link
  docs/devguide/create-module.asciidoc
Labels: docs, Team:Elastic-Agent-Data-Plane

#34852 Skip integration and system tests for stan module
  x-pack/metricbeat/module/stan/channels/channels_integration_test.go
  x-pack/metricbeat/module/stan/stats/stats_integration_test.go
  x-pack/metricbeat/module/stan/subscriptions/subscriptions_integration_test.go
  x-pack/metricbeat/module/stan/test_stan.py
Labels: failed-test, backport-v7.17.0, Team:Cloudnative-Monitoring, backport-v8.6.0, backport-v8.7.0

#34857 Make linter requirements compatible with gofmt in 1.19
  .golangci.yml
Labels: bug, Team:Elastic-Agent

#34825 [updatecli] update elastic stack version for testing 7.17.10-6a05ef88
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34830 [DOCS] Remove hard coded links to master branch
  libbeat/docs/newbeat.asciidoc
Labels: docs, backport, needs_team

#34829 [DOCS] Remove hard coded links to master branch
  libbeat/docs/newbeat.asciidoc
Labels: docs, backport, needs_team

#34827 [DOCS] Remove hard coded links to master branch
  libbeat/docs/newbeat.asciidoc
Labels: docs, Team:Elastic-Agent-Data-Plane

#34456 Report FQDN on host.name enabled by a feature flag
  CHANGELOG.next.asciidoc
  NOTICE.txt
  auditbeat/auditbeat.reference.yml
  auditbeat/docs/configuring-howto.asciidoc
  dev-tools/notice/overrides.json
  filebeat/beater/filebeat.go
  filebeat/config/config.go
  filebeat/docs/configuring-howto.asciidoc
  filebeat/filebeat.reference.yml
  go.mod
  go.sum
  heartbeat/docs/configuring-howto.asciidoc
  heartbeat/heartbeat.reference.yml
  libbeat/_meta/config/default.reference.yml.tmpl
  libbeat/_meta/config/feature-flags.reference.yml.tmpl
  libbeat/beat/info.go
  libbeat/beat/info_test.go
  libbeat/cmd/instance/beat.go
  libbeat/docs/shared-feature-flags.asciidoc
  libbeat/features/features.go
  libbeat/features/features_test.go
  libbeat/management/management.go
  libbeat/processors/add_host_metadata/add_host_metadata.go
  libbeat/processors/add_host_metadata/add_host_metadata_test.go
  libbeat/publisher/processing/default.go
  metricbeat/docs/configuring-howto.asciidoc
  metricbeat/metricbeat.reference.yml
  packetbeat/docs/configuring-howto.asciidoc
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/libbeat/management/generate.go
  x-pack/libbeat/management/managerV2.go
  x-pack/libbeat/management/managerV2_test.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: enhancement, Team:Elastic-Agent, backport-v8.7.0

#34861 x-pack/filebeat/input/cel: fix doc entry title indentation
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: bug, docs, Filebeat, Team:Security-External Integrations, 8.8-candidate, backport-v8.6.0, backport-v8.7.0

#34622 x-pack/filebeat/input/httpjson: fix relation parameter handling in getRFC5988Link
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/value_tpl.go
  x-pack/filebeat/input/httpjson/value_tpl_test.go
Labels: bug, Filebeat, Team:Security-External Integrations, backport-v7.17.0, 8.8-candidate, backport-v8.7.0

#34872 [updatecli] update elastic stack version for testing 7.17.10-40fdd3ef
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34871 Don't safe-wrap processors that don't have `Close`
  libbeat/processors/safe_processor.go
  libbeat/processors/safe_processor_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-v7.17.0, backport-v8.6.0, backport-v8.7.0

#34870 Add test for the processor re-use issue
  filebeat/channel/runner.go
  filebeat/channel/runner_mock_test.go
  filebeat/channel/runner_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-v7.17.0, backport-v8.6.0, backport-v8.7.0

#34856 Reenable flaky tests that have been fixed
  filebeat/input/filestream/input_integration_test.go
  filebeat/input/filestream/internal/input-logfile/harvester_test.go
  heartbeat/monitors/active/http/http_test.go
  heartbeat/monitors/active/tcp/tls_test.go
Labels: cleanup, Team:Elastic-Agent

#34886 winlogbeat metrics - Set input type as "winlog"
  winlogbeat/eventlog/wineventlog.go
Labels: bug, Winlogbeat, Team:Security-External Integrations, backport-v8.7.0

#34891 [Heartbeat] Fix mapping for state.ends.id
  CHANGELOG.next.asciidoc
  heartbeat/_meta/fields.common.yml
  heartbeat/include/fields.go
  x-pack/heartbeat/include/fields.go
Labels: bug, Heartbeat, Team:Uptime, v8.7.0, backport-v8.7.0

#34884 libbeat/monitoring/inputmon - Ignore dataset metrics without name and id
  libbeat/monitoring/inputmon/httphandler.go
  libbeat/monitoring/inputmon/httphandler_test.go
Labels: bug, Team:Security-External Integrations, backport-v8.7.0

#34803 Update elastic-agent-system-metrics dep
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent

#34889 packetbeat,winlogbeat,x-pack/filebeat: add metrics documentation
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-tcp.asciidoc
  filebeat/docs/inputs/input-udp.asciidoc
  filebeat/docs/inputs/input-unix.asciidoc
  packetbeat/docs/configuring-howto.asciidoc
  packetbeat/docs/protocol-metrics-packetbeat.asciidoc
  winlogbeat/docs/configuring-howto.asciidoc
  winlogbeat/docs/metrics-winlogbeat.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-cloudwatch.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: enhancement, Packetbeat, Filebeat, Winlogbeat, Team:Security-External Integrations, 8.8-candidate, backport-v8.7.0

#34494 x-pack/filebeat/module/salesforce: use unix line endings
  x-pack/filebeat/module/salesforce/logout-rest/config/logout-rest.yml
Labels: Team:Integrations, cleanup, backport-skip, 8.8-candidate

#34925 [updatecli] update elastic stack version for testing 8.6.3-b0dbc9d5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34924 [updatecli] update elastic stack version for testing 7.17.10-319f366a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34913 [libbeat] Register missing /debug/pprof/ routes in beat HTTP API server
  libbeat/pprof/pprof.go
Labels: bug, Team:Security-External Integrations, Team:Elastic-Agent, backport-v8.7.0

#34711 Add forcemerge threadpools
  metricbeat/docs/fields.asciidoc
  metricbeat/module/elasticsearch/fields.go
  metricbeat/module/elasticsearch/node_stats/_meta/fields.yml
  metricbeat/module/elasticsearch/node_stats/data.go
Labels: enhancement, Team:Observability, Team:Platforms, Team:Core

#34909 [Snyk] Security upgrade alpine from 3.15 to 3.16
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
Labels: needs_team

#34937 [updatecli] update elastic stack version for testing 8.6.3-05478f37
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34936 [Heartbeat] Don't use inet / be silent when setting up projects
  CHANGELOG.next.asciidoc
  x-pack/heartbeat/monitors/browser/source/project.go
Labels: bug, Heartbeat, Team:Uptime, backport-v8.7.0

#34934 x-pack/filebeat/input/cel: register CSV MIME type handlers
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/input.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.8-candidate

#34893 x-pack/filebeat/module/microsoft: drop empty api responses
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/microsoft/defender_atp/config/atp.yml
  x-pack/filebeat/module/microsoft/defender_atp/ingest/pipeline.yml
  x-pack/filebeat/module/microsoft/defender_atp/test/defender_atp-test.json.log
  x-pack/filebeat/module/microsoft/m365_defender/config/defender.yml
  x-pack/filebeat/module/microsoft/m365_defender/ingest/pipeline.yml
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test-empty.ndjson.log
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, 8.8-candidate, bugfix, backport-v8.7.0

#34931 winlogbeat/docs: improve event_logs.name docs
  CHANGELOG.next.asciidoc
  winlogbeat/docs/winlogbeat-options.asciidoc
Labels: enhancement, docs, Winlogbeat, Team:Security-External Integrations, backport-v7.17.0, 8.8-candidate, backport-v8.7.0

#34950 CHANGELOG: fix up pull entries
  CHANGELOG.next.asciidoc
Labels: cleanup, Team:Security-External Integrations, backport-skip

#34820 GCP Carbon footprint metricset
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/gcp.asciidoc
  metricbeat/docs/modules/gcp/carbon.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/gcp/_meta/config.yml
  x-pack/metricbeat/module/gcp/carbon/_meta/data.json
  x-pack/metricbeat/module/gcp/carbon/_meta/docs.asciidoc
  x-pack/metricbeat/module/gcp/carbon/_meta/fields.yml
  x-pack/metricbeat/module/gcp/carbon/carbon.go
  x-pack/metricbeat/module/gcp/carbon/carbon_integration_test.go
  x-pack/metricbeat/module/gcp/carbon/carbon_test.go
  x-pack/metricbeat/module/gcp/fields.go
  x-pack/metricbeat/modules.d/gcp.yml.disabled
Labels: enhancement, Team:Cloud-Monitoring

#34918 [Snyk] Security upgrade alpine from 3.15 to 3.16
  dev-tools/kubernetes/heartbeat/Dockerfile.run
Labels: needs_team

#34939 filebeat/scripts/mage - Remove installation of journald deps from crossBuild
  filebeat/scripts/mage/build.go
Labels: :Packaging, Filebeat, Packaging, build-system, Team:Elastic-Agent, backport-v7.17.0, build-failures, backport-v8.7.0

#34952 Refactor queues to be initialized explicitly instead of through global registry
  libbeat/publisher/pipeline/module.go
  libbeat/publisher/queue/diskqueue/config.go
  libbeat/publisher/queue/diskqueue/queue.go
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/memqueue/config.go
  libbeat/publisher/queue/queue.go
  libbeat/publisher/queue/queue_reg.go
Labels: cleanup, Team:Elastic-Agent

#34955 [updatecli] update elastic stack version for testing 8.6.3-c7851810
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34928 [Heartbeat] Trace socket
  heartbeat/beater/heartbeat.go
  heartbeat/config/config.go
  heartbeat/tracer/tracer.go
  heartbeat/tracer/tracer_test.go
Labels: enhancement, Heartbeat, Team:Uptime

#34810 filebeat/module/mysql: add authentication message parsing and related.ip & related.user fields
  CHANGELOG.next.asciidoc
  filebeat/module/mysql/error/ingest/pipeline.yml
  filebeat/module/mysql/error/test/mariadb-10.4.8.log
  filebeat/module/mysql/error/test/mariadb-10.4.8.log-expected.json
  filebeat/module/mysql/error/test/mysql-darwin-brew-5.7.10.log-expected.json
  filebeat/module/mysql/error/test/mysql-ubuntu-5.5.53-extented.log
  filebeat/module/mysql/error/test/mysql-ubuntu-5.5.53-extented.log-expected.json
  filebeat/module/mysql/error/test/mysql-ubuntu-5.5.53.log-expected.json
  filebeat/module/mysql/error/test/mysql-ubuntu-8.0.15.log
  filebeat/module/mysql/error/test/mysql-ubuntu-8.0.15.log-expected.json
  filebeat/module/mysql/slowlog/ingest/pipeline.json
  filebeat/module/mysql/slowlog/test/mariadb-10.1.21.log-expected.json
  filebeat/module/mysql/slowlog/test/mariadb-10.2.12.log-expected.json
  filebeat/module/mysql/slowlog/test/mariadb-10.3.13.log-expected.json
  filebeat/module/mysql/slowlog/test/mariadb-explain.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-5.7.22.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-darwin-brew-5.7.10.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-debian-5.7.17.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-debian-5.7.19.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-ubuntu-5.5.53.log-expected.json
  filebeat/module/mysql/slowlog/test/mysql-ubuntu-8.0.15.log-expected.json
  filebeat/module/mysql/slowlog/test/percona-ubuntu-5.7.19-innodb.log-expected.json
  filebeat/module/mysql/slowlog/test/percona-ubuntu-5.7.19.log-expected.json
  filebeat/module/mysql/slowlog/test/percona-ubuntu-8.0.15.log-expected.json
Labels: needs_team

#34943 auditbeat/metricbeat/packetbeat - verify required glibc version
  auditbeat/magefile.go
  dev-tools/mage/pkg.go
  packetbeat/scripts/mage/build.go
  packetbeat/scripts/mage/pcap.go
  x-pack/auditbeat/magefile.go
  x-pack/metricbeat/magefile.go
  x-pack/packetbeat/magefile.go
Labels: :Packaging, Packetbeat, Auditbeat, Packaging, Team:Security-External Integrations

#34965 Fix linter typecheck rule
  .golangci.yml
Labels: bug, Team:Elastic-Agent

#34963 Remove timeouts v2 manager integration tests
  x-pack/libbeat/management/tests/fbtest/filebeat_v2_test.go
  x-pack/libbeat/management/tests/init.go
  x-pack/libbeat/management/tests/mbtest/metricbeat_v2_test.go
  x-pack/libbeat/management/tests/mock_server.go
  x-pack/libbeat/management/tests/output_read.go
Labels: bug, Team:Elastic-Agent

#34946 Log any FQDN lookup errors and fallback to OS-reported hostname
  NOTICE.txt
  go.mod
  go.sum
  libbeat/cmd/instance/beat.go
  libbeat/processors/add_host_metadata/add_host_metadata.go
  libbeat/processors/add_host_metadata/add_host_metadata_test.go
Labels: bug, Team:Elastic-Agent, backport-v8.7.0

#34770 Set the fileProspector's ignoreInactiveSince value
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/prospector_creator.go
  filebeat/input/filestream/prospector_creator_test.go
Labels: Team:Elastic-Agent

#34958 Cleanup: Stop using the global plugin registry for the Beats manager
  libbeat/cmd/instance/beat.go
  libbeat/management/management.go
  x-pack/libbeat/management/managerV2.go
  x-pack/libbeat/management/plugin.go
  x-pack/libbeat/management/tests/init.go
Labels: cleanup, Team:Elastic-Agent

#34957 [elasticsearch] ingest ccr remote_cluster
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/ccr/data.go
Labels: bug, Feature:Stack Monitoring, Team:Infra Monitoring UI, Module:elasticsearch

#34962 docs: Prepare Changelog for 8.7.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#34974 Cleanup: Remove unused/underused API from the beats feature package
  filebeat/input/v2/plugin.go
  libbeat/feature/bundle.go
  libbeat/feature/bundle_test.go
  libbeat/feature/feature.go
  libbeat/feature/registry.go
  libbeat/feature/registry_test.go
  x-pack/functionbeat/function/provider/feature.go
  x-pack/functionbeat/function/provider/feature_test.go
  x-pack/functionbeat/function/provider/registry_test.go
  x-pack/functionbeat/include/feature.go
  x-pack/functionbeat/manager/aws/aws.go
  x-pack/functionbeat/provider/aws/include/feature.go
  x-pack/functionbeat/provider/local/include/feature.go
  x-pack/functionbeat/provider/local/local/local.go
Labels: cleanup, Team:Elastic-Agent

#34967 [Snyk] Security upgrade golang from 1.19.5 to 1.19.6
  libbeat/Dockerfile
Labels: needs_team, backport-v8.7.0

#34964 Update `allow_older_versions` when running under Elastic Agent
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
  libbeat/cmd/instance/beat_test.go
Labels: bug, Filebeat, Team:Elastic-Agent-Data-Plane, backport-v8.7.0

#34960 [updatecli] update elastic stack version for testing 7.17.10-5423f09a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34976 [Metricbeat][Kubernetes] Add condition NetworkUnavailable to state node
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_node/_meta/fields.yml
  metricbeat/module/kubernetes/state_node/state_node.go
Labels: Team:Cloudnative-Monitoring

#34914 [filebeat][gcs] - Added missing locks for safe concurrency
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/gcs/job.go
  x-pack/filebeat/input/gcs/scheduler.go
  x-pack/filebeat/input/gcs/state.go
Labels: Team:Security-External Integrations, bugfix, backport-v8.7.0

#34911 Split large batches on error instead of dropping them
  CHANGELOG.next.asciidoc
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/metrics.go
  libbeat/outputs/observer.go
  libbeat/outputs/outest/batch.go
  libbeat/outputs/shipper/api/shipper_mock.go
  libbeat/outputs/shipper/shipper.go
  libbeat/outputs/shipper/shipper_test.go
  libbeat/publisher/event.go
  libbeat/publisher/pipeline/testing.go
  libbeat/publisher/pipeline/ttl_batch.go
  libbeat/publisher/pipeline/ttl_batch_test.go
Labels: bug, Team:Elastic-Agent

#34988 [updatecli] update elastic stack version for testing 8.6.3-a519b953
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call
