Repository elastic/beats, pull requests merged in 2023-05, with the labels that each got.

#35261 [updatecli] update elastic stack version for testing 8.8.0-1fcea9ba
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35248 [updatecli] update elastic stack version for testing 8.7.1-79685088
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35072 [Release] Update version to 8.7.2
  libbeat/version/version.go
Labels: release, Team:Automation

#35278 [updatecli] update elastic stack version for testing 8.9.0-a2c79020
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35282 docs: update docs versions 7.17.10
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#35284 [Release] Update test environments for 7.17.11
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#35283 [Release] Update version to 7.17.11
  libbeat/version/version.go
Labels: release, Team:Automation

#35269 Fix a comment that wasn't properly updated in previous PR
  libbeat/outputs/output_reg.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#35285 [Heartbeat] Fix docs around ICMP sysctl settings
  heartbeat/docs/monitors/monitor-icmp.asciidoc
Labels: docs, Heartbeat, Team:Uptime, v8.7.0

#35257 [Docs] Update logging.files.permissions documentation to consider umask
  filebeat/docs/filebeat-general-options.asciidoc
  libbeat/docs/loggingconfig.asciidoc
Labels: docs, Team:Elastic-Agent, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0, backport-v8.4.0, backport-v8.5.0, backport-v8.6.0, backport-v8.7.0, backport-v8.8.0

#35281 Resolve all linter issues for the `filestream` package
  .golangci.yml
  filebeat/input/filestream/copytruncate_prospector.go
  filebeat/input/filestream/filestream.go
  filebeat/input/filestream/filestream_test.go
  filebeat/input/filestream/identifier_inode_deviceid.go
  filebeat/input/filestream/internal/input-logfile/clean.go
  filebeat/input/filestream/internal/input-logfile/publish.go
  filebeat/input/filestream/internal/input-logfile/publish_test.go
  filebeat/input/filestream/internal/input-logfile/store.go
  filebeat/input/filestream/internal/input-logfile/store_test.go
  filebeat/input/filestream/internal/input-logfile/update_writer.go
  filebeat/input/filestream/prospector.go
  filebeat/input/filestream/prospector_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#35315 [updatecli] update elastic stack version for testing 8.7.1-2ea32c14
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34865 winlogbeat/eventlog: don't attempt to salvage messages for forwarded events
  CHANGELOG.next.asciidoc
  winlogbeat/eventlog/wineventlog.go
Labels: Filebeat, Winlogbeat, Team:Security-External Integrations, 8.8-candidate, bugfix, backport-v8.7.0

#35275 notify: add date to avoid google group issues with similar subjects
  .github/workflows/notify-stalled-snapshots.yml
Labels: needs_team, backport-skip

#33701 [metricbeat] [gcp] add redis metadata
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/metricbeat/module/gcp/metrics/metadata_services.go
  x-pack/metricbeat/module/gcp/metrics/redis/metadata.go
  x-pack/metricbeat/module/gcp/metrics/redis/metadata_test.go
Labels: Team:Cloud-Monitoring

#35303 [8.2](backport #35257) [Docs] Update logging.files.permissions documentation to consider umask
  NOTICE.txt
  filebeat/docs/filebeat-general-options.asciidoc
  libbeat/docs/loggingconfig.asciidoc
Labels: backport, Team:Automation

#35329 [updatecli] update elastic stack version for testing 8.9.0-5c23b5b2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35272 Use UID for dockerfile to allow runasNonRoot to be used.
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Elastic-Agent, >enhancement, backport-v8.8.0

#35324 packetbeat/beater: prevent double close of pb.done
  CHANGELOG.next.asciidoc
  packetbeat/beater/packetbeat.go
Labels: Packetbeat, Team:Security-External Integrations, 8.8-candidate, bugfix, backport-v8.7.0

#35270 upgrade elastic-agent-client to 7.1.1 for pprof fix
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, Team:Elastic-Agent, backport-v8.7.0, backport-v8.8.0

#35327 Source URI Reloading backports
  x-pack/elastic-agent/pkg/agent/application/local_mode.go
  x-pack/elastic-agent/pkg/agent/application/managed_mode.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/emitter/controller.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/router/router.go
  x-pack/elastic-agent/pkg/agent/application/pipeline/stream/operator_stream.go
  x-pack/elastic-agent/pkg/agent/operation/operator.go
  x-pack/elastic-agent/pkg/agent/operation/operator_test.go
  x-pack/elastic-agent/pkg/artifact/config.go
  x-pack/elastic-agent/pkg/artifact/config_test.go
  x-pack/elastic-agent/pkg/artifact/download/composed/downloader.go
  x-pack/elastic-agent/pkg/artifact/download/composed/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/http/downloader.go
  x-pack/elastic-agent/pkg/artifact/download/http/verifier.go
  x-pack/elastic-agent/pkg/artifact/download/reloadable.go
  x-pack/elastic-agent/pkg/artifact/download/snapshot/downloader.go
  x-pack/elastic-agent/pkg/artifact/download/snapshot/verifier.go
Labels: backport, needs_team

#35300 [add_cloud_metadata processor] add cloud.region field to GCE cloud provider
  CHANGELOG.next.asciidoc
  libbeat/processors/add_cloud_metadata/provider_google_gce.go
  libbeat/processors/add_cloud_metadata/provider_google_gce_test.go
Labels: needs_team, backport-v7.17.0, backport-v8.7.0, backport-v8.8.0

#35350 [updatecli] update elastic stack version for testing 8.9.0-23370c3a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35280 [updatecli] update elastic stack version for testing 8.8.0-97faefbe
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35352 Remove unused pipeline callback ClientListener.FilteredOut
  filebeat/beater/channels.go
  libbeat/beat/pipeline.go
  libbeat/publisher/pipeline/client.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#35317 [winlog/winlogbeat] Move repeated channel not found logs to debug level
  CHANGELOG.next.asciidoc
  filebeat/input/winlog/input.go
  winlogbeat/beater/eventlogger.go
Labels: enhancement, Winlogbeat, Team:Security-External Integrations, backport-v7.17.0, backport-v8.6.0, backport-v8.7.0, backport-v8.8.0

#35336 [Heartbeat] Fix run from location in states loader
  CHANGELOG.next.asciidoc
  heartbeat/beater/heartbeat.go
  heartbeat/hbtestllext/isdefs.go
  heartbeat/monitors/factory.go
  heartbeat/monitors/wrappers/monitorstate/esloader.go
  heartbeat/monitors/wrappers/monitorstate/monitorstate.go
  heartbeat/monitors/wrappers/monitorstate/tracker.go
  x-pack/heartbeat/scenarios/basics_test.go
Labels: bug, Heartbeat, Team:Uptime, v8.8.0

#35302 [add_cloud_metadata processor] Update azure metadata api version
  CHANGELOG.next.asciidoc
  libbeat/processors/add_cloud_metadata/provider_azure_vm.go
  libbeat/processors/add_cloud_metadata/provider_azure_vm_test.go
Labels: bug, needs_team, backport-v7.17.0, backport-v8.7.0, backport-v8.8.0

#35341 updatecli: use golang-crossbuild repository
  .ci/bump-golang.yml
  .github/workflows/bump-golang.yml
Labels: Team:Automation, backport-v7.17.0, backport-v8.7.0, backport-v8.8.0

#35381 [updatecli] update elastic stack version for testing 8.8.0-8d0a4918
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35380 [updatecli] update elastic stack version for testing 7.17.11-47c70080
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35342 bump golang 1.19.9
  .go-version
  .golangci.yml
  auditbeat/Dockerfile
  filebeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/auditbeat/magefile.go
  x-pack/functionbeat/Dockerfile
  x-pack/osquerybeat/magefile.go
Labels: Team:Elastic-Agent, backport-v7.17.0, backport-v8.8.0

#35379 [updatecli] update elastic stack version for testing 8.9.0-c595c7d9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35367 [Automation] Bump Golang version to 1.19.9
  .go-version
  .golangci.yml
  auditbeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
Labels: needs_team, backport-skip, backport-v8.8.0

#34487 ci: remove apm-beats-update
  .ci/apm-beats-update.groovy
  .ci/jobs/apm-beats-update.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.7.0, backport-v8.8.0

#35134 Delete `filestream` input after creating for config validation
  filebeat/input/filestream/internal/input-logfile/harvester.go
  filebeat/input/filestream/internal/input-logfile/input.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/filestream/internal/input-logfile/manager_test.go
  filebeat/input/v2/compat/compat.go
  filebeat/input/v2/input.go
  filebeat/input/v2/internal/inputest/loader.go
  filebeat/input/v2/loader.go
  filebeat/tests/system/config/filestream-reload-not-duplicated-id.yml.j2
  filebeat/tests/system/test_reload_inputs.py
  libbeat/cfgfile/reload.go
Labels: Team:Elastic-Agent, v8.8.0, backport-v8.7.0

#35271 [DOCS] Expand & clarify load balancing descriptions
  filebeat/docs/configuring-howto.asciidoc
  filebeat/docs/load-balancing.asciidoc
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
  libbeat/outputs/logstash/docs/logstash.asciidoc
  libbeat/outputs/redis/docs/redis.asciidoc
Labels: docs, Team:Docs

#35399 [updatecli] update elastic stack version for testing 7.17.11-4961dcd0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35401 [Heartbeat] Fix NPE on reloads with run_from
  heartbeat/monitors/factory.go
  heartbeat/monitors/factory_test.go
Labels: bug, Heartbeat, Team:Uptime, v8.8.0, backport-v8.8.0

#35400 [updatecli] update elastic stack version for testing 8.7.2-dd4c72f2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35289 upgrade mssql driver to v0.12.3
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Service-Integrations

#35204 x-pack/filebeat/input/http_endpoint: Add CRC validation for webhooks
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/zoom.asciidoc
  x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
  x-pack/filebeat/input/http_endpoint/config.go
  x-pack/filebeat/input/http_endpoint/crc.go
  x-pack/filebeat/input/http_endpoint/crc_test.go
  x-pack/filebeat/input/http_endpoint/handler.go
  x-pack/filebeat/input/http_endpoint/handler_test.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/http_endpoint/validate.go
  x-pack/filebeat/module/zoom/_meta/docs.asciidoc
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip

#35376 [Heartbeat] States ES Client backoff and run once exit
  CHANGELOG.next.asciidoc
  heartbeat/beater/heartbeat.go
  heartbeat/monitors/wrappers/monitorstate/esloader.go
Labels: bug, Team:Uptime, release-note:skip, v8.8.0, backport-v8.8.0

#35411 [updatecli] update elastic stack version for testing 8.7.2-9848dc50
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35413 [updatecli] update elastic stack version for testing 8.8.0-c26f78b8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35416 [Heartbeat] Normalize state location names
  heartbeat/monitors/wrappers/monitorstate/monitorstate.go
  heartbeat/monitors/wrappers/monitorstate/monitorstate_test.go
Labels: bug, Heartbeat, Team:Uptime, v8.8.0, backport-v8.8.0

#35386 Add more detail about generated docs to the contributors guide
  docs/devguide/contributing.asciidoc
  docs/devguide/documentation.asciidoc
  docs/devguide/index.asciidoc
Labels: docs, Team:Docs, backport-v7.17.0, backport-v8.7.0, backport-v8.8.0

#35409 x-pack/filebeat/input/cel: add execution budget and relax CSV mime name
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/config.go
  x-pack/filebeat/input/cel/input.go
Labels: Filebeat, Team:Security-External Integrations, backport-skip, 8.8-candidate

#35427 libbeat/monitoring/inputmon - Add defensive check for empty ID or input type
  libbeat/monitoring/inputmon/input.go
  libbeat/monitoring/inputmon/input_test.go
Labels: libbeat, Team:Security-External Integrations, Team:Elastic-Agent-Data-Plane

#35426 Remove unnecessary logging
  filebeat/input/filestream/internal/input-logfile/harvester.go
Labels: bug, Team:Elastic-Agent, backport-v8.8.0

#35434 [Heartbeat]: fix error formatting on socktrace timeout
  CHANGELOG.next.asciidoc
  heartbeat/beater/heartbeat.go
  heartbeat/tracer/tracer.go
Labels: bug, Heartbeat, Team:Uptime, backport-v8.8.0

#35424 [Heartbeat] remove Synthetics beta label
  CHANGELOG.next.asciidoc
  heartbeat/docs/monitors/monitor-browser.asciidoc
  x-pack/heartbeat/monitors/browser/browser.go
Labels: Team:Uptime, cleanup, v8.8.0, backport-v8.8.0

#35437 winlogbeat/sys/wineventlog: don't use claimed buffer use value
  CHANGELOG.next.asciidoc
  winlogbeat/sys/wineventlog/wineventlog_windows.go
Labels: bug, Winlogbeat, needs_team, 8.9-candidate, backport-v8.8.0

#35441 Metricbeat AWS Module Docs Fix - Cherry picked from 96f67e8
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
Labels: docs, Team:Cloud-Monitoring

#35423 winlogbeat/sys/wineventlog: don't panic on nil iterator/renderer close
  CHANGELOG.next.asciidoc
  winlogbeat/eventlog/wineventlog_experimental.go
  winlogbeat/sys/wineventlog/iterator.go
  winlogbeat/sys/wineventlog/renderer.go
Labels: bug, Winlogbeat, Team:Security-External Integrations, backport-skip, 8.8-candidate

#35398 [Heartbeat] Force default gid access to extracted project files
  CHANGELOG.next.asciidoc
  x-pack/heartbeat/monitors/browser/source/project.go
  x-pack/heartbeat/monitors/browser/source/project_test.go
  x-pack/heartbeat/monitors/browser/source/source.go
  x-pack/heartbeat/monitors/browser/source/zipurl.go
Labels: bug, Team:Uptime, v8.7.0, backport-v8.8.0

#35446 Log error when setting data into the persistent store fails
  filebeat/input/filestream/internal/input-logfile/publish.go
  filebeat/input/v2/input-cursor/publish.go
Labels: bug, Team:Elastic-Agent, backport-v8.8.0

#35450 packetbeat/sniffer - Use non-deprecated logger statements
  packetbeat/sniffer/afpacket.go
  packetbeat/sniffer/afpacket_linux.go
  packetbeat/sniffer/afpacket_nonlinux.go
  packetbeat/sniffer/device.go
  packetbeat/sniffer/file.go
  packetbeat/sniffer/sniffer.go
Labels: Packetbeat, Team:Security-External Integrations

#35433 x-pack/filebeat/input/azureblobstorage: ensure checkpoint is valid after cursor filling
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/azureblobstorage/state.go
Labels: bug, Filebeat, Team:Security-External Integrations, backport-skip, 8.8-candidate

#35459 Add `elastic/obs-cloud-monitoring` to own cloud-related processors
  .github/CODEOWNERS
Labels: enhancement, needs_team

#35452 Safely start k8s watchers to avoid memory leak
  metricbeat/module/kubernetes/util/kubernetes.go
Labels: v7.17.0, 7.17-candidate, Team:Cloudnative-Monitoring

#35410 ci: retry release manager if it failed
  .ci/packaging.groovy
Labels: automation, Team:Automation, backport-v8.7.0, backport-v8.8.0

#35468 [updatecli] update elastic stack version for testing 8.7.2-7653c06b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35463 Pre-cleanup for #35218
  metricbeat/helper/prometheus/ptest/ptest.go
  metricbeat/module/etcd/metrics/metrics_test.go
  metricbeat/module/kubernetes/apiserver/apiserver_test.go
  metricbeat/module/kubernetes/controllermanager/controllermanager_test.go
  x-pack/libbeat/common/proc/job_unix.go
Labels: Team:Elastic-Agent

#35404 [heartbeat] Stop promoting `browser` options
  heartbeat/docs/configuring-howto.asciidoc
  heartbeat/docs/heartbeat-options.asciidoc
  heartbeat/docs/heartbeat-scheduler.asciidoc
  heartbeat/docs/monitors/monitor-browser.asciidoc
  heartbeat/docs/monitors/monitor-common-options.asciidoc
Labels: docs, Team:Docs, backport-v8.8.0

#35469 Update docs for loadbalance settings in Beats outputs
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
  libbeat/outputs/logstash/docs/logstash.asciidoc
  libbeat/outputs/redis/docs/redis.asciidoc
Labels: docs, Team:Elastic-Agent, backport-v8.7.0, backport-v8.8.0

#35467 auditbeat/module/file_integrity/fileorigin_test.go - Create file per sub-test
  auditbeat/module/file_integrity/fileorigin_test.go
Labels: Auditbeat, flaky-test, Team:Security-External Integrations

#35360 Fix RFC5424 syslog parser to return Z as a timestamp offset
  CHANGELOG.next.asciidoc
  filebeat/input/syslog/parser/syslog_rfc5424.rl
  filebeat/input/syslog/rfc5424_parser.go
  filebeat/input/syslog/rfc5424_test.go
Labels: bug, Team:Security-External Integrations, 8.9-candidate, backport-v8.8.0

#35425 Add time-bounded contexts to AWS API calls
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/aws.go
  x-pack/metricbeat/module/aws/utils.go
Labels: Team:Cloud-Monitoring, backport-v8.7.0, backport-v8.8.0

#35453 [Packetbeat] Add support for af_packet fanout group
  CHANGELOG.next.asciidoc
  packetbeat/_meta/config/beat.reference.yml.tmpl
  packetbeat/config/config.go
  packetbeat/config/config_test.go
  packetbeat/docs/packetbeat-options.asciidoc
  packetbeat/packetbeat.reference.yml
  packetbeat/sniffer/afpacket.go
  packetbeat/sniffer/afpacket_linux.go
  packetbeat/sniffer/afpacket_nonlinux.go
  packetbeat/sniffer/sniffer.go
  x-pack/packetbeat/packetbeat.reference.yml
Labels: enhancement, Packetbeat, Team:Security-External Integrations, backport-skip

#35035 [AWS] [Cloudwatch] Fix no error logs displayed in some instances of logp.Error usage
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/metadata.go
  x-pack/metricbeat/module/aws/cloudwatch/metadata/ec2/ec2.go
  x-pack/metricbeat/module/aws/cloudwatch/metadata/rds/rds.go
  x-pack/metricbeat/module/aws/cloudwatch/metadata/sqs/sqs.go
Labels: bug, Team:Cloud-Monitoring, bugfix

#35487 [updatecli] update elastic stack version for testing 8.7.2-581e1396
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35485 [updatecli] update elastic stack version for testing 8.8.0-9e4f7a5d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35486 [updatecli] update elastic stack version for testing 7.17.11-31efa078
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35474 winlogbeat: allow termination while attempting to open channels
  CHANGELOG.next.asciidoc
  winlogbeat/beater/eventlogger.go
Labels: bug, Winlogbeat, Team:Security-External Integrations, backport-v8.7.0, 8.9-candidate, backport-v8.8.0

#35484 [Packetbeat] Fix BPF filter setting not being applied to sniffers
  CHANGELOG.next.asciidoc
  packetbeat/sniffer/sniffer.go
Labels: bug, Packetbeat, Team:Security-External Integrations, backport-v8.7.0, backport-v8.8.0

#35499 [updatecli] update elastic stack version for testing 8.8.0-49c28bdb
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35498 [updatecli] update elastic stack version for testing 8.7.2-99e4ac2a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35497 [updatecli] update elastic stack version for testing 7.17.11-53c77961
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35466 [DOCS] Add preview notice for FQDN feature
  libbeat/docs/shared-feature-flags.asciidoc
Labels: docs, Team:Docs, backport-v8.7.0, backport-v8.8.0

#35509 [updatecli] update elastic stack version for testing 8.7.2-738acb99
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35508 [updatecli] update elastic stack version for testing 8.8.0-cc834a5d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35510 [updatecli] update elastic stack version for testing 7.17.11-874490f1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35470 [Heartbeat] Bump node to 18.16.0
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Heartbeat, Team:Uptime, technical debt, v8.8.0, backport-v8.8.0

#35435 x-pack/winlogbeat/module/routing: set host.os.type and host.os.family in forwarded events
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/routing/ingest/routing.yml
Labels: enhancement, Winlogbeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35235 x-pack/filebeat/input/httpjson: provide XML decoding functionality
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/config_response.go
  x-pack/filebeat/input/httpjson/encoding.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/input_test.go
  x-pack/filebeat/input/httpjson/pagination.go
  x-pack/filebeat/input/httpjson/request.go
  x-pack/filebeat/input/httpjson/request_test.go
  x-pack/filebeat/input/httpjson/response.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35516 [updatecli] update elastic stack version for testing 7.17.11-b843b253
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35507 [filebeat][httpjson] Add delegated account support when using ADC
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/config_auth.go
  x-pack/filebeat/input/httpjson/config_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations

#35500 [Heartbeat] Disable testing brwoser monitors on darwin platform
  x-pack/heartbeat/monitors/browser/config_test.go
  x-pack/heartbeat/monitors/browser/project_test.go
  x-pack/heartbeat/monitors/browser/source/local_test.go
  x-pack/heartbeat/monitors/browser/source/project_test.go
  x-pack/heartbeat/monitors/browser/source/source_test.go
  x-pack/heartbeat/monitors/browser/source/validatepackage_test.go
  x-pack/heartbeat/monitors/browser/source/zipurl_test.go
  x-pack/heartbeat/monitors/browser/synthexec/enrich_test.go
  x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
Labels: bug, Team:Uptime, release-note:skip, backport-v8.8.0

#35526 [updatecli] update elastic stack version for testing 7.17.11-0c2fb1a0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35517 [updatecli] update elastic stack version for testing 8.8.0-4abaa07c
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35396 [Metricbeat]Move kibana module object instatiation and validations out of metrics…
  metricbeat/module/kibana/cluster_actions/cluster_actions.go
  metricbeat/module/kibana/cluster_rules/cluster_rules.go
  metricbeat/module/kibana/node_actions/node_actions.go
  metricbeat/module/kibana/node_rules/node_rules.go
  metricbeat/module/kibana/stats/stats.go
Labels: bug, Team:Infra Monitoring UI, Module:kibana, backport-v8.7.0, backport-v8.8.0

#35525 Enable dependabot for Go modules
  .github/dependabot.yml
Labels: automation, Team:Elastic-Agent-Data-Plane

#35456 feat: Add Hetzner Cloud to add_cloud_metadata
  .golangci.yml
  CHANGELOG.next.asciidoc
  libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc
  libbeat/processors/add_cloud_metadata/provider_hetzner_cloud.go
  libbeat/processors/add_cloud_metadata/provider_hetzner_cloud_test.go
  libbeat/processors/add_cloud_metadata/providers.go
Labels: needs_team

#35480 [IIS] Remove beta warning from application_pool metricset
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/iis/application_pool/application_pool.go
Labels: Team:Service-Integrations

#35538 Add post-dependabot GH action to update NOTICE.txt
  .github/dependabot.yml
  .github/workflows/post-dependabot.yml
Labels: automation, Team:Elastic-Agent-Data-Plane

#35548 [updatecli] update elastic stack version for testing 8.7.2-3ff44d96
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35547 [updatecli] update elastic stack version for testing 7.17.11-835d340b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35549 .github/workflows/post-dependabot.yml - Fix invalid job name
  .github/workflows/post-dependabot.yml
Labels: automation, Team:Elastic-Agent-Data-Plane

#35403 [updatecli] update elastic stack version for testing 8.9.0-554074dc
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35550 .github/workflows/post-dependabot.yml - Allow write contents
  .github/workflows/post-dependabot.yml
Labels: automation, Team:Elastic-Agent-Data-Plane

#35430 x-pack/filebeat/input/awss3 - Add clarifying comment on optional inputMetrics
  x-pack/filebeat/input/awss3/metrics.go
  x-pack/filebeat/input/awss3/s3.go
  x-pack/filebeat/input/awss3/s3_objects.go
  x-pack/filebeat/input/awss3/sqs.go
  x-pack/filebeat/input/awss3/sqs_s3_event.go
Labels: Filebeat, Team:Security-External Integrations, Team:Cloud-Monitoring

#35541 packetbeat: fix handling of npcap.never_install configuration options from fleet
  CHANGELOG.next.asciidoc
  packetbeat/beater/install_npcap.go
  packetbeat/beater/install_npcap_test.go
  packetbeat/npcap/npcap.go
Labels: bug, Packetbeat, Team:Security-External Integrations, 8.9-candidate, backport-v8.8.0

#35501 retry pip upgrade
  dev-tools/mage/pytest.go
Labels: Team:Elastic-Agent-Control-Plane, bugfix

#34624 Fix mongodb multiple hosts connection issue
  CHANGELOG-developer.next.asciidoc
  metricbeat/docs/modules/mongodb.asciidoc
  metricbeat/module/mongodb/_meta/docs.asciidoc
  metricbeat/module/mongodb/collstats/collstats.go
  metricbeat/module/mongodb/dbstats/dbstats.go
  metricbeat/module/mongodb/dbstats/dbstats_integration_test.go
  metricbeat/module/mongodb/docker-compose.yml
  metricbeat/module/mongodb/metrics/metrics.go
  metricbeat/module/mongodb/mongodb.go
  metricbeat/module/mongodb/mongodb_test.go
  metricbeat/module/mongodb/replstatus/replstatus.go
  metricbeat/module/mongodb/replstatus/replstatus_integration_test.go
  metricbeat/module/mongodb/status/status.go
  metricbeat/module/mongodb/status/status_integration_test.go
Labels: Team:Automation, Team:Service-Integrations

#35524 docs: Prepare Changelog for 8.8.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#35564 [updatecli] update elastic stack version for testing 8.8.0-b66548ac
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35506 ci: retry DRA in a new CI runner
  .ci/packaging.groovy
Labels: automation, Team:Automation, backport-v8.7.0, backport-v8.8.0

#35553 [DOCS] Add instructions to verify Docker install images
  libbeat/docs/shared-docker.asciidoc
Labels: docs, Team:Docs, backport-v8.8.0

#35555 make test fqdn lookup deterministic
  libbeat/processors/add_host_metadata/add_host_metadata_test.go
Labels: Team:Elastic-Agent-Data-Plane, bugfix

#35558 Activemq metricbeat - Updated documentation to add space between words
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/activemq.asciidoc
  x-pack/metricbeat/module/activemq/_meta/docs.asciidoc
Labels: Team:Service-Integrations

#35570 make TestDefaultHarvesterGroup test deterministic
  filebeat/input/filestream/internal/input-logfile/harvester_test.go
Labels: Team:Elastic-Agent-Data-Plane, bugfix

#35575 [updatecli] update elastic stack version for testing 8.7.2-1098350b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35576 [updatecli] update elastic stack version for testing 7.17.11-97b4b531
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35577 [updatecli] update elastic stack version for testing 8.8.0-e7f7cdfa
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35540 [AWS] Collect metrics from linked accounts
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/billing/billing.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
Labels: Team:Cloud-Monitoring

#35584 x-pack/filebeat/docs/inputs/cel: update for mito@v1.2.0
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: docs, Filebeat, Team:Security-External Integrations, backport-skip, bugfix, 8.9-candidate

#35551 [Heartbeat] Remove synthetics support for ironbank
  dev-tools/packaging/files/ironbank/heartbeat/signatures/RPM-GPG-KEY-CentOS-Official
  dev-tools/packaging/files/ironbank/heartbeat/signatures/RPM-GPG-KEY-rockyofficial
  dev-tools/packaging/files/ironbank/heartbeat/signatures/linux_signing_key.pub
  dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile
  dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml
  x-pack/heartbeat/ironbank/Makefile
Labels: Team:Uptime, cleanup, Team:Automation, release-note:skip, backport-v7.17.0, backport-v8.7.0, backport-v8.8.0

#35224 [Release] Update test environments for 8.8.1
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#35594 Remove extra changelog entries
  CHANGELOG.next.asciidoc
Labels: needs_team

#35581 sync filebeat system auth dataset with system integration
  CHANGELOG.next.asciidoc
  filebeat/module/system/auth/ingest/pipeline.yml
  filebeat/module/system/auth/test/secure-rhel7.log-expected.json
  filebeat/module/system/auth/test/test.log
  filebeat/module/system/auth/test/test.log-expected.json
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-v8.8.0

#35601 [Backport] [8.6] [34406] Clarify usage of kubernetes pod labels
  libbeat/docs/shared-autodiscover.asciidoc
Labels: backport, Team:Docs, v8.6.0

#35608 [updatecli] update elastic stack version for testing 8.7.2-81170f47
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35609 [updatecli] update elastic stack version for testing 7.17.11-6ec6183f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35613 [updatecli] update elastic stack version for testing 8.8.1-8b995292
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#34874 [Azure] Sanitize message in case of malformed json
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/azureeventhub/config.go
  x-pack/filebeat/input/azureeventhub/input.go
  x-pack/filebeat/input/azureeventhub/sanitization.go
  x-pack/filebeat/input/azureeventhub/sanitization_test.go
Labels: Team:Cloud-Monitoring

#35182 [Processor: add_cloud_metadata] Use AWS client to get instance metadata and EKS cluster name
  .pre-commit-config.yaml
  CHANGELOG.next.asciidoc
  NOTICE.txt
  dev-tools/kubernetes/Tiltfile
  go.mod
  libbeat/processors/add_cloud_metadata/generic_fetcher.go
  libbeat/processors/add_cloud_metadata/provider_aws_ec2.go
  libbeat/processors/add_cloud_metadata/provider_aws_ec2_test.go
Labels: Team:Elastic-Agent

#35372 x-pack/filebeat/input/cel: provide XML decoding functionality
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/config.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35250 Fix input reload under Elastic-Agent
  CHANGELOG.next.asciidoc
  Jenkinsfile
  filebeat/input/log/input.go
  libbeat/common/errors.go
  x-pack/filebeat/magefile.go
  x-pack/filebeat/tests/integration/framework_test.go
  x-pack/filebeat/tests/integration/input_reload_test.go
  x-pack/libbeat/management/config.go
  x-pack/libbeat/management/input_reload_test.go
  x-pack/libbeat/management/managerV2.go
  x-pack/libbeat/management/managerV2_test.go
  x-pack/libbeat/management/test_utils.go
Labels: Team:Automation, Team:Elastic-Agent

#35621 Add changelog for #31767
  CHANGELOG.next.asciidoc
Labels: docs, needs_team, backport-v8.8.0

#35625 mod,x-pack/filebeat/docs/inputs/cel: update version of github.com/elastic/mito to v1.3.0
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35559 x-pack/filebeat/input/cel: mark as GA
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/input.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.9-candidate
