Repository elastic/beats, pull requests merged in 2023-06, with the labels that each got.

#35392 [filebeat][httpjson] Add http metrics to httpjson input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/input_cursor.go
  x-pack/filebeat/input/httpjson/input_stateless.go
  x-pack/filebeat/input/httpjson/metrics.go
  x-pack/filebeat/input/httpjson/metrics_test.go
  x-pack/filebeat/input/httpjson/request.go
  x-pack/filebeat/input/httpjson/request_chain_helper.go
  x-pack/filebeat/input/httpjson/request_chain_helper_test.go
  x-pack/filebeat/input/httpjson/request_test.go
  x-pack/filebeat/input/httpjson/response.go
  x-pack/filebeat/input/internal/httplog/roundtripper.go
Labels: enhancement, Filebeat, Team:Security-External Integrations

#35630 Make sure k8s watchers close when closing k8s meta processor
  CHANGELOG.next.asciidoc
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
Labels: backport, Team:Cloudnative-Monitoring, v8.9.0, 8.9-candidate, 8.9 candidate

#35604 Add CRC validation to Zoom module
  .github/CODEOWNERS
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/zoom.asciidoc
  x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/input/http_endpoint/config.go
  x-pack/filebeat/input/http_endpoint/handler_test.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/module/zoom/_meta/config.yml
  x-pack/filebeat/module/zoom/_meta/docs.asciidoc
  x-pack/filebeat/module/zoom/webhook/config/webhook.yml
  x-pack/filebeat/module/zoom/webhook/manifest.yml
  x-pack/filebeat/modules.d/zoom.yml.disabled
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip

#35545 CODEOWNER update for obs-infraobs-integrations.
  .github/CODEOWNERS
Labels: enhancement, Team:Integrations, Team:Elastic-Agent

#35634 CI: unit testing of Auditbeat and Packetbeat on RHEL9
  auditbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: enhancement, ci, Team:Automation, Team:Security-External Integrations

#33585 [metricbeat] [azure] migrate to new azure sdk
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/docs/modules/azure.asciidoc
  x-pack/metricbeat/module/azure/_meta/docs.asciidoc
  x-pack/metricbeat/module/azure/billing/client.go
  x-pack/metricbeat/module/azure/billing/client_test.go
  x-pack/metricbeat/module/azure/billing/data.go
  x-pack/metricbeat/module/azure/billing/data_test.go
  x-pack/metricbeat/module/azure/billing/mock_service.go
  x-pack/metricbeat/module/azure/billing/service.go
  x-pack/metricbeat/module/azure/client.go
  x-pack/metricbeat/module/azure/client_test.go
  x-pack/metricbeat/module/azure/client_utils.go
  x-pack/metricbeat/module/azure/client_utils_test.go
  x-pack/metricbeat/module/azure/config.go
  x-pack/metricbeat/module/azure/mock_service.go
  x-pack/metricbeat/module/azure/monitor/client_helper.go
  x-pack/metricbeat/module/azure/monitor/client_helper_test.go
  x-pack/metricbeat/module/azure/monitor/monitor_test.go
  x-pack/metricbeat/module/azure/monitor_service.go
  x-pack/metricbeat/module/azure/service_interface.go
  x-pack/metricbeat/module/azure/storage/client_helper.go
  x-pack/metricbeat/module/azure/storage/client_helper_test.go
  x-pack/metricbeat/module/azure/storage/storage_test.go
Labels: Team:Cloud-Monitoring

#35643 [updatecli] update elastic stack version for testing 7.17.11-a516d267
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35648 [AWS] Add include_linked_accounts config parameter for ListMetrics API
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/aws/_meta/config.reference.yml
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/aws.go
  x-pack/metricbeat/module/aws/billing/billing.go
  x-pack/metricbeat/module/aws/billing/billing_integration_test.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: Team:Cloud-Monitoring, backport-v8.8.0

#35605 [filebeat][gcs] Fix for concurrency issues and context timeouts in the GCS input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/gcs/input.go
  x-pack/filebeat/input/gcs/input_stateless.go
  x-pack/filebeat/input/gcs/input_test.go
  x-pack/filebeat/input/gcs/job.go
  x-pack/filebeat/input/gcs/scheduler.go
  x-pack/filebeat/input/gcs/state.go
Labels: Team:Security-External Integrations, bugfix, backport-v8.8.0

#35647 libbeat/monitoring/inputmon: log key, id and input type when registering/deregistering metrics
  CHANGELOG-developer.next.asciidoc
  libbeat/monitoring/inputmon/input.go
Labels: enhancement, libbeat, Team:Security-External Integrations, Team:Elastic-Agent, 8.9-candidate, backport-v8.8.0

#35674 [filebeat][gcs] - Enhanced context passing and added scheduler debug logs
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/gcs/input.go
  x-pack/filebeat/input/gcs/input_stateless.go
  x-pack/filebeat/input/gcs/scheduler.go
Labels: enhancement, Team:Security-External Integrations, backport-v8.8.0, 8.9 candidate

#35660 Add `include_message` to the parser config validation
  CHANGELOG.next.asciidoc
  libbeat/reader/parser/parser.go
  libbeat/reader/parser/parser_test.go
Labels: needs_team, backport-v8.8.0

#35684 Make Beats tech leads the owners of go.mod.
  .github/CODEOWNERS
Labels: Team:Elastic-Agent-Data-Plane, backport-v8.8.0

#35683 [updatecli] update elastic stack version for testing 7.17.11-50dd0ed0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35657 [updatecli] update elastic stack version for testing 8.8.1-67054589
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35599 [updatecli] update elastic stack version for testing 8.9.0-b4b9b632
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35637 filebeat/input/tcp: fix call to get unspecified IPv6 addresses
  CHANGELOG.next.asciidoc
  filebeat/input/tcp/input.go
  filebeat/input/udp/input.go
  filebeat/tests/system/test_tcp.py
  filebeat/tests/system/test_udp.py
  libbeat/tests/system/config/libbeat.yml.j2
Labels: bug, Filebeat, Team:Security-External Integrations, 8.9-candidate, backport-v8.8.0

#35692 x-pack/filebeat/docs/inputs/http_endpoint: Note that `crc.secret` is required in http_endpoint docs
  x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
Labels: enhancement, docs, Filebeat, Team:Security-External Integrations, backport-skip

#35489 [Packetbeat] Add AF_PACKET metrics
  CHANGELOG.next.asciidoc
  packetbeat/_meta/config/beat.reference.yml.tmpl
  packetbeat/beater/processor.go
  packetbeat/config/config.go
  packetbeat/docs/packetbeat-options.asciidoc
  packetbeat/docs/protocol-metrics-packetbeat.asciidoc
  packetbeat/packetbeat.reference.yml
  packetbeat/sniffer/afpacket.go
  packetbeat/sniffer/afpacket_linux.go
  packetbeat/sniffer/sniffer.go
  x-pack/packetbeat/packetbeat.reference.yml
Labels: enhancement, Packetbeat, Team:Security-External Integrations, backport-v8.8.0

#35667 Feature/improve tests syntax
  CHANGELOG-developer.next.asciidoc
  filebeat/tests/load/load.py
  filebeat/tests/open-file-handlers/log_file.py
Labels: Team:Elastic-Agent, backport-v7.17.0, backport-v8.8.0

#35478 x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta: new package
  CHANGELOG-developer.next.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35703 [updatecli] update elastic stack version for testing 8.9.0-f5346fd1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35619 Create A Diagnostic Callback interface for Metricsets
  libbeat/cfgfile/list.go
  libbeat/cfgfile/list_test.go
  libbeat/common/diagnostics/diagnostics.go
  libbeat/common/diagnostics/helpers.go
  libbeat/common/reload/reload.go
  metricbeat/beater/metricbeat.go
  metricbeat/mb/module/factory.go
  metricbeat/mb/module/runner.go
  metricbeat/mb/module/runner_group.go
  metricbeat/mb/module/runner_group_test.go
  metricbeat/mb/module/runner_test.go
  metricbeat/module/system/core/core.go
  metricbeat/module/system/cpu/cpu.go
  metricbeat/module/system/diskio/diskio.go
  metricbeat/module/system/filesystem/filesystem.go
  metricbeat/module/system/fsstat/fsstat.go
  metricbeat/module/system/memory/memory.go
  x-pack/libbeat/management/managerV2.go
Labels: enhancement, Team:Elastic-Agent

#35698 [Heartbeat] Add nil check to diagnostics processor serializer
  CHANGELOG.next.asciidoc
  libbeat/publisher/processing/default.go
  libbeat/publisher/processing/default_test.go
Labels: bug, Team:Uptime, Team:Elastic-Agent, backport-v8.8.0

#35513 [metricbeat] add healthcheck to docker-compose for integ tests
  metricbeat/module/postgresql/docker-compose.yml
Labels: Team:Integrations, bugfix

#35614 [Filebeat] Add metrics for `gcp-pubsub` input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-gcp-pubsub.asciidoc
  x-pack/filebeat/input/gcppubsub/input.go
  x-pack/filebeat/input/gcppubsub/metrics.go
  x-pack/filebeat/input/gcppubsub/pubsub_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip

#35710 [updatecli] update elastic stack version for testing 8.8.1-e731bb3f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35711 [updatecli] update elastic stack version for testing 7.17.11-ba9a7d5f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35695 [Release] Prepare Changelog for 8.8.1
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#35716 [Heartbeat] Add abort to internal trace
  heartbeat/beater/heartbeat.go
  heartbeat/tracer/tracer.go
  heartbeat/tracer/tracer_test.go
Labels: enhancement, Heartbeat, Team:Uptime, v8.9.0

#35138 x-pack/filebeat/input/httpjson: add benchmarks
  CHANGELOG-developer.next.asciidoc
  x-pack/filebeat/input/httpjson/input_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35676 [Release] Update version to 8.8.2
  libbeat/version/version.go
Labels: release, Team:Automation

#35520 x-pack/filebeat/input/awss3: relax queue_url constraints for non-standard endpoints
  CHANGELOG-developer.next.asciidoc
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/config_test.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35644 [AWS] Fix provider name in debug log message
  x-pack/libbeat/common/aws/credentials.go
Labels: cleanup, Team:Cloud-Monitoring

#35677 [Release] Update test environments for 8.8.2
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#35475 [AWS S3 input] Add support in s3 input for JSON with array of objects
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/s3_objects.go
  x-pack/filebeat/input/awss3/s3_objects_test.go
  x-pack/filebeat/input/awss3/testdata/array.json
Labels: Team:Cloud-Monitoring

#35720 [updatecli] update elastic stack version for testing 8.8.1-d9afcd4f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35636 [Heartbeat] Update gval to latest version to improve Heartbeat JSON parsing
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: enhancement, Heartbeat, Team:Uptime, cleanup, :uptime, Team:Elastic-Agent

#35723 dependabot - Segment by responsible team
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: automation, Team:Security-External Integrations, backport-skip, Team:Elastic-Agent-Data-Plane, Team:Service-Integrations

#35693 Add doc-site-branch to version.asciidoc
  dev-tools/mage/settings.go
  libbeat/docs/version.asciidoc
Labels: docs, Team:Elastic-Agent

#35729 [filebeat][gcs] - Fixed the source of max workers in scheduler
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/gcs/scheduler.go
Labels: Team:Security-External Integrations, bugfix

#35726 x-pack/filebeat/input/httpjson: fix benchmarks
  x-pack/filebeat/input/httpjson/input_test.go
  x-pack/filebeat/input/httpjson/metrics_test.go
Labels: bug, Filebeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35640 [libbeat][reader][parquet] - Updated Apache Arrow library from v11 to v12.0.1
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/libbeat/reader/parquet/parquet.go
  x-pack/libbeat/reader/parquet/parquet_test.go
  x-pack/libbeat/reader/parquet/testdata/cloudtrail.json
  x-pack/libbeat/reader/parquet/testdata/cloudtrail.ndjson
  x-pack/libbeat/reader/parquet/testdata/route53.json
  x-pack/libbeat/reader/parquet/testdata/route53.ndjson
  x-pack/libbeat/reader/parquet/testdata/vpc_flow.json
  x-pack/libbeat/reader/parquet/testdata/vpc_flow.ndjson
Labels: Team:Security-External Integrations, bugfix, 8.9 candidate

#35747 [updatecli] update elastic stack version for testing 8.8.2-3ed30946
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35746 [updatecli] update elastic stack version for testing 7.17.11-777002b0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35665 Fix include_linked_accounts documentation
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
Labels: Team:Cloud-Monitoring, backport-v8.8.0

#35724 auditbeat/module/file_integrity: remove garbled PE executable test file
  CHANGELOG-developer.next.asciidoc
  auditbeat/module/file_integrity/exeobjparser_test.go
  auditbeat/module/file_integrity/testdata/garble_pe_executable
Labels: enhancement, Auditbeat, Team:Security-External Integrations, 8.9-candidate, backport-v8.8.0, unfortunate

#35207 Handle empty sysmon DNS answer data
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml
  x-pack/winlogbeat/module/sysmon/test/testdata/collection/sysmon-no-evtx.evtx.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-10.2-dns.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-11-filedelete.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-11-filedeletedetected.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-11-registry.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-12-loadimage.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-12-processcreate.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-13-clipboardchange.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-13-processtampering.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-9.01.golden.json
  x-pack/winlogbeat/module/sysmon/test/testdata/ingest/sysmon-no-evtx.golden.json
  x-pack/winlogbeat/module/testing.go
Labels: enhancement, Winlogbeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35719 Set the unit unhealthy if output fails to start
  CHANGELOG.next.asciidoc
  x-pack/filebeat/tests/integration/framework_test.go
  x-pack/filebeat/tests/integration/managerV2_test.go
  x-pack/libbeat/management/managerV2.go
  x-pack/libbeat/management/managerV2_test.go
Labels: bug, Team:Elastic-Agent

#35757 x-pack/filebeat/module/panw Fix url scheme grok pattern
  CHANGELOG-developer.next.asciidoc
  x-pack/filebeat/module/panw/panos/ingest/pipeline.yml
  x-pack/filebeat/module/panw/panos/test/pan_inc_threat.log
  x-pack/filebeat/module/panw/panos/test/pan_inc_threat.log-expected.json
Labels: Filebeat, Team:Security-External Integrations, bugfix, backport-v8.8.0

#35686 [AWS] Change include_linked_accounts default value to true
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/aws.go
Labels: Team:Cloud-Monitoring

#35736 Fix race in FQDN values during startup
  libbeat/features/features.go
  libbeat/features/features_test.go
  libbeat/processors/add_host_metadata/add_host_metadata.go
  libbeat/processors/add_host_metadata/add_host_metadata_test.go
  libbeat/processors/add_host_metadata/config.go
Labels: bug, Team:Elastic-Agent-Control-Plane

#35751 [Automation] Bump Golang version to 1.19.10
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  auditbeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
Labels: backport-skip, Team:Elastic-Agent-Data-Plane, backport-v8.8.0

#35768 [updatecli] update elastic stack version for testing 7.17.11-e46e5ca7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35728 [Heartbeat] Fix race condition in scheduler tests
  heartbeat/scheduler/scheduler_test.go
Labels: bug, Team:Uptime, release-note:skip, failed-test, backport-v8.8.0

#35777 Onboard repository in Buildkite
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  catalog-info.yaml
Labels: ci, needs_team, release-note:skip, backport-v7.17.0, backport-v8.8.0

#35785 Revert "[8.8](backport #35751) [Automation] Bump Golang version to 1.…
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  auditbeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
Labels: needs_team

#35789 Remove 32-bit architectures from build scripts and support code
  .ci/packaging.groovy
  Jenkinsfile
  dev-tools/mage/godaemon.go
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgdeps.go
  dev-tools/mage/platforms.go
  docs/devguide/contributing.asciidoc
  libbeat/scripts/Makefile
  packetbeat/scripts/mage/build.go
  packetbeat/scripts/mage/pcap.go
  x-pack/packetbeat/magefile.go
Labels: bug, Team:Automation, Team:Elastic-Agent, backport-v8.8.0

#35240 metricbeat/module/redis: Add TLS and username support for Redis module
  CHANGELOG-developer.next.asciidoc
  metricbeat/docs/modules/redis.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/redis/_meta/config.reference.yml
  metricbeat/module/redis/_meta/config.yml
  metricbeat/module/redis/config.go
  metricbeat/module/redis/metricset.go
  metricbeat/module/redis/metricset_test.go
  metricbeat/module/redis/redis.go
  metricbeat/modules.d/redis.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: enhancement, needs_team

#35787 [updatecli] update elastic stack version for testing 8.8.2-0c8e2646
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35797 [updatecli] update elastic stack version for testing 7.17.11-6470dfa7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35772 filebeat/{tcp,udp}: fix error reporting and IPv6 address handling in metric poller
  CHANGELOG.next.asciidoc
  filebeat/input/tcp/input.go
  filebeat/input/tcp/input_test.go
  filebeat/input/tcp/testdata/proc_net_tcp.txt
  filebeat/input/tcp/testdata/proc_net_tcp6.txt
  filebeat/input/udp/input.go
  filebeat/input/udp/input_test.go
  filebeat/input/udp/testdata/proc_net_udp.txt
  filebeat/input/udp/testdata/proc_net_udp6.txt
Labels: bug, Filebeat, Team:Security-External Integrations, 8.9-candidate, backport-v8.8.0

#35774 x-pack/filebeat/input/cel: update mito version to v1.4.0
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: bug, Filebeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35099 x-pack/metricbeat/module/statsd: Add support for float64 values for metrics of counter type
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/statsd/server/data.go
  x-pack/metricbeat/module/statsd/server/data_test.go
  x-pack/metricbeat/module/statsd/server/registry.go
Labels: needs_team

#35775 Fix condition matching note for kubernetes autodiscovery
  libbeat/docs/shared-autodiscover.asciidoc
Labels: Team:Cloudnative-Monitoring, bugfix, backport-v8.6.0, backport-v8.7.0, backport-v8.8.0

#35819 [updatecli] update elastic stack version for testing 7.17.11-4433090a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35712 [updatecli] update elastic stack version for testing 8.9.0-9ee1e6fb
  testing/environments/snapshot.yml
Labels: automation, Team:Elastic-Agent, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35773 x-pack/filebeat/input/gcppubsub: make metric collection persist beyond construction
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/gcppubsub/input.go
Labels: bug, Filebeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35611 x-pack/filebeat/input/entityanalytics/provider/okta: new package
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc
  x-pack/filebeat/input/entityanalytics/input.go
  x-pack/filebeat/input/entityanalytics/provider/okta/conf.go
  x-pack/filebeat/input/entityanalytics/provider/okta/conf_test.go
  x-pack/filebeat/input/entityanalytics/provider/okta/metrics.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go
  x-pack/filebeat/input/entityanalytics/provider/okta/state_string.go
  x-pack/filebeat/input/entityanalytics/provider/okta/statestore.go
  x-pack/filebeat/input/entityanalytics/provider/okta/statestore_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.9-candidate

#35529 [Filebeat] Add metrics for filestream
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-filestream.asciidoc
  filebeat/input/filestream/environment_test.go
  filebeat/input/filestream/input.go
  filebeat/input/filestream/internal/input-logfile/harvester.go
  filebeat/input/filestream/internal/input-logfile/harvester_test.go
  filebeat/input/filestream/internal/input-logfile/input.go
  filebeat/input/filestream/internal/input-logfile/metrics.go
  filebeat/input/filestream/metrics_integration_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, Team:Elastic-Agent, backport-skip

#35578 [filebeat][awss3] - Added support for parquet decoding and decoder config
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/decoding.go
  x-pack/filebeat/input/awss3/decoding_config.go
  x-pack/filebeat/input/awss3/decoding_test.go
  x-pack/filebeat/input/awss3/s3_objects.go
  x-pack/filebeat/input/awss3/testdata/cloudtrail.json
  x-pack/filebeat/input/awss3/testdata/cloudtrail.parquet
  x-pack/filebeat/input/awss3/testdata/vpc-flow.gz.parquet
Labels: Team:Security-External Integrations, 8.9 candidate

#35831 [updatecli] update elastic stack version for testing 8.8.2-6bda6fd3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35830 [updatecli] update elastic stack version for testing 7.17.11-8753e430
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#33459 [Metricbeat] GCP update compute metadata API
  NOTICE.txt
  go.mod
  go.sum
  x-pack/metricbeat/module/gcp/metrics/compute/metadata.go
Labels: Team:Cloud-Monitoring, 8.9-candidate

#35820 Fix panic when MaxRetryInterval is specified, but RetryInterval is not
  CHANGELOG.next.asciidoc
  libbeat/publisher/queue/diskqueue/config.go
Labels: Team:Elastic-Agent, backport-v7.17.0, backport-v8.8.0

#35780 Upgrade to Go 1.19.10 and handle changes in golang Debian base image
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  auditbeat/Dockerfile
  dev-tools/mage/pytest.go
  dev-tools/mage/target/integtest/integtest.go
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  libbeat/tests/system/requirements.txt
  libbeat/tests/system/requirements_aix.txt
  metricbeat/Dockerfile
  metricbeat/magefile.go
  metricbeat/module/aerospike/_meta/Dockerfile
  metricbeat/module/haproxy/_meta/Dockerfile
  metricbeat/module/kafka/_meta/Dockerfile
  metricbeat/module/mongodb/_meta/Dockerfile
  metricbeat/module/munin/_meta/Dockerfile
  metricbeat/module/rabbitmq/_meta/Dockerfile
  packetbeat/Dockerfile
  testing/environments/docker/kafka/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/metricbeat/magefile.go
Labels: Team:Elastic-Agent, backport-v7.17.0, backport-v8.8.0

#35812 Bump elastic-agent-autodiscover agent to 0.6.2
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent

#35821 [kibana] update audit pipeline
  filebeat/docs/fields.asciidoc
  filebeat/module/kibana/_meta/fields.yml
  filebeat/module/kibana/audit/config/audit.yml
  filebeat/module/kibana/audit/ingest/pipeline-json.yml
  filebeat/module/kibana/audit/ingest/pipeline.yml
  filebeat/module/kibana/audit/test/test-audit-711.log-expected.json
  filebeat/module/kibana/audit/test/test-audit-713.log-expected.json
  filebeat/module/kibana/audit/test/test-audit-890.log
  filebeat/module/kibana/audit/test/test-audit-890.log-expected.json
  filebeat/module/kibana/fields.go
Labels: Team:Infra Monitoring UI, Module:kibana, v8.9.0

#35852 Disable failing activemq tests
  x-pack/metricbeat/module/activemq/test_activemq.py
Labels: Team:Services, backport-v7.17.0, backport-v8.8.0

#35859 [updatecli] update elastic stack version for testing 8.8.2-c9f8756a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35807 x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher: add device handling
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/azuread/azure.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/azure_test.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/device.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/device_test.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/fetcher.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph_test.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/group.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/mock/mock.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/statestore.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/statestore_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, 8.9-candidate, backport-v8.9.0

#35870 [Release] update version to next minor 8.10.0
  libbeat/version/version.go
  x-pack/filebeat/tests/integration/managerV2_test.go
Labels: in progress, release, automation, Team:Automation

#35872 [Release] Update test environment to 8.10.0
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: in progress, release, automation, Team:Automation, backport-v8.9.0

#35875 Update references to ubuntu-18 in 7.x
  dev-tools/Jenkinsfile.yml
  generator/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
Labels: bug, Team:Elastic-Agent

#35843 Fix double fetch
  CHANGELOG.next.asciidoc
  x-pack/heartbeat/monitors/browser/browser.go
  x-pack/heartbeat/monitors/browser/source/project.go
  x-pack/heartbeat/monitors/browser/source/project_test.go
  x-pack/heartbeat/monitors/browser/sourcejob.go
  x-pack/heartbeat/monitors/browser/sourcejob_test.go
Labels: bug, Team:Uptime, v8.9.0, backport-v8.9.0

#35885 Update renaming arm labels
  auditbeat/Jenkinsfile.yml
  filebeat/Jenkinsfile.yml
  heartbeat/Jenkinsfile.yml
  libbeat/Jenkinsfile.yml
  metricbeat/Jenkinsfile.yml
  packetbeat/Jenkinsfile.yml
  x-pack/auditbeat/Jenkinsfile.yml
  x-pack/dockerlogbeat/Jenkinsfile.yml
  x-pack/elastic-agent/Jenkinsfile.yml
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/functionbeat/Jenkinsfile.yml
  x-pack/heartbeat/Jenkinsfile.yml
  x-pack/libbeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
  x-pack/packetbeat/Jenkinsfile.yml
Labels: Team:Elastic-Agent, backport-skip

#35890 [updatecli] update elastic stack version for testing 8.8.2-363ffebd
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35788 [Heartbeat] filter dev flags inside synthetics args
  CHANGELOG.next.asciidoc
  x-pack/heartbeat/monitors/browser/sourcejob.go
  x-pack/heartbeat/monitors/browser/sourcejob_test.go
Labels: bug, Team:Uptime, backport-v8.8.0

#35892 filebeat/inputs/journald - Document cursor_seek_fallback, add seek test
  filebeat/docs/inputs/input-journald.asciidoc
  filebeat/input/journald/input_filtering_test.go
Labels: docs, Filebeat, backport-skip, Team:Elastic-Agent-Data-Plane

#35697 all: Fix grammatical mistakes in `*.tmpl` files
  auditbeat/_meta/config/auditbeat.config.modules.yml.tmpl
  auditbeat/auditbeat.reference.yml
  auditbeat/auditbeat.yml
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
  dev-tools/packaging/templates/windows/install-service.ps1.tmpl
  filebeat/_meta/config/filebeat.global.reference.yml.tmpl
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/_meta/config/filebeat.inputs.yml.tmpl
  filebeat/filebeat.reference.yml
  filebeat/filebeat.yml
  heartbeat/_meta/config/beat.reference.yml.tmpl
  heartbeat/_meta/config/beat.yml.tmpl
  heartbeat/heartbeat.reference.yml
  heartbeat/heartbeat.yml
  libbeat/_meta/config.yml.tmpl
  libbeat/_meta/config/general.reference.yml.tmpl
  libbeat/_meta/config/general.yml.tmpl
  libbeat/_meta/config/http.reference.yml.tmpl
  libbeat/_meta/config/logging.reference.yml.tmpl
  libbeat/_meta/config/logging.yml.tmpl
  libbeat/_meta/config/monitoring.reference.yml.tmpl
  libbeat/_meta/config/monitoring.yml.tmpl
  libbeat/_meta/config/output-elasticsearch.reference.yml.tmpl
  libbeat/_meta/config/processors.reference.yml.tmpl
  libbeat/_meta/config/setup.dashboards.reference.yml.tmpl
  libbeat/_meta/config/setup.dashboards.yml.tmpl
  libbeat/_meta/config/setup.ilm.reference.yml.tmpl
  metricbeat/metricbeat.reference.yml
  metricbeat/metricbeat.yml
  metricbeat/scripts/module/metricset/metricset.go.tmpl
  packetbeat/_meta/config/beat.reference.yml.tmpl
  packetbeat/packetbeat.reference.yml
  packetbeat/packetbeat.yml
  winlogbeat/winlogbeat.reference.yml
  winlogbeat/winlogbeat.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/auditbeat/auditbeat.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/filebeat.yml
  x-pack/functionbeat/_meta/config/beat.reference.yml.tmpl
  x-pack/functionbeat/_meta/config/beat.yml.tmpl
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/functionbeat/functionbeat.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/heartbeat/heartbeat.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/metricbeat.yml
  x-pack/osquerybeat/_meta/config/beat.docker.yml.tmpl
  x-pack/osquerybeat/_meta/config/beat.reference.yml.tmpl
  x-pack/osquerybeat/_meta/config/beat.yml.tmpl
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/osquerybeat/osquerybeat.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/packetbeat/packetbeat.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.yml
Labels: Team:Elastic-Agent

#35898 [updatecli] update elastic stack version for testing 8.8.2-c7e9ae2e
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35658 filebeat/input/filestream - Fix registry cleaner log message
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/internal/input-logfile/clean.go
  filebeat/input/v2/compat/compat.go
Labels: bug, Filebeat, Team:Elastic-Agent-Data-Plane

#35897 [updatecli] update elastic stack version for testing 8.9.0-46e5f4bc
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35908 [updatecli] update elastic stack version for testing 8.8.2-652417ba
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35903 x-pack/filebeat/input/http_endpoint: make sure address is removed on server closure
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/http_endpoint/input_test.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#35886 Tests for exposing filestream metrics together with log input metrics #35835
  filebeat/input/filestream/legacy_metrics_integration_test.go
  filebeat/magefile.go
  libbeat/tests/integration/framework.go
  x-pack/filebeat/tests/integration/framework_test.go
  x-pack/filebeat/tests/integration/managerV2_test.go
Labels: Team:Elastic-Agent

#35919 Make all docker images consistent for future updates
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  metricbeat/module/http/_meta/Dockerfile
  metricbeat/module/nats/_meta/Dockerfile
  metricbeat/module/vsphere/_meta/Dockerfile
  x-pack/metricbeat/module/stan/_meta/Dockerfile
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-v7.17.0, backport-v8.8.0

#35924 [updatecli] update elastic stack version for testing 8.8.2-33f1abe8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35925 [updatecli] update elastic stack version for testing 7.17.11-ee6563d4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35926 [updatecli] update elastic stack version for testing 8.9.0-0be0aa36
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35921 Adding prealloc linter rule
  .golangci.yml
Labels: needs_team

#35907 Enable `7.x` DRA builds
  .ci/packaging.groovy
Labels: needs_team

#35931 Include all Dockerfiles that use Golang into the bump job
  .ci/bump-golang.yml
Labels: enhancement, Team:Automation, backport-skip, Team:Elastic-Agent-Data-Plane

#35942 Add separate Golan Bump job for 7.17
  .ci/bump-golang-7.17.yml
  .github/workflows/bump-golang.yml
Labels: enhancement, Team:Automation, backport-skip, Team:Elastic-Agent-Data-Plane

#35948 [updatecli] update elastic stack version for testing 8.8.2-438a24ff
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35947 [updatecli] update elastic stack version for testing 8.9.0-efd868fc
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35915 x-pack/filebeat/input/cel: use structpb.Struct as intermediate type
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/cel/input.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.10-candidate

#35940 Update Docker images that are not included in the automation
  filebeat/Dockerfile
  filebeat/magefile.go
  libbeat/Dockerfile
  x-pack/filebeat/magefile.go
  x-pack/libbeat/Dockerfile
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#35862 docs: update docs versions 8.8.2
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#35939 docs: Prepare Changelog for 8.8.2
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, forwardport-main

#35864 [Release] Update version to 8.8.3
  libbeat/version/version.go
Labels: release, Team:Automation

#35950 docs: Prepare Changelog for 7.17.11
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, forwardport-main

#35946 Updated protobuf to 1.29.1
  NOTICE.txt
  go.mod
  go.sum
Labels: needs_team, backport-v7.17.0

#35853 docs: update docs versions 7.17.11
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#35865 [Release] Update test environments for 8.8.3
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#35854 [Release] Update version to 7.17.12
  libbeat/version/version.go
Labels: release, Team:Automation

#35855 [Release] Update test environments for 7.17.12
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#35951 Remove NOTE about port in Cloud ID
  libbeat/docs/output-cloud.asciidoc
Labels: docs, Team:Docs

#35969 [updatecli] update elastic stack version for testing 8.8.2-41f17f3c
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35967 [updatecli] update elastic stack version for testing 7.17.11-670b6a4a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35968 [updatecli] update elastic stack version for testing 8.9.0-dd1f0db2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35976 [updatecli] update elastic stack version for testing 8.8.2-ba369b11
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call
