Repository elastic/beats, pull requests merged in 2023-07, with the labels that each got.

#35985 [updatecli] update elastic stack version for testing 8.8.3-1f4ea904
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35986 [updatecli] update elastic stack version for testing 8.9.0-024bad78
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35972 [filebeat] Check for duplicate ID for filestream metrics
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/internal/input-logfile/input.go
  filebeat/input/filestream/internal/input-logfile/manager.go
Labels: bug, Filebeat, Team:Elastic-Agent, backport-v8.9.0

#35991 [updatecli] update elastic stack version for testing 8.8.3-dcc440f7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35992 [updatecli] update elastic stack version for testing 8.9.0-872b2eab
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35994 Added verification fallback to https://artifacts.elastic.co/GPG-KEY-elastic-agent
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download_test.go
Labels: backport, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane

#35829 [updatecli] update elastic stack version for testing 8.10.0-18649b44
  testing/environments/snapshot.yml
Labels: automation, Team:Elastic-Agent, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36001 [updatecli] update elastic stack version for testing 8.9.0-55dfeb9a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35997 x-pack/filebeat/docs/inputs: fix copy paste error
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: bug, docs, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#36002 [updatecli] update elastic stack version for testing 8.8.3-9428e7c2
  testing/environments/snapshot.yml
Labels: needs_team

#35999 Introducing Deployment condition status metric in Kubernetes module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_deployment/_meta/data.json
  metricbeat/module/kubernetes/state_deployment/_meta/fields.yml
  metricbeat/module/kubernetes/state_deployment/_meta/test/ksm.v2.4.2.plain.expected
  metricbeat/module/kubernetes/state_deployment/_meta/test/ksm.v2.5.0.plain.expected
  metricbeat/module/kubernetes/state_deployment/_meta/test/ksm.v2.6.0.plain.expected
  metricbeat/module/kubernetes/state_deployment/_meta/test/ksm.v2.7.0.plain.expected
  metricbeat/module/kubernetes/state_deployment/_meta/testdata/docs.plain-expected.json
  metricbeat/module/kubernetes/state_deployment/_meta/testdata/ksm.v2.4.2.plain-expected.json
  metricbeat/module/kubernetes/state_deployment/_meta/testdata/ksm.v2.5.0.plain-expected.json
  metricbeat/module/kubernetes/state_deployment/_meta/testdata/ksm.v2.6.0.plain-expected.json
  metricbeat/module/kubernetes/state_deployment/_meta/testdata/ksm.v2.7.0.plain-expected.json
  metricbeat/module/kubernetes/state_deployment/state_deployment.go
  metricbeat/module/prometheus/collector/_meta/data.json
Labels: Team:Cloudnative-Monitoring

#36004 [doc] Add defaults for filebeat udp input.
  filebeat/docs/inputs/input-common-udp-options.asciidoc
Labels: docs, Team:Docs, backport-v8.8.0, backport-v8.9.0

#36006 Do not print context canceled errors
  CHANGELOG.next.asciidoc
  x-pack/libbeat/management/managerV2.go
Labels: enhancement, Team:Elastic-Agent, backport-v8.9.0

#36003 [updatecli] update elastic stack version for testing 8.10.0-0d099cfb
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35996 filebeat/input/{tcp,udp}: use correct address list in udp
  CHANGELOG.next.asciidoc
  filebeat/input/tcp/input.go
  filebeat/input/udp/input.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#36027 x-pack/filebeat/module/fortinet: remove NUL bytes from log lines
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/fortinet/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/fortinet/firewall/test/event-nul.log
  x-pack/filebeat/module/fortinet/firewall/test/event-nul.log-expected.json
Labels: bug, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#36031 Fix k8s test versions
  .ci/scripts/kind-setup.sh
  Jenkinsfile
  deploy/kubernetes/Jenkinsfile.yml
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/module/kubernetes/_meta/docs.asciidoc
  metricbeat/module/kubernetes/test/integration.go
Labels: Team:Automation

#36040 [updatecli] update elastic stack version for testing 7.17.12-a5bf8147
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35977 Fix rollover handling in system/network host data
  metricbeat/module/system/network/network.go
  metricbeat/module/system/network/network_test.go
  metricbeat/module/system/network/tests/rollover/proc/net/dev
  metricbeat/module/system/network/tests/rollover2/proc/net/dev
  metricbeat/module/system/network/tests/rollover32/proc/net/dev
  metricbeat/module/system/network/tests/rollover32_2/proc/net/dev
  metricbeat/module/system/network/tests/testdata/proc/net/dev
  metricbeat/module/system/network/tests/testdata2/proc/net/dev
  metricbeat/module/system/network/tests/testdata3/proc/net/dev
Labels: Team:Elastic-Agent

#36008 x-pack/filebeat/input/cel: make redact configuration recommended
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/config.go
  x-pack/filebeat/input/cel/config_test.go
  x-pack/filebeat/input/cel/input_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#35920 Remove logger outside of WriteJSONKeys
  libbeat/beat/event.go
  libbeat/common/jsontransform/expand.go
  libbeat/common/jsontransform/jsonhelper.go
  libbeat/common/jsontransform/jsonhelper_test.go
  libbeat/processors/actions/decode_json_fields.go
Labels: enhancement, libbeat, needs_team, backport-skip

#36050 Update docs.asciidoc
  metricbeat/module/system/filesystem/_meta/docs.asciidoc
Labels: docs, Team:Docs

#36039 [updatecli] update elastic stack version for testing 8.8.3-b2365b79
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36053 [updatecli] update elastic stack version for testing 8.9.0-a302929e
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36052 [updatecli] update elastic stack version for testing 7.17.12-18dff279
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35928 Improve StreamBuf append
  CHANGELOG.next.asciidoc
  libbeat/common/streambuf/streambuf.go
Labels: enhancement, Team:Elastic-Agent, backport-skip

#36047 Remove deprecate message for flag that wasn't deprecated
  metricbeat/internal/sysinit/init.go
Labels: bug, Team:Elastic-Agent

#35945 Decrease Clones
  CHANGELOG.next.asciidoc
  libbeat/beat/event.go
  libbeat/beat/event_test.go
Labels: enhancement, needs_team, backport-skip

#36058 [updatecli] update elastic stack version for testing 7.17.12-3f1ad8e1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36060 [updatecli] update elastic stack version for testing 8.9.0-53fadbe2
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35806 Filebeat mqtt add cleansession
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-mqtt.asciidoc
  filebeat/input/mqtt/client.go
  filebeat/input/mqtt/config.go
Labels: Team:Elastic-Agent, backport-skip, >enhancement

#36067 [updatecli] update elastic stack version for testing 8.9.0-905e99b1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36068 [updatecli] update elastic stack version for testing 7.17.12-c78d45be
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36063 x-pack/filebeat/docs/inputs/cel: fix copy paste error
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: bug, docs, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#36041 [updatecli] update elastic stack version for testing 8.10.0-464beb1d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36073 Make fingerprinting faster
  filebeat/input/filestream/fswatch.go
  filebeat/input/filestream/fswatch_test.go
Labels: enhancement, Filebeat, Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#36065 Add file system information to each event
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/fswatch_test.go
  filebeat/input/filestream/identifier.go
  filebeat/input/filestream/identifier_fingerprint.go
  filebeat/input/filestream/identifier_inode_deviceid.go
  filebeat/input/filestream/input.go
  filebeat/input/filestream/prospector_test.go
  libbeat/reader/readfile/fs_metafields_other.go
  libbeat/reader/readfile/fs_metafields_windows.go
  libbeat/reader/readfile/metafields.go
  libbeat/reader/readfile/metafields_other_test.go
  libbeat/reader/readfile/metafields_test.go
  libbeat/reader/readfile/metafields_windows_test.go
Labels: enhancement, Filebeat, backport-skip, Team:Elastic-Agent-Data-Plane

#36054 [awss3][automation] Fix skipping aws tests in automation
  Jenkinsfile
  x-pack/filebeat/input/awss3/input_integration_test.go
Labels: ci, Team:Automation, Team:Elastic-Agent, Team:Cloud-Monitoring, bugfix, backport-v8.9.0

#36078 Add benchmarks for scanning files
  filebeat/input/filestream/fswatch_test.go
Labels: Filebeat, Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#36091 Pin PyYAML version to 5.3.1 to avoid CI errors temporarily
  CHANGELOG-developer.next.asciidoc
  libbeat/tests/system/requirements.txt
  libbeat/tests/system/requirements_aix.txt
  metricbeat/Dockerfile
  metricbeat/module/kubernetes/_meta/terraform/eks/requirements.txt
Labels: bug, needs_team, backport-v7.17.0

#36034 x-pack/filebeat/input/awss3: fix priority of region name configurations
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_test.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#36084 [updatecli] update elastic stack version for testing 8.9.0-446d2070
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36082 [updatecli] update elastic stack version for testing 7.17.12-d37f924b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36045 Update docker documentation example for dbus in system metrics
  metricbeat/docs/running-on-docker.asciidoc
Labels: docs, Team:Elastic-Agent

#36116 [updatecli] update elastic stack version for testing 8.9.0-164e5e60
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36106 Set providers parameter in config to aws for provider_aws_ec2_test.go
  libbeat/processors/add_cloud_metadata/provider_aws_ec2_test.go
Labels: Team:Cloud-Monitoring

#36108 x-pack/filebeat/processors/decode_def/cef: relax size constraint on network bytes
  CHANGELOG.next.asciidoc
  x-pack/filebeat/processors/decode_cef/cef/cef_test.go
  x-pack/filebeat/processors/decode_cef/cef/keys.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.10-candidate

#36126 Support build of projects outside of beats directory
  CHANGELOG.next.asciidoc
  dev-tools/mage/build.go
Labels: enhancement, needs_team, backport-skip

#36129 [updatecli] update elastic stack version for testing 8.9.0-5732cdbc
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36130 [updatecli] update elastic stack version for testing 7.17.12-4a94a841
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36089 Fix ndjson parser to store JSON fields correctly under `target`
  CHANGELOG.next.asciidoc
  libbeat/reader/parser/parser_test.go
  libbeat/reader/readjson/json.go
Labels: Team:Elastic-Agent

#36107 x-pack/filebeat/input/cel: make now global static per evaluation
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#36137 [updatecli] update elastic stack version for testing 7.17.12-5a5017c5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36036 [filebeat][httpjson]- Added min & max functions to the template engine
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/texttemplate.go
  x-pack/filebeat/input/httpjson/value_tpl.go
  x-pack/filebeat/input/httpjson/value_tpl_test.go
Labels: enhancement, Team:Security-External Integrations, 8.10-candidate

#36140 Adding 8.6.2 changelog to 8.7 branch
  CHANGELOG.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, Team:Elastic-Agent

#36144 [updatecli] update elastic stack version for testing 7.17.12-624c085e
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36143 [updatecli] update elastic stack version for testing 8.9.0-911df49b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36101 x-pack/filebeat/input/awss3 ; Fix nil hit panic when a getter is invoked on input metric
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/metrics.go
  x-pack/filebeat/input/awss3/metrics_test.go
  x-pack/filebeat/input/awss3/sqs.go
Labels: Filebeat, Team:Security-External Integrations, Team:Cloud-Monitoring, bugfix, backport-v8.9.0

#36092 x-pack/filebeat/input/entityanalytics/provider/azuread: add registered owner/user handling
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/azuread/azure.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/device.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/device_test.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.10-candidate

#36139 x-pack/filebeat/docs/inputs/cel: use attributes for mito doc links
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: enhancement, docs, Team:Security-External Integrations, backport-skip, 8.10-candidate

#36127 docs: Prepare Changelog for 7.17.12
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#36128 docs: Prepare Changelog for 8.9.0
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, forwardport-main

#36112 docs: update docs versions 7.17.12
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#36113 [Release] Update version to 7.17.13
  libbeat/version/version.go
Labels: release, Team:Automation

#35868 [Release] Update version to 8.9.1
  libbeat/version/version.go
Labels: release, Team:Automation

#36146 x-pack/filebeat/input/cel: update mito version to v1.5.0
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.10-candidate

#36152 x-pack/filebeat/docs/inputs/cel: add a text API example
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: docs, Filebeat, Team:Security-External Integrations, backport-skip, 8.10-candidate

#36114 [Release] Update test environments for 7.17.13
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#36160 [Filebeat][Salesforce] Add CODEOWNER for salesforce as obs-infraobs-integrations
  .github/CODEOWNERS
Labels: Team:Obs-InfraObs

#36162 [updatecli] update elastic stack version for testing 8.9.0-6b15bb32
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35727 x-pack/filebeat/input/awss3[integration test]Test integration tests on localstack
  .ci/jobs/docker-compose.yml
  .ci/scripts/docker-services-cleanup.sh
  .ci/scripts/install-docker-services.sh
  CHANGELOG.next.asciidoc
  Jenkinsfile
  x-pack/filebeat/input/awss3/_meta/terraform/.gitignore
  x-pack/filebeat/input/awss3/_meta/terraform/README.md
  x-pack/filebeat/input/awss3/_meta/terraform/localstack.tf
  x-pack/filebeat/input/awss3/_meta/terraform/outputs.tf
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_integration_test.go
Labels: Filebeat, Team:Automation, Team:Security-External Integrations, backport-skip, Team:Elastic-Agent-Data-Plane, Team:Cloud-Monitoring, >enhancement, 8.10-candidate

#36142 [Azure Billing] Update forecast api metrics interval
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/billing/billing.go
  x-pack/metricbeat/module/azure/billing/billing_test.go
Labels: needs_team

#35408 filebeat/input/journald: allow specifying since when to read journald entries
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-journald.asciidoc
  filebeat/input/journald/config.go
  filebeat/input/journald/config_test.go
  filebeat/input/journald/input.go
  filebeat/input/journald/input_filtering_test.go
  filebeat/input/journald/pkg/journalread/mode.go
  filebeat/input/journald/pkg/journalread/mode_test.go
  filebeat/input/journald/pkg/journalread/reader.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.10-candidate

#36000 upgrade Go to 1.20.6
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  Vagrantfile
  auditbeat/Dockerfile
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  dev-tools/mage/gotest.go
  dev-tools/mage/gotest_test.go
  filebeat/input/syslog/format_check.go
  filebeat/input/syslog/rfc3164_parser.go
  filebeat/input/syslog/rfc5424_parser.go
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  libbeat/reader/syslog/rfc3164_test.go
  libbeat/reader/syslog/rfc5424_test.go
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  metricbeat/module/nats/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/metricbeat/module/stan/_meta/Dockerfile
Labels: enhancement, Team:Elastic-Agent, backport-skip, 8.10-candidate

#36167 Update PULL_REQUEST_TEMPLATE.md - Update checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs, Team:Elastic-Agent

#35959 Convert some libbeat python tests to go
  filebeat/input/filestream/legacy_metrics_integration_test.go
  libbeat/magefile.go
  libbeat/tests/integration/base_test.go
  libbeat/tests/integration/ca_pinning_test.go
  libbeat/tests/integration/cmd_completion_test.go
  libbeat/tests/integration/cmd_export_config_test.go
  libbeat/tests/integration/cmd_keystore_test.go
  libbeat/tests/integration/cmd_setup_index_management_test.go
  libbeat/tests/integration/cmd_test.go
  libbeat/tests/integration/cmd_version_test.go
  libbeat/tests/integration/dashboard_test.go
  libbeat/tests/integration/framework.go
  libbeat/tests/integration/http_test.go
  libbeat/tests/integration/logging_test.go
  libbeat/tests/integration/meta_test.go
  libbeat/tests/integration/template_test.go
  libbeat/tests/integration/testdata/testbeat-dashboards.zip
  libbeat/tests/integration/testdata/testbeat-no-dashboards.zip
  libbeat/tests/system/test_base.py
  libbeat/tests/system/test_ca_pinning.py
  libbeat/tests/system/test_cmd_completion.py
  libbeat/tests/system/test_cmd_export_config.py
  libbeat/tests/system/test_cmd_keystore.py
  libbeat/tests/system/test_cmd_test.py
  libbeat/tests/system/test_cmd_version.py
  libbeat/tests/system/test_dashboard.py
  libbeat/tests/system/test_http.py
  libbeat/tests/system/test_logging.py
  libbeat/tests/system/test_meta.py
  libbeat/tests/system/test_template.py
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#36158 dependabot: skip github.com/elastic/mito auto updates
  .github/dependabot.yml
  CHANGELOG-developer.next.asciidoc
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.10-candidate

#36169 [filebeat][httpjson] - Fix input metric name
  CHANGELOG-developer.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/metrics.go
Labels: Team:Security-External Integrations, bugfix, backport-v8.9.0

#36171 Update elastic-agent-client to support diagnostics changes
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent

#36179 Skip TestFetch as Flaky
  metricbeat/module/postgresql/statement/statement_integration_test.go
Labels: flaky-test, Team:Obs-InfraObs, backport-v8.9.0

#36184 [updatecli] update elastic stack version for testing 8.9.1-44a814f0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36178 x-pack/winlogbeat/module/powershell: improve details regexp pattern performance
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/powershell/ingest/powershell.yml
  x-pack/winlogbeat/module/powershell/ingest/powershell_operational.yml
Labels: bug, Winlogbeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0
