Repository elastic/beats, pull requests merged in 2023-08, with the labels that each got.

#35935 packetbeat/beater: make Npcap installation lazy
  CHANGELOG.next.asciidoc
  packetbeat/_meta/config/windows_npcap.yml.tmpl
  packetbeat/beater/install_npcap.go
  packetbeat/beater/install_npcap_test.go
  packetbeat/beater/packetbeat.go
  packetbeat/beater/processor.go
  packetbeat/docs/packetbeat-options.asciidoc
Labels: bug, Packetbeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#36182 metricbeat/module/postgresql: Improve healthcheck for Postgres
  metricbeat/module/postgresql/docker-compose.yml
  metricbeat/module/postgresql/statement/statement_integration_test.go
Labels: bug, needs_team

#36157 [DOCS] Advise users to migrate from Filebeat to Elastic Agent
  filebeat/docs/modules.asciidoc
Labels: docs, Filebeat, Team:Docs, backport-v8.0.0, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v8.4.0, backport-v8.5.0, backport-v8.6.0, backport-v8.7.0, backport-v8.8.0, backport-v8.9.0

#36163 Documenting metrics messages in Beats logs
  auditbeat/docs/troubleshooting.asciidoc
  filebeat/docs/troubleshooting.asciidoc
  heartbeat/docs/troubleshooting.asciidoc
  libbeat/docs/metrics-in-logs.asciidoc
  metricbeat/docs/troubleshooting.asciidoc
  packetbeat/docs/troubleshooting.asciidoc
  winlogbeat/docs/troubleshooting.asciidoc
  x-pack/functionbeat/docs/troubleshooting.asciidoc
Labels: docs, Team:Docs, Team:Elastic-Agent, backport-skip

#36210 [updatecli] update elastic stack version for testing 8.9.1-877ad540
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36209 [updatecli] update elastic stack version for testing 7.17.13-7f46ddb9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36204 [DOCS] Remove unneeded breaking changes pages
  libbeat/docs/index.asciidoc
  libbeat/docs/release-notes/breaking/breaking-7.17.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.0.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.1.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.2.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.3.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.4.asciidoc
  libbeat/docs/release-notes/breaking/breaking-8.5.asciidoc
  libbeat/docs/release-notes/breaking/breaking.asciidoc
  libbeat/docs/release-notes/redirects.asciidoc
Labels: docs, Team:Docs, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v8.5.0, backport-v8.6.0, backport-v8.7.0, v8.10.0, backport-v8.8.0, backport-v8.9.0

#36229 [updatecli] update elastic stack version for testing 7.17.13-f0591b59
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36216 Allow manually triggering the golang bump
  .github/workflows/bump-golang.yml
Labels: Team:Elastic-Agent

#36228 [updatecli] update elastic stack version for testing 8.9.1-40dca293
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36103 [updatecli] update elastic stack version for testing 8.10.0-ed2e01b4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36205 github: unify PR description and commit message
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Team:Security-External Integrations, Team:Elastic-Agent-Data-Plane

#36124 [filebeat][azure-blob-storage] - Fixed concurrency & flakey tests issue
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/azureblobstorage/input.go
  x-pack/filebeat/input/azureblobstorage/input_test.go
  x-pack/filebeat/input/azureblobstorage/job.go
  x-pack/filebeat/input/azureblobstorage/mock/data_random.go
  x-pack/filebeat/input/azureblobstorage/mock/mock.go
  x-pack/filebeat/input/azureblobstorage/state.go
Labels: Team:Security-External Integrations, bugfix, 8.10-candidate

#36183 Report status per unit
  CHANGELOG.next.asciidoc
  libbeat/cfgfile/list.go
  libbeat/common/reload/reload.go
  x-pack/libbeat/management/input_reload_test.go
  x-pack/libbeat/management/managerV2.go
  x-pack/libbeat/management/managerV2_test.go
Labels: Team:Elastic-Agent

#36237 Changelog: adding 8.7.0 and 8.7.1 to release-notes.html
  libbeat/docs/release.asciidoc
Labels: docs, Team:Elastic-Agent

#36201 Restart Beat after install on deb package
  CHANGELOG.next.asciidoc
  dev-tools/packaging/files/linux/systemd-daemon-reload.sh
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/deb/postinstall.sh.tmpl
Labels: Team:Elastic-Agent

#36193 [Heartbeat] Add default TZ to heartbeat docker images
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: bug, Team:Uptime, release-note:skip, backport-v8.9.0

#36234 Fix bump-golang job failing to update Dockerfiles.
  .ci/bump-golang-7.17.yml
  .ci/bump-golang.yml
Labels: Team:Automation, Team:Elastic-Agent

#36240 x-pack/filebeat/processors/decode_cef - Improve docs
  x-pack/filebeat/processors/decode_cef/docs/decode_cef.asciidoc
Labels: enhancement, docs, :Processors, Team:Security-External Integrations, backport-v8.9.0

#36244 Fix the 7.17 Go version bump script.
  .ci/bump-golang-7.17.yml
Labels: Team:Automation, Team:Elastic-Agent

#36241 [Automation] Bump Golang version to 1.20.7
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  auditbeat/Dockerfile
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  go.mod
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  metricbeat/module/nats/_meta/Dockerfile
  metricbeat/module/vsphere/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/metricbeat/module/stan/_meta/Dockerfile
Labels: Team:Elastic-Agent, backport-skip, backport-v8.9.0

#36187 fix flaky integration tests
  libbeat/tests/integration/framework.go
  libbeat/tests/integration/template_test.go
Labels: flaky-test, Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane

#36242 [updatecli] update elastic stack version for testing 8.9.1-6c14de65
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36173 [Winlogbeat] Add missing query while reading .evtx file
  CHANGELOG.next.asciidoc
  winlogbeat/eventlog/wineventlog.go
  winlogbeat/eventlog/wineventlog_experimental.go
  winlogbeat/eventlog/wineventlog_test.go
Labels: Winlogbeat, Team:Security-External Integrations, backport-v7.17.0, bugfix, 8.10-candidate

#36258 [Heartbeat] enable rhel9 on ci
  heartbeat/Jenkinsfile.yml
Labels: Team:Uptime, ci, release-note:skip, backport-skip

#36263 [updatecli] update elastic stack version for testing 8.9.1-d46182aa
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36256 Filter out duplicate paths resolved from matching globs
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/fswatch.go
  filebeat/input/filestream/fswatch_test.go
Labels: bug, Filebeat, Team:Elastic-Agent-Data-Plane, backport-v7.17.0

#36266 Removing e2e tests from packaging as it has been removed
  .ci/packaging.groovy
Labels: :Testing, Team:Automation, Team:Elastic-Agent

#36271 x-pack/filebeat/input/cel: improve error reporting from Test run
  x-pack/filebeat/input/cel/input.go
Labels: bug, Filebeat, Team:Security-External Integrations, backport-skip, 8.10-candidate

#36261 Revert "Restart Beat after install on deb package"
  CHANGELOG.next.asciidoc
  dev-tools/packaging/files/linux/systemd-daemon-reload.sh
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/deb/postinstall.sh.tmpl
Labels: Team:Elastic-Agent

#36276 [updatecli] update elastic stack version for testing 8.9.1-ef89186d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36191 [Heartbeat] Deprecate aws_elb provider
  CHANGELOG.next.asciidoc
  libbeat/docs/shared-autodiscover.asciidoc
  x-pack/libbeat/autodiscover/providers/aws/elb/provider.go
Labels: Team:Uptime, cleanup, release-note:deprecation, Team:Elastic-Agent

#36188 dev-tools/packaging/templates/rpm: add warning when /etc/rc.d/init.d/functions is missing
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/rpm/elastic-agent.init.sh.tmpl
  dev-tools/packaging/templates/rpm/init.sh.tmpl
Labels: Packetbeat, Auditbeat, Team:Security-External Integrations, backport-v7.17.0, 8.10-candidate, backport-v8.9.0

#36280 libbeat/processors/translate_sid: mark as generally available
  CHANGELOG.next.asciidoc
  libbeat/processors/translate_sid/docs/translate_sid.asciidoc
Labels: libbeat, Team:Security-External Integrations, backport-skip, 8.10-candidate

#35980 x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta: add device handling
  CHANGELOG-developer.next.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go
Labels: Filebeat, Team:Security-External Integrations, backport-skip, 8.10-candidate

#36283 [updatecli] update elastic stack version for testing 8.9.1-afb401d4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#35688 x-pack/metricbeat/module/sql: Add option to execute SQL queries for all databases
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/sql.asciidoc
  metricbeat/helper/sql/sql.go
  x-pack/metricbeat/module/sql/_meta/docs.asciidoc
  x-pack/metricbeat/module/sql/docker-compose.yml
  x-pack/metricbeat/module/sql/query/query.go
  x-pack/metricbeat/module/sql/query/test_sql_mssql.py
Labels: enhancement, Team:Elastic-Agent, Team:Service-Integrations, Team:Obs-InfraObs

#36287 filebeat/input/{tcp,udp}: fix resolution of device address during metric initialisation
  CHANGELOG.next.asciidoc
  filebeat/input/internal/procnet/procnet.go
  filebeat/input/internal/procnet/procnet_test.go
  filebeat/input/tcp/input.go
  filebeat/input/tcp/input_test.go
  filebeat/input/udp/input.go
  filebeat/input/udp/input_test.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#36297 [updatecli] update elastic stack version for testing 8.9.1-975bdf3e
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36274 [elasticsearch] support api_key
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/elasticsearch.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/elasticsearch/_meta/config-xpack.yml
  metricbeat/module/elasticsearch/_meta/config.reference.yml
  metricbeat/module/elasticsearch/_meta/config.yml
  metricbeat/module/elasticsearch/metricset.go
  metricbeat/module/elasticsearch/node/node_test.go
  metricbeat/modules.d/elasticsearch-xpack.yml.disabled
  metricbeat/modules.d/elasticsearch.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: enhancement, Team:Infra Monitoring UI, Module:elasticsearch, v8.10.0

#36303 Make naming consistent with the main branch
  filebeat/input/filestream/fswatch_test.go
  filebeat/input/filestream/identifier.go
  filebeat/input/filestream/identifier_fingerprint.go
  filebeat/input/filestream/identifier_inode_deviceid.go
  filebeat/input/filestream/prospector_test.go
Labels: enhancement, Filebeat, Team:Elastic-Agent-Data-Plane

#36273 [filebeat][httpjson] - Added support for Okta Oauth2 provider
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/config_auth.go
  x-pack/filebeat/input/httpjson/config_okta_auth.go
  x-pack/filebeat/input/httpjson/config_test.go
Labels: Filebeat, Team:Security-External Integrations, 8.10-candidate

#36308 x-pack/filebeat/module/juniper: fix handling of jrx structured data
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/juniper/srx/ingest/pipeline.yml
  x-pack/filebeat/module/juniper/srx/test/flow.log
  x-pack/filebeat/module/juniper/srx/test/flow.log-expected.json
Labels: bug, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#36301 Update elastic-agent-client to 7.3.0
  NOTICE.txt
  go.mod
  go.sum
Labels: dependency, backport-skip, Team:Elastic-Agent-Data-Plane

#35938 [O11y][Salesforce] Add support of the `interval` parameter in Salesforce `setupaudittrail-rest` fileset.
  CHANGELOG.next.asciidoc
  filebeat/docs/modules/salesforce.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/module/salesforce/_meta/config.yml
  x-pack/filebeat/module/salesforce/_meta/docs.asciidoc
  x-pack/filebeat/modules.d/salesforce.yml.disabled
Labels: enhancement, Filebeat, Team:Elastic-Agent

#36049 x-pack/filebeat/input/entityanalytics/provider/okta: add device handling
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/okta/conf.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go
  x-pack/filebeat/input/entityanalytics/provider/okta/statestore.go
  x-pack/filebeat/input/entityanalytics/provider/okta/statestore_test.go
Labels: enhancement, Filebeat, Team:Security-External Integrations, backport-skip, 8.10-candidate

#36304 Fix flaky fswatch test due to non-deterministic order
  filebeat/input/filestream/fswatch_test.go
Labels: bug, backport-skip, Team:Elastic-Agent-Data-Plane

#36208 x-pack/filebeat/input/awss3 Add AWS Endpoint resolver
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/config_test.go
  x-pack/filebeat/input/awss3/input.go
Labels: Team:Automation, Team:Security-External Integrations, Team:Cloud-Monitoring, 8.10-candidate, backport-v8.9.0

#36315 [updatecli] update elastic stack version for testing 7.17.13-1b4d0dba
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36316 [updatecli] update elastic stack version for testing 8.9.1-456ef5ad
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36243 [updatecli] update elastic stack version for testing 8.10.0-0aabd193
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36309 winlogbeat/sys/wineventlog: don't use strict mode for forwarded events
  winlogbeat/eventlog/wineventlog.go
  winlogbeat/eventlog/wineventlog_experimental.go
Labels: bug, Winlogbeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0

#35739 [Azure] Add input metrics to the azure-eventhub input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-azure-eventhub.asciidoc
  x-pack/filebeat/input/azureeventhub/eph.go
  x-pack/filebeat/input/azureeventhub/input.go
  x-pack/filebeat/input/azureeventhub/input_test.go
  x-pack/filebeat/input/azureeventhub/metrics.go
  x-pack/filebeat/input/azureeventhub/metrics_test.go
  x-pack/filebeat/input/azureeventhub/sanitization_test.go
Labels: enhancement, Team:Cloud-Monitoring

#36133 Osquerybeat: Upgrade to osquery 5.8.2
  x-pack/osquerybeat/internal/distro/distro.go
Labels: Team:Asset Mgt, backport-skip, >enhancement, v8.10.0

#36328 [updatecli] update elastic stack version for testing 8.9.1-162a595c
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36329 [updatecli] update elastic stack version for testing 7.17.13-7c96d528
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36326 x-pack/filebeat/module/cisco Fix Cisco module Grok pattern
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml
Labels: bug, Team:Security-External Integrations, backport-v8.9.0

#36331 Add more dimensions to allowedDimensions for azure storage account to…
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/storage/storage.go
Labels: Team:Obs-InfraObs

#36345 .github/dependabot.yml - Revert team based segmentation
  .github/dependabot.yml
Labels: backport-skip, Team:Elastic-Agent-Data-Plane, dependabot

#36344 [updatecli] update elastic stack version for testing 8.9.1-39dfdc3b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36337 Fix linting error with receiver names
  libbeat/esleg/eslegclient/enc.go
Labels: cleanup, backport-skip, Team:Elastic-Agent-Data-Plane

#36342 [Release] Update docs for the 8.11.0 release
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#36310 auditbeat/module/file_integrity: add support for selinux and posix_acl_access xattrs
  CHANGELOG.next.asciidoc
  NOTICE.txt
  auditbeat/module/file_integrity/event.go
  auditbeat/module/file_integrity/event_test.go
  auditbeat/module/file_integrity/fileinfo_posix.go
  auditbeat/module/file_integrity/flatbuffers.go
  auditbeat/module/file_integrity/schema.fbs
  auditbeat/module/file_integrity/schema/Metadata.go
  go.mod
  go.sum
Labels: enhancement, Auditbeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.10.0

#36351 auditbeat/module/file_integrity: encode POSIXACLAccess as []byte
  auditbeat/module/file_integrity/event.go
  auditbeat/module/file_integrity/fileinfo_posix.go
  auditbeat/module/file_integrity/flatbuffers.go
  auditbeat/module/file_integrity/schema.fbs
  auditbeat/module/file_integrity/schema/Metadata.go
Labels: enhancement, Auditbeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.10.0

#36254 ironbank: update the list of maintainers for the ironbank
  dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml
Labels: Team:Automation, backport-v7.17.0, backport-v8.9.0, backport-v8.10.0

#36335 docs: Prepare Changelog for 8.9.1
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, forwardport-main

#36333 [Release] Update version to 8.9.2
  libbeat/version/version.go
Labels: release, Team:Automation

#36358 x-pack/filebeat/input/azureblobstorage: reduce tested maximum worker load
  x-pack/filebeat/input/azureblobstorage/input_test.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.10.0

#36354 Fix last release version and current version
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
  libbeat/version/version.go
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Elastic-Agent

#36341 [Release] update version to next minor 8.11.0
  libbeat/version/version.go
Labels: in progress, release, automation, Team:Automation

#36366 [updatecli] update elastic stack version for testing 8.9.1-f33bc992
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36343 [Release] Update test environment to 8.11.0
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: in progress, release, automation, Team:Automation, backport-v8.10.0

#35955 force newer version of k8s.io
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/input/azureblobstorage/client.go
  x-pack/filebeat/input/azureblobstorage/job.go
  x-pack/filebeat/input/azureblobstorage/scheduler.go
Labels: Team:Security-External Integrations

#36238 libbeat/tests/compose: Fix conflict in container creation for integration tests
  libbeat/tests/compose/compose.go
  libbeat/tests/compose/project.go
  libbeat/tests/compose/wrapper.go
Labels: bug, containers, ci, Team:Elastic-Agent

#36370 [updatecli] update elastic stack version for testing 7.17.13-dde9c3ba
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36334 [Release] Update test environments for 8.9.2
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#36282 [filebeat][httpjson] Reduce HTTP metrics allocations
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/metrics_test.go
  x-pack/filebeat/input/internal/httplog/roundtripper.go
Labels: enhancement, Team:Security-External Integrations

#36375 [Metricbeat][Kubernetes] Add test metrics family to scheduler, proxy and controller manager
  .github/CODEOWNERS
  metricbeat/helper/kubernetes/ktest/ktest.go
  metricbeat/module/kubernetes/controllermanager/controllermanager_test.go
  metricbeat/module/kubernetes/proxy/proxy_test.go
  metricbeat/module/kubernetes/scheduler/scheduler_test.go
  metricbeat/module/kubernetes/state_container/state_container_test.go
  metricbeat/module/kubernetes/state_cronjob/state_cronjob_test.go
  metricbeat/module/kubernetes/state_daemonset/state_daemonset_test.go
  metricbeat/module/kubernetes/state_deployment/state_deployment_test.go
  metricbeat/module/kubernetes/state_job/state_job_test.go
  metricbeat/module/kubernetes/state_node/state_node_test.go
  metricbeat/module/kubernetes/state_persistentvolume/state_persistentvolume_test.go
  metricbeat/module/kubernetes/state_persistentvolumeclaim/state_persistentvolumeclaim_test.go
  metricbeat/module/kubernetes/state_pod/state_pod_test.go
  metricbeat/module/kubernetes/state_replicaset/state_replicaset_test.go
  metricbeat/module/kubernetes/state_resourcequota/state_resourcequota_test.go
  metricbeat/module/kubernetes/state_service/state_service_test.go
  metricbeat/module/kubernetes/state_statefulset/state_statefulset_test.go
  metricbeat/module/kubernetes/state_storageclass/state_storageclass_test.go
Labels: Team:Cloudnative-Monitoring

#36382 metricbeat - Update stack test version to 8.9.1
  metricbeat/docker-compose.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Metricbeat, needs_team

#36383 [updatecli] update elastic stack version for testing 7.17.13-23b69bf5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36388 x-pack/filebeat/input/cel: don't panic when redact option is not specified
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0, backport-v8.10.0

#36390 Simplify input configuration under Elastic-Agent
  CHANGELOG.next.asciidoc
  x-pack/libbeat/management/generate.go
  x-pack/libbeat/management/simple_input_config_test.go
Labels: Team:Elastic-Agent

#36275 Improve the esleg bulk response parsing
  libbeat/esleg/eslegclient/api.go
  libbeat/esleg/eslegclient/bulkapi.go
  libbeat/esleg/eslegclient/bulkapi_mock_test.go
  libbeat/esleg/eslegclient/connection.go
  libbeat/esleg/eslegclient/connection_test.go
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client_test.go
Labels: enhancement, needs_team, backport-skip

#36397 [updatecli] update elastic stack version for testing 8.9.2-a6da2234
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36401 [updatecli] update elastic stack version for testing 7.17.13-7e207efe
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36365 [updatecli] update elastic stack version for testing 8.10.0-6bf877e8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36407 [updatecli] update elastic stack version for testing 8.10.0-322e3ef7
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36408 [updatecli] update elastic stack version for testing 8.9.2-8eb52857
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36394 dns processor - Add A, AAAA, and TXT query support
  CHANGELOG.next.asciidoc
  libbeat/processors/dns/cache.go
  libbeat/processors/dns/cache_test.go
  libbeat/processors/dns/config.go
  libbeat/processors/dns/dns.go
  libbeat/processors/dns/dns_test.go
  libbeat/processors/dns/doc.go
  libbeat/processors/dns/docs/dns.asciidoc
  libbeat/processors/dns/resolver.go
  libbeat/processors/dns/resolver_test.go
Labels: enhancement, libbeat, :Processors, Team:Security-External Integrations, backport-skip, 8.11-candidate

#36420 [updatecli] update elastic stack version for testing 8.9.2-1a569074
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36418 [updatecli] update elastic stack version for testing 8.10.0-edf31268
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36419 [updatecli] update elastic stack version for testing 7.17.13-f0d1f9e1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36385 x-pack/filebeat/input/internal: split httpmon out of httplog
  CHANGELOG-developer.next.asciidoc
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/internal/httplog/roundtripper.go
  x-pack/filebeat/input/internal/httpmon/roundtripper.go
Labels: Filebeat, cleanup, Team:Security-External Integrations, backport-skip, 8.11-candidate

#36327 [updatecli] update elastic stack version for testing 8.11.0-76b03348
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36417 Mark syslog processor as GA and improve documentation
  CHANGELOG.next.asciidoc
  libbeat/processors/syslog/docs/syslog.asciidoc
Labels: enhancement, docs, libbeat, Team:Security-External Integrations, backport-skip

#36422 Add .devcontainer
  .ci/bump-golang.yml
  .devcontainer/devcontainer.json
Labels: Team:Automation, Team:Elastic-Agent-Data-Plane, backport-v8.10.0

#36431 Upgrade elastic-agent-libs to v0.3.13
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent, backport-v8.9.0, backport-v8.10.0

#36338 [Metricbeat] [GCP] Fix compute metadata
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/gcp/metrics/compute/metadata.go
Labels: Team:Cloud-Monitoring

#36436 [updatecli] update elastic stack version for testing 8.9.2-fe004c3f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36435 [updatecli] update elastic stack version for testing 8.11.0-ba1a8c0f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36290 filebeat/input/internal/procnet: fix typos in test error messages
  filebeat/input/internal/procnet/procnet_test.go
Labels: bug, Filebeat, Team:Security-External Integrations, 8.10-candidate, backport-v8.9.0, backport-v8.10.0

#36386 CODEOWNERS: assign ownership of x-pack/filebeat/input/internal packages
  .github/CODEOWNERS
Labels: Filebeat, cleanup, Team:Security-External Integrations, backport-skip, 8.10-candidate

#36448 [updatecli] update elastic stack version for testing 8.11.0-16180d4a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36451 [updatecli] update elastic stack version for testing 8.9.2-a804d52d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36450 [updatecli] update elastic stack version for testing 7.17.13-1c18dee3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#36428 [Azure] [Billing] Add Azure resource tags from Usage Details API
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/azure/billing/data.go
  x-pack/metricbeat/module/azure/billing/data_test.go
Labels: Team:Cloud-Monitoring

#36452 Fix link to SonicWall Firewall integration docs
  filebeat/docs/modules/sonicwall.asciidoc
  x-pack/filebeat/module/sonicwall/_meta/docs.asciidoc
Labels: docs, Team:Docs, v8.10.0, v8.9.0, backport-v8.9.0, backport-v8.10.0

#36439 x-pack/filebeat/input/httpjson: reorganise code to improve code locality
  x-pack/filebeat/input/httpjson/config_chain.go
  x-pack/filebeat/input/httpjson/config_request.go
  x-pack/filebeat/input/httpjson/config_response.go
  x-pack/filebeat/input/httpjson/encoding.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/input_manager.go
  x-pack/filebeat/input/httpjson/input_test.go
  x-pack/filebeat/input/httpjson/metrics_test.go
  x-pack/filebeat/input/httpjson/pagination.go
  x-pack/filebeat/input/httpjson/request.go
  x-pack/filebeat/input/httpjson/request_chain_helper.go
  x-pack/filebeat/input/httpjson/request_chain_helper_test.go
  x-pack/filebeat/input/httpjson/request_test.go
  x-pack/filebeat/input/httpjson/response.go
  x-pack/filebeat/input/httpjson/split.go
  x-pack/filebeat/input/httpjson/split_test.go
  x-pack/filebeat/input/httpjson/transform.go
  x-pack/filebeat/input/httpjson/transform_registry.go
  x-pack/filebeat/input/httpjson/transform_test.go
Labels: enhancement, Filebeat, cleanup, Team:Security-External Integrations, backport-skip, 8.11-candidate

#36474 golangci.yml: silence invalid linter complaints on use of logp.TestingSetup
  .golangci.yml
Labels: enhancement, Team:Security-External Integrations, backport-skip, 8.11-candidate
