Repository elastic/beats, pull requests merged in 2024-04, with the labels that each got.

#38688 [Release] Update test environments for 8.13.2
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#38698 docs: Prepare Changelog for 8.13.1
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, forwardport-main

#38670 x-pack/filebeat: Update CODEOWNERS for the new Salesforce's filebeat input
  .github/CODEOWNERS
Labels: Team:Ingest-EngProd

#38659 Deploy K8S Pipeline migration
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/auditbeat/generate_auditbeat_pipeline.sh
  .buildkite/auditbeat/scripts/crosscompile.sh
  .buildkite/auditbeat/scripts/unit-tests.sh
  .buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml
  .buildkite/deploy/kubernetes/scripts/install-kind.sh
  .buildkite/deploy/kubernetes/scripts/install-kubectl.sh
  .buildkite/deploy/kubernetes/scripts/kind-setup.sh
  .buildkite/deploy/kubernetes/scripts/make.sh
  .buildkite/deploy/kubernetes/scripts/setup-k8s-env.sh
  .buildkite/env-scripts/env.sh
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/filebeat/generate_filebeat_pipeline.sh
  .buildkite/filebeat/scripts/integration-gotests.sh
  .buildkite/filebeat/scripts/integration-pytests.sh
  .buildkite/filebeat/scripts/unit-tests.sh
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/hooks/pre-command
  .buildkite/pull-requests.json
  .buildkite/scripts/generate_filebeat_pipeline.sh
  .buildkite/scripts/setenv.sh
  auditbeat/module/file_integrity/fileinfo_test.go
  auditbeat/module/file_integrity/metricset_test.go
Labels: macOS, arm, Team:Elastic-Agent, macOSArm, windows-2019, backport-v7.17.0, backport-v8.13.0

#37332 [Metricbeat][Kubernetes] Share watchers between metricsets
  CHANGELOG-developer.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  libbeat/autodiscover/providers/kubernetes/pod_test.go
  metricbeat/helper/kubernetes/state_metricset.go
  metricbeat/module/kubernetes/container/container.go
  metricbeat/module/kubernetes/kubernetes.go
  metricbeat/module/kubernetes/node/node.go
  metricbeat/module/kubernetes/pod/pod.go
  metricbeat/module/kubernetes/state_container/state_container.go
  metricbeat/module/kubernetes/util/kubernetes.go
  metricbeat/module/kubernetes/util/kubernetes_test.go
  x-pack/filebeat/input/internal/httplog/roundtripper.go
Labels: Team:Elastic-Agent, Team:Cloudnative-Monitoring

#38707 [CI] Comment trigger commands for main beats pipeline
  .buildkite/pull-requests.json
Labels: needs_team

#38720 .golangci.yml - Disallow OSS -> x-pack dependencies
  .golangci.yml
Labels: Team:Elastic-Agent

#38583 replace default images
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/auditbeat/generate_auditbeat_pipeline.sh
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/hooks/pre-command
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/scripts/cloud_tests.sh
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_auditbeat_pipeline.sh
  .buildkite/scripts/generate_filebeat_pipeline.sh
  .buildkite/scripts/generate_libbeat_pipeline.sh
  .buildkite/scripts/generate_metricbeat_pipeline.sh
  .buildkite/scripts/generate_packetbeat_pipeline.sh
  .buildkite/scripts/generate_winlogbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_auditbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_dockerlogbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_filebeat_pipeline.sh
  .buildkite/scripts/generate_xpack_heartbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_libbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_metricbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_osquerybeat_pipeline.sh
  .buildkite/scripts/generate_xpack_packetbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_winlogbeat_pipeline.sh
  .buildkite/scripts/go_int_tests.sh
  .buildkite/scripts/packaging/package-step.sh
  .buildkite/scripts/py_int_tests.sh
  .buildkite/scripts/setenv.sh
  .buildkite/scripts/win_unit_tests.ps1
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: x-pack, needs_team, macOS, arm, aws, backport-v7.17.0, backport-v8.12.0, backport-v8.13.0

#38199 [Auditbeat] fim(ebpf): enrich file events with process data
  CHANGELOG.next.asciidoc
  NOTICE.txt
  auditbeat/module/file_integrity/event.go
  auditbeat/module/file_integrity/event_linux.go
  auditbeat/module/file_integrity/event_linux_test.go
  auditbeat/tests/system/test_file_integrity.py
  go.mod
  go.sum
  libbeat/ebpf/sys/sys.go
  libbeat/ebpf/sys/time.go
  libbeat/tests/system/requirements.txt
  libbeat/tests/system/requirements_aix.txt
  metricbeat/Dockerfile
Labels: Team:Elastic-Agent, Team:Security-Linux Platform

#38736 Fix the dynamic step for pipeline upload on the x-pack Heartbeat
  .buildkite/scripts/common.sh
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
Labels: bug, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#36727 [Filebeat][Module][Logstash] Include plugin.id in the plain text log format
  filebeat/module/logstash/log/ingest/pipeline-plaintext.yml
Labels: Feature:Stack Monitoring, needs_team, >enhancement

#38570 [libbeat] Delete proxy queue
  libbeat/outputs/shipper/shipper.go
  libbeat/publisher/queue/proxy/README.md
  libbeat/publisher/queue/proxy/batch.go
  libbeat/publisher/queue/proxy/broker.go
  libbeat/publisher/queue/proxy/diagrams/broker.d2
  libbeat/publisher/queue/proxy/diagrams/broker.svg
  libbeat/publisher/queue/proxy/internal_api.go
  libbeat/publisher/queue/proxy/produce.go
  libbeat/publisher/queue/proxy/queue_test.go
Labels: cleanup, Team:Elastic-Agent

#38728 [Automation][7.17] Bump Golang version to 1.21.9
  .go-version
  .golangci.yml
  auditbeat/Dockerfile
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  filebeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  metricbeat/module/nats/_meta/Dockerfile
  metricbeat/module/vsphere/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
  x-pack/metricbeat/module/stan/_meta/Dockerfile
Labels: Team:Elastic-Agent, backport-skip

#37640 Auditbeat Processor to enrich auditd events with session view information
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/cmd/root.go
  x-pack/auditbeat/processors/sessionmd/add_session_metadata.go
  x-pack/auditbeat/processors/sessionmd/add_session_metadata_test.go
  x-pack/auditbeat/processors/sessionmd/config.go
  x-pack/auditbeat/processors/sessionmd/doc.go
  x-pack/auditbeat/processors/sessionmd/processdb/db.go
  x-pack/auditbeat/processors/sessionmd/processdb/db_test.go
  x-pack/auditbeat/processors/sessionmd/processdb/entry_leader_test.go
  x-pack/auditbeat/processors/sessionmd/procfs/mock.go
  x-pack/auditbeat/processors/sessionmd/procfs/procfs.go
  x-pack/auditbeat/processors/sessionmd/provider/ebpf_provider/ebpf_provider.go
  x-pack/auditbeat/processors/sessionmd/provider/provider.go
  x-pack/auditbeat/processors/sessionmd/timeutils/time.go
  x-pack/auditbeat/processors/sessionmd/timeutils/time_test.go
  x-pack/auditbeat/processors/sessionmd/types/events.go
  x-pack/auditbeat/processors/sessionmd/types/process.go
Labels: enhancement, Auditbeat, Team:Elastic-Agent, backport-skip

#38591 Clean up non-indexable policy handling in the ES output
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client_proxy_test.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/elasticsearch/config_test.go
  libbeat/outputs/elasticsearch/dead_letter_index.go
  libbeat/outputs/elasticsearch/death_letter_selector.go
  libbeat/outputs/elasticsearch/elasticsearch.go
  libbeat/outputs/elasticsearch/elasticsearch_test.go
  libbeat/outputs/elasticsearch/non_indexable_policy.go
Labels: cleanup, Team:Elastic-Agent

#38561 [libbeat] Cache processor docs and memory fixes.
  CHANGELOG.next.asciidoc
  libbeat/processors/cache/docs/cache.asciidoc
  libbeat/processors/cache/file_store.go
  libbeat/processors/cache/file_store_test.go
  libbeat/processors/cache/mem_store.go
  libbeat/processors/cache/mem_store_test.go
Labels: bugfix, Team:Security-Service Integrations, backport-v8.13.0

#38727 [Automation] Bump Golang version to 1.21.9
  .ci/bump-golang.yml
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  auditbeat/Dockerfile
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  go.mod
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  metricbeat/module/nats/_meta/Dockerfile
  metricbeat/module/vsphere/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/metricbeat/module/stan/_meta/Dockerfile
Labels: Team:Automation, Team:Elastic-Agent, backport-skip, backport-v8.13.0

#38521 [updatecli] update elastic stack version for testing 8.14.0-e399a313
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#38709 x-pack/filebeat/module/o365: fix handling of o365.audit.OperationProperties
  CHANGELOG.next.asciidoc
  x-pack/filebeat/module/o365/audit/_meta/fields.yml
  x-pack/filebeat/module/o365/audit/ingest/pipeline.yml
  x-pack/filebeat/module/o365/audit/test/13-dlp-exchange.log-expected.json
  x-pack/filebeat/module/o365/audit/test/stringly-json.log
  x-pack/filebeat/module/o365/audit/test/stringly-json.log-expected.json
  x-pack/filebeat/module/o365/fields.go
Labels: Filebeat, backport-v7.17.0, bugfix, Team:Security-Service Integrations

#38557 [updatecli] update elastic stack version for testing 8.13.2-fcd9deb3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#38471 [Metricbeat][Autodiscover Kubernetes] Fix multiple instances reporting same metrics
  CHANGELOG-developer.next.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/providers/kubernetes/config.go
  libbeat/autodiscover/providers/kubernetes/config_test.go
  libbeat/autodiscover/providers/kubernetes/kubernetes.go
  libbeat/autodiscover/providers/kubernetes/kubernetes_test.go
  libbeat/docs/shared-autodiscover.asciidoc
Labels: Team:Cloudnative-Monitoring, bugfix, backport-v8.13.0

#38765 [updatecli] update elastic stack version for testing 8.13.2-948b05e8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#38328 [Auditbeat] fim(ebpf): enrich file events with container id
  CHANGELOG.next.asciidoc
  NOTICE.txt
  auditbeat/module/file_integrity/event.go
  auditbeat/module/file_integrity/event_linux.go
  auditbeat/module/file_integrity/event_linux_test.go
  go.mod
  go.sum
Labels: enhancement, Team:Security-Linux Platform, backport-v8.13.0

#38771 docs: update docs versions 8.13.2
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#38772 [Release] Update version to 8.13.3
  libbeat/version/version.go
Labels: release, Team:Automation

#38773 [Release] Update test environments for 8.13.3
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#38488 Fix Filestream store GC, entries are now removed when they TTL expires
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/internal/input-logfile/clean.go
  filebeat/input/filestream/internal/input-logfile/store.go
  filebeat/tests/integration/store_test.go
  libbeat/tests/integration/framework.go
Labels: bug, Team:Automation, Team:Elastic-Agent

#38706 [AWS] Fix rds field description aws.rds.cpu.total.pct
  filebeat/docs/fields.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/module/aws/rds/_meta/fields.yml
Labels: Team:obs-ds-hosted-services, backport-v8.12.0, backport-v8.13.0

#38783 Single pipeline entrypoint
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_auditbeat_pipeline.sh
Labels: enhancement, needs_team, backport-v7.17.0, backport-v8.13.0

#38791 [Release] Update test environments for 7.17.21
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#38788 docs: update docs versions 7.17.20
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  filebeat/docs/fields.asciidoc
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#38782 Split windows steps
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/scripts/generate_metricbeat_pipeline.sh
  .buildkite/scripts/generate_packetbeat_pipeline.sh
  .buildkite/scripts/generate_winlogbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_auditbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_dockerlogbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_filebeat_pipeline.sh
  .buildkite/scripts/generate_xpack_heartbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_libbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_metricbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_osquerybeat_pipeline.sh
  .buildkite/scripts/generate_xpack_packetbeat_pipeline.sh
  .buildkite/scripts/generate_xpack_winlogbeat_pipeline.sh
Labels: needs_team, backport-v7.17.0, backport-v8.13.0

#38792 docs: Prepare Changelog for 7.17.20
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#38774 docs: Prepare Changelog for 8.13.2
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, forwardport-main

#38801 Remove the beats pipeline slug from sourcing envs
  .buildkite/hooks/pre-command
Labels: cleanup, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38553 Setting Prometheus Remote_write Period default value to 1m
  CHANGELOG.next.asciidoc
  metricbeat/module/prometheus/remote_write/_meta/docs.asciidoc
  x-pack/metricbeat/module/prometheus/remote_write/config.go
  x-pack/metricbeat/module/prometheus/remote_write/data.go
Labels: Team:Cloudnative-Monitoring, backport-v8.13.0

#38812 Clean BK scripts
  .buildkite/hooks/pre-command
  .buildkite/scripts/common.sh
Labels: cleanup, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38814 Dedicated script for detecting changesets on Buildkite
  .buildkite/scripts/changesets.sh
Labels: backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38816 Remove Buildkite pipeline trigger
  .buildkite/pull-requests.json
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38830 Fix missing vars in buildkite changesets.sh
  .buildkite/scripts/changesets.sh
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38415 Correcting typos in awscloudwatch
  x-pack/filebeat/input/awscloudwatch/config.go
Labels: needs_team

#38572 [libbeat] Implement early event encoding for the Elasticsearch output
  CHANGELOG.next.asciidoc
  libbeat/esleg/eslegclient/enc.go
  libbeat/outputs/console/console.go
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/elasticsearch/dead_letter_index.go
  libbeat/outputs/elasticsearch/elasticsearch.go
  libbeat/outputs/elasticsearch/elasticsearch_test.go
  libbeat/outputs/elasticsearch/event_encoder.go
  libbeat/outputs/elasticsearch/event_encoder_test.go
  libbeat/outputs/fileout/file.go
  libbeat/outputs/kafka/kafka.go
  libbeat/outputs/logstash/logstash.go
  libbeat/outputs/logstash/logstash_integration_test.go
  libbeat/outputs/output_reg.go
  libbeat/outputs/redis/redis.go
  libbeat/outputs/util.go
  libbeat/publisher/event.go
  libbeat/publisher/pipeline/client_test.go
  libbeat/publisher/pipeline/controller.go
  libbeat/publisher/pipeline/controller_test.go
  libbeat/publisher/pipeline/pipeline.go
  libbeat/publisher/pipeline/pipeline_test.go
  libbeat/publisher/pipeline/stress/out.go
  libbeat/publisher/pipeline/ttl_batch_test.go
  libbeat/publisher/queue/diskqueue/benchmark_test.go
  libbeat/publisher/queue/diskqueue/consumer.go
  libbeat/publisher/queue/diskqueue/frames.go
  libbeat/publisher/queue/diskqueue/producer.go
  libbeat/publisher/queue/diskqueue/queue.go
  libbeat/publisher/queue/diskqueue/queue_test.go
  libbeat/publisher/queue/diskqueue/reader_loop.go
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/memqueue/internal_api.go
  libbeat/publisher/queue/memqueue/produce.go
  libbeat/publisher/queue/memqueue/queue_test.go
  libbeat/publisher/queue/memqueue/runloop_test.go
  libbeat/publisher/queue/queue.go
Labels: enhancement, Team:Elastic-Agent

#38790 [Release] Update version to 7.17.21
  libbeat/version/version.go
Labels: release, Team:Automation

#38837 [updatecli] update elastic stack version for testing 8.14.0-3c0002e4
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#38805 Moved deploy-k8s pipeline to central pipeline
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/heartbeat/scripts/integration-gotests.sh
  .buildkite/heartbeat/scripts/integration-pytests.sh
  .buildkite/heartbeat/scripts/unit-tests.sh
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/packaging.sh
Labels: kubernetes, Team:Elastic-Agent, backport-v7.17.0, backport-v8.13.0

#38848 Tool setup for macOS workers on Buildkite
  .buildkite/scripts/install_macos_tools.sh
Labels: ci, Team:Ingest-EngProd

#38843 rename ManifestUrl env var to MANIFEST_URL
  .buildkite/x-pack/elastic-agent/pipeline.xpack.elastic-agent.package.yml
  .buildkite/x-pack/elastic-agent/scripts/steps/package.sh
  dev-tools/mage/settings.go
  x-pack/elastic-agent/magefile.go
Labels: enhancement, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane

#38826 Moved xpack/dockerlogbeat pipeline to central pipeline
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/generate_xpack_dockerlogbeat_pipeline.sh
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
Labels: Team:Elastic-Agent, backport-v7.17.0, backport-v8.13.0

#38827 Move to static BK pipeline for metricbeat
  .buildkite/hooks/pre-command
  .buildkite/metricbeat/pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_metricbeat_pipeline.sh
Labels: :Windows, ci, macOS, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38862 Centralised pipeline xpack/dockerlogbeat fixes
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
Labels: Team:Elastic-Agent, backport-v7.17.0, backport-v8.13.0

#38416 Fix handling of truncated files for Filestream input
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/input.go
  filebeat/tests/integration/filestream_truncation_test.go
  filebeat/tests/integration/store_test.go
  libbeat/tests/integration/framework.go
Labels: bug, Team:Automation, Team:Elastic-Agent

#38252 libbeat/processors/add_process_metada: add capabilities to process me…
  CHANGELOG.next.asciidoc
  libbeat/processors/add_process_metadata/add_process_metadata.go
  libbeat/processors/add_process_metadata/add_process_metadata_test.go
  libbeat/processors/add_process_metadata/config.go
  libbeat/processors/add_process_metadata/gosysinfo_provider.go
Labels: enhancement, Team:Elastic-Agent, Team:Security-Linux Platform

#38851 Moved xpack/winlogbeat pipeline to central pipeline
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_xpack_winlogbeat_pipeline.sh
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: Team:Elastic-Agent, backport-v7.17.0, backport-v8.13.0

#38865 [CI] Agentbeat package pipeline resource
  catalog-info.yaml
Labels: enhancement, Team:Elastic-Agent

#38875 Adjust the Beats pipelines branch configuraiton
  catalog-info.yaml
Labels: backport-skip, Team:Ingest-EngProd

#38877 Fix metricbeat packaging on 7.17
  .buildkite/metricbeat/pipeline.yml
Labels: ci, Team:Ingest-EngProd

#38881 Set Buildkite to trigger builds with labels
  catalog-info.yaml
Labels: bug, backport-skip, Team:Ingest-EngProd

#38883 Add scripts folder to trigger all projects
  .buildkite/pipeline.yml
Labels: backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38892 [7.17](backport #38883) Add scripts folder to trigger all projects
  .buildkite/pipeline.yml
Labels: backport, Team:Ingest-EngProd

#38893 catalog-info codeowners fix
  .github/CODEOWNERS
Labels: backport-skip, Team:Ingest-EngProd

#38894 Revert branch_configuration for beats pipeline
  catalog-info.yaml
Labels: bug, backport-skip, Team:Ingest-EngProd

#38889 macOS arm64 CI for metricbeat
  .buildkite/metricbeat/pipeline.yml
Labels: ci, macOS, Team:Ingest-EngProd

#38895 Allow mergify bot to trigger builds
  .buildkite/pull-requests.json
Labels: bug, backport-skip, Team:Ingest-EngProd

#38556 Fix panic when more than 32767 pipeline clients are active
  CHANGELOG-developer.next.asciidoc
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/internal/input-logfile/harvester.go
  filebeat/input/kafka/input.go
  filebeat/input/v2/input-cursor/input.go
  filebeat/input/v2/input-stateless/stateless.go
  filebeat/input/v2/input-stateless/stateless_test.go
  libbeat/beat/pipeline.go
  libbeat/publisher/pipeline/client.go
  libbeat/publisher/pipeline/client_test.go
  libbeat/publisher/pipeline/pipeline.go
  libbeat/publisher/pipeline/pipeline_test.go
  libbeat/publisher/testing/testing.go
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/entityanalytics/internal/kvstore/input.go
  x-pack/filebeat/input/lumberjack/input.go
  x-pack/filebeat/input/netflow/input.go
  x-pack/filebeat/input/shipper/input.go
Labels: bug, Team:Elastic-Agent

#38903 Add support for installing Node.js on macOS
  .buildkite/scripts/install_macos_tools.sh
Labels: ci, macOS, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38632 Fix clean_inactive for Filestream input
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/input/filestream/internal/input-logfile/clean.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/v2/input-cursor/clean.go
  filebeat/input/v2/input-cursor/manager.go
  filebeat/tests/integration/filestream_test.go
Labels: bug, Team:Elastic-Agent

#38776 [Auditbeat] fim(kprobes): enrich file events by coupling add_process_metadata processor
  CHANGELOG.next.asciidoc
  auditbeat/module/file_integrity/eventreader_kprobes.go
  auditbeat/module/file_integrity/eventreader_linux.go
  auditbeat/module/file_integrity/metricset.go
  libbeat/processors/add_process_metadata/add_process_metadata.go
  libbeat/processors/add_process_metadata/add_process_metadata_test.go
  libbeat/processors/add_process_metadata/cache.go
  libbeat/processors/add_process_metadata/cache_test.go
  libbeat/processors/add_process_metadata/config.go
  libbeat/processors/add_process_metadata/gosysinfo_provider.go
  metricbeat/mb/module/configuration.go
  metricbeat/mb/module/connector.go
  metricbeat/mb/module/connector_test.go
  metricbeat/mb/module/factory.go
  metricbeat/mb/module/runner_group.go
  metricbeat/mb/module/runner_group_test.go
  metricbeat/mb/module/testing.go
  metricbeat/mb/module/wrapper.go
  x-pack/winlogbeat/include/list.go
Labels: enhancement, Team:Elastic-Agent, Team:Security-Linux Platform, backport-v8.13.0

#38126 [Metricbeat][Aerospike Module] Add support for TLS
  metricbeat/docs/modules/aerospike.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/aerospike/_meta/config.reference.yml
  metricbeat/module/aerospike/_meta/config.yml
  metricbeat/module/aerospike/_meta/fields.yml
  metricbeat/module/aerospike/aerospike.go
  metricbeat/module/aerospike/aerospike_test.go
  metricbeat/module/aerospike/fields.go
  metricbeat/module/aerospike/namespace/namespace.go
  metricbeat/modules.d/aerospike.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Obs-InfraObs

#38925 Fix macOS failures with auditbeat
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/pipeline.yml
Labels: :Windows, ci, macOS, arm, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38913 Move to static BK pipeline for x-pack/metricbeat
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/cloud_tests.sh
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_xpack_metricbeat_pipeline.sh
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
Labels: :Windows, ci, macOS, aws, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38825 Remove old steps from filebeat-pipeline.yaml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/filebeat/generate_filebeat_pipeline.sh
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_filebeat_pipeline.sh
Labels: Packaging, macOS, arm, windows-10, windows-2019, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, windows-11

#38871 Buildkite pipeline unification fixes
  .buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/pipeline.yml
Labels: kubernetes, Team:Elastic-Agent, backport-v7.17.0, backport-v8.13.0

#38757 Add a markdown with high level kubernetes metadata enrichment explanation
  metricbeat/module/kubernetes/_meta/images/enrichers.png
  metricbeat/module/kubernetes/util/enrichers.md
Labels: needs_team

#38866 [updatecli] update elastic stack version for testing 8.14.0-cf1b0234
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#38949 [updatecli] update elastic stack version for testing 8.13.3-19734ad9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#38799 Session view processor procfs
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/processors/sessionmd/add_session_metadata.go
  x-pack/auditbeat/processors/sessionmd/add_session_metadata_test.go
  x-pack/auditbeat/processors/sessionmd/processdb/db.go
  x-pack/auditbeat/processors/sessionmd/processdb/db_test.go
  x-pack/auditbeat/processors/sessionmd/procfs/procfs.go
  x-pack/auditbeat/processors/sessionmd/provider/procfs_provider/procfs_provider.go
  x-pack/auditbeat/processors/sessionmd/provider/procfs_provider/procfs_provider_test.go
  x-pack/auditbeat/processors/sessionmd/types/process.go
Labels: enhancement, Auditbeat, backport-skip, Team:Security-Linux Platform, Team:Security-Deployment and Devices

#38922 x-pack/filebeat/input/o365audit: deprecate input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-o365audit.asciidoc
  x-pack/filebeat/input/o365audit/input.go
Labels: enhancement, Filebeat, backport-skip, Team:Security-Service Integrations

#38923 Add release note for PR 38126 in changelog.next.asciidoc
  CHANGELOG.next.asciidoc
Labels: needs_team

#38943 Remove X-PACK Filebeat bot trigger
  .buildkite/pull-requests.json
Labels: backport-skip, Team:Ingest-EngProd

#38948 Bring back env vars for metricbeat pipelines
  .buildkite/hooks/pre-command
Labels: :Windows, ci, macOS, aws, Team:Ingest-EngProd

#38924 migrate libbeat to static
  .buildkite/hooks/pre-command
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_libbeat_pipeline.sh
Labels: libbeat, arm, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38939 Migrate x-pack/osquerybeat to static pipeline
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_xpack_osquerybeat_pipeline.sh
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
Labels: :Windows, ci, macOS, Team:Ingest-EngProd

#38966 Remove modules from Filebeat
  .buildkite/filebeat/filebeat-pipeline.yml
Labels: bug, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd

#38891 Added support for shards total count in Elasticsearch Module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/elasticsearch/fields.go
  metricbeat/module/elasticsearch/node_stats/_meta/data.json
  metricbeat/module/elasticsearch/node_stats/_meta/fields.yml
  metricbeat/module/elasticsearch/node_stats/data.go
Labels: enhancement, Team:Monitoring

#38959 Fix issue with x-pack/metricbeat not using base settings.
  x-pack/metricbeat/cmd/root.go
Labels: Team:Elastic-Agent, backport-skip

#38987 [updatecli] update elastic stack version for testing 8.14.0-918a815f
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#38985 x-pack/filebeat/input/gcppubsub: Prevent input blockage by increasing default `max_outstanding_messages`
  CHANGELOG.next.asciidoc
  x-pack/filebeat/_meta/config/filebeat.inputs.reference.xpack.yml.tmpl
  x-pack/filebeat/docs/inputs/input-gcp-pubsub.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/input/gcppubsub/config.go
  x-pack/filebeat/input/gcppubsub/pubsub_test.go
Labels: Filebeat, Team:Elastic-Agent, bugfix, Team:Security-Service Integrations

#38988 [updatecli] update elastic stack version for testing 8.13.3-b68daf90
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#38370 [AWS] AWS Health metricbeat module
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  metricbeat/docs/modules/aws/awshealth.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/module/aws/awshealth/_meta/data.json
  x-pack/metricbeat/module/aws/awshealth/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/awshealth/_meta/fields.yml
  x-pack/metricbeat/module/aws/awshealth/awshealth.go
  x-pack/metricbeat/module/aws/awshealth/awshealth_integration_test.go
  x-pack/metricbeat/module/aws/awshealth/awshealth_test.go
  x-pack/metricbeat/module/aws/fields.go
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: enhancement, Team:Integrations, Team:Elastic-Agent

#38991 [7.17] Skip failing prometheus remote write test.
  metricbeat/module/prometheus/test_prometheus.py
Labels: Team:Elastic-Agent

#38522 [updatecli] update elastic stack version for testing 7.17.21-29fdcf2a
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#38962 x-pack/filebeat/input/{cel,httpjson}: fix oauth2 config validation
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/cel/config_auth.go
  x-pack/filebeat/input/cel/config_test.go
  x-pack/filebeat/input/httpjson/config_auth.go
  x-pack/filebeat/input/httpjson/config_test.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-v8.13.0

#38951 [CI] Jenkins package pipeline for agentbeat
  .buildkite/scripts/install-msitools.sh
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .ci/packaging.groovy
  Jenkinsfile
  Jenkinsfile.yml
  x-pack/agentbeat/Jenkinsfile.yml
  x-pack/osquerybeat/internal/distro/distro.go
  x-pack/osquerybeat/internal/msiutil/expand.go
  x-pack/osquerybeat/magefile.go
  x-pack/osquerybeat/scripts/mage/distro.go
Labels: enhancement, Team:Automation

#38998 Adding missing comma in packaging.groovy, add agentbeat for arm.
  .ci/packaging.groovy
Labels: Team:Automation

#38721 Update aws-sdk-go to v1.51.14
  NOTICE.txt
  go.mod
  go.sum
Labels: backport, needs_team, dependency

#38828 [CI] xpack/auditbeat monorepo migration
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_xpack_auditbeat_pipeline.sh
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
Labels: enhancement, :Windows, macOS, arm, Team:Ingest-EngProd

#39004 Added an empty ironbank target to agentbeat
  x-pack/agentbeat/magefile.go
Labels: needs_team

#39006 [filebeat][websocket] - Updated Input title to align with existing inputs
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-websocket.asciidoc
Labels: docs, Filebeat, Team:Security-Service Integrations, backport-v8.13.0

#39005 Fix msitools installation for packaging pipeline
  .ci/packaging.groovy
Labels: Team:Automation

#39014 Remove BK PR Bot trigger for x-pack/heartbeat
  .buildkite/pull-requests.json
Labels: ci, Team:Ingest-EngProd

#39015 [updatecli] update elastic stack version for testing 7.17.21-e9b73307
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39017 [updatecli] update elastic stack version for testing 8.14.0-799c1dc0
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39018 add .asc downloads to elastic-agent-package-7.17
  dev-tools/mage/manifest/manifest.go
Labels: Team:Elastic-Agent

#39016 [updatecli] update elastic stack version for testing 8.13.3-3dc31fcb
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#38990 x-pack/filebeat/input/entityanalytics - Fix log format
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go
Labels: bug, Filebeat, backport-skip, Team:Security-Service Integrations

#38994 Update ECS in auditbeat sessionmd processor
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/processors/sessionmd/_meta/fields.yml
  x-pack/auditbeat/processors/sessionmd/fields.go
Labels: backport-skip, bugfix, Team:Security-Linux Platform

#39026 Add missing command name for filebeat.
  x-pack/agentbeat/agentbeat.spec.yml
Labels: Team:Elastic-Agent, backport-skip

#38861 filebeat/azure/azureeventhub: upgrade azure-event-hubs-go and azure-storage-blob-go dependencies
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Cloud-Monitoring

#38941 Migrate X-PACK Filebeat pipeline to main Beat pipeline
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  .buildkite/scripts/cloud_tests.sh
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_xpack_filebeat_pipeline.sh
  .buildkite/scripts/setenv.sh
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
Labels: :Windows, arm, aws, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39030 backport: Add 8.14 branch
  .mergify.yml
Labels: release, Team:Automation, impact:critical, backport-v8.14.0

#38845 [CI] x-pack/heartbeat monorepo
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_xpack_heartbeat_pipeline.sh
  .buildkite/scripts/install_macos_tools.sh
  .buildkite/scripts/setenv.sh
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
Labels: enhancement, ci, Team:Ingest-EngProd

#39042 Fix conflict issues after merging #38845
  .buildkite/scripts/common.sh
Labels: Team:Ingest-EngProd

#38945 Set owner of syslog reader and processor
  .github/CODEOWNERS
Labels: Team:Security-Deployment and Devices

#39045 Fixed issues with Heartbeat pipeline
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/hooks/pre-command
  .buildkite/hooks/scripts/util.sh
Labels: :Windows, macOS, Team:Elastic-Agent, backport-v7.17.0, backport-v8.13.0, backport-v8.14.0

#39033 [Release] update version to next minor 8.15.0
  libbeat/version/version.go
Labels: in progress, release, automation, Team:Automation

#39024 [netflow] Restore netflow input on Windows
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/default-inputs/inputs_windows.go
Labels: bug, Filebeat, Team:Security-Deployment and Devices, backport-v8.13.0

#39054 [updatecli] update elastic stack version for testing 7.17.21-53490780
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39055 [updatecli] update elastic stack version for testing 8.13.3-c9047748
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39056 [updatecli] update elastic stack version for testing 8.14.0-318ae53b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#38926 Moved winlogbeat pipeline to central pipeline
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
Labels: :Windows, macOS, Team:Elastic-Agent, backport-v7.17.0, backport-v8.13.0, backport-v8.14.0

#39071 Improve conditionals for x-pack/metricbeat BK CI
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
Labels: macOS, aws, Team:Ingest-EngProd

#39077 Remove BK PR Bot trigger for packetbeat
  .buildkite/pull-requests.json
Labels: ci, Team:Ingest-EngProd

#38964 migrate x-pack/libbeat to static
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_xpack_libbeat_pipeline.sh
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
Labels: needs_team, backport-v7.17.0, backport-v8.13.0

#39085 [updatecli] update elastic stack version for testing 7.17.21-587bbe3b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39084 [updatecli] update elastic stack version for testing 8.13.3-c3270b70
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39007 Buildkite Xpack/Winlogbeat pipeline fixes
  .buildkite/scripts/changesets.psm1
  .buildkite/scripts/common.sh
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: :Windows, Team:Elastic-Agent, backport-v7.17.0, backport-v8.13.0, backport-v8.14.0

#39087 Migrate packetbeat to static Buildkite pipeline
  .buildkite/hooks/pre-command
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_packetbeat_pipeline.sh
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39109 [8.13](backport #39087) Migrate packetbeat to static Buildkite pipeline
  .buildkite/hooks/pre-command
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_packetbeat_pipeline.sh
Labels: :Windows, backport, macOS, arm, aws, Team:Ingest-EngProd

#38982 [libbeat] Fix parsing of RFC 3164 process IDs in syslog processor
  CHANGELOG.next.asciidoc
  libbeat/reader/syslog/parser/rfc3164.rl
  libbeat/reader/syslog/rfc3164_gen.go
  libbeat/reader/syslog/rfc3164_test.go
Labels: bug, libbeat, Team:Security-Deployment and Devices, backport-v8.13.0, backport-v8.14.0

#39130 [updatecli] update elastic stack version for testing 7.17.21-5d83bb4d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39134 [Auditbeat] Remove temporary "ReplaceFields" config option
  x-pack/auditbeat/processors/sessionmd/add_session_metadata.go
  x-pack/auditbeat/processors/sessionmd/add_session_metadata_test.go
  x-pack/auditbeat/processors/sessionmd/config.go
Labels: enhancement, Team:Security-Linux Platform

#39135 [8.14] Update versions in tests to 8.13.2 consistently
  metricbeat/docker-compose.yml
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane

#39129 [updatecli] update elastic stack version for testing 8.13.3-22bed9d1
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39136 [main] Update test versions to 8.13.2
  metricbeat/docker-compose.yml
  x-pack/metricbeat/docker-compose.yml
Labels: Team:Elastic-Agent

#39072 move x-pack/packetbeat to static pipeline
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/common.sh
  .buildkite/scripts/generate_xpack_packetbeat_pipeline.sh
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
Labels: x-pack, needs_team, macOS, arm, backport-v7.17.0, backport-v8.13.0, backport-v8.14.0

#39064 Agentbeat: remove unused files from package and silence new error message
  dev-tools/packaging/package_test.go
  filebeat/fileset/modules.go
  x-pack/agentbeat/dev-tools/packaging/packages.yml
Labels: Team:Elastic-Agent, backport-v8.14.0

#38983 Cleanup: Remove unused ACK tracking in `awscloudwatch` input
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/filebeat/input/awscloudwatch/input_integration_test.go
  x-pack/filebeat/input/awscloudwatch/processor.go
Labels: cleanup, Team:Elastic-Agent

#38957 Cleanup: Replace custom goroutine shutdown listeners with shared context wrapper
  filebeat/input/v2/input.go
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/filebeat/input/awss3/input.go
Labels: cleanup, Team:Elastic-Agent

#39163 [updatecli] update elastic stack version for testing 7.17.21-5339d087
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39162 [updatecli] update elastic stack version for testing 8.13.3-94d3b00c
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39177 Add initial BK pipeline for IronBank validation
  .buildkite/ironbank-valitation.yml
  catalog-info.yaml
Labels: ci, Team:Ingest-EngProd

#39066 Use upstream go plugins helpers
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Fleet, backport-skip

#39176 Trigger the monorepo trigger only on PR
  .buildkite/pipeline.yml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39195 [updatecli] update elastic stack version for testing 7.17.21-75fbaabb
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39193 [updatecli] update elastic stack version for testing 8.13.3-6596e7ab
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39053 [updatecli] update elastic stack version for testing 8.14.0-318ae53b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39194 [updatecli] update elastic stack version for testing 8.15.0-f50da2d9
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39207 Fixes for packaging pipeline
  .buildkite/packaging.pipeline.yml
  .buildkite/scripts/dra.sh
  .buildkite/scripts/packaging/package-dra.sh
Labels: ci, Team:Ingest-EngProd

#39212 Fix BK DRA pipeline
  .buildkite/packaging.pipeline.yml
Labels: ci, Team:Ingest-EngProd

#39165 [Eleasticsearch] Remove `hidden` field from indice metricset docs
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/elasticsearch.go
  metricbeat/module/elasticsearch/elasticsearch_integration_test.go
  metricbeat/module/elasticsearch/index/data.go
Labels: enhancement, Module:elasticsearch, Team:Monitoring, backport-v8.14.0
