Repository elastic/beats, pull requests merged in 2024-09, with the labels that each got.

#40670 Create mergify config for 8.x backports
  .mergify.yml
Labels: needs_team

#40651 [libbeat][parquet reader] - Added debug logs & improved batch_size tracking
  CHANGELOG-developer.next.asciidoc
  x-pack/libbeat/reader/parquet/parquet.go
  x-pack/libbeat/reader/parquet/parquet_test.go
Labels: enhancement, Team:Security-Service Integrations, backport-v8.15.0, 8.16-candidate, libbeat:reader

#40634 [vSphere][datastore_cluster] Add support for new metrics in datastore_cluster metricset
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/vsphere.asciidoc
  metricbeat/docs/modules/vsphere/datastorecluster.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/vsphere/_meta/README.md
  metricbeat/module/vsphere/_meta/config.reference.yml
  metricbeat/module/vsphere/_meta/config.yml
  metricbeat/module/vsphere/_meta/docs.asciidoc
  metricbeat/module/vsphere/datastorecluster/_meta/data.json
  metricbeat/module/vsphere/datastorecluster/_meta/docs.asciidoc
  metricbeat/module/vsphere/datastorecluster/_meta/fields.yml
  metricbeat/module/vsphere/datastorecluster/data.go
  metricbeat/module/vsphere/datastorecluster/data_test.go
  metricbeat/module/vsphere/datastorecluster/datastorecluster.go
  metricbeat/module/vsphere/datastorecluster/datastorecluster_test.go
  metricbeat/module/vsphere/fields.go
  metricbeat/modules.d/vsphere.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: enhancement, module, Metricbeat, Team:Elastic-Agent-Data-Plane, Module:beat, Team:Obs-InfraObs

#40679 [7.17](backport #40440) [CI] Set Buildkite retries to 1 #40649
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: backport, Team:Ingest-EngProd

#40666 Fix build tags in journald input
  filebeat/input/journald/pkg/journalfield/conv_expand_test.go
  filebeat/input/journald/pkg/journalfield/conv_test.go
  filebeat/input/journald/pkg/journalfield/default.go
  filebeat/input/journald/pkg/journalfield/matcher_test.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#40661 [GCP] Log `ListTimeSeries` and `AggregatedList` requests duration
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/gcp/metrics/compute/metadata.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
Labels: needs_team

#40681 x-pack/filebeat/input/entityanalytics/provider/okta: fix publication of groups
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-v8.15.0

#40483 Remove x-pack code from OSS filebeat.
  filebeat/input/filestream/internal/input-logfile/harvester_test.go
Labels: refactoring, Filebeat, Team:Elastic-Agent-Data-Plane

#40563 Dump artifact uri response body when fail decoding
  x-pack/elastic-agent/pkg/artifact/download/snapshot/downloader.go
  x-pack/elastic-agent/pkg/artifact/download/snapshot/downloader_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#40589 [Packetbeat] Fix Packetbeat parsing mongodb OP_MSG
  packetbeat/protos/mongodb/mongodb.go
  packetbeat/protos/mongodb/mongodb_parser.go
  packetbeat/protos/mongodb/mongodb_parser_test.go
  packetbeat/protos/mongodb/mongodb_structs.go
  packetbeat/protos/mongodb/mongodb_structs_test.go
  packetbeat/protos/mongodb/testdata/1req.bin
  packetbeat/protos/mongodb/testdata/1res.bin
  packetbeat/protos/mongodb/testdata/2req.bin
  packetbeat/protos/mongodb/testdata/2res.bin
  packetbeat/protos/mongodb/testdata/3req.bin
  packetbeat/protos/mongodb/testdata/3res.bin
Labels: bug, backport-skip, bugfix, Team:Security-Deployment and Devices

#40689 [Heartbeat] Add Synthetics to wolfi image
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: enhancement, backport-skip, Team:Elastic-Agent-Data-Plane

#40667 refactor fleet mode detection and storage
  libbeat/cfgfile/cfgfile.go
  libbeat/common/fleetmode/fleet_mode.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#40580 x-pack/filebeat/input/cel: improve missing events error value
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/cel/input.go
Labels: enhancement, Filebeat, backport-skip, Team:Security-Service Integrations

#40583 [Heartbeat] Fix testing pipeline for Windows
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  x-pack/heartbeat/include/list.go
  x-pack/heartbeat/magefile.go
  x-pack/heartbeat/scenarios/basics_test.go
  x-pack/heartbeat/scenarios/browserbasics_test.go
Labels: Team:obs-ds-hosted-services, ci, backport-skip

#40683 Add support of snapshot in vSphere virtualmachine metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/vsphere/fields.go
  metricbeat/module/vsphere/virtualmachine/_meta/data.json
  metricbeat/module/vsphere/virtualmachine/_meta/fields.yml
  metricbeat/module/vsphere/virtualmachine/data.go
  metricbeat/module/vsphere/virtualmachine/data_test.go
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
Labels: enhancement, Team:Obs-InfraObs

#40703 [winlogbeat] Only init metrics if needed
  winlogbeat/eventlog/wineventlog.go
  winlogbeat/eventlog/wineventlog_experimental.go
Labels: backport-skip, Team:Security-Windows Platform

#40524 Make Wolfi a part of Docker packaging
  dev-tools/packaging/package_test.go
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#40704 Manual backport of elastic-agent PR #3682 - Use only fs.NewDownloader for file://
  x-pack/elastic-agent/pkg/agent/application/upgrade/step_download.go
Labels: Team:Elastic-Agent-Control-Plane, bugfix

#40694 [vSphere][datastore_cluster] Add support for new metrics in datastore_cluster metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/vsphere/datastorecluster/_meta/data.json
  metricbeat/module/vsphere/datastorecluster/_meta/fields.yml
  metricbeat/module/vsphere/datastorecluster/data.go
  metricbeat/module/vsphere/datastorecluster/data_test.go
  metricbeat/module/vsphere/datastorecluster/datastorecluster.go
  metricbeat/module/vsphere/fields.go
Labels: enhancement, Metricbeat, Module:beat, Team:Obs-InfraObs

#40625 [add_kubernetes_metadata] Remove extra debug messages
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
Labels: backport-v7.17.0, Team:Cloudnative-Monitoring, backport-v8.15.0

#40715 [Docs] Clarify how/when metrics are collected
  metricbeat/docs/modules/system.asciidoc
  metricbeat/module/system/_meta/docs.asciidoc
Labels: Team:Docs, backport-v8.15.0

#40692 [Processor\Script] Add option to prevent creation of new sessions
  CHANGELOG.next.asciidoc
  libbeat/processors/script/javascript/config.go
  libbeat/processors/script/javascript/session.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#40718 Automatically label PRs to `main` with `backport-v8.x`
  .mergify.yml
Labels: automation, needs_team, backport-skip

#40086 [Kubernetes - Metricbeat] Providing config option to disable Kubeadm config api requests
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/module/kubernetes/_meta/test/docs/01_playground/metricbeat.yaml
  metricbeat/module/kubernetes/event/config.go
  metricbeat/module/kubernetes/util/kubernetes.go
Labels: backport-skip, Team:Cloudnative-Monitoring

#40707 Update fields to use mapstr in vSphere virtualmachine metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/vsphere/fields.go
  metricbeat/module/vsphere/virtualmachine/_meta/data.json
  metricbeat/module/vsphere/virtualmachine/_meta/fields.yml
  metricbeat/module/vsphere/virtualmachine/data.go
  metricbeat/module/vsphere/virtualmachine/data_test.go
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
  metricbeat/module/vsphere/virtualmachine/virtualmachine_test.go
Labels: enhancement, needs_team, backport-v8.x

#40733 [Heartbeat] Adjust Windows test pipeline
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
Labels: Team:obs-ds-hosted-services, ci, release-note:skip, backport-8.x

#40730 [netflow] Ensure custom fields configuration is applied
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/netflow/input.go
  x-pack/filebeat/input/netflow/input_test.go
Labels: Filebeat, bugfix, Team:Security-Deployment and Devices, backport-v8.15.0, backport-v8.x

#40741 mergify: add backport-v8.x always for main
  .mergify.yml
Labels: needs_team, backport-skip

#40678 [Metricbeat][vSphere] Support for configurable IntervalId for performance API
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/vsphere.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/vsphere/_meta/config.reference.yml
  metricbeat/module/vsphere/_meta/config.yml
  metricbeat/module/vsphere/_meta/docs.asciidoc
  metricbeat/module/vsphere/cluster/cluster.go
  metricbeat/module/vsphere/datastore/_meta/data.json
  metricbeat/module/vsphere/datastore/datastore.go
  metricbeat/module/vsphere/datastore/datastore_test.go
  metricbeat/module/vsphere/datastorecluster/datastorecluster.go
  metricbeat/module/vsphere/host/_meta/data.json
  metricbeat/module/vsphere/host/host.go
  metricbeat/module/vsphere/host/host_test.go
  metricbeat/module/vsphere/network/network.go
  metricbeat/module/vsphere/resourcepool/resourcepool.go
  metricbeat/module/vsphere/test_vsphere.py
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
  metricbeat/modules.d/vsphere.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: enhancement, module, Metricbeat, Module:beat, Team:Obs-InfraObs, backport-v8.x

#40716 mergify: support for backport-major.minor
  .mergify.yml
Labels: needs_team, backport-v8.x

#40767 Add known issue that Beats do not recover from transient network errors
  CHANGELOG.asciidoc
Labels: Team:Docs, Team:Elastic-Agent-Data-Plane

#40682 github-action: use oblt-actions/elastic/active-branches
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/notify-stalled-snapshots.yml
Labels: needs_team, backport-8.x

#40736 Change maintainer label to opencontainers in Dockerfile
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x

#40558 [Journald] Restart journalctl if it exits unexpectedly
  CHANGELOG.next.asciidoc
  filebeat/input/journald/input.go
  filebeat/input/journald/pkg/journalctl/jctlmock_test.go
  filebeat/input/journald/pkg/journalctl/journalctl.go
  filebeat/input/journald/pkg/journalctl/reader.go
  filebeat/input/journald/pkg/journalctl/reader_test.go
  filebeat/input/journald/pkg/journalctl/testdata/sample-journal-event.json
  filebeat/input/mqtt/client_mocked.go
  filebeat/tests/integration/journald_test.go
  filebeat/tests/integration/testdata/filebeat_journald.yml
  filebeat/tests/mockjournalctl/main.go
  libbeat/common/backoff/backoff.go
  libbeat/common/backoff/equal_jitter.go
  libbeat/common/backoff/exponential.go
  libbeat/tests/integration/framework.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#40753 fix invalid bitSize in strconv.ParseFloat
  libbeat/processors/ratelimit/limit.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x

#40769 Do not cancel context on Connection.Close
  libbeat/esleg/eslegclient/connection.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.15, backport-8.x

#40754 mergify: replace queue action for queue_rules
  .mergify.yml
Labels: needs_team, backport-skip, backport-8.x

#40411 {,x-pack/}metricbeat/module/prometheus/{collector,remote_write}: Add `metrics_count` to Prometheus module if `metrics_count` is `true`
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/prometheus.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/prometheus/_meta/config.epr.yml
  metricbeat/module/prometheus/_meta/config.yml
  metricbeat/module/prometheus/_meta/fields.yml
  metricbeat/module/prometheus/collector/_meta/data.json
  metricbeat/module/prometheus/collector/_meta/testdata/config.yml
  metricbeat/module/prometheus/collector/_meta/testdata/docs.plain-expected.json
  metricbeat/module/prometheus/collector/_meta/testdata/duplicate-metrics.plain-expected.json
  metricbeat/module/prometheus/collector/_meta/testdata/etcd-3.3.10-partial.plain-expected.json
  metricbeat/module/prometheus/collector/_meta/testdata/metrics-with-naninf.plain-expected.json
  metricbeat/module/prometheus/collector/_meta/testdata/prometheus-2.6.0-partial.plain-expected.json
  metricbeat/module/prometheus/collector/collector.go
  metricbeat/module/prometheus/collector/collector_test.go
  metricbeat/module/prometheus/collector/config.go
  metricbeat/module/prometheus/fields.go
  metricbeat/module/prometheus/remote_write/config.go
  metricbeat/module/prometheus/remote_write/data.go
  metricbeat/module/prometheus/remote_write/remote_write.go
  metricbeat/module/prometheus/remote_write/remote_write_test.go
  metricbeat/modules.d/prometheus.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/prometheus/_meta/config.yml
  x-pack/metricbeat/module/prometheus/collector/_meta/data.json
  x-pack/metricbeat/module/prometheus/collector/_meta/testdata/config.yml
  x-pack/metricbeat/module/prometheus/collector/_meta/testdata/docs.plain-expected.json
  x-pack/metricbeat/module/prometheus/collector/_meta/testdata/metrics-with-naninf.plain-expected.json
  x-pack/metricbeat/module/prometheus/collector/_meta/testdata/prometheus-2.6.0-partial.plain-expected.json
  x-pack/metricbeat/module/prometheus/collector/collector_test.go
  x-pack/metricbeat/module/prometheus/remote_write/config.go
  x-pack/metricbeat/module/prometheus/remote_write/data.go
  x-pack/metricbeat/module/prometheus/remote_write/remote_write.go
  x-pack/metricbeat/module/prometheus/remote_write/remote_write_test.go
  x-pack/metricbeat/modules.d/prometheus.yml.disabled
Labels: Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, backport-8.x

#40757 mergify: avoid label automation always
  .mergify.yml
Labels: needs_team, backport-8.x

#40786 updatecli: ironbank images are not anymore in the package file
  .github/workflows/updatecli.d/values.d/ironbank.yml
Labels: needs_team, backport-skip

#40770 Fix typo in changelog
  CHANGELOG.asciidoc
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#40751 libbeat/processors/replace: fix zero string replacement validation
  CHANGELOG.next.asciidoc
  libbeat/processors/actions/replace.go
  libbeat/processors/actions/replace_test.go
Labels: Filebeat, libbeat, bugfix, Team:Security-Service Integrations, backport-8.x

#40802 changelog: add missing pr number
  CHANGELOG.next.asciidoc
Labels: bugfix, Team:Security-Service Integrations, backport-8.x

#40734 testing: Fix Docker deprecation warnings
  testing/environments/Dockerfile
  testing/environments/local.yml
  testing/environments/snapshot.yml
Labels: cleanup, backport-skip, Team:Elastic-Agent-Data-Plane

#40714 [vSphere] add triggered alarm to existing metricsets.
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/vsphere/cluster/_meta/data.json
  metricbeat/module/vsphere/cluster/_meta/fields.yml
  metricbeat/module/vsphere/cluster/cluster.go
  metricbeat/module/vsphere/cluster/data.go
  metricbeat/module/vsphere/cluster/data_test.go
  metricbeat/module/vsphere/datastore/_meta/fields.yml
  metricbeat/module/vsphere/datastore/data.go
  metricbeat/module/vsphere/datastore/datastore.go
  metricbeat/module/vsphere/datastorecluster/_meta/fields.yml
  metricbeat/module/vsphere/datastorecluster/data.go
  metricbeat/module/vsphere/datastorecluster/datastorecluster.go
  metricbeat/module/vsphere/fields.go
  metricbeat/module/vsphere/host/_meta/data.json
  metricbeat/module/vsphere/host/_meta/fields.yml
  metricbeat/module/vsphere/host/data.go
  metricbeat/module/vsphere/host/host.go
  metricbeat/module/vsphere/network/_meta/fields.yml
  metricbeat/module/vsphere/network/data.go
  metricbeat/module/vsphere/network/network.go
  metricbeat/module/vsphere/resourcepool/_meta/fields.yml
  metricbeat/module/vsphere/resourcepool/data.go
  metricbeat/module/vsphere/resourcepool/resourcepool.go
  metricbeat/module/vsphere/virtualmachine/_meta/fields.yml
  metricbeat/module/vsphere/virtualmachine/data.go
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
Labels: enhancement, Metricbeat, Team:Obs-InfraObs, backport-8.x

#40006 OOTB support AWS Eventbridge
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/input/awss3/_meta/terraform/.terraform.lock.hcl
  x-pack/filebeat/input/awss3/_meta/terraform/main.tf
  x-pack/filebeat/input/awss3/_meta/terraform/outputs.tf
  x-pack/filebeat/input/awss3/input_benchmark_test.go
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/sqs_s3_event.go
  x-pack/filebeat/input/awss3/sqs_s3_event_test.go
  x-pack/filebeat/input/awss3/sqs_test.go
Labels: enhancement, Team:obs-ds-hosted-services, Team:Elastic-Agent-Data-Plane, Team:Cloud-Monitoring, Team:Security-Linux Platform, Team:Security-Service Integrations, Team:Security-Deployment and Devices, backport-8.x

#40775 chore: add debug histograms for s3 object size and events per processed s3 object
  CHANGELOG-developer.next.asciidoc
  x-pack/filebeat/input/awss3/metrics.go
  x-pack/filebeat/input/awss3/s3_objects.go
Labels: Team:obs-ds-hosted-services, backport-8.x

#40796 Change codeowners for enterprise-search
  .github/CODEOWNERS
Labels: backport, needs_team, backport-8.x

#40823 [8.15](backport #40559) [vSphere][network] Add support for new metrics in network metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/vsphere.asciidoc
  metricbeat/docs/modules/vsphere/network.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/vsphere/_meta/README.md
  metricbeat/module/vsphere/_meta/config.reference.yml
  metricbeat/module/vsphere/_meta/config.yml
  metricbeat/module/vsphere/_meta/docs.asciidoc
  metricbeat/module/vsphere/fields.go
  metricbeat/module/vsphere/host/data.go
  metricbeat/module/vsphere/host/data_test.go
  metricbeat/module/vsphere/host/host.go
  metricbeat/module/vsphere/host/host_test.go
  metricbeat/module/vsphere/network/_meta/data.json
  metricbeat/module/vsphere/network/_meta/docs.asciidoc
  metricbeat/module/vsphere/network/_meta/fields.yml
  metricbeat/module/vsphere/network/data.go
  metricbeat/module/vsphere/network/data_test.go
  metricbeat/module/vsphere/network/network.go
  metricbeat/module/vsphere/network/network_test.go
  metricbeat/modules.d/vsphere.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: needs_team

#40825 [8.15](backport #40456) [vSphere][resourcepool] Add support for new metrics in resourcepool metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/vsphere.asciidoc
  metricbeat/docs/modules/vsphere/resourcepool.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/vsphere/_meta/README.md
  metricbeat/module/vsphere/_meta/config.reference.yml
  metricbeat/module/vsphere/_meta/config.yml
  metricbeat/module/vsphere/_meta/docs.asciidoc
  metricbeat/module/vsphere/fields.go
  metricbeat/module/vsphere/resourcepool/_meta/data.json
  metricbeat/module/vsphere/resourcepool/_meta/docs.asciidoc
  metricbeat/module/vsphere/resourcepool/_meta/fields.yml
  metricbeat/module/vsphere/resourcepool/data.go
  metricbeat/module/vsphere/resourcepool/data_test.go
  metricbeat/module/vsphere/resourcepool/resourcepool.go
  metricbeat/module/vsphere/resourcepool/resourcepool_test.go
  metricbeat/modules.d/vsphere.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: needs_team

#40829 [8.15](backport #40634) [vSphere][datastore_cluster] Add support for new metrics in datastore_cluster metricset
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/vsphere.asciidoc
  metricbeat/docs/modules/vsphere/datastorecluster.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/vsphere/_meta/README.md
  metricbeat/module/vsphere/_meta/config.reference.yml
  metricbeat/module/vsphere/_meta/config.yml
  metricbeat/module/vsphere/_meta/docs.asciidoc
  metricbeat/module/vsphere/datastorecluster/_meta/data.json
  metricbeat/module/vsphere/datastorecluster/_meta/docs.asciidoc
  metricbeat/module/vsphere/datastorecluster/_meta/fields.yml
  metricbeat/module/vsphere/datastorecluster/data.go
  metricbeat/module/vsphere/datastorecluster/data_test.go
  metricbeat/module/vsphere/datastorecluster/datastorecluster.go
  metricbeat/module/vsphere/datastorecluster/datastorecluster_test.go
  metricbeat/module/vsphere/fields.go
  metricbeat/modules.d/vsphere.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: needs_team

#40830 [8.15](backport #40683) Add support of snapshot in vSphere virtualmachine metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/vsphere/fields.go
  metricbeat/module/vsphere/virtualmachine/_meta/data.json
  metricbeat/module/vsphere/virtualmachine/_meta/fields.yml
  metricbeat/module/vsphere/virtualmachine/data.go
  metricbeat/module/vsphere/virtualmachine/data_test.go
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
Labels: needs_team

#40831 [8.15](backport #40694) [vSphere][datastore_cluster] Add support for new metrics in datastore_cluster metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/vsphere/datastorecluster/_meta/data.json
  metricbeat/module/vsphere/datastorecluster/_meta/fields.yml
  metricbeat/module/vsphere/datastorecluster/data.go
  metricbeat/module/vsphere/datastorecluster/data_test.go
  metricbeat/module/vsphere/datastorecluster/datastorecluster.go
  metricbeat/module/vsphere/fields.go
Labels: needs_team

#40834 [8.15](backport #40766) [Metricbeat][vSphere] New metrics support and minor changes to existing metricsets
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/vsphere/datastore/_meta/data.json
  metricbeat/module/vsphere/datastore/_meta/fields.yml
  metricbeat/module/vsphere/datastore/data.go
  metricbeat/module/vsphere/datastore/data_test.go
  metricbeat/module/vsphere/datastore/datastore.go
  metricbeat/module/vsphere/datastore/datastore_test.go
  metricbeat/module/vsphere/fields.go
  metricbeat/module/vsphere/host/_meta/data.json
  metricbeat/module/vsphere/host/host.go
  metricbeat/module/vsphere/virtualmachine/_meta/data.json
  metricbeat/module/vsphere/virtualmachine/_meta/fields.yml
  metricbeat/module/vsphere/virtualmachine/data_test.go
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
Labels: needs_team

#40764 tests: fix check to enable the race detector in supported platforms
  dev-tools/mage/gotest.go
Labels: cleanup, backport-skip, Team:Elastic-Agent-Data-Plane

#40742 azure-eventhub: expand input sanitizer's invalid JSON coverage
  x-pack/filebeat/input/azureeventhub/README.md
  x-pack/filebeat/input/azureeventhub/config.go
  x-pack/filebeat/input/azureeventhub/decoder.go
  x-pack/filebeat/input/azureeventhub/decoder_test.go
  x-pack/filebeat/input/azureeventhub/metrics.go
  x-pack/filebeat/input/azureeventhub/metrics_test.go
  x-pack/filebeat/input/azureeventhub/sanitization.go
  x-pack/filebeat/input/azureeventhub/sanitization_test.go
  x-pack/filebeat/input/azureeventhub/sanitizers.go
  x-pack/filebeat/input/azureeventhub/sanitizers_legacy.go
  x-pack/filebeat/input/azureeventhub/sanitizers_test.go
  x-pack/filebeat/input/azureeventhub/v1_input.go
  x-pack/filebeat/input/azureeventhub/v2_input.go
Labels: enhancement, Team:obs-ds-hosted-services, backport-8.15, input:azure-eventhub, backport-8.x

#40849 Osquerybeat: Upgrade to osquery 5.13.1
  CHANGELOG.next.asciidoc
  x-pack/osquerybeat/internal/distro/distro.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane, Team:Security-Deployment and Devices

#40691 [AWS] Support owning account for cross account monitoring
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/aws.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/aws/_meta/config.reference.yml
  x-pack/metricbeat/module/aws/_meta/config.yml
  x-pack/metricbeat/module/aws/_meta/docs.asciidoc
  x-pack/metricbeat/module/aws/aws.go
  x-pack/metricbeat/module/aws/billing/billing.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
  x-pack/metricbeat/modules.d/aws.yml.disabled
Labels: enhancement, Team:obs-ds-hosted-services, Team:Elastic-Agent-Data-Plane, backport-8.x

#40836 [metricbeat] meraki module with device_health metricset
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/meraki.asciidoc
  metricbeat/docs/modules/meraki/device_health.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/meraki/_meta/config.yml
  x-pack/metricbeat/module/meraki/_meta/docs.asciidoc
  x-pack/metricbeat/module/meraki/_meta/fields.yml
  x-pack/metricbeat/module/meraki/device_health/_meta/data.json
  x-pack/metricbeat/module/meraki/device_health/_meta/docs.asciidoc
  x-pack/metricbeat/module/meraki/device_health/_meta/fields.yml
  x-pack/metricbeat/module/meraki/device_health/device_health.go
  x-pack/metricbeat/module/meraki/device_health/device_health_test.go
  x-pack/metricbeat/module/meraki/device_health/devices.go
  x-pack/metricbeat/module/meraki/device_health/switchports.go
  x-pack/metricbeat/module/meraki/device_health/uplinks.go
  x-pack/metricbeat/module/meraki/doc.go
  x-pack/metricbeat/module/meraki/fields.go
  x-pack/metricbeat/modules.d/meraki.yml.disabled
Labels: Team:Elastic-Agent-Data-Plane, backport-8.15, backport-8.x

#40686 x-pack/metricbeat/module/panw: Add a new module
  .github/CODEOWNERS
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/panw.asciidoc
  metricbeat/docs/modules/panw/interfaces.asciidoc
  metricbeat/docs/modules/panw/routing.asciidoc
  metricbeat/docs/modules/panw/system.asciidoc
  metricbeat/docs/modules/panw/vpn.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/panw/_meta/config.yml
  x-pack/metricbeat/module/panw/_meta/docs.asciidoc
  x-pack/metricbeat/module/panw/_meta/fields.yml
  x-pack/metricbeat/module/panw/_meta/testdata/bgp_peers.xml
  x-pack/metricbeat/module/panw/client.go
  x-pack/metricbeat/module/panw/config.go
  x-pack/metricbeat/module/panw/doc.go
  x-pack/metricbeat/module/panw/fields.go
  x-pack/metricbeat/module/panw/interfaces/_meta/data.json
  x-pack/metricbeat/module/panw/interfaces/_meta/docs.asciidoc
  x-pack/metricbeat/module/panw/interfaces/_meta/fields.yml
  x-pack/metricbeat/module/panw/interfaces/ha_interfaces.go
  x-pack/metricbeat/module/panw/interfaces/ifnet_interfaces.go
  x-pack/metricbeat/module/panw/interfaces/interface_types.go
  x-pack/metricbeat/module/panw/interfaces/interfaces.go
  x-pack/metricbeat/module/panw/interfaces/tunnels.go
  x-pack/metricbeat/module/panw/routing/_meta/data.json
  x-pack/metricbeat/module/panw/routing/_meta/docs.asciidoc
  x-pack/metricbeat/module/panw/routing/_meta/fields.yml
  x-pack/metricbeat/module/panw/routing/bgp_peers.go
  x-pack/metricbeat/module/panw/routing/routing.go
  x-pack/metricbeat/module/panw/routing/routing_types.go
  x-pack/metricbeat/module/panw/system/_meta/data.json
  x-pack/metricbeat/module/panw/system/_meta/docs.asciidoc
  x-pack/metricbeat/module/panw/system/_meta/fields.yml
  x-pack/metricbeat/module/panw/system/certificates.go
  x-pack/metricbeat/module/panw/system/fans.go
  x-pack/metricbeat/module/panw/system/filesystem.go
  x-pack/metricbeat/module/panw/system/license.go
  x-pack/metricbeat/module/panw/system/power.go
  x-pack/metricbeat/module/panw/system/resources.go
  x-pack/metricbeat/module/panw/system/system.go
  x-pack/metricbeat/module/panw/system/system_types.go
  x-pack/metricbeat/module/panw/system/thermal.go
  x-pack/metricbeat/module/panw/util.go
  x-pack/metricbeat/module/panw/vpn/_meta/data.json
  x-pack/metricbeat/module/panw/vpn/_meta/docs.asciidoc
  x-pack/metricbeat/module/panw/vpn/_meta/fields.yml
  x-pack/metricbeat/module/panw/vpn/gp_sessions.go
  x-pack/metricbeat/module/panw/vpn/gp_stats.go
  x-pack/metricbeat/module/panw/vpn/vpn.go
  x-pack/metricbeat/module/panw/vpn/vpn_types.go
  x-pack/metricbeat/modules.d/panw.yml.disabled
Labels: Team:Elastic-Agent-Data-Plane, Team:Security-Deployment and Devices, backport-8.15, backport-8.x

#40865 add changelog entries for new meraki and panw metricbeat modules
  CHANGELOG.next.asciidoc
Labels: needs_team, backport-8.15, backport-8.x

#40871 Fix entries in CHANGELOG.next.asciidoc
  CHANGELOG.next.asciidoc
Labels: needs_team

#40872 Fix entries in CHANGELOG.next.asciidoc
  CHANGELOG.next.asciidoc
Labels: needs_team, backport-8.x

#40876 [vSphere] update field name for triggered_alarm
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/vsphere/cluster/_meta/data.json
  metricbeat/module/vsphere/cluster/_meta/fields.yml
  metricbeat/module/vsphere/cluster/cluster.go
  metricbeat/module/vsphere/cluster/data.go
  metricbeat/module/vsphere/datastore/_meta/fields.yml
  metricbeat/module/vsphere/datastore/data.go
  metricbeat/module/vsphere/datastore/datastore.go
  metricbeat/module/vsphere/datastorecluster/_meta/fields.yml
  metricbeat/module/vsphere/datastorecluster/data.go
  metricbeat/module/vsphere/datastorecluster/datastorecluster.go
  metricbeat/module/vsphere/fields.go
  metricbeat/module/vsphere/host/_meta/data.json
  metricbeat/module/vsphere/host/_meta/fields.yml
  metricbeat/module/vsphere/host/data.go
  metricbeat/module/vsphere/host/host.go
  metricbeat/module/vsphere/network/_meta/fields.yml
  metricbeat/module/vsphere/network/data.go
  metricbeat/module/vsphere/network/network.go
  metricbeat/module/vsphere/resourcepool/_meta/fields.yml
  metricbeat/module/vsphere/resourcepool/data.go
  metricbeat/module/vsphere/resourcepool/resourcepool.go
  metricbeat/module/vsphere/virtualmachine/_meta/fields.yml
  metricbeat/module/vsphere/virtualmachine/data.go
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
Labels: needs_team, backport-8.x

#40857 Expose output disk queue settings when running under agent
  libbeat/outputs/util.go
  libbeat/outputs/util_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-8.x

#40301 Disable kubeadm for filebeat (both filbeat.input and filbeat.autodiscover)
  CHANGELOG.next.asciidoc
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  filebeat/_meta/config/filebeat.autodiscover.reference.yml.tmpl
  filebeat/_meta/test/docs/01_playground/filebeat.yaml
  filebeat/filebeat.reference.yml
  libbeat/autodiscover/providers/kubernetes/config.go
  libbeat/autodiscover/providers/kubernetes/pod.go
  libbeat/autodiscover/providers/kubernetes/service.go
  libbeat/processors/add_kubernetes_metadata/config.go
  libbeat/processors/add_kubernetes_metadata/docs/add_kubernetes_metadata.asciidoc
  libbeat/processors/add_kubernetes_metadata/kubernetes.go
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/util/kubernetes.go
  x-pack/filebeat/filebeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Cloudnative-Monitoring, backport-8.x

#40816 Add NewBeatReceiver function for beats as otel receivers
  NOTICE.txt
  filebeat/cmd/root.go
  filebeat/input/input.go
  go.mod
  go.sum
  libbeat/beat/info.go
  libbeat/cmd/instance/beat.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#40578 [feat:filebeat/input/redis/slowlog] Add Redis replication role to slowlogs
  CHANGELOG.next.asciidoc
  filebeat/input/redis/harvester.go
  filebeat/tests/system/test_redis.py
Labels: Filebeat, backport-skip, Team:Elastic-Agent-Data-Plane, backport-8.x

#40461 x-pack/metricbeat/module/gcp: Add Organization ID and display name to cloud labels
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/gcp.asciidoc
  x-pack/metricbeat/module/gcp/_meta/docs.asciidoc
  x-pack/metricbeat/module/gcp/constants.go
  x-pack/metricbeat/module/gcp/metrics/cloudsql/metadata.go
  x-pack/metricbeat/module/gcp/metrics/compute/metadata.go
  x-pack/metricbeat/module/gcp/metrics/metadata_services.go
  x-pack/metricbeat/module/gcp/metrics/metricset.go
  x-pack/metricbeat/module/gcp/metrics/redis/metadata.go
  x-pack/metricbeat/module/gcp/metrics/timeseries.go
  x-pack/metricbeat/module/gcp/timeseries_metadata_collector.go
Labels: needs_team, bugfix, backport-8.x

#40886 Rename Wolfi images to satisfy the release naming convention
  dev-tools/packaging/package_test.go
  dev-tools/packaging/packages.yml
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane, backport-8.x

#40901 [metricbeat][panw] fix concurrent map write error caused by reusing a mapstr.M
  x-pack/metricbeat/module/panw/interfaces/ha_interfaces.go
  x-pack/metricbeat/module/panw/interfaces/ifnet_interfaces.go
  x-pack/metricbeat/module/panw/interfaces/tunnels.go
  x-pack/metricbeat/module/panw/routing/bgp_peers.go
  x-pack/metricbeat/module/panw/system/certificates.go
  x-pack/metricbeat/module/panw/system/fans.go
  x-pack/metricbeat/module/panw/system/filesystem.go
  x-pack/metricbeat/module/panw/system/license.go
  x-pack/metricbeat/module/panw/system/power.go
  x-pack/metricbeat/module/panw/system/resources.go
  x-pack/metricbeat/module/panw/system/thermal.go
  x-pack/metricbeat/module/panw/vpn/gp_sessions.go
  x-pack/metricbeat/module/panw/vpn/gp_stats.go
Labels: needs_team, backport-8.x

#40904 fix concurrent map write error caused by reusing a mapstr.M
  x-pack/metricbeat/module/panw/interfaces/ha_interfaces.go
  x-pack/metricbeat/module/panw/interfaces/ifnet_interfaces.go
  x-pack/metricbeat/module/panw/interfaces/tunnels.go
  x-pack/metricbeat/module/panw/routing/bgp_peers.go
  x-pack/metricbeat/module/panw/system/certificates.go
  x-pack/metricbeat/module/panw/system/fans.go
  x-pack/metricbeat/module/panw/system/filesystem.go
  x-pack/metricbeat/module/panw/system/license.go
  x-pack/metricbeat/module/panw/system/power.go
  x-pack/metricbeat/module/panw/system/resources.go
  x-pack/metricbeat/module/panw/system/thermal.go
  x-pack/metricbeat/module/panw/vpn/gp_sessions.go
  x-pack/metricbeat/module/panw/vpn/gp_stats.go
Labels: needs_team, backport-8.x

#40895 [8.15] Upgrade gRPC to v1.64.1
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane

#40684 [winlogbeat] Add handling for missing event data types in the experimental API
  CHANGELOG.next.asciidoc
  winlogbeat/sys/strings.go
  winlogbeat/sys/strings_test.go
  winlogbeat/sys/strings_windows.go
  winlogbeat/sys/wineventlog/syscall_windows.go
  winlogbeat/sys/zsyscall_windows.go
  winlogbeat/sys/zsyscall_windows_test.go
Labels: enhancement, Winlogbeat, Team:Security-Windows Platform, backport-8.x

#40360 [kibana] support api_key
  metricbeat/docs/modules/kibana.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kibana/_meta/config-xpack.yml
  metricbeat/module/kibana/_meta/config.reference.yml
  metricbeat/module/kibana/_meta/config.yml
  metricbeat/module/kibana/cluster_actions/cluster_actions.go
  metricbeat/module/kibana/cluster_rules/cluster_rules.go
  metricbeat/module/kibana/config.go
  metricbeat/module/kibana/kibana.go
  metricbeat/module/kibana/metricset.go
  metricbeat/module/kibana/node_actions/node_actions.go
  metricbeat/module/kibana/node_rules/node_rules.go
  metricbeat/module/kibana/settings/settings.go
  metricbeat/module/kibana/stats/stats.go
  metricbeat/module/kibana/status/status.go
  metricbeat/modules.d/kibana-xpack.yml.disabled
  metricbeat/modules.d/kibana.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: enhancement, Team:Elastic-Agent-Data-Plane, Module:kibana, Team:Monitoring, Team:Opex, backport-8.x

#40915 Chore: update packaging pipeline to run automatically on 8.x branch
  .buildkite/packaging.pipeline.yml
Labels: Team:Ingest-EngProd, backport-8.x

#40909 [filebeat] Fix long filepaths in diagnostics exceeding max path limits on Windows
  CHANGELOG.next.asciidoc
  filebeat/input/v2/compat/compat.go
  filebeat/input/v2/input-cursor/input.go
  filebeat/input/v2/input.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
  x-pack/filebeat/input/entityanalytics/provider/jamf/jamf.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/input_test.go
Labels: Filebeat, backport-skip, bugfix, Team:Security-Deployment and Devices, backport-8.x

#40920 clean up old Jenkins resources
  .buildkite/aws-tests-pipeline.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .ci/beats-tester-bc.groovy
  .ci/beats-tester.groovy
  .ci/build-docker-images.groovy
  .ci/ironbank-validation.groovy
  .ci/jobs/beats-release-changelog.yml
  .ci/jobs/beats-release-minor-major-project.yml
  .ci/jobs/beats-release-minor-major.yml
  .ci/jobs/beats-release-patch-project.yml
  .ci/jobs/beats-release-patch.yml
  .ci/jobs/beats-schedule-daily.yml
  .ci/jobs/beats-schedule-weekly.yml
  .ci/jobs/beats-test-infra.yml
  .ci/jobs/beats-tester-bc.yml
  .ci/jobs/beats-tester.yml
  .ci/jobs/beats.yml
  .ci/jobs/build-it-docker-images.yml
  .ci/jobs/defaults.yml
  .ci/jobs/folders.yml
  .ci/jobs/ironbank-validation.yml
  .ci/jobs/packaging.yml
  .ci/packaging.groovy
  .ci/packer_cache.sh
  .ci/schedule-daily.groovy
  .ci/schedule-weekly.groovy
  .ci/scripts/generate_build_table.py
  .editorconfig
  .github/paths-labeller.yml
  Jenkinsfile
  Jenkinsfile.yml
  README.md
  dev-tools/common.bash
  dev-tools/find_pr_jenkins_jobs.sh
  dev-tools/jenkins_ci.sh
  dev-tools/jenkins_intake.sh
  dev-tools/jenkins_release.sh
  docs/devguide/terraform.asciidoc
  filebeat/scripts/jenkins/unit-test.sh
  libbeat/.gitignore
  x-pack/filebeat/Jenkinsfile.yml
  x-pack/metricbeat/Jenkinsfile.yml
Labels: Team:Automation, release-note:skip, Team:Elastic-Agent-Data-Plane, backport-8.x

#40870 [AWS CloudWatch Metrics] Record previous endTime to use for next collection period
  CHANGELOG-developer.next.asciidoc
  x-pack/metricbeat/module/aws/billing/billing.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch_test.go
  x-pack/metricbeat/module/aws/utils.go
  x-pack/metricbeat/module/aws/utils_test.go
Labels: Team:obs-ds-hosted-services, backport-8.15, backport-8.x

#40912 x-pack/filebeat/input/cel: make http functions always available
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/cel/config.go
  x-pack/filebeat/input/cel/input.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-8.x

#40918 x-pack/metricbeat/module/gcp: Override GCP API endpoint in metric client
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/gcp.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/gcp/_meta/config.yml
  x-pack/metricbeat/module/gcp/_meta/docs.asciidoc
  x-pack/metricbeat/module/gcp/metrics/metricset.go
  x-pack/metricbeat/modules.d/gcp.yml.disabled
Labels: Team:obs-ds-hosted-services, Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, backport-8.x

#40935 Update beats-ci references in README
  README.md
Labels: Team:Ingest-EngProd, backport-8.x

#40838 x-pack/filebeat/input/streaming: add falcon hose stream follower
  .github/CODEOWNERS
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-streaming.asciidoc
  x-pack/filebeat/input/streaming/config.go
  x-pack/filebeat/input/streaming/crowdstrike.go
  x-pack/filebeat/input/streaming/crowdstrike_test.go
  x-pack/filebeat/input/streaming/input.go
Labels: enhancement, Filebeat, Team:Elastic-Agent-Data-Plane, Team:Security-Service Integrations, backport-8.x

#40238 Go-based changeset definition for MODULE
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/scripts/changesets.psm1
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
  dev-tools/mage/module_changeset.go
  metricbeat/magefile.go
  x-pack/auditbeat/magefile.go
  x-pack/metricbeat/magefile.go
Labels: :Windows, ci, backport-7.17, Team:Ingest-EngProd, backport-v8.14.0, backport-8.15, backport-8.x

#40951 add agentbeat spec sections for new meraki and panw modules
  x-pack/agentbeat/agentbeat.spec.yml
Labels: needs_team, backport-8.15, backport-8.x

#40956 switch to elastic fsnotify fork
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#40955 Update prometheus dependencies to be in-sync with OTel
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/helper/socket/ptable.go
  x-pack/auditbeat/processors/sessionmd/procfs/procfs.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#40560 Add pre-commit step to beats pipelines
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: :Windows, ci, arm, Team:Ingest-EngProd, backport-8.x

#40981 Revert "[8.x](backport #40909) [filebeat] Fix long filepaths in diagnostics exceeding max path limits on Windows"
  CHANGELOG.next.asciidoc
  filebeat/input/v2/compat/compat.go
  filebeat/input/v2/input-cursor/input.go
  filebeat/input/v2/input.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
  x-pack/filebeat/input/entityanalytics/provider/jamf/jamf.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/input_test.go
Labels: needs_team

#40963 Change codeowners from ent-search-application to app-search-team
  .github/CODEOWNERS
Labels: backport, needs_team, backport-8.x

#40965 Add pre-commit to x-pack/agentbeat
  .buildkite/x-pack/pipeline.xpack.agentbeat.yml
Labels: ci, Team:Ingest-EngProd, backport-8.15, backport-8.x

#40976 [8.15] Add missing changelog for connection recovery fix
  CHANGELOG.next.asciidoc
Labels: Team:Elastic-Agent-Data-Plane

#40980 Revert "[filebeat] Fix long filepaths in diagnostics exceeding max path limits on Windows"
  CHANGELOG.next.asciidoc
  filebeat/input/v2/compat/compat.go
  filebeat/input/v2/input-cursor/input.go
  filebeat/input/v2/input.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
  x-pack/filebeat/input/entityanalytics/provider/jamf/jamf.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/input_test.go
Labels: Team:Elastic-Agent, backport-skip

#40990 Add Buildkite trigger context annotation
  .buildkite/hooks/pre-command
Labels: ci, backport-7.17, Team:Ingest-EngProd, backport-8.15, backport-8.x

#40993 Don't register cfgfile flags on `flag.CommandLine` in `func init()`
  libbeat/cfgfile/cfgfile.go
  libbeat/cmd/instance/beat_integration_test.go
  libbeat/cmd/root.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#40996 Revert "Revert "[filebeat] Fix long filepaths in diagnostics exceeding max path limits on Windows""
  CHANGELOG.next.asciidoc
  filebeat/input/v2/compat/compat.go
  filebeat/input/v2/input-cursor/input.go
  filebeat/input/v2/input.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
  x-pack/filebeat/input/entityanalytics/provider/jamf/jamf.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/input_test.go
Labels: needs_team, backport-8.x

#41009 Revert "[winlogbeat] Add handling for missing event data types in the experimental API"
  CHANGELOG.next.asciidoc
  winlogbeat/sys/strings.go
  winlogbeat/sys/strings_test.go
  winlogbeat/sys/strings_windows.go
  winlogbeat/sys/wineventlog/syscall_windows.go
  winlogbeat/sys/zsyscall_windows.go
  winlogbeat/sys/zsyscall_windows_test.go
Labels: Team:Security-Windows Platform, backport-8.x

#41011 Add missing changelog for ES fix.
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
Labels: needs_team

#41016 Adjust beats-packaging-pipeline to trigger on 8.x
  catalog-info.yaml
Labels: Team:Ingest-EngProd, backport-8.x

#40968 Restore docker.network.in.* and docker.network.out.* fields in docker module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/docker/fields.go
  metricbeat/module/docker/network/_meta/fields.yml
  metricbeat/module/docker/network/data.go
  metricbeat/module/docker/network/helper.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.15, 8.16-candidate, backport-8.x

#41021 Enable type assertion checks
  .golangci.yml
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#40992 Fix nil pointer deref if the file output lacks a `path` setting.
  libbeat/outputs/fileout/config.go
  libbeat/outputs/fileout/config_test.go
  libbeat/outputs/fileout/pathformatstring.go
  libbeat/outputs/fileout/pathformatstring_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-8.x

#40983 Update README.md
  libbeat/autodiscover/README.md
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41014 Fix prometheus imports to match OTel
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/helper/openmetrics/openmetrics.go
  metricbeat/helper/prometheus/prometheus.go
  metricbeat/helper/prometheus/textparse.go
  metricbeat/helper/prometheus/textparse_test.go
  metricbeat/module/docker/image/image.go
  metricbeat/module/openmetrics/collector/collector.go
  metricbeat/module/openmetrics/collector/collector_test.go
  metricbeat/module/openmetrics/collector/data.go
  metricbeat/module/prometheus/collector/collector.go
  metricbeat/module/prometheus/collector/collector_test.go
  x-pack/libbeat/autodiscover/providers/nomad/nomad_test.go
  x-pack/libbeat/common/nomad/metadata_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x
