Repository elastic/beats, pull requests merged in 2024-11, with the labels that each got.

#41449 Use optional values for docker memory metrics
  CHANGELOG.next.asciidoc
  metricbeat/module/docker/memory/_meta/data.json
  metricbeat/module/docker/memory/data.go
  metricbeat/module/docker/memory/helper.go
  metricbeat/module/docker/memory/memory_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, Team:Security-External Integrations, backport-8.x

#41418 [winlogbeat] Add handling for missing event data types in the experimental API
  CHANGELOG.next.asciidoc
  winlogbeat/sys/strings.go
  winlogbeat/sys/strings_test.go
  winlogbeat/sys/strings_windows.go
  winlogbeat/sys/wineventlog/syscall_windows.go
  winlogbeat/sys/zsyscall_windows.go
  winlogbeat/sys/zsyscall_windows_test.go
Labels: enhancement, Winlogbeat, Team:Elastic-Agent-Data-Plane, Team:Security-Windows Platform, backport-8.x

#40637 Bug: fix slice init length
  libbeat/processors/fingerprint/fingerprint_test.go
  libbeat/processors/ratelimit/limit.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.15, backport-8.x

#41460 x-pack/filebeat/input/entityanalytics/provider/okta: add support for role and factor data collection
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/okta/conf.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go
  x-pack/filebeat/input/entityanalytics/provider/okta/statestore.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-8.x

#41509 Adjust weekly macOS pipeline
  .buildkite/hooks/pre-command
  catalog-info.yaml
Labels: ci, backport-skip, Team:Ingest-EngProd

#41519 Update contributing.asciidoc
  docs/devguide/contributing.asciidoc
Labels: docs, Team:Elastic-Agent-Data-Plane, backport-8.x

#41530 [libbeat]: Add support for `values` in lowercase processor
  CHANGELOG.next.asciidoc
  libbeat/processors/actions/alterFieldProcessor.go
  libbeat/processors/actions/docs/lowercase.asciidoc
  libbeat/processors/actions/lowercase.go
  libbeat/processors/actions/lowercase_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-8.x

#41472 [libbeat] Add translate_ldap_attribute processor
  .github/CODEOWNERS
  CHANGELOG.next.asciidoc
  filebeat/tests/integration/translate_ldap_attribute_test.go
  libbeat/cmd/instance/imports_common.go
  libbeat/docs/processors-list.asciidoc
  libbeat/processors/translate_ldap_attribute/config.go
  libbeat/processors/translate_ldap_attribute/doc.go
  libbeat/processors/translate_ldap_attribute/docs/translate_ldap_attribute.asciidoc
  libbeat/processors/translate_ldap_attribute/ldap.go
  libbeat/processors/translate_ldap_attribute/translate_ldap_attribute.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, Team:Security-Windows Platform, backport-8.x

#41504 Fix handling of custom endpoints in AWS input
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/input_test.go
  x-pack/filebeat/input/awss3/s3.go
  x-pack/filebeat/input/awss3/sqs.go
  x-pack/filebeat/input/awss3/sqs_input.go
Labels: bug, aws, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.16

#41541 go.mod - use elastic/goja fork
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41535 [libbeat]: add uppercase processor
  CHANGELOG.next.asciidoc
  libbeat/processors/actions/docs/uppercase.asciidoc
  libbeat/processors/actions/lowercase_test.go
  libbeat/processors/actions/uppercase.go
  libbeat/processors/actions/uppercase_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-8.x

#41551 Add support for region/zone for Vertex AI service in GCP module
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/gcp/constants.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester_test.go
Labels: enhancement, needs_team, backport-8.x

#41523 otelconsumer: handle entity too large errors
  libbeat/outputs/otelconsumer/otelconsumer.go
  libbeat/outputs/otelconsumer/otelconsumer_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-8.x

#41563 Put full version of Go in go.mod while updating
  .github/workflows/updatecli.d/bump-golang.yml
  go.mod
Labels: bug, Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane, backport-8.x

#41580 [chore][metricbeat/test_diskio]: fix CI failure
  metricbeat/module/system/test_system.py
  metricbeat/tests/system/metricbeat.py
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41572 [aws] Set region in config from GetBucketLocation API call
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/s3.go
  x-pack/filebeat/input/awss3/s3_input.go
Labels: Team:obs-ds-hosted-services, backport-8.15, backport-8.x, backport-8.16

#41581 [packetbeat] Expire source port mappings.
  CHANGELOG.next.asciidoc
  packetbeat/procs/procs.go
Labels: bugfix, Team:Security-Linux Platform, backport-8.x

#41299 [Release] Update version to 8.16.1
  libbeat/version/version.go
Labels: release, Team:Elastic-Agent-Data-Plane

#41298 [Release] Update test environments for 8.16.1
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Elastic-Agent-Data-Plane

#41233 [Metricbeat][Aerospike] Add support for basic auth
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/docs/modules/aerospike.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/aerospike/_meta/Dockerfile
  metricbeat/module/aerospike/_meta/config.reference.yml
  metricbeat/module/aerospike/_meta/config.yml
  metricbeat/module/aerospike/_meta/docs.asciidoc
  metricbeat/module/aerospike/aerospike.go
  metricbeat/module/aerospike/aerospike_test.go
  metricbeat/module/aerospike/docker-compose.yml
  metricbeat/module/aerospike/namespace/namespace.go
  metricbeat/modules.d/aerospike.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: enhancement, Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, backport-8.x, backport-8.16

#41477 [AWS] [EC2] enrich events with EC2 tags with add_cloud_metadata processor
  CHANGELOG.next.asciidoc
  libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc
  libbeat/processors/add_cloud_metadata/provider_aws_ec2.go
  libbeat/processors/add_cloud_metadata/provider_aws_ec2_test.go
  libbeat/processors/add_cloud_metadata/providers.go
Labels: enhancement, Team:obs-ds-hosted-services, backport-8.x

#41616 Add concurrency groups for macOS steps
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
Labels: ci, macOS, Team:Ingest-EngProd, backport-8.15, backport-8.x, backport-8.16

#41619 Add concurrency groups to macOS steps on 7.17
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
Labels: ci, macOS, Team:Ingest-EngProd

#41633 Packaging pipeline mem bump
  .buildkite/packaging.pipeline.yml
Labels: Team:Ingest-EngProd, backport-8.x

#41585 filebeat: input v2 compat uses random ID for CheckConfig
  CHANGELOG.next.asciidoc
  filebeat/input/v2/compat/compat.go
  filebeat/input/v2/compat/compat_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-8.x

#41637 Bump elastic-agent-lib version to 0.17.3
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41640 libbeat: increase total_fields.limit to 12500
  CHANGELOG.asciidoc
  libbeat/template/load_test.go
  libbeat/template/template.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.16

#41622 [meraki] Log `getDevicePerformanceScores` errors
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/meraki/device_health/device_health.go
  x-pack/metricbeat/module/meraki/device_health/devices.go
Labels: Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, bugfix, backport-8.x

#41639 [winlogbeat] Implement exclusion range support for event_id
  CHANGELOG.next.asciidoc
  winlogbeat/docs/winlogbeat-options.asciidoc
  winlogbeat/sys/wineventlog/query.go
  winlogbeat/sys/wineventlog/query_test.go
Labels: enhancement, Winlogbeat, Team:Security-Windows Platform, backport-8.x

#41505 [filebeat][gcs] - Added input metrics
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-gcs.asciidoc
  x-pack/filebeat/input/gcs/decoding_test.go
  x-pack/filebeat/input/gcs/input.go
  x-pack/filebeat/input/gcs/input_stateless.go
  x-pack/filebeat/input/gcs/input_test.go
  x-pack/filebeat/input/gcs/job.go
  x-pack/filebeat/input/gcs/metrics.go
  x-pack/filebeat/input/gcs/metrics_test.go
  x-pack/filebeat/input/gcs/scheduler.go
  x-pack/filebeat/input/gcs/state.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-8.x, input:GCS

#41584 [libbeat] Go Benchmarks comparing compress/gzip and klauspost/compress
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  libbeat/esleg/eslegclient/enc.go
  libbeat/internal/testutil/util.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/processors/actions/lowercase_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41555 Journald support for System module
  CHANGELOG.next.asciidoc
  filebeat/docs/include/use-journald.asciidoc
  filebeat/docs/modules/system.asciidoc
  filebeat/filebeat.reference.yml
  filebeat/module/system/README.md
  filebeat/module/system/_meta/config.reference.yml
  filebeat/module/system/_meta/config.yml
  filebeat/module/system/_meta/docs.asciidoc
  filebeat/module/system/auth/config/auth.yml
  filebeat/module/system/auth/ingest/entrypoint.yml
  filebeat/module/system/auth/ingest/files.yml
  filebeat/module/system/auth/ingest/grok-auth-messages.yml
  filebeat/module/system/auth/ingest/journald.yml
  filebeat/module/system/auth/ingest/pipeline.yml
  filebeat/module/system/auth/manifest.yml
  filebeat/module/system/auth/test/debian-12.export
  filebeat/module/system/auth/test/debian-12.journal-expected.json
  filebeat/module/system/syslog/config/syslog.yml
  filebeat/module/system/syslog/ingest/entrypoint.yml
  filebeat/module/system/syslog/ingest/files.yml
  filebeat/module/system/syslog/ingest/journald.yml
  filebeat/module/system/syslog/ingest/pipeline.yml
  filebeat/module/system/syslog/manifest.yml
  filebeat/module/system/syslog/test/debian-12.export
  filebeat/module/system/syslog/test/debian-12.journal-expected.json
  filebeat/modules.d/system.yml.disabled
  filebeat/tests/system/test_modules.py
  x-pack/filebeat/filebeat.reference.yml
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-8.x

#41540 Update input-kafka.asciidoc to indicate required version for Kafka 4.0
  filebeat/docs/inputs/input-kafka.asciidoc
  libbeat/outputs/kafka/docs/kafka.asciidoc
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41600 x-pack/filebeat/input/streaming: fix missing key in streaming input logging
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/streaming/crowdstrike.go
  x-pack/filebeat/input/streaming/websocket.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-8.x, backport-8.16

#41607 sql: Fix incorrect handling of types
  CHANGELOG.next.asciidoc
  metricbeat/helper/sql/sql.go
  metricbeat/helper/sql/sql_test.go
  x-pack/metricbeat/module/sql/query/query.go
Labels: Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, bugfix, backport-8.x

#41570 Metricbeat: add configurable failure threshold before reporting streams as degraded
  metricbeat/mb/module/wrapper.go
  metricbeat/mb/module/wrapper_internal_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-8.x

#41495 x-pack/filebeat/input/awss3: support for Access Point ARN
  CHANGELOG.next.asciidoc
  x-pack/filebeat/_meta/config/filebeat.inputs.reference.xpack.yml.tmpl
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/config_test.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/s3.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-8.x, backport-8.16

#41542 Switch to base 16 for TLS serial number in packetbeat in line with ECS changes
  CHANGELOG.next.asciidoc
  packetbeat/protos/tls/parse.go
  packetbeat/protos/tls/parse_test.go
  packetbeat/protos/tls/tls_test.go
  packetbeat/tests/system/golden/established_tls-expected.json
  packetbeat/tests/system/golden/tls_all_options-expected.json
Labels: bug, Team:Security-Linux Platform, backport-8.x, backport-8.16

#41662 set default value of kafka version to 2.1.0
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-kafka.asciidoc
  filebeat/input/kafka/config.go
  libbeat/outputs/kafka/config.go
  libbeat/outputs/kafka/docs/kafka.asciidoc
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#41733 Add known issue for AWS S3 input (target 8.15)
  CHANGELOG.asciidoc
Labels: docs, Team:Docs

#41735 Add known issue for AWS S3 input (target 8.16)
  CHANGELOG.asciidoc
Labels: docs, Team:Docs

#41727 mod: update elastic/mito to version v1.16.0
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-8.x

#41571 Add debug logging statements to auditbeat system/socket metricset
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/module/system/socket/state.go
Labels: Team:Security-Linux Platform, backport-8.x

#41750 Bump github.com/elastic/go-sysinfo to v1.15.0
  NOTICE.txt
  go.mod
  go.sum
Labels: dependency, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.16, backport-8.17

#41698 metricbeat: add integration TestIndexTotalFieldsLimitNotReached
  x-pack/metricbeat/tests/integration/setup_integration_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.15, backport-8.x, backport-8.16

#41558 go.mod - update to go-libaudit v2.6.1
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: Auditbeat, Team:Security-Linux Platform, backport-8.x

#41525 [winlogbeat] Add missing functionality to experimental API
  CHANGELOG.next.asciidoc
  libbeat/processors/decode_xml_wineventlog/config.go
  libbeat/processors/decode_xml_wineventlog/decoder.go
  libbeat/processors/decode_xml_wineventlog/decoder_windows.go
  libbeat/processors/decode_xml_wineventlog/docs/decode_xml_wineventlog.asciidoc
  libbeat/processors/decode_xml_wineventlog/processor.go
  winlogbeat/docs/winlogbeat-options.asciidoc
  winlogbeat/eventlog/bench_test.go
  winlogbeat/eventlog/cache.go
  winlogbeat/eventlog/wineventlog.go
  winlogbeat/eventlog/wineventlog_experimental.go
  winlogbeat/eventlog/wineventlog_test.go
  winlogbeat/sys/wineventlog/format_message_test.go
  winlogbeat/sys/wineventlog/metadata_store.go
  winlogbeat/sys/wineventlog/metadata_store_test.go
  winlogbeat/sys/wineventlog/publisher_metadata.go
  winlogbeat/sys/wineventlog/publisher_metadata_test.go
  winlogbeat/sys/wineventlog/renderer.go
  winlogbeat/sys/wineventlog/renderer_test.go
  winlogbeat/sys/wineventlog/testdata/4738.evtx
  winlogbeat/sys/wineventlog/util_test.go
  winlogbeat/sys/wineventlog/wineventlog_windows.go
Labels: enhancement, Winlogbeat, Team:Security-Windows Platform, backport-8.x

#41755 [AWS] [S3] fix: improve object size metric calculation
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/metrics.go
  x-pack/filebeat/input/awss3/s3_objects.go
  x-pack/filebeat/input/awss3/s3_objects_test.go
Labels: bug, Team:obs-ds-hosted-services, backport-8.x, backport-8.16

#41780 Update users page to link to ILM where applicable
  libbeat/docs/security/users.asciidoc
Labels: Team:Docs, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17

#41559 go.mod - update to elastic/go-seccomp-bpf v1.5.0
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41636 [libbeat] fix: aws & openstack metadata conflict in add_cloud_metadata processor
  CHANGELOG.next.asciidoc
  libbeat/processors/add_cloud_metadata/docs/add_cloud_metadata.asciidoc
  libbeat/processors/add_cloud_metadata/provider_alibaba_cloud.go
  libbeat/processors/add_cloud_metadata/provider_aws_ec2.go
  libbeat/processors/add_cloud_metadata/provider_azure_vm.go
  libbeat/processors/add_cloud_metadata/provider_digital_ocean.go
  libbeat/processors/add_cloud_metadata/provider_google_gce.go
  libbeat/processors/add_cloud_metadata/provider_hetzner_cloud.go
  libbeat/processors/add_cloud_metadata/provider_openstack_nova.go
  libbeat/processors/add_cloud_metadata/provider_tencent_cloud.go
  libbeat/processors/add_cloud_metadata/providers.go
  libbeat/processors/add_cloud_metadata/providers_test.go
Labels: bug, Team:obs-ds-hosted-services, backport-8.x, backport-8.16

#41765 x-pack/filebeat/input/http_endpoint: fix handling of http_endpoint request exceeding memory limits
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
  x-pack/filebeat/input/http_endpoint/config.go
  x-pack/filebeat/input/http_endpoint/handler.go
  x-pack/filebeat/input/http_endpoint/handler_test.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/http_endpoint/input_test.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, 8.16-candidate, backport-8.x, backport-8.16, backport-8.17

#41618 Update catalog-info file with correct system property
  catalog-info.yaml
Labels: skip-ci, backport-7.17, Team:Ingest-EngProd, backport-8.x

#41824 Fix Kafka output panic at startup
  libbeat/outputs/kafka/client.go
  libbeat/outputs/kafka/kafka_integration_test.go
  libbeat/outputs/redis/backoff.go
  libbeat/outputs/redis/client.go
  libbeat/tests/integration/kafka_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17

#41655 Update Beats to the current Sarama fork
  NOTICE.txt
  filebeat/input/kafka/config.go
  filebeat/input/kafka/input.go
  filebeat/input/kafka/kafka_integration_test.go
  go.mod
  go.sum
  libbeat/common/kafka/sasl.go
  libbeat/common/kafka/version.go
  libbeat/common/kafka/version_test.go
  libbeat/outputs/kafka/client.go
  libbeat/outputs/kafka/config.go
  libbeat/outputs/kafka/kafka.go
  libbeat/outputs/kafka/kafka_integration_test.go
  libbeat/outputs/kafka/log.go
  libbeat/outputs/kafka/message.go
  libbeat/outputs/kafka/partition.go
  libbeat/outputs/kafka/partition_test.go
  libbeat/tests/integration/kafka_test.go
  metricbeat/module/jolokia/_meta/Dockerfile
  metricbeat/module/jolokia/docker-compose.yml
  metricbeat/module/kafka/README.md
  metricbeat/module/kafka/broker.go
  metricbeat/module/kafka/consumergroup/consumergroup.go
  metricbeat/module/kafka/consumergroup/consumergroup_integration_test.go
  metricbeat/module/kafka/consumergroup/mock_test.go
  metricbeat/module/kafka/consumergroup/query.go
  metricbeat/module/kafka/docker-compose.yml
  metricbeat/module/kafka/partition/partition.go
  metricbeat/module/kafka/partition/partition_integration_test.go
  testing/environments/docker/kafka/Dockerfile
Labels: backport-skip, Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, backport-8.x

#41809 Update testing.asciidoc
  docs/devguide/testing.asciidoc
Labels: docs, Team:Elastic-Agent-Data-Plane, backport-8.x
