Repository elastic/beats, pull requests merged in 2024-05, with the labels that each got.

#38695 .github/dependabot.yml - add elastic/ebpfevents
  .github/dependabot.yml
Labels: needs_team, dependabot

#39335 Allow everyone in Elastic to build Beats
  catalog-info.yaml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39332 More resilient DRA packaging
  .buildkite/packaging.pipeline.yml
  catalog-info.yaml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39344 [updatecli] update elastic stack version for testing 7.17.21-48567783
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39343 [updatecli] update elastic stack version for testing 8.13.3-dae2338c
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39342 [updatecli] update elastic stack version for testing 8.15.0-aa640648
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39174 Enabling retries for Beats flaky tests
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: :Windows, macOS, arm, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39243 [Auditbeat][add_session_metadata processor] Fix more potential enrichment failures
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/processors/sessionmd/add_session_metadata.go
  x-pack/auditbeat/processors/sessionmd/processdb/db.go
  x-pack/auditbeat/processors/sessionmd/provider/ebpf_provider/ebpf_provider.go
  x-pack/auditbeat/processors/sessionmd/provider/procfs_provider/procfs_provider.go
  x-pack/auditbeat/processors/sessionmd/provider/procfs_provider/procfs_provider_test.go
  x-pack/auditbeat/processors/sessionmd/provider/provider.go
Labels: bugfix, Team:Security-Deployment and Devices, backport-v8.14.0

#39312 [Release] Update version to 8.13.4
  libbeat/version/version.go
Labels: release, Team:Automation

#39309 docs: update docs versions 8.13.3
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#39314 [Release] Update version to 7.17.22
  libbeat/version/version.go
Labels: release, Team:Automation

#39310 docs: update docs versions 7.17.21
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
  deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#39345 Update catalog-info from main
  catalog-info.yaml
Labels: ci, Team:Ingest-EngProd

#39346 Update catalog-info from main
  catalog-info.yaml
Labels: ci, Team:Ingest-EngProd

#39347 Update catalog-info from main
  catalog-info.yaml
Labels: ci, Team:Ingest-EngProd

#39361 [Auditbeat/FIM/kprobes]: allow extra syscalls by auditbeat required in FIM with kprobes
  CHANGELOG.next.asciidoc
  auditbeat/module/file_integrity/kprobes/probes_fsnotify_nameremove.go
  auditbeat/module/file_integrity/kprobes/seccomp_linux.go
  auditbeat/tests/system/test_file_integrity.py
Labels: bug, Team:Security-Linux Platform, backport-v8.13.0, backport-v8.14.0

#39187 Remove python dynamic pipeline scripts
  .buildkite/buildkite.yml
  .buildkite/pipeline.py
  .buildkite/pytest.ini
  .buildkite/scripts/run_dynamic_pipeline_tests.sh
  .buildkite/test_pipeline.py
  auditbeat/buildkite.yml
  filebeat/buildkite.yml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39357 docs: Prepare Changelog for 7.17.21
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation

#39356 docs: Prepare Changelog for 8.13.3
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, forwardport-main

#39245 Update auditbeat pipeline to match Jenkins steps
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/hooks/pre-command
Labels: :Windows, :integrations, macOS, arm, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39362 [Auditbeat/FIM/fsnotify]: prevent losing events for recursive mode on OS X
  CHANGELOG.next.asciidoc
  auditbeat/module/file_integrity/monitor/monitor_test.go
  auditbeat/module/file_integrity/monitor/recursive.go
Labels: bug, backport-v7.17.0, Team:Security-Linux Platform, backport-v8.13.0, backport-v8.14.0

#39379 [updatecli] update elastic stack version for testing 7.17.21-86bc1e1e
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39377 [updatecli] update elastic stack version for testing 8.15.0-7f8575f3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39378 [updatecli] update elastic stack version for testing 8.13.3-6dd01262
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39327 `aws-s3` input: fix SQS region selection
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_test.go
Labels: bug, Team:Elastic-Agent, Team:Cloud-Monitoring

#39386 Auto trigger DRA for all 8.x branches
  catalog-info.yaml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39391 Disable DRY_RUN for 8.13 packaging on Buildkite
  .buildkite/scripts/dra.sh
Labels: ci, Team:Ingest-EngProd

#39387 Disable 8.x DRA packaging from Jenkins
  .ci/jobs/packaging.yml
Labels: ci, Team:Automation, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39330 Add disruptive change mitigations section to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: backport-skip, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane

#39399 [updatecli] update elastic stack version for testing 7.17.21-4f451c48
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39401 [updatecli] update elastic stack version for testing 8.15.0-3eefdcff
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39400 [updatecli] update elastic stack version for testing 8.13.3-76ce1a63
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39380 [updatecli] update elastic stack version for testing 8.14.0-ba404a5d
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39329 x-pack/filebeat/input/http_endpoint: ensure all responses are HTML-escaped
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/http_endpoint/input.go
Labels: enhancement, Filebeat, backport-skip, Team:Security-Service Integrations

#39313 [Release] Update test environments for 8.13.4
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#39315 [Release] Update test environments for 7.17.22
  metricbeat/docker-compose.yml
  metricbeat/module/logstash/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#39381 Filebeat inputs: remove the unused run mode in v2.InputManager.Init
  filebeat/beater/filebeat.go
  filebeat/input/filestream/environment_test.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/v2/input-cursor/manager.go
  filebeat/input/v2/input-cursor/manager_test.go
  filebeat/input/v2/input-stateless/stateless.go
  filebeat/input/v2/input.go
  filebeat/input/v2/internal/inputest/inputest.go
  filebeat/input/v2/loader.go
  filebeat/input/v2/loader_test.go
  filebeat/input/v2/mode_string.go
  filebeat/input/v2/simplemanager.go
  filebeat/input/v2/util_test.go
  x-pack/filebeat/input/awscloudwatch/input.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/cel/input_manager.go
  x-pack/filebeat/input/entityanalytics/input.go
  x-pack/filebeat/input/entityanalytics/input_test.go
  x-pack/filebeat/input/entityanalytics/internal/kvstore/manager.go
  x-pack/filebeat/input/entityanalytics/internal/kvstore/manager_test.go
  x-pack/filebeat/input/httpjson/input_manager.go
  x-pack/filebeat/input/netflow/input.go
  x-pack/filebeat/input/salesforce/input_manager.go
  x-pack/filebeat/input/salesforce/input_manager_test.go
  x-pack/filebeat/input/shipper/input.go
  x-pack/filebeat/input/websocket/input_manager.go
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane, Team:Cloud-Monitoring, Team:Service-Integrations, Team:Security-Deployment and Devices

#39415 [updatecli] update elastic stack version for testing 7.17.22-3712b6ed
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39416 [updatecli] update elastic stack version for testing 8.14.0-c743e4c8
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39417 [updatecli] update elastic stack version for testing 8.15.0-b7cc7ef3
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39239 Update x-pack/heartbeat pipeline to match Jenkins
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
Labels: :Windows, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39428 Disable 7.17 DRA packaging from Jenkins
  .ci/jobs/packaging.yml
Labels: ci, Team:Automation, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39429 Disable DRY_RUN for 7.17 packaging on Buildkite
  .buildkite/scripts/dra.sh
Labels: ci, Team:Ingest-EngProd

#39224 [7.17 backport] Update elastic-agent-client used in 7.17 releases
  NOTICE.txt
  go.mod
  go.sum
  x-pack/elastic-agent/pkg/core/server/server.go
Labels: technical debt, dependency, Team:Elastic-Agent-Control-Plane

#39441 [updatecli] update elastic stack version for testing 7.17.22-60b5dd1b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39443 [updatecli] update elastic stack version for testing 8.14.0-6d69ee76
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39442 [updatecli] update elastic stack version for testing 8.15.0-177234da
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39440 [updatecli] update elastic stack version for testing 8.13.4-cc6fca83
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39235 Add MODULE definition for x-pack/dockerlogbeat Go Integration tests
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/setenv.sh
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
Labels: backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39420 x-pack/filebeat/input/entityanalytics/provider/azuread: fix query handling
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/input_test.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-v8.13.0, backport-v8.14.0

#39316 Add kubernetes.pod.status_reason and kubernetes.pod.status.ready_time fields in Kubernetes state_pod metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/kubernetes/_meta/test/KSM/ksm.v2.12.0.plain
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/state_pod/_meta/data.json
  metricbeat/module/kubernetes/state_pod/_meta/fields.yml
  metricbeat/module/kubernetes/state_pod/_meta/test/ksm.v2.10.0.plain.expected
  metricbeat/module/kubernetes/state_pod/_meta/test/ksm.v2.11.0.plain.expected
  metricbeat/module/kubernetes/state_pod/_meta/test/ksm.v2.12.0.plain.expected
  metricbeat/module/kubernetes/state_pod/_meta/testdata/docs.plain-expected.json
  metricbeat/module/kubernetes/state_pod/_meta/testdata/ksm.v2.10.0.plain-expected.json
  metricbeat/module/kubernetes/state_pod/_meta/testdata/ksm.v2.11.0.plain-expected.json
  metricbeat/module/kubernetes/state_pod/_meta/testdata/ksm.v2.12.0.plain-expected.json
  metricbeat/module/kubernetes/state_pod/state_pod.go
Labels: Team:Cloudnative-Monitoring

#39436 docs: Prepare Changelog for 8.13.4
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
  libbeat/docs/release.asciidoc
Labels: docs, in progress, release, automation, Team:Automation, forwardport-main

#39464 Remove unused Buildkite scripts (part 1)
  .buildkite/scripts/crosscompile.sh
  .buildkite/scripts/install_tools.sh
  .buildkite/scripts/stress_tests.sh
  .buildkite/scripts/unit_tests.sh
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39467 [Automation] Bump Golang version to 1.21.10
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  auditbeat/Dockerfile
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  go.mod
  heartbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  metricbeat/module/nats/_meta/Dockerfile
  metricbeat/module/vsphere/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/functionbeat/Dockerfile
  x-pack/metricbeat/module/stan/_meta/Dockerfile
Labels: Team:Elastic-Agent, backport-skip

#39460 mod: update elastic/mito to version v1.11.0
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: enhancement, Filebeat, backport-skip, bugfix, Team:Security-Service Integrations

#39468 [Automation][7.17] Bump Golang version to 1.21.10
  .go-version
  .golangci.yml
  CHANGELOG.next.asciidoc
  auditbeat/Dockerfile
  dev-tools/kubernetes/filebeat/Dockerfile.debug
  dev-tools/kubernetes/heartbeat/Dockerfile.debug
  dev-tools/kubernetes/metricbeat/Dockerfile.debug
  filebeat/Dockerfile
  heartbeat/Dockerfile
  libbeat/Dockerfile
  libbeat/docs/version.asciidoc
  metricbeat/Dockerfile
  metricbeat/module/http/_meta/Dockerfile
  metricbeat/module/nats/_meta/Dockerfile
  metricbeat/module/vsphere/_meta/Dockerfile
  packetbeat/Dockerfile
  x-pack/elastic-agent/pkg/agent/operation/tests/scripts/serviceable-1.0-darwin-x86_64/main.go
  x-pack/functionbeat/Dockerfile
  x-pack/libbeat/Dockerfile
  x-pack/metricbeat/module/stan/_meta/Dockerfile
Labels: needs_team, backport-skip

#39455 x-pack/filebeat/input/internal/httplog: improve req/resp logging
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/internal/httplog/roundtripper.go
Labels: enhancement, Filebeat, backport-v8.12.0, Team:Security-Service Integrations, backport-v8.13.0

#39437 [Release] Update version to 8.13.5
  libbeat/version/version.go
Labels: release, Team:Automation

#39434 docs: update docs versions 8.13.4
  deploy/kubernetes/auditbeat-kubernetes.yaml
  deploy/kubernetes/filebeat-kubernetes.yaml
  deploy/kubernetes/heartbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat-kubernetes.yaml
  libbeat/docs/version.asciidoc
Labels: docs, in progress, release, Team:Automation

#39295 Deploy/K8S pipeline post-migration fixes
  .buildkite/deploy/kubernetes/deploy-k8s-pipeline.yml
  .buildkite/deploy/kubernetes/scripts/install-kind.sh
  .buildkite/deploy/kubernetes/scripts/install-kubectl.sh
  .buildkite/deploy/kubernetes/scripts/make.sh
  .buildkite/deploy/kubernetes/scripts/setup-k8s-env.sh
  .buildkite/env-scripts/env.sh
  .buildkite/env-scripts/util.sh
  .buildkite/hooks/pre-command
  .buildkite/hooks/scripts/util.sh
  .buildkite/scripts/setenv.sh
Labels: kubernetes, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#38534 [DOCS] Add the `read_pipeline` cluster privilege to winlogbeat documentation
  libbeat/docs/security/api-keys.asciidoc
  libbeat/docs/security/users.asciidoc
Labels: bug, docs, Team:Automation, Team:Docs, Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane, backport-v8.13.0, backport-v8.14.0

#39483 ci(jenkins): remove post-build notifications
  Jenkinsfile
Labels: Team:Automation, backport-v7.17.0, backport-v8.13.0, backport-v8.14.0

#39353 `aws-s3` input: Split S3 poller and SQS reader into explicit input objects
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_benchmark_test.go
  x-pack/filebeat/input/awss3/input_test.go
  x-pack/filebeat/input/awss3/s3.go
  x-pack/filebeat/input/awss3/s3_input.go
  x-pack/filebeat/input/awss3/s3_objects.go
  x-pack/filebeat/input/awss3/s3_objects_test.go
  x-pack/filebeat/input/awss3/s3_test.go
  x-pack/filebeat/input/awss3/sqs.go
  x-pack/filebeat/input/awss3/sqs_input.go
  x-pack/filebeat/input/awss3/sqs_s3_event.go
  x-pack/filebeat/input/awss3/sqs_s3_event_test.go
  x-pack/filebeat/input/awss3/sqs_test.go
  x-pack/filebeat/input/awss3/states.go
  x-pack/filebeat/input/awss3/states_test.go
  x-pack/libbeat/common/aws/credentials.go
  x-pack/libbeat/common/aws/credentials_test.go
  x-pack/libbeat/common/aws/semaphore.go
  x-pack/libbeat/common/aws/semaphore_test.go
Labels: cleanup, Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane

#39500 Remove fields not needed for session view in add_session_view processor
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/processors/sessionmd/types/process.go
Labels: enhancement, backport-skip, Team:Security-Linux Platform

#39404 Add error check to groupToEvents so we don't blindly add error values
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/data.go
  metricbeat/module/windows/perfmon/data_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-v8.14.0

#39513 Fixed pipelines formatting
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: enhancement, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39510 Explicitly set DOCKER_PULL, RACE_DETECTOR and TEST_COVERAGE for pipelines
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/scripts/setenv.sh
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: enhancement, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39506 Remove hardcoded module definitions in CI
  .buildkite/metricbeat/pipeline.yml
  .buildkite/scripts/changesets.psm1
  .buildkite/scripts/changesets.sh
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39540 Allow dependabot report BK status checks
  .buildkite/pull-requests.json
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39545 Update pull-requests.json from main
  .buildkite/pull-requests.json
Labels: ci, Team:Ingest-EngProd

#39547 Update pull-requests.json from main
  .buildkite/pull-requests.json
Labels: ci, Team:Ingest-EngProd

#39533 [BK] - Remove certain steps from running for Branches
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39548 Update pull-requests.json from main
  .buildkite/pull-requests.json
Labels: ci, Team:Ingest-EngProd

#39552 [BK] - Remove osx steps from branch execution
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39534 Remove unused env vars from pipelines
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
Labels: cleanup, ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39503 x-pack/filebeat/input/cel: add http metrics collection
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/input.go
Labels: enhancement, Filebeat, backport-skip, Team:Security-Service Integrations

#39454 Fix the AWS SDK dependencies issue causing the "not found, ResolveEndpointV2" error
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/input/awss3/s3_objects_test.go
  x-pack/metricbeat/module/aws/utils.go
Labels: needs_team

#39569 Add next-major tests for auditbeat 7.17
  .buildkite/auditbeat/auditbeat-pipeline.yml
Labels: ci, Team:Ingest-EngProd

#39544 [winlogbeat] performance improvment; avoid rendering event message twice
  CHANGELOG.next.asciidoc
  winlogbeat/sys/wineventlog/format_message.go
  winlogbeat/sys/wineventlog/wineventlog_windows.go
Labels: enhancement, Team:Security-Windows Platform, backport-v8.13.0, backport-v8.14.0

#39571 [8.14](backport #39534) Remove unused env vars from pipelines
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
Labels: backport, ci, Team:Ingest-EngProd

#39560 Add prev-minor/next-major tests for filebeat 7.17
  .buildkite/filebeat/filebeat-pipeline.yml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39143 Osquerybeat: Add action responses data stream
  x-pack/osquerybeat/beater/action_handler.go
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/beater/resetable_action_handler.go
  x-pack/osquerybeat/beater/resetable_action_handler_test.go
  x-pack/osquerybeat/cmd/root.go
  x-pack/osquerybeat/cmd/root_test.go
  x-pack/osquerybeat/cmd/testdata/osquerycfg/legacy.in.json
  x-pack/osquerybeat/cmd/testdata/osquerycfg/legacy.out.json
  x-pack/osquerybeat/cmd/testdata/osquerycfg/legacy_with_osquery.in.json
  x-pack/osquerybeat/cmd/testdata/osquerycfg/legacy_with_osquery.out.json
  x-pack/osquerybeat/cmd/testdata/osquerycfg/two_streams.in.json
  x-pack/osquerybeat/cmd/testdata/osquerycfg/two_streams.out.json
  x-pack/osquerybeat/cmd/testdata/osquerycfg/two_streams_with_osquery.in.json
  x-pack/osquerybeat/cmd/testdata/osquerycfg/two_streams_with_osquery.out.json
  x-pack/osquerybeat/internal/config/config.go
  x-pack/osquerybeat/internal/pub/publisher.go
  x-pack/osquerybeat/internal/pub/publisher_test.go
Labels: enhancement, backport-skip, Team:Security-Deployment and Devices

#39472 updatecli: move to the .github folder and support for signed commits
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-golang.yml
  .github/workflows/updatecli.d/bump-elastic-stack-snapshot.yml
  .github/workflows/updatecli.d/bump-golang-7.17.yml
  .github/workflows/updatecli.d/bump-golang.yml
  .github/workflows/updatecli.d/scm.yml
Labels: needs_team, backport-v7.17.0, backport-v8.14.0

#39559 github-action: delete opentelemetry workflow
  .github/workflows/opentelemetry.yml
Labels: needs_team

#39568 Auditbeat: align Buildkite steps to match Jenkins
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/auditbeat/generate_auditbeat_pipeline.sh
Labels: ci, Team:Ingest-EngProd

#39538 [aws] Remove unused function newV2Context from input_test.go
  x-pack/filebeat/input/awss3/input_test.go
Labels: Team:obs-ds-hosted-services

#39537 [add_session_metadata processor] Enrich events with user and group names
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/processors/sessionmd/add_session_metadata.go
  x-pack/auditbeat/processors/sessionmd/add_session_metadata_test.go
  x-pack/auditbeat/processors/sessionmd/processdb/db.go
  x-pack/auditbeat/processors/sessionmd/processdb/names.go
  x-pack/auditbeat/processors/sessionmd/provider/ebpf_provider/ebpf_provider.go
  x-pack/auditbeat/processors/sessionmd/provider/procfs_provider/procfs_provider.go
  x-pack/auditbeat/processors/sessionmd/provider/procfs_provider/procfs_provider_test.go
  x-pack/auditbeat/processors/sessionmd/provider/provider.go
Labels: enhancement, backport-skip, Team:Security-Deployment and Devices

#39028 x-pack/filebeat/module/salesforce: Remove dashboards
  CHANGELOG.next.asciidoc
  filebeat/docs/images/filebeat-salesforce-login-dashboard.png
  filebeat/docs/images/filebeat-salesforce-logout-dashboard.png
  filebeat/docs/images/filebeat-salesforce-setupaudittrail-dashboard.png
  filebeat/docs/modules/salesforce.asciidoc
  x-pack/filebeat/module/salesforce/_meta/docs.asciidoc
  x-pack/filebeat/module/salesforce/_meta/kibana/7/dashboard/243e40b0-f891-11ee-9088-0f36517484ce.json
  x-pack/filebeat/module/salesforce/_meta/kibana/7/dashboard/6e6bee90-f7e6-11ee-9088-0f36517484ce.json
  x-pack/filebeat/module/salesforce/_meta/kibana/7/dashboard/c66be450-f891-11ee-9088-0f36517484ce.json
  x-pack/filebeat/module/salesforce/_meta/kibana/7/dashboard/cb7b4a40-f7ff-11ee-9088-0f36517484ce.json
  x-pack/filebeat/module/salesforce/_meta/kibana/7/map/15bcb8a0-f891-11ee-9088-0f36517484ce.json
  x-pack/filebeat/module/salesforce/_meta/kibana/7/map/c9668e10-f88e-11ee-9088-0f36517484ce.json
  x-pack/filebeat/module/salesforce/_meta/kibana/7/search/2752cec0-f804-11ee-9088-0f36517484ce.json
  x-pack/filebeat/module/salesforce/_meta/kibana/7/search/3e7187a0-f894-11ee-9088-0f36517484ce.json
  x-pack/filebeat/module/salesforce/module.yml
Labels: module, Filebeat, :Dashboards, Team:Obs-InfraObs

#39581 Libbeat: added module integration test step
  .buildkite/libbeat/pipeline.libbeat.yml
Labels: ci, Team:Ingest-EngProd

#38839 [Metricbeat][Kubernetes Volume] Add pvc reference to distinguish ephemeral from persistent volumes
  CHANGELOG.next.asciidoc
  metricbeat/module/kubernetes/_meta/test/stats_summary.json
  metricbeat/module/kubernetes/types.go
  metricbeat/module/kubernetes/volume/data.go
  metricbeat/module/kubernetes/volume/volume_test.go
Labels: Team:Cloudnative-Monitoring

#38710 [Metricbeat][MySQL] Performance metricset does not working with MySQL 5.7
  CHANGELOG.next.asciidoc
  metricbeat/module/mysql/performance/manifest.yml
Labels: bug, module, Metricbeat, Module:beat, Team:Obs-InfraObs, bugfix

#39535 [Heartbeat] Add stringer redaction to synthexec cmd
  CHANGELOG.next.asciidoc
  x-pack/heartbeat/monitors/browser/synthexec/synthcmd.go
  x-pack/heartbeat/monitors/browser/synthexec/synthcmd_test.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_linux.go
  x-pack/heartbeat/monitors/browser/synthexec/synthexec_test.go
Labels: bug, Team:obs-ds-hosted-services, v8.12.0, backport-v8.14.0

#39591 Migrate left over to buildkite
  .mergify.yml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39598 Restore macOS CI execution with merge commits
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .github/workflows/macos-auditbeat.yml
  .github/workflows/macos-filebeat.yml
  .github/workflows/macos-heartbeat.yml
  .github/workflows/macos-metricbeat.yml
  .github/workflows/macos-packetbeat.yml
  .github/workflows/macos-xpack-auditbeat.yml
  .github/workflows/macos-xpack-filebeat.yml
  .github/workflows/macos-xpack-functionbeat.yml
  .github/workflows/macos-xpack-heartbeat.yml
  .github/workflows/macos-xpack-metricbeat.yml
  .github/workflows/macos-xpack-osquerybeat.yml
  .github/workflows/macos-xpack-packetbeat.yml
Labels: ci, macOS, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39582 [updatecli] update elastic stack version for testing 7.17.22-f8bdfabc
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39561 [updatecli] update elastic stack version for testing 8.14.0-526ba7a5
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39587 x-pack/filebeat/input/cel: add default user-agent to http requests
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
Labels: enhancement, Filebeat, backport-skip, Team:Security-Service Integrations

#39588 filebeat,x-pack/filebeat: prevent master=>event.original rename failures
  CHANGELOG.next.asciidoc
  filebeat/module/santa/log/ingest/pipeline.yml
  x-pack/filebeat/module/checkpoint/firewall/ingest/pipeline.yml
  x-pack/filebeat/module/cisco/umbrella/ingest/pipeline.yml
  x-pack/filebeat/module/coredns/log/ingest/pipeline-json.yml
  x-pack/filebeat/module/iptables/log/ingest/pipeline.yml
  x-pack/filebeat/module/panw/panos/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/abusemalware/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/abuseurl/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/anomali/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/malwarebazaar/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/misp/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/otx/ingest/pipeline.yml
  x-pack/filebeat/module/threatintel/threatq/ingest/pipeline.yml
Labels: enhancement, Filebeat, backport-skip, Team:Security-Service Integrations, Team:Security-Deployment and Devices

#39410 x-pack/filebeat/input/http_endpoint: make input GA
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
  x-pack/filebeat/input/http_endpoint/ack.go
  x-pack/filebeat/input/http_endpoint/ack_test.go
  x-pack/filebeat/input/http_endpoint/handler.go
  x-pack/filebeat/input/http_endpoint/handler_test.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/http_endpoint/input_test.go
  x-pack/filebeat/input/lumberjack/ack.go
  x-pack/filebeat/tests/system/test_http_endpoint.py
Labels: enhancement, Filebeat, backport-skip, Team:Elastic-Agent-Data-Plane, Team:Security-Service Integrations

#39211 Update xpack/filebeat & xpack/metricbeat pipelines to match Jenkins steps
  .buildkite/scripts/setup_cloud_env.sh
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
Labels: :Windows, macOS, arm, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39603 [8.13](backport #39598) Restore macOS CI execution with merge commits
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .github/workflows/macos-auditbeat.yml
  .github/workflows/macos-filebeat.yml
  .github/workflows/macos-heartbeat.yml
  .github/workflows/macos-metricbeat.yml
  .github/workflows/macos-packetbeat.yml
  .github/workflows/macos-xpack-auditbeat.yml
  .github/workflows/macos-xpack-filebeat.yml
  .github/workflows/macos-xpack-functionbeat.yml
  .github/workflows/macos-xpack-heartbeat.yml
  .github/workflows/macos-xpack-metricbeat.yml
  .github/workflows/macos-xpack-osquerybeat.yml
  .github/workflows/macos-xpack-packetbeat.yml
Labels: ci, macOS, Team:Ingest-EngProd

#39616 Deleted old Agentbeat packaging pipeline
  catalog-info.yaml
Labels: enhancement, ci, backport-skip, Team:Ingest-EngProd

#39577 Osquerybeat: Follow up with changelog and unit test tweak for "Add action responses data stream PR"
  CHANGELOG.next.asciidoc
  x-pack/osquerybeat/internal/pub/publisher_test.go
Labels: docs, cleanup, backport-skip, Team:Security-Deployment and Devices

#39584 Remove shipper
  NOTICE.txt
  go.mod
  go.sum
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/outest/batch.go
  libbeat/outputs/shipper/README.md
  libbeat/outputs/shipper/api/shipper_mock.go
  libbeat/outputs/shipper/config.go
  libbeat/outputs/shipper/shipper.go
  libbeat/outputs/shipper/shipper_test.go
  libbeat/publisher/event.go
  libbeat/publisher/includes/includes.go
  libbeat/publisher/pipeline/ttl_batch.go
  libbeat/publisher/pipeline/ttl_batch_test.go
  libbeat/publisher/queue/diskqueue/benchmark_test.go
  libbeat/publisher/queue/diskqueue/config.go
  libbeat/publisher/queue/diskqueue/consumer.go
  libbeat/publisher/queue/diskqueue/queue.go
  libbeat/publisher/queue/diskqueue/segments.go
  libbeat/publisher/queue/diskqueue/serialize.go
  libbeat/publisher/queue/diskqueue/serialize_test.go
  libbeat/publisher/queue/memqueue/broker.go
  libbeat/publisher/queue/memqueue/queue_test.go
  libbeat/publisher/queue/queue.go
  x-pack/filebeat/cmd/agent.go
  x-pack/filebeat/cmd/root.go
  x-pack/filebeat/input/default-inputs/inputs_other.go
  x-pack/filebeat/input/default-inputs/inputs_windows.go
  x-pack/filebeat/input/shipper/acker.go
  x-pack/filebeat/input/shipper/config.go
  x-pack/filebeat/input/shipper/input.go
  x-pack/filebeat/input/shipper/server.go
  x-pack/filebeat/input/shipper/srv_unix.go
  x-pack/filebeat/input/shipper/srv_windows.go
  x-pack/filebeat/input/shipper/tools/test_unix.go
  x-pack/filebeat/input/shipper/tools/test_windows.go
  x-pack/filebeat/input/shipper/tools/tools.go
  x-pack/filebeat/tests/integration/shipper_test.go
  x-pack/libbeat/management/generate.go
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane

#39438 [Release] Update test environments for 8.13.5
  metricbeat/docker-compose.yml
  testing/environments/latest.yml
  x-pack/metricbeat/docker-compose.yml
Labels: release, Team:Automation

#39611 Fix module env var definition from changeset
  .buildkite/scripts/changesets.sh
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39617 [updatecli] update elastic stack version for testing 7.17.22-cc1e0082
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39562 [updatecli] update elastic stack version for testing 8.15.0-1a872dbc
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39618 [updatecli] update elastic stack version for testing 8.14.0-f5ce0819
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39635 Enable Slack notifications for main BK CI Job
  catalog-info.yaml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39622 Update libbeat pipeline to match Jenkins on 7.17 branch
  .buildkite/libbeat/pipeline.libbeat.yml
Labels: macOS, Team:Ingest-EngProd

#39649 [updatecli] update elastic stack version for testing 8.14.0-ede8ab2b
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39650 [updatecli] update elastic stack version for testing 8.15.0-9bce1e63
  testing/environments/snapshot.yml
Labels: automation, build-monitoring, dependency, backport-skip, Team:Beats-On-Call

#39585 Revert "[7.17 backport] Update elastic-agent-client used in 7.17 releases"
  NOTICE.txt
  go.mod
  go.sum
  x-pack/elastic-agent/pkg/core/server/server.go
Labels: bug, Team:Elastic-Agent

#39639 Update x-pack/auditbeat pipeline to match Jenkins
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
Labels: :Windows, ci, macOS, arm, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39612 [Docs][Elasticsearch] Specify metricsets list behaviour with xpack mode enabled
  metricbeat/docs/modules/elasticsearch.asciidoc
  metricbeat/module/elasticsearch/_meta/docs.asciidoc
Labels: Team:Monitoring

#39495 Manage Azure and Event Hub SDKs version with Dependabot
  .github/dependabot.yml
Labels: Team:obs-ds-hosted-services

#39646 github-actions: use GitHub secrets for the slack bot and the ephemeral GitHub token
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-golang.yml
  .github/workflows/notify-stalled-snapshots.yml
Labels: needs_team, backport-skip

#39496 [libbeat] Small cleanup of unused code in monitoring initialization
  libbeat/monitoring/report/report.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#39656 x-pack/filebeat/input/http_endpoint: fix request trace logging file names
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/http_endpoint/input.go
Labels: Filebeat, backport-skip, bugfix, Team:Security-Service Integrations

#39678 x-pack/filebeat/input/httpjson: skip flakey test on windows
  CHANGELOG-developer.next.asciidoc
  x-pack/filebeat/input/httpjson/metrics_test.go
Labels: Filebeat, flaky-test, bugfix, Team:Security-Service Integrations, backport-v8.14.0

#39672 Remove verbose debug logs from acker
  CHANGELOG-developer.next.asciidoc
  filebeat/beater/acker.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane, backport-v8.14.0

#39668 updatecli: use `GITHUB_ACTOR`
  .github/workflows/updatecli.d/bump-golang-7.17.yml
  .github/workflows/updatecli.d/bump-golang.yml
Labels: needs_team, backport-skip

#39663 Style fixes for Buildkite xpack/auditbeat pipeline
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
Labels: ci, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39642 Update xpack/libbeat pipeline to match Jenkins
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
Labels: ci, arm, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39693 Update main beats pipeline
  .buildkite/pipeline.yml
Labels: ci, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39620 let the system/process metricset monitor a single PID
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/module/system/process/config.go
  metricbeat/module/system/process/process.go
  metricbeat/module/system/process/process_test.go
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane

#39675 [CI] Metricbeat: set AWS region to terraform.tf
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  x-pack/metricbeat/module/aws/terraform.tf
Labels: enhancement, ci, aws, backport-v7.17.0, Team:Ingest-EngProd, backport-v8.14.0

#38767 Log raw events to a separate log file
  CHANGELOG.next.asciidoc
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  filebeat/tests/integration/event_log_file_test.go
  filebeat/tests/system/test_reload_inputs.py
  filebeat/tests/system/test_reload_modules.py
  heartbeat/heartbeat.reference.yml
  libbeat/_meta/config/logging.reference.yml.tmpl
  libbeat/cmd/instance/beat.go
  libbeat/docs/loggingconfig.asciidoc
  libbeat/outputs/elasticsearch/client.go
  libbeat/outputs/fileout/file.go
  libbeat/outputs/kafka/client.go
  libbeat/outputs/redis/client.go
  libbeat/processors/actions/append.go
  libbeat/processors/actions/copy_fields.go
  libbeat/processors/actions/decode_base64_field.go
  libbeat/processors/actions/decompress_gzip_field.go
  libbeat/processors/actions/rename.go
  libbeat/processors/actions/replace.go
  libbeat/processors/urldecode/urldecode.go
  libbeat/publisher/processing/processors.go
  libbeat/tests/integration/framework.go
  libbeat/tests/system/beat/beat.py
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/agentbeat/agentbeat.spec.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane

#39700 Skip Flaky test - packetbeat/route TestDefault
  packetbeat/route/route_test.go
Labels: flaky-test, Team:Security-Linux Platform, Team:Security-Windows Platform

#39694 Dockerfile: keep nghttp2 up to date.
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Elastic-Agent-Data-Plane, backport-v7.17.0, backport-v8.14.0

#39665 Enable macOS arm tests for x-pack/filebeat
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
Labels: ci, macOS, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39666 Updated xpack/filebeat to match 7.17
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
Labels: ci, Team:Ingest-EngProd

#39648 [aws/s3]: fix s3_input integration test
  .ci/jobs/docker-compose.yml
  x-pack/filebeat/input/awss3/input_integration_test.go
Labels: Team:obs-ds-hosted-services, Team:Automation, aws, Team:Elastic-Agent-Data-Plane

#39714 Revert "let the system/process metricset monitor a single PID (#39620)"
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/module/system/process/config.go
  metricbeat/module/system/process/process.go
  metricbeat/module/system/process/process_test.go
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane

#39691 Update x-pack/osquerybeat pipeline to match Jenkins
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
Labels: :Windows, ci, macOS, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39692 Update x-pack/osquerybeat to match steps from Jenkins 7.17 branch
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
Labels: :Windows, ci, macOS, Team:Ingest-EngProd

#39715 Update x-pack/packetbeat pipeline to match common styling
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
Labels: ci, Team:Ingest-EngProd

#39716 Update x-pack/packetbeat pipeline to match common styling
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
Labels: ci, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39674 (+Doc) FB "index" means ingesting target
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: enhancement, docs, Team:Docs, >enhancement

#39621 [Heartbeat] improve monitor state loader failure attempts
  CHANGELOG.next.asciidoc
  heartbeat/monitors/wrappers/monitorstate/tracker.go
Labels: bug, Team:obs-ds-hosted-services, backport-v8.14.0

#39586 Update elastic-agent-client and rename control proto package to cproto
  NOTICE.txt
  go.mod
  go.sum
  x-pack/elastic-agent/control.proto
  x-pack/elastic-agent/magefile.go
  x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go
  x-pack/elastic-agent/pkg/agent/control/client/client.go
  x-pack/elastic-agent/pkg/agent/control/cproto/control.pb.go
  x-pack/elastic-agent/pkg/agent/control/cproto/control_grpc.pb.go
  x-pack/elastic-agent/pkg/agent/control/server/server.go
  x-pack/elastic-agent/pkg/core/server/server.go
Labels: bug, backport, Team:Elastic-Agent-Control-Plane

#39664 Normalize AWS RDS CPU Utilization values before metadata API call
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/aws/cloudwatch/metadata/rds/rds.go
Labels: Team:Service-Integrations

#39727 Revert "Dockerfile: keep nghttp2 up to date. (#39694)"
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Elastic-Agent-Data-Plane

#39481 filebeat/module/apache: Rename the field `apache2.module.error` to `apache.module.error`
  CHANGELOG.next.asciidoc
  filebeat/module/apache/_meta/kibana/7/dashboard/Filebeat-Apache-Dashboard-ecs.json
  filebeat/module/apache/_meta/kibana/7/search/Apache-errors-log-ecs.json
Labels: needs_team

#39661 Migrate needed .ci/* scripts into .buildkite/* ( elastic#3353 )
  .buildkite/deploy/docker/docker-compose.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/setup_cloud_env.sh
  .buildkite/scripts/terraform-cleanup.sh
Labels: :Windows, ci, macOS, aws, backport-v7.17.0, backport-v8.13.0, Team:Ingest-EngProd, backport-v8.14.0

#39709 [8.14] Fix handling of custom Endpoint when using S3 + SQS
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/input_integration_test.go
  x-pack/filebeat/input/awss3/input_test.go
Labels: bug, aws, Team:Elastic-Agent-Data-Plane, Team:Cloud-Monitoring

#39704 Add changelog entries for elastic-agent-system-metrics updates
  CHANGELOG.next.asciidoc
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane

#39759 [auditbeat/fim/kprobes] Correct seccomp policy for arm64
  CHANGELOG.next.asciidoc
  auditbeat/module/file_integrity/kprobes/seccomp_linux_amd64.go
Labels: bug, needs_team, backport-v8.14.0

#39763 heartbeat - move seccomp customization to InitializeModule
  heartbeat/security/policy_linux_386.go
  heartbeat/security/policy_linux_amd64.go
  heartbeat/security/policy_linux_arm64.go
  heartbeat/security/seccomp.go
  heartbeat/security/security.go
Labels: Heartbeat, Team:obs-ds-hosted-services, backport-v8.14.0
