Repository elastic/beats, pull requests merged in 2024-12, with the labels that each got.

#41848 [FlakyTest] TestFileWatcher/does_not_emit_events_for_empty_files/emits_a_create_event_once_something_is_written_to_the_empty_file
  filebeat/input/filestream/fswatch_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41626 Support `location_label` config in GCP Metrics Metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/modules/gcp.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/gcp/_meta/config.yml
  x-pack/metricbeat/module/gcp/metrics/_meta/docs.asciidoc
  x-pack/metricbeat/module/gcp/metrics/metrics_requester.go
  x-pack/metricbeat/module/gcp/metrics/metrics_requester_test.go
  x-pack/metricbeat/module/gcp/metrics/metricset.go
  x-pack/metricbeat/modules.d/gcp.yml.disabled
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-8.x

#41816 move metricbeat command setup out of init
  metricbeat/cmd/root.go
  metricbeat/main.go
  metricbeat/main_test.go
  x-pack/agentbeat/main.go
  x-pack/libbeat/management/tests/mbtest/metricbeat_v2_test.go
  x-pack/libbeat/management/tests/mbtest/system/process_integration_test.go
  x-pack/metricbeat/cmd/root.go
  x-pack/metricbeat/main.go
  x-pack/metricbeat/main_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41825 metricbeat: suppress error when RAID metrics are enabled on non-RAID system
  metricbeat/module/system/raid/blockinfo/getdev.go
  metricbeat/module/system/raid/raid.go
  metricbeat/module/system/raid/raid_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17

#41335 x-pack/filebeat/input/cel: add evaluation state dump debugging feature
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/config.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-8.x

#41834 [filebeat][gcs] - Refactor & cleanup with updates to some default values and docs
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-gcs.asciidoc
  x-pack/filebeat/input/gcs/client.go
  x-pack/filebeat/input/gcs/config.go
  x-pack/filebeat/input/gcs/input.go
  x-pack/filebeat/input/gcs/input_stateless.go
  x-pack/filebeat/input/gcs/input_test.go
Labels: refactoring, Filebeat, cleanup, Team:Security-Service Integrations, backport-8.x, input:GCS

#41731 filestream: validate input id on startup
  CHANGELOG.next.asciidoc
  filebeat/beater/filebeat.go
  filebeat/input/filestream/config.go
  filebeat/input/filestream/config_test.go
  filebeat/tests/integration/filestream_test.go
Labels: breaking change, backport-skip, Team:Elastic-Agent-Data-Plane

#41864 Update CHANGELOG.asciidoc
  CHANGELOG.asciidoc
Labels: Team:Docs

#41822 [xpack][metricbeats][gcp] don't skip first value in histogram calculations
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/gcp/distribution.go
  x-pack/metricbeat/module/gcp/distribution_test.go
  x-pack/metricbeat/module/gcp/pubsub/_meta/data_topic.json
Labels: Team:obs-ds-hosted-services, Team:Obs-InfraObs, backport-8.x

#41857 Don't panic if libbeat processors are registered more than once
  CHANGELOG.next.asciidoc
  libbeat/processors/namespace.go
  libbeat/processors/namespace_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41863 helper/hasher general improvements
  CHANGELOG.next.asciidoc
  auditbeat/helper/hasher/hasher.go
Labels: enhancement, Team:Security-Linux Platform, backport-8.15, backport-8.x, backport-8.16, backport-8.17

#41869 [AWS] improve S3 input states copy by only storing filtered entries
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/input_benchmark_test.go
  x-pack/filebeat/input/awss3/s3_input.go
  x-pack/filebeat/input/awss3/s3_test.go
  x-pack/filebeat/input/awss3/states.go
  x-pack/filebeat/input/awss3/states_test.go
Labels: enhancement, Team:obs-ds-hosted-services, backport-8.x

#41862 [filebeat][gcs] - Added support for retry config
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-gcs.asciidoc
  x-pack/filebeat/input/gcs/config.go
  x-pack/filebeat/input/gcs/input.go
  x-pack/filebeat/input/gcs/input_stateless.go
  x-pack/filebeat/input/gcs/input_test.go
  x-pack/filebeat/input/gcs/mock/mock.go
  x-pack/filebeat/input/gcs/types.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-8.x, input:GCS

#41801 add metricbeat benchmark module
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/benchmark.asciidoc
  metricbeat/docs/modules/benchmark/info.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/benchmark/_meta/config.yml
  x-pack/metricbeat/module/benchmark/_meta/docs.asciidoc
  x-pack/metricbeat/module/benchmark/_meta/fields.yml
  x-pack/metricbeat/module/benchmark/doc.go
  x-pack/metricbeat/module/benchmark/fields.go
  x-pack/metricbeat/module/benchmark/info/_meta/data.json
  x-pack/metricbeat/module/benchmark/info/_meta/docs.asciidoc
  x-pack/metricbeat/module/benchmark/info/_meta/fields.yml
  x-pack/metricbeat/module/benchmark/info/config.go
  x-pack/metricbeat/module/benchmark/info/config_test.go
  x-pack/metricbeat/module/benchmark/info/info.go
  x-pack/metricbeat/module/benchmark/info/info_test.go
  x-pack/metricbeat/modules.d/benchmark.yml.disabled
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41882 Add known issues for Filebeat 8.14.0
  CHANGELOG.asciidoc
Labels: Team:Elastic-Agent-Data-Plane, forwardport-main

#41770 [winlogbeat] Make experimental api GA
  CHANGELOG.next.asciidoc
  winlogbeat/_meta/fields.common.yml
  winlogbeat/docs/fields.asciidoc
  winlogbeat/docs/winlogbeat-options.asciidoc
  winlogbeat/eventlog/wineventlog_raw.go
  winlogbeat/eventlog/wineventlog_test.go
  winlogbeat/include/fields.go
  winlogbeat/sys/wineventlog/testdata/raw.evtx
  winlogbeat/sys/wineventlog/testdata/raw.xml
  winlogbeat/sys/wineventlog/wineventlog_windows_test.go
Labels: enhancement, Winlogbeat, Team:Security-Windows Platform, backport-8.x

#41583 x-pack/filebeat/input/entityanalytics/provider/okta: Rate limiting fixes
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter_test.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go
Labels: bugfix, Team:Security-Service Integrations, backport-8.15, backport-8.x, backport-8.16

#41891 Invoke m.Run on TestMain and fix test flakiness
  filebeat/autodiscover/builder/hints/logs_test.go
  filebeat/input/filestream/input_integration_test.go
  filebeat/processor/add_kubernetes_metadata/matchers_test.go
  filebeat/tests/integration/translate_ldap_attribute_test.go
  metricbeat/autodiscover/appender/kubernetes/token/token_test.go
  metricbeat/autodiscover/builder/hints/metrics_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.15, backport-8.x, backport-8.16, backport-8.17

#41895 Fix log file rotation bug
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: bugfix, Team:Security-Linux Platform, backport-8.x

#41694 [aws] feat: aws-s3 input registry cleanup for untracked s3 objects
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/s3_input.go
  x-pack/filebeat/input/awss3/states.go
  x-pack/filebeat/input/awss3/states_test.go
Labels: enhancement, Team:obs-ds-hosted-services, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.16, backport-8.17

#41932 [azure-eventhub] Make the azure-eventhub input v1 tracer opt-in
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-azure-eventhub.asciidoc
  x-pack/filebeat/input/azureeventhub/tracer.go
Labels: enhancement, Team:obs-ds-hosted-services, input:azure-eventhub, backport-8.x, backport-8.16, backport-8.17

#41884 x-pack/filebeat/input/cel: add evaluation coverage collection support
  CHANGELOG-developer.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/config.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-8.x

#41920 x-pack/filebeat/input/httpjson: redact authorization headers in logging
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/request.go
Labels: enhancement, Filebeat, bugfix, Team:Security-Service Integrations, backport-8.x

#41794 Remove ManagerV2 unnecessary reload when apm tracing config is nil
  CHANGELOG.next.asciidoc
  x-pack/libbeat/management/managerV2.go
  x-pack/libbeat/management/managerV2_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.16, backport-8.17

#41918 Let network processor handle multiple IPs
  CHANGELOG.next.asciidoc
  libbeat/conditions/conditions_test.go
  libbeat/conditions/network.go
  libbeat/conditions/network_test.go
  libbeat/docs/processors-using.asciidoc
Labels: bugfix, Team:Security-Linux Platform, backport-8.x

#41939 Add unique per beat monitoring namespace
  filebeat/beater/filebeat.go
  heartbeat/monitors/mocks.go
  libbeat/beat/info.go
  libbeat/cmd/instance/beat.go
  x-pack/filebeat/input/benchmark/input.go
  x-pack/heartbeat/scenarios/framework/framework.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41911 otelconsumer: remove temporary handling of entity too large
  libbeat/outputs/otelconsumer/otelconsumer.go
  libbeat/outputs/otelconsumer/otelconsumer_test.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x

#41721 Add breaking change for Filebeat removed 'docker' input
  CHANGELOG.asciidoc
Labels: docs, Team:Docs, backport-8.x, backport-8.16, backport-8.17

#41940 Reassign components ownership from obs-cloud-monitoring to obs-ds-hosted-services
  .github/CODEOWNERS
Labels: Team:obs-ds-hosted-services, backport-8.x

#41934 [filebeat][streaming] - Added support for TLS & forward proxy configs for websockets
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-streaming.asciidoc
  x-pack/filebeat/input/streaming/config.go
  x-pack/filebeat/input/streaming/input_manager.go
  x-pack/filebeat/input/streaming/input_test.go
  x-pack/filebeat/input/streaming/testdata/certs/ca.crt
  x-pack/filebeat/input/streaming/testdata/certs/cert.pem
  x-pack/filebeat/input/streaming/testdata/certs/key.pem
  x-pack/filebeat/input/streaming/websocket.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, input:streaming, backport-8.x, backport-8.17

#41970 [filebeat][gcs] - Removed bucket_timeout config option and replaced bucket context with parent program context
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-gcs.asciidoc
  x-pack/filebeat/input/gcs/config.go
  x-pack/filebeat/input/gcs/input.go
  x-pack/filebeat/input/gcs/input_stateless.go
  x-pack/filebeat/input/gcs/input_test.go
  x-pack/filebeat/input/gcs/job.go
  x-pack/filebeat/input/gcs/types.go
Labels: docs, Filebeat, Team:Security-Service Integrations, backport-8.x, input:GCS, deprecation

#41597 Remove Eng Prod metricbeats tests ownership
  .github/CODEOWNERS
Labels: Team:Ingest-EngProd, backport-8.x, backport-8.16, backport-8.17

#41977 .../input/entityanalytics/provider/okta: Rate limiting fix, improvements
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/okta/conf.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter_test.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go
Labels: enhancement, bugfix, Team:Security-Service Integrations, backport-8.x

#41916 Remove Nassim from ironbank maintainers list
  dev-tools/packaging/templates/ironbank/auditbeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/filebeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/metricbeat/hardening_manifest.yaml
  dev-tools/packaging/templates/ironbank/packetbeat/hardening_manifest.yaml
Labels: Team:Elastic-Agent, backport-8.x

#42004 auditbeat: Split common tty definitions
  CHANGELOG.next.asciidoc
  auditbeat/helper/tty/tty.go
  x-pack/auditbeat/processors/sessionmd/processdb/db.go
  x-pack/auditbeat/processors/sessionmd/processdb/db_test.go
  x-pack/auditbeat/processors/sessionmd/processdb/entry_leader_test.go
  x-pack/auditbeat/processors/sessionmd/procfs/procfs.go
  x-pack/auditbeat/processors/sessionmd/provider/kerneltracingprovider/kerneltracingprovider_linux.go
  x-pack/auditbeat/processors/sessionmd/types/events.go
Labels: enhancement, Team:Security-Linux Platform, backport-8.x

#41858 Update CODEOWNERS according to k8s ownership transfer plan
  .github/CODEOWNERS
Labels: release-note:skip, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.16, backport-8.17

#41808 Correct the default filename of events-data
  auditbeat/auditbeat.reference.yml
  filebeat/filebeat.reference.yml
  heartbeat/heartbeat.reference.yml
  libbeat/_meta/config/logging.reference.yml.tmpl
  libbeat/docs/loggingconfig.asciidoc
  metricbeat/metricbeat.reference.yml
  packetbeat/packetbeat.reference.yml
  winlogbeat/winlogbeat.reference.yml
  x-pack/auditbeat/auditbeat.reference.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/functionbeat/functionbeat.reference.yml
  x-pack/heartbeat/heartbeat.reference.yml
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/osquerybeat/osquerybeat.reference.yml
  x-pack/packetbeat/packetbeat.reference.yml
  x-pack/winlogbeat/winlogbeat.reference.yml
Labels: Team:Elastic-Agent-Data-Plane

#41965 [system/cpu][system/core] - New config for using performance counters
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/docs/modules/system.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/system/_meta/config.reference.yml
  metricbeat/module/system/core/_meta/docs.asciidoc
  metricbeat/module/system/core/config.go
  metricbeat/module/system/core/core.go
  metricbeat/module/system/cpu/_meta/docs.asciidoc
  metricbeat/module/system/cpu/config.go
  metricbeat/module/system/cpu/cpu.go
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42012 [filebeat][streaming] - Added default values for websocket retries & put a cap on waitTime to be <= waitMax
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-streaming.asciidoc
  x-pack/filebeat/input/streaming/config.go
  x-pack/filebeat/input/streaming/websocket.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, input:streaming, backport-8.x, backport-8.16, backport-8.17

#41516 x-pack/metricbeat/module/openai: Add new module
  .github/CODEOWNERS
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/openai.asciidoc
  metricbeat/docs/modules/openai/usage.asciidoc
  metricbeat/docs/modules_list.asciidoc
  x-pack/agentbeat/agentbeat.spec.yml
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/openai/_meta/config.yml
  x-pack/metricbeat/module/openai/_meta/docs.asciidoc
  x-pack/metricbeat/module/openai/_meta/fields.yml
  x-pack/metricbeat/module/openai/doc.go
  x-pack/metricbeat/module/openai/fields.go
  x-pack/metricbeat/module/openai/usage/_meta/data.json
  x-pack/metricbeat/module/openai/usage/_meta/docs.asciidoc
  x-pack/metricbeat/module/openai/usage/_meta/fields.yml
  x-pack/metricbeat/module/openai/usage/client.go
  x-pack/metricbeat/module/openai/usage/config.go
  x-pack/metricbeat/module/openai/usage/errors.go
  x-pack/metricbeat/module/openai/usage/helper.go
  x-pack/metricbeat/module/openai/usage/persistcache.go
  x-pack/metricbeat/module/openai/usage/schema.go
  x-pack/metricbeat/module/openai/usage/usage.go
  x-pack/metricbeat/module/openai/usage/usage_integration_test.go
  x-pack/metricbeat/modules.d/openai.yml.disabled
Labels: Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, backport-8.x, Module: openai

#42041 [system/cpu,core] - Disable performance counter by default to unblock agent CI
  metricbeat/docs/modules/system.asciidoc
  metricbeat/metricbeat.reference.yml
  metricbeat/module/system/_meta/config.reference.yml
  metricbeat/module/system/core/_meta/docs.asciidoc
  metricbeat/module/system/core/config.go
  metricbeat/module/system/cpu/_meta/docs.asciidoc
  metricbeat/module/system/cpu/config.go
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42054 Beats standalone docker image will not start without -e option
  CHANGELOG.asciidoc
Labels: needs_team, forwardport-main, backport-8.x

#42053 Changed CreationDate to string to prevent scientific notation conversion
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/index/data.go
Labels: bug, Team:Monitoring, backport-8.x, backport-8.17

#42056 Bump golang.org/x/crypto to v0.31.0
  NOTICE.txt
  go.mod
  go.sum
Labels: dependency, Team:Elastic-Agent-Data-Plane, backport-7.17, backport-8.x, backport-8.16, backport-8.17

#41909 Include Npcap in Packetbeat when bundled with Agentbeat
  x-pack/agentbeat/magefile.go
  x-pack/packetbeat/magefile.go
  x-pack/packetbeat/scripts/mage/pcap.go
Labels: bug, Team:Elastic-Agent-Control-Plane, QA:Ready For Testing, backport-8.x, backport-8.16, backport-8.17

#41903 Add regex pattern matching to add_kubernetes_metadata processor
  CHANGELOG.next.asciidoc
  libbeat/processors/add_kubernetes_metadata/docs/indexers_and_matchers.asciidoc
  libbeat/processors/add_kubernetes_metadata/matchers.go
  libbeat/processors/add_kubernetes_metadata/matchers_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.16, backport-8.17

#42019 x-pack/filebeat/input/awss3: fix document ID construction when using csv decoder
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/decoding.go
  x-pack/filebeat/input/awss3/decoding_csv.go
  x-pack/filebeat/input/awss3/s3_objects.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-8.x, backport-8.16, backport-8.17

#41960 Add upstream deadlock warning to the logstash output
  libbeat/outputs/logstash/async.go
  libbeat/outputs/logstash/deadlock.go
  libbeat/outputs/logstash/deadlock_test.go
  libbeat/outputs/logstash/sync.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-7.17, backport-8.x, backport-8.16, backport-8.17

#42113 Update elastic-agent-libs to v0.17.5
  NOTICE.txt
  go.mod
  go.sum
Labels: technical debt, Team:Elastic-Agent-Control-Plane, backport-8.x

#41929 [x-pack][iis] capture extra .NET CLR metrics
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  x-pack/metricbeat/module/iis/application_pool/_meta/data.json
  x-pack/metricbeat/module/iis/application_pool/_meta/fields.yml
  x-pack/metricbeat/module/iis/application_pool/reader.go
  x-pack/metricbeat/module/iis/fields.go
Labels: enhancement, Team:Obs-InfraObs, backport-8.x

#42103 [7.17] Use MongoDB 5.0 in metricbeat integration tests
  metricbeat/docs/modules/mongodb.asciidoc
  metricbeat/module/mongodb/_meta/docs.asciidoc
  metricbeat/module/mongodb/dbstats/dbstats_integration_test.go
  metricbeat/module/mongodb/docker-compose.yml
Labels: cleanup, backport-skip, Team:Elastic-Agent-Data-Plane

#42120 Skip flaky test TestRateLimiter
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter_test.go
Labels: needs_team, backport-8.x

#42094 .../input/entityanalytics/provider/okta: Handle 429s, concurrent limits
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/okta_test.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter.go
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter_test.go
Labels: enhancement, backport-skip, Team:Security-Service Integrations

#42114 [Filebeat] minor cleanup to aws-s3 input docs
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
Labels: docs, Filebeat, needs_team, backport-8.x

#41762 Use `fingerprint` file identity by default and migrate file state from `native` or `path`
  CHANGELOG.next.asciidoc
  filebeat/_meta/config/filebeat.global.reference.yml.tmpl
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/docs/faq.asciidoc
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/docs/inputs/input-filestream.asciidoc
  filebeat/filebeat.reference.yml
  filebeat/include/list.go
  filebeat/input/filestream/environment_test.go
  filebeat/input/filestream/fswatch.go
  filebeat/input/filestream/fswatch_test.go
  filebeat/input/filestream/identifier.go
  filebeat/input/filestream/identifier_test.go
  filebeat/input/filestream/input_integration_test.go
  filebeat/input/filestream/input_test.go
  filebeat/input/filestream/internal/input-logfile/prospector.go
  filebeat/input/filestream/internal/input-logfile/store.go
  filebeat/input/filestream/internal/input-logfile/store_test.go
  filebeat/input/filestream/legacy_metrics_integration_test.go
  filebeat/input/filestream/metrics_integration_test.go
  filebeat/input/filestream/parsers_integration_test.go
  filebeat/input/filestream/prospector.go
  filebeat/input/filestream/prospector_creator.go
  filebeat/input/filestream/prospector_test.go
  filebeat/input/filestream/testdata/log.log
  filebeat/tests/integration/event_log_file_test.go
  filebeat/tests/integration/filestream_test.go
  filebeat/tests/integration/filestream_truncation_test.go
  filebeat/tests/integration/store_test.go
  filebeat/tests/integration/translate_ldap_attribute_test.go
  filebeat/tests/system/config/filestream-fixup-id.yml.j2
  filebeat/tests/system/test_reload_inputs.py
  libbeat/tests/integration/framework.go
  x-pack/filebeat/filebeat.reference.yml
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-8.x

#42127 [Filebeat] aws-s3 - Document _id generation behavior
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
Labels: enhancement, docs, Filebeat, needs_team, backport-8.x

#42078 [x-pack][filebeat] incorporate LastModified into s3 event _id generation
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/s3_input.go
  x-pack/filebeat/input/awss3/s3_objects.go
  x-pack/filebeat/input/awss3/s3_objects_test.go
  x-pack/filebeat/input/awss3/sqs_s3_event.go
  x-pack/filebeat/input/azureblobstorage/input_test.go
  x-pack/filebeat/input/gcs/input_test.go
Labels: enhancement, Team:Obs-InfraObs, backport-8.x

#42119 [filebeat] Add unifiedlogs input to agent
  x-pack/agentbeat/agentbeat.spec.yml
  x-pack/filebeat/input/unifiedlogs/config.go
  x-pack/filebeat/input/unifiedlogs/config_test.go
  x-pack/filebeat/input/unifiedlogs/input.go
  x-pack/filebeat/input/unifiedlogs/input_test.go
Labels: release-note:skip, Team:Security-Windows Platform, backport-8.x

#42123 .../input/entityanalytics/provider/okta: Fix flaky tests
  CHANGELOG-developer.next.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/okta/internal/okta/ratelimiter_test.go
Labels: flaky-test, cleanup, Team:Security-Service Integrations, backport-8.x

#42151 [chore] update go.mod
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.16, backport-8.17

#42152 security: bump golang.org/x/net to v0.33.0
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent, backport-8.x, backport-8.16, backport-8.17

#42144 Revert the Ubuntu version update
  CHANGELOG.next.asciidoc
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Elastic-Agent-Data-Plane, backport-8.16

#42125 Add configuration example and improve reference
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/_meta/config/filebeat.inputs.yml.tmpl
  filebeat/filebeat.reference.yml
  filebeat/filebeat.yml
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/filebeat.yml
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42177 [go.mod] update elastic-agent-system-metrics
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42128 Call tlscommon.SetInsecureDefaults
  libbeat/cmd/instance/beat_test.go
  libbeat/cmd/instance/testdata/tls.yml
  libbeat/cmd/instance/testdata/tls10.yml
  libbeat/cmd/root.go
Labels: backport, release-note:skip, Team:Elastic-Agent-Control-Plane

#41667 filebeat/inputs/filestream: add metric for messages truncated
  filebeat/docs/inputs/input-filestream.asciidoc
  filebeat/input/filestream/environment_test.go
  filebeat/input/filestream/input.go
  filebeat/input/filestream/internal/input-logfile/metrics.go
  filebeat/input/filestream/metrics_integration_test.go
  libbeat/reader/multiline/message_buffer.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x
