Repository elastic/beats, pull requests merged in 2025-02, with the labels that each got.

#42567 .../input/entityanalytics/provider/okta: Publish events progressively
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta_test.go
Labels: enhancement, Team:Security-Service Integrations

#42569 metricbeat: Update beat module with apm-server tail sampling monitoring metrics fields
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/beat/_meta/fields.yml
  metricbeat/module/beat/fields.go
  metricbeat/module/beat/stats/_meta/fields.yml
  metricbeat/module/beat/stats/_meta/test/apm-server.stats.712.json
Labels: bug, needs_team, backport-8.x, backport-8.16, backport-8.17, backport-8.18, backport-9.0

#42107 Remove experimental warning from journald input.
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-journald.asciidoc
  filebeat/input/journald/input.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.18

#42565 Add latency metrics for logstash async output
  libbeat/outputs/logstash/async.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#42442 x-pack/filebeat/input/httpjson: add metrics for number of events and pages published
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/metrics.go
  x-pack/filebeat/input/httpjson/request.go
  x-pack/filebeat/input/httpjson/request_test.go
Labels: enhancement, Filebeat, backport-7.17, Team:Security-Service Integrations, backport-8.x, backport-8.16

#42513 chore: add linter that catches math/rand imports
  .golangci.yml
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x

#42594 mergify: support backport-active-8, backport-active-9 and backport-active-all
  .mergify.yml
Labels: backport-skip, Team:Elastic-Agent-Data-Plane, Team:Ingest-EngProd

#42550 [DOCS] [7.7] Removes link to master
  docs/devguide/create-module.asciidoc
Labels: docs, v7.7.0, Team:Docs

#42551 [DOCS] [7.6] Removes link to master
  docs/devguide/create-module.asciidoc
Labels: docs, v7.6.0, Team:Docs

#42552 [DOCS] [7.5] Removes link to master
  docs/devguide/create-module.asciidoc
Labels: docs, v7.5.0, Team:Docs

#42553 [DOCS] [7.4] Removes link to master
  docs/devguide/create-module.asciidoc
Labels: docs, v7.4.0, Team:Docs

#42554 [DOCS] [7.3] Removes link to master
  docs/devguide/create-module.asciidoc
Labels: docs, v7.3.0, Team:Docs

#42614 mergify: support 8.x for the backport-active-8
  .mergify.yml
Labels: needs_team, backport-skip

#42591 [Metricbeat][Azure]Check for metrics dimensions before matching two metrics together
  x-pack/metricbeat/module/azure/client_utils.go
  x-pack/metricbeat/module/azure/client_utils_test.go
Labels: Team:obs-ds-hosted-services, bugfix, backport-8.x, backport-8.18, backport-active-9

#42627 [winlogbeat] add check for possible null metadata
  winlogbeat/sys/wineventlog/metadata_store.go
Labels: Winlogbeat, bugfix, Team:Security-Windows Platform, backport-8.x, windows, backport-8.18, backport-active-9

#42596 [Journald] Add tests to ensure no data duplication on restart
  filebeat/tests/integration/journald_test.go
  filebeat/tests/integration/testdata/filebeat_journald.yml
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#41919 Run auditbeat integration tests on non-PR builds
  .buildkite/auditbeat/auditbeat-pipeline.yml
Labels: Auditbeat, :integrations, release-note:skip, Team:Security-Deployment and Devices, backport-8.x

#42649 [otelconsumer]: Add fields on logrecord attributes to support dynamic indexing
  libbeat/outputs/otelconsumer/otelconsumer.go
  libbeat/outputs/otelconsumer/otelconsumer_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#42652 Wait for the beat to exit during shutdown of beats receivers
  x-pack/filebeat/fbreceiver/receiver.go
  x-pack/metricbeat/mbreceiver/receiver.go
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#42648 filebeat/beater: improve StateStore godoc
  filebeat/beater/filebeat.go
Labels: enhancement, docs, Team:Elastic-Agent, Team:Security-Service Integrations, backport-8.x

#42450 Add simplified integration framework
  filebeat/testing/integration/integration.go
  filebeat/testing/integration/log_generator.go
  filebeat/testing/integration/sample_test.go
  libbeat/testing/integration/README.md
  libbeat/testing/integration/integration.go
  libbeat/testing/integration/output_watcher.go
  libbeat/testing/integration/output_watcher_test.go
  libbeat/testing/integration/run_beat.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#42286 update kafka version used in testing to 3.6.0
  libbeat/docker-compose.yml
  metricbeat/docker-compose.yml
  metricbeat/docs/modules/kafka.asciidoc
  metricbeat/module/kafka/README.md
  metricbeat/module/kafka/_meta/Dockerfile
  metricbeat/module/kafka/_meta/adminclient.properties
  metricbeat/module/kafka/_meta/docs.asciidoc
  metricbeat/module/kafka/_meta/healthcheck.sh
  metricbeat/module/kafka/_meta/run.sh
  metricbeat/module/kafka/_meta/supported-versions.yml
  metricbeat/module/kafka/broker/_meta/docs.asciidoc
  metricbeat/module/kafka/consumer/_meta/docs.asciidoc
  metricbeat/module/kafka/consumergroup/consumergroup.go
  metricbeat/module/kafka/consumergroup/consumergroup_integration_test.go
  metricbeat/module/kafka/docker-compose.yml
  metricbeat/module/kafka/partition/partition.go
  metricbeat/module/kafka/producer/_meta/docs.asciidoc
  testing/environments/docker/kafka/Dockerfile
  testing/environments/docker/kafka/healthcheck.sh
  testing/environments/docker/kafka/run.sh
Labels: needs_team, backport-8.x

#42559 Preserve original meta fields during early encoding of events
  CHANGELOG.next.asciidoc
  libbeat/outputs/elasticsearch/event_encoder.go
  libbeat/outputs/elasticsearch/event_encoder_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#42682 x-pack/filebeat/input/entityanalytics/provider/activedirectory: fix use before init bug
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/activedirectory/activedirectory.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-active-8, backport-active-9

#42694 otel: add otelmap package for conversions between map types
  libbeat/otelbeat/otelmap/otelmap.go
  libbeat/otelbeat/otelmap/otelmap_test.go
  libbeat/outputs/otelconsumer/otelconsumer.go
  libbeat/outputs/otelconsumer/otelconsumer_test.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#42658 fix(otel): ensure default processors are applied in fbreceiver
  libbeat/beat/info.go
  libbeat/cmd/instance/beat.go
  libbeat/publisher/processing/default.go
  x-pack/filebeat/fbreceiver/factory.go
  x-pack/filebeat/fbreceiver/receiver_test.go
  x-pack/metricbeat/mbreceiver/factory.go
Labels: Team:Elastic-Agent-Data-Plane, bugfix, backport-8.x, backport-9.0

#42718 Revert "ci: remove win 2019 and win 2016 pipelines"
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: needs_team

#42707 [otelconsumer] Add log record attributes as flattened keys
  libbeat/outputs/otelconsumer/otelconsumer.go
  libbeat/outputs/otelconsumer/otelconsumer_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#42709 docs: fix table formatting in Filebeat metrics descriptions
  libbeat/docs/metrics-in-logs.asciidoc
Labels: docs, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#42626 Fixing NPCAP install with agentbeat
  .buildkite/x-pack/pipeline.xpack.agentbeat.yml
  x-pack/agentbeat/magefile.go
  x-pack/packetbeat/magefile.go
  x-pack/packetbeat/scripts/mage/pcap.go
  x-pack/packetbeat/tests/system/app_run_agentbeat_test.go
Labels: :Windows, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-active-8, backport-active-9

#42725 [otelconsumer] Fix timestamp discrepancy for documents ingested in otel mode
  libbeat/otelbeat/otelmap/otelmap.go
  libbeat/otelbeat/otelmap/otelmap_test.go
  libbeat/outputs/otelconsumer/otelconsumer_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#41508 [Heartbeat] Adds maintenance windows !!
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  heartbeat/docs/monitors/monitor-common-options.asciidoc
  heartbeat/monitors/maintwin/maintwin.go
  heartbeat/monitors/maintwin/maintwin_test.go
  heartbeat/monitors/stdfields/stdfields.go
  heartbeat/monitors/task.go
  heartbeat/scheduler/scheduler.go
  heartbeat/scheduler/scheduler_test.go
Labels: enhancement, Team:obs-ds-hosted-services, backport-8.x

#42756 fix(x-pack/filebeat/input/http_endpoint): hmac header validation
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/http_endpoint/handler_test.go
  x-pack/filebeat/input/http_endpoint/validate.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-8.x, backport-8.17, backport-8.18

#42619 [x-pack/winlogbeat] Port pipeline changes from integrations
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/powershell/ingest/powershell.yml
  x-pack/winlogbeat/module/powershell/ingest/powershell_operational.yml
  x-pack/winlogbeat/module/security/ingest/security.yml
  x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml
Labels: Winlogbeat, Team:Security-Windows Platform, backport-active-8, backport-active-9

#42764 Update the ownership to comply with the current O11y org
  .github/CODEOWNERS
Labels: Team:obs-ds-hosted-services, backport-active-all

#42776 [meraki] add `CODEOWNERS` entry
  .github/CODEOWNERS
Labels: Team:Obs-InfraObs

#42714 [metricbeat] Refactor kubernetes bearer token authentication
  CHANGELOG.next.asciidoc
  metricbeat/helper/http.go
  metricbeat/helper/http_test.go
  metricbeat/module/kubernetes/apiserver/metricset.go
  metricbeat/module/kubernetes/controllermanager/controllermanager.go
  metricbeat/module/kubernetes/kubernetes.go
  metricbeat/module/kubernetes/scheduler/scheduler.go
Labels: enhancement, cleanup, Team:Cloudnative-Monitoring, bugfix, backport-active-8, backport-active-9

#42780 Skip flaky test TestFilebeat/Filebeat_crashes_due_to_incorrect_config
  filebeat/testing/integration/sample_test.go
Labels: flaky-test, Team:Elastic-Agent-Data-Plane

#42398 Handle leak of process info in `hostfs` provider for `add_session_metadata`
  x-pack/auditbeat/processors/sessionmd/add_session_metadata.go
  x-pack/auditbeat/processors/sessionmd/add_session_metadata_test.go
  x-pack/auditbeat/processors/sessionmd/config.go
  x-pack/auditbeat/processors/sessionmd/docs/add_session_metadata.asciidoc
  x-pack/auditbeat/processors/sessionmd/processdb/db.go
  x-pack/auditbeat/processors/sessionmd/processdb/db_test.go
  x-pack/auditbeat/processors/sessionmd/processdb/entry_leader_test.go
  x-pack/auditbeat/processors/sessionmd/processdb/metrics.go
  x-pack/auditbeat/processors/sessionmd/processdb/reaper.go
  x-pack/auditbeat/processors/sessionmd/procfs/mock.go
  x-pack/auditbeat/processors/sessionmd/procfs/procfs.go
  x-pack/auditbeat/processors/sessionmd/provider/procfsprovider/procfsprovider.go
  x-pack/auditbeat/processors/sessionmd/provider/procfsprovider/procfsprovider_test.go
  x-pack/auditbeat/processors/sessionmd/types/events.go
Labels: bug, Auditbeat, Team:Security-Linux Platform, backport-8.x

#42747 Update testify and fix filebeat tests
  NOTICE.txt
  filebeat/channel/runner_mock_test.go
  go.mod
  go.sum
Labels: bug, Team:Elastic-Agent-Data-Plane

#42799 Remove filebeat/filebeat_windows_amd64.syso added by mistake
  filebeat/filebeat_windows_amd64.syso
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#42746 [meraki] fix panic due to uninitialized device wifi structs
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  x-pack/metricbeat/module/meraki/device_health/device_health.go
  x-pack/metricbeat/module/meraki/device_health/device_health_test.go
  x-pack/metricbeat/module/meraki/device_health/devices.go
  x-pack/metricbeat/module/meraki/device_health/switchports.go
  x-pack/metricbeat/module/meraki/device_health/uplinks.go
Labels: Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#42777 [filebeat] Compare documents ingested by fb in normal vs otel mode
  libbeat/otelbeat/beatconverter/beatconverter_test.go
  libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel.go
  libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel_test.go
  x-pack/filebeat/tests/integration/otel_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#42797 [fbreceiver] - Fix batcher's configuration
  libbeat/otelbeat/beatconverter/beatconverter_test.go
  libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel.go
  libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-active-all

#42847 [filebeat] Add fallback to attach if session exists
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/etw/input.go
Labels: enhancement, Input:etw, Team:Security-Windows Platform, backport-8.x, backport-8.18, backport-active-9

#42825 Added binfmt to beats packaging step
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/scripts/packaging/packaging.sh
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.agentbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: ci, Team:Ingest-EngProd, backport-active-all

#42826 {filebeat,winlogbeat} Improve error handling when opening and reading event logs
  CHANGELOG.next.asciidoc
  winlogbeat/eventlog/errors_unix.go
  winlogbeat/eventlog/errors_windows.go
  winlogbeat/eventlog/runner.go
Labels: enhancement, Filebeat, Winlogbeat, Team:Security-Windows Platform, backport-8.x, backport-8.18, backport-active-9

#42851 mod: update elastic/mito to version v1.17.0
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/input/cel/input_test.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-8.x, backport-8.18, backport-9.0

#42848 enhancement(4534): removed encryption and encrytion related logic from segments
  CHANGELOG.next.asciidoc
  libbeat/publisher/queue/diskqueue/benchmark_test.go
  libbeat/publisher/queue/diskqueue/compression_test.go
  libbeat/publisher/queue/diskqueue/config.go
  libbeat/publisher/queue/diskqueue/docs/on-disk-structures.md
  libbeat/publisher/queue/diskqueue/docs/schemaV2.pic
  libbeat/publisher/queue/diskqueue/docs/schemaV2.svg
  libbeat/publisher/queue/diskqueue/enc_compress_test.go
  libbeat/publisher/queue/diskqueue/encryption.go
  libbeat/publisher/queue/diskqueue/encryption_test.go
  libbeat/publisher/queue/diskqueue/segments.go
  libbeat/publisher/queue/diskqueue/segments_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.18, backport-active-9

#42795 Add metrics for kernel_tracing provider, fix mutex issue
  CHANGELOG.next.asciidoc
  x-pack/auditbeat/processors/sessionmd/add_session_metadata.go
  x-pack/auditbeat/processors/sessionmd/add_session_metadata_test.go
  x-pack/auditbeat/processors/sessionmd/provider/kerneltracingprovider/kerneltracingprovider_linux.go
  x-pack/auditbeat/processors/sessionmd/provider/kerneltracingprovider/metrics.go
Labels: bug, Team:Security-Linux Platform, backport-8.x

#42895 fix(tests): ensure TestFilebeatOTelE2E does not fail if timestamps are equal
  x-pack/filebeat/tests/integration/otel_test.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#42862 fix(tests): relax TestGroup_Go timeouts
  filebeat/input/filestream/internal/task/group_test.go
Labels: flaky-test, Team:Elastic-Agent-Data-Plane, backport-active-all

#42823 Update Stack Monitoring data stream to 9
  metricbeat/helper/elastic/elastic.go
  metricbeat/helper/elastic/elastic_test.go
Labels: bug, Metricbeat, monitoring, Team:Elastic-Agent-Data-Plane, Team:Monitoring, backport-9.0

#42901 [Stack Monitoring] Only fetch cluster-level index stats summary
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/_meta/README.md
  metricbeat/module/elasticsearch/index_summary/index_summary.go
Labels: enhancement, Feature:Stack Monitoring, Module:elasticsearch, Team:Monitoring, backport-8.x, backport-8.17, backport-8.18

#42896 [docs] Add the new docs CI checks
  .github/workflows/docs-build.yml
  .github/workflows/docs-cleanup.yml
Labels: Team:Docs, backport-skip

#42936 Disable interpolation for monorepo plugin
  .buildkite/pipeline.yml
Labels: needs_team, backport-active-8, backport-active-9

#42617 Skip Flaky test TestTranslateGUIDWithLDAP
  filebeat/tests/integration/translate_ldap_attribute_test.go
Labels: flaky-test, Team:Security-Windows Platform

#42803 fix: don't fail merticbeat/windows/perfmon when no data is available
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/perfmon/reader.go
  metricbeat/module/windows/perfmon/reader_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, backport-active-all

#42937 [Stack Monitoring] Remove `kibana.settings` metricset
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/kibana.asciidoc
  metricbeat/docs/modules/kibana/settings.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/module/kibana/_meta/README.md
  metricbeat/module/kibana/fields.go
  metricbeat/module/kibana/kibana.go
  metricbeat/module/kibana/settings/_meta/data.json
  metricbeat/module/kibana/settings/_meta/docs.asciidoc
  metricbeat/module/kibana/settings/_meta/fields.yml
  metricbeat/module/kibana/settings/_meta/test/settings.700.json
  metricbeat/module/kibana/settings/_meta/test/stats-legacy.700.json
  metricbeat/module/kibana/settings/_meta/test/stats.700.json
  metricbeat/module/kibana/settings/data.go
  metricbeat/module/kibana/settings/settings.go
  metricbeat/module/kibana/settings/settings_test.go
Labels: Feature:Stack Monitoring, Module:kibana, Team:Monitoring, backport-9.0

#42605 github-actions: enable 9 branches for the pre-commit
  .github/workflows/pre-commit.yml
Labels: Team:Automation, backport-skip

#42915 [9.x] Fully remove Enterprise Search from Metricbeat
  CHANGELOG.next.asciidoc
  dev-tools/mage/module_changeset.go
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/enterprisesearch.asciidoc
  metricbeat/docs/modules/enterprisesearch/health.asciidoc
  metricbeat/docs/modules/enterprisesearch/stats.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/helper/elastic/elastic.go
  x-pack/agentbeat/agentbeat.spec.yml
  x-pack/metricbeat/include/list.go
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/enterprisesearch/_meta/Dockerfile
  x-pack/metricbeat/module/enterprisesearch/_meta/config-xpack.yml
  x-pack/metricbeat/module/enterprisesearch/_meta/config.yml
  x-pack/metricbeat/module/enterprisesearch/_meta/docker-entrypoint-dependencies.sh
  x-pack/metricbeat/module/enterprisesearch/_meta/docs.asciidoc
  x-pack/metricbeat/module/enterprisesearch/_meta/fields.yml
  x-pack/metricbeat/module/enterprisesearch/_meta/kibana/7/dashboard/Metricbeat-enterprise-search-overview.json
  x-pack/metricbeat/module/enterprisesearch/doc.go
  x-pack/metricbeat/module/enterprisesearch/docker-compose.yml
  x-pack/metricbeat/module/enterprisesearch/fields.go
  x-pack/metricbeat/module/enterprisesearch/health/_meta/docs.asciidoc
  x-pack/metricbeat/module/enterprisesearch/health/_meta/fields.yml
  x-pack/metricbeat/module/enterprisesearch/health/_meta/testdata/config.yml
  x-pack/metricbeat/module/enterprisesearch/health/_meta/testdata/health.json
  x-pack/metricbeat/module/enterprisesearch/health/_meta/testdata/health.json-expected.json
  x-pack/metricbeat/module/enterprisesearch/health/data.go
  x-pack/metricbeat/module/enterprisesearch/health/data_test.go
  x-pack/metricbeat/module/enterprisesearch/health/health.go
  x-pack/metricbeat/module/enterprisesearch/health/health_integration_test.go
  x-pack/metricbeat/module/enterprisesearch/module.yml
  x-pack/metricbeat/module/enterprisesearch/stats/_meta/docs.asciidoc
  x-pack/metricbeat/module/enterprisesearch/stats/_meta/fields.yml
  x-pack/metricbeat/module/enterprisesearch/stats/_meta/testdata/config.yml
  x-pack/metricbeat/module/enterprisesearch/stats/_meta/testdata/stats.json
  x-pack/metricbeat/module/enterprisesearch/stats/_meta/testdata/stats.json-expected.json
  x-pack/metricbeat/module/enterprisesearch/stats/data.go
  x-pack/metricbeat/module/enterprisesearch/stats/data_test.go
  x-pack/metricbeat/module/enterprisesearch/stats/stats.go
  x-pack/metricbeat/module/enterprisesearch/stats/stats_integration_test.go
  x-pack/metricbeat/module/enterprisesearch/test_enterprisesearch.py
  x-pack/metricbeat/modules.d/enterprisesearch-xpack.yml.disabled
  x-pack/metricbeat/modules.d/enterprisesearch.yml.disabled
Labels: Team:Elastic-Agent-Data-Plane, deprecation, backport-9.0, backport-active-9, Team:Search
