Repository elastic/beats, pull requests merged in 2025-01, with the labels that each got.

#41849 [filebeat] Introduce otel mode
  NOTICE.txt
  go.mod
  go.sum
  libbeat/cmd/instance/beat.go
  libbeat/otelbeat/beatconverter/beatconverter.go
  libbeat/otelbeat/beatconverter/beatconverter_test.go
  libbeat/otelbeat/oteltranslate/testdata/certs/client.crt
  libbeat/otelbeat/oteltranslate/testdata/certs/client.key
  libbeat/otelbeat/oteltranslate/testdata/certs/rootCA.crt
  libbeat/otelbeat/oteltranslate/tls_otel.go
  libbeat/otelbeat/oteltranslate/tls_otel_test.go
  libbeat/otelbeat/providers/fbprovider/fbprovider.go
  libbeat/otelbeat/providers/fbprovider/fbprovider_test.go
  libbeat/outputs/elasticsearch/config.go
  libbeat/outputs/elasticsearch/config_otel.go
  libbeat/outputs/elasticsearch/config_otel_test.go
  libbeat/outputs/elasticsearch/config_presets_test.go
  libbeat/outputs/elasticsearch/config_test.go
  libbeat/outputs/elasticsearch/testdata/basic-op.yml
  libbeat/outputs/elasticsearch/testdata/basic.yml
  libbeat/outputs/hosts.go
  libbeat/outputs/hosts_test.go
  x-pack/filebeat/cmd/otel_test.go
  x-pack/filebeat/cmd/root.go
  x-pack/filebeat/filebeat-otel.yml
  x-pack/libbeat/common/otelbeat/otel.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42180 libbeat: optimize asset data decoding
  libbeat/asset/registry.go
  x-pack/filebeat/fbreceiver/receiver_test.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x

#42191 [chore] update notice
  NOTICE.txt
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17

#42199 Fix Otel API change and update system test golden files to 2025
  x-pack/filebeat/fbreceiver/receiver_test.go
  x-pack/filebeat/module/cisco/asa/test/additional_messages.log-expected.json
  x-pack/filebeat/module/cisco/asa/test/non-canonical.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/288_auto_clear_users_history_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/289_auto_clear_users_history_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/310_monitor_dr_replication_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/311_monitor_dr_replication_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/357_monitor_fw_rules_start.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/358_monitor_fw_rules_end.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/479_security_warning_the_signature_hash_algorithm_of_the_vault_certificate_is_sha1.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/59_clear_safe_history.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/88_set_password.log-expected.json
  x-pack/filebeat/module/cyberarkpas/audit/test/legacysyslog.log-expected.json
  x-pack/filebeat/module/microsoft/m365_defender/test/m365_defender-test.ndjson.log-expected.json
  x-pack/filebeat/module/mysqlenterprise/audit/test/mysql_audit_test.log-expected.json
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42060 fix templates and docs to use correct `--` command line args
  CHANGELOG.next.asciidoc
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-daemonset.yaml
  dev-tools/kubernetes/metricbeat/manifest.debug.multi.yaml
  dev-tools/kubernetes/metricbeat/manifest.debug.yaml
  dev-tools/kubernetes/metricbeat/manifest.run.yaml
  dev-tools/mage/pkg.go
  dev-tools/packaging/package_test.go
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
  dev-tools/packaging/templates/ironbank/auditbeat/Dockerfile
  dev-tools/packaging/templates/ironbank/filebeat/Dockerfile
  dev-tools/packaging/templates/ironbank/heartbeat/Dockerfile
  dev-tools/packaging/templates/ironbank/metricbeat/Dockerfile
  dev-tools/packaging/templates/ironbank/packetbeat/Dockerfile
  filebeat/tests/open-file-handlers/run.sh
  libbeat/docs/command-reference.asciidoc
  metricbeat/docs/running-on-docker.asciidoc
  metricbeat/module/kubernetes/_meta/remote-debugger/README.md
Labels: Team:Elastic-Agent-Data-Plane, bugfix, backport-8.x, backport-8.17

#42187 [Winlogbeat] Improve query building and error recovery
  CHANGELOG.next.asciidoc
  winlogbeat/docs/winlogbeat-options.asciidoc
  winlogbeat/eventlog/errors_windows.go
  winlogbeat/sys/wineventlog/query.go
  winlogbeat/sys/wineventlog/query_test.go
  winlogbeat/sys/wineventlog/syscall_windows.go
Labels: enhancement, Winlogbeat, Team:Security-Windows Platform, backport-8.x

#42202 Update elastic-agent-libs to v0.18.0
  NOTICE.txt
  go.mod
  go.sum
Labels: needs_team, release-note:skip, dependency, backport-8.x

#41954 Filestream returns error when an input with duplicated ID is created
  CHANGELOG.next.asciidoc
  filebeat/beater/crawler.go
  filebeat/beater/filebeat.go
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/input/filestream/config.go
  filebeat/input/filestream/input_integration_test.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/filestream/internal/input-logfile/manager_test.go
  filebeat/tests/integration/filestream_test.go
  heartbeat/beater/heartbeat.go
  libbeat/autodiscover/autodiscover.go
  libbeat/autodiscover/autodiscover_test.go
  libbeat/cfgfile/list.go
  libbeat/cfgfile/reload.go
  libbeat/cfgfile/reload_integration_test.go
  libbeat/common/errors.go
  libbeat/common/errors_test.go
  metricbeat/beater/metricbeat.go
  x-pack/libbeat/management/managerV2.go
  x-pack/libbeat/management/managerV2_test.go
Labels: breaking change, backport-skip, Team:Elastic-Agent-Data-Plane

#42218 [filebeat][streaming] - Added more retry codes to websocket retry logic
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/streaming/websocket.go
Labels: bugfix, Team:Security-Service Integrations, input:streaming, backport-8.x, backport-8.16, backport-8.17

#42016 [Kubernetes Integration] Fix for apiserver token expiration
  CHANGELOG.next.asciidoc
  metricbeat/helper/prometheus/prometheus.go
  metricbeat/module/kubernetes/apiserver/metricset.go
  metricbeat/module/kubernetes/controllermanager/controllermanager.go
  metricbeat/module/kubernetes/scheduler/scheduler.go
Labels: Team:obs-ds-hosted-services, backport-8.x, backport-8.16, backport-8.17

#42225 [filebeat][websocket] - Added infinite & blanket retry options to websockets and improved logging and retry logic
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-streaming.asciidoc
  x-pack/filebeat/input/streaming/config.go
  x-pack/filebeat/input/streaming/config_test.go
  x-pack/filebeat/input/streaming/input_test.go
  x-pack/filebeat/input/streaming/websocket.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, input:streaming, backport-8.x, backport-8.16, backport-8.17

#42233 github-actions: python 3.12 is the default when using ubuntu-latest
  .github/workflows/check-default.yml
  .github/workflows/check-docs.yml
Labels: needs_team, backport-7.17, backport-8.x, backport-8.16, backport-8.17

#42212 [filebeat][streaming] - Added OAuth2 support with auto token refresh for websockets
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-streaming.asciidoc
  x-pack/filebeat/input/streaming/config.go
  x-pack/filebeat/input/streaming/config_test.go
  x-pack/filebeat/input/streaming/input.go
  x-pack/filebeat/input/streaming/input_manager.go
  x-pack/filebeat/input/streaming/input_test.go
  x-pack/filebeat/input/streaming/websocket.go
Labels: enhancement, docs, Filebeat, Team:Security-Service Integrations, input:streaming, backport-8.x, backport-8.16, backport-8.17

#41817 [aws] [s3] Introduce ignore_older & start_timestamp for S3 input allowing better registry cleanups
  CHANGELOG.next.asciidoc
  x-pack/filebeat/_meta/config/filebeat.inputs.reference.xpack.yml.tmpl
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
  x-pack/filebeat/filebeat.reference.yml
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/config_test.go
  x-pack/filebeat/input/awss3/input_benchmark_test.go
  x-pack/filebeat/input/awss3/s3_filters.go
  x-pack/filebeat/input/awss3/s3_filters_test.go
  x-pack/filebeat/input/awss3/s3_input.go
  x-pack/filebeat/input/awss3/s3_test.go
Labels: enhancement, Team:obs-ds-hosted-services, Team:Elastic-Agent-Data-Plane, backport-8.x

#42150 Switch Docker images to UBI
  CHANGELOG.next.asciidoc
  dev-tools/packaging/packages.yml
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#42267 Remove TLSv1.0 from supported protocols
  libbeat/docs/shared-ssl-config.asciidoc
Labels: docs, backport-skip, Team:Elastic-Agent-Control-Plane

#42226 [filebeat] Add E2E testing for filebeat in otel mode
  NOTICE.txt
  go.mod
  go.sum
  x-pack/filebeat/tests/integration/otel_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42266 github-actions: support for copying the backport labels
  .github/workflows/mergify-labels-copier.yml
Labels: needs_team, backport-skip, backport-8.x

#42116 Add support for recursive structures in packetbeat's ECS field handlers
  CHANGELOG.next.asciidoc
  packetbeat/pb/event.go
  packetbeat/pb/event_test.go
Labels: bugfix, Team:Security-Linux Platform, backport-8.x

#42268 Add description of Wolfi container install image
  libbeat/docs/shared-beats-attributes.asciidoc
  libbeat/docs/shared-docker.asciidoc
Labels: docs, Team:Docs, backport-8.x, backport-8.17

#42274 [x-pack][metricbeat][iis] improve error handling on pdh counters in application_pool data stream
  CHANGELOG-developer.next.asciidoc
  x-pack/metricbeat/module/iis/application_pool/reader.go
Labels: Team:Obs-InfraObs, bugfix, backport-8.x

#42304 Allow use of version qualifier for staging artifacts
  .buildkite/packaging.pipeline.yml
  .buildkite/scripts/dra.sh
  .buildkite/scripts/packaging/prepare-release-manager.sh
Labels: ci, Team:Ingest-EngProd, backport-8.x

#42326 Don't run packaging snapshot with prereleases
  .buildkite/packaging.pipeline.yml
Labels: bug, needs_team, backport-7.17, backport-8.x, backport-8.16, backport-8.17

#42315 [streaming] - Made namespace consistent in logging & put a null check to stop paincs on shutdown
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/streaming/crowdstrike.go
  x-pack/filebeat/input/streaming/websocket.go
Labels: bugfix, Team:Security-Service Integrations, input:streaming, backport-8.x, backport-8.16, backport-8.17

#42306 x-pack/filebeat/docs - document gzip S3 object handling
  x-pack/filebeat/docs/inputs/input-aws-s3.asciidoc
Labels: enhancement, docs, Filebeat, needs_team, backport-8.x, backport-8.17

#42171 metricbeat/module/mongodb/collstats: Add extra collstats metrics
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/mongodb/collstats/_meta/data.json
  metricbeat/module/mongodb/collstats/_meta/fields.yml
  metricbeat/module/mongodb/collstats/collstats.go
  metricbeat/module/mongodb/collstats/data.go
  metricbeat/module/mongodb/collstats/data_test.go
  metricbeat/module/mongodb/fields.go
Labels: enhancement, Team:Obs-InfraObs, backport-8.x

#42360 Backport missing winlog changes
  filebeat/docs/inputs/input-winlog.asciidoc
  winlogbeat/sys/wineventlog/metadata_store.go
  winlogbeat/sys/wineventlog/metadata_store_test.go
  x-pack/winlogbeat/module/security/ingest/security.yml
Labels: backport-skip, Team:Security-Windows Platform

#42220 Add parsers documentation to Journald docs
  filebeat/docs/inputs/input-journald.asciidoc
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42359 github-actions: fix slack inputs
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-golang.yml
  .github/workflows/notify-stalled-snapshots.yml
  .github/workflows/updatecli-compose.yml
Labels: needs_team, backport-8.x

#42373 Revert "[8.x](backport #42359) github-actions: fix slack inputs"
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-golang.yml
  .github/workflows/notify-stalled-snapshots.yml
  .github/workflows/updatecli-compose.yml
Labels: needs_team

#42377 pre-commit: detect conflict if no ongoing merge operation
  .pre-commit-config.yaml
Labels: needs_team, backport-7.17, backport-8.x, backport-8.17

#42356 Increase Osquery max timeout limit to 24 hours
  CHANGELOG.next.asciidoc
  x-pack/osquerybeat/beater/osquerybeat.go
  x-pack/osquerybeat/internal/osqdcli/client.go
Labels: enhancement, Osquerybeat, Team:Security-Deployment and Devices, backport-8.x

#42382 pre-commit(merge-conflict): exclude NOTICE.txt
  .pre-commit-config.yaml
Labels: needs_team, backport-7.17, backport-8.x, backport-8.17

#42328 Remove the system-logs input
  CHANGELOG-developer.next.asciidoc
  filebeat/include/list.go
  filebeat/input/default-inputs/inputs_linux.go
  filebeat/input/systemlogs/input.go
  filebeat/input/systemlogs/input_linux.go
  filebeat/input/systemlogs/input_linux_test.go
  filebeat/input/systemlogs/input_other.go
  filebeat/input/systemlogs/input_test.go
  filebeat/tests/integration/systemlogs_all_test.go
  filebeat/tests/integration/systemlogs_linux_test.go
  filebeat/tests/integration/systemlogs_other_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42221 Fix flakiness on TestFilestreamMetadataUpdatedOnRename
  filebeat/input/filestream/input_integration_test.go
Labels: Team:Elastic-Agent-Data-Plane

#42376 Revert "Revert "[8.x](backport #42359) github-actions: fix slack inputs""
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-golang.yml
  .github/workflows/notify-stalled-snapshots.yml
  .github/workflows/updatecli-compose.yml
Labels: needs_team

#42391 CI: x-pack/packetbeat: Enable GCP authentication for system tests
  .buildkite/hooks/pre-command
  .buildkite/scripts/gcp_auth.sh
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
Labels: enhancement, Team:Ingest-EngProd, backport-8.x

#42389 managerV2_test: Fix code smell around state check
  x-pack/filebeat/tests/integration/managerV2_test.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x

#42292 fix setting namespace for non beat receivers
  CHANGELOG.next.asciidoc
  libbeat/cmd/instance/beat.go
Labels: Team:Elastic-Agent-Data-Plane, bugfix, backport-8.x

#42329 Prevent 'thundering herd' issue with the scale preset
  libbeat/outputs/elasticsearch/config_presets.go
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-8.x

#42401 Handle authorization errors in Kafka output
  CHANGELOG.next.asciidoc
  libbeat/outputs/kafka/client.go
  libbeat/tests/integration/kafka_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41795 Add registry to Filebeat's diagnostic
  CHANGELOG.next.asciidoc
  filebeat/beater/diagnostics.go
  filebeat/beater/diagnostics_test.go
  filebeat/beater/filebeat.go
  x-pack/filebeat/input/benchmark/input.go
  x-pack/filebeat/tests/integration/registrydiagnostics_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42405 Fix some golangci-lint errors
  filebeat/registrar/registrar.go
  libbeat/common/cleanup/cleanup.go
  libbeat/common/schema/schema_test.go
  libbeat/statestore/error.go
  libbeat/statestore/internal/storecompliance/reg.go
  libbeat/statestore/mock_test.go
  libbeat/statestore/storetest/storetest.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x

#41887 Remove zookeeper mntr hostname
  CHANGELOG.next.asciidoc
  libbeat/docs/troubleshooting/default_field.md
  libbeat/kibana/testdata/extensive/fields.yml
  libbeat/kibana/testdata/extensive/metricbeat-6.ndjson
  metricbeat/docs/fields.asciidoc
  metricbeat/module/zookeeper/fields.go
  metricbeat/module/zookeeper/mntr/_meta/docs.asciidoc
  metricbeat/module/zookeeper/mntr/_meta/fields.yml
Labels: cleanup, Team:Obs-InfraObs, backport-8.x

#42312 [filebeat] Add support for `bulk_max_size` and `preset`
  NOTICE.txt
  go.mod
  libbeat/otelbeat/beatconverter/beatconverter.go
  libbeat/otelbeat/beatconverter/beatconverter_test.go
  libbeat/otelbeat/beatconverter/config_otel_test.go
  libbeat/otelbeat/beatconverter/testdata/basic-op.yml
  libbeat/otelbeat/beatconverter/testdata/basic.yml
  libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel.go
  libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel_test.go
  libbeat/outputs/elasticsearch/config.go
  libbeat/outputs/elasticsearch/config_presets.go
  libbeat/outputs/elasticsearch/config_presets_test.go
  libbeat/outputs/elasticsearch/elasticsearch.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#41748 Autodiscover memleak
  CHANGELOG.next.asciidoc
  libbeat/autodiscover/autodiscover.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42295 Limit usage of the deprecated `log` and `container` inputs
  CHANGELOG.next.asciidoc
  filebeat/_meta/test/module/foo/multi/config/multi.yml
  filebeat/_meta/test/module/foo/multibad/config/multi.yml
  filebeat/docs/autodiscover-hints.asciidoc
  filebeat/docs/autodiscover-nomad-config.asciidoc
  filebeat/docs/filebeat-filtering.asciidoc
  filebeat/docs/how-filebeat-works.asciidoc
  filebeat/docs/inputs/input-container.asciidoc
  filebeat/docs/inputs/input-filestream-file-options.asciidoc
  filebeat/docs/inputs/input-filestream-reader-options.asciidoc
  filebeat/docs/inputs/input-log.asciidoc
  filebeat/docs/reload-configuration.asciidoc
  filebeat/fileset/fileset.go
  filebeat/input/container/input.go
  filebeat/input/container/input_test.go
  filebeat/input/filestream/fswatch_test.go
  filebeat/input/filestream/legacy_metrics_integration_test.go
  filebeat/input/filestream/takeover/takeover_test.go
  filebeat/input/log/input.go
  filebeat/input/log/input_test.go
  filebeat/tests/files/config.yml
  filebeat/tests/load/filebeat.yml
  filebeat/tests/open-file-handlers/filebeat.yml
  filebeat/tests/system/config/filebeat.yml.j2
  filebeat/tests/system/config/filebeat_inputs.yml.j2
  filebeat/tests/system/test_autodiscover.py
  filebeat/tests/system/test_container.py
  filebeat/tests/system/test_crawler.py
  filebeat/tests/system/test_registrar.py
  filebeat/tests/system/test_reload_inputs.py
  filebeat/tests/system/test_reload_modules.py
  filebeat/tests/system/test_shutdown.py
  testing/environments/snapshot.yml
Labels: Filebeat, breaking change, backport-skip, Team:Elastic-Agent-Data-Plane, deprecation

#42327 x-pack/filebeat/input: Fix truncation of bodies in request tracing
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
  x-pack/filebeat/docs/inputs/input-entity-analytics.asciidoc
  x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
  x-pack/filebeat/docs/inputs/input-httpjson.asciidoc
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/entityanalytics/provider/azuread/fetcher/graph/graph.go
  x-pack/filebeat/input/entityanalytics/provider/jamf/jamf.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
  x-pack/filebeat/input/httpjson/input.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-8.x

#41446 [filebeat] Elasticsearch state storage for httpjson and cel inputs
  filebeat/beater/filebeat.go
  filebeat/beater/store.go
  filebeat/features/features.go
  filebeat/features/features_test.go
  filebeat/input/filestream/environment_test.go
  filebeat/input/filestream/input_test.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/filestream/internal/input-logfile/store.go
  filebeat/input/filestream/internal/input-logfile/store_test.go
  filebeat/input/journald/environment_test.go
  filebeat/input/journald/input_filtering_test.go
  filebeat/input/v2/input-cursor/manager.go
  filebeat/input/v2/input-cursor/store.go
  filebeat/input/v2/input-cursor/store_test.go
  filebeat/registrar/registrar.go
  libbeat/statestore/backend/backend.go
  libbeat/statestore/backend/es/error.go
  libbeat/statestore/backend/es/notifier.go
  libbeat/statestore/backend/es/notifier_test.go
  libbeat/statestore/backend/es/registry.go
  libbeat/statestore/backend/es/store.go
  libbeat/statestore/backend/memlog/store.go
  libbeat/statestore/mock_test.go
  libbeat/statestore/store.go
  libbeat/statestore/storetest/storetest.go
  x-pack/filebeat/input/awss3/states.go
  x-pack/filebeat/input/awss3/states_test.go
  x-pack/filebeat/input/salesforce/input_manager_test.go
  x-pack/filebeat/tests/integration/managerV2_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, Team:Security-Deployment and Devices, backport-8.x

#42434 Upgrade dbadger-io to v4.4.0
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Service-Integrations

#42438 Document that `pipeline` needs to be lowercase
  filebeat/docs/inputs/input-common-options.asciidoc
  libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: Team:Elastic-Agent-Data-Plane, backport-7.17, backport-8.x, backport-8.16, backport-8.17

#42368 [filebeat] Add intermediary support for `ssl.verification_mode`
  libbeat/otelbeat/oteltranslate/tls_otel.go
  libbeat/otelbeat/oteltranslate/tls_otel_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42421 [metricbeat] Gather more fields from _node/stats
  CHANGELOG.next.asciidoc
  metricbeat/docs/fields.asciidoc
  metricbeat/module/elasticsearch/fields.go
  metricbeat/module/elasticsearch/node_stats/_meta/data.json
  metricbeat/module/elasticsearch/node_stats/_meta/fields.yml
  metricbeat/module/elasticsearch/node_stats/_meta/test/node_stats.817.json
  metricbeat/module/elasticsearch/node_stats/data.go
  metricbeat/module/elasticsearch/node_stats/node_stats.go
  metricbeat/module/elasticsearch/node_stats/node_stats_test.go
Labels: enhancement, Feature:Stack Monitoring, Team:Monitoring, backport-8.x

#42435 Remove erroneous status reporting
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/input.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-8.x

#42455 Backport #43434 to 8.16: Upgrade dbadger-io to v4.4.0
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Service-Integrations

#42348 Updated spec file for agentbeat to reflect new binary distribution
  x-pack/agentbeat/agentbeat.spec.yml
Labels: enhancement, needs_team, backport-skip

#42397 [metricbeat] [meraki] Ignore 400 error for unsupported per-device licensing
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/meraki/device_health/devices.go
Labels: Team:Obs-InfraObs, backport-8.x, backport-8.17

#42426 Fix Elasticsearch index behavior in case of missing settings
  CHANGELOG.next.asciidoc
  filebeat/tests/system/test_input.py
  libbeat/tests/system/beat/common_tests.py
  libbeat/tests/system/idxmgmt.py
  libbeat/tests/system/test_cmd_setup_index_management.py
  metricbeat/module/elasticsearch/index/_meta/test/cluster_state.7.17.27.json
  metricbeat/module/elasticsearch/index/_meta/test/cluster_state.710.json
  metricbeat/module/elasticsearch/index/_meta/test/generate.sh
  metricbeat/module/elasticsearch/index/_meta/test/root.7.17.27.json
  metricbeat/module/elasticsearch/index/_meta/test/root.710.json
  metricbeat/module/elasticsearch/index/_meta/test/root.8.17.0.json
  metricbeat/module/elasticsearch/index/_meta/test/settings.7.17.27.json
  metricbeat/module/elasticsearch/index/_meta/test/settings.8.17.0.json
  metricbeat/module/elasticsearch/index/_meta/test/settings.json
  metricbeat/module/elasticsearch/index/_meta/test/stats.175.json
  metricbeat/module/elasticsearch/index/_meta/test/stats.201.json
  metricbeat/module/elasticsearch/index/_meta/test/stats.240.json
  metricbeat/module/elasticsearch/index/_meta/test/stats.512.json
  metricbeat/module/elasticsearch/index/_meta/test/stats.623.json
  metricbeat/module/elasticsearch/index/_meta/test/stats.7.17.27.json
  metricbeat/module/elasticsearch/index/_meta/test/stats.700-alpha1.json
  metricbeat/module/elasticsearch/index/_meta/test/stats.8.17.0.json
  metricbeat/module/elasticsearch/index/_meta/test/stats.800.bench.json
  metricbeat/module/elasticsearch/index/_meta/test/stats.800.snapshot.20201118.json
  metricbeat/module/elasticsearch/index/_meta/test/xpack_usage.7.17.27.json
  metricbeat/module/elasticsearch/index/_meta/test/xpack_usage.8.17.0.json
  metricbeat/module/elasticsearch/index/data.go
  metricbeat/module/elasticsearch/index/data_test.go
  packetbeat/tests/system/packetbeat.py
  packetbeat/tests/system/test_0065_unmatched_http.py
  x-pack/filebeat/tests/system/test_http_endpoint.py
Labels: bug, Feature:Stack Monitoring, Team:Monitoring, backport-8.x, backport-8.17

#42439 Include full queue metrics in the monitoring index
  CHANGELOG.next.asciidoc
  libbeat/publisher/pipeline/monitoring.go
  metricbeat/module/beat/stats/data.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-8.x

#42473 Comment out Journald configuration in Filebeat's default config file
  filebeat/_meta/config/filebeat.inputs.yml.tmpl
  filebeat/filebeat.yml
  x-pack/filebeat/filebeat.yml
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42469 otelconsumer: remove metadata and adjust timestamp format
  libbeat/outputs/otelconsumer/otelconsumer.go
  libbeat/outputs/otelconsumer/otelconsumer_test.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x

#42172 [tests] Fix packetbeat system tests on windows
  .buildkite/scripts/gcp_auth.ps1
  .buildkite/scripts/gcp_auth.sh
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  x-pack/packetbeat/magefile.go
  x-pack/packetbeat/tests/system/app_test.go
Labels: Packetbeat, failed-test, Team:Security-Linux Platform, Team:Security-Windows Platform, backport-8.x

#42017 [Metricbeat] Windows Module add wmi metricset
  .github/CODEOWNERS
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/windows.asciidoc
  metricbeat/docs/modules/windows/wmi.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_common.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/windows/_meta/config.reference.yml
  metricbeat/module/windows/_meta/config.yml
  metricbeat/module/windows/fields.go
  metricbeat/module/windows/wmi/_meta/data.json
  metricbeat/module/windows/wmi/_meta/docs.asciidoc
  metricbeat/module/windows/wmi/_meta/fields.yml
  metricbeat/module/windows/wmi/config.go
  metricbeat/module/windows/wmi/config_test.go
  metricbeat/module/windows/wmi/doc.go
  metricbeat/module/windows/wmi/utils.go
  metricbeat/module/windows/wmi/utils_test.go
  metricbeat/module/windows/wmi/wmi.go
  metricbeat/module/windows/wmi/wmi_test.go
  metricbeat/modules.d/windows.yml.disabled
  x-pack/metricbeat/metricbeat.reference.yml
Labels: needs_team, backport-8.x

#42503 Use centralized version qualifier
  .buildkite/packaging.pipeline.yml
  .buildkite/scripts/version_qualifier.sh
Labels: ci, needs_team, forwardport-main, backport-8.x, backport-8.16, backport-8.17

#42478 [Heartbeat] Upgrade Node to LTS v18.20.6
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:obs-ds-hosted-services, release-note:skip, dependency, backport-8.x

#42403 Update Journald fields to better match ECS
  CHANGELOG.next.asciidoc
  filebeat/docs/inputs/input-journald.asciidoc
  filebeat/input/journald/input.go
  filebeat/input/journald/input_filtering_test.go
  filebeat/input/journald/input_parsers_test.go
  filebeat/input/journald/input_test.go
  filebeat/input/journald/pkg/journalfield/conv_test.go
  filebeat/input/journald/pkg/journalfield/default.go
  filebeat/input/journald/testdata/input-multiline-parser-events.json
  filebeat/input/journald/testdata/ndjson-parser.export
  filebeat/input/journald/testdata/ndjson-parser.journal.gz
  filebeat/module/system/auth/test/debian-12.journal-expected.json
  filebeat/module/system/syslog/test/debian-12.journal-expected.json
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42510 mergify: remove backport-8.x enforcement
  .mergify.yml
Labels: needs_team, backport-skip

#42521 Update branch filters to include/exclude 9.*
  catalog-info.yaml
Labels: Team:Ingest-EngProd, backport-8.x, backport-8.16, backport-8.17, backport-8.18, backport-9.0

#42514 Write latency statistics go under a histogram key
  metricbeat/docs/fields.asciidoc
  metricbeat/module/beat/fields.go
  metricbeat/module/beat/stats/_meta/fields.yml
  metricbeat/module/beat/stats/data.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17, backport-8.18

#42479 [Heartbeat] Upgrade Node to LTS v18.20.6
  dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:obs-ds-hosted-services, release-note:skip, dependency, backport-skip

#42412 otelconsumer: set document id attribute for elasticsearchexporter
  libbeat/outputs/otelconsumer/otelconsumer.go
  libbeat/outputs/otelconsumer/otelconsumer_test.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x

#42462 Add status reporting for Journald input
  CHANGELOG.next.asciidoc
  filebeat/input/journald/environment_test.go
  filebeat/input/journald/input.go
  filebeat/input/journald/input_test.go
  filebeat/input/v2/input.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#42537 Wire in Kafka read and write metrics
  libbeat/outputs/kafka/config.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17, backport-8.18, backport-9.0
