Repository elastic/beats, pull requests merged in 2025-10, with the labels that each got.

#46864 Skip filebeatreceiver TestMultipleReceivers for now
  x-pack/filebeat/fbreceiver/receiver_test.go
Labels: Team:Elastic-Agent-Data-Plane

#46810 [DO NOT MERGE BEFORE 9.2 FF] New CI check to verify if a changelog fragment is in the PR
  .github/workflows/fragment-in-pr.yml
Labels: backport-skip, Team:Elastic-Agent-Data-Plane, skip-changelog

#46883 Remove old changelog files
  CHANGELOG.asciidoc
  CHANGELOG.next.asciidoc
Labels: Team:Elastic-Agent-Data-Plane, skip-changelog

#46865 enforce ordering of libbeat API server Start/Stop functions
  libbeat/api/server.go
  libbeat/api/server_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.1, skip-changelog, backport-9.2

#46844 [beatreceivers] fix race condition in beat LoadMeta
  libbeat/cmd/instance/beat.go
  libbeat/cmd/instance/beat_test.go
  x-pack/filebeat/fbreceiver/receiver_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.1, skip-changelog, backport-9.2

#46721 [OTel] Add E2E to ensure data consistency in Logstash Exporter
  x-pack/filebeat/docker-compose.yml
  x-pack/filebeat/tests/integration/logstash/config/pipelines.yml
  x-pack/filebeat/tests/integration/otel_lsexporter_test.go
Labels: release-note:skip, Team:Elastic-Agent-Data-Plane

#46931 Remove the data plane team as the changelog fragment owners.
  .github/CODEOWNERS
Labels: needs_team

#46528 [docs] Add missing page-level `applies_to` to Auditbeat modules
  auditbeat/scripts/docs_collector.py
  docs/reference/auditbeat/auditbeat-module-auditd.md
  docs/reference/auditbeat/auditbeat-module-file_integrity.md
  docs/reference/auditbeat/auditbeat-modules.md
Labels: docs, Team:Docs, backport-active-9, skip-changelog

#46944 [DOCS] Update API key link
  docs/reference/serverless/beats.md
Labels: docs, Team:Docs, backport-active-9

#46913 [Filebeat/Journald] Fix flakiness from TestDoubleStarCanBeUsed
  .buildkite/filebeat/filebeat-pipeline.yml
  filebeat/input/journald/environment_test.go
  filebeat/input/journald/input_test.go
Labels: Team:Elastic-Agent-Data-Plane, skip-changelog, backport-9.2

#45732 Add `UpdateStatus` reporter to packetbeat runners
  changelog/fragments/1759436464-add-packetbeat-status-reporter.yaml
  libbeat/cfgfile/list.go
  libbeat/cfgfile/reload.go
  packetbeat/beater/processor.go
  packetbeat/sniffer/sniffer.go
Labels: Team:Elastic-Agent-Data-Plane, Team:Security-Linux Platform

#46866 Doc: Use current Logstash SSL settings for beats
  docs/reference/auditbeat/configuring-ssl-logstash.md
  docs/reference/auditbeat/ssl-client-fails.md
  docs/reference/filebeat/configuring-ssl-logstash.md
  docs/reference/filebeat/ssl-client-fails.md
  docs/reference/heartbeat/configuring-ssl-logstash.md
  docs/reference/heartbeat/ssl-client-fails.md
  docs/reference/metricbeat/configuring-ssl-logstash.md
  docs/reference/metricbeat/ssl-client-fails.md
  docs/reference/packetbeat/configuring-ssl-logstash.md
  docs/reference/packetbeat/ssl-client-fails.md
  docs/reference/winlogbeat/configuring-ssl-logstash.md
  docs/reference/winlogbeat/ssl-client-fails.md
Labels: docs, Team:Docs, backport-9.0, backport-9.1, skip-changelog
