Repository elastic/beats, pull requests merged in 2025-03, with the labels that each got.

#42794 [azure-eventhub] Update sdk/messaging/azeventhubs to v1.3.0
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:obs-ds-hosted-services, Team:Elastic-Agent-Data-Plane, input:azure-eventhub, backport-8.x, backport-8.17

#35669 [Auditbeat] improve docs for exclude_files option of file_integrity
  auditbeat/auditbeat.reference.yml
  auditbeat/docs/modules/file_integrity.asciidoc
  auditbeat/module/file_integrity/_meta/config.yml.tmpl
  auditbeat/module/file_integrity/_meta/docs.asciidoc
  x-pack/auditbeat/auditbeat.reference.yml
Labels: docs, Auditbeat, Team:Security-Linux Platform, backport-8.x

#34331 x-pack/winlogbeat - fix typo in PowerShell dashboard
  x-pack/winlogbeat/module/powershell/_meta/kibana/7/dashboard/c77e06c0-9e7c-11ea-af6f-cfdb1ee1d6c8.json
Labels: Winlogbeat, Team:Security-Windows Platform, backport-8.x

#42849 [otelconsumer]: Add support for conversion of type any
  libbeat/otelbeat/otelmap/otelmap.go
  libbeat/otelbeat/otelmap/otelmap_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#42943 [chore] - Introduce a helper to setup registry
  libbeat/beat/info.go
  libbeat/cmd/instance/beat.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#42796 x-pack/filebeat/input/entityanalytics/provider/activedirectory: do not consider computers to be users
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory/activedirectory.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-active-8, backport-active-9

#42996 [filebeat] Skip test case for sequoia
  x-pack/filebeat/input/unifiedlogs/input_test.go
Labels: Filebeat, macOS, macOSArm, macos-m1, Team:Security-Windows Platform, backport-8.x, backport-8.18, backport-active-9

#43027 [winlogbeat] Fix boolean key in security pipelines and sync pipelines with integration
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/powershell/ingest/powershell.yml
  x-pack/winlogbeat/module/powershell/ingest/powershell_operational.yml
  x-pack/winlogbeat/module/routing/ingest/routing.yml
  x-pack/winlogbeat/module/security/ingest/security.yml
  x-pack/winlogbeat/module/security/ingest/security_standard.yml
  x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml
Labels: Winlogbeat, bugfix, Team:Security-Windows Platform, backport-active-all

#43043 Revert "[8.16](backport #43027) [winlogbeat] Fix boolean key in security pipelines and sync pipelines with integration"
  CHANGELOG.next.asciidoc
  x-pack/winlogbeat/module/powershell/ingest/powershell.yml
  x-pack/winlogbeat/module/powershell/ingest/powershell_operational.yml
  x-pack/winlogbeat/module/routing/ingest/routing.yml
  x-pack/winlogbeat/module/security/ingest/security.yml
  x-pack/winlogbeat/module/security/ingest/security_standard.yml
  x-pack/winlogbeat/module/sysmon/ingest/sysmon.yml
Labels: needs_team

#42402 FIPS Build
  dev-tools/mage/build.go
  dev-tools/mage/build_test.go
  dev-tools/mage/common.go
  dev-tools/mage/crossbuild.go
  dev-tools/mage/dockerbuilder.go
  dev-tools/mage/gotest.go
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgtypes.go
  dev-tools/mage/settings.go
  dev-tools/packaging/package_test.go
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-8.x

#42998 Add Windows 2025 for unit test steps
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/metricbeat/pipeline.yml
Labels: ci, Team:Ingest-EngProd, windows

#43052 [REVERT] Update Stack Monitoring data stream to 9
  metricbeat/helper/elastic/elastic.go
  metricbeat/helper/elastic/elastic_test.go
Labels: Metricbeat, monitoring, Team:Elastic-Agent-Data-Plane, Team:Monitoring, backport-9.0

#43026 Don't package arm64 on amd64 workers
  .buildkite/packaging.pipeline.yml
Labels: needs_team, backport-active-8, backport-active-9

#42992 filebeat: make deep copy before notifying of config change
  filebeat/beater/filebeat.go
  libbeat/statestore/backend/es/store.go
  x-pack/filebeat/tests/integration/managerV2_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.18, backport-9.0, backport-active-all

#42420 [AWSs3 Input] Handle unexpectedEOF errors
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/awss3/s3_objects.go
Labels: Team:obs-ds-hosted-services, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-active-8, backport-active-9

#42798 [fbreceivier] inject log level
  libbeat/otelbeat/beatconverter/beatconverter.go
  libbeat/otelbeat/beatconverter/beatconverter_test.go
  libbeat/otelbeat/beatconverter/logging.go
Labels: Team:Elastic-Agent-Data-Plane

#43089 [filebeat] Winlog input reports status to elastic-agent
  CHANGELOG.next.asciidoc
  filebeat/input/winlog/input.go
  winlogbeat/beater/eventlogger.go
  winlogbeat/eventlog/runner.go
Labels: enhancement, Filebeat, Team:Security-Windows Platform, backport-8.x, backport-active-9

#42966 fix(libbeat): mitigate race condition in ratelimit processor
  CHANGELOG.next.asciidoc
  libbeat/processors/ratelimit/rate_limit_test.go
  libbeat/processors/ratelimit/token_bucket.go
Labels: Team:Elastic-Agent-Data-Plane, bugfix, backport-active-all

#43124 Disable broken mssql integration tests
  x-pack/metricbeat/module/mssql/performance/performance_integration_test.go
  x-pack/metricbeat/module/mssql/transaction_log/transaction_log_integration_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, Team:Service-Integrations, Team:Obs-InfraObs, backport-active-all

#43132 [metricbeat] Fix perfmon test
  metricbeat/module/windows/perfmon/data_test.go
Labels: Metricbeat, needs_team, backport-8.x, backport-active-9

#43106 "(chore) Update elastic-agent-lib to v0.18.9"
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#43125 x-pack/filebeat/input/cel: fix incorrect test logic
  x-pack/filebeat/input/cel/input_test.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-active-8, backport-active-9

#43159 chore: fix flakiness and add comments to explain testing logic
  x-pack/filebeat/input/awss3/sqs_test.go
Labels: Team:obs-ds-hosted-services, backport-8.x

#43160 fix flaky test metricbeat/module/apache/status TestFetchTimeout
  metricbeat/module/apache/status/status_test.go
Labels: release-note:skip, Team:Elastic-Agent-Data-Plane, backport-active-all

#43072 fix: logging args count mismatch in metricbeat/module/redis/key/key.go
  CHANGELOG.next.asciidoc
  metricbeat/module/redis/key/key.go
Labels: bug, Team:Obs-InfraObs, backport-8.x

#43107 Improve integration test framework
  filebeat/testing/integration/sample_test.go
  libbeat/testing/integration/integration.go
  libbeat/testing/integration/run_beat.go
Labels: enhancement, Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#42914 Fix permissions for config files used in tests
  CHANGELOG-developer.next.asciidoc
  filebeat/beater/filebeat_test.go
  filebeat/config/main_test.go
  filebeat/fileset/main_test.go
  metricbeat/mb/main_test.go
  metricbeat/tests/system/test_cmd.py
  metricbeat/tests/system/test_lightmodules.py
  metricbeat/tests/system/test_reload.py
  testing/testflag/testflag.go
Labels: Team:Elastic-Agent-Data-Plane, backport-active-all

#43048 Revert "Serverless beats tests pipeline resource"
  catalog-info.yaml
Labels: needs_team

#43119 Disable flaky mssql tests
  x-pack/metricbeat/module/mssql/test_mssql.py
  x-pack/metricbeat/module/sql/query/test_sql_mssql.py
Labels: bug, Team:Elastic-Agent-Data-Plane, Team:Service-Integrations, Team:Obs-InfraObs, backport-active-all

#43169 x-pack/filebeat/input/azureblobstorage: prevent key logging in fetch operation
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/azureblobstorage/client.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-active-8, backport-active-9

#43121 Fix flaky http_endpoint test
  x-pack/filebeat/tests/system/test_http_endpoint.py
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-active-all

#43228 Remove functionbeat from DRA in 8x branch
  .buildkite/packaging.pipeline.yml
Labels: needs_team

#42886 [feat][fbreceiver] - enable http internal monitoring
  NOTICE.txt
  go.mod
  go.sum
  libbeat/api/routes.go
  libbeat/beat/info.go
  libbeat/cmd/instance/beat.go
  x-pack/filebeat/fbreceiver/factory.go
  x-pack/filebeat/fbreceiver/receiver.go
  x-pack/filebeat/tests/integration/otel_test.go
Labels: enhancement, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#43171 x-pack/filebeat/input/http_endpoint: allow limiting body size
  CHANGELOG.next.asciidoc
  x-pack/filebeat/docs/inputs/input-http-endpoint.asciidoc
  x-pack/filebeat/input/http_endpoint/config.go
  x-pack/filebeat/input/http_endpoint/input.go
  x-pack/filebeat/input/http_endpoint/validate.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-active-8, backport-active-9

#43149 Align setup-python action with prior branches
  .github/workflows/check-dev-tools.yml
Labels: ci, needs_team, backport-9.0

#43007 [CI] Trigger Serverless beats tests in the agent repo
  .buildkite/pipeline.yml
Labels: enhancement, backport-skip, Team:Ingest-EngProd

#42392 add state_horizontalpodautoscaler metricset
  deploy/kubernetes/metricbeat-kubernetes.yaml
  deploy/kubernetes/metricbeat/metricbeat-configmap.yaml
  metricbeat/docs/fields.asciidoc
  metricbeat/docs/modules/kubernetes.asciidoc
  metricbeat/docs/modules/kubernetes/state_horizontalpodautoscaler.asciidoc
  metricbeat/docs/modules_list.asciidoc
  metricbeat/include/list_docker.go
  metricbeat/metricbeat.reference.yml
  metricbeat/module/kubernetes/_meta/config.reference.yml
  metricbeat/module/kubernetes/_meta/test/KSM/docs.plain
  metricbeat/module/kubernetes/_meta/test/KSM/ksm.v2.10.0.plain
  metricbeat/module/kubernetes/_meta/test/KSM/ksm.v2.11.0.plain
  metricbeat/module/kubernetes/_meta/test/KSM/ksm.v2.12.0.plain
  metricbeat/module/kubernetes/fields.go
  metricbeat/module/kubernetes/kubernetes.yml
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/_meta/data.json
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/_meta/docs.asciidoc
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/_meta/fields.yml
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/_meta/test/ksm.v2.10.0.plain.expected
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/_meta/test/ksm.v2.11.0.plain.expected
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/_meta/test/ksm.v2.12.0.plain.expected
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/_meta/testdata/config.yml
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/_meta/testdata/docs.plain-expected.json
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/_meta/testdata/ksm.v2.10.0.plain-expected.json
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/_meta/testdata/ksm.v2.11.0.plain-expected.json
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/_meta/testdata/ksm.v2.12.0.plain-expected.json
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/state_horizontalpodautoscaler.go
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/state_horizontalpodautoscaler_integration_test.go
  metricbeat/module/kubernetes/state_horizontalpodautoscaler/state_horizontalpodautoscaler_test.go
  metricbeat/module/kubernetes/util/kubernetes.go
  x-pack/metricbeat/metricbeat.reference.yml
Labels: Team:Cloudnative-Monitoring, backport-8.x

#43170 bk(package jobs): Don't package arm64 on amd64 workers
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.agentbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: needs_team, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#43254 Skip flaky vsphere datastore TestFetchEventContents
  metricbeat/module/vsphere/datastore/datastore_test.go
Labels: Team:Elastic-Agent-Data-Plane, Team:Service-Integrations, backport-active-all

#43243 Removed system indices from extra metadata pull in Elasticsearch module
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/index/data.go
Labels: enhancement, Feature:Stack Monitoring, Team:Monitoring, backport-8.x, backport-9.0

#43249 Skip flaky kafka module test
  metricbeat/module/kafka/broker/broker_integration_test.go
  metricbeat/module/kafka/consumer/consumer_integration_test.go
  metricbeat/module/kafka/consumergroup/consumergroup_integration_test.go
  metricbeat/module/kafka/partition/partition_integration_test.go
  metricbeat/module/kafka/producer/producer_integration_test.go
Labels: Team:Service-Integrations, backport-active-all

#43019 ci(packaging): add aarch64 on a PR basis for x-pack/osquerybeat
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
Labels: needs_team, backport-active-all

#43081 otel: add test for multiple Beats receivers running in the same process
  libbeat/otelbeat/oteltest/oteltest.go
  x-pack/filebeat/fbreceiver/receiver_test.go
  x-pack/metricbeat/mbreceiver/receiver_test.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#43272 [ci] Add win2025 to winlogbeat CI
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: Winlogbeat, ci, Team:Security-Windows Platform, backport-8.x, backport-8.17, backport-8.18, backport-active-9

#43302 oteltest: make CheckReceivers environment more similar to the collector
  libbeat/otelbeat/oteltest/oteltest.go
  x-pack/filebeat/fbreceiver/receiver_test.go
  x-pack/metricbeat/mbreceiver/receiver_test.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#43241 Add aerospike input in agentbaet-spec.yml
  x-pack/agentbeat/agentbeat.spec.yml
Labels: Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, backport-8.x

#43104 feat: add warning log message to indicate vSphere connection is configured as insecure
  CHANGELOG.next.asciidoc
  metricbeat/module/vsphere/cluster/cluster.go
  metricbeat/module/vsphere/datastore/datastore.go
  metricbeat/module/vsphere/datastorecluster/datastorecluster.go
  metricbeat/module/vsphere/host/host.go
  metricbeat/module/vsphere/network/network.go
  metricbeat/module/vsphere/resourcepool/resourcepool.go
  metricbeat/module/vsphere/security/logging.go
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
Labels: enhancement, Team:Obs-InfraObs, backport-8.x, backport-active-all

#43058 (cleanup) Remove the unused libbeat/common/op package
  libbeat/common/op/cancel.go
  libbeat/common/op/signal.go
  libbeat/common/op/signal_util.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#43255 Skip flaky kubernetes state_job TestFetchMetricset
  metricbeat/module/kubernetes/state_job/state_job_integration_test.go
Labels: Team:obs-ds-hosted-services, Team:Elastic-Agent-Data-Plane, backport-active-all

#43342 [Flaky test] Disable flaky metricbeat process test
  metricbeat/module/system/process/process_test.go
Labels: flaky-test, Team:Elastic-Agent-Data-Plane, backport-active-all

#42222 [fix:filebeat/input/redis/slowlog] Correctly parse Redis role values in connection receive
  filebeat/input/redis/harvester.go
  filebeat/input/redis/redis_integration_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#43063 filebeat,libbeat,x-pack/filebeat: clean up state store types
  filebeat/beater/filebeat.go
  filebeat/beater/store.go
  filebeat/input/default-inputs/inputs.go
  filebeat/input/default-inputs/inputs_linux.go
  filebeat/input/default-inputs/inputs_windows.go
  filebeat/input/filestream/environment_test.go
  filebeat/input/filestream/input.go
  filebeat/input/filestream/input_test.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/filestream/internal/input-logfile/store.go
  filebeat/input/filestream/internal/input-logfile/store_test.go
  filebeat/input/journald/environment_test.go
  filebeat/input/journald/input.go
  filebeat/input/journald/input_filtering_test.go
  filebeat/input/journald/input_stub.go
  filebeat/input/v2/input-cursor/manager.go
  filebeat/input/v2/input-cursor/store.go
  filebeat/input/v2/input-cursor/store_test.go
  filebeat/input/winlog/input.go
  filebeat/registrar/registrar.go
  libbeat/statestore/store.go
  x-pack/filebeat/input/awss3/input.go
  x-pack/filebeat/input/awss3/s3_input.go
  x-pack/filebeat/input/awss3/states.go
  x-pack/filebeat/input/awss3/states_test.go
  x-pack/filebeat/input/azureblobstorage/input.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_manager.go
  x-pack/filebeat/input/default-inputs/inputs.go
  x-pack/filebeat/input/default-inputs/inputs_aix.go
  x-pack/filebeat/input/default-inputs/inputs_darwin.go
  x-pack/filebeat/input/default-inputs/inputs_other.go
  x-pack/filebeat/input/default-inputs/inputs_windows.go
  x-pack/filebeat/input/gcs/input.go
  x-pack/filebeat/input/httpjson/input.go
  x-pack/filebeat/input/httpjson/input_manager.go
  x-pack/filebeat/input/o365audit/input.go
  x-pack/filebeat/input/salesforce/input.go
  x-pack/filebeat/input/salesforce/input_manager.go
  x-pack/filebeat/input/salesforce/input_manager_test.go
  x-pack/filebeat/input/streaming/input.go
  x-pack/filebeat/input/streaming/input_manager.go
  x-pack/filebeat/input/unifiedlogs/input.go
Labels: enhancement, Filebeat, libbeat, Team:obs-ds-hosted-services, Team:Obs-InfraObs, Team:Security-Service Integrations, Team:Security-Windows Platform, backport-8.x, backport-active-9

#43364 x-pack/filebeat/input/entityanalytics/provider/activedirectory: do not convert special values of accountExpires
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/entityanalytics/provider/activedirectory/internal/activedirectory/activedirectory.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, backport-8.x, backport-9.0

#43322 Allow faccessat(2) as well as faccessat2(2)
  CHANGELOG.next.asciidoc
  libbeat/common/seccomp/policy_linux_386.go
  libbeat/common/seccomp/policy_linux_amd64.go
Labels: bug, Team:Elastic-Agent-Data-Plane, Team:Security-Linux Platform, backport-8.x

#43380 [cleanup] Remove confusing always-nil return value
  filebeat/input/v2/loader.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#43317 Fix flaky envoyproxy + apache tests
  metricbeat/module/apache/status/status_test.go
  metricbeat/module/envoyproxy/server/server_test.go
Labels: flaky-test, Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs

#43280 bk(packaging): use arm64 for darwin/arm64
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/packaging.pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/winlogbeat/pipeline.winlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.agentbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
Labels: needs_team, backport-8.x, backport-8.18, backport-9.0

#43387 bk(dra): split arm64 for linux and darwin from amd64
  .buildkite/packaging.pipeline.yml
Labels: needs_team, backport-8.x, backport-8.18, backport-9.0

#43363 Update Beats 'Upgrade' docs for 9.0
  docs/reference/libbeat/upgrading.md
Labels: Team:Docs, backport-9.0

#43409 bump elastic-agent-system-metrics
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#43381 [Flaky test] Disable flaky zookeeper tests
  metricbeat/module/zookeeper/test_zookeeper.py
Labels: flaky-test, Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, backport-active-all

#43001 Package fips beats
  .buildkite/packaging.pipeline.yml
  .buildkite/scripts/packaging/packaging.sh
  .buildkite/x-pack/pipeline.xpack.agentbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  dev-tools/mage/build.go
  dev-tools/mage/crossbuild.go
  dev-tools/mage/fips-settings.yaml
  dev-tools/mage/pkg.go
  dev-tools/mage/pkgspecs.go
  dev-tools/mage/pkgtypes.go
  dev-tools/mage/settings.go
  dev-tools/packaging/package_test.go
  dev-tools/packaging/packages.yml
  x-pack/agentbeat/dev-tools/packaging/packages.yml
  x-pack/agentbeat/magefile.go
  x-pack/dockerlogbeat/magefile.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, backport-8.x

#43402 Fix flaky logstash output test
  libbeat/outputs/logstash/deadlock.go
  libbeat/outputs/logstash/deadlock_test.go
Labels: flaky-test, Team:Elastic-Agent-Data-Plane, backport-active-all

#43394 [Cleanup] Remove unused python test tags decorator
  libbeat/tests/system/beat/tags.py
Labels: cleanup, Team:Elastic-Agent-Data-Plane

#43453 Add more complete failure logs to python tests
  libbeat/tests/system/beat/beat.py
Labels: flaky-test, cleanup, Team:Elastic-Agent-Data-Plane, backport-active-all

#43313 Update CODEOWNERS
  .github/CODEOWNERS
Labels: needs_team, backport-skip

#42624 [Filestream] Expand take-over mode for Filestream inputs and support dynamic inputs
  CHANGELOG.next.asciidoc
  docs/reference/filebeat/_debugging_on_kibana.md
  docs/reference/filebeat/_if_something_went_wrong.md
  docs/reference/filebeat/_step_1_set_an_identifier_for_each_filestream_input.md
  docs/reference/filebeat/_step_2_enable_the_take_over_mode.md
  docs/reference/filebeat/_step_3_use_new_option_names.md
  docs/reference/filebeat/_step_4.md
  docs/reference/filebeat/filebeat-input-filestream.md
  docs/reference/toc.yml
  filebeat/_meta/config/filebeat.inputs.reference.yml.tmpl
  filebeat/backup/backup.go
  filebeat/backup/files.go
  filebeat/backup/files_test.go
  filebeat/backup/registry.go
  filebeat/backup/registry_test.go
  filebeat/beater/filebeat.go
  filebeat/filebeat.reference.yml
  filebeat/input/filestream/config.go
  filebeat/input/filestream/config_test.go
  filebeat/input/filestream/input.go
  filebeat/input/filestream/input_test.go
  filebeat/input/filestream/internal/input-logfile/input.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/filestream/internal/input-logfile/manager_test.go
  filebeat/input/filestream/internal/input-logfile/prospector.go
  filebeat/input/filestream/internal/input-logfile/store.go
  filebeat/input/filestream/internal/input-logfile/store_test.go
  filebeat/input/filestream/prospector.go
  filebeat/input/filestream/prospector_creator.go
  filebeat/input/filestream/prospector_test.go
  filebeat/input/filestream/takeover/config.go
  filebeat/input/filestream/takeover/takeover.go
  filebeat/input/filestream/takeover/takeover_test.go
  filebeat/tests/integration/filestream_test.go
  filebeat/tests/integration/filestream_truncation_test.go
  filebeat/tests/integration/testdata/take-over/01.log
  filebeat/tests/integration/testdata/take-over/01.txt
  filebeat/tests/integration/testdata/take-over/02.log
  filebeat/tests/integration/testdata/take-over/02.txt
  filebeat/tests/integration/testdata/take-over/expected-registry-happy-path-log-input.json
  filebeat/tests/integration/testdata/take-over/expected-registry-happy-path.json
  filebeat/tests/integration/testdata/take-over/happy-path-log-input.yml
  filebeat/tests/integration/testdata/take-over/happy-path.yml
  filebeat/tests/system/test_input.py
  libbeat/tests/integration/framework.go
  x-pack/filebeat/filebeat.reference.yml
Labels: macOS, backport-skip, Team:Elastic-Agent-Data-Plane, windows-11

#43386 Add missing install steps
  docs/docset.yml
  docs/reference/auditbeat/auditbeat-installation-configuration.md
  docs/reference/auditbeat/running-on-docker.md
  docs/reference/auditbeat/setup-repositories.md
  docs/reference/filebeat/filebeat-installation-configuration.md
  docs/reference/filebeat/running-on-docker.md
  docs/reference/filebeat/setup-repositories.md
  docs/reference/heartbeat/heartbeat-installation-configuration.md
  docs/reference/heartbeat/running-on-docker.md
  docs/reference/heartbeat/setup-repositories.md
  docs/reference/metricbeat/metricbeat-installation-configuration.md
  docs/reference/metricbeat/running-on-docker.md
  docs/reference/metricbeat/setup-repositories.md
  docs/reference/packetbeat/packetbeat-installation-configuration.md
  docs/reference/packetbeat/running-on-docker.md
  docs/reference/packetbeat/setup-repositories.md
  docs/reference/winlogbeat/winlogbeat-installation-configuration.md
Labels: Team:Docs, Team:Elastic-Agent-Data-Plane, backport-9.0

#42959 Remove direct dependency on Azure/go-autorest/autorest/adal
  CHANGELOG-developer.next.asciidoc
  NOTICE.txt
  go.mod
  x-pack/filebeat/input/o365audit/auth/auth.go
  x-pack/filebeat/input/o365audit/auth/cert.go
  x-pack/filebeat/input/o365audit/auth/secret.go
  x-pack/filebeat/input/o365audit/config.go
  x-pack/filebeat/input/o365audit/contentblob.go
  x-pack/filebeat/input/o365audit/input.go
  x-pack/filebeat/input/o365audit/listblobs.go
  x-pack/filebeat/input/o365audit/poll/poll.go
Labels: cleanup, Team:Security-Service Integrations, backport-8.x, backport-9.0

#43356 [Chore][libbeat] Replace global logger with single logger instance
  NOTICE.txt
  filebeat/tests/integration/filebeat_test.go
  go.mod
  go.sum
  libbeat/api/server.go
  libbeat/api/server_test.go
  libbeat/beat/info.go
  libbeat/cmd/instance/beat.go
  libbeat/cmd/instance/beat_reexec_other.go
  libbeat/cmd/instance/beat_test.go
  libbeat/cmd/instance/locks/lock.go
  libbeat/cmd/instance/locks/lock_test.go
  libbeat/cmd/test/output.go
  libbeat/idxmgmt/idxmgmt.go
  libbeat/idxmgmt/std_test.go
  libbeat/instrumentation/instrumentation.go
  libbeat/instrumentation/instrumentation_test.go
  libbeat/monitoring/report/elasticsearch/client.go
  libbeat/monitoring/report/elasticsearch/elasticsearch.go
  libbeat/monitoring/report/elasticsearch/elasticsearch_test.go
  libbeat/monitoring/report/log/log.go
  libbeat/monitoring/report/log/log_test.go
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/logstash/logstash_integration_test.go
  x-pack/filebeat/fbreceiver/receiver_test.go
Labels: Team:Elastic-Agent-Data-Plane

#43506 Remove incorrect entry from 8.17.2 changelog
  CHANGELOG.asciidoc
Labels: Team:Docs, backport-skip

#43369 x-pack/filebeat/input/awss3: allow a grace time on shutdown
  CHANGELOG.next.asciidoc
  docs/reference/filebeat/filebeat-input-aws-s3.md
  x-pack/filebeat/input/awss3/config.go
  x-pack/filebeat/input/awss3/config_test.go
  x-pack/filebeat/input/awss3/sqs_input.go
  x-pack/filebeat/input/awss3/sqs_test.go
Labels: enhancement, Filebeat, Team:obs-ds-hosted-services, Team:Security-Service Integrations, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#43512 Doc: Update links to logstash plugins
  docs/docset.yml
  docs/reference/auditbeat/auditbeat-geoip.md
  docs/reference/auditbeat/configuring-ssl-logstash.md
  docs/reference/auditbeat/connection-problem.md
  docs/reference/auditbeat/logstash-output.md
  docs/reference/auditbeat/redis-output.md
  docs/reference/auditbeat/ssl-client-fails.md
  docs/reference/filebeat/configuring-ssl-logstash.md
  docs/reference/filebeat/connection-problem.md
  docs/reference/filebeat/filebeat-deduplication.md
  docs/reference/filebeat/filebeat-geoip.md
  docs/reference/filebeat/filebeat-input-netflow.md
  docs/reference/filebeat/logstash-output.md
  docs/reference/filebeat/multiline-examples.md
  docs/reference/filebeat/redis-output.md
  docs/reference/filebeat/ssl-client-fails.md
  docs/reference/heartbeat/configuring-ssl-logstash.md
  docs/reference/heartbeat/connection-problem.md
  docs/reference/heartbeat/heartbeat-geoip.md
  docs/reference/heartbeat/logstash-output.md
  docs/reference/heartbeat/redis-output.md
  docs/reference/heartbeat/ssl-client-fails.md
  docs/reference/metricbeat/configuring-ssl-logstash.md
  docs/reference/metricbeat/connection-problem.md
  docs/reference/metricbeat/logstash-output.md
  docs/reference/metricbeat/metricbeat-geoip.md
  docs/reference/metricbeat/metricbeat-module-http.md
  docs/reference/metricbeat/redis-output.md
  docs/reference/metricbeat/ssl-client-fails.md
  docs/reference/packetbeat/configuring-ssl-logstash.md
  docs/reference/packetbeat/connection-problem.md
  docs/reference/packetbeat/logstash-output.md
  docs/reference/packetbeat/packetbeat-geoip.md
  docs/reference/packetbeat/redis-output.md
  docs/reference/packetbeat/ssl-client-fails.md
  docs/reference/winlogbeat/configuring-ssl-logstash.md
  docs/reference/winlogbeat/connection-problem.md
  docs/reference/winlogbeat/logstash-output.md
  docs/reference/winlogbeat/redis-output.md
  docs/reference/winlogbeat/ssl-client-fails.md
  docs/reference/winlogbeat/winlogbeat-geoip.md
Labels: docs, Team:Elastic-Agent-Data-Plane, backport-9.0

#43513 Migrate the 'test' and 'unit' root make targets to mage
  Makefile
  magefile.go
Labels: Team:Elastic-Agent-Data-Plane

#43284 Set server ja3s
  CHANGELOG.next.asciidoc
  packetbeat/protos/tls/tls.go
  packetbeat/protos/tls/tls_test.go
  packetbeat/tests/system/golden/established_tls-expected.json
  packetbeat/tests/system/golden/tls_1_3-expected.json
  packetbeat/tests/system/golden/tls_all_options-expected.json
  packetbeat/tests/system/golden/tls_no_certs-expected.json
  packetbeat/tests/system/golden/tls_not_detailed-expected.json
Labels: enhancement, Packetbeat, Team:Security-Linux Platform, backport-8.x, backport-8.16, backport-8.17, backport-8.18, backport-9.0

#43514 Auditbeat: GH action for macOS 13/14/15 unit tests
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .github/actions/unit-test/action.yml
  .github/workflows/auditbeat-macos-unit-tests.yml
Labels: ci, Team:Obs-InfraObs, backport-active-8, backport-active-9

#43515 Filebeat: GH action for macOS 13/14/15 unit tests
  .buildkite/filebeat/filebeat-pipeline.yml
  .github/workflows/filebeat-macos-unit-tests.yml
Labels: ci, Team:Obs-InfraObs, backport-active-8, backport-active-9

#43521 Heartbeat: GH action for macOS 13/14/15 unit tests
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .github/workflows/heartbeat-macos-unit-tests.yml
Labels: ci, Team:Obs-InfraObs, backport-active-8, backport-active-9

#43499 x-pack/filebeat/docs/inputs/cel: document resource.proxy_url and upda…
  x-pack/filebeat/docs/inputs/input-cel.asciidoc
Labels: docs, Filebeat, Team:Security-Service Integrations, backport-8.17, backport-8.18

#43362 updatecli: remove .golangci.yml from bump-golang.yml
  .github/workflows/updatecli.d/bump-golang.yml
Labels: needs_team, backport-8.x

#43522 Packetbeat: GH action for macOS 13/14/15 unit tests
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .github/workflows/packetbeat-macos-unit-tests.yml
Labels: ci, Team:Obs-InfraObs, backport-active-8, backport-active-9

#43535 dependabot: add github composite actions
  .github/dependabot.yml
Labels: Team:Automation, backport-skip

#43523 x-pack/auditbeat: GH action for macOS 13/14/15 unit tests
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .github/workflows/xpack-auditbeat-macos-unit-tests.yml
Labels: ci, Team:Obs-InfraObs, backport-active-8, backport-active-9

#43560 x-pack/filebeat/input/streaming: add debug logging for stream refresh and requests
  x-pack/filebeat/input/streaming/crowdstrike.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#43602 [Flaky Test] Fix metricbeat/module/system/process TestFetchDegradeOnPartial
  metricbeat/module/system/process/process_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-active-all

#43485 [meraki] Use `GetOrganizationWirelessDevicesChannelUtilizationByDevice` for channel utilization data
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/module/meraki/device_health/device_health.go
  x-pack/metricbeat/module/meraki/device_health/device_health_test.go
  x-pack/metricbeat/module/meraki/device_health/devices.go
Labels: Team:Obs-InfraObs, backport-8.17
