Repository elastic/beats, pull requests merged in 2025-04, with the labels that each got.

#43527 x-pack/osquesrybeat: GH action for macOS 13/14/15 unit tests
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
  .github/workflows/xpack-osquerybeat-macos-unit-tests.yml
Labels: ci, Team:Obs-InfraObs, backport-active-8, backport-active-9

#43619 xpack/auditbeat: update push paths
  .github/workflows/xpack-auditbeat-macos-unit-tests.yml
Labels: ci, backport-skip, Team:Obs-InfraObs

#43528 x-pack/packetbeat: GH action for macOS 13/14/15 unit tests
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
  .github/workflows/xpack-packetbeat-macos-unit-tests.yml
Labels: ci, Team:Obs-InfraObs, backport-active-8, backport-active-9

#43642 [metricbeat][vsphere] update list of supported vSphere versions
  CHANGELOG.next.asciidoc
  metricbeat/module/vsphere/_meta/docs.asciidoc
Labels: Team:Obs-InfraObs

#43653 chore: bump golang.org/x/net to v0.38.0
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.18, backport-9.0

#43661 chore: bump github.com/golang-jwt/jwt/v5 to v5.2.2
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#43672 [Flaky test] Increase timeout on flaky SQS test
  x-pack/filebeat/input/awss3/sqs_test.go
Labels: flaky-test, Team:obs-ds-hosted-services, Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#43683 Restore maintainer label to container images
  CHANGELOG.next.asciidoc
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
Labels: Team:Elastic-Agent-Data-Plane, backport-8.17, backport-active-all

#43665 [metricbeat][windows/service] - Don't affect data collection for other services if single service fails
  CHANGELOG.next.asciidoc
  metricbeat/module/windows/service/reader.go
  metricbeat/module/windows/service/reader_test.go
  metricbeat/module/windows/service/service.go
  metricbeat/module/windows/service/service_status.go
  metricbeat/module/windows/service/service_status_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, Team:Security-Windows Platform, backport-active-all

#43620 Update elastic-agent-libs to `v0.19.0`
  .github/workflows/golangci-lint.yml
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Data-Plane, backport-active-all

#43676 Allow agentbeat to be importable
  x-pack/agentbeat/cmd/cmd.go
  x-pack/agentbeat/cmd/prepare_root_command.go
  x-pack/agentbeat/cmd/prepare_root_command_fips.go
  x-pack/agentbeat/main.go
  x-pack/agentbeat/main_test.go
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#43637 Added omitempty on new elasticsearch package fields
  CHANGELOG.next.asciidoc
  metricbeat/module/elasticsearch/index/_meta/test/settings.8.17.0.json
  metricbeat/module/elasticsearch/index/data.go
Labels: bug, Team:Monitoring, backport-active-all

#43520 Metricbeat: GH action for macOS 13/14/15 unit tests
  .buildkite/metricbeat/pipeline.yml
  .github/workflows/metricbeat-macos-unit-tests.yml
Labels: ci, Team:Obs-InfraObs, backport-active-8, backport-active-9

#43727 [windows/service] Fix integration test
  metricbeat/module/windows/service/service_integration_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-active-all

#43526 x-pack/metricbeat: GH action for macOS 13/14/15 unit tests
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .github/workflows/xpack-metricbeat-macos-unit-tests.yml
Labels: ci, Team:Obs-InfraObs, backport-active-8, backport-active-9

#43666 Delete macOS weekly pipeline
  .buildkite/macos-tests-pipeline.yml
  catalog-info.yaml
Labels: ci, backport-skip, Team:Obs-InfraObs

#43611 Enable unit tests with -tags=requirefips
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  auditbeat/module/file_integrity/file_parsers_fips_test.go
  auditbeat/module/file_integrity/file_parsers_nofips_test.go
  auditbeat/module/file_integrity/scanner_fips_test.go
  auditbeat/module/file_integrity/scanner_nofips_test.go
  auditbeat/module/file_integrity/scanner_test.go
  dev-tools/mage/gotest.go
  filebeat/testing/integration/sample_test.go
  libbeat/otelbeat/oteltranslate/tls_otel_fips_test.go
  libbeat/otelbeat/oteltranslate/tls_otel_nofips_test.go
  libbeat/otelbeat/oteltranslate/tls_otel_test.go
  libbeat/outputs/kafka/config_nofips_test.go
  libbeat/outputs/kafka/config_test.go
  libbeat/processors/communityid/communityid.go
  libbeat/processors/communityid/communityid_test.go
  x-pack/filebeat/input/netflow/netflow_fips_test.go
  x-pack/filebeat/input/netflow/netflow_nofips_test.go
  x-pack/filebeat/input/netflow/netflow_test.go
Labels: :Testing, release-note:skip, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane, Team:Security-Linux Platform, Team:Security-Deployment and Devices, backport-8.x

#43428 x-pack/metricbeat/module/aws: Use FIPS endpoint when metricbeat is running in FIPS 140-3 mode
  x-pack/metricbeat/module/aws/aws.go
  x-pack/metricbeat/module/aws/awshealth/awshealth.go
  x-pack/metricbeat/module/aws/billing/billing.go
  x-pack/metricbeat/module/aws/cloudwatch/cloudwatch.go
Labels: Team:Obs-InfraObs, backport-8.x, backport-9.0

#43774 Fix paths for macOS GH Workflows
  .github/workflows/auditbeat-macos-unit-tests.yml
  .github/workflows/filebeat-macos-unit-tests.yml
  .github/workflows/heartbeat-macos-unit-tests.yml
  .github/workflows/metricbeat-macos-unit-tests.yml
  .github/workflows/packetbeat-macos-unit-tests.yml
  .github/workflows/xpack-auditbeat-macos-unit-tests.yml
  .github/workflows/xpack-filebeat-macos-unit-tests.yml
  .github/workflows/xpack-heartbeat-macos-unit-tests.yml
  .github/workflows/xpack-metricbeat-macos-unit-tests.yml
  .github/workflows/xpack-osquerybeat-macos-unit-tests.yml
  .github/workflows/xpack-packetbeat-macos-unit-tests.yml
Labels: ci, Team:Obs-InfraObs, bugfix, backport-active-8

#43641 Update the `log` to `filestream` migration guide
  docs/reference/filebeat/_debugging_on_kibana.md
  docs/reference/filebeat/_step_1_set_an_identifier_for_each_filestream_input.md
  docs/reference/filebeat/_step_2_enable_the_take_over_mode.md
  docs/reference/filebeat/_step_3_use_new_option_names.md
  docs/reference/filebeat/_step_4.md
  docs/reference/filebeat/configuration-autodiscover-advanced.md
  docs/reference/filebeat/configuration-autodiscover-hints.md
  docs/reference/filebeat/configuration-autodiscover.md
  docs/reference/filebeat/filebeat-input-container.md
  docs/reference/filebeat/filebeat-input-log.md
  docs/reference/filebeat/howto-guides.md
  docs/reference/filebeat/migrate-to-filestream.md
  docs/reference/toc.yml
Labels: docs, Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane, backport-9.0

#43783 Revert "docs: test automation"
  docs/extend/community-beats.md
Labels: needs_team

#43778 CODEOWNERS: change code owner for docs folder
  .github/CODEOWNERS
Labels: Team:Docs, backport-8.x, backport-9.0

#42618 New input metrics API and add per-input metrics to libbeat pipeline client
  CHANGELOG-developer.next.asciidoc
  filebeat/beater/channels.go
  filebeat/beater/filebeat.go
  filebeat/input/filestream/environment_test.go
  filebeat/input/filestream/input_integration_test.go
  filebeat/input/filestream/input_test.go
  filebeat/input/filestream/internal/input-logfile/input.go
  filebeat/input/filestream/internal/input-logfile/manager.go
  filebeat/input/filestream/internal/input-logfile/metrics.go
  filebeat/input/filestream/metrics_integration_test.go
  filebeat/input/filestream/parsers_integration_test.go
  filebeat/input/journald/environment_test.go
  filebeat/input/v2/compat/compat.go
  filebeat/input/v2/compat/compat_test.go
  filebeat/input/v2/input-cursor/input.go
  filebeat/input/v2/input-cursor/manager_test.go
  filebeat/input/v2/input.go
  filebeat/input/winlog/input.go
  libbeat/beat/info.go
  libbeat/beat/pipeline.go
  libbeat/cmd/instance/beat.go
  libbeat/monitoring/inputmon/httphandler.go
  libbeat/monitoring/inputmon/httphandler_test.go
  libbeat/monitoring/inputmon/input.go
  libbeat/monitoring/inputmon/input_test.go
  libbeat/publisher/pipeline/client.go
  libbeat/publisher/pipeline/client_test.go
  libbeat/publisher/pipeline/monitoring.go
  libbeat/publisher/pipeline/pipeline.go
  metricbeat/beater/metricbeat.go
  packetbeat/beater/packetbeat.go
  winlogbeat/beater/winlogbeat.go
  x-pack/filebeat/tests/integration/input_metrics_test.go
  x-pack/filebeat/tests/integration/testdata/input_metrics-no-id.log
  x-pack/filebeat/tests/integration/testdata/input_metrics.log
Labels: Team:obs-ds-hosted-services, macOS, macOSArm, windows-2019, Team:Elastic-Agent-Data-Plane, windows-2022, Team:Security-Linux Platform, Team:Security-Windows Platform, windows-11, backport-active-8

#43805 [docs] Fix metricbeat modules table
  docs/reference/metricbeat/metricbeat-modules.md
Labels: docs, Team:Docs, backport-9.0

#43807 [Disk queue] Don't check the serialization format unless there's a valid handle
  libbeat/publisher/queue/diskqueue/reader_loop.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-active-all

#43789 Improve docs on how to run integration tests
  docs/extend/testing.md
Labels: release-note:skip, Team:Docs, Team:Elastic-Agent-Data-Plane

#43739 [unifiedlogs] Fix unifiedlog stdout reader
  x-pack/filebeat/input/unifiedlogs/input.go
  x-pack/filebeat/input/unifiedlogs/input_test.go
Labels: macOS, macOSArm, Team:Elastic-Agent-Data-Plane, macos-m1, bugfix, Team:Security-Windows Platform, backport-8.x, backport-8.18, backport-active-9

#43771 Add Beats Release Notes for 9.0.0
  docs/docset.yml
  docs/release-notes/breaking-changes.md
  docs/release-notes/index.md
Labels: Team:Docs, backport-9.0

#43825 Collect integration test failures folders for all beats
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/heartbeat/heartbeat-pipeline.yml
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.heartbeat.yml
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  .buildkite/x-pack/pipeline.xpack.osquerybeat.yml
Labels: Team:Elastic-Agent-Data-Plane

#43655 x-pack/filebeat/input/entityanalytics/provider/okta: add support for pagination batch size
  CHANGELOG.next.asciidoc
  docs/reference/filebeat/filebeat-input-entity-analytics.md
  x-pack/filebeat/input/entityanalytics/provider/okta/conf.go
  x-pack/filebeat/input/entityanalytics/provider/okta/okta.go
Labels: enhancement, Filebeat, Team:Elastic-Agent-Data-Plane, Team:Security-Service Integrations, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#43837 Fix typo in "store/set" operation name
  libbeat/statestore/store.go
Labels: bug, release-note:skip, Team:Elastic-Agent-Data-Plane, backport-active-all

#43834 [Flaky Test] oteltest.CheckReceivers increase timeout
  libbeat/otelbeat/oteltest/oteltest.go
  x-pack/filebeat/fbreceiver/receiver_test.go
Labels: Team:Elastic-Agent-Data-Plane

#43846 [docs] Update mapped_pages
  docs/reference/filebeat/file-identity.md
  docs/reference/filebeat/filebeat-input-unifiedlogs.md
  docs/reference/metricbeat/_metricsets_70.md
  docs/reference/metricbeat/exported-fields-benchmark.md
  docs/reference/metricbeat/exported-fields-openai.md
  docs/reference/metricbeat/metricbeat-metricset-benchmark-info.md
  docs/reference/metricbeat/metricbeat-metricset-openai-usage.md
  docs/reference/metricbeat/metricbeat-metricset-windows-wmi.md
  docs/reference/metricbeat/metricbeat-module-benchmark.md
  docs/reference/metricbeat/metricbeat-module-openai.md
  docs/release-notes/index.md
Labels: docs, Team:Docs, backport-9.0

#43863 Clarify support of Podman (8.x docs)
  metricbeat/docs/modules/docker.asciidoc
  metricbeat/module/docker/_meta/docs.asciidoc
Labels: Team:Docs, backport-8.17, backport-8.18

#43836 [docs] Update APM, Synthetics, Uptime links
  docs/reference/auditbeat/auditbeat-installation-configuration.md
  docs/reference/auditbeat/configuration-instrumentation.md
  docs/reference/filebeat/configuration-instrumentation.md
  docs/reference/filebeat/filebeat-installation-configuration.md
  docs/reference/heartbeat/configuration-heartbeat-options.md
  docs/reference/heartbeat/configuration-instrumentation.md
  docs/reference/heartbeat/heartbeat-installation-configuration.md
  docs/reference/libbeat/upgrading.md
  docs/reference/metricbeat/configuration-instrumentation.md
  docs/reference/metricbeat/metricbeat-installation-configuration.md
  docs/reference/packetbeat/configuration-instrumentation.md
  docs/reference/packetbeat/packetbeat-installation-configuration.md
  docs/reference/winlogbeat/configuration-instrumentation.md
  docs/reference/winlogbeat/winlogbeat-installation-configuration.md
Labels: docs, Team:Docs, backport-9.0

#43800 [mbreceiver][fbreceiver] - use logp.DefaultConfig
  NOTICE.txt
  go.mod
  go.sum
  libbeat/cmd/instance/beat.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-9.0

#43855 mod,x-pack/filebeat/input/cel: bump mito version to v1.18.0
  CHANGELOG.next.asciidoc
  NOTICE.txt
  docs/reference/filebeat/filebeat-input-cel.md
  go.mod
  go.sum
  x-pack/filebeat/input/cel/config.go
  x-pack/filebeat/input/cel/input.go
  x-pack/filebeat/input/cel/input_test.go
Labels: enhancement, Filebeat, Team:Security-Service Integrations, backport-8.x, backport-9.0

#43782 Add FIPS check for .deb artifacts
  dev-tools/mage/common.go
  dev-tools/packaging/package_test.go
Labels: enhancement, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent-Data-Plane

#43874 Fix memqueue race condition during shutdown
  libbeat/publisher/queue/memqueue/runloop.go
  libbeat/publisher/queue/memqueue/runloop_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-active-all

#43900 [DOCS] Specifies no deprecations and known issues for 9.0.0
  docs/release-notes/deprecations.md
  docs/release-notes/known-issues.md
Labels: docs, Team:Docs

#43907 Set navigation title for release notes
  docs/release-notes/index.md
Labels: Team:Docs, backport-9.0

#43793 Add buildkite step to run unit tests with GODEBUG=fips140=only
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
  auditbeat/module/file_integrity/exeobjparser_test.go
  dev-tools/mage/gotest.go
  dev-tools/mage/target/unittest/unittest.go
  libbeat/processors/communityid/communityid_test.go
  metricbeat/autodiscover/builder/hints/metrics_test.go
  testing/testutils/skipFIPS140.go
  x-pack/filebeat/input/cel/input_test.go
  x-pack/filebeat/input/http_endpoint/handler_test.go
  x-pack/filebeat/input/httpjson/value_tpl_test.go
  x-pack/filebeat/input/lumberjack/generate_certs_test.go
  x-pack/filebeat/input/streaming/input_test.go
  x-pack/filebeat/module/cisco/ios/pipeline_test.go
  x-pack/libbeat/common/cloudfoundry/cache_test.go
  x-pack/metricbeat/magefile.go
Labels: :Testing, release-note:skip, Team:Security-Linux Platform, Team:Security-Service Integrations, Team:Security-Deployment and Devices

#43711 Fix filebeat module golden files and update elastic stack version for testing
  filebeat/input/filestream/internal/task/group_test.go
  filebeat/module/apache/access/test/test-vhost.log-expected.json
  filebeat/module/apache/access/test/test.log-expected.json
  filebeat/module/apache/access/test/ubuntu-2.2.22.log-expected.json
  filebeat/module/iis/access/test/test-x-forward-for-extended.log-expected.json
  filebeat/module/iis/access/test/test.log-expected.json
  filebeat/module/nginx/access/test/access.log-expected.json
  filebeat/module/nginx/access/test/test-with-host.log-expected.json
  filebeat/module/nginx/access/test/test.log-expected.json
  filebeat/module/nginx/ingress_controller/test/test.log-expected.json
  filebeat/tests/system/test_modules.py
  libbeat/tests/integration/dashboard_test.go
  testing/environments/docker/logstash/pipeline-xpack/default.conf
  testing/environments/docker/logstash/pipeline/default.conf
  testing/environments/snapshot.yml
  x-pack/filebeat/module/aws/cloudtrail/test/console-login-json.log-expected.json
  x-pack/filebeat/module/fortinet/firewall/test/utm.log-expected.json
  x-pack/filebeat/module/gcp/audit/test/audit-log-entries.json.log-expected.json
  x-pack/filebeat/module/o365/audit/test/04-sharepoint.log-expected.json
  x-pack/filebeat/module/o365/audit/test/06-sharepointfileop.log-expected.json
  x-pack/filebeat/module/o365/audit/test/14-sp-sharing-op.log-expected.json
  x-pack/filebeat/module/o365/audit/test/15-azuread-sts-logon.log-expected.json
  x-pack/filebeat/module/o365/audit/test/25-ms-teams-groups.log-expected.json
  x-pack/filebeat/module/okta/system/test/okta-system-test.json.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/firewall.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
Labels: Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, Team:Security-Service Integrations, backport-active-all

#43618 [add_cloud_metadata]Collect cloud.availability_zone for azure
  CHANGELOG.next.asciidoc
  libbeat/processors/add_cloud_metadata/provider_azure_vm.go
  libbeat/processors/add_cloud_metadata/provider_azure_vm_test.go
Labels: Team:obs-ds-hosted-services, backport-active-8, backport-active-9

#43911 Add better GOPROXY fallback to docker-based tests
  dev-tools/mage/integtest_docker.go
Labels: needs_team

#43925 Revert "[8.x](backport #43711) Fix filebeat module golden files and update elastic stack version for testing"
  filebeat/input/filestream/internal/task/group_test.go
  filebeat/module/apache/access/test/test-vhost.log-expected.json
  filebeat/module/apache/access/test/test.log-expected.json
  filebeat/module/apache/access/test/ubuntu-2.2.22.log-expected.json
  filebeat/module/iis/access/test/test-x-forward-for-extended.log-expected.json
  filebeat/module/iis/access/test/test.log-expected.json
  filebeat/module/nginx/access/test/access.log-expected.json
  filebeat/module/nginx/access/test/test-with-host.log-expected.json
  filebeat/module/nginx/access/test/test.log-expected.json
  filebeat/module/nginx/ingress_controller/test/test.log-expected.json
  filebeat/tests/system/test_modules.py
  libbeat/tests/integration/dashboard_test.go
  testing/environments/docker/logstash/pipeline-xpack/default.conf
  testing/environments/docker/logstash/pipeline/default.conf
  testing/environments/snapshot.yml
  x-pack/filebeat/module/aws/cloudtrail/test/console-login-json.log-expected.json
  x-pack/filebeat/module/fortinet/firewall/test/utm.log-expected.json
  x-pack/filebeat/module/gcp/audit/test/audit-log-entries.json.log-expected.json
  x-pack/filebeat/module/o365/audit/test/04-sharepoint.log-expected.json
  x-pack/filebeat/module/o365/audit/test/06-sharepointfileop.log-expected.json
  x-pack/filebeat/module/o365/audit/test/14-sp-sharing-op.log-expected.json
  x-pack/filebeat/module/o365/audit/test/15-azuread-sts-logon.log-expected.json
  x-pack/filebeat/module/o365/audit/test/25-ms-teams-groups.log-expected.json
  x-pack/filebeat/module/okta/system/test/okta-system-test.json.log-expected.json
  x-pack/filebeat/module/sophos/xg/test/firewall.log-expected.json
  x-pack/filebeat/module/suricata/eve/test/eve-small.log-expected.json
Labels: Team:Elastic-Agent-Data-Plane

#43639 bump github.com/elastic/elastic-agent-system-metrics
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#43886 filebeat: input/v2: NewPipelineClientListener reuses existing metrics
  filebeat/input/v2/input.go
  filebeat/input/v2/input_test.go
Labels: bug, Team:Elastic-Agent-Data-Plane

#43073 Execute Go integration tests sequentially within a beat module
  dev-tools/mage/gotest.go
  metricbeat/module/kafka/broker/broker_integration_test.go
  metricbeat/module/kafka/consumer/consumer_integration_test.go
  metricbeat/module/kafka/consumergroup/consumergroup_integration_test.go
  metricbeat/module/kafka/partition/partition_integration_test.go
  metricbeat/module/kafka/producer/producer_integration_test.go
  x-pack/metricbeat/module/sql/query/query_integration_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-active-all

#43833 mergify: new way of backporting to active branches
  .github/workflows/backport-active.yml
  .mergify.yml
Labels: enhancement, skip-ci, backport-skip, Team:Elastic-Agent-Data-Plane, backport-active-9

#43830 [Flaky Test] skip x-pack/filebeat/input/netflow TestNetFlow/ipfix_cisco.reversed
  x-pack/filebeat/input/netflow/netflow_test.go
Labels: flaky-test, Team:Elastic-Agent-Data-Plane, Team:Security-Deployment and Devices, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#43929 Add fipsonly test step for metricbeat
  .buildkite/metricbeat/pipeline.yml
  metricbeat/magefile.go
Labels: :Testing, needs_team, release-note:skip

#43840 Add FIPS indicator to startup and version command
  libbeat/beat/info.go
  libbeat/cmd/instance/beat.go
  libbeat/cmd/version.go
  libbeat/version/fips.go
  libbeat/version/nofips.go
Labels: enhancement, release-note:skip, Team:Elastic-Agent-Control-Plane, backport-8.x

#43962 Rename buildkite test step to avoid confusion
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/filebeat/filebeat-pipeline.yml
  .buildkite/libbeat/pipeline.libbeat.yml
  .buildkite/metricbeat/pipeline.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.filebeat.yml
  .buildkite/x-pack/pipeline.xpack.libbeat.yml
  .buildkite/x-pack/pipeline.xpack.metricbeat.yml
Labels: technical debt, needs_team, release-note:skip, backport-8.x

#43950 [Chore] Use logptest.NewTestingLogger
  NOTICE.txt
  filebeat/autodiscover/builder/hints/logs_test.go
  filebeat/fileset/modules_test.go
  filebeat/input/inputtest/input.go
  filebeat/input/log/input_test.go
  filebeat/input/mqtt/input_test.go
  filebeat/input/mqtt/mqtt_integration_test.go
  filebeat/input/redis/redis_integration_test.go
  go.mod
  go.sum
  libbeat/api/server_test.go
  libbeat/autodiscover/autodiscover_test.go
  libbeat/cfgfile/glob_manager_test.go
  libbeat/cfgfile/glob_watcher_test.go
  libbeat/cfgfile/list_test.go
  libbeat/cmd/instance/beat_test.go
  libbeat/cmd/instance/locks/lock_test.go
  libbeat/idxmgmt/std_test.go
  libbeat/instrumentation/instrumentation_test.go
  libbeat/monitoring/report/elasticsearch/elasticsearch_test.go
  libbeat/monitoring/report/log/log_test.go
  libbeat/outputs/console/console_test.go
  libbeat/outputs/elasticsearch/bulk_test.go
  libbeat/outputs/elasticsearch/client_integration_test.go
  libbeat/outputs/elasticsearch/client_proxy_test.go
  libbeat/outputs/elasticsearch/client_test.go
  libbeat/outputs/kafka/config_test.go
  libbeat/outputs/kafka/kafka_integration_test.go
  libbeat/outputs/kafka/partition_test.go
  libbeat/outputs/logstash/deadlock_test.go
  libbeat/outputs/logstash/logstash_integration_test.go
  libbeat/outputs/logstash/logstash_test.go
  libbeat/outputs/otelconsumer/otelconsumer_test.go
  libbeat/outputs/redis/redis_integration_test.go
  libbeat/outputs/redis/redis_test.go
  libbeat/processors/actions/append_test.go
  libbeat/processors/actions/copy_fields_test.go
  libbeat/processors/actions/decode_base64_field_test.go
  libbeat/publisher/pipeline/client_test.go
  libbeat/publisher/pipeline/consumer_test.go
  libbeat/publisher/pipeline/controller_test.go
  libbeat/publisher/pipeline/stress/stress_test.go
  libbeat/publisher/queue/diskqueue/acks_test.go
  libbeat/publisher/queue/diskqueue/core_loop_test.go
  libbeat/publisher/queue/diskqueue/queue_test.go
  libbeat/publisher/queue/memqueue/runloop_test.go
  libbeat/statestore/backend/memlog/memlog_test.go
  libbeat/statestore/backend/memlog/store_test.go
  libbeat/template/load_integration_test.go
  libbeat/template/load_test.go
  metricbeat/module/windows/service/reader_test.go
  metricbeat/module/windows/service/service_integration_test.go
  metricbeat/module/windows/service/service_status_test.go
  x-pack/filebeat/input/cometd/cometd_integration_test.go
  x-pack/filebeat/input/cometd/input_test.go
  x-pack/filebeat/input/gcppubsub/pubsub_test.go
  x-pack/libbeat/common/cloudfoundry/cache_test.go
  x-pack/libbeat/persistentcache/persistentcache_test.go
  x-pack/libbeat/persistentcache/store_test.go
Labels: Team:Elastic-Agent-Data-Plane

#43449 Add retry logic for vSphere client Logout operation
  CHANGELOG-developer.next.asciidoc
  metricbeat/module/vsphere/client/logout.go
  metricbeat/module/vsphere/client/logout_test.go
  metricbeat/module/vsphere/client/mock_logout.go
  metricbeat/module/vsphere/client/retry.go
  metricbeat/module/vsphere/cluster/cluster.go
  metricbeat/module/vsphere/datastore/datastore.go
  metricbeat/module/vsphere/datastorecluster/datastorecluster.go
  metricbeat/module/vsphere/host/host.go
  metricbeat/module/vsphere/network/network.go
  metricbeat/module/vsphere/resourcepool/resourcepool.go
  metricbeat/module/vsphere/virtualmachine/virtualmachine.go
Labels: bug, Team:Obs-InfraObs, backport-8.x, backport-8.17, backport-8.18, backport-9.0

#43858 Increase time until close for unifiedlogs test
  x-pack/filebeat/input/unifiedlogs/input_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x, backport-8.18, backport-active-9

#43769 [azure-eventhub] Bump sdk/messaging/azeventhubs to 1.3.1
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:obs-ds-hosted-services, bugfix, input:azure-eventhub, backport-active-all

#44004 Relocate the fingerprint identity explainer image
  docs/reference/filebeat/file-identity.md
  docs/reference/filebeat/images/fingerprint-file-identity.png
Labels: docs, Team:Elastic-Agent-Data-Plane, backport-9.0

#43953 mergify: support 8.19 and remove support 8.x
  .mergify.yml
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#44005 Update filebeat-input-journald.md
  docs/reference/filebeat/filebeat-input-journald.md
Labels: Team:Elastic-Agent-Data-Plane, backport-active-all

#43936 Rename FIPS-compliant to FIPS-capable
  dev-tools/mage/pkg.go
  x-pack/agentbeat/magefile.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.x

#43231 [otelbeat] utilise upstream logic to convert beat.Event to plog.Log
  libbeat/otelbeat/otelmap/otelmap.go
  libbeat/otelbeat/otelmap/otelmap_test.go
  libbeat/outputs/otelconsumer/benchmark_test.go
  libbeat/outputs/otelconsumer/otelconsumer.go
Labels: Team:Elastic-Agent-Data-Plane, backport-9.0, backport-8.19

#43888 [chore][BeatReceiver]: create a BeatReceiver in libbeat
  libbeat/otelbeat/beatreceiver/beat_receiver.go
  x-pack/filebeat/fbreceiver/factory.go
  x-pack/filebeat/fbreceiver/receiver.go
  x-pack/filebeat/tests/integration/otel_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-9.0, backport-8.19

#44024 Update APT and YUM docs with correct artifacts path
  docs/docset.yml
  docs/reference/auditbeat/setup-repositories.md
  docs/reference/filebeat/setup-repositories.md
  docs/reference/heartbeat/setup-repositories.md
  docs/reference/metricbeat/setup-repositories.md
  docs/reference/packetbeat/setup-repositories.md
Labels: Team:Docs, backport-9.0

#44031 Use encoded api key on es-exporter config
  libbeat/otelbeat/beatconverter/beatconverter_test.go
  libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel.go
  libbeat/otelbeat/oteltranslate/outputs/elasticsearch/config_otel_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-9.0, backport-8.19

#44041 [ci] Add Windows server 2025 to auditbeat and packetbeat CI pipelines
  .buildkite/auditbeat/auditbeat-pipeline.yml
  .buildkite/packetbeat/pipeline.packetbeat.yml
  .buildkite/x-pack/pipeline.xpack.auditbeat.yml
  .buildkite/x-pack/pipeline.xpack.packetbeat.yml
Labels: Packetbeat, Auditbeat, ci, Team:Security-Linux Platform, backport-active-8, backport-active-9

#43559 otelconsumer: set log record observed timestamp
  libbeat/outputs/otelconsumer/otelconsumer.go
  libbeat/outputs/otelconsumer/otelconsumer_test.go
Labels: cleanup, Team:Elastic-Agent-Data-Plane, backport-9.0, backport-8.19

#44052 catalog-info: add missing scheduler id and validate catalog in the CI
  .buildkite/pipeline.yml
  catalog-info.yaml
Labels: needs_team, backport-skip

#44053 Add a note that `api_key` and `cloud.auth` are not related
  docs/reference/auditbeat/configure-cloud-id.md
  docs/reference/filebeat/configure-cloud-id.md
  docs/reference/heartbeat/configure-cloud-id.md
  docs/reference/metricbeat/configure-cloud-id.md
  docs/reference/packetbeat/configure-cloud-id.md
  docs/reference/winlogbeat/configure-cloud-id.md
Labels: docs, Team:Elastic-Agent-Data-Plane, backport-9.0

#44057 add testing logger to perfmon_test.go
  metricbeat/module/windows/perfmon/perfmon_test.go
  metricbeat/module/windows/perfmon/reader_integration_test.go
Labels: Team:Elastic-Agent-Data-Plane

#44042 Add ws2025 known issue and workaround
  docs/release-notes/known-issues.md
  winlogbeat/eventlog/config.go
  winlogbeat/eventlog/wineventlog.go
  winlogbeat/eventlog/wineventlog_test.go
Labels: docs, Winlogbeat, Team:Security-Windows Platform, backport-active-8, backport-active-9

#43999 Check ch for nil in libbeat/publisher/queue/memqueue /broker.go pop()
  libbeat/publisher/queue/memqueue/broker.go
Labels: Team:Elastic-Agent-Data-Plane, bugfix, backport-8.17, backport-8.18, backport-9.0, backport-8.19

#44056 Install systemd on Filebeat Docker images
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
  docs/reference/filebeat/filebeat-input-journald.md
  docs/release-notes/index.md
Labels: Team:Elastic-Agent-Data-Plane, bugfix, backport-active-all

#44037 enable internal http monitoring for metricbeat receiver
  x-pack/filebeat/fbreceiver/factory.go
  x-pack/metricbeat/mbreceiver/factory.go
  x-pack/metricbeat/mbreceiver/receiver.go
  x-pack/metricbeat/mbreceiver/receiver_test.go
Labels: Team:Elastic-Agent-Data-Plane, backport-9.0, backport-8.19

#44071 Filestream integration test improvements
  filebeat/input/filestream/environment_test.go
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#44068 [filebeat][streaming] - Fixed websocket input panic on sudden network error or server crash
  CHANGELOG.next.asciidoc
  x-pack/filebeat/input/streaming/websocket.go
Labels: Filebeat, bugfix, Team:Security-Service Integrations, input:streaming, backport-8.17, backport-8.18, backport-9.0, backport-8.19

#44051 Log the reader closed message at a lower level
  CHANGELOG.next.asciidoc
  filebeat/input/filestream/input.go
Labels: Team:Elastic-Agent-Data-Plane, backport-8.18, backport-9.0, backport-8.19

#43743 github-actions(updatecli): use oblt-actions, pin version and avoid diverging PRs
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-golang.yml
  .github/workflows/updatecli-compose.yml
  .github/workflows/updatecli.d/bump-elastic-stack-snapshot.yml
  .github/workflows/updatecli.d/bump-golang-7.17.yml
  .github/workflows/updatecli.d/bump-golang.yml
  .mergify.yml
  .tool-versions
Labels: needs_team, backport-7.17, backport-8.x

#44108 Remove systemd from the Wolfi image
  dev-tools/packaging/templates/docker/Dockerfile.tmpl
  docs/reference/filebeat/filebeat-input-journald.md
  docs/release-notes/index.md
Labels: Team:Elastic-Agent-Data-Plane, backport-active-all

#42953 mergify: update rules
  .mergify.yml
Labels: needs_team, backport-skip

#43518 [gcp] Add `dataproc` metadata collector
  CHANGELOG.next.asciidoc
  x-pack/metricbeat/metricbeat.reference.yml
  x-pack/metricbeat/module/gcp/_meta/config.yml
  x-pack/metricbeat/module/gcp/_meta/docs.asciidoc
  x-pack/metricbeat/module/gcp/dataproc/_meta/data.json
  x-pack/metricbeat/module/gcp/metrics/dataproc/metadata.go
  x-pack/metricbeat/module/gcp/metrics/dataproc/metadata_test.go
  x-pack/metricbeat/module/gcp/metrics/metadata_services.go
  x-pack/metricbeat/module/gcp/metrics/metricset.go
  x-pack/metricbeat/modules.d/gcp.yml.disabled
Labels: enhancement, Team:Elastic-Agent-Data-Plane, Team:Obs-InfraObs, backport-8.x

#44131 [libbeat/logging] fix a breaking bug
  libbeat/cmd/instance/beat.go
Labels: bug, impact:critical, Team:Elastic-Agent-Data-Plane
